# Evaluation on DeepSeek-LLM-7B using CounterBench for reasoning tasks

In [1]:
!pip install bitsandbytes

Collecting bitsandbytes
  Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.9.0+cu126)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.20.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)
Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl (59.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.1/59.1 MB 13.7 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.49.1

In [2]:
import torch
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from sklearn.metrics import classification_report

In [3]:
from huggingface_hub import login
login()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [4]:
model_name = "deepseek-ai/deepseek-llm-7b-chat"

In [5]:
bitsandbytes_config = BitsAndBytesConfig(load_in_4bit=True,
                                         bnb_4bit_compute_dtype=torch.float16,
                                         bnb_4bit_quant_type='nf4',
                                         bnb_4bit_use_double_quant=True)

In [6]:
tokenizer = AutoTokenizer.from_pretrained(model_name)
model= AutoModelForCausalLM.from_pretrained(model_name,
                                             quantization_config=bitsandbytes_config,
                                             device_map="auto",
                                             offload_folder="offload")

config.json:   0%|          | 0.00/594 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

pytorch_model.bin.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Loading weights:   0%|          | 0/273 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/181 [00:00<?, ?B/s]

In [7]:
def get_prompt(instruction,questions,contexts):
  prompts=[]
  for i in range(len(questions)):
    prompt = f"{instruction}\nContext:{contexts[i]}\nQuestion:{questions[i]}\nAnswer:"
    prompts.append(prompt)
  return prompts

In [8]:
def training(prompts, num_tokens=1):
    predictions = []
    for i, prompt in enumerate(prompts):
        chat = [
            {"role": "user", "content": prompt}
        ]


        formatted_prompt = tokenizer.apply_chat_template(
            chat,
            tokenize=False,
            add_generation_prompt=True
        )


        inputs = tokenizer(
            formatted_prompt,
            return_tensors="pt",
            padding=True,
            truncation=True
        ).to("cuda")

        with torch.no_grad():
            output_tokens = model.generate(
                **inputs,
                max_new_tokens=num_tokens,
                temperature=0.1,
                do_sample=False,
                pad_token_id=tokenizer.pad_token_id or tokenizer.eos_token_id,
                eos_token_id=tokenizer.eos_token_id,
                repetition_penalty=1.1,
                num_beams=1,
            )

        input_length = inputs["input_ids"].shape[1]
        new_tokens = output_tokens[0][input_length:]

        response = tokenizer.decode(new_tokens, skip_special_tokens=True).strip()

        print(f"Iteration {i}")
        print(f"Model Output: {response}\n")

        predictions.append(response)

    return predictions

In [9]:
ds = load_dataset(
    "json",
    data_files=[
        "hf://datasets/CounterBench/CounterBench/data_balanced_alpha_V1.json",
        "hf://datasets/CounterBench/CounterBench/data_balanced_backdoor_V2.json"
    ]
)

print(ds)
print(ds["train"].features)

data_balanced_alpha_V1.json: 0.00B [00:00, ?B/s]

data_balanced_backdoor_V2.json: 0.00B [00:00, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['question', 'given_info', 'answer', 'type', 'question_id', 'meta'],
        num_rows: 1200
    })
})
{'question': Value('string'), 'given_info': Value('string'), 'answer': Value('string'), 'type': Value('string'), 'question_id': Value('string'), 'meta': {'graph_id': Value('string'), 'model_id': Value('int64'), 'query_type': Value('string'), 'rung': Value('int64'), 'story_id': Value('string')}}

In [10]:
dataset = ds["train"].to_pandas()

In [11]:
dataset

,question,given_info,answer,type,question_id,meta
0,Would Lumbo occur if not Ziklo instead of Ziklo?,"We know that Ziklo causes Blaf, Blaf causes Tr...",no,basic,0,"{'graph_id': 'graph5', 'model_id': 0, 'query_t..."
1,Would Zlim occur if not Glent instead of Glent?,"We know that Glent causes Razz, Razz causes Pe...",no,basic,200,"{'graph_id': 'graph5', 'model_id': 1, 'query_t..."
2,Would Klep occur if not Praf instead of Praf?,"We know that Praf causes Vank, Vank causes Scu...",no,basic,400,"{'graph_id': 'graph5', 'model_id': 2, 'query_t..."
3,Would Jext occur if not Fizo instead of Fizo?,"We know that Fizo causes Blorn, Blorn causes P...",no,basic,600,"{'graph_id': 'graph5', 'model_id': 3, 'query_t..."
4,Would Wrox occur if not Nuv instead of Nuv?,"We know that Nuv causes Splee, Splee causes Bl...",no,basic,800,"{'graph_id': 'graph5', 'model_id': 4, 'query_t..."
...,...,...,...,...,...,...
1195,Would Lumbo occur if not Ziklo instead of Ziklo?,"We know that Blaf causes Ziklo, Blaf causes Tr...",no,backdoor,39,"{'graph_id': 'graph9', 'model_id': 195, 'query..."
1196,Would Zlim occur if not Glent instead of Glent?,"We know that Razz causes Glent, Razz causes Pe...",no,backdoor,239,"{'graph_id': 'graph9', 'model_id': 196, 'query..."
1197,Would Klep occur if not Praf instead of Praf?,"We know that Vank causes Praf, Vank causes Scu...",no,backdoor,439,"{'graph_id': 'graph9', 'model_id': 197, 'query..."
1198,Would Jext occur if not Fizo instead of Fizo?,"We know that Blorn causes Fizo, Blorn causes P...",no,backdoor,639,"{'graph_id': 'graph9', 'model_id': 198, 'query..."
1199,Would Wrox occur if not Nuv instead of Nuv?,"We know that Splee causes Nuv, Splee causes Bl...",no,backdoor,839,"{'graph_id': 'graph9', 'model_id': 199, 'query..."

In [12]:
dataset['type'].value_counts()

type
basic          250
conditional    250
joint          250
nested         250
backdoor       200
Name: count, dtype: int64

In [13]:
instruction = "Instruction: Answer the question strictly using the causal facts provided. Do not introduce any new information. For counterfactuals, simulate the scenario along the causal chain step by step. Only output the final answer as Yes or No. Do not write anything else."

## Basic Questions

In [14]:
dataset_basic = dataset[dataset['type']=="basic"]

In [15]:
dataset_basic

,question,given_info,answer,type,question_id,meta
0,Would Lumbo occur if not Ziklo instead of Ziklo?,"We know that Ziklo causes Blaf, Blaf causes Tr...",no,basic,0,"{'graph_id': 'graph5', 'model_id': 0, 'query_t..."
1,Would Zlim occur if not Glent instead of Glent?,"We know that Glent causes Razz, Razz causes Pe...",no,basic,200,"{'graph_id': 'graph5', 'model_id': 1, 'query_t..."
2,Would Klep occur if not Praf instead of Praf?,"We know that Praf causes Vank, Vank causes Scu...",no,basic,400,"{'graph_id': 'graph5', 'model_id': 2, 'query_t..."
3,Would Jext occur if not Fizo instead of Fizo?,"We know that Fizo causes Blorn, Blorn causes P...",no,basic,600,"{'graph_id': 'graph5', 'model_id': 3, 'query_t..."
4,Would Wrox occur if not Nuv instead of Nuv?,"We know that Nuv causes Splee, Splee causes Bl...",no,basic,800,"{'graph_id': 'graph5', 'model_id': 4, 'query_t..."
...,...,...,...,...,...,...
495,Would Lumbo occur if not Ziklo instead of Ziklo?,"We know that Ziklo causes Blaf and Trune, Trun...",no,basic,99,"{'graph_id': 'graph9', 'model_id': 495, 'query..."
496,Would Zlim occur if not Glent instead of Glent?,"We know that Glent causes Razz and Pex, Pex ca...",no,basic,299,"{'graph_id': 'graph9', 'model_id': 496, 'query..."
497,Would Klep occur if not Praf instead of Praf?,"We know that Praf causes Vank and Scud, Scud c...",no,basic,499,"{'graph_id': 'graph9', 'model_id': 497, 'query..."
498,Would Jext occur if not Fizo instead of Fizo?,"We know that Fizo causes Blorn and Plim, Plim ...",no,basic,699,"{'graph_id': 'graph9', 'model_id': 498, 'query..."
499,Would Wrox occur if not Nuv instead of Nuv?,"We know that Nuv causes Splee and Blen, Blen c...",no,basic,899,"{'graph_id': 'graph9', 'model_id': 499, 'query..."

In [16]:
questions = dataset_basic["question"].values.tolist()
contexts = dataset_basic["given_info"].values.tolist()
true_answers = dataset_basic["answer"].values.tolist()

In [17]:
prompts = get_prompt(instruction,questions,contexts)

In [18]:
prompts[0]

'Instruction: Answer the question strictly using the causal facts provided. Do not introduce any new information. For counterfactuals, simulate the scenario along the causal chain step by step. Only output the final answer as Yes or No. Do not write anything else.\nContext:We know that Ziklo causes Blaf, Blaf causes Trune, Trune causes Vork, and Vork causes Lumbo.\nQuestion:Would Lumbo occur if not Ziklo instead of Ziklo?\nAnswer:'

In [19]:
predictions = training(prompts)

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Iteration 0
Model Output: No

Iteration 1
Model Output: No

Iteration 2
Model Output: No

Iteration 3
Model Output: No

Iteration 4
Model Output: No

Iteration 5
Model Output: No

Iteration 6
Model Output: Yes

Iteration 7
Model Output: No

Iteration 8
Model Output: No

Iteration 9
Model Output: No

Iteration 10
Model Output: Yes

Iteration 11
Model Output: No

Iteration 12
Model Output: No

Iteration 13
Model Output: No

Iteration 14
Model Output: No

Iteration 15
Model Output: Yes

Iteration 16
Model Output: No

Iteration 17
Model Output: No

Iteration 18
Model Output: No

Iteration 19
Model Output: No

Iteration 20
Model Output: Yes

Iteration 21
Model Output: No

Iteration 22
Model Output: Yes

Iteration 23
Model Output: No

Iteration 24
Model Output: No

Iteration 25
Model Output: Yes

Iteration 26
Model Output: No

Iteration 27
Model Output: Yes

Iteration 28
Model Output: No

Iteration 29
Model Output: Yes

Iteration 30
Model Output: Yes

Iteration 31
Model Output: No

Iteration 32
Model Output: No

Iteration 33
Model Output: Yes

Iteration 34
Model Output: No

Iteration 35
Model Output: Yes

Iteration 36
Model Output: No

Iteration 37
Model Output: No

Iteration 38
Model Output: No

Iteration 39
Model Output: No

Iteration 40
Model Output: Yes

Iteration 41
Model Output: No

Iteration 42
Model Output: No

Iteration 43
Model Output: No

Iteration 44
Model Output: No

Iteration 45
Model Output: Yes

Iteration 46
Model Output: No

Iteration 47
Model Output: No

Iteration 48
Model Output: No

Iteration 49
Model Output: No

Iteration 50
Model Output: No

Iteration 51
Model Output: No

Iteration 52
Model Output: No

Iteration 53
Model Output: No

Iteration 54
Model Output: No

Iteration 55
Model Output: Yes

Iteration 56
Model Output: No

Iteration 57
Model Output: No

Iteration 58
Model Output: No

Iteration 59
Model Output: No

Iteration 60
Model Output: Yes

Iteration 61
Model Output: No

Iteration 62
Model Output: No

Iteration 63
Model Output: Yes

Iteration 64
Model Output: No

Iteration 65
Model Output: No

Iteration 66
Model Output: No

Iteration 67
Model Output: No

Iteration 68
Model Output: No

Iteration 69
Model Output: No

Iteration 70
Model Output: No

Iteration 71
Model Output: No

Iteration 72
Model Output: No

Iteration 73
Model Output: No

Iteration 74
Model Output: No

Iteration 75
Model Output: Yes

Iteration 76
Model Output: Yes

Iteration 77
Model Output: No

Iteration 78
Model Output: No

Iteration 79
Model Output: Yes

Iteration 80
Model Output: Yes

Iteration 81
Model Output: No

Iteration 82
Model Output: No

Iteration 83
Model Output: No

Iteration 84
Model Output: No

Iteration 85
Model Output: Yes

Iteration 86
Model Output: No

Iteration 87
Model Output: No

Iteration 88
Model Output: No

Iteration 89
Model Output: No

Iteration 90
Model Output: Yes

Iteration 91
Model Output: No

Iteration 92
Model Output: Yes

Iteration 93
Model Output: No

Iteration 94
Model Output: No

Iteration 95
Model Output: Yes

Iteration 96
Model Output: No

Iteration 97
Model Output: Yes

Iteration 98
Model Output: No

Iteration 99
Model Output: No

Iteration 100
Model Output: No

Iteration 101
Model Output: No

Iteration 102
Model Output: No

Iteration 103
Model Output: No

Iteration 104
Model Output: No

Iteration 105
Model Output: Yes

Iteration 106
Model Output: No

Iteration 107
Model Output: Yes

Iteration 108
Model Output: No

Iteration 109
Model Output: No

Iteration 110
Model Output: Yes

Iteration 111
Model Output: No

Iteration 112
Model Output: No

Iteration 113
Model Output: Yes

Iteration 114
Model Output: No

Iteration 115
Model Output: Yes

Iteration 116
Model Output: Yes

Iteration 117
Model Output: No

Iteration 118
Model Output: Yes

Iteration 119
Model Output: No

Iteration 120
Model Output: No

Iteration 121
Model Output: No

Iteration 122
Model Output: No

Iteration 123
Model Output: No

Iteration 124
Model Output: No

Iteration 125
Model Output: No

Iteration 126
Model Output: No

Iteration 127
Model Output: No

Iteration 128
Model Output: No

Iteration 129
Model Output: No

Iteration 130
Model Output: No

Iteration 131
Model Output: No

Iteration 132
Model Output: No

Iteration 133
Model Output: No

Iteration 134
Model Output: No

Iteration 135
Model Output: Yes

Iteration 136
Model Output: Yes

Iteration 137
Model Output: Yes

Iteration 138
Model Output: Yes

Iteration 139
Model Output: Yes

Iteration 140
Model Output: Yes

Iteration 141
Model Output: No

Iteration 142
Model Output: Yes

Iteration 143
Model Output: Yes

Iteration 144
Model Output: No

Iteration 145
Model Output: No

Iteration 146
Model Output: No

Iteration 147
Model Output: No

Iteration 148
Model Output: No

Iteration 149
Model Output: No

Iteration 150
Model Output: Yes

Iteration 151
Model Output: No

Iteration 152
Model Output: Yes

Iteration 153
Model Output: Yes

Iteration 154
Model Output: No

Iteration 155
Model Output: Yes

Iteration 156
Model Output: No

Iteration 157
Model Output: No

Iteration 158
Model Output: No

Iteration 159
Model Output: Yes

Iteration 160
Model Output: No

Iteration 161
Model Output: No

Iteration 162
Model Output: No

Iteration 163
Model Output: No

Iteration 164
Model Output: No

Iteration 165
Model Output: No

Iteration 166
Model Output: No

Iteration 167
Model Output: No

Iteration 168
Model Output: No

Iteration 169
Model Output: No

Iteration 170
Model Output: Yes

Iteration 171
Model Output: No

Iteration 172
Model Output: No

Iteration 173
Model Output: No

Iteration 174
Model Output: No

Iteration 175
Model Output: No

Iteration 176
Model Output: No

Iteration 177
Model Output: No

Iteration 178
Model Output: No

Iteration 179
Model Output: No

Iteration 180
Model Output: No

Iteration 181
Model Output: No

Iteration 182
Model Output: No

Iteration 183
Model Output: No

Iteration 184
Model Output: No

Iteration 185
Model Output: No

Iteration 186
Model Output: No

Iteration 187
Model Output: No

Iteration 188
Model Output: No

Iteration 189
Model Output: No

Iteration 190
Model Output: Yes

Iteration 191
Model Output: Yes

Iteration 192
Model Output: No

Iteration 193
Model Output: Yes

Iteration 194
Model Output: Yes

Iteration 195
Model Output: Yes

Iteration 196
Model Output: No

Iteration 197
Model Output: Yes

Iteration 198
Model Output: No

Iteration 199
Model Output: No

Iteration 200
Model Output: No

Iteration 201
Model Output: No

Iteration 202
Model Output: No

Iteration 203
Model Output: No

Iteration 204
Model Output: No

Iteration 205
Model Output: No

Iteration 206
Model Output: No

Iteration 207
Model Output: No

Iteration 208
Model Output: No

Iteration 209
Model Output: No

Iteration 210
Model Output: Yes

Iteration 211
Model Output: No

Iteration 212
Model Output: No

Iteration 213
Model Output: Yes

Iteration 214
Model Output: No

Iteration 215
Model Output: Yes

Iteration 216
Model Output: Yes

Iteration 217
Model Output: No

Iteration 218
Model Output: No

Iteration 219
Model Output: No

Iteration 220
Model Output: No

Iteration 221
Model Output: Yes

Iteration 222
Model Output: No

Iteration 223
Model Output: Yes

Iteration 224
Model Output: Yes

Iteration 225
Model Output: Yes

Iteration 226
Model Output: Yes

Iteration 227
Model Output: Yes

Iteration 228
Model Output: Yes

Iteration 229
Model Output: No

Iteration 230
Model Output: Yes

Iteration 231
Model Output: No

Iteration 232
Model Output: Yes

Iteration 233
Model Output: No

Iteration 234
Model Output: No

Iteration 235
Model Output: Yes

Iteration 236
Model Output: No

Iteration 237
Model Output: No

Iteration 238
Model Output: No

Iteration 239
Model Output: Yes

Iteration 240
Model Output: Yes

Iteration 241
Model Output: No

Iteration 242
Model Output: Yes

Iteration 243
Model Output: No

Iteration 244
Model Output: Yes

Iteration 245
Model Output: Yes

Iteration 246
Model Output: No

Iteration 247
Model Output: No

Iteration 248
Model Output: No

Iteration 249
Model Output: No

In [20]:
predictions_new = [elem.lower() for elem in predictions]

In [21]:
print(classification_report(true_answers,predictions_new,zero_division=0))

              precision    recall  f1-score   support

          no       0.56      0.80      0.66       125
         yes       0.65      0.37      0.47       125

    accuracy                           0.58       250
   macro avg       0.60      0.58      0.56       250
weighted avg       0.60      0.58      0.56       250

## Conditional Questions

In [22]:
dataset_conditional = dataset[dataset['type']=="conditional"]

In [23]:
dataset_conditional

,question,given_info,answer,type,question_id,meta
25,Would Lumbo occur if not Ziklo instead of Ziklo?,"We know that Ziklo causes not Blaf, Blaf and T...",yes,conditional,5,"{'graph_id': 'graph5', 'model_id': 25, 'query_..."
26,Would Zlim occur if not Glent instead of Glent?,"We know that Glent causes not Razz, Razz and P...",yes,conditional,205,"{'graph_id': 'graph5', 'model_id': 26, 'query_..."
27,Would Klep occur if not Praf instead of Praf?,"We know that Praf causes not Vank, Vank and Sc...",yes,conditional,405,"{'graph_id': 'graph5', 'model_id': 27, 'query_..."
28,Would Jext occur if not Fizo instead of Fizo?,"We know that Fizo causes not Blorn, Blorn and ...",yes,conditional,605,"{'graph_id': 'graph5', 'model_id': 28, 'query_..."
29,Would Wrox occur if not Nuv instead of Nuv?,"We know that Nuv causes not Splee, Splee and B...",yes,conditional,805,"{'graph_id': 'graph5', 'model_id': 29, 'query_..."
...,...,...,...,...,...,...
435,Would Lumbo occur if not Ziklo instead of Ziklo?,"We know that Ziklo causes Blaf and Trune, Blaf...",no,conditional,87,"{'graph_id': 'graph7', 'model_id': 435, 'query..."
436,Would Zlim occur if not Glent instead of Glent?,"We know that Glent causes Razz and Pex, Razz a...",no,conditional,287,"{'graph_id': 'graph7', 'model_id': 436, 'query..."
437,Would Klep occur if not Praf instead of Praf?,"We know that Praf causes Vank and Scud, Vank a...",no,conditional,487,"{'graph_id': 'graph7', 'model_id': 437, 'query..."
438,Would Jext occur if not Fizo instead of Fizo?,"We know that Fizo causes Blorn and Plim, Blorn...",no,conditional,687,"{'graph_id': 'graph7', 'model_id': 438, 'query..."
439,Would Wrox occur if not Nuv instead of Nuv?,"We know that Nuv causes Splee and Blen, Splee ...",no,conditional,887,"{'graph_id': 'graph7', 'model_id': 439, 'query..."

In [24]:
questions = dataset_conditional["question"].values.tolist()
contexts = dataset_conditional["given_info"].values.tolist()
true_answers = dataset_conditional["answer"].values.tolist()

In [25]:
prompts = get_prompt(instruction,questions,contexts)

In [26]:
prompts[0]

'Instruction: Answer the question strictly using the causal facts provided. Do not introduce any new information. For counterfactuals, simulate the scenario along the causal chain step by step. Only output the final answer as Yes or No. Do not write anything else.\nContext:We know that Ziklo causes not Blaf, Blaf and Trune together cause Vork, Vork causes Lumbo. We observed Trune\nQuestion:Would Lumbo occur if not Ziklo instead of Ziklo?\nAnswer:'

In [27]:
predictions = training(prompts)

Iteration 0
Model Output: No

Iteration 1
Model Output: No

Iteration 2
Model Output: No

Iteration 3
Model Output: Yes

Iteration 4
Model Output: No

Iteration 5
Model Output: Yes

Iteration 6
Model Output: No

Iteration 7
Model Output: Yes

Iteration 8
Model Output: Yes

Iteration 9
Model Output: Yes

Iteration 10
Model Output: No

Iteration 11
Model Output: No

Iteration 12
Model Output: No

Iteration 13
Model Output: No

Iteration 14
Model Output: No

Iteration 15
Model Output: Yes

Iteration 16
Model Output: No

Iteration 17
Model Output: Yes

Iteration 18
Model Output: Yes

Iteration 19
Model Output: Yes

Iteration 20
Model Output: Yes

Iteration 21
Model Output: No

Iteration 22
Model Output: Yes

Iteration 23
Model Output: Yes

Iteration 24
Model Output: No

Iteration 25
Model Output: Yes

Iteration 26
Model Output: No

Iteration 27
Model Output: Yes

Iteration 28
Model Output: No

Iteration 29
Model Output: No

Iteration 30
Model Output: Yes

Iteration 31
Model Output: No

Iteration 32
Model Output: Yes

Iteration 33
Model Output: Yes

Iteration 34
Model Output: Yes

Iteration 35
Model Output: Yes

Iteration 36
Model Output: Yes

Iteration 37
Model Output: Yes

Iteration 38
Model Output: Yes

Iteration 39
Model Output: Yes

Iteration 40
Model Output: Yes

Iteration 41
Model Output: Yes

Iteration 42
Model Output: Yes

Iteration 43
Model Output: Yes

Iteration 44
Model Output: Yes

Iteration 45
Model Output: Yes

Iteration 46
Model Output: No

Iteration 47
Model Output: Yes

Iteration 48
Model Output: Yes

Iteration 49
Model Output: Yes

Iteration 50
Model Output: Yes

Iteration 51
Model Output: No

Iteration 52
Model Output: Yes

Iteration 53
Model Output: Yes

Iteration 54
Model Output: Yes

Iteration 55
Model Output: Yes

Iteration 56
Model Output: No

Iteration 57
Model Output: Yes

Iteration 58
Model Output: No

Iteration 59
Model Output: Yes

Iteration 60
Model Output: Yes

Iteration 61
Model Output: No

Iteration 62
Model Output: No

Iteration 63
Model Output: No

Iteration 64
Model Output: Yes

Iteration 65
Model Output: Yes

Iteration 66
Model Output: No

Iteration 67
Model Output: Yes

Iteration 68
Model Output: No

Iteration 69
Model Output: No

Iteration 70
Model Output: No

Iteration 71
Model Output: No

Iteration 72
Model Output: No

Iteration 73
Model Output: No

Iteration 74
Model Output: No

Iteration 75
Model Output: Yes

Iteration 76
Model Output: No

Iteration 77
Model Output: No

Iteration 78
Model Output: Yes

Iteration 79
Model Output: No

Iteration 80
Model Output: No

Iteration 81
Model Output: No

Iteration 82
Model Output: No

Iteration 83
Model Output: Yes

Iteration 84
Model Output: No

Iteration 85
Model Output: No

Iteration 86
Model Output: No

Iteration 87
Model Output: No

Iteration 88
Model Output: No

Iteration 89
Model Output: No

Iteration 90
Model Output: No

Iteration 91
Model Output: Yes

Iteration 92
Model Output: Yes

Iteration 93
Model Output: No

Iteration 94
Model Output: Yes

Iteration 95
Model Output: No

Iteration 96
Model Output: No

Iteration 97
Model Output: No

Iteration 98
Model Output: No

Iteration 99
Model Output: No

Iteration 100
Model Output: Yes

Iteration 101
Model Output: No

Iteration 102
Model Output: Yes

Iteration 103
Model Output: Yes

Iteration 104
Model Output: Yes

Iteration 105
Model Output: No

Iteration 106
Model Output: No

Iteration 107
Model Output: No

Iteration 108
Model Output: No

Iteration 109
Model Output: Yes

Iteration 110
Model Output: No

Iteration 111
Model Output: No

Iteration 112
Model Output: No

Iteration 113
Model Output: Yes

Iteration 114
Model Output: No

Iteration 115
Model Output: No

Iteration 116
Model Output: No

Iteration 117
Model Output: No

Iteration 118
Model Output: No

Iteration 119
Model Output: No

Iteration 120
Model Output: Yes

Iteration 121
Model Output: Yes

Iteration 122
Model Output: No

Iteration 123
Model Output: No

Iteration 124
Model Output: Yes

Iteration 125
Model Output: Yes

Iteration 126
Model Output: Yes

Iteration 127
Model Output: No

Iteration 128
Model Output: Yes

Iteration 129
Model Output: Yes

Iteration 130
Model Output: Yes

Iteration 131
Model Output: No

Iteration 132
Model Output: No

Iteration 133
Model Output: No

Iteration 134
Model Output: Yes

Iteration 135
Model Output: No

Iteration 136
Model Output: Yes

Iteration 137
Model Output: No

Iteration 138
Model Output: Yes

Iteration 139
Model Output: No

Iteration 140
Model Output: Yes

Iteration 141
Model Output: No

Iteration 142
Model Output: Yes

Iteration 143
Model Output: No

Iteration 144
Model Output: Yes

Iteration 145
Model Output: No

Iteration 146
Model Output: No

Iteration 147
Model Output: No

Iteration 148
Model Output: No

Iteration 149
Model Output: No

Iteration 150
Model Output: Yes

Iteration 151
Model Output: Yes

Iteration 152
Model Output: No

Iteration 153
Model Output: Yes

Iteration 154
Model Output: Yes

Iteration 155
Model Output: No

Iteration 156
Model Output: No

Iteration 157
Model Output: No

Iteration 158
Model Output: No

Iteration 159
Model Output: Yes

Iteration 160
Model Output: No

Iteration 161
Model Output: No

Iteration 162
Model Output: No

Iteration 163
Model Output: Yes

Iteration 164
Model Output: No

Iteration 165
Model Output: No

Iteration 166
Model Output: No

Iteration 167
Model Output: No

Iteration 168
Model Output: No

Iteration 169
Model Output: Yes

Iteration 170
Model Output: Yes

Iteration 171
Model Output: Yes

Iteration 172
Model Output: Yes

Iteration 173
Model Output: Yes

Iteration 174
Model Output: Yes

Iteration 175
Model Output: Yes

Iteration 176
Model Output: Yes

Iteration 177
Model Output: Yes

Iteration 178
Model Output: Yes

Iteration 179
Model Output: Yes

Iteration 180
Model Output: No

Iteration 181
Model Output: No

Iteration 182
Model Output: Yes

Iteration 183
Model Output: Yes

Iteration 184
Model Output: No

Iteration 185
Model Output: Yes

Iteration 186
Model Output: No

Iteration 187
Model Output: Yes

Iteration 188
Model Output: No

Iteration 189
Model Output: Yes

Iteration 190
Model Output: Yes

Iteration 191
Model Output: No

Iteration 192
Model Output: Yes

Iteration 193
Model Output: Yes

Iteration 194
Model Output: Yes

Iteration 195
Model Output: Yes

Iteration 196
Model Output: No

Iteration 197
Model Output: Yes

Iteration 198
Model Output: Yes

Iteration 199
Model Output: Yes

Iteration 200
Model Output: Yes

Iteration 201
Model Output: No

Iteration 202
Model Output: No

Iteration 203
Model Output: Yes

Iteration 204
Model Output: Yes

Iteration 205
Model Output: No

Iteration 206
Model Output: No

Iteration 207
Model Output: No

Iteration 208
Model Output: Yes

Iteration 209
Model Output: Yes

Iteration 210
Model Output: No

Iteration 211
Model Output: No

Iteration 212
Model Output: No

Iteration 213
Model Output: No

Iteration 214
Model Output: Yes

Iteration 215
Model Output: Yes

Iteration 216
Model Output: No

Iteration 217
Model Output: Yes

Iteration 218
Model Output: No

Iteration 219
Model Output: No

Iteration 220
Model Output: Yes

Iteration 221
Model Output: Yes

Iteration 222
Model Output: No

Iteration 223
Model Output: Yes

Iteration 224
Model Output: Yes

Iteration 225
Model Output: No

Iteration 226
Model Output: No

Iteration 227
Model Output: No

Iteration 228
Model Output: No

Iteration 229
Model Output: No

Iteration 230
Model Output: Yes

Iteration 231
Model Output: No

Iteration 232
Model Output: No

Iteration 233
Model Output: No

Iteration 234
Model Output: No

Iteration 235
Model Output: No

Iteration 236
Model Output: No

Iteration 237
Model Output: No

Iteration 238
Model Output: No

Iteration 239
Model Output: No

Iteration 240
Model Output: No

Iteration 241
Model Output: No

Iteration 242
Model Output: No

Iteration 243
Model Output: No

Iteration 244
Model Output: No

Iteration 245
Model Output: No

Iteration 246
Model Output: No

Iteration 247
Model Output: No

Iteration 248
Model Output: No

Iteration 249
Model Output: No

In [28]:
predictions_new = [elem.lower() for elem in predictions]

In [29]:
print(classification_report(true_answers,predictions_new,zero_division=0))

              precision    recall  f1-score   support

          no       0.62      0.68      0.65       125
         yes       0.64      0.58      0.61       125

    accuracy                           0.63       250
   macro avg       0.63      0.63      0.63       250
weighted avg       0.63      0.63      0.63       250

## Joint Questions

In [30]:
dataset_joint = dataset[dataset['type']=="joint"]

In [31]:
dataset_joint

,question,given_info,answer,type,question_id,meta
500,Would Lumbo occur if not Ziklo and not Blaf?,"We know that Ziklo causes Blaf and Vork, Blaf ...",yes,joint,100,"{'graph_id': 'graph5', 'model_id': 500, 'query..."
501,Would Zlim occur if not Glent and not Razz?,"We know that Glent causes Razz and Zurn, Razz ...",yes,joint,300,"{'graph_id': 'graph5', 'model_id': 501, 'query..."
502,Would Klep occur if not Praf and not Vank?,"We know that Praf causes Vank and Wrenk, Vank ...",yes,joint,500,"{'graph_id': 'graph5', 'model_id': 502, 'query..."
503,Would Jext occur if not Fizo and not Blorn?,"We know that Fizo causes Blorn and Quaz, Blorn...",yes,joint,700,"{'graph_id': 'graph5', 'model_id': 503, 'query..."
504,Would Wrox occur if not Nuv and not Splee?,"We know that Nuv causes Splee and Druk, Splee ...",yes,joint,900,"{'graph_id': 'graph5', 'model_id': 504, 'query..."
...,...,...,...,...,...,...
745,Would Lumbo occur if not Ziklo and not Sline?,"We know that Ziklo causes Blaf, Blaf causes Tr...",yes,joint,149,"{'graph_id': 'graph7', 'model_id': 745, 'query..."
746,Would Zlim occur if not Glent and not Melf?,"We know that Glent causes Razz, Razz causes Pe...",yes,joint,349,"{'graph_id': 'graph7', 'model_id': 746, 'query..."
747,Would Klep occur if not Praf and not Yobb?,"We know that Praf causes Vank, Vank causes Scu...",yes,joint,549,"{'graph_id': 'graph7', 'model_id': 747, 'query..."
748,Would Jext occur if not Fizo and not Skul?,"We know that Fizo causes Blorn, Blorn causes P...",yes,joint,749,"{'graph_id': 'graph7', 'model_id': 748, 'query..."
749,Would Wrox occur if not Nuv and not Plog?,"We know that Nuv causes Splee, Splee causes Bl...",yes,joint,949,"{'graph_id': 'graph7', 'model_id': 749, 'query..."

In [32]:
questions = dataset_joint["question"].values.tolist()
contexts = dataset_joint["given_info"].values.tolist()
true_answers = dataset_joint["answer"].values.tolist()

In [33]:
prompts = get_prompt(instruction,questions,contexts)

In [34]:
prompts[0]

'Instruction: Answer the question strictly using the causal facts provided. Do not introduce any new information. For counterfactuals, simulate the scenario along the causal chain step by step. Only output the final answer as Yes or No. Do not write anything else.\nContext:We know that Ziklo causes Blaf and Vork, Blaf causes not Trune, Trune or Vork causes Lumbo.\nQuestion:Would Lumbo occur if not Ziklo and not Blaf?\nAnswer:'

In [35]:
predictions = training(prompts)

Iteration 0
Model Output: Yes

Iteration 1
Model Output: Yes

Iteration 2
Model Output: Yes

Iteration 3
Model Output: Yes

Iteration 4
Model Output: Yes

Iteration 5
Model Output: Yes

Iteration 6
Model Output: Yes

Iteration 7
Model Output: Yes

Iteration 8
Model Output: Yes

Iteration 9
Model Output: No

Iteration 10
Model Output: No

Iteration 11
Model Output: No

Iteration 12
Model Output: No

Iteration 13
Model Output: No

Iteration 14
Model Output: No

Iteration 15
Model Output: Yes

Iteration 16
Model Output: Yes

Iteration 17
Model Output: Yes

Iteration 18
Model Output: Yes

Iteration 19
Model Output: Yes

Iteration 20
Model Output: Yes

Iteration 21
Model Output: Yes

Iteration 22
Model Output: Yes

Iteration 23
Model Output: Yes

Iteration 24
Model Output: No

Iteration 25
Model Output: Yes

Iteration 26
Model Output: Yes

Iteration 27
Model Output: Yes

Iteration 28
Model Output: Yes

Iteration 29
Model Output: Yes

Iteration 30
Model Output: Yes

Iteration 31
Model Output: Yes

Iteration 32
Model Output: Yes

Iteration 33
Model Output: Yes

Iteration 34
Model Output: Yes

Iteration 35
Model Output: Yes

Iteration 36
Model Output: Yes

Iteration 37
Model Output: Yes

Iteration 38
Model Output: Yes

Iteration 39
Model Output: Yes

Iteration 40
Model Output: Yes

Iteration 41
Model Output: Yes

Iteration 42
Model Output: Yes

Iteration 43
Model Output: Yes

Iteration 44
Model Output: Yes

Iteration 45
Model Output: Yes

Iteration 46
Model Output: Yes

Iteration 47
Model Output: No

Iteration 48
Model Output: Yes

Iteration 49
Model Output: Yes

Iteration 50
Model Output: Yes

Iteration 51
Model Output: Yes

Iteration 52
Model Output: Yes

Iteration 53
Model Output: Yes

Iteration 54
Model Output: Yes

Iteration 55
Model Output: Yes

Iteration 56
Model Output: No

Iteration 57
Model Output: Yes

Iteration 58
Model Output: Yes

Iteration 59
Model Output: No

Iteration 60
Model Output: Yes

Iteration 61
Model Output: Yes

Iteration 62
Model Output: Yes

Iteration 63
Model Output: Yes

Iteration 64
Model Output: Yes

Iteration 65
Model Output: No

Iteration 66
Model Output: No

Iteration 67
Model Output: No

Iteration 68
Model Output: Yes

Iteration 69
Model Output: No

Iteration 70
Model Output: No

Iteration 71
Model Output: Yes

Iteration 72
Model Output: No

Iteration 73
Model Output: Yes

Iteration 74
Model Output: No

Iteration 75
Model Output: Yes

Iteration 76
Model Output: Yes

Iteration 77
Model Output: Yes

Iteration 78
Model Output: Yes

Iteration 79
Model Output: Yes

Iteration 80
Model Output: Yes

Iteration 81
Model Output: Yes

Iteration 82
Model Output: Yes

Iteration 83
Model Output: Yes

Iteration 84
Model Output: Yes

Iteration 85
Model Output: No

Iteration 86
Model Output: Yes

Iteration 87
Model Output: Yes

Iteration 88
Model Output: No

Iteration 89
Model Output: Yes

Iteration 90
Model Output: No

Iteration 91
Model Output: No

Iteration 92
Model Output: Yes

Iteration 93
Model Output: Yes

Iteration 94
Model Output: No

Iteration 95
Model Output: Yes

Iteration 96
Model Output: Yes

Iteration 97
Model Output: Yes

Iteration 98
Model Output: Yes

Iteration 99
Model Output: Yes

Iteration 100
Model Output: Yes

Iteration 101
Model Output: Yes

Iteration 102
Model Output: Yes

Iteration 103
Model Output: Yes

Iteration 104
Model Output: Yes

Iteration 105
Model Output: Yes

Iteration 106
Model Output: No

Iteration 107
Model Output: Yes

Iteration 108
Model Output: Yes

Iteration 109
Model Output: No

Iteration 110
Model Output: No

Iteration 111
Model Output: No

Iteration 112
Model Output: Yes

Iteration 113
Model Output: No

Iteration 114
Model Output: Yes

Iteration 115
Model Output: Yes

Iteration 116
Model Output: Yes

Iteration 117
Model Output: Yes

Iteration 118
Model Output: Yes

Iteration 119
Model Output: Yes

Iteration 120
Model Output: Yes

Iteration 121
Model Output: No

Iteration 122
Model Output: No

Iteration 123
Model Output: Yes

Iteration 124
Model Output: Yes

Iteration 125
Model Output: No

Iteration 126
Model Output: No

Iteration 127
Model Output: No

Iteration 128
Model Output: No

Iteration 129
Model Output: No

Iteration 130
Model Output: No

Iteration 131
Model Output: No

Iteration 132
Model Output: No

Iteration 133
Model Output: No

Iteration 134
Model Output: No

Iteration 135
Model Output: Yes

Iteration 136
Model Output: Yes

Iteration 137
Model Output: No

Iteration 138
Model Output: Yes

Iteration 139
Model Output: Yes

Iteration 140
Model Output: Yes

Iteration 141
Model Output: Yes

Iteration 142
Model Output: Yes

Iteration 143
Model Output: No

Iteration 144
Model Output: Yes

Iteration 145
Model Output: No

Iteration 146
Model Output: No

Iteration 147
Model Output: No

Iteration 148
Model Output: No

Iteration 149
Model Output: No

Iteration 150
Model Output: No

Iteration 151
Model Output: No

Iteration 152
Model Output: No

Iteration 153
Model Output: No

Iteration 154
Model Output: No

Iteration 155
Model Output: Yes

Iteration 156
Model Output: Yes

Iteration 157
Model Output: Yes

Iteration 158
Model Output: Yes

Iteration 159
Model Output: Yes

Iteration 160
Model Output: Yes

Iteration 161
Model Output: Yes

Iteration 162
Model Output: No

Iteration 163
Model Output: Yes

Iteration 164
Model Output: Yes

Iteration 165
Model Output: Yes

Iteration 166
Model Output: Yes

Iteration 167
Model Output: Yes

Iteration 168
Model Output: No

Iteration 169
Model Output: Yes

Iteration 170
Model Output: Yes

Iteration 171
Model Output: No

Iteration 172
Model Output: No

Iteration 173
Model Output: Yes

Iteration 174
Model Output: Yes

Iteration 175
Model Output: Yes

Iteration 176
Model Output: Yes

Iteration 177
Model Output: No

Iteration 178
Model Output: Yes

Iteration 179
Model Output: Yes

Iteration 180
Model Output: No

Iteration 181
Model Output: No

Iteration 182
Model Output: No

Iteration 183
Model Output: No

Iteration 184
Model Output: No

Iteration 185
Model Output: Yes

Iteration 186
Model Output: No

Iteration 187
Model Output: Yes

Iteration 188
Model Output: Yes

Iteration 189
Model Output: Yes

Iteration 190
Model Output: Yes

Iteration 191
Model Output: Yes

Iteration 192
Model Output: Yes

Iteration 193
Model Output: Yes

Iteration 194
Model Output: Yes

Iteration 195
Model Output: Yes

Iteration 196
Model Output: Yes

Iteration 197
Model Output: Yes

Iteration 198
Model Output: Yes

Iteration 199
Model Output: Yes

Iteration 200
Model Output: Yes

Iteration 201
Model Output: Yes

Iteration 202
Model Output: Yes

Iteration 203
Model Output: Yes

Iteration 204
Model Output: Yes

Iteration 205
Model Output: Yes

Iteration 206
Model Output: Yes

Iteration 207
Model Output: Yes

Iteration 208
Model Output: Yes

Iteration 209
Model Output: Yes

Iteration 210
Model Output: Yes

Iteration 211
Model Output: No

Iteration 212
Model Output: No

Iteration 213
Model Output: Yes

Iteration 214
Model Output: Yes

Iteration 215
Model Output: Yes

Iteration 216
Model Output: Yes

Iteration 217
Model Output: Yes

Iteration 218
Model Output: Yes

Iteration 219
Model Output: Yes

Iteration 220
Model Output: Yes

Iteration 221
Model Output: Yes

Iteration 222
Model Output: Yes

Iteration 223
Model Output: Yes

Iteration 224
Model Output: Yes

Iteration 225
Model Output: Yes

Iteration 226
Model Output: Yes

Iteration 227
Model Output: Yes

Iteration 228
Model Output: Yes

Iteration 229
Model Output: Yes

Iteration 230
Model Output: Yes

Iteration 231
Model Output: Yes

Iteration 232
Model Output: Yes

Iteration 233
Model Output: Yes

Iteration 234
Model Output: Yes

Iteration 235
Model Output: No

Iteration 236
Model Output: No

Iteration 237
Model Output: No

Iteration 238
Model Output: No

Iteration 239
Model Output: No

Iteration 240
Model Output: No

Iteration 241
Model Output: No

Iteration 242
Model Output: No

Iteration 243
Model Output: No

Iteration 244
Model Output: No

Iteration 245
Model Output: Yes

Iteration 246
Model Output: Yes

Iteration 247
Model Output: Yes

Iteration 248
Model Output: Yes

Iteration 249
Model Output: Yes

In [36]:
predictions_new = [elem.lower() for elem in predictions]

In [37]:
print(classification_report(true_answers,predictions_new,zero_division=0))

              precision    recall  f1-score   support

          no       0.82      0.49      0.61       125
         yes       0.64      0.90      0.74       125

    accuracy                           0.69       250
   macro avg       0.73      0.69      0.68       250
weighted avg       0.73      0.69      0.68       250

## Nested Questions

In [38]:
dataset_nested = dataset[dataset['type']=="nested"]

In [39]:
dataset_nested

,question,given_info,answer,type,question_id,meta
750,"Assume not Ziklo, and based on this assumption...","We know that Ziklo causes Blaf, Trune and Vork...",yes,nested,150,"{'graph_id': 'graph9', 'model_id': 750, 'query..."
751,"Assume not Glent, and based on this assumption...","We know that Glent causes Razz, Pex and Zurn, ...",yes,nested,350,"{'graph_id': 'graph9', 'model_id': 751, 'query..."
752,"Assume not Praf, and based on this assumption,...","We know that Praf causes Vank, Scud and Wrenk,...",yes,nested,550,"{'graph_id': 'graph9', 'model_id': 752, 'query..."
753,"Assume not Fizo, and based on this assumption,...","We know that Fizo causes Blorn, Plim and Quaz,...",yes,nested,750,"{'graph_id': 'graph9', 'model_id': 753, 'query..."
754,"Assume not Nuv, and based on this assumption, ...","We know that Nuv causes Splee, Blen and Druk, ...",yes,nested,950,"{'graph_id': 'graph9', 'model_id': 754, 'query..."
...,...,...,...,...,...,...
995,"Assume not Ziklo, and based on this assumption...","We know that Ziklo causes Blaf and Trune, Trun...",yes,nested,199,"{'graph_id': 'graph8', 'model_id': 995, 'query..."
996,"Assume not Glent, and based on this assumption...","We know that Glent causes Razz and Pex, Pex ca...",yes,nested,399,"{'graph_id': 'graph8', 'model_id': 996, 'query..."
997,"Assume not Praf, and based on this assumption,...","We know that Praf causes Vank and Scud, Scud c...",yes,nested,599,"{'graph_id': 'graph8', 'model_id': 997, 'query..."
998,"Assume not Fizo, and based on this assumption,...","We know that Fizo causes Blorn and Plim, Plim ...",yes,nested,799,"{'graph_id': 'graph8', 'model_id': 998, 'query..."
999,"Assume not Nuv, and based on this assumption, ...","We know that Nuv causes Splee and Blen, Blen c...",yes,nested,999,"{'graph_id': 'graph8', 'model_id': 999, 'query..."

In [40]:
questions = dataset_nested["question"].values.tolist()
contexts = dataset_nested["given_info"].values.tolist()
true_answers = dataset_nested["answer"].values.tolist()

In [41]:
prompts = get_prompt(instruction,questions,contexts)

In [42]:
prompts[0]

'Instruction: Answer the question strictly using the causal facts provided. Do not introduce any new information. For counterfactuals, simulate the scenario along the causal chain step by step. Only output the final answer as Yes or No. Do not write anything else.\nContext:We know that Ziklo causes Blaf, Trune and Vork, not Vork causes Sline, Sline causes Frim, Frim or Vork causes Qado, Qado causes Jurf, and Jurf causes Lumbo.\nQuestion:Assume not Ziklo, and based on this assumption, further suppose not Sline. Would Lumbo occur?\nAnswer:'

In [43]:
predictions = training(prompts)

Iteration 0
Model Output: No

Iteration 1
Model Output: No

Iteration 2
Model Output: No

Iteration 3
Model Output: No

Iteration 4
Model Output: Yes

Iteration 5
Model Output: Yes

Iteration 6
Model Output: Yes

Iteration 7
Model Output: No

Iteration 8
Model Output: No

Iteration 9
Model Output: No

Iteration 10
Model Output: No

Iteration 11
Model Output: No

Iteration 12
Model Output: No

Iteration 13
Model Output: No

Iteration 14
Model Output: No

Iteration 15
Model Output: No

Iteration 16
Model Output: No

Iteration 17
Model Output: No

Iteration 18
Model Output: No

Iteration 19
Model Output: No

Iteration 20
Model Output: No

Iteration 21
Model Output: No

Iteration 22
Model Output: No

Iteration 23
Model Output: No

Iteration 24
Model Output: No

Iteration 25
Model Output: No

Iteration 26
Model Output: No

Iteration 27
Model Output: No

Iteration 28
Model Output: No

Iteration 29
Model Output: No

Iteration 30
Model Output: No

Iteration 31
Model Output: No

Iteration 32
Model Output: No

Iteration 33
Model Output: No

Iteration 34
Model Output: No

Iteration 35
Model Output: No

Iteration 36
Model Output: No

Iteration 37
Model Output: No

Iteration 38
Model Output: No

Iteration 39
Model Output: Yes

Iteration 40
Model Output: No

Iteration 41
Model Output: No

Iteration 42
Model Output: No

Iteration 43
Model Output: No

Iteration 44
Model Output: No

Iteration 45
Model Output: No

Iteration 46
Model Output: No

Iteration 47
Model Output: No

Iteration 48
Model Output: No

Iteration 49
Model Output: No

Iteration 50
Model Output: No

Iteration 51
Model Output: No

Iteration 52
Model Output: No

Iteration 53
Model Output: No

Iteration 54
Model Output: No

Iteration 55
Model Output: No

Iteration 56
Model Output: No

Iteration 57
Model Output: No

Iteration 58
Model Output: No

Iteration 59
Model Output: No

Iteration 60
Model Output: No

Iteration 61
Model Output: No

Iteration 62
Model Output: No

Iteration 63
Model Output: No

Iteration 64
Model Output: No

Iteration 65
Model Output: No

Iteration 66
Model Output: No

Iteration 67
Model Output: No

Iteration 68
Model Output: No

Iteration 69
Model Output: No

Iteration 70
Model Output: No

Iteration 71
Model Output: No

Iteration 72
Model Output: No

Iteration 73
Model Output: No

Iteration 74
Model Output: No

Iteration 75
Model Output: No

Iteration 76
Model Output: No

Iteration 77
Model Output: No

Iteration 78
Model Output: No

Iteration 79
Model Output: No

Iteration 80
Model Output: No

Iteration 81
Model Output: No

Iteration 82
Model Output: No

Iteration 83
Model Output: No

Iteration 84
Model Output: No

Iteration 85
Model Output: No

Iteration 86
Model Output: No

Iteration 87
Model Output: No

Iteration 88
Model Output: No

Iteration 89
Model Output: No

Iteration 90
Model Output: No

Iteration 91
Model Output: No

Iteration 92
Model Output: No

Iteration 93
Model Output: No

Iteration 94
Model Output: No

Iteration 95
Model Output: Yes

Iteration 96
Model Output: Yes

Iteration 97
Model Output: No

Iteration 98
Model Output: No

Iteration 99
Model Output: Yes

Iteration 100
Model Output: No

Iteration 101
Model Output: No

Iteration 102
Model Output: No

Iteration 103
Model Output: No

Iteration 104
Model Output: No

Iteration 105
Model Output: No

Iteration 106
Model Output: No

Iteration 107
Model Output: No

Iteration 108
Model Output: No

Iteration 109
Model Output: No

Iteration 110
Model Output: No

Iteration 111
Model Output: No

Iteration 112
Model Output: No

Iteration 113
Model Output: No

Iteration 114
Model Output: No

Iteration 115
Model Output: No

Iteration 116
Model Output: No

Iteration 117
Model Output: No

Iteration 118
Model Output: No

Iteration 119
Model Output: No

Iteration 120
Model Output: Yes

Iteration 121
Model Output: Yes

Iteration 122
Model Output: No

Iteration 123
Model Output: No

Iteration 124
Model Output: Yes

Iteration 125
Model Output: No

Iteration 126
Model Output: No

Iteration 127
Model Output: No

Iteration 128
Model Output: No

Iteration 129
Model Output: No

Iteration 130
Model Output: No

Iteration 131
Model Output: No

Iteration 132
Model Output: No

Iteration 133
Model Output: No

Iteration 134
Model Output: No

Iteration 135
Model Output: Yes

Iteration 136
Model Output: No

Iteration 137
Model Output: No

Iteration 138
Model Output: No

Iteration 139
Model Output: No

Iteration 140
Model Output: Yes

Iteration 141
Model Output: Yes

Iteration 142
Model Output: No

Iteration 143
Model Output: No

Iteration 144
Model Output: Yes

Iteration 145
Model Output: Yes

Iteration 146
Model Output: No

Iteration 147
Model Output: No

Iteration 148
Model Output: No

Iteration 149
Model Output: No

Iteration 150
Model Output: Yes

Iteration 151
Model Output: No

Iteration 152
Model Output: No

Iteration 153
Model Output: No

Iteration 154
Model Output: Yes

Iteration 155
Model Output: Yes

Iteration 156
Model Output: No

Iteration 157
Model Output: No

Iteration 158
Model Output: No

Iteration 159
Model Output: Yes

Iteration 160
Model Output: Yes

Iteration 161
Model Output: No

Iteration 162
Model Output: No

Iteration 163
Model Output: No

Iteration 164
Model Output: No

Iteration 165
Model Output: No

Iteration 166
Model Output: No

Iteration 167
Model Output: No

Iteration 168
Model Output: No

Iteration 169
Model Output: No

Iteration 170
Model Output: Yes

Iteration 171
Model Output: No

Iteration 172
Model Output: No

Iteration 173
Model Output: No

Iteration 174
Model Output: No

Iteration 175
Model Output: Yes

Iteration 176
Model Output: Yes

Iteration 177
Model Output: No

Iteration 178
Model Output: Yes

Iteration 179
Model Output: Yes

Iteration 180
Model Output: Yes

Iteration 181
Model Output: No

Iteration 182
Model Output: No

Iteration 183
Model Output: No

Iteration 184
Model Output: No

Iteration 185
Model Output: Yes

Iteration 186
Model Output: No

Iteration 187
Model Output: No

Iteration 188
Model Output: No

Iteration 189
Model Output: Yes

Iteration 190
Model Output: No

Iteration 191
Model Output: No

Iteration 192
Model Output: No

Iteration 193
Model Output: No

Iteration 194
Model Output: No

Iteration 195
Model Output: No

Iteration 196
Model Output: No

Iteration 197
Model Output: No

Iteration 198
Model Output: No

Iteration 199
Model Output: No

Iteration 200
Model Output: No

Iteration 201
Model Output: No

Iteration 202
Model Output: No

Iteration 203
Model Output: No

Iteration 204
Model Output: No

Iteration 205
Model Output: Yes

Iteration 206
Model Output: No

Iteration 207
Model Output: No

Iteration 208
Model Output: No

Iteration 209
Model Output: No

Iteration 210
Model Output: No

Iteration 211
Model Output: No

Iteration 212
Model Output: No

Iteration 213
Model Output: No

Iteration 214
Model Output: No

Iteration 215
Model Output: Yes

Iteration 216
Model Output: No

Iteration 217
Model Output: No

Iteration 218
Model Output: No

Iteration 219
Model Output: Yes

Iteration 220
Model Output: No

Iteration 221
Model Output: No

Iteration 222
Model Output: No

Iteration 223
Model Output: No

Iteration 224
Model Output: Yes

Iteration 225
Model Output: No

Iteration 226
Model Output: No

Iteration 227
Model Output: No

Iteration 228
Model Output: No

Iteration 229
Model Output: No

Iteration 230
Model Output: No

Iteration 231
Model Output: No

Iteration 232
Model Output: No

Iteration 233
Model Output: No

Iteration 234
Model Output: No

Iteration 235
Model Output: No

Iteration 236
Model Output: No

Iteration 237
Model Output: No

Iteration 238
Model Output: No

Iteration 239
Model Output: No

Iteration 240
Model Output: No

Iteration 241
Model Output: No

Iteration 242
Model Output: No

Iteration 243
Model Output: No

Iteration 244
Model Output: No

Iteration 245
Model Output: No

Iteration 246
Model Output: No

Iteration 247
Model Output: No

Iteration 248
Model Output: No

Iteration 249
Model Output: No

In [44]:
predictions_new = [elem.lower() for elem in predictions]

In [45]:
print(classification_report(true_answers,predictions_new,zero_division=0))

              precision    recall  f1-score   support

          no       0.53      0.93      0.68       125
         yes       0.72      0.18      0.29       125

    accuracy                           0.56       250
   macro avg       0.63      0.56      0.48       250
weighted avg       0.63      0.56      0.48       250

## Backdoor Questions

In [46]:
dataset_backdoor = dataset[dataset['type']=="backdoor"]

In [47]:
dataset_backdoor

,question,given_info,answer,type,question_id,meta
1000,Would Lumbo occur if not Ziklo instead of Ziklo?,"We know that Blaf causes Ziklo, Ziklo or Blaf ...",yes,backdoor,0,"{'graph_id': 'graph5', 'model_id': 0, 'query_t..."
1001,Would Zlim occur if not Glent instead of Glent?,"We know that Razz causes Glent, Glent or Razz ...",yes,backdoor,200,"{'graph_id': 'graph5', 'model_id': 1, 'query_t..."
1002,Would Klep occur if not Praf instead of Praf?,"We know that Vank causes Praf, Praf or Vank ca...",yes,backdoor,400,"{'graph_id': 'graph5', 'model_id': 2, 'query_t..."
1003,Would Jext occur if not Fizo instead of Fizo?,"We know that Blorn causes Fizo, Fizo or Blorn ...",yes,backdoor,600,"{'graph_id': 'graph5', 'model_id': 3, 'query_t..."
1004,Would Wrox occur if not Nuv instead of Nuv?,"We know that Splee causes Nuv, Nuv or Splee ca...",yes,backdoor,800,"{'graph_id': 'graph5', 'model_id': 4, 'query_t..."
...,...,...,...,...,...,...
1195,Would Lumbo occur if not Ziklo instead of Ziklo?,"We know that Blaf causes Ziklo, Blaf causes Tr...",no,backdoor,39,"{'graph_id': 'graph9', 'model_id': 195, 'query..."
1196,Would Zlim occur if not Glent instead of Glent?,"We know that Razz causes Glent, Razz causes Pe...",no,backdoor,239,"{'graph_id': 'graph9', 'model_id': 196, 'query..."
1197,Would Klep occur if not Praf instead of Praf?,"We know that Vank causes Praf, Vank causes Scu...",no,backdoor,439,"{'graph_id': 'graph9', 'model_id': 197, 'query..."
1198,Would Jext occur if not Fizo instead of Fizo?,"We know that Blorn causes Fizo, Blorn causes P...",no,backdoor,639,"{'graph_id': 'graph9', 'model_id': 198, 'query..."
1199,Would Wrox occur if not Nuv instead of Nuv?,"We know that Splee causes Nuv, Splee causes Bl...",no,backdoor,839,"{'graph_id': 'graph9', 'model_id': 199, 'query..."

In [48]:
questions = dataset_backdoor["question"].values.tolist()
contexts = dataset_backdoor["given_info"].values.tolist()
true_answers = dataset_backdoor["answer"].values.tolist()

In [49]:
prompts = get_prompt(instruction,questions,contexts)

In [50]:
prompts[0]

'Instruction: Answer the question strictly using the causal facts provided. Do not introduce any new information. For counterfactuals, simulate the scenario along the causal chain step by step. Only output the final answer as Yes or No. Do not write anything else.\nContext:We know that Blaf causes Ziklo, Ziklo or Blaf causes Trune, Trune causes Vork, and Vork causes Lumbo. Blaf~ Bern(0.2). We observed Trune\nQuestion:Would Lumbo occur if not Ziklo instead of Ziklo?\nAnswer:'

In [51]:
predictions = training(prompts)

Iteration 0
Model Output: Yes

Iteration 1
Model Output: No

Iteration 2
Model Output: No

Iteration 3
Model Output: Yes

Iteration 4
Model Output: Yes

Iteration 5
Model Output: Yes

Iteration 6
Model Output: No

Iteration 7
Model Output: No

Iteration 8
Model Output: No

Iteration 9
Model Output: Yes

Iteration 10
Model Output: Yes

Iteration 11
Model Output: No

Iteration 12
Model Output: No

Iteration 13
Model Output: No

Iteration 14
Model Output: Yes

Iteration 15
Model Output: Yes

Iteration 16
Model Output: Yes

Iteration 17
Model Output: Yes

Iteration 18
Model Output: Yes

Iteration 19
Model Output: Yes

Iteration 20
Model Output: Yes

Iteration 21
Model Output: Yes

Iteration 22
Model Output: Yes

Iteration 23
Model Output: Yes

Iteration 24
Model Output: Yes

Iteration 25
Model Output: Yes

Iteration 26
Model Output: Yes

Iteration 27
Model Output: Yes

Iteration 28
Model Output: Yes

Iteration 29
Model Output: Yes

Iteration 30
Model Output: Yes

Iteration 31
Model Output: No

Iteration 32
Model Output: No

Iteration 33
Model Output: Yes

Iteration 34
Model Output: Yes

Iteration 35
Model Output: Yes

Iteration 36
Model Output: Yes

Iteration 37
Model Output: Yes

Iteration 38
Model Output: Yes

Iteration 39
Model Output: Yes

Iteration 40
Model Output: Yes

Iteration 41
Model Output: Yes

Iteration 42
Model Output: Yes

Iteration 43
Model Output: Yes

Iteration 44
Model Output: Yes

Iteration 45
Model Output: Yes

Iteration 46
Model Output: Yes

Iteration 47
Model Output: Yes

Iteration 48
Model Output: Yes

Iteration 49
Model Output: Yes

Iteration 50
Model Output: Yes

Iteration 51
Model Output: No

Iteration 52
Model Output: No

Iteration 53
Model Output: Yes

Iteration 54
Model Output: Yes

Iteration 55
Model Output: Yes

Iteration 56
Model Output: No

Iteration 57
Model Output: No

Iteration 58
Model Output: Yes

Iteration 59
Model Output: Yes

Iteration 60
Model Output: Yes

Iteration 61
Model Output: No

Iteration 62
Model Output: No

Iteration 63
Model Output: Yes

Iteration 64
Model Output: Yes

Iteration 65
Model Output: Yes

Iteration 66
Model Output: Yes

Iteration 67
Model Output: Yes

Iteration 68
Model Output: Yes

Iteration 69
Model Output: Yes

Iteration 70
Model Output: Yes

Iteration 71
Model Output: Yes

Iteration 72
Model Output: Yes

Iteration 73
Model Output: Yes

Iteration 74
Model Output: Yes

Iteration 75
Model Output: Yes

Iteration 76
Model Output: Yes

Iteration 77
Model Output: Yes

Iteration 78
Model Output: Yes

Iteration 79
Model Output: Yes

Iteration 80
Model Output: Yes

Iteration 81
Model Output: Yes

Iteration 82
Model Output: Yes

Iteration 83
Model Output: Yes

Iteration 84
Model Output: Yes

Iteration 85
Model Output: Yes

Iteration 86
Model Output: Yes

Iteration 87
Model Output: Yes

Iteration 88
Model Output: Yes

Iteration 89
Model Output: Yes

Iteration 90
Model Output: Yes

Iteration 91
Model Output: Yes

Iteration 92
Model Output: Yes

Iteration 93
Model Output: Yes

Iteration 94
Model Output: Yes

Iteration 95
Model Output: Yes

Iteration 96
Model Output: Yes

Iteration 97
Model Output: Yes

Iteration 98
Model Output: Yes

Iteration 99
Model Output: Yes

Iteration 100
Model Output: Yes

Iteration 101
Model Output: Yes

Iteration 102
Model Output: Yes

Iteration 103
Model Output: Yes

Iteration 104
Model Output: Yes

Iteration 105
Model Output: Yes

Iteration 106
Model Output: Yes

Iteration 107
Model Output: Yes

Iteration 108
Model Output: Yes

Iteration 109
Model Output: Yes

Iteration 110
Model Output: Yes

Iteration 111
Model Output: Yes

Iteration 112
Model Output: Yes

Iteration 113
Model Output: Yes

Iteration 114
Model Output: Yes

Iteration 115
Model Output: Yes

Iteration 116
Model Output: Yes

Iteration 117
Model Output: Yes

Iteration 118
Model Output: Yes

Iteration 119
Model Output: Yes

Iteration 120
Model Output: Yes

Iteration 121
Model Output: Yes

Iteration 122
Model Output: Yes

Iteration 123
Model Output: Yes

Iteration 124
Model Output: Yes

Iteration 125
Model Output: Yes

Iteration 126
Model Output: Yes

Iteration 127
Model Output: Yes

Iteration 128
Model Output: Yes

Iteration 129
Model Output: Yes

Iteration 130
Model Output: Yes

Iteration 131
Model Output: Yes

Iteration 132
Model Output: Yes

Iteration 133
Model Output: Yes

Iteration 134
Model Output: Yes

Iteration 135
Model Output: Yes

Iteration 136
Model Output: Yes

Iteration 137
Model Output: Yes

Iteration 138
Model Output: Yes

Iteration 139
Model Output: Yes

Iteration 140
Model Output: Yes

Iteration 141
Model Output: Yes

Iteration 142
Model Output: Yes

Iteration 143
Model Output: Yes

Iteration 144
Model Output: Yes

Iteration 145
Model Output: Yes

Iteration 146
Model Output: Yes

Iteration 147
Model Output: Yes

Iteration 148
Model Output: Yes

Iteration 149
Model Output: Yes

Iteration 150
Model Output: Yes

Iteration 151
Model Output: No

Iteration 152
Model Output: Yes

Iteration 153
Model Output: Yes

Iteration 154
Model Output: Yes

Iteration 155
Model Output: Yes

Iteration 156
Model Output: Yes

Iteration 157
Model Output: Yes

Iteration 158
Model Output: Yes

Iteration 159
Model Output: Yes

Iteration 160
Model Output: Yes

Iteration 161
Model Output: No

Iteration 162
Model Output: Yes

Iteration 163
Model Output: Yes

Iteration 164
Model Output: Yes

Iteration 165
Model Output: Yes

Iteration 166
Model Output: Yes

Iteration 167
Model Output: Yes

Iteration 168
Model Output: Yes

Iteration 169
Model Output: Yes

Iteration 170
Model Output: Yes

Iteration 171
Model Output: Yes

Iteration 172
Model Output: Yes

Iteration 173
Model Output: Yes

Iteration 174
Model Output: Yes

Iteration 175
Model Output: Yes

Iteration 176
Model Output: Yes

Iteration 177
Model Output: Yes

Iteration 178
Model Output: Yes

Iteration 179
Model Output: Yes

Iteration 180
Model Output: Yes

Iteration 181
Model Output: Yes

Iteration 182
Model Output: Yes

Iteration 183
Model Output: Yes

Iteration 184
Model Output: Yes

Iteration 185
Model Output: Yes

Iteration 186
Model Output: Yes

Iteration 187
Model Output: Yes

Iteration 188
Model Output: Yes

Iteration 189
Model Output: Yes

Iteration 190
Model Output: Yes

Iteration 191
Model Output: Yes

Iteration 192
Model Output: Yes

Iteration 193
Model Output: Yes

Iteration 194
Model Output: Yes

Iteration 195
Model Output: Yes

Iteration 196
Model Output: Yes

Iteration 197
Model Output: Yes

Iteration 198
Model Output: Yes

Iteration 199
Model Output: Yes

In [52]:
predictions_new = [elem.lower() for elem in predictions]

In [53]:
print(classification_report(true_answers,predictions_new,zero_division=0))

              precision    recall  f1-score   support

          no       0.67      0.11      0.20       105
         yes       0.49      0.94      0.64        95

    accuracy                           0.51       200
   macro avg       0.58      0.53      0.42       200
weighted avg       0.58      0.51      0.41       200