# Evaluation on gemma-3-4b-it using BBEH benchmark for reasoning tasks

In [1]:
!pip install bitsandbytes

Collecting bitsandbytes
  Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.9.0+cu126)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.20.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)
Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl (59.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.1/59.1 MB 14.1 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.49.1

In [2]:
import json
import torch
import pandas as pd
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from sklearn.metrics import classification_report

In [3]:
from huggingface_hub import login
login()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [4]:
model_name = "google/gemma-3-4b-it"

In [5]:
bitsandbytes_config = BitsAndBytesConfig(load_in_4bit=True,
                                         bnb_4bit_compute_dtype=torch.float16,
                                         bnb_4bit_quant_type='nf4',
                                         bnb_4bit_use_double_quant=True)

In [6]:
tokenizer = AutoTokenizer.from_pretrained(model_name)
model= AutoModelForCausalLM.from_pretrained(model_name,
                                             quantization_config=bitsandbytes_config,
                                             device_map="auto",
                                             offload_folder="offload")

config.json:   0%|          | 0.00/855 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.16M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/33.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/90.6k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/883 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/215 [00:00<?, ?B/s]

In [7]:
def load_json(path):
  with open(path,"r") as f:
    data = json.load(f)

    df = pd.DataFrame(data['examples'])
    return df

In [8]:
def get_prompt(instruction,questions):
  prompts=[]
  for i in range(len(questions)):
    question = questions[i].split("Reply")[0]
    prompt = f"{instruction}\n\n{question}\n\nAnswer: "
    prompts.append(prompt)
  return prompts

In [22]:
def training(prompts,num_tokens=1):
    predictions = []
    for i, prompt in enumerate(prompts):
        chat = [
            {"role": "user", "content": prompt}
        ]
        formatted_prompt = tokenizer.apply_chat_template(chat, tokenize=False, add_generation_prompt=True)

        input_ids = tokenizer(formatted_prompt, return_tensors="pt").to("cuda")

        output_tokens = model.generate(
            **input_ids,
            max_new_tokens=num_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )
        new_tokens = output_tokens[0][len(input_ids[0]):]
        response = tokenizer.decode(new_tokens, skip_special_tokens=True).strip()

        print(f"Iteration {i}")
        print(f"Model Output: {response}\n")

        predictions.append(response)

    return predictions

## Task Casual Understanding

In [10]:
dataset = load_json("/content/task_casual_understanding.json")

In [11]:
dataset

                                                 input target
0    Question: Lauren and Jane work for the same co...    Yes
1    Question: Lauren and Jane work for the same co...    Yes
2    Question: The receptionist in the philosophy d...    Yes
3    Question: The receptionist in the philosophy d...     No
4    Question: Claire's parents bought her an old c...    Yes
..                                                 ...    ...
195  Question: A test tube contains a mixture. Sam ...    Yes
196  Question: Reagent X and Y are both added to a ...     No
197  Question: There is a test tube on the left and...    Yes
198  Question: Sam is heating Reagent X in a test t...    Yes
199  Question: Sam throws a poisonous test tube tow...     No

[200 rows x 2 columns]

In [12]:
questions = dataset['input'].values.tolist()

In [13]:
true_answers = dataset['target'].values.tolist()

In [14]:
instruction = f"""Instruction: You are an AI assistant for casual understanding. Read the story and answer with exactly one word:
Yes (if you think majority of people will answer yes), No (if you think majority of people will answer no), or Ambiguous(If you think that majority of people do not know the answer) . Do not add explanations.
"""

In [15]:
prompts = get_prompt(instruction,questions)

In [16]:
prompts[0]

"Instruction: You are an AI assistant for casual understanding. Read the story and answer with exactly one word:\nYes (if you think majority of people will answer yes), No (if you think majority of people will answer no), or Ambiguous(If you think that majority of people do not know the answer) . Do not add explanations.\n\n\nQuestion: Lauren and Jane work for the same company. They each need to use a computer for work sometimes. Unfortunately, the computer isn't very powerful. If two people are logged on at the same time, it usually crashes. So the company decided to institute an official policy. It declared that Lauren would be the only one permitted to use the computer in the mornings and that Jane would be the only one permitted to use the computer in the afternoons. As expected, Lauren logged on the computer the next day at 9:00 am. But Jane decided to disobey the official policy. She also logged on at 9:00 am. The computer crashed immediately. Did Jane cause the computer to crash?  \n\nAnswer: "

In [23]:
predictions = training(prompts,num_tokens=5)

Iteration 0
Model Output: Yes

Iteration 1
Model Output: Yes

Iteration 2
Model Output: Yes

Iteration 3
Model Output: Yes

Iteration 4
Model Output: Yes

Iteration 5
Model Output: Yes

Iteration 6
Model Output: Ambiguous

Iteration 7
Model Output: Ambiguous

Iteration 8
Model Output: Yes

Iteration 9
Model Output: Yes

Iteration 10
Model Output: Yes

Iteration 11
Model Output: Yes

Iteration 12
Model Output: No

Iteration 13
Model Output: Ambiguous

Iteration 14
Model Output: Yes

Iteration 15
Model Output: Yes

Iteration 16
Model Output: Yes

Iteration 17
Model Output: Yes

Iteration 18
Model Output: Yes

Iteration 19
Model Output: Yes

Iteration 20
Model Output: Yes

Iteration 21
Model Output: Yes

Iteration 22
Model Output: Yes

Iteration 23
Model Output: Yes

Iteration 24
Model Output: Yes

Iteration 25
Model Output: Yes

Iteration 26
Model Output: No

Iteration 27
Model Output: Yes

Iteration 28
Model Output: Yes

Iteration 29
Model Output: Yes

Iteration 30
Model Output: Yes

Iteration 31
Model Output: Yes

Iteration 32
Model Output: Yes

Iteration 33
Model Output: Yes

Iteration 34
Model Output: Yes

Iteration 35
Model Output: Yes

Iteration 36
Model Output: Yes

Iteration 37
Model Output: Yes

Iteration 38
Model Output: Ambiguous

Iteration 39
Model Output: Yes

Iteration 40
Model Output: Yes

Iteration 41
Model Output: Yes

Iteration 42
Model Output: Yes

Iteration 43
Model Output: Yes

Iteration 44
Model Output: Yes

Iteration 45
Model Output: Yes

Iteration 46
Model Output: Yes

Iteration 47
Model Output: Yes

Iteration 48
Model Output: Yes

Iteration 49
Model Output: Yes

Iteration 50
Model Output: Yes

Iteration 51
Model Output: Yes

Iteration 52
Model Output: Yes

Iteration 53
Model Output: Yes

Iteration 54
Model Output: Yes

Iteration 55
Model Output: Yes

Iteration 56
Model Output: Yes

Iteration 57
Model Output: Yes

Iteration 58
Model Output: Yes

Iteration 59
Model Output: Yes

Iteration 60
Model Output: Yes

Iteration 61
Model Output: Yes

Iteration 62
Model Output: Yes

Iteration 63
Model Output: Yes

Iteration 64
Model Output: Yes

Iteration 65
Model Output: Yes

Iteration 66
Model Output: Yes

Iteration 67
Model Output: Yes

Iteration 68
Model Output: Yes

Iteration 69
Model Output: Yes

Iteration 70
Model Output: Yes

Iteration 71
Model Output: Yes

Iteration 72
Model Output: Yes

Iteration 73
Model Output: Yes

Iteration 74
Model Output: Yes

Iteration 75
Model Output: Yes

Iteration 76
Model Output: Yes

Iteration 77
Model Output: Yes

Iteration 78
Model Output: Yes

Iteration 79
Model Output: Yes

Iteration 80
Model Output: Yes

Iteration 81
Model Output: Yes

Iteration 82
Model Output: Yes

Iteration 83
Model Output: Yes

Iteration 84
Model Output: Yes

Iteration 85
Model Output: Yes

Iteration 86
Model Output: Yes

Iteration 87
Model Output: Yes

Iteration 88
Model Output: Ambiguous

Iteration 89
Model Output: No

Iteration 90
Model Output: No

Iteration 91
Model Output: Yes

Iteration 92
Model Output: Yes

Iteration 93
Model Output: Yes

Iteration 94
Model Output: Yes

Iteration 95
Model Output: Yes

Iteration 96
Model Output: Yes

Iteration 97
Model Output: Yes

Iteration 98
Model Output: Yes

Iteration 99
Model Output: Yes

Iteration 100
Model Output: Ambiguous

Iteration 101
Model Output: Ambiguous

Iteration 102
Model Output: Yes

Iteration 103
Model Output: Yes

Iteration 104
Model Output: Yes

Iteration 105
Model Output: Yes

Iteration 106
Model Output: Yes

Iteration 107
Model Output: Yes

Iteration 108
Model Output: Yes

Iteration 109
Model Output: Yes

Iteration 110
Model Output: Yes

Iteration 111
Model Output: Yes

Iteration 112
Model Output: Yes

Iteration 113
Model Output: Yes

Iteration 114
Model Output: Yes

Iteration 115
Model Output: Yes

Iteration 116
Model Output: Yes

Iteration 117
Model Output: Yes

Iteration 118
Model Output: Yes

Iteration 119
Model Output: Yes

Iteration 120
Model Output: Yes

Iteration 121
Model Output: Yes

Iteration 122
Model Output: Ambiguous

Iteration 123
Model Output: Ambiguous

Iteration 124
Model Output: Yes

Iteration 125
Model Output: Yes

Iteration 126
Model Output: Yes

Iteration 127
Model Output: Yes

Iteration 128
Model Output: Yes

Iteration 129
Model Output: Yes

Iteration 130
Model Output: Yes

Iteration 131
Model Output: Yes

Iteration 132
Model Output: Yes

Iteration 133
Model Output: Yes

Iteration 134
Model Output: Yes

Iteration 135
Model Output: Yes

Iteration 136
Model Output: Ambiguous

Iteration 137
Model Output: Yes

Iteration 138
Model Output: Yes

Iteration 139
Model Output: Yes

Iteration 140
Model Output: Yes

Iteration 141
Model Output: Yes

Iteration 142
Model Output: Yes

Iteration 143
Model Output: Yes

Iteration 144
Model Output: Yes

Iteration 145
Model Output: Yes

Iteration 146
Model Output: Yes

Iteration 147
Model Output: Yes

Iteration 148
Model Output: Ambiguous

Iteration 149
Model Output: Yes

Iteration 150
Model Output: Yes

Iteration 151
Model Output: Yes

Iteration 152
Model Output: Yes

Iteration 153
Model Output: Yes

Iteration 154
Model Output: Yes

Iteration 155
Model Output: Yes

Iteration 156
Model Output: Yes

Iteration 157
Model Output: Yes

Iteration 158
Model Output: Yes

Iteration 159
Model Output: Yes

Iteration 160
Model Output: Yes

Iteration 161
Model Output: Yes

Iteration 162
Model Output: Yes

Iteration 163
Model Output: No

Iteration 164
Model Output: Yes

Iteration 165
Model Output: Yes

Iteration 166
Model Output: Yes

Iteration 167
Model Output: Yes

Iteration 168
Model Output: Yes

Iteration 169
Model Output: Yes

Iteration 170
Model Output: Yes

Iteration 171
Model Output: Yes

Iteration 172
Model Output: Yes

Iteration 173
Model Output: Yes

Iteration 174
Model Output: Yes

Iteration 175
Model Output: Yes

Iteration 176
Model Output: Yes

Iteration 177
Model Output: Yes

Iteration 178
Model Output: Yes

Iteration 179
Model Output: Yes

Iteration 180
Model Output: Yes

Iteration 181
Model Output: Yes

Iteration 182
Model Output: Yes

Iteration 183
Model Output: Yes

Iteration 184
Model Output: Yes

Iteration 185
Model Output: Yes

Iteration 186
Model Output: Yes

Iteration 187
Model Output: Yes

Iteration 188
Model Output: Yes

Iteration 189
Model Output: Yes

Iteration 190
Model Output: Yes

Iteration 191
Model Output: No

Iteration 192
Model Output: Yes

Iteration 193
Model Output: Yes

Iteration 194
Model Output: Yes

Iteration 195
Model Output: Yes

Iteration 196
Model Output: No

Iteration 197
Model Output: Yes

Iteration 198
Model Output: Yes

Iteration 199
Model Output: Yes

In [24]:
predictions[:10]

['Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Ambiguous',
 'Ambiguous',
 'Yes',
 'Yes']

In [25]:
print(classification_report(true_answers,predictions,zero_division=0))

              precision    recall  f1-score   support

   Ambiguous       0.27      0.07      0.11        45
          No       0.71      0.06      0.11        80
         Yes       0.39      0.95      0.55        75

    accuracy                           0.40       200
   macro avg       0.46      0.36      0.26       200
weighted avg       0.49      0.40      0.28       200

## Task Movie Recommendation

In [26]:
dataset = load_json("/content/task_movie_recommendation.json")

In [27]:
dataset

                                                 input target
0    Which option has more similar movies in terms ...    (E)
1    Which option has more similar movies in terms ...    (C)
2    Which option has more similar movies in terms ...    (C)
3    Which option has more similar movies in terms ...    (A)
4    Which option has more similar movies in terms ...    (I)
..                                                 ...    ...
195  Which option has more similar movies in terms ...    (E)
196  Which option has more similar movies in terms ...    (E)
197  Which option has more similar movies in terms ...    (E)
198  Which option has more similar movies in terms ...    (A)
199  Which option has more similar movies in terms ...    (F)

[200 rows x 2 columns]

In [28]:
dataset["target"].value_counts()

target
(A)    26
(G)    22
(H)    21
(E)    21
(J)    20
(D)    20
(C)    18
(F)    18
(B)    17
(I)    17
Name: count, dtype: int64

In [29]:
questions = dataset['input'].values.tolist()

In [30]:
true_answers = dataset['target'].values.tolist()

In [31]:
true_answers = [x.strip("()").upper() for x in true_answers]
true_answers[:10]

['E', 'C', 'C', 'A', 'I', 'D', 'B', 'F', 'D', 'H']

In [44]:
instruction = f"""You are an assistant that determines which group of movies is most similar in terms of what people are likely to enjoy together. Reply only with the letter (A, B, C, D, E, F, G, H, I, or J) of the group that is most similar.
Do not write any explanation, full movie names, or extra text. The answer must be a single uppercase letter."""

In [45]:
prompts = get_prompt(instruction,questions)

In [46]:
prompts[1]

'You are an assistant that determines which group of movies is most similar in terms of what people are likely to enjoy together. Reply only with the letter (A, B, C, D, E, F, G, H, I, or J) of the group that is most similar.\nDo not write any explanation, full movie names, or extra text. The answer must be a single uppercase letter.\n\nWhich option has more similar movies in terms of whether a group of people will like them or not?\nOptions:\n(A) Street Fighter II The Animated Movie, The Sixth Sense, The Matrix, The Shawshank Redemption, Terminator 2 Judgment Day\n(B) The Boy Who Could Fly, The Sheltering Sky, Forrest Gump, Terminator 2 Judgment Day, The Matrix\n(C) Forrest Gump, The Shawshank Redemption, Terminator 2 Judgment Day, The Matrix, The Sixth Sense\n(D) The Boy Who Could Fly, The Sheltering Sky, Street Fighter II The Animated Movie, The Sixth Sense, Terminator 2 Judgment Day\n(E) The Matrix, The Boy Who Could Fly, Forrest Gump, The Shawshank Redemption, The Sixth Sense\n(F) The Boy Who Could Fly, The Matrix, Terminator 2 Judgment Day, The Sixth Sense, Forrest Gump\n(G) The Shawshank Redemption, Street Fighter II The Animated Movie, The Sheltering Sky, The Matrix, The Boy Who Could Fly\n(H) Street Fighter II The Animated Movie, The Matrix, The Sixth Sense, The Shawshank Redemption, The Sheltering Sky\n(I) The Sheltering Sky, Street Fighter II The Animated Movie, Forrest Gump, Terminator 2 Judgment Day, The Boy Who Could Fly\n(J) Street Fighter II The Animated Movie, The Sixth Sense, The Boy Who Could Fly, The Shawshank Redemption, Forrest Gump\n\n\nAnswer: '

In [47]:
predictions = training(prompts,num_tokens=5)

Iteration 0
Model Output: A

Iteration 1
Model Output: C

Iteration 2
Model Output: C

Iteration 3
Model Output: A

Iteration 4
Model Output: B

Iteration 5
Model Output: B

Iteration 6
Model Output: B

Iteration 7
Model Output: B

Iteration 8
Model Output: C

Iteration 9
Model Output: J

Iteration 10
Model Output: A

Iteration 11
Model Output: A

Iteration 12
Model Output: A

Iteration 13
Model Output: A

Iteration 14
Model Output: B

Iteration 15
Model Output: J

Iteration 16
Model Output: B

Iteration 17
Model Output: C

Iteration 18
Model Output: A

Iteration 19
Model Output: B

Iteration 20
Model Output: A

Iteration 21
Model Output: A

Iteration 22
Model Output: C

Iteration 23
Model Output: H

Iteration 24
Model Output: A

Iteration 25
Model Output: A

Iteration 26
Model Output: B

Iteration 27
Model Output: A

Iteration 28
Model Output: A

Iteration 29
Model Output: A

Iteration 30
Model Output: C

Iteration 31
Model Output: C

Iteration 32
Model Output: A

Iteration 33
Model Output: A

Iteration 34
Model Output: D

Iteration 35
Model Output: A

Iteration 36
Model Output: B

Iteration 37
Model Output: A

Iteration 38
Model Output: A

Iteration 39
Model Output: H

Iteration 40
Model Output: B

Iteration 41
Model Output: C

Iteration 42
Model Output: H

Iteration 43
Model Output: C

Iteration 44
Model Output: A

Iteration 45
Model Output: C

Iteration 46
Model Output: C

Iteration 47
Model Output: A

Iteration 48
Model Output: H

Iteration 49
Model Output: A

Iteration 50
Model Output: A

Iteration 51
Model Output: C

Iteration 52
Model Output: A

Iteration 53
Model Output: I

Iteration 54
Model Output: C

Iteration 55
Model Output: A

Iteration 56
Model Output: A

Iteration 57
Model Output: A

Iteration 58
Model Output: A

Iteration 59
Model Output: C

Iteration 60
Model Output: C

Iteration 61
Model Output: B

Iteration 62
Model Output: B

Iteration 63
Model Output: A

Iteration 64
Model Output: A

Iteration 65
Model Output: A

Iteration 66
Model Output: A

Iteration 67
Model Output: A

Iteration 68
Model Output: A

Iteration 69
Model Output: C

Iteration 70
Model Output: H

Iteration 71
Model Output: I

Iteration 72
Model Output: A

Iteration 73
Model Output: A

Iteration 74
Model Output: A

Iteration 75
Model Output: B

Iteration 76
Model Output: J

Iteration 77
Model Output: C

Iteration 78
Model Output: B

Iteration 79
Model Output: A

Iteration 80
Model Output: I

Iteration 81
Model Output: C

Iteration 82
Model Output: A

Iteration 83
Model Output: A

Iteration 84
Model Output: C

Iteration 85
Model Output: F

Iteration 86
Model Output: A

Iteration 87
Model Output: C

Iteration 88
Model Output: A

Iteration 89
Model Output: J

Iteration 90
Model Output: A

Iteration 91
Model Output: A

Iteration 92
Model Output: B

Iteration 93
Model Output: J

Iteration 94
Model Output: A

Iteration 95
Model Output: C

Iteration 96
Model Output: A

Iteration 97
Model Output: C

Iteration 98
Model Output: A

Iteration 99
Model Output: A

Iteration 100
Model Output: A

Iteration 101
Model Output: B

Iteration 102
Model Output: C

Iteration 103
Model Output: C

Iteration 104
Model Output: A

Iteration 105
Model Output: A

Iteration 106
Model Output: C

Iteration 107
Model Output: C

Iteration 108
Model Output: A

Iteration 109
Model Output: H

Iteration 110
Model Output: A

Iteration 111
Model Output: B

Iteration 112
Model Output: B

Iteration 113
Model Output: A

Iteration 114
Model Output: A

Iteration 115
Model Output: A

Iteration 116
Model Output: C

Iteration 117
Model Output: G

Iteration 118
Model Output: A

Iteration 119
Model Output: J

Iteration 120
Model Output: A

Iteration 121
Model Output: B

Iteration 122
Model Output: A

Iteration 123
Model Output: A

Iteration 124
Model Output: C

Iteration 125
Model Output: B

Iteration 126
Model Output: B

Iteration 127
Model Output: A

Iteration 128
Model Output: B

Iteration 129
Model Output: J

Iteration 130
Model Output: A

Iteration 131
Model Output: A

Iteration 132
Model Output: A

Iteration 133
Model Output: A

Iteration 134
Model Output: H

Iteration 135
Model Output: B

Iteration 136
Model Output: D

Iteration 137
Model Output: A

Iteration 138
Model Output: C

Iteration 139
Model Output: C

Iteration 140
Model Output: C

Iteration 141
Model Output: D

Iteration 142
Model Output: G

Iteration 143
Model Output: G

Iteration 144
Model Output: A

Iteration 145
Model Output: J

Iteration 146
Model Output: A

Iteration 147
Model Output: A

Iteration 148
Model Output: A

Iteration 149
Model Output: A

Iteration 150
Model Output: A

Iteration 151
Model Output: A

Iteration 152
Model Output: C

Iteration 153
Model Output: B

Iteration 154
Model Output: A

Iteration 155
Model Output: B

Iteration 156
Model Output: A

Iteration 157
Model Output: C

Iteration 158
Model Output: A

Iteration 159
Model Output: J

Iteration 160
Model Output: A

Iteration 161
Model Output: C

Iteration 162
Model Output: A

Iteration 163
Model Output: C

Iteration 164
Model Output: H

Iteration 165
Model Output: A

Iteration 166
Model Output: C

Iteration 167
Model Output: A

Iteration 168
Model Output: B

Iteration 169
Model Output: C

Iteration 170
Model Output: C

Iteration 171
Model Output: A

Iteration 172
Model Output: B

Iteration 173
Model Output: A

Iteration 174
Model Output: A

Iteration 175
Model Output: A

Iteration 176
Model Output: A

Iteration 177
Model Output: B

Iteration 178
Model Output: B

Iteration 179
Model Output: A

Iteration 180
Model Output: C

Iteration 181
Model Output: A

Iteration 182
Model Output: B

Iteration 183
Model Output: F

Iteration 184
Model Output: A

Iteration 185
Model Output: A

Iteration 186
Model Output: A

Iteration 187
Model Output: J

Iteration 188
Model Output: B

Iteration 189
Model Output: B

Iteration 190
Model Output: C

Iteration 191
Model Output: C

Iteration 192
Model Output: A

Iteration 193
Model Output: C

Iteration 194
Model Output: F

Iteration 195
Model Output: J

Iteration 196
Model Output: F

Iteration 197
Model Output: A

Iteration 198
Model Output: A

Iteration 199
Model Output: A

In [48]:
predictions[:10]

['A', 'C', 'C', 'A', 'B', 'B', 'B', 'B', 'C', 'J']

In [49]:
print(classification_report(true_answers,predictions,zero_division=0))

              precision    recall  f1-score   support

           A       0.20      0.73      0.32        26
           B       0.16      0.29      0.20        17
           C       0.14      0.33      0.20        18
           D       0.67      0.10      0.17        20
           E       0.00      0.00      0.00        21
           F       0.25      0.06      0.09        18
           G       1.00      0.14      0.24        22
           H       0.38      0.14      0.21        21
           I       0.33      0.06      0.10        17
           J       0.27      0.15      0.19        20

    accuracy                           0.21       200
   macro avg       0.34      0.20      0.17       200
weighted avg       0.35      0.21      0.18       200

## Task Disambiguation QA

In [52]:
dataset = load_json("/content/task_disambiguationQA.json")

In [53]:
dataset['target'].value_counts()

target
(B)    25
(D)    24
(C)    23
(A)    22
(E)    17
(F)     7
(G)     1
(H)     1
Name: count, dtype: int64

In [67]:
dataset

                                                 input target
0    Here is a sentence with pronoun(s) whose antec...    (A)
1    Here is a sentence with pronoun(s) whose antec...    (D)
2    Here is a sentence with pronoun(s) whose antec...    (E)
3    Here is a sentence with pronoun(s) whose antec...    (B)
4    Here is a sentence with pronoun(s) whose antec...    (A)
..                                                 ...    ...
115  Here is a sentence with pronoun(s) whose antec...    (D)
116  Here is a sentence with pronoun(s) whose antec...    (A)
117  Here is a sentence with pronoun(s) whose antec...    (B)
118  Here is a sentence with pronoun(s) whose antec...    (D)
119  Here is a sentence with pronoun(s) whose antec...    (E)

[120 rows x 2 columns]

In [54]:
questions = dataset['input'].values.tolist()

In [68]:
questions[0]

'Here is a sentence with pronoun(s) whose antecedent(s) can either be derived from the context or is ambiguous.\nSentence: The visitor tells the teacher that she likes the cake, and then tells the chef that it was her favorite dish.\nWhich of the following options correctly explains the antecedent(s) of the pronoun(s)?\n(A) The visitor likes cake and the visitor told the chef.\n(B) The teacher likes cake and the teacher told the chef.\n(C) The visitor likes cake and the teacher told the chef.\n(D) The teacher likes cake and the visitor told the chef.\n(E) Ambiguous.'

In [55]:
true_answers = dataset['target'].values.tolist()

In [56]:
true_answers = [x.strip("()").upper() for x in true_answers]
true_answers[:10]

['A', 'D', 'E', 'B', 'A', 'B', 'B', 'A', 'C', 'D']

In [69]:
instruction = f"""Instruction: You are a linguistics expert specializing in coreference resolution.
Task: Read the sentence and the provided options. Identify the correct antecedent(s) for the pronouns based strictly on the context and causal logic provided.
Constraint: Output ONLY the uppercase letter corresponding to the correct option. Do not explain your reasoning.
"""

In [70]:
prompts = get_prompt(instruction,questions)

In [71]:
prompts[1]

'Instruction: You are a linguistics expert specializing in coreference resolution. \nTask: Read the sentence and the provided options. Identify the correct antecedent(s) for the pronouns based strictly on the context and causal logic provided.\nConstraint: Output ONLY the uppercase letter corresponding to the correct option. Do not explain your reasoning.\n\n\nHere is a sentence with pronoun(s) whose antecedent(s) can either be derived from the context or is ambiguous.\nSentence: The designer called the janitor and asked him to clean the room as soon as possible, but he went to fetch a cup of coffee first and then returned to his desk.\nWhich of the following options correctly explains the antecedent(s) of the pronoun(s)?\n(A) Designer is cleaning the room as soon as possible and got coffee.\n(B) Janitor is cleaning the room as soon as possible and got coffee.\n(C) Designer is cleaning the room as soon as possible and janitor got coffee.\n(D) Janitor is cleaning the room as soon as possible and designer got coffee.\n(E) Ambiguous.\n\nAnswer: '

In [74]:
predictions = training(prompts,num_tokens=5)

Iteration 0
Model Output: B

Iteration 1
Model Output: B

Iteration 2
Model Output: B

Iteration 3
Model Output: B

Iteration 4
Model Output: B

Iteration 5
Model Output: B

Iteration 6
Model Output: B

Iteration 7
Model Output: C

Iteration 8
Model Output: B

Iteration 9
Model Output: B

Iteration 10
Model Output: C

Iteration 11
Model Output: C

Iteration 12
Model Output: B

Iteration 13
Model Output: B

Iteration 14
Model Output: B

Iteration 15
Model Output: C

Iteration 16
Model Output: D

Iteration 17
Model Output: C

Iteration 18
Model Output: C

Iteration 19
Model Output: B

Iteration 20
Model Output: B

Iteration 21
Model Output: D

Iteration 22
Model Output: B

Iteration 23
Model Output: C

Iteration 24
Model Output: B

Iteration 25
Model Output: B

Iteration 26
Model Output: B

Iteration 27
Model Output: B

Iteration 28
Model Output: A

Iteration 29
Model Output: B

Iteration 30
Model Output: C

Iteration 31
Model Output: E

Iteration 32
Model Output: B

Iteration 33
Model Output: B

Iteration 34
Model Output: B

Iteration 35
Model Output: C

Iteration 36
Model Output: A

Iteration 37
Model Output: B

Iteration 38
Model Output: A

Iteration 39
Model Output: C

Iteration 40
Model Output: B

Iteration 41
Model Output: B

Iteration 42
Model Output: B

Iteration 43
Model Output: B

Iteration 44
Model Output: C

Iteration 45
Model Output: C

Iteration 46
Model Output: D

Iteration 47
Model Output: C

Iteration 48
Model Output: B

Iteration 49
Model Output: B

Iteration 50
Model Output: C

Iteration 51
Model Output: A

Iteration 52
Model Output: B

Iteration 53
Model Output: B

Iteration 54
Model Output: B

Iteration 55
Model Output: C

Iteration 56
Model Output: D

Iteration 57
Model Output: A

Iteration 58
Model Output: B

Iteration 59
Model Output: E

Iteration 60
Model Output: C

Iteration 61
Model Output: B

Iteration 62
Model Output: A

Iteration 63
Model Output: B

Iteration 64
Model Output: B

Iteration 65
Model Output: C

Iteration 66
Model Output: B

Iteration 67
Model Output: C

Iteration 68
Model Output: C

Iteration 69
Model Output: B

Iteration 70
Model Output: C

Iteration 71
Model Output: B

Iteration 72
Model Output: B

Iteration 73
Model Output: B

Iteration 74
Model Output: B

Iteration 75
Model Output: A

Iteration 76
Model Output: C

Iteration 77
Model Output: B

Iteration 78
Model Output: A

Iteration 79
Model Output: B

Iteration 80
Model Output: B

Iteration 81
Model Output: C

Iteration 82
Model Output: B

Iteration 83
Model Output: B

Iteration 84
Model Output: C

Iteration 85
Model Output: B

Iteration 86
Model Output: B

Iteration 87
Model Output: A

Iteration 88
Model Output: B

Iteration 89
Model Output: B

Iteration 90
Model Output: A

Iteration 91
Model Output: E

Iteration 92
Model Output: B

Iteration 93
Model Output: B

Iteration 94
Model Output: C

Iteration 95
Model Output: C

Iteration 96
Model Output: B

Iteration 97
Model Output: C

Iteration 98
Model Output: B

Iteration 99
Model Output: B

Iteration 100
Model Output: B

Iteration 101
Model Output: C

Iteration 102
Model Output: B

Iteration 103
Model Output: B

Iteration 104
Model Output: B

Iteration 105
Model Output: B

Iteration 106
Model Output: C

Iteration 107
Model Output: B

Iteration 108
Model Output: C

Iteration 109
Model Output: B

Iteration 110
Model Output: B

Iteration 111
Model Output: B

Iteration 112
Model Output: C

Iteration 113
Model Output: D

Iteration 114
Model Output: C

Iteration 115
Model Output: B

Iteration 116
Model Output: C

Iteration 117
Model Output: B

Iteration 118
Model Output: E

Iteration 119
Model Output: B

In [75]:
predictions

['B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'B',
 'C',
 'B',
 'B',
 'C',
 'C',
 'B',
 'B',
 'B',
 'C',
 'D',
 'C',
 'C',
 'B',
 'B',
 'D',
 'B',
 'C',
 'B',
 'B',
 'B',
 'B',
 'A',
 'B',
 'C',
 'E',
 'B',
 'B',
 'B',
 'C',
 'A',
 'B',
 'A',
 'C',
 'B',
 'B',
 'B',
 'B',
 'C',
 'C',
 'D',
 'C',
 'B',
 'B',
 'C',
 'A',
 'B',
 'B',
 'B',
 'C',
 'D',
 'A',
 'B',
 'E',
 'C',
 'B',
 'A',
 'B',
 'B',
 'C',
 'B',
 'C',
 'C',
 'B',
 'C',
 'B',
 'B',
 'B',
 'B',
 'A',
 'C',
 'B',
 'A',
 'B',
 'B',
 'C',
 'B',
 'B',
 'C',
 'B',
 'B',
 'A',
 'B',
 'B',
 'A',
 'E',
 'B',
 'B',
 'C',
 'C',
 'B',
 'C',
 'B',
 'B',
 'B',
 'C',
 'B',
 'B',
 'B',
 'B',
 'C',
 'B',
 'C',
 'B',
 'B',
 'B',
 'C',
 'D',
 'C',
 'B',
 'C',
 'B',
 'E',
 'B']

In [76]:
print(classification_report(true_answers,predictions,zero_division=0))

              precision    recall  f1-score   support

           A       0.20      0.09      0.12        22
           B       0.23      0.64      0.34        25
           C       0.25      0.35      0.29        23
           D       0.60      0.12      0.21        24
           E       0.25      0.06      0.10        17
           F       0.00      0.00      0.00         7
           G       0.00      0.00      0.00         1
           H       0.00      0.00      0.00         1

    accuracy                           0.25       120
   macro avg       0.19      0.16      0.13       120
weighted avg       0.29      0.25      0.20       120

## Task: Boolean Expressions

In [77]:
dataset = load_json("/content/task_boolean_expressions.json")

In [78]:
dataset

                                                 input target
0    From the following five expressions, only one ...    (E)
1    From the following five expressions, only one ...    (C)
2    From the following five expressions, only one ...    (E)
3    From the following five expressions, only one ...    (D)
4    From the following five expressions, only one ...    (C)
..                                                 ...    ...
195  From the following five expressions, only one ...    (A)
196  From the following five expressions, only one ...    (B)
197  From the following five expressions, only one ...    (B)
198  From the following five expressions, only one ...    (C)
199  From the following five expressions, only one ...    (A)

[200 rows x 2 columns]

In [79]:
dataset["target"].value_counts()

target
(E)    43
(B)    41
(C)    40
(A)    39
(D)    37
Name: count, dtype: int64

In [80]:
questions = dataset["input"].values.tolist()

In [81]:
true_answers = dataset["target"].values.tolist()

In [83]:
true_answers = [x.strip("()").upper() for x in true_answers]
true_answers[:10]

['E', 'C', 'E', 'D', 'C', 'D', 'C', 'D', 'A', 'A']

In [82]:
questions[0]

'From the following five expressions, only one evaluates to true. Which one is it?\n\n(A) not (not (not (not (False) or (-5 - (1 / -5) is greater than -7)) or (not (False) or (-5 * -10 + -5 * -6 is greater than -4 * 6))) or (not (not (False) or (False)) or (not not not (-3 - (-2 / 4) is greater than -6) and not not (The capital of India is Mumbai.)))) and (not (not (not (The capital of the Nigeria is Abuja.) or (-7 - (-4 / 7) > 4)) or (not (-6 - (-7 / -5) > -6) and (True))) and (not not ((-1 * 9 is less than or equal to -6) or (-4 * 10 + -1 * -7 <= 9 * 10)) or not not not (not not (6 * -2 is less than or equal to 4) or not not not (-5 * 9 + 6 * -3 <= -9 * 6))))\n(B) ((not (not not not (not (not (not not not (not not (not (not (max(-3, 8, 5, -2) - min(-3, 8, 5, -2) <= 4) and (False)) or (max(-6, 8, 5, -1) - min(-6, 8, 5, -1) <= 9)) or not not not (-6 - (9 / -1) is less than or equal to 6)) and not not (The capital of Afghanistan is Kabul.)) or (1 - (5 / -2) > 4)) or (True)) and not not (-3 * -8 <= 1)) and (9 * -1 + -6 * 7 > 10 * 10)) or (The capital of Denmark is Aarhus.)) and (9 * 8 + 7 * 10 is less than or equal to 5 * 10)\n(C) not ((not not (not not (not (not not (not (not not not (5 - (6 / 2) > 5) and not not (True)) or (3 * -7 + 3 * -2 <= -6 * 2)) or not not not (False)) and (-9 - (-2 / 3) > 6)) or not not not (max(8, -1, -7, -6) - min(8, -1, -7, -6) is greater than 1)) or not not not (max(9, -4, -3, -4) - min(9, -4, -3, -4) is greater than 3)) and (The capital of Turkey is Istanbul.)) and (2 * 3 + 10 * -9 > -7 * -8)\n(D) not (not (not (not (The capital of Jordan is Amman.) or (max(7, 3, -2, 10) - min(7, 3, -2, 10) is greater than 7)) or (not not not (The capital of Colombia is Bogota.) and not not (The capital of Afghanistan is Kandahar.))) and (not (not not (-4 - (2 / -1) <= -6) or not not not (max(8, -6, -6, 9) - min(8, -6, -6, 9) is greater than 1)) or (not (The capital of Iraq is Beirut.) or (-6 * 1 > -6)))) and (not not not (not not not (not (The capital of Norway is Bergen.) and (The capital of Norway is Bergen.)) and not not (not not not (True) and not not (The capital of Denmark is Copenhagen.))) and not not (not (not (True) or (The capital of Canada is Ottawa.)) and ((False) or (max(9, 3, -7, 9) - min(9, 3, -7, 9) is greater than 6))))\n(E) not ((not (not (not not (not not ((not (not (not ((False) or (1 * 6 + 6 * 1 <= -10 * -4)) and (-6 * 7 > 5)) or (-3 * -3 + 3 * -2 <= -5 * -7)) or (The capital of Colombia is Medellin.)) or (-3 * 6 > 6)) or not not not (max(-10, 9, -2, -7) - min(-10, 9, -2, -7) is greater than 3)) or not not not (-3 * -2 + -4 * -5 is greater than 1 * 5)) or (7 * -3 > -9)) or (max(2, -4, 3, -3) - min(2, -4, 3, -3) > 8)) and (False)) and (8 * -2 is less than or equal to -8)\n'

In [ ]:
instruction = f"""Instruction: You are a high-level logic and reasoning engine.
Task: Carefully evaluate the five nested Boolean expressions (A, B, C, D, E) provided.
Method:
1. Break down each expression into its sub-components.
2. Evaluate the truth value of the geographic facts (Capitals).
3. Solve the mathematical inequalities.
4. Simplify the 'not' operators step-by-step.
Constraint: After your internal evaluation, identify the ONLY expression that is True.
Output Format: Output exactly one uppercase letter (A, B, C, D, or E) as the final result."""

In [84]:
prompts = get_prompt(instruction,questions)

In [85]:
prompts[0]

'Instruction: You are a linguistics expert specializing in coreference resolution. \nTask: Read the sentence and the provided options. Identify the correct antecedent(s) for the pronouns based strictly on the context and causal logic provided.\nConstraint: Output ONLY the uppercase letter corresponding to the correct option. Do not explain your reasoning.\n\n\nFrom the following five expressions, only one evaluates to true. Which one is it?\n\n(A) not (not (not (not (False) or (-5 - (1 / -5) is greater than -7)) or (not (False) or (-5 * -10 + -5 * -6 is greater than -4 * 6))) or (not (not (False) or (False)) or (not not not (-3 - (-2 / 4) is greater than -6) and not not (The capital of India is Mumbai.)))) and (not (not (not (The capital of the Nigeria is Abuja.) or (-7 - (-4 / 7) > 4)) or (not (-6 - (-7 / -5) > -6) and (True))) and (not not ((-1 * 9 is less than or equal to -6) or (-4 * 10 + -1 * -7 <= 9 * 10)) or not not not (not not (6 * -2 is less than or equal to 4) or not not not (-5 * 9 + 6 * -3 <= -9 * 6))))\n(B) ((not (not not not (not (not (not not not (not not (not (not (max(-3, 8, 5, -2) - min(-3, 8, 5, -2) <= 4) and (False)) or (max(-6, 8, 5, -1) - min(-6, 8, 5, -1) <= 9)) or not not not (-6 - (9 / -1) is less than or equal to 6)) and not not (The capital of Afghanistan is Kabul.)) or (1 - (5 / -2) > 4)) or (True)) and not not (-3 * -8 <= 1)) and (9 * -1 + -6 * 7 > 10 * 10)) or (The capital of Denmark is Aarhus.)) and (9 * 8 + 7 * 10 is less than or equal to 5 * 10)\n(C) not ((not not (not not (not (not not (not (not not not (5 - (6 / 2) > 5) and not not (True)) or (3 * -7 + 3 * -2 <= -6 * 2)) or not not not (False)) and (-9 - (-2 / 3) > 6)) or not not not (max(8, -1, -7, -6) - min(8, -1, -7, -6) is greater than 1)) or not not not (max(9, -4, -3, -4) - min(9, -4, -3, -4) is greater than 3)) and (The capital of Turkey is Istanbul.)) and (2 * 3 + 10 * -9 > -7 * -8)\n(D) not (not (not (not (The capital of Jordan is Amman.) or (max(7, 3, -2, 10) - min(7, 3, -2, 10) is greater than 7)) or (not not not (The capital of Colombia is Bogota.) and not not (The capital of Afghanistan is Kandahar.))) and (not (not not (-4 - (2 / -1) <= -6) or not not not (max(8, -6, -6, 9) - min(8, -6, -6, 9) is greater than 1)) or (not (The capital of Iraq is Beirut.) or (-6 * 1 > -6)))) and (not not not (not not not (not (The capital of Norway is Bergen.) and (The capital of Norway is Bergen.)) and not not (not not not (True) and not not (The capital of Denmark is Copenhagen.))) and not not (not (not (True) or (The capital of Canada is Ottawa.)) and ((False) or (max(9, 3, -7, 9) - min(9, 3, -7, 9) is greater than 6))))\n(E) not ((not (not (not not (not not ((not (not (not ((False) or (1 * 6 + 6 * 1 <= -10 * -4)) and (-6 * 7 > 5)) or (-3 * -3 + 3 * -2 <= -5 * -7)) or (The capital of Colombia is Medellin.)) or (-3 * 6 > 6)) or not not not (max(-10, 9, -2, -7) - min(-10, 9, -2, -7) is greater than 3)) or not not not (-3 * -2 + -4 * -5 is greater than 1 * 5)) or (7 * -3 > -9)) or (max(2, -4, 3, -3) - min(2, -4, 3, -3) > 8)) and (False)) and (8 * -2 is less than or equal to -8)\n\n\nAnswer: '

In [86]:
predictions = training(prompts,num_tokens=5)

Iteration 0
Model Output: E

Iteration 1
Model Output: C

Iteration 2
Model Output: C

Iteration 3
Model Output: C

Iteration 4
Model Output: C

Iteration 5
Model Output: D

Iteration 6
Model Output: C

Iteration 7
Model Output: C

Iteration 8
Model Output: A

Iteration 9
Model Output: C

Iteration 10
Model Output: C

Iteration 11
Model Output: C

Iteration 12
Model Output: C

Iteration 13
Model Output: C

Iteration 14
Model Output: C

Iteration 15
Model Output: C

Iteration 16
Model Output: A

Iteration 17
Model Output: A

Iteration 18
Model Output: C

Iteration 19
Model Output: C

Iteration 20
Model Output: C

Iteration 21
Model Output: C

Iteration 22
Model Output: C

Iteration 23
Model Output: C

Iteration 24
Model Output: E

Iteration 25
Model Output: A

Iteration 26
Model Output: D

Iteration 27
Model Output: C

Iteration 28
Model Output: C

Iteration 29
Model Output: D

Iteration 30
Model Output: C

Iteration 31
Model Output: C

Iteration 32
Model Output: C

Iteration 33
Model Output: C

Iteration 34
Model Output: A

Iteration 35
Model Output: C

Iteration 36
Model Output: E

Iteration 37
Model Output: C

Iteration 38
Model Output: C

Iteration 39
Model Output: C

Iteration 40
Model Output: D

Iteration 41
Model Output: C

Iteration 42
Model Output: A

Iteration 43
Model Output: E

Iteration 44
Model Output: C

Iteration 45
Model Output: C

Iteration 46
Model Output: C

Iteration 47
Model Output: C

Iteration 48
Model Output: C

Iteration 49
Model Output: C

Iteration 50
Model Output: C

Iteration 51
Model Output: C

Iteration 52
Model Output: C

Iteration 53
Model Output: C

Iteration 54
Model Output: C

Iteration 55
Model Output: C

Iteration 56
Model Output: A

Iteration 57
Model Output: A

Iteration 58
Model Output: C

Iteration 59
Model Output: C

Iteration 60
Model Output: A

Iteration 61
Model Output: C

Iteration 62
Model Output: C

Iteration 63
Model Output: A

Iteration 64
Model Output: C

Iteration 65
Model Output: C

Iteration 66
Model Output: C

Iteration 67
Model Output: C

Iteration 68
Model Output: D

Iteration 69
Model Output: E

Iteration 70
Model Output: A

Iteration 71
Model Output: C

Iteration 72
Model Output: E

Iteration 73
Model Output: D

Iteration 74
Model Output: C

Iteration 75
Model Output: D

Iteration 76
Model Output: C

Iteration 77
Model Output: D

Iteration 78
Model Output: B

Iteration 79
Model Output: C

Iteration 80
Model Output: D

Iteration 81
Model Output: C

Iteration 82
Model Output: E

Iteration 83
Model Output: B

Iteration 84
Model Output: C

Iteration 85
Model Output: C

Iteration 86
Model Output: A

Iteration 87
Model Output: A

Iteration 88
Model Output: B

Iteration 89
Model Output: C

Iteration 90
Model Output: C

Iteration 91
Model Output: C

Iteration 92
Model Output: E

Iteration 93
Model Output: A

Iteration 94
Model Output: C

Iteration 95
Model Output: A

Iteration 96
Model Output: C

Iteration 97
Model Output: A

Iteration 98
Model Output: C

Iteration 99
Model Output: C

Iteration 100
Model Output: A

Iteration 101
Model Output: C

Iteration 102
Model Output: C

Iteration 103
Model Output: C

Iteration 104
Model Output: C

Iteration 105
Model Output: A

Iteration 106
Model Output: D

Iteration 107
Model Output: C

Iteration 108
Model Output: A

Iteration 109
Model Output: C

Iteration 110
Model Output: E

Iteration 111
Model Output: D

Iteration 112
Model Output: B

Iteration 113
Model Output: D

Iteration 114
Model Output: C

Iteration 115
Model Output: E

Iteration 116
Model Output: C

Iteration 117
Model Output: C

Iteration 118
Model Output: D

Iteration 119
Model Output: C

Iteration 120
Model Output: C

Iteration 121
Model Output: C

Iteration 122
Model Output: C

Iteration 123
Model Output: D

Iteration 124
Model Output: C

Iteration 125
Model Output: C

Iteration 126
Model Output: D

Iteration 127
Model Output: C

Iteration 128
Model Output: C

Iteration 129
Model Output: D

Iteration 130
Model Output: C

Iteration 131
Model Output: A

Iteration 132
Model Output: D

Iteration 133
Model Output: C

Iteration 134
Model Output: A

Iteration 135
Model Output: C

Iteration 136
Model Output: D

Iteration 137
Model Output: A

Iteration 138
Model Output: C

Iteration 139
Model Output: C

Iteration 140
Model Output: C

Iteration 141
Model Output: A

Iteration 142
Model Output: C

Iteration 143
Model Output: A

Iteration 144
Model Output: C

Iteration 145
Model Output: C

Iteration 146
Model Output: C

Iteration 147
Model Output: A

Iteration 148
Model Output: C

Iteration 149
Model Output: B

Iteration 150
Model Output: A

Iteration 151
Model Output: C

Iteration 152
Model Output: C

Iteration 153
Model Output: A

Iteration 154
Model Output: A

Iteration 155
Model Output: C

Iteration 156
Model Output: C

Iteration 157
Model Output: C

Iteration 158
Model Output: A

Iteration 159
Model Output: D

Iteration 160
Model Output: D

Iteration 161
Model Output: C

Iteration 162
Model Output: C

Iteration 163
Model Output: C

Iteration 164
Model Output: C

Iteration 165
Model Output: C

Iteration 166
Model Output: C

Iteration 167
Model Output: C

Iteration 168
Model Output: B

Iteration 169
Model Output: D

Iteration 170
Model Output: C

Iteration 171
Model Output: A

Iteration 172
Model Output: A

Iteration 173
Model Output: C

Iteration 174
Model Output: D

Iteration 175
Model Output: C

Iteration 176
Model Output: C

Iteration 177
Model Output: C

Iteration 178
Model Output: C

Iteration 179
Model Output: C

Iteration 180
Model Output: C

Iteration 181
Model Output: E

Iteration 182
Model Output: A

Iteration 183
Model Output: E

Iteration 184
Model Output: C

Iteration 185
Model Output: D

Iteration 186
Model Output: C

Iteration 187
Model Output: E

Iteration 188
Model Output: A

Iteration 189
Model Output: A

Iteration 190
Model Output: C

Iteration 191
Model Output: A

Iteration 192
Model Output: C

Iteration 193
Model Output: C

Iteration 194
Model Output: E

Iteration 195
Model Output: C

Iteration 196
Model Output: D

Iteration 197
Model Output: C

Iteration 198
Model Output: E

Iteration 199
Model Output: C

In [87]:
predictions

['E',
 'C',
 'C',
 'C',
 'C',
 'D',
 'C',
 'C',
 'A',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'A',
 'A',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'E',
 'A',
 'D',
 'C',
 'C',
 'D',
 'C',
 'C',
 'C',
 'C',
 'A',
 'C',
 'E',
 'C',
 'C',
 'C',
 'D',
 'C',
 'A',
 'E',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'A',
 'A',
 'C',
 'C',
 'A',
 'C',
 'C',
 'A',
 'C',
 'C',
 'C',
 'C',
 'D',
 'E',
 'A',
 'C',
 'E',
 'D',
 'C',
 'D',
 'C',
 'D',
 'B',
 'C',
 'D',
 'C',
 'E',
 'B',
 'C',
 'C',
 'A',
 'A',
 'B',
 'C',
 'C',
 'C',
 'E',
 'A',
 'C',
 'A',
 'C',
 'A',
 'C',
 'C',
 'A',
 'C',
 'C',
 'C',
 'C',
 'A',
 'D',
 'C',
 'A',
 'C',
 'E',
 'D',
 'B',
 'D',
 'C',
 'E',
 'C',
 'C',
 'D',
 'C',
 'C',
 'C',
 'C',
 'D',
 'C',
 'C',
 'D',
 'C',
 'C',
 'D',
 'C',
 'A',
 'D',
 'C',
 'A',
 'C',
 'D',
 'A',
 'C',
 'C',
 'C',
 'A',
 'C',
 'A',
 'C',
 'C',
 'C',
 'A',
 'C',
 'B',
 'A',
 'C',
 'C',
 'A',
 'A',
 'C',
 'C',
 'C',
 'A',
 'D',
 'D',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'B',
 'D',
 'C',
 'A',
 'A',
 'C',
 'D',
 'C',
 'C',
 'C',
 'C',
 'C',
 'C',
 'E',
 'A',
 'E',
 'C',
 'D',
 'C',
 'E',
 'A',
 'A',
 'C',
 'A',
 'C',
 'C',
 'E',
 'C',
 'D',
 'C',
 'E',
 'C']

In [88]:
print(classification_report(true_answers,predictions,zero_division=0))

              precision    recall  f1-score   support

           A       0.11      0.10      0.11        39
           B       0.33      0.05      0.09        41
           C       0.23      0.68      0.34        40
           D       0.21      0.14      0.16        37
           E       0.40      0.14      0.21        43

    accuracy                           0.22       200
   macro avg       0.26      0.22      0.18       200
weighted avg       0.26      0.22      0.18       200