# Evaluation on LLaMA 3.1-8B + Instruction-Tuned using CounterBench for reasoning tasks

In [1]:
!pip install bitsandbytes

Collecting bitsandbytes
  Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.9.0+cu126)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.20.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)
Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl (59.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.1/59.1 MB 14.8 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.49.1

In [2]:
import json
import torch
import pandas as pd
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from sklearn.metrics import classification_report

In [3]:
from huggingface_hub import login
login()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [4]:
model_name = "meta-llama/Llama-3.1-8B-Instruct"

In [5]:
bitsandbytes_config = BitsAndBytesConfig(load_in_4bit=True,
                                         bnb_4bit_compute_dtype=torch.float16,
                                         bnb_4bit_quant_type='nf4',
                                         bnb_4bit_use_double_quant=True)

In [7]:
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name,
                                             quantization_config=bitsandbytes_config,
                                             device_map="auto",
                                             offload_folder="offload")

config.json:   0%|          | 0.00/855 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/55.4k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/184 [00:00<?, ?B/s]

In [8]:
def get_prompt(instruction,questions,contexts):
  prompts=[]
  for i in range(len(questions)):
    prompt = f"{instruction}\nContext:{contexts[i]}\nQuestion:{questions[i]}\nAnswer:"
    prompts.append(prompt)
  return prompts

In [23]:
def training(prompts,num_tokens=1):
  predictions=[]
  for i in range(len(prompts)):
    input_tokens = tokenizer(prompts[i],return_tensors="pt")
    input_ids = input_tokens["input_ids"].to("cuda:0")
    attention_mask = input_tokens["attention_mask"].to("cuda:0")
    output_tokens = model.generate(input_ids=input_ids,attention_mask=attention_mask,max_new_tokens=num_tokens,pad_token_id=tokenizer.eos_token_id,
                                   eos_token_id=tokenizer.eos_token_id)
    response = tokenizer.decode(output_tokens[0], skip_special_tokens=True)
    pred_answer = response.split("Answer:")[1].split("Explanation:")[0]
    print(f"Iteration {i}\n")
    print(f"Response: {pred_answer}")
    pred_answer = pred_answer.replace("\n","").strip()
    predictions.append(pred_answer)

  return predictions

In [10]:
ds = load_dataset(
    "json",
    data_files=[
        "hf://datasets/CounterBench/CounterBench/data_balanced_alpha_V1.json",
        "hf://datasets/CounterBench/CounterBench/data_balanced_backdoor_V2.json"
    ]
)

print(ds)
print(ds["train"].features)

data_balanced_alpha_V1.json: 0.00B [00:00, ?B/s]

data_balanced_backdoor_V2.json: 0.00B [00:00, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['question', 'given_info', 'answer', 'type', 'question_id', 'meta'],
        num_rows: 1200
    })
})
{'question': Value('string'), 'given_info': Value('string'), 'answer': Value('string'), 'type': Value('string'), 'question_id': Value('string'), 'meta': {'graph_id': Value('string'), 'model_id': Value('int64'), 'query_type': Value('string'), 'rung': Value('int64'), 'story_id': Value('string')}}

In [11]:
dataset = ds["train"].to_pandas()

In [12]:
dataset

,question,given_info,answer,type,question_id,meta
0,Would Lumbo occur if not Ziklo instead of Ziklo?,"We know that Ziklo causes Blaf, Blaf causes Tr...",no,basic,0,"{'graph_id': 'graph5', 'model_id': 0, 'query_t..."
1,Would Zlim occur if not Glent instead of Glent?,"We know that Glent causes Razz, Razz causes Pe...",no,basic,200,"{'graph_id': 'graph5', 'model_id': 1, 'query_t..."
2,Would Klep occur if not Praf instead of Praf?,"We know that Praf causes Vank, Vank causes Scu...",no,basic,400,"{'graph_id': 'graph5', 'model_id': 2, 'query_t..."
3,Would Jext occur if not Fizo instead of Fizo?,"We know that Fizo causes Blorn, Blorn causes P...",no,basic,600,"{'graph_id': 'graph5', 'model_id': 3, 'query_t..."
4,Would Wrox occur if not Nuv instead of Nuv?,"We know that Nuv causes Splee, Splee causes Bl...",no,basic,800,"{'graph_id': 'graph5', 'model_id': 4, 'query_t..."
...,...,...,...,...,...,...
1195,Would Lumbo occur if not Ziklo instead of Ziklo?,"We know that Blaf causes Ziklo, Blaf causes Tr...",no,backdoor,39,"{'graph_id': 'graph9', 'model_id': 195, 'query..."
1196,Would Zlim occur if not Glent instead of Glent?,"We know that Razz causes Glent, Razz causes Pe...",no,backdoor,239,"{'graph_id': 'graph9', 'model_id': 196, 'query..."
1197,Would Klep occur if not Praf instead of Praf?,"We know that Vank causes Praf, Vank causes Scu...",no,backdoor,439,"{'graph_id': 'graph9', 'model_id': 197, 'query..."
1198,Would Jext occur if not Fizo instead of Fizo?,"We know that Blorn causes Fizo, Blorn causes P...",no,backdoor,639,"{'graph_id': 'graph9', 'model_id': 198, 'query..."
1199,Would Wrox occur if not Nuv instead of Nuv?,"We know that Splee causes Nuv, Splee causes Bl...",no,backdoor,839,"{'graph_id': 'graph9', 'model_id': 199, 'query..."

In [13]:
dataset['type'].value_counts()

type
basic          250
conditional    250
joint          250
nested         250
backdoor       200
Name: count, dtype: int64

In [14]:
intstruction = "Instruction: Answer the question strictly using the causal facts provided. Do not introduce any new information. For counterfactuals, simulate the scenario along the causal chain step by step. Only output the final answer as Yes or No. Do not write anything else."

## Basic Questions

In [15]:
dataset_basic = dataset[dataset['type']=="basic"]

In [16]:
dataset_basic

,question,given_info,answer,type,question_id,meta
0,Would Lumbo occur if not Ziklo instead of Ziklo?,"We know that Ziklo causes Blaf, Blaf causes Tr...",no,basic,0,"{'graph_id': 'graph5', 'model_id': 0, 'query_t..."
1,Would Zlim occur if not Glent instead of Glent?,"We know that Glent causes Razz, Razz causes Pe...",no,basic,200,"{'graph_id': 'graph5', 'model_id': 1, 'query_t..."
2,Would Klep occur if not Praf instead of Praf?,"We know that Praf causes Vank, Vank causes Scu...",no,basic,400,"{'graph_id': 'graph5', 'model_id': 2, 'query_t..."
3,Would Jext occur if not Fizo instead of Fizo?,"We know that Fizo causes Blorn, Blorn causes P...",no,basic,600,"{'graph_id': 'graph5', 'model_id': 3, 'query_t..."
4,Would Wrox occur if not Nuv instead of Nuv?,"We know that Nuv causes Splee, Splee causes Bl...",no,basic,800,"{'graph_id': 'graph5', 'model_id': 4, 'query_t..."
...,...,...,...,...,...,...
495,Would Lumbo occur if not Ziklo instead of Ziklo?,"We know that Ziklo causes Blaf and Trune, Trun...",no,basic,99,"{'graph_id': 'graph9', 'model_id': 495, 'query..."
496,Would Zlim occur if not Glent instead of Glent?,"We know that Glent causes Razz and Pex, Pex ca...",no,basic,299,"{'graph_id': 'graph9', 'model_id': 496, 'query..."
497,Would Klep occur if not Praf instead of Praf?,"We know that Praf causes Vank and Scud, Scud c...",no,basic,499,"{'graph_id': 'graph9', 'model_id': 497, 'query..."
498,Would Jext occur if not Fizo instead of Fizo?,"We know that Fizo causes Blorn and Plim, Plim ...",no,basic,699,"{'graph_id': 'graph9', 'model_id': 498, 'query..."
499,Would Wrox occur if not Nuv instead of Nuv?,"We know that Nuv causes Splee and Blen, Blen c...",no,basic,899,"{'graph_id': 'graph9', 'model_id': 499, 'query..."

In [17]:
questions = dataset_basic["question"].values.tolist()

In [18]:
contexts = dataset_basic["given_info"].values.tolist()

In [19]:
true_answers = dataset_basic["answer"].values.tolist()

In [20]:
prompts = get_prompt(intstruction,questions,contexts)

In [21]:
prompts[0]

'Instruction: Answer the question strictly using the causal facts provided. Do not introduce any new information. For counterfactuals, simulate the scenario along the causal chain step by step. Only output the final answer as Yes or No. Do not write anything else.\nContext:We know that Ziklo causes Blaf, Blaf causes Trune, Trune causes Vork, and Vork causes Lumbo.\nQuestion:Would Lumbo occur if not Ziklo instead of Ziklo?\nAnswer:'

In [24]:
predictions = training(prompts)

Iteration 0

Response: No
Iteration 1

Response: No
Iteration 2

Response:  No
Iteration 3

Response:  No
Iteration 4

Response: Yes
Iteration 5

Response: Yes
Iteration 6

Response:  No
Iteration 7

Response:  No
Iteration 8

Response: No
Iteration 9

Response: Yes
Iteration 10

Response: No
Iteration 11

Response: Yes
Iteration 12

Response:  No
Iteration 13

Response: No
Iteration 14

Response: No
Iteration 15

Response: No
Iteration 16

Response:  No
Iteration 17

Response: No
Iteration 18

Response:  No
Iteration 19

Response:  No
Iteration 20

Response:  No
Iteration 21

Response:  No
Iteration 22

Response: No
Iteration 23

Response:  No
Iteration 24

Response: Yes
Iteration 25

Response:  No
Iteration 26

Response:  No
Iteration 27

Response:  No
Iteration 28

Response: Yes
Iteration 29

Response: Yes
Iteration 30

Response: No
Iteration 31

Response: Yes
Iteration 32

Response:  No
Iteration 33

Response: No
Iteration 34

Response:  No
Iteration 35

Response:  No
Iteration 36

Response: No
Iteration 37

Response:  No
Iteration 38

Response:  No
Iteration 39

Response: Yes
Iteration 40

Response: Yes
Iteration 41

Response: No
Iteration 42

Response: No
Iteration 43

Response: No
Iteration 44

Response:  No
Iteration 45

Response: Yes
Iteration 46

Response:  Yes
Iteration 47

Response: Yes
Iteration 48

Response: No
Iteration 49

Response: No
Iteration 50

Response: No
Iteration 51

Response:  No
Iteration 52

Response: No
Iteration 53

Response: No
Iteration 54

Response: No
Iteration 55

Response:  No
Iteration 56

Response: No
Iteration 57

Response: No
Iteration 58

Response: No
Iteration 59

Response:  No
Iteration 60

Response: No
Iteration 61

Response:  No
Iteration 62

Response:  No
Iteration 63

Response: No
Iteration 64

Response:  No
Iteration 65

Response:  No
Iteration 66

Response: No
Iteration 67

Response: No
Iteration 68

Response: No
Iteration 69

Response:  No
Iteration 70

Response:  No
Iteration 71

Response:  No
Iteration 72

Response:  No
Iteration 73

Response:  No
Iteration 74

Response: No
Iteration 75

Response:  No
Iteration 76

Response: No
Iteration 77

Response:  Yes
Iteration 78

Response:  No
Iteration 79

Response:  Yes
Iteration 80

Response:  No
Iteration 81

Response:  No
Iteration 82

Response:  No
Iteration 83

Response:  No
Iteration 84

Response: No
Iteration 85

Response:  Yes
Iteration 86

Response: Yes
Iteration 87

Response:  Yes
Iteration 88

Response:  No
Iteration 89

Response:  No
Iteration 90

Response:  No
Iteration 91

Response:  No
Iteration 92

Response:  No
Iteration 93

Response:  No
Iteration 94

Response: No
Iteration 95

Response:  No
Iteration 96

Response:  No
Iteration 97

Response:  No
Iteration 98

Response: No
Iteration 99

Response:  No
Iteration 100

Response: Yes
Iteration 101

Response:  No
Iteration 102

Response:  No
Iteration 103

Response: Yes
Iteration 104

Response:  No
Iteration 105

Response: No
Iteration 106

Response:  No
Iteration 107

Response:  No
Iteration 108

Response: No
Iteration 109

Response:  No
Iteration 110

Response:  No
Iteration 111

Response:  No
Iteration 112

Response:  No
Iteration 113

Response:  No
Iteration 114

Response: No
Iteration 115

Response: Yes
Iteration 116

Response: Yes
Iteration 117

Response:  Yes
Iteration 118

Response:  Yes
Iteration 119

Response:  Yes
Iteration 120

Response:  No
Iteration 121

Response: Yes
Iteration 122

Response:  No
Iteration 123

Response:  Yes
Iteration 124

Response: No
Iteration 125

Response: No
Iteration 126

Response: No
Iteration 127

Response: No
Iteration 128

Response:  No
Iteration 129

Response:  No
Iteration 130

Response:  No
Iteration 131

Response:  No
Iteration 132

Response:  No
Iteration 133

Response:  No
Iteration 134

Response: No
Iteration 135

Response:  Yes
Iteration 136

Response: No
Iteration 137

Response: No
Iteration 138

Response: Yes
Iteration 139

Response:  No
Iteration 140

Response:  No
Iteration 141

Response:  No
Iteration 142

Response:  Yes
Iteration 143

Response: No
Iteration 144

Response:  No
Iteration 145

Response: No
Iteration 146

Response: No
Iteration 147

Response: No
Iteration 148

Response: No
Iteration 149

Response:  No
Iteration 150

Response:  No
Iteration 151

Response:  Yes
Iteration 152

Response:  No
Iteration 153

Response:  No
Iteration 154

Response: No
Iteration 155

Response: No
Iteration 156

Response:  No
Iteration 157

Response:  No
Iteration 158

Response: Yes
Iteration 159

Response: Yes
Iteration 160

Response: No
Iteration 161

Response: Yes
Iteration 162

Response:  No
Iteration 163

Response:  No
Iteration 164

Response:  No
Iteration 165

Response:  No
Iteration 166

Response:  No
Iteration 167

Response:  No
Iteration 168

Response:  No
Iteration 169

Response: No
Iteration 170

Response: No
Iteration 171

Response:  No
Iteration 172

Response:  No
Iteration 173

Response: No
Iteration 174

Response:  No
Iteration 175

Response:  No
Iteration 176

Response: Yes
Iteration 177

Response: Yes
Iteration 178

Response:  No
Iteration 179

Response:  No
Iteration 180

Response: No
Iteration 181

Response:  Yes
Iteration 182

Response:  No
Iteration 183

Response:  No
Iteration 184

Response: Yes
Iteration 185

Response: Yes
Iteration 186

Response:  No
Iteration 187

Response:  No
Iteration 188

Response: No
Iteration 189

Response: Yes
Iteration 190

Response: No
Iteration 191

Response: No
Iteration 192

Response: No
Iteration 193

Response: No
Iteration 194

Response: No
Iteration 195

Response: No
Iteration 196

Response: No
Iteration 197

Response:  No
Iteration 198

Response:  No
Iteration 199

Response: No
Iteration 200

Response: No
Iteration 201

Response: No
Iteration 202

Response: No
Iteration 203

Response: No
Iteration 204

Response:  No
Iteration 205

Response: No
Iteration 206

Response: Yes
Iteration 207

Response: Yes
Iteration 208

Response: Yes
Iteration 209

Response: No
Iteration 210

Response: Yes
Iteration 211

Response: No
Iteration 212

Response:  No
Iteration 213

Response: Yes
Iteration 214

Response: No
Iteration 215

Response: Yes
Iteration 216

Response:  No
Iteration 217

Response: Yes
Iteration 218

Response:  No
Iteration 219

Response: Yes
Iteration 220

Response:  No
Iteration 221

Response: No
Iteration 222

Response: No
Iteration 223

Response: No
Iteration 224

Response: No
Iteration 225

Response:  No
Iteration 226

Response:  No
Iteration 227

Response: Yes
Iteration 228

Response:  No
Iteration 229

Response:  No
Iteration 230

Response: No
Iteration 231

Response: No
Iteration 232

Response:  Yes
Iteration 233

Response: Yes
Iteration 234

Response: No
Iteration 235

Response:  No
Iteration 236

Response:  No
Iteration 237

Response:  No
Iteration 238

Response:  Yes
Iteration 239

Response: No
Iteration 240

Response: No
Iteration 241

Response:  No
Iteration 242

Response:  No
Iteration 243

Response:  No
Iteration 244

Response:  No
Iteration 245

Response:  No
Iteration 246

Response: Yes
Iteration 247

Response:  No
Iteration 248

Response: Yes
Iteration 249

Response:  No

In [25]:
predictions

['No',
 'No',
 'No',
 'No',
 'Yes',
 'Yes',
 'No',
 'No',
 'No',
 'Yes',
 'No',
 'Yes',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Yes',
 'No',
 'No',
 'No',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Yes',
 'Yes',
 'No',
 'No',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Yes',
 'No',
 'Yes',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Yes',
 'No',
 'No',
 'Yes',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Yes',
 'No',
 'No',
 'Yes',
 'No',
 'No',
 'No',
 'Yes',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Yes',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Yes',
 'Yes',
 'No',
 'No',
 'No',
 'Yes',
 'No',
 'No',
 'Yes',
 'Yes',
 'No',
 'No',
 'No',
 'Yes',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'No',
 'No',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'No',
 'Yes',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Yes',
 'No',
 'No',
 'No',
 'No',
 'Yes',
 'Yes',
 'No',
 'No',
 'No',
 'No',
 'Yes',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Yes',
 'No',
 'Yes',
 'No']

In [26]:
predictions_new = [elem.lower() for elem in predictions]
predictions_new

['no',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'no']

In [27]:
print(classification_report(true_answers,predictions_new,zero_division=0))

              precision    recall  f1-score   support

          no       0.51      0.79      0.62       125
         yes       0.52      0.22      0.31       125

    accuracy                           0.51       250
   macro avg       0.51      0.51      0.46       250
weighted avg       0.51      0.51      0.46       250

## Conditional Questions

In [28]:
dataset_conditional = dataset[dataset['type']=="conditional"]

In [29]:
dataset_conditional

,question,given_info,answer,type,question_id,meta
25,Would Lumbo occur if not Ziklo instead of Ziklo?,"We know that Ziklo causes not Blaf, Blaf and T...",yes,conditional,5,"{'graph_id': 'graph5', 'model_id': 25, 'query_..."
26,Would Zlim occur if not Glent instead of Glent?,"We know that Glent causes not Razz, Razz and P...",yes,conditional,205,"{'graph_id': 'graph5', 'model_id': 26, 'query_..."
27,Would Klep occur if not Praf instead of Praf?,"We know that Praf causes not Vank, Vank and Sc...",yes,conditional,405,"{'graph_id': 'graph5', 'model_id': 27, 'query_..."
28,Would Jext occur if not Fizo instead of Fizo?,"We know that Fizo causes not Blorn, Blorn and ...",yes,conditional,605,"{'graph_id': 'graph5', 'model_id': 28, 'query_..."
29,Would Wrox occur if not Nuv instead of Nuv?,"We know that Nuv causes not Splee, Splee and B...",yes,conditional,805,"{'graph_id': 'graph5', 'model_id': 29, 'query_..."
...,...,...,...,...,...,...
435,Would Lumbo occur if not Ziklo instead of Ziklo?,"We know that Ziklo causes Blaf and Trune, Blaf...",no,conditional,87,"{'graph_id': 'graph7', 'model_id': 435, 'query..."
436,Would Zlim occur if not Glent instead of Glent?,"We know that Glent causes Razz and Pex, Razz a...",no,conditional,287,"{'graph_id': 'graph7', 'model_id': 436, 'query..."
437,Would Klep occur if not Praf instead of Praf?,"We know that Praf causes Vank and Scud, Vank a...",no,conditional,487,"{'graph_id': 'graph7', 'model_id': 437, 'query..."
438,Would Jext occur if not Fizo instead of Fizo?,"We know that Fizo causes Blorn and Plim, Blorn...",no,conditional,687,"{'graph_id': 'graph7', 'model_id': 438, 'query..."
439,Would Wrox occur if not Nuv instead of Nuv?,"We know that Nuv causes Splee and Blen, Splee ...",no,conditional,887,"{'graph_id': 'graph7', 'model_id': 439, 'query..."

In [30]:
questions = dataset_conditional["question"].values.tolist()

In [31]:
contexts = dataset_conditional["given_info"].values.tolist()

In [32]:
true_answers = dataset_conditional["answer"].values.tolist()

In [33]:
prompts = get_prompt(intstruction,questions,contexts)

In [34]:
prompts[0]

'Instruction: Answer the question strictly using the causal facts provided. Do not introduce any new information. For counterfactuals, simulate the scenario along the causal chain step by step. Only output the final answer as Yes or No. Do not write anything else.\nContext:We know that Ziklo causes not Blaf, Blaf and Trune together cause Vork, Vork causes Lumbo. We observed Trune\nQuestion:Would Lumbo occur if not Ziklo instead of Ziklo?\nAnswer:'

In [35]:
predictions = training(prompts)

Iteration 0

Response:  No
Iteration 1

Response: Yes
Iteration 2

Response:  Yes
Iteration 3

Response: Yes
Iteration 4

Response: Yes
Iteration 5

Response:  No
Iteration 6

Response: No
Iteration 7

Response:  No
Iteration 8

Response:  No
Iteration 9

Response:  Yes
Iteration 10

Response:  Yes
Iteration 11

Response:  No
Iteration 12

Response:  No
Iteration 13

Response: No
Iteration 14

Response:  No
Iteration 15

Response:  No
Iteration 16

Response: Yes
Iteration 17

Response:  No
Iteration 18

Response: No
Iteration 19

Response:  No
Iteration 20

Response:  No
Iteration 21

Response: Yes
Iteration 22

Response: No
Iteration 23

Response: No
Iteration 24

Response: Yes
Iteration 25

Response: Yes
Iteration 26

Response: No
Iteration 27

Response:  No
Iteration 28

Response: No
Iteration 29

Response:  No
Iteration 30

Response:  No
Iteration 31

Response:  Yes
Iteration 32

Response:  No
Iteration 33

Response:  No
Iteration 34

Response:  No
Iteration 35

Response: No
Iteration 36

Response:  No
Iteration 37

Response: No
Iteration 38

Response:  No
Iteration 39

Response:  No
Iteration 40

Response: No
Iteration 41

Response:  Yes
Iteration 42

Response:  No
Iteration 43

Response: Yes
Iteration 44

Response:  No
Iteration 45

Response: Yes
Iteration 46

Response: Yes
Iteration 47

Response:  No
Iteration 48

Response: No
Iteration 49

Response: No
Iteration 50

Response:  No
Iteration 51

Response: No
Iteration 52

Response:  No
Iteration 53

Response: No
Iteration 54

Response: Yes
Iteration 55

Response: No
Iteration 56

Response:  No
Iteration 57

Response:  No
Iteration 58

Response:  No
Iteration 59

Response:  Yes
Iteration 60

Response: No
Iteration 61

Response: Yes
Iteration 62

Response:  No
Iteration 63

Response: Yes
Iteration 64

Response:  No
Iteration 65

Response: No
Iteration 66

Response: No
Iteration 67

Response: No
Iteration 68

Response: No
Iteration 69

Response:  No
Iteration 70

Response: No
Iteration 71

Response:  No
Iteration 72

Response:  No
Iteration 73

Response: Yes
Iteration 74

Response: Yes
Iteration 75

Response: Yes
Iteration 76

Response: No
Iteration 77

Response: No
Iteration 78

Response: No
Iteration 79

Response: Yes
Iteration 80

Response:  No
Iteration 81

Response: Yes
Iteration 82

Response: Yes
Iteration 83

Response: Yes
Iteration 84

Response: No
Iteration 85

Response: No
Iteration 86

Response: Yes
Iteration 87

Response:  No
Iteration 88

Response:  No
Iteration 89

Response:  No
Iteration 90

Response:  No
Iteration 91

Response: Yes
Iteration 92

Response:  Yes
Iteration 93

Response: Yes
Iteration 94

Response:  No
Iteration 95

Response: No
Iteration 96

Response: No
Iteration 97

Response: Yes
Iteration 98

Response: Yes
Iteration 99

Response:  Yes
Iteration 100

Response:  No
Iteration 101

Response:  No
Iteration 102

Response:  No
Iteration 103

Response: No
Iteration 104

Response:  No
Iteration 105

Response:  No
Iteration 106

Response:  No
Iteration 107

Response:  Yes
Iteration 108

Response: No
Iteration 109

Response: Yes
Iteration 110

Response: Yes
Iteration 111

Response: Yes
Iteration 112

Response: Yes
Iteration 113

Response: Yes
Iteration 114

Response:  Yes
Iteration 115

Response: No
Iteration 116

Response: No
Iteration 117

Response: Yes
Iteration 118

Response: Yes
Iteration 119

Response: Yes
Iteration 120

Response: Yes
Iteration 121

Response: No
Iteration 122

Response: No
Iteration 123

Response: No
Iteration 124

Response: No
Iteration 125

Response: Yes
Iteration 126

Response: No
Iteration 127

Response:  No
Iteration 128

Response: Yes
Iteration 129

Response: No
Iteration 130

Response:  No
Iteration 131

Response: No
Iteration 132

Response: No
Iteration 133

Response: Yes
Iteration 134

Response:  No
Iteration 135

Response: No
Iteration 136

Response: Yes
Iteration 137

Response:  No
Iteration 138

Response: Yes
Iteration 139

Response:  Yes
Iteration 140

Response:  No
Iteration 141

Response: Yes
Iteration 142

Response: Yes
Iteration 143

Response: Yes
Iteration 144

Response:  No
Iteration 145

Response:  No
Iteration 146

Response:  No
Iteration 147

Response:  No
Iteration 148

Response: Yes
Iteration 149

Response:  No
Iteration 150

Response: No
Iteration 151

Response: No
Iteration 152

Response:  Yes
Iteration 153

Response: Yes
Iteration 154

Response: Yes
Iteration 155

Response: No
Iteration 156

Response:  No
Iteration 157

Response: No
Iteration 158

Response: No
Iteration 159

Response: Yes
Iteration 160

Response: No
Iteration 161

Response: No
Iteration 162

Response:  No
Iteration 163

Response: Yes
Iteration 164

Response:  No
Iteration 165

Response: Yes
Iteration 166

Response:  No
Iteration 167

Response:  No
Iteration 168

Response: Yes
Iteration 169

Response:  No
Iteration 170

Response: No
Iteration 171

Response: No
Iteration 172

Response: No
Iteration 173

Response: Yes
Iteration 174

Response: No
Iteration 175

Response: No
Iteration 176

Response:  No
Iteration 177

Response: Yes
Iteration 178

Response: Yes
Iteration 179

Response: No
Iteration 180

Response: No
Iteration 181

Response: No
Iteration 182

Response: No
Iteration 183

Response: No
Iteration 184

Response: No
Iteration 185

Response: No
Iteration 186

Response:  No
Iteration 187

Response: No
Iteration 188

Response: No
Iteration 189

Response: No
Iteration 190

Response: No
Iteration 191

Response: Yes
Iteration 192

Response: Yes
Iteration 193

Response: No
Iteration 194

Response: No
Iteration 195

Response: No
Iteration 196

Response: No
Iteration 197

Response: Yes
Iteration 198

Response:  No
Iteration 199

Response:  No
Iteration 200

Response: No
Iteration 201

Response: No
Iteration 202

Response: No
Iteration 203

Response: Yes
Iteration 204

Response: Yes
Iteration 205

Response: Yes
Iteration 206

Response: No
Iteration 207

Response: No
Iteration 208

Response: No
Iteration 209

Response: Yes
Iteration 210

Response: Yes
Iteration 211

Response: Yes
Iteration 212

Response: Yes
Iteration 213

Response: Yes
Iteration 214

Response: No
Iteration 215

Response: No
Iteration 216

Response: Yes
Iteration 217

Response: No
Iteration 218

Response: No
Iteration 219

Response: No
Iteration 220

Response:  No
Iteration 221

Response: No
Iteration 222

Response: Yes
Iteration 223

Response: Yes
Iteration 224

Response: Yes
Iteration 225

Response: Yes
Iteration 226

Response: No
Iteration 227

Response:  Yes
Iteration 228

Response: No
Iteration 229

Response:  No
Iteration 230

Response:  No
Iteration 231

Response: Yes
Iteration 232

Response: No
Iteration 233

Response: Yes
Iteration 234

Response: No
Iteration 235

Response: No
Iteration 236

Response: No
Iteration 237

Response: No
Iteration 238

Response:  No
Iteration 239

Response:  No
Iteration 240

Response: Yes
Iteration 241

Response: Yes
Iteration 242

Response:  No
Iteration 243

Response: Yes
Iteration 244

Response:  No
Iteration 245

Response: Yes
Iteration 246

Response: Yes
Iteration 247

Response: Yes
Iteration 248

Response: Yes
Iteration 249

Response: Yes

In [36]:
predictions_new = [elem.lower() for elem in predictions]

In [37]:
print(classification_report(true_answers,predictions_new,zero_division=0))

              precision    recall  f1-score   support

          no       0.47      0.60      0.53       125
         yes       0.45      0.33      0.38       125

    accuracy                           0.46       250
   macro avg       0.46      0.46      0.45       250
weighted avg       0.46      0.46      0.45       250

## Joint Questions

In [38]:
dataset_joint = dataset[dataset['type']=="joint"]

In [39]:
dataset_joint

,question,given_info,answer,type,question_id,meta
500,Would Lumbo occur if not Ziklo and not Blaf?,"We know that Ziklo causes Blaf and Vork, Blaf ...",yes,joint,100,"{'graph_id': 'graph5', 'model_id': 500, 'query..."
501,Would Zlim occur if not Glent and not Razz?,"We know that Glent causes Razz and Zurn, Razz ...",yes,joint,300,"{'graph_id': 'graph5', 'model_id': 501, 'query..."
502,Would Klep occur if not Praf and not Vank?,"We know that Praf causes Vank and Wrenk, Vank ...",yes,joint,500,"{'graph_id': 'graph5', 'model_id': 502, 'query..."
503,Would Jext occur if not Fizo and not Blorn?,"We know that Fizo causes Blorn and Quaz, Blorn...",yes,joint,700,"{'graph_id': 'graph5', 'model_id': 503, 'query..."
504,Would Wrox occur if not Nuv and not Splee?,"We know that Nuv causes Splee and Druk, Splee ...",yes,joint,900,"{'graph_id': 'graph5', 'model_id': 504, 'query..."
...,...,...,...,...,...,...
745,Would Lumbo occur if not Ziklo and not Sline?,"We know that Ziklo causes Blaf, Blaf causes Tr...",yes,joint,149,"{'graph_id': 'graph7', 'model_id': 745, 'query..."
746,Would Zlim occur if not Glent and not Melf?,"We know that Glent causes Razz, Razz causes Pe...",yes,joint,349,"{'graph_id': 'graph7', 'model_id': 746, 'query..."
747,Would Klep occur if not Praf and not Yobb?,"We know that Praf causes Vank, Vank causes Scu...",yes,joint,549,"{'graph_id': 'graph7', 'model_id': 747, 'query..."
748,Would Jext occur if not Fizo and not Skul?,"We know that Fizo causes Blorn, Blorn causes P...",yes,joint,749,"{'graph_id': 'graph7', 'model_id': 748, 'query..."
749,Would Wrox occur if not Nuv and not Plog?,"We know that Nuv causes Splee, Splee causes Bl...",yes,joint,949,"{'graph_id': 'graph7', 'model_id': 749, 'query..."

In [40]:
questions = dataset_joint["question"].values.tolist()
contexts = dataset_joint["given_info"].values.tolist()
true_answers = dataset_joint["answer"].values.tolist()

In [41]:
prompts = get_prompt(intstruction,questions,contexts)

In [42]:
prompts[0]

'Instruction: Answer the question strictly using the causal facts provided. Do not introduce any new information. For counterfactuals, simulate the scenario along the causal chain step by step. Only output the final answer as Yes or No. Do not write anything else.\nContext:We know that Ziklo causes Blaf and Vork, Blaf causes not Trune, Trune or Vork causes Lumbo.\nQuestion:Would Lumbo occur if not Ziklo and not Blaf?\nAnswer:'

In [43]:
predictions = training(prompts)

Iteration 0

Response: No
Iteration 1

Response: Yes
Iteration 2

Response:  No
Iteration 3

Response: Yes
Iteration 4

Response:  Yes
Iteration 5

Response:  Yes
Iteration 6

Response: Yes
Iteration 7

Response:  Yes
Iteration 8

Response: Yes
Iteration 9

Response:  Yes
Iteration 10

Response:  No
Iteration 11

Response:  No
Iteration 12

Response:  No
Iteration 13

Response: Yes
Iteration 14

Response:  No
Iteration 15

Response: Yes
Iteration 16

Response: Yes
Iteration 17

Response: Yes
Iteration 18

Response:  Yes
Iteration 19

Response:  Yes
Iteration 20

Response: No
Iteration 21

Response: Yes
Iteration 22

Response:  No
Iteration 23

Response: Yes
Iteration 24

Response:  No
Iteration 25

Response:  No
Iteration 26

Response:  No
Iteration 27

Response:  No
Iteration 28

Response:  No
Iteration 29

Response: Yes
Iteration 30

Response: No
Iteration 31

Response:  No
Iteration 32

Response:  No
Iteration 33

Response:  No
Iteration 34

Response:  No
Iteration 35

Response: Yes
Iteration 36

Response:  No
Iteration 37

Response: Yes
Iteration 38

Response:  Yes
Iteration 39

Response: Yes
Iteration 40

Response: Yes
Iteration 41

Response:  Yes
Iteration 42

Response:  No
Iteration 43

Response: Yes
Iteration 44

Response: Yes
Iteration 45

Response:  No
Iteration 46

Response:  No
Iteration 47

Response: No
Iteration 48

Response:  No
Iteration 49

Response:  No
Iteration 50

Response:  No
Iteration 51

Response: No
Iteration 52

Response:  No
Iteration 53

Response: Yes
Iteration 54

Response:  No
Iteration 55

Response:  Yes
Iteration 56

Response:  No
Iteration 57

Response:  No
Iteration 58

Response: Yes
Iteration 59

Response:  No
Iteration 60

Response: Yes
Iteration 61

Response: Yes
Iteration 62

Response:  Yes
Iteration 63

Response: Yes
Iteration 64

Response: Yes
Iteration 65

Response:  No
Iteration 66

Response:  No
Iteration 67

Response:  No
Iteration 68

Response:  No
Iteration 69

Response:  No
Iteration 70

Response:  No
Iteration 71

Response: Yes
Iteration 72

Response: No
Iteration 73

Response: Yes
Iteration 74

Response: No
Iteration 75

Response:  No
Iteration 76

Response:  No
Iteration 77

Response:  Yes
Iteration 78

Response:  No
Iteration 79

Response:  Yes
Iteration 80

Response: No
Iteration 81

Response:  No
Iteration 82

Response:  No
Iteration 83

Response: No
Iteration 84

Response:  Yes
Iteration 85

Response:  Yes
Iteration 86

Response:  No
Iteration 87

Response:  No
Iteration 88

Response:  No
Iteration 89

Response:  No
Iteration 90

Response:  No
Iteration 91

Response: No
Iteration 92

Response: No
Iteration 93

Response: No
Iteration 94

Response:  No
Iteration 95

Response: Yes
Iteration 96

Response:  Yes
Iteration 97

Response: No
Iteration 98

Response: Yes
Iteration 99

Response: Yes
Iteration 100

Response:  No
Iteration 101

Response:  No
Iteration 102

Response:  No
Iteration 103

Response:  No
Iteration 104

Response:  No
Iteration 105

Response:  No
Iteration 106

Response:  No
Iteration 107

Response:  No
Iteration 108

Response:  No
Iteration 109

Response:  No
Iteration 110

Response: Yes
Iteration 111

Response:  No
Iteration 112

Response:  No
Iteration 113

Response:  Yes
Iteration 114

Response: Yes
Iteration 115

Response: Yes
Iteration 116

Response: Yes
Iteration 117

Response:  Yes
Iteration 118

Response:  No
Iteration 119

Response:  No
Iteration 120

Response:  No
Iteration 121

Response:  No
Iteration 122

Response:  No
Iteration 123

Response:  No
Iteration 124

Response:  No
Iteration 125

Response:  No
Iteration 126

Response:  No
Iteration 127

Response:  No
Iteration 128

Response:  No
Iteration 129

Response:  No
Iteration 130

Response:  No
Iteration 131

Response:  Yes
Iteration 132

Response:  No
Iteration 133

Response:  Yes
Iteration 134

Response:  No
Iteration 135

Response:  No
Iteration 136

Response:  No
Iteration 137

Response:  No
Iteration 138

Response: No
Iteration 139

Response: No
Iteration 140

Response: No
Iteration 141

Response:  Yes
Iteration 142

Response:  No
Iteration 143

Response:  No
Iteration 144

Response:  No
Iteration 145

Response:  No
Iteration 146

Response:  No
Iteration 147

Response: No
Iteration 148

Response:  No
Iteration 149

Response:  No
Iteration 150

Response:  No
Iteration 151

Response:  No
Iteration 152

Response:  No
Iteration 153

Response:  No
Iteration 154

Response: No
Iteration 155

Response:  No
Iteration 156

Response:  No
Iteration 157

Response:  Yes
Iteration 158

Response:  No
Iteration 159

Response:  No
Iteration 160

Response: No
Iteration 161

Response:  No
Iteration 162

Response:  No
Iteration 163

Response:  No
Iteration 164

Response: No
Iteration 165

Response: 0
Iteration 166

Response:  No
Iteration 167

Response:  No
Iteration 168

Response: No
Iteration 169

Response: Yes
Iteration 170

Response: No
Iteration 171

Response:  Yes
Iteration 172

Response:  No
Iteration 173

Response: No
Iteration 174

Response: Yes
Iteration 175

Response:  No
Iteration 176

Response:  No
Iteration 177

Response:  No
Iteration 178

Response:  No
Iteration 179

Response:  No
Iteration 180

Response:  No
Iteration 181

Response:  No
Iteration 182

Response:  No
Iteration 183

Response:  No
Iteration 184

Response: No
Iteration 185

Response: Yes
Iteration 186

Response:  No
Iteration 187

Response:  No
Iteration 188

Response: Yes
Iteration 189

Response: Yes
Iteration 190

Response: Yes
Iteration 191

Response: Yes
Iteration 192

Response: No
Iteration 193

Response: No
Iteration 194

Response: Yes
Iteration 195

Response: No
Iteration 196

Response: No
Iteration 197

Response: No
Iteration 198

Response: Yes
Iteration 199

Response: No
Iteration 200

Response: No
Iteration 201

Response: No
Iteration 202

Response:  No
Iteration 203

Response: No
Iteration 204

Response: No
Iteration 205

Response: No
Iteration 206

Response:  No
Iteration 207

Response: Yes
Iteration 208

Response: No
Iteration 209

Response: No
Iteration 210

Response:  No
Iteration 211

Response:  No
Iteration 212

Response: No
Iteration 213

Response:  No
Iteration 214

Response:  No
Iteration 215

Response:  No
Iteration 216

Response:  No
Iteration 217

Response:  No
Iteration 218

Response:  No
Iteration 219

Response:  No
Iteration 220

Response:  No
Iteration 221

Response:  No
Iteration 222

Response:  No
Iteration 223

Response: No
Iteration 224

Response: Yes
Iteration 225

Response: No
Iteration 226

Response:  Yes
Iteration 227

Response:  No
Iteration 228

Response: Yes
Iteration 229

Response:  Yes
Iteration 230

Response: Yes
Iteration 231

Response:  No
Iteration 232

Response:  No
Iteration 233

Response: Yes
Iteration 234

Response: Yes
Iteration 235

Response:  No
Iteration 236

Response:  Yes
Iteration 237

Response:  Yes
Iteration 238

Response:  No
Iteration 239

Response: No
Iteration 240

Response:  No
Iteration 241

Response:  Yes
Iteration 242

Response:  No
Iteration 243

Response:  No
Iteration 244

Response: No
Iteration 245

Response:  Yes
Iteration 246

Response:  Yes
Iteration 247

Response:  No
Iteration 248

Response:  Yes
Iteration 249

Response: No

In [44]:
predictions_new = [elem.lower() for elem in predictions]

In [45]:
print(classification_report(true_answers,predictions_new,zero_division=0))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
          no       0.58      0.79      0.67       125
         yes       0.68      0.42      0.51       125

    accuracy                           0.60       250
   macro avg       0.42      0.40      0.39       250
weighted avg       0.63      0.60      0.59       250

## Nested Questions

In [46]:
dataset_nested = dataset[dataset['type']=="nested"]

In [47]:
dataset_nested

,question,given_info,answer,type,question_id,meta
750,"Assume not Ziklo, and based on this assumption...","We know that Ziklo causes Blaf, Trune and Vork...",yes,nested,150,"{'graph_id': 'graph9', 'model_id': 750, 'query..."
751,"Assume not Glent, and based on this assumption...","We know that Glent causes Razz, Pex and Zurn, ...",yes,nested,350,"{'graph_id': 'graph9', 'model_id': 751, 'query..."
752,"Assume not Praf, and based on this assumption,...","We know that Praf causes Vank, Scud and Wrenk,...",yes,nested,550,"{'graph_id': 'graph9', 'model_id': 752, 'query..."
753,"Assume not Fizo, and based on this assumption,...","We know that Fizo causes Blorn, Plim and Quaz,...",yes,nested,750,"{'graph_id': 'graph9', 'model_id': 753, 'query..."
754,"Assume not Nuv, and based on this assumption, ...","We know that Nuv causes Splee, Blen and Druk, ...",yes,nested,950,"{'graph_id': 'graph9', 'model_id': 754, 'query..."
...,...,...,...,...,...,...
995,"Assume not Ziklo, and based on this assumption...","We know that Ziklo causes Blaf and Trune, Trun...",yes,nested,199,"{'graph_id': 'graph8', 'model_id': 995, 'query..."
996,"Assume not Glent, and based on this assumption...","We know that Glent causes Razz and Pex, Pex ca...",yes,nested,399,"{'graph_id': 'graph8', 'model_id': 996, 'query..."
997,"Assume not Praf, and based on this assumption,...","We know that Praf causes Vank and Scud, Scud c...",yes,nested,599,"{'graph_id': 'graph8', 'model_id': 997, 'query..."
998,"Assume not Fizo, and based on this assumption,...","We know that Fizo causes Blorn and Plim, Plim ...",yes,nested,799,"{'graph_id': 'graph8', 'model_id': 998, 'query..."
999,"Assume not Nuv, and based on this assumption, ...","We know that Nuv causes Splee and Blen, Blen c...",yes,nested,999,"{'graph_id': 'graph8', 'model_id': 999, 'query..."

In [48]:
questions = dataset_nested["question"].values.tolist()
contexts = dataset_nested["given_info"].values.tolist()
true_answers = dataset_nested["answer"].values.tolist()

In [49]:
prompts = get_prompt(intstruction,questions,contexts)

In [50]:
prompts[0]

'Instruction: Answer the question strictly using the causal facts provided. Do not introduce any new information. For counterfactuals, simulate the scenario along the causal chain step by step. Only output the final answer as Yes or No. Do not write anything else.\nContext:We know that Ziklo causes Blaf, Trune and Vork, not Vork causes Sline, Sline causes Frim, Frim or Vork causes Qado, Qado causes Jurf, and Jurf causes Lumbo.\nQuestion:Assume not Ziklo, and based on this assumption, further suppose not Sline. Would Lumbo occur?\nAnswer:'

In [51]:
predictions = training(prompts)

Iteration 0

Response:  No
Iteration 1

Response:  No
Iteration 2

Response:  No
Iteration 3

Response:  No
Iteration 4

Response:  No
Iteration 5

Response:  No
Iteration 6

Response: No
Iteration 7

Response:  No
Iteration 8

Response:  No
Iteration 9

Response:  No
Iteration 10

Response:  No
Iteration 11

Response:  No
Iteration 12

Response:  Yes
Iteration 13

Response:  No
Iteration 14

Response:  Yes
Iteration 15

Response:  Yes
Iteration 16

Response:  No
Iteration 17

Response: No
Iteration 18

Response:  No
Iteration 19

Response: Yes
Iteration 20

Response:  No
Iteration 21

Response:  No
Iteration 22

Response:  No
Iteration 23

Response:  No
Iteration 24

Response:  Yes
Iteration 25

Response:  No
Iteration 26

Response:  No
Iteration 27

Response:  No
Iteration 28

Response:  No
Iteration 29

Response: No
Iteration 30

Response:  Yes
Iteration 31

Response:  No
Iteration 32

Response:  No
Iteration 33

Response: Yes
Iteration 34

Response: No
Iteration 35

Response:  Yes
Iteration 36

Response:  Yes
Iteration 37

Response:  No
Iteration 38

Response:  No
Iteration 39

Response:  No
Iteration 40

Response:  Yes
Iteration 41

Response:  No
Iteration 42

Response: No
Iteration 43

Response:  Yes
Iteration 44

Response:  No
Iteration 45

Response:  No
Iteration 46

Response:  No
Iteration 47

Response:  No
Iteration 48

Response:  No
Iteration 49

Response:  Yes
Iteration 50

Response:  No
Iteration 51

Response:  No
Iteration 52

Response:  Yes
Iteration 53

Response:  Yes
Iteration 54

Response: Yes
Iteration 55

Response:  No
Iteration 56

Response:  No
Iteration 57

Response: No
Iteration 58

Response:  No
Iteration 59

Response:  No
Iteration 60

Response:  No
Iteration 61

Response:  No
Iteration 62

Response:  No
Iteration 63

Response:  Yes
Iteration 64

Response:  No
Iteration 65

Response:  No
Iteration 66

Response:  No
Iteration 67

Response:  Yes
Iteration 68

Response:  No
Iteration 69

Response:  Yes
Iteration 70

Response:  Yes
Iteration 71

Response:  No
Iteration 72

Response:  No
Iteration 73

Response: Yes
Iteration 74

Response: Yes
Iteration 75

Response:  No
Iteration 76

Response:  No
Iteration 77

Response:  No
Iteration 78

Response:  Yes
Iteration 79

Response:  No
Iteration 80

Response:  No
Iteration 81

Response:  No
Iteration 82

Response:  No
Iteration 83

Response:  No
Iteration 84

Response:  No
Iteration 85

Response:  No
Iteration 86

Response:  No
Iteration 87

Response:  No
Iteration 88

Response:  No
Iteration 89

Response: No
Iteration 90

Response:  Yes
Iteration 91

Response:  Yes
Iteration 92

Response:  No
Iteration 93

Response:  No
Iteration 94

Response:  No
Iteration 95

Response:  Yes
Iteration 96

Response:  No
Iteration 97

Response:  Yes
Iteration 98

Response:  No
Iteration 99

Response:  No
Iteration 100

Response:  No
Iteration 101

Response:  No
Iteration 102

Response:  Yes
Iteration 103

Response:  Yes
Iteration 104

Response:  No
Iteration 105

Response:  No
Iteration 106

Response:  No
Iteration 107

Response:  No
Iteration 108

Response:  Yes
Iteration 109

Response:  No
Iteration 110

Response:  No
Iteration 111

Response:  No
Iteration 112

Response:  No
Iteration 113

Response:  Yes
Iteration 114

Response:  No
Iteration 115

Response:  Yes
Iteration 116

Response:  No
Iteration 117

Response:  No
Iteration 118

Response:  No
Iteration 119

Response:  No
Iteration 120

Response:  No
Iteration 121

Response:  No
Iteration 122

Response:  No
Iteration 123

Response:  Yes
Iteration 124

Response:  Yes
Iteration 125

Response:  No
Iteration 126

Response:  Yes
Iteration 127

Response:  Yes
Iteration 128

Response: No
Iteration 129

Response:  No
Iteration 130

Response:  Yes
Iteration 131

Response:  Yes
Iteration 132

Response:  No
Iteration 133

Response:  No
Iteration 134

Response:  No
Iteration 135

Response:  Yes
Iteration 136

Response:  No
Iteration 137

Response:  No
Iteration 138

Response:  No
Iteration 139

Response:  Yes
Iteration 140

Response:  No
Iteration 141

Response:  No
Iteration 142

Response: No
Iteration 143

Response: No
Iteration 144

Response: No
Iteration 145

Response:  No
Iteration 146

Response:  No
Iteration 147

Response: Yes
Iteration 148

Response:  No
Iteration 149

Response:  Yes
Iteration 150

Response:  Yes
Iteration 151

Response:  No
Iteration 152

Response:  No
Iteration 153

Response:  Yes
Iteration 154

Response:  No
Iteration 155

Response:  No
Iteration 156

Response:  No
Iteration 157

Response:  Yes
Iteration 158

Response:  No
Iteration 159

Response: No
Iteration 160

Response:  No
Iteration 161

Response:  No
Iteration 162

Response:  Yes
Iteration 163

Response:  Yes
Iteration 164

Response: No
Iteration 165

Response:  No
Iteration 166

Response:  No
Iteration 167

Response:  Yes
Iteration 168

Response:  No
Iteration 169

Response: Yes
Iteration 170

Response:  No
Iteration 171

Response:  No
Iteration 172

Response:  No
Iteration 173

Response:  Yes
Iteration 174

Response:  No
Iteration 175

Response:  No
Iteration 176

Response:  Yes
Iteration 177

Response:  Yes
Iteration 178

Response:  No
Iteration 179

Response:  No
Iteration 180

Response:  No
Iteration 181

Response: No
Iteration 182

Response:  Yes
Iteration 183

Response:  No
Iteration 184

Response:  Yes
Iteration 185

Response:  Yes
Iteration 186

Response:  No
Iteration 187

Response:  Yes
Iteration 188

Response:  No
Iteration 189

Response:  No
Iteration 190

Response:  No
Iteration 191

Response:  No
Iteration 192

Response:  Yes
Iteration 193

Response:  No
Iteration 194

Response:  Yes
Iteration 195

Response:  No
Iteration 196

Response:  No
Iteration 197

Response:  Yes
Iteration 198

Response:  No
Iteration 199

Response:  No
Iteration 200

Response:  No
Iteration 201

Response:  Yes
Iteration 202

Response: No
Iteration 203

Response:  Yes
Iteration 204

Response:  No
Iteration 205

Response:  No
Iteration 206

Response: Yes
Iteration 207

Response:  No
Iteration 208

Response:  No
Iteration 209

Response: Yes
Iteration 210

Response:  No
Iteration 211

Response:  No
Iteration 212

Response:  No
Iteration 213

Response:  No
Iteration 214

Response: No
Iteration 215

Response:  No
Iteration 216

Response:  No
Iteration 217

Response:  No
Iteration 218

Response: No
Iteration 219

Response: Yes
Iteration 220

Response:  Yes
Iteration 221

Response:  No
Iteration 222

Response:  Yes
Iteration 223

Response:  Yes
Iteration 224

Response: Yes
Iteration 225

Response:  No
Iteration 226

Response:  No
Iteration 227

Response:  No
Iteration 228

Response:  No
Iteration 229

Response: No
Iteration 230

Response:  Yes
Iteration 231

Response:  No
Iteration 232

Response:  Yes
Iteration 233

Response:  Yes
Iteration 234

Response:  Yes
Iteration 235

Response:  Yes
Iteration 236

Response:  No
Iteration 237

Response:  Yes
Iteration 238

Response:  No
Iteration 239

Response: Yes
Iteration 240

Response:  No
Iteration 241

Response: Yes
Iteration 242

Response:  No
Iteration 243

Response:  Yes
Iteration 244

Response:  No
Iteration 245

Response:  No
Iteration 246

Response:  Yes
Iteration 247

Response: Yes
Iteration 248

Response:  No
Iteration 249

Response:  Yes

In [52]:
predictions_new = [elem.lower() for elem in predictions]

In [53]:
print(classification_report(true_answers,predictions_new,zero_division=0))

              precision    recall  f1-score   support

          no       0.51      0.70      0.59       125
         yes       0.53      0.34      0.41       125

    accuracy                           0.52       250
   macro avg       0.52      0.52      0.50       250
weighted avg       0.52      0.52      0.50       250

## Backdoor Questions

In [54]:
dataset_backdoor = dataset[dataset['type']=="backdoor"]

In [55]:
dataset_backdoor

,question,given_info,answer,type,question_id,meta
1000,Would Lumbo occur if not Ziklo instead of Ziklo?,"We know that Blaf causes Ziklo, Ziklo or Blaf ...",yes,backdoor,0,"{'graph_id': 'graph5', 'model_id': 0, 'query_t..."
1001,Would Zlim occur if not Glent instead of Glent?,"We know that Razz causes Glent, Glent or Razz ...",yes,backdoor,200,"{'graph_id': 'graph5', 'model_id': 1, 'query_t..."
1002,Would Klep occur if not Praf instead of Praf?,"We know that Vank causes Praf, Praf or Vank ca...",yes,backdoor,400,"{'graph_id': 'graph5', 'model_id': 2, 'query_t..."
1003,Would Jext occur if not Fizo instead of Fizo?,"We know that Blorn causes Fizo, Fizo or Blorn ...",yes,backdoor,600,"{'graph_id': 'graph5', 'model_id': 3, 'query_t..."
1004,Would Wrox occur if not Nuv instead of Nuv?,"We know that Splee causes Nuv, Nuv or Splee ca...",yes,backdoor,800,"{'graph_id': 'graph5', 'model_id': 4, 'query_t..."
...,...,...,...,...,...,...
1195,Would Lumbo occur if not Ziklo instead of Ziklo?,"We know that Blaf causes Ziklo, Blaf causes Tr...",no,backdoor,39,"{'graph_id': 'graph9', 'model_id': 195, 'query..."
1196,Would Zlim occur if not Glent instead of Glent?,"We know that Razz causes Glent, Razz causes Pe...",no,backdoor,239,"{'graph_id': 'graph9', 'model_id': 196, 'query..."
1197,Would Klep occur if not Praf instead of Praf?,"We know that Vank causes Praf, Vank causes Scu...",no,backdoor,439,"{'graph_id': 'graph9', 'model_id': 197, 'query..."
1198,Would Jext occur if not Fizo instead of Fizo?,"We know that Blorn causes Fizo, Blorn causes P...",no,backdoor,639,"{'graph_id': 'graph9', 'model_id': 198, 'query..."
1199,Would Wrox occur if not Nuv instead of Nuv?,"We know that Splee causes Nuv, Splee causes Bl...",no,backdoor,839,"{'graph_id': 'graph9', 'model_id': 199, 'query..."

In [56]:
questions = dataset_backdoor["question"].values.tolist()
contexts = dataset_backdoor["given_info"].values.tolist()
true_answers = dataset_backdoor["answer"].values.tolist()

In [57]:
prompts = get_prompt(intstruction,questions,contexts)

In [58]:
prompts[0]

'Instruction: Answer the question strictly using the causal facts provided. Do not introduce any new information. For counterfactuals, simulate the scenario along the causal chain step by step. Only output the final answer as Yes or No. Do not write anything else.\nContext:We know that Blaf causes Ziklo, Ziklo or Blaf causes Trune, Trune causes Vork, and Vork causes Lumbo. Blaf~ Bern(0.2). We observed Trune\nQuestion:Would Lumbo occur if not Ziklo instead of Ziklo?\nAnswer:'

In [59]:
predictions = training(prompts)

Iteration 0

Response:  Yes
Iteration 1

Response:  No
Iteration 2

Response: No
Iteration 3

Response: No
Iteration 4

Response:  No
Iteration 5

Response: No
Iteration 6

Response:  No
Iteration 7

Response: Yes
Iteration 8

Response: No
Iteration 9

Response: Yes
Iteration 10

Response: No
Iteration 11

Response:  No
Iteration 12

Response: No
Iteration 13

Response: No
Iteration 14

Response:  Yes
Iteration 15

Response: Yes
Iteration 16

Response:  No
Iteration 17

Response: No
Iteration 18

Response:  No
Iteration 19

Response:  No
Iteration 20

Response:  No
Iteration 21

Response: No
Iteration 22

Response: No
Iteration 23

Response:  No
Iteration 24

Response:  No
Iteration 25

Response: No
Iteration 26

Response:  No
Iteration 27

Response:  No
Iteration 28

Response: Yes
Iteration 29

Response:  No
Iteration 30

Response: Yes
Iteration 31

Response: Yes
Iteration 32

Response: Yes
Iteration 33

Response: No
Iteration 34

Response: No
Iteration 35

Response: Yes
Iteration 36

Response: Yes
Iteration 37

Response:  No
Iteration 38

Response:  No
Iteration 39

Response:  No
Iteration 40

Response: No
Iteration 41

Response:  No
Iteration 42

Response:  No
Iteration 43

Response: No
Iteration 44

Response: No
Iteration 45

Response: No
Iteration 46

Response:  Yes
Iteration 47

Response:  Yes
Iteration 48

Response:  No
Iteration 49

Response:  No
Iteration 50

Response: Yes
Iteration 51

Response: No
Iteration 52

Response:  No
Iteration 53

Response: No
Iteration 54

Response: Yes
Iteration 55

Response: No
Iteration 56

Response: Yes
Iteration 57

Response: Yes
Iteration 58

Response: No
Iteration 59

Response: Yes
Iteration 60

Response: No
Iteration 61

Response: No
Iteration 62

Response: No
Iteration 63

Response: No
Iteration 64

Response:  No
Iteration 65

Response: Yes
Iteration 66

Response: Yes
Iteration 67

Response: No
Iteration 68

Response:  Yes
Iteration 69

Response:  No
Iteration 70

Response:  No
Iteration 71

Response:  No
Iteration 72

Response:  Yes
Iteration 73

Response: No
Iteration 74

Response:  No
Iteration 75

Response: No
Iteration 76

Response: No
Iteration 77

Response:  No
Iteration 78

Response:  No
Iteration 79

Response: No
Iteration 80

Response:  No
Iteration 81

Response: No
Iteration 82

Response:  No
Iteration 83

Response: No
Iteration 84

Response:  No
Iteration 85

Response: Yes
Iteration 86

Response:  Yes
Iteration 87

Response: No
Iteration 88

Response:  No
Iteration 89

Response:  No
Iteration 90

Response: No
Iteration 91

Response: No
Iteration 92

Response:  Yes
Iteration 93

Response:  No
Iteration 94

Response: No
Iteration 95

Response: No
Iteration 96

Response: No
Iteration 97

Response:  No
Iteration 98

Response:  No
Iteration 99

Response: No
Iteration 100

Response: Yes
Iteration 101

Response:  No
Iteration 102

Response:  No
Iteration 103

Response:  No
Iteration 104

Response: No
Iteration 105

Response:  No
Iteration 106

Response:  No
Iteration 107

Response:  No
Iteration 108

Response:  No
Iteration 109

Response:  No
Iteration 110

Response:  No
Iteration 111

Response:  No
Iteration 112

Response:  Yes
Iteration 113

Response:  No
Iteration 114

Response:  No
Iteration 115

Response: Yes
Iteration 116

Response: No
Iteration 117

Response:  Yes
Iteration 118

Response: Yes
Iteration 119

Response: Yes
Iteration 120

Response: Yes
Iteration 121

Response:  No
Iteration 122

Response: No
Iteration 123

Response: No
Iteration 124

Response: Yes
Iteration 125

Response: Yes
Iteration 126

Response: Yes
Iteration 127

Response: Yes
Iteration 128

Response:  No
Iteration 129

Response:  No
Iteration 130

Response: Yes
Iteration 131

Response: No
Iteration 132

Response:  No
Iteration 133

Response: No
Iteration 134

Response: No
Iteration 135

Response:  Yes
Iteration 136

Response:  No
Iteration 137

Response:  Yes
Iteration 138

Response: Yes
Iteration 139

Response: Yes
Iteration 140

Response:  No
Iteration 141

Response:  No
Iteration 142

Response:  Yes
Iteration 143

Response: Yes
Iteration 144

Response:  Yes
Iteration 145

Response: Yes
Iteration 146

Response:  Yes
Iteration 147

Response:  No
Iteration 148

Response:  No
Iteration 149

Response:  Yes
Iteration 150

Response:  Yes
Iteration 151

Response:  No
Iteration 152

Response:  No
Iteration 153

Response: No
Iteration 154

Response: No
Iteration 155

Response:  No
Iteration 156

Response:  No
Iteration 157

Response:  No
Iteration 158

Response:  Yes
Iteration 159

Response:  Yes
Iteration 160

Response:  Yes
Iteration 161

Response:  No
Iteration 162

Response:  Yes
Iteration 163

Response:  Yes
Iteration 164

Response:  No
Iteration 165

Response: Yes
Iteration 166

Response:  No
Iteration 167

Response:  Yes
Iteration 168

Response:  No
Iteration 169

Response: Yes
Iteration 170

Response:  No
Iteration 171

Response:  No
Iteration 172

Response:  No
Iteration 173

Response:  No
Iteration 174

Response:  No
Iteration 175

Response:  No
Iteration 176

Response:  No
Iteration 177

Response:  No
Iteration 178

Response: Yes
Iteration 179

Response:  No
Iteration 180

Response:  No
Iteration 181

Response:  No
Iteration 182

Response:  No
Iteration 183

Response:  Yes
Iteration 184

Response:  No
Iteration 185

Response:  No
Iteration 186

Response:  No
Iteration 187

Response:  No
Iteration 188

Response:  No
Iteration 189

Response:  No
Iteration 190

Response: No
Iteration 191

Response:  No
Iteration 192

Response:  No
Iteration 193

Response:  No
Iteration 194

Response: No
Iteration 195

Response:  No
Iteration 196

Response: No
Iteration 197

Response:  Yes
Iteration 198

Response: Yes
Iteration 199

Response:  No

In [60]:
predictions_new = [elem.lower() for elem in predictions]

In [61]:
print(classification_report(true_answers,predictions_new,zero_division=0))

              precision    recall  f1-score   support

          no       0.60      0.80      0.69       105
         yes       0.65      0.41      0.50        95

    accuracy                           0.61       200
   macro avg       0.62      0.61      0.59       200
weighted avg       0.62      0.61      0.60       200