# Evaluation on LLaMA 3 + Instruction-Tuned using BBEH benchmark for reasoning tasks

In [ ]:
!pip install bitsandbytes

Collecting bitsandbytes
  Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.9.0+cu126)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (25.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.20.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)
Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl (59.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.1/59.1 MB 14.8 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.49.1

In [ ]:
import json
import torch
import pandas as pd
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from sklearn.metrics import classification_report

In [ ]:
from huggingface_hub import login
login()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [ ]:
model_llama = "meta-llama/Llama-3.1-8B-Instruct"

In [ ]:
bitsandbytes_config = BitsAndBytesConfig(load_in_4bit=True,
                                         bnb_4bit_compute_dtype=torch.float16,
                                         bnb_4bit_quant_type='nf4',
                                         bnb_4bit_use_double_quant=True)

In [ ]:
tokenizer_llama = AutoTokenizer.from_pretrained(model_llama)
model_llama = AutoModelForCausalLM.from_pretrained(model_llama,
                                             quantization_config=bitsandbytes_config,
                                             device_map="auto",
                                             offload_folder="offload")

config.json:   0%|          | 0.00/855 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/55.4k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/184 [00:00<?, ?B/s]

In [ ]:
tokenizer_llama.pad_token = tokenizer_llama.eos_token

In [ ]:
def load_json(path):
  with open(path,"r") as f:
    data = json.load(f)

    df = pd.DataFrame(data['examples'])
    return df

In [ ]:
def get_prompt(instruction,questions):
  prompts=[]
  for i in range(len(questions)):
    prompt = f"{instruction}\n\n{questions[i]}\n\nAnswer:"
    prompts.append(prompt)
  return prompts

In [ ]:
def training(prompts,num_tokens=1):
  predictions=[]
  for i in range(len(prompts)):
    input_tokens = tokenizer_llama(prompts[i],return_tensors="pt")
    input_ids = input_tokens["input_ids"].to("cuda:0")
    attention_mask = input_tokens["attention_mask"].to("cuda:0")
    output_tokens = model_llama.generate(input_ids=input_ids,attention_mask=attention_mask,max_new_tokens=num_tokens,pad_token_id=tokenizer_llama.pad_token_id)
    response = tokenizer_llama.decode(output_tokens[0], skip_special_tokens=True)
    pred_answer = response.split("Answer:")[1].split("Explanation:")[0]
    print(f"Iteration {i}\n")
    print(f"Response: {pred_answer}")
    pred_answer = pred_answer.replace("\n","").strip()
    predictions.append(pred_answer)

  return predictions

## Task Casual Understanding

In [ ]:
dataset = load_json("/content/task_casual_understanding.json")

In [ ]:
dataset

                                                 input target
0    Question: Lauren and Jane work for the same co...    Yes
1    Question: Lauren and Jane work for the same co...    Yes
2    Question: The receptionist in the philosophy d...    Yes
3    Question: The receptionist in the philosophy d...     No
4    Question: Claire's parents bought her an old c...    Yes
..                                                 ...    ...
195  Question: A test tube contains a mixture. Sam ...    Yes
196  Question: Reagent X and Y are both added to a ...     No
197  Question: There is a test tube on the left and...    Yes
198  Question: Sam is heating Reagent X in a test t...    Yes
199  Question: Sam throws a poisonous test tube tow...     No

[200 rows x 2 columns]

In [ ]:
dataset['input'][0]

"Question: Lauren and Jane work for the same company. They each need to use a computer for work sometimes. Unfortunately, the computer isn't very powerful. If two people are logged on at the same time, it usually crashes. So the company decided to institute an official policy. It declared that Lauren would be the only one permitted to use the computer in the mornings and that Jane would be the only one permitted to use the computer in the afternoons. As expected, Lauren logged on the computer the next day at 9:00 am. But Jane decided to disobey the official policy. She also logged on at 9:00 am. The computer crashed immediately. Did Jane cause the computer to crash?  Reply Yes or No based on the answer the majority of people would give. If you think people would be split roughly 50-50 between Yes and No then reply Ambiguous."

In [ ]:
instruction = """
Instruction: You are an AI that answers causal questions based on what the majority of people would think.
"""

In [ ]:
questions = dataset['input'].values.tolist()

In [ ]:
true_answers = dataset['target'].values.tolist()

In [ ]:
questions[2]

"Question: The receptionist in the philosophy department keeps her desk stocked with pens. The administrative assistants are allowed to take the pens, but faculty members are supposed to buy their own. The administrative assistants typically do take the pens. Unfortunately, so do the faculty members. The receptionist has repeatedly emailed them reminders that only administrative assistants are allowed to take the pens. On Monday morning, one of the administrative assistants encounters Professor Smith walking past the receptionist's desk. Both take pens. Later that day, the receptionist needs to take an important message... but she has a problem. There are no pens left on her desk. Did Professor Smith cause the problem?  Reply Yes or No based on the answer the majority of people would give. If you think people would be split roughly 50-50 between Yes and No then reply Ambiguous."

In [ ]:
prompts = get_prompt(instruction,questions)

In [ ]:
prompts[1]

"\nInstruction: You are an AI that answers causal questions based on what the majority of people would think.\n\n\nQuestion: Lauren and Jane work for the same company. They each need to use a computer for work sometimes. Unfortunately, the computer isn't very powerful. If two people are logged on at the same time, it usually crashes. So the company decided to institute an official policy. It declared that Jane would be the only one permitted to use the computer in the mornings and that Lauren would be the only one permitted to use the computer in the afternoons. As expected, Jane logged on the computer the next day at 9:00 am. But Lauren decided to disobey the official policy. She also logged on at 9:00 am. The computer crashed immediately. Did Jane cause the computer to crash?  Reply Yes or No based on the answer the majority of people would give. If you think people would be split roughly 50-50 between Yes and No then reply Ambiguous.\n\nAnswer:"

In [ ]:
predictions = training(prompts)

Iteration 0

Response:  Yes
Iteration 1

Response:  Yes
Iteration 2

Response:  Yes
Iteration 3

Response:  Yes
Iteration 4

Response:  Yes
Iteration 5

Response:  No
Iteration 6

Response:  No
Iteration 7

Response:  No
Iteration 8

Response:  No
Iteration 9

Response:  Yes
Iteration 10

Response:  No
Iteration 11

Response:  No
Iteration 12

Response:  No
Iteration 13

Response:  No
Iteration 14

Response:  Yes
Iteration 15

Response:  Yes
Iteration 16

Response:  Yes
Iteration 17

Response:  Yes
Iteration 18

Response:  No
Iteration 19

Response:  No
Iteration 20

Response:  No
Iteration 21

Response:  Yes
Iteration 22

Response:  No
Iteration 23

Response:  Yes
Iteration 24

Response:  No
Iteration 25

Response:  Yes
Iteration 26

Response:  No
Iteration 27

Response:  No
Iteration 28

Response:  Yes
Iteration 29

Response:  No
Iteration 30

Response:  Yes
Iteration 31

Response:  No
Iteration 32

Response:  No
Iteration 33

Response:  No
Iteration 34

Response:  No
Iteration 35

Response:  No
Iteration 36

Response:  No
Iteration 37

Response:  Yes
Iteration 38

Response:  Yes
Iteration 39

Response:  Yes
Iteration 40

Response:  Yes
Iteration 41

Response:  Yes
Iteration 42

Response:  Yes
Iteration 43

Response:  No
Iteration 44

Response:  No
Iteration 45

Response:  Yes
Iteration 46

Response:  Yes
Iteration 47

Response:  No
Iteration 48

Response:  No
Iteration 49

Response:  Yes
Iteration 50

Response:  No
Iteration 51

Response:  No
Iteration 52

Response:  No
Iteration 53

Response:  No
Iteration 54

Response:  Yes
Iteration 55

Response:  No
Iteration 56

Response:  No
Iteration 57

Response:  Yes
Iteration 58

Response:  No
Iteration 59

Response:  No
Iteration 60

Response:  No
Iteration 61

Response:  Yes
Iteration 62

Response:  Yes
Iteration 63

Response:  No
Iteration 64

Response:  Yes
Iteration 65

Response:  No
Iteration 66

Response:  Yes
Iteration 67

Response:  No
Iteration 68

Response:  Yes
Iteration 69

Response:  No
Iteration 70

Response:  Yes
Iteration 71

Response:  Yes
Iteration 72

Response:  Yes
Iteration 73

Response:  No
Iteration 74

Response:  No
Iteration 75

Response:  No
Iteration 76

Response:  Yes
Iteration 77

Response:  Yes
Iteration 78

Response:  No
Iteration 79

Response:  Yes
Iteration 80

Response:  No
Iteration 81

Response:  No
Iteration 82

Response:  Yes
Iteration 83

Response:  No
Iteration 84

Response:  No
Iteration 85

Response:  No
Iteration 86

Response:  No
Iteration 87

Response:  No
Iteration 88

Response:  No
Iteration 89

Response:  Yes
Iteration 90

Response:  Yes
Iteration 91

Response:  Yes
Iteration 92

Response:  Yes
Iteration 93

Response:  Yes
Iteration 94

Response:  No
Iteration 95

Response:  Yes
Iteration 96

Response:  Yes
Iteration 97

Response:  No
Iteration 98

Response:  Yes
Iteration 99

Response:  No
Iteration 100

Response:  No
Iteration 101

Response:  No
Iteration 102

Response:  No
Iteration 103

Response:  No
Iteration 104

Response:  Yes
Iteration 105

Response:  No
Iteration 106

Response:  No
Iteration 107

Response:  No
Iteration 108

Response:  Yes
Iteration 109

Response:  Yes
Iteration 110

Response:  Yes
Iteration 111

Response:  Yes
Iteration 112

Response:  Yes
Iteration 113

Response:  Yes
Iteration 114

Response:  Yes
Iteration 115

Response:  Yes
Iteration 116

Response:  Yes
Iteration 117

Response:  No
Iteration 118

Response:  Yes
Iteration 119

Response:  Yes
Iteration 120

Response:  Yes
Iteration 121

Response:  Yes
Iteration 122

Response:  Yes
Iteration 123

Response:  Yes
Iteration 124

Response:  Yes
Iteration 125

Response:  Yes
Iteration 126

Response:  No
Iteration 127

Response:  No
Iteration 128

Response:  No
Iteration 129

Response:  Yes
Iteration 130

Response:  No
Iteration 131

Response:  No
Iteration 132

Response:  Yes
Iteration 133

Response:  No
Iteration 134

Response:  Yes
Iteration 135

Response:  Yes
Iteration 136

Response:  No
Iteration 137

Response:  No
Iteration 138

Response:  No
Iteration 139

Response:  Yes
Iteration 140

Response:  Yes
Iteration 141

Response:  Yes
Iteration 142

Response:  No
Iteration 143

Response:  According
Iteration 144

Response:  A
Iteration 145

Response:  A
Iteration 146

Response:  No
Iteration 147

Response:  A
Iteration 148

Response:  A
Iteration 149

Response:  No
Iteration 150

Response:  A
Iteration 151

Response:  This
Iteration 152

Response:  No
Iteration 153

Response:  No
Iteration 154

Response:  Yes
Iteration 155

Response:  No
Iteration 156

Response:  No
Iteration 157

Response:  No
Iteration 158

Response:  No
Iteration 159

Response:  The
Iteration 160

Response:  No
Iteration 161

Response:  No
Iteration 162

Response:  According
Iteration 163

Response:  No
Iteration 164

Response:  No
Iteration 165

Response:  Yes
Iteration 166

Response:  A
Iteration 167

Response:  Yes
Iteration 168

Response:  No
Iteration 169

Response:  Yes
Iteration 170

Response:  The
Iteration 171

Response:  No
Iteration 172

Response:  No
Iteration 173

Response:  No
Iteration 174

Response:  No
Iteration 175

Response:  No
Iteration 176

Response:  A
Iteration 177

Response:  No
Iteration 178

Response:  According
Iteration 179

Response:  A
Iteration 180

Response:  According
Iteration 181

Response:  The
Iteration 182

Response:  No
Iteration 183

Response:  No
Iteration 184

Response:  According
Iteration 185

Response:  Yes
Iteration 186

Response:  No
Iteration 187

Response:  A
Iteration 188

Response:  The
Iteration 189

Response:  No
Iteration 190

Response:  No
Iteration 191

Response:  Yes
Iteration 192

Response:  No
Iteration 193

Response:  Yes
Iteration 194

Response:  Yes
Iteration 195

Response:  A
Iteration 196

Response:  No
Iteration 197

Response:  A
Iteration 198

Response:  No
Iteration 199

Response:  A

In [ ]:
true_answers[:10]

['Yes', 'Yes', 'Yes', 'No', 'Yes', 'Ambiguous', 'No', 'Ambiguous', 'Yes', 'No']

In [ ]:
predictions[:10]

['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes']

In [ ]:
predictions = [p if p=="Yes" or p=="No" else "Ambiguous" for p in predictions]

In [ ]:
predictions[:19]

['Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'No',
 'No',
 'No',
 'Yes',
 'No',
 'No',
 'No',
 'No',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No']

In [ ]:
print(classification_report(true_answers,predictions,zero_division=0))

              precision    recall  f1-score   support

   Ambiguous       0.00      0.00      0.00        45
          No       0.38      0.47      0.42        80
         Yes       0.37      0.39      0.38        75

    accuracy                           0.34       200
   macro avg       0.25      0.29      0.27       200
weighted avg       0.29      0.34      0.31       200

## Task Movie Recommendation

In [ ]:
dataset = load_json("/content/task_movie_recommendation.json")

In [ ]:
dataset

                                                 input target
0    Which option has more similar movies in terms ...    (E)
1    Which option has more similar movies in terms ...    (C)
2    Which option has more similar movies in terms ...    (C)
3    Which option has more similar movies in terms ...    (A)
4    Which option has more similar movies in terms ...    (I)
..                                                 ...    ...
195  Which option has more similar movies in terms ...    (E)
196  Which option has more similar movies in terms ...    (E)
197  Which option has more similar movies in terms ...    (E)
198  Which option has more similar movies in terms ...    (A)
199  Which option has more similar movies in terms ...    (F)

[200 rows x 2 columns]

In [ ]:
questions = dataset['input'].values.tolist()

In [ ]:
questions[0]

'Which option has more similar movies in terms of whether a group of people will like them or not?\nOptions:\n(A) The Mask, The Lion King, Pretty Woman, Batman, The Front Page\n(B) Maelstrom, The Lion King, Lamerica, Pretty Woman, The Front Page\n(C) The Fugitive, The Mask, Maelstrom, Pretty Woman, Batman\n(D) The Lion King, The Mask, Lamerica, Maelstrom, Batman\n(E) Batman, The Lion King, Pretty Woman, The Fugitive, The Mask\n(F) Batman, The Mask, Maelstrom, The Fugitive, Lamerica\n(G) The Front Page, The Fugitive, Maelstrom, Lamerica, Batman\n(H) The Fugitive, Pretty Woman, Lamerica, Batman, The Lion King\n(I) The Fugitive, Lamerica, The Mask, The Front Page, Batman\n(J) The Fugitive, Pretty Woman, The Lion King, The Mask, The Front Page\n'

In [ ]:
questions[1]

'Which option has more similar movies in terms of whether a group of people will like them or not?\nOptions:\n(A) Street Fighter II The Animated Movie, The Sixth Sense, The Matrix, The Shawshank Redemption, Terminator 2 Judgment Day\n(B) The Boy Who Could Fly, The Sheltering Sky, Forrest Gump, Terminator 2 Judgment Day, The Matrix\n(C) Forrest Gump, The Shawshank Redemption, Terminator 2 Judgment Day, The Matrix, The Sixth Sense\n(D) The Boy Who Could Fly, The Sheltering Sky, Street Fighter II The Animated Movie, The Sixth Sense, Terminator 2 Judgment Day\n(E) The Matrix, The Boy Who Could Fly, Forrest Gump, The Shawshank Redemption, The Sixth Sense\n(F) The Boy Who Could Fly, The Matrix, Terminator 2 Judgment Day, The Sixth Sense, Forrest Gump\n(G) The Shawshank Redemption, Street Fighter II The Animated Movie, The Sheltering Sky, The Matrix, The Boy Who Could Fly\n(H) Street Fighter II The Animated Movie, The Matrix, The Sixth Sense, The Shawshank Redemption, The Sheltering Sky\n(I) The Sheltering Sky, Street Fighter II The Animated Movie, Forrest Gump, Terminator 2 Judgment Day, The Boy Who Could Fly\n(J) Street Fighter II The Animated Movie, The Sixth Sense, The Boy Who Could Fly, The Shawshank Redemption, Forrest Gump\n'

In [ ]:
true_answers = dataset['target'].values.tolist()

In [ ]:
true_answers = [x.strip("()").upper() for x in true_answers]
true_answers[:10]

['E', 'C', 'C', 'A', 'I', 'D', 'B', 'F', 'D', 'H']

In [ ]:
instruction = f"""You are an assistant that determines which group of movies is most similar in terms of what people are likely to enjoy together. Reply only with the letter (A, B, C, D, E, F, G, H, I, or J) of the group that is most similar.
Do not write any explanation, full movie names, or extra text. The answer must be a single uppercase letter."""

In [ ]:
prompts = get_prompt(instruction,questions)

In [ ]:
prompts[1]

'You are an assistant that determines which group of movies is most similar in terms of what people are likely to enjoy together. Reply only with the letter (A, B, C, D, E, F, G, H, I, or J) of the group that is most similar.\nDo not write any explanation, full movie names, or extra text. The answer must be a single uppercase letter.\n\nWhich option has more similar movies in terms of whether a group of people will like them or not?\nOptions:\n(A) Street Fighter II The Animated Movie, The Sixth Sense, The Matrix, The Shawshank Redemption, Terminator 2 Judgment Day\n(B) The Boy Who Could Fly, The Sheltering Sky, Forrest Gump, Terminator 2 Judgment Day, The Matrix\n(C) Forrest Gump, The Shawshank Redemption, Terminator 2 Judgment Day, The Matrix, The Sixth Sense\n(D) The Boy Who Could Fly, The Sheltering Sky, Street Fighter II The Animated Movie, The Sixth Sense, Terminator 2 Judgment Day\n(E) The Matrix, The Boy Who Could Fly, Forrest Gump, The Shawshank Redemption, The Sixth Sense\n(F) The Boy Who Could Fly, The Matrix, Terminator 2 Judgment Day, The Sixth Sense, Forrest Gump\n(G) The Shawshank Redemption, Street Fighter II The Animated Movie, The Sheltering Sky, The Matrix, The Boy Who Could Fly\n(H) Street Fighter II The Animated Movie, The Matrix, The Sixth Sense, The Shawshank Redemption, The Sheltering Sky\n(I) The Sheltering Sky, Street Fighter II The Animated Movie, Forrest Gump, Terminator 2 Judgment Day, The Boy Who Could Fly\n(J) Street Fighter II The Animated Movie, The Sixth Sense, The Boy Who Could Fly, The Shawshank Redemption, Forrest Gump\n\n\nAnswer:'

In [ ]:
predictions = training(prompts)

Iteration 0

Response:  B
Iteration 1

Response:  C
Iteration 2

Response:  A
Iteration 3

Response:  F
Iteration 4

Response:  B
Iteration 5

Response:  C
Iteration 6

Response:  A
Iteration 7

Response:  B
Iteration 8

Response:  C
Iteration 9

Response:  F
Iteration 10

Response:  A
Iteration 11

Response:  I
Iteration 12

Response:  C
Iteration 13

Response:  C
Iteration 14

Response:  B
Iteration 15

Response:  B
Iteration 16

Response:  A
Iteration 17

Response:  B
Iteration 18

Response:  C
Iteration 19

Response:  A
Iteration 20

Response:  C
Iteration 21

Response:  C
Iteration 22

Response:  D
Iteration 23

Response:  F
Iteration 24

Response:  B
Iteration 25

Response:  C
Iteration 26

Response:  A
Iteration 27

Response:  B
Iteration 28

Response:  C
Iteration 29

Response:  B
Iteration 30

Response:  A
Iteration 31

Response:  C
Iteration 32

Response:  B
Iteration 33

Response:  C
Iteration 34

Response:  C
Iteration 35

Response:  G
Iteration 36

Response:  B
Iteration 37

Response:  A
Iteration 38

Response:  C
Iteration 39

Response:  C
Iteration 40

Response:  G
Iteration 41

Response:  C
Iteration 42

Response:  F
Iteration 43

Response:  C
Iteration 44

Response:  A
Iteration 45

Response:  C
Iteration 46

Response:  F
Iteration 47

Response:  G
Iteration 48

Response:  B
Iteration 49

Response:  A
Iteration 50

Response:  C
Iteration 51

Response:  F
Iteration 52

Response:  A
Iteration 53

Response:  I
Iteration 54

Response:  A
Iteration 55

Response:  F
Iteration 56

Response:  A
Iteration 57

Response:  B
Iteration 58

Response:  A
Iteration 59

Response:  F
Iteration 60

Response:  B
Iteration 61

Response:  B
Iteration 62

Response:  B
Iteration 63

Response:  A
Iteration 64

Response:  F
Iteration 65

Response:  A
Iteration 66

Response:  B
Iteration 67

Response:  D
Iteration 68

Response:  B
Iteration 69

Response:  A
Iteration 70

Response:  A
Iteration 71

Response:  A
Iteration 72

Response:  A
Iteration 73

Response:  B
Iteration 74

Response:  C
Iteration 75

Response:  C
Iteration 76

Response:  A
Iteration 77

Response:  C
Iteration 78

Response:  A
Iteration 79

Response:  F
Iteration 80

Response:  B
Iteration 81

Response:  C
Iteration 82

Response:  C
Iteration 83

Response:  I
Iteration 84

Response:  A
Iteration 85

Response:  B
Iteration 86

Response:  B
Iteration 87

Response:  B
Iteration 88

Response:  B
Iteration 89

Response:  B
Iteration 90

Response:  C
Iteration 91

Response:  A
Iteration 92

Response:  B
Iteration 93

Response:  B
Iteration 94

Response:  A
Iteration 95

Response:  B
Iteration 96

Response:  A
Iteration 97

Response:  C
Iteration 98

Response:  C
Iteration 99

Response:  C
Iteration 100

Response:  A
Iteration 101

Response:  A
Iteration 102

Response:  A
Iteration 103

Response:  A
Iteration 104

Response:  C
Iteration 105

Response:  A
Iteration 106

Response:  F
Iteration 107

Response:  C
Iteration 108

Response:  B
Iteration 109

Response:  A
Iteration 110

Response:  A
Iteration 111

Response:  B
Iteration 112

Response:  B
Iteration 113

Response:  A
Iteration 114

Response:  B
Iteration 115

Response:  F
Iteration 116

Response:  C
Iteration 117

Response:  B
Iteration 118

Response:  F
Iteration 119

Response:  B
Iteration 120

Response:  C
Iteration 121

Response:  B
Iteration 122

Response:  I
Iteration 123

Response:  A
Iteration 124

Response:  B
Iteration 125

Response:  F
Iteration 126

Response:  B
Iteration 127

Response:  B
Iteration 128

Response:  G
Iteration 129

Response:  A
Iteration 130

Response:  F
Iteration 131

Response:  A
Iteration 132

Response:  A
Iteration 133

Response:  A
Iteration 134

Response:  B
Iteration 135

Response:  B
Iteration 136

Response:  C
Iteration 137

Response:  B
Iteration 138

Response:  A
Iteration 139

Response:  C
Iteration 140

Response:  C
Iteration 141

Response:  F
Iteration 142

Response:  C
Iteration 143

Response:  B
Iteration 144

Response:  B
Iteration 145

Response:  C
Iteration 146

Response:  E
Iteration 147

Response:  C
Iteration 148

Response:  C
Iteration 149

Response:  G
Iteration 150

Response:  B
Iteration 151

Response:  E
Iteration 152

Response:  A
Iteration 153

Response:  C
Iteration 154

Response:  G
Iteration 155

Response:  C
Iteration 156

Response:  E
Iteration 157

Response:  A
Iteration 158

Response:  C
Iteration 159

Response:  C
Iteration 160

Response:  C
Iteration 161

Response:  G
Iteration 162

Response:  I
Iteration 163

Response:  C
Iteration 164

Response:  G
Iteration 165

Response:  B
Iteration 166

Response:  C
Iteration 167

Response:  A
Iteration 168

Response:  F
Iteration 169

Response:  A
Iteration 170

Response:  B
Iteration 171

Response:  F
Iteration 172

Response:  A
Iteration 173

Response:  A
Iteration 174

Response:  D
Iteration 175

Response:  C
Iteration 176

Response:  A
Iteration 177

Response:  G
Iteration 178

Response:  B
Iteration 179

Response:  C
Iteration 180

Response:  C
Iteration 181

Response:  C
Iteration 182

Response:  B
Iteration 183

Response:  F
Iteration 184

Response:  A
Iteration 185

Response:  B
Iteration 186

Response:  A
Iteration 187

Response:  F
Iteration 188

Response:  B
Iteration 189

Response:  C
Iteration 190

Response:  B
Iteration 191

Response:  A
Iteration 192

Response:  E
Iteration 193

Response:  F
Iteration 194

Response:  A
Iteration 195

Response:  B
Iteration 196

Response:  B
Iteration 197

Response:  F
Iteration 198

Response:  F
Iteration 199

Response:  C

In [ ]:
predictions[:10]

['B', 'C', 'A', 'F', 'B', 'C', 'A', 'B', 'C', 'F']

In [ ]:
print(classification_report(true_answers,predictions,zero_division=0))

              precision    recall  f1-score   support

           A       0.08      0.15      0.10        26
           B       0.11      0.35      0.17        17
           C       0.08      0.22      0.11        18
           D       0.67      0.10      0.17        20
           E       0.00      0.00      0.00        21
           F       0.22      0.28      0.24        18
           G       0.11      0.05      0.06        22
           H       0.00      0.00      0.00        21
           I       0.20      0.06      0.09        17
           J       0.00      0.00      0.00        20

    accuracy                           0.12       200
   macro avg       0.15      0.12      0.10       200
weighted avg       0.14      0.12      0.09       200

## Task Disambiguation QA

In [ ]:
dataset = load_json("/content/task_disambiguationQA.json")

In [ ]:
dataset

                                                 input target
0    Here is a sentence with pronoun(s) whose antec...    (A)
1    Here is a sentence with pronoun(s) whose antec...    (D)
2    Here is a sentence with pronoun(s) whose antec...    (E)
3    Here is a sentence with pronoun(s) whose antec...    (B)
4    Here is a sentence with pronoun(s) whose antec...    (A)
..                                                 ...    ...
115  Here is a sentence with pronoun(s) whose antec...    (D)
116  Here is a sentence with pronoun(s) whose antec...    (A)
117  Here is a sentence with pronoun(s) whose antec...    (B)
118  Here is a sentence with pronoun(s) whose antec...    (D)
119  Here is a sentence with pronoun(s) whose antec...    (E)

[120 rows x 2 columns]

In [ ]:
dataset['target'].value_counts()

target
(B)    25
(D)    24
(C)    23
(A)    22
(E)    17
(F)     7
(G)     1
(H)     1
Name: count, dtype: int64

In [ ]:
questions = dataset['input'].values.tolist()

In [ ]:
true_answers = dataset['target'].values.tolist()

In [ ]:
true_answers = [x.strip("()").upper() for x in true_answers]
true_answers[:10]

['A', 'D', 'E', 'B', 'A', 'B', 'B', 'A', 'C', 'D']

In [ ]:
questions[1]

'Here is a sentence with pronoun(s) whose antecedent(s) can either be derived from the context or is ambiguous.\nSentence: The designer called the janitor and asked him to clean the room as soon as possible, but he went to fetch a cup of coffee first and then returned to his desk.\nWhich of the following options correctly explains the antecedent(s) of the pronoun(s)?\n(A) Designer is cleaning the room as soon as possible and got coffee.\n(B) Janitor is cleaning the room as soon as possible and got coffee.\n(C) Designer is cleaning the room as soon as possible and janitor got coffee.\n(D) Janitor is cleaning the room as soon as possible and designer got coffee.\n(E) Ambiguous.'

In [ ]:
instruction = f"""You are an AI assistant solving a pronoun disambiguation task.

For each sentence:
- Identify what the pronoun(s) most likely refer to based on common sense.
- If more than one interpretation is equally plausible, select “Ambiguous”.

Rules:
- Do not assume information that is not stated.
- Do not infer intent beyond what is commonly assumed.
- Choose exactly one answer from (A)–(H) based on available letters.

Final answer format:
(A), (B), (C), (D), (E), (H), (G), or (F)
"""

In [ ]:
prompts = get_prompt(instruction,questions)

In [ ]:
prompts[1]

'You are an AI assistant solving a pronoun disambiguation task.\n\nFor each sentence:\n- Identify what the pronoun(s) most likely refer to based on common sense.\n- If more than one interpretation is equally plausible, select “Ambiguous”.\n\nRules:\n- Do not assume information that is not stated.\n- Do not infer intent beyond what is commonly assumed.\n- Choose exactly one answer from (A)–(H) based on available letters.\n\nFinal answer format:\n(A), (B), (C), (D), (E), (H), (G), or (F)\n\n\nHere is a sentence with pronoun(s) whose antecedent(s) can either be derived from the context or is ambiguous.\nSentence: The designer called the janitor and asked him to clean the room as soon as possible, but he went to fetch a cup of coffee first and then returned to his desk.\nWhich of the following options correctly explains the antecedent(s) of the pronoun(s)?\n(A) Designer is cleaning the room as soon as possible and got coffee.\n(B) Janitor is cleaning the room as soon as possible and got coffee.\n(C) Designer is cleaning the room as soon as possible and janitor got coffee.\n(D) Janitor is cleaning the room as soon as possible and designer got coffee.\n(E) Ambiguous.\n\nAnswer:'

In [ ]:
predictions = training(prompts,num_tokens=3)

Iteration 0

Response:  (E)
Iteration 1

Response:  (E)
Iteration 2

Response:  (E)
Iteration 3

Response:  (E)
Iteration 4

Response:  (E)
Iteration 5

Response:  (E)
Iteration 6

Response:  (C)
Iteration 7

Response:  (D)
Iteration 8

Response:  (D)
Iteration 9

Response:  (D)
Iteration 10

Response:  (D)
Iteration 11

Response:  (E)
Iteration 12

Response:  (C)
Iteration 13

Response:  (E)
Iteration 14

Response:  (C)
Iteration 15

Response:  (E)
Iteration 16

Response:  (E)
Iteration 17

Response:  (E)
Iteration 18

Response:  (E)
Iteration 19

Response:  (C)
Iteration 20

Response:  (B)
Iteration 21

Response:  (E)
Iteration 22

Response:  (D)
Iteration 23

Response:  (C)
Iteration 24

Response:  (C)
Iteration 25

Response:  (A)
Iteration 26

Response:  (E)
Iteration 27

Response:  (A)
Iteration 28

Response:  (F)
Iteration 29

Response:  (F)
Iteration 30

Response:  (B)
Iteration 31

Response:  (A),
Iteration 32

Response:  (E)
Iteration 33

Response:  (C)
Iteration 34

Response:  (E)
Iteration 35

Response:  (D)
Iteration 36

Response:  (E)
Iteration 37

Response:  (B)
Iteration 38

Response:  (D)
Iteration 39

Response:  (E)
Iteration 40

Response:  (C)
Iteration 41

Response:  (F)
Iteration 42

Response:  (E)
Iteration 43

Response:  (E)
Iteration 44

Response:  (D)
Iteration 45

Response:  (A)
Iteration 46

Response:  (B)
Iteration 47

Response:  (B)
Iteration 48

Response:  (C)
Iteration 49

Response:  (C)
Iteration 50

Response:  (F)
Iteration 51

Response:  (F)
Iteration 52

Response:  (F)
Iteration 53

Response:  (A)
Iteration 54

Response:  (E)
Iteration 55

Response:  (D)
Iteration 56

Response:  (C)
Iteration 57

Response:  (B)
Iteration 58

Response:  (E)
Iteration 59

Response:  (E)
Iteration 60

Response:  (H)
Iteration 61

Response:  (E)
Iteration 62

Response:  (E)
Iteration 63

Response:  (A)
Iteration 64

Response:  (C)
Iteration 65

Response:  (D)
Iteration 66

Response:  (D)
Iteration 67

Response:  (C)
Iteration 68

Response:  (C)
Iteration 69

Response:  (D)
Iteration 70

Response:  (D)
Iteration 71

Response:  (E)
Iteration 72

Response:  (E)
Iteration 73

Response:  (C)
Iteration 74

Response:  (C)
Iteration 75

Response:  (C)
Iteration 76

Response:  (D)
Iteration 77

Response:  (C)
Iteration 78

Response:  (E)
Iteration 79

Response:  (C)
Iteration 80

Response:  (C)
Iteration 81

Response:  (C)
Iteration 82

Response:  (B)
Iteration 83

Response:  (A)
Iteration 84

Response:  (D)
Iteration 85

Response:  (D)
Iteration 86

Response:  (C)
Iteration 87

Response:  (C)
Iteration 88

Response:  (E)
Iteration 89

Response:  (B)
Iteration 90

Response:  (B)
Iteration 91

Response:  (F)
Iteration 92

Response:  (E)
Iteration 93

Response:  (A)
Iteration 94

Response:  (E)
Iteration 95

Response:  (E)
Iteration 96

Response:  (C)
Iteration 97

Response:  (C)
Iteration 98

Response:  (C)
Iteration 99

Response:  (E)
Iteration 100

Response:  (C)
Iteration 101

Response:  (C)
Iteration 102

Response:  (C)
Iteration 103

Response:  (E)
Iteration 104

Response:  (E)
Iteration 105

Response:  (A)
Iteration 106

Response:  (C)
Iteration 107

Response:  (D)
Iteration 108

Response:  (E)
Iteration 109

Response:  (E)
Iteration 110

Response:  (A)
Iteration 111

Response:  (F)
Iteration 112

Response:  (E)
Iteration 113

Response:  (F)
Iteration 114

Response:  (F)
Iteration 115

Response:  (A)
Iteration 116

Response:  (F)
Iteration 117

Response:  (E)
Iteration 118

Response:  (E)
Iteration 119

Response:  (A)

In [ ]:
predictions[:10]

['(E)', '(E)', '(E)', '(E)', '(E)', '(E)', '(C)', '(D)', '(D)', '(D)']

In [ ]:
predictions = [x.strip("()").upper() for x in predictions]
predictions[:10]

['E', 'E', 'E', 'E', 'E', 'E', 'C', 'D', 'D', 'D']

In [ ]:
predictions = [x if x in ['A','B','C','D','E'] else "Ambiguous" for x in predictions]

In [ ]:
print(classification_report(true_answers,predictions,zero_division=0))

              precision    recall  f1-score   support

           A       0.45      0.23      0.30        22
   Ambiguous       0.00      0.00      0.00         0
           B       0.44      0.16      0.24        25
           C       0.50      0.65      0.57        23
           D       0.47      0.33      0.39        24
           E       0.23      0.53      0.32        17
           F       0.00      0.00      0.00         7
           G       0.00      0.00      0.00         1
           H       0.00      0.00      0.00         1

    accuracy                           0.34       120
   macro avg       0.23      0.21      0.20       120
weighted avg       0.40      0.34      0.34       120

## Task: Boolean Expressions

In [ ]:
dataset = load_json("/content/task_boolean_expressions.json")

In [ ]:
dataset

                                                 input target
0    From the following five expressions, only one ...    (E)
1    From the following five expressions, only one ...    (C)
2    From the following five expressions, only one ...    (E)
3    From the following five expressions, only one ...    (D)
4    From the following five expressions, only one ...    (C)
..                                                 ...    ...
195  From the following five expressions, only one ...    (A)
196  From the following five expressions, only one ...    (B)
197  From the following five expressions, only one ...    (B)
198  From the following five expressions, only one ...    (C)
199  From the following five expressions, only one ...    (A)

[200 rows x 2 columns]

In [ ]:
dataset["target"].value_counts()

target
(E)    43
(B)    41
(C)    40
(A)    39
(D)    37
Name: count, dtype: int64

In [ ]:
questions = dataset["input"].values.tolist()

In [ ]:
true_answers = dataset["target"].values.tolist()

In [ ]:
true_answers = [x.strip("()").upper() for x in true_answers]
true_answers[:10]

['E', 'C', 'E', 'D', 'C', 'D', 'C', 'D', 'A', 'A']

In [ ]:
questions[1]

'From the following five expressions, only one evaluates to true. Which one is it?\n\n(A) not (not not not ((not ((not not (not not not (not not not ((not not not (not not not ((not not not (not (not not not (9 * 9 + -3 * 6 is greater than -9 * -6) and not not (The capital of Azerbaijan is Ganja.)) or (The capital of the Nigeria is Lagos.)) and not not (-10 * -2 <= -1)) and (-1 - (8 / -10) > 1)) and not not (False)) and not not (10 - (-1 / -3) <= -3)) or (The capital of Canada is Toronto.)) and not not (-4 * -3 + -2 * 4 <= -4 * -5)) and not not (-3 * -5 + 2 * 3 is less than or equal to 4 * -9)) or not not not (False)) and (The capital of UAE is Abu Dhabi.)) or (6 * 8 + 4 * 4 is greater than -3 * -3)) and (The capital of the Nigeria is Lagos.)) and not not (4 * 2 <= 7)) and (-8 * 5 + -2 * -7 > -2 * -5)\n(B) not not not ((not (True) or (-6 * -1 + 8 * -2 > 7 * 5)) or (not (The capital of Nepal is Pokhara.) or (True))) and not not (not (not not not (2 * -10 + -2 * -4 > -1 * 1) and not not (max(2, -4, -5, -8) - min(2, -4, -5, -8) <= 7)) or ((True) or (-4 - (-9 / -4) > 8)))\n(C) not not (not (not not not (not not (not ((not (not not not (not not not (5 * -1 + 4 * 9 is greater than -1 * -6) and not not (3 * -6 is less than or equal to -9)) and not not (-9 * 8 + 9 * -9 > 5 * -1)) or (-3 * -10 + 3 * 4 is less than or equal to -7 * -1)) or (The capital of Denmark is Copenhagen.)) or (-7 * 1 + 10 * -6 is greater than -9 * 10)) or not not not (8 * 1 <= -2)) and not not (-2 * -1 <= -4)) or (9 * 4 <= -5)) or not not not (The capital of Azerbaijan is Baku.)\n(D) not not not (not not not (not not (((not (not (not (not not (not not (not ((not not not (not not (max(8, 1, -7, 9) - min(8, 1, -7, 9) <= 3) or not not not (9 - (-3 / -10) <= 3)) and not not (-5 * 7 + -6 * -8 is less than or equal to 1 * -5)) and (-1 * -6 <= -1)) or (max(-5, 10, -9, 3) - min(-5, 10, -9, 3) <= 9)) or not not not (5 - (2 / 2) is greater than 3)) or not not not (False)) and (max(-10, -8, -6, -8) - min(-10, -8, -6, -8) <= 6)) or (False)) or (7 * 4 > -8)) or (True)) or (max(-2, -4, -8, 6) - min(-2, -4, -8, 6) <= 4)) or not not not (-4 * -9 + -6 * -7 is less than or equal to 8 * -7)) and not not (The capital of Iraq is Beirut.)) and not not (False)\n(E) not (not not (not not not ((The capital of Norway is Oslo.) and (False)) and not not (not (False) and (10 - (-2 / 8) is greater than 9))) or not not not (not not (not not (5 * 7 <= 1) or not not not (False)) or not not not (not not not (False) and not not (-7 * -1 <= -5)))) and (not (not (not not not (True) and not not (max(9, -2, -10, -3) - min(9, -2, -10, -3) <= 5)) and (not (-1 * 6 is less than or equal to -1) and (True))) or (not (not not (9 * 6 > 7) or not not not (max(6, 10, -8, -7) - min(6, 10, -8, -7) is greater than 10)) and (not not not (False) and not not (-6 * -2 + -1 * 2 is greater than 5 * -1))))\n'

In [ ]:
instruction=f"""You are evaluating boolean expressions.

Exactly one option is True.

Output format rules:
- Output ONLY one of the following exact strings:
(A)
(B)
(C)
(D)
(E)

Do NOT use LaTeX.
Do NOT use special symbols.
Do NOT add explanations.
Do NOT add whitespace or extra characters.
"""

In [ ]:
prompts = get_prompt(instruction,questions)

In [ ]:
prompts[1]

'You are evaluating boolean expressions.\n\nExactly one option is True.\n\nOutput format rules:\n- Output ONLY one of the following exact strings:\n(A)\n(B)\n(C)\n(D)\n(E)\n\nDo NOT use LaTeX.\nDo NOT use special symbols.\nDo NOT add explanations.\nDo NOT add whitespace or extra characters.\n\n\nFrom the following five expressions, only one evaluates to true. Which one is it?\n\n(A) not (not not not ((not ((not not (not not not (not not not ((not not not (not not not ((not not not (not (not not not (9 * 9 + -3 * 6 is greater than -9 * -6) and not not (The capital of Azerbaijan is Ganja.)) or (The capital of the Nigeria is Lagos.)) and not not (-10 * -2 <= -1)) and (-1 - (8 / -10) > 1)) and not not (False)) and not not (10 - (-1 / -3) <= -3)) or (The capital of Canada is Toronto.)) and not not (-4 * -3 + -2 * 4 <= -4 * -5)) and not not (-3 * -5 + 2 * 3 is less than or equal to 4 * -9)) or not not not (False)) and (The capital of UAE is Abu Dhabi.)) or (6 * 8 + 4 * 4 is greater than -3 * -3)) and (The capital of the Nigeria is Lagos.)) and not not (4 * 2 <= 7)) and (-8 * 5 + -2 * -7 > -2 * -5)\n(B) not not not ((not (True) or (-6 * -1 + 8 * -2 > 7 * 5)) or (not (The capital of Nepal is Pokhara.) or (True))) and not not (not (not not not (2 * -10 + -2 * -4 > -1 * 1) and not not (max(2, -4, -5, -8) - min(2, -4, -5, -8) <= 7)) or ((True) or (-4 - (-9 / -4) > 8)))\n(C) not not (not (not not not (not not (not ((not (not not not (not not not (5 * -1 + 4 * 9 is greater than -1 * -6) and not not (3 * -6 is less than or equal to -9)) and not not (-9 * 8 + 9 * -9 > 5 * -1)) or (-3 * -10 + 3 * 4 is less than or equal to -7 * -1)) or (The capital of Denmark is Copenhagen.)) or (-7 * 1 + 10 * -6 is greater than -9 * 10)) or not not not (8 * 1 <= -2)) and not not (-2 * -1 <= -4)) or (9 * 4 <= -5)) or not not not (The capital of Azerbaijan is Baku.)\n(D) not not not (not not not (not not (((not (not (not (not not (not not (not ((not not not (not not (max(8, 1, -7, 9) - min(8, 1, -7, 9) <= 3) or not not not (9 - (-3 / -10) <= 3)) and not not (-5 * 7 + -6 * -8 is less than or equal to 1 * -5)) and (-1 * -6 <= -1)) or (max(-5, 10, -9, 3) - min(-5, 10, -9, 3) <= 9)) or not not not (5 - (2 / 2) is greater than 3)) or not not not (False)) and (max(-10, -8, -6, -8) - min(-10, -8, -6, -8) <= 6)) or (False)) or (7 * 4 > -8)) or (True)) or (max(-2, -4, -8, 6) - min(-2, -4, -8, 6) <= 4)) or not not not (-4 * -9 + -6 * -7 is less than or equal to 8 * -7)) and not not (The capital of Iraq is Beirut.)) and not not (False)\n(E) not (not not (not not not ((The capital of Norway is Oslo.) and (False)) and not not (not (False) and (10 - (-2 / 8) is greater than 9))) or not not not (not not (not not (5 * 7 <= 1) or not not not (False)) or not not not (not not not (False) and not not (-7 * -1 <= -5)))) and (not (not (not not not (True) and not not (max(9, -2, -10, -3) - min(9, -2, -10, -3) <= 5)) and (not (-1 * 6 is less than or equal to -1) and (True))) or (not (not not (9 * 6 > 7) or not not not (max(6, 10, -8, -7) - min(6, 10, -8, -7) is greater than 10)) and (not not not (False) and not not (-6 * -2 + -1 * 2 is greater than 5 * -1))))\n\n\nAnswer:'

In [ ]:
predictions = training(prompts,num_tokens=3)

Iteration 0

Response:  (B)
Iteration 1

Response:  (A)
Iteration 2

Response:  (C)
Iteration 3

Response:  (E)
Iteration 4

Response:  (C)
Iteration 5

Response:  (E)
Iteration 6

Response:  (A)
Iteration 7

Response:  (A)
Iteration 8

Response:  (A)
Iteration 9

Response:  (E)
Iteration 10

Response:  (D)
Iteration 11

Response:  (B)
Iteration 12

Response:  (A)
Iteration 13

Response:  (D)
Iteration 14

Response:  (A)
Iteration 15

Response:  (A)
Iteration 16

Response:  (E)
Iteration 17

Response:  (C)
Iteration 18

Response:  (A)
Iteration 19

Response:  (E)
Iteration 20

Response:  (B)
Iteration 21

Response:  (A)
Iteration 22

Response:  (C)
Iteration 23

Response:  (C)
Iteration 24

Response:  (D)
Iteration 25

Response:  (E)
Iteration 26

Response:  (C)
Iteration 27

Response:  (B)
Iteration 28

Response:  (E)
Iteration 29

Response:  (A)
Iteration 30

Response:  (C)
Iteration 31

Response:  (D)
Iteration 32

Response:  (E)
Iteration 33

Response:  (D)
Iteration 34

Response:  (C)
Iteration 35

Response:  (C)
Iteration 36

Response:  (A)
Iteration 37

Response:  (B)
Iteration 38

Response:  (B)
Iteration 39

Response:  (E)
Iteration 40

Response:  (E)
Iteration 41

Response:  (E)
Iteration 42

Response:  (C)
Iteration 43

Response:  (D)
Iteration 44

Response:  (C)
Iteration 45

Response:  (A)
Iteration 46

Response:  (E)
Iteration 47

Response:  (A)
Iteration 48

Response:  (B)
Iteration 49

Response:  (B)
Iteration 50

Response:  (C)
Iteration 51

Response:  (B)
Iteration 52

Response:  (E)
Iteration 53

Response:  (B)
Iteration 54

Response:  (A)
Iteration 55

Response:  (A)
Iteration 56

Response:  (B)
Iteration 57

Response:  (D)
Iteration 58

Response:  (E)
Iteration 59

Response:  (E)
Iteration 60

Response:  (D)
Iteration 61

Response:  (E)
Iteration 62

Response:  (C)
Iteration 63

Response:  (B)
Iteration 64

Response:  (E)
Iteration 65

Response:  (D)
Iteration 66

Response:  (E)
Iteration 67

Response:  (D)
Iteration 68

Response:  (E)
Iteration 69

Response:  (E)
Iteration 70

Response:  (A)
Iteration 71

Response:  (A)
Iteration 72

Response:  (C)
Iteration 73

Response:  (E)
Iteration 74

Response:  (E)
Iteration 75

Response:  (D)
Iteration 76

Response:  (A)
Iteration 77

Response:  (E)
Iteration 78

Response:  (C)
Iteration 79

Response:  (C)
Iteration 80

Response:  (E)
Iteration 81

Response:  (C)
Iteration 82

Response:  (C)
Iteration 83

Response:  (C)
Iteration 84

Response:  (C)
Iteration 85

Response:  (A)
Iteration 86

Response:  (E)
Iteration 87

Response:  (B)
Iteration 88

Response:  (E)
Iteration 89

Response:  (E)
Iteration 90

Response:  (E)
Iteration 91

Response:  (A)
Iteration 92

Response:  (B)
Iteration 93

Response:  (A)
Iteration 94

Response:  (A)
Iteration 95

Response:  (C)
Iteration 96

Response:  (C)
Iteration 97

Response:  (B)
Iteration 98

Response:  (D)
Iteration 99

Response:  (C)
Iteration 100

Response:  (C)
Iteration 101

Response:  (E)
Iteration 102

Response:  (B)
Iteration 103

Response:  (C)
Iteration 104

Response:  (C)
Iteration 105

Response:  (E)
Iteration 106

Response:  (B)
Iteration 107

Response:  (B)
Iteration 108

Response:  (E)
Iteration 109

Response:  (A)
Iteration 110

Response:  (E)
Iteration 111

Response:  (C)
Iteration 112

Response:  (E)
Iteration 113

Response:  (E)
Iteration 114

Response:  (A)
Iteration 115

Response:  (E)
Iteration 116

Response:  (A)
Iteration 117

Response:  (C)
Iteration 118

Response:  (C)
Iteration 119

Response:  (D)
Iteration 120

Response:  (A)
Iteration 121

Response:  (B)
Iteration 122

Response:  (E)
Iteration 123

Response:  (A)
Iteration 124

Response:  (E)
Iteration 125

Response:  (D)
Iteration 126

Response:  (C)
Iteration 127

Response:  (E)
Iteration 128

Response:  (E)
Iteration 129

Response:  (E)
Iteration 130

Response:  (B)
Iteration 131

Response:  (E)
Iteration 132

Response:  (E)
Iteration 133

Response:  (A)
Iteration 134

Response:  (C)
Iteration 135

Response:  (A)
Iteration 136

Response:  (C)
Iteration 137

Response:  (C)
Iteration 138

Response:  (A)
Iteration 139

Response:  (B)
Iteration 140

Response:  (E)
Iteration 141

Response:  (D)
Iteration 142

Response:  (C)
Iteration 143

Response:  (A)
Iteration 144

Response:  (E)
Iteration 145

Response:  (C)
Iteration 146

Response:  (E)
Iteration 147

Response:  (D)
Iteration 148

Response:  (D)
Iteration 149

Response:  (D)
Iteration 150

Response:  (B)
Iteration 151

Response:  (A)
Iteration 152

Response:  (D)
Iteration 153

Response:  (C)
Iteration 154

Response:  (C)
Iteration 155

Response:  (C)
Iteration 156

Response:  (A)
Iteration 157

Response:  (B)
Iteration 158

Response:  (A)
Iteration 159

Response:  (B)
Iteration 160

Response:  (E)
Iteration 161

Response:  (A)
Iteration 162

Response:  (C)
Iteration 163

Response:  (C)
Iteration 164

Response:  (E)
Iteration 165

Response:  (B)
Iteration 166

Response:  (E)
Iteration 167

Response:  (E)
Iteration 168

Response:  (E)
Iteration 169

Response:  (E)
Iteration 170

Response:  (E)
Iteration 171

Response:  (B)
Iteration 172

Response:  (E)
Iteration 173

Response:  (D)
Iteration 174

Response:  (E)
Iteration 175

Response:  (A)
Iteration 176

Response:  (A)
Iteration 177

Response:  (E)
Iteration 178

Response:  (E)
Iteration 179

Response:  (A)
Iteration 180

Response:  (B)
Iteration 181

Response:  (D)
Iteration 182

Response:  (C)
Iteration 183

Response:  (C)
Iteration 184

Response:  (C)
Iteration 185

Response:  (A)
Iteration 186

Response:  (B)
Iteration 187

Response:  (E)
Iteration 188

Response:  (A)
Iteration 189

Response:  (E)
Iteration 190

Response:  (C)
Iteration 191

Response:  (C)
Iteration 192

Response:  (B)
Iteration 193

Response:  (C)
Iteration 194

Response:  (E)
Iteration 195

Response:  (A)
Iteration 196

Response:  (A)
Iteration 197

Response:  (E)
Iteration 198

Response:  (A)
Iteration 199

Response:  (D)

In [ ]:
predictions[:10]

['(B)', '(A)', '(C)', '(E)', '(C)', '(E)', '(A)', '(A)', '(A)', '(E)']

In [ ]:
predictions = [x.strip("()").upper() for x in predictions]
predictions[:10]

['B', 'A', 'C', 'E', 'C', 'E', 'A', 'A', 'A', 'E']

In [ ]:
print(classification_report(true_answers,predictions,zero_division=0))

              precision    recall  f1-score   support

           A       0.19      0.21      0.20        39
           B       0.10      0.07      0.09        41
           C       0.15      0.17      0.16        40
           D       0.09      0.05      0.07        37
           E       0.18      0.26      0.21        43

    accuracy                           0.15       200
   macro avg       0.14      0.15      0.15       200
weighted avg       0.14      0.15      0.15       200

##