# Evaluation on Qwen/Qwen3-8B using BBEH benchmark for reasoning tasks

In [1]:
!pip install bitsandbytes

Collecting bitsandbytes
  Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.9.0+cu126)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.20.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)
Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl (59.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.1/59.1 MB 13.4 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.49.1

In [2]:
import json
import torch
import pandas as pd
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from sklearn.metrics import classification_report

In [3]:
from huggingface_hub import login
login()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [4]:
model_name = "Qwen/Qwen3-8B"

In [5]:
bitsandbytes_config = BitsAndBytesConfig(load_in_4bit=True,
                                         bnb_4bit_compute_dtype=torch.float16,
                                         bnb_4bit_quant_type='nf4',
                                         bnb_4bit_use_double_quant=True)

In [6]:
tokenizer = AutoTokenizer.from_pretrained(model_name)
model= AutoModelForCausalLM.from_pretrained(model_name,
                                             quantization_config=bitsandbytes_config,
                                             device_map="auto",
                                             offload_folder="offload")

config.json:   0%|          | 0.00/728 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/399 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

In [7]:
def load_json(path):
  with open(path,"r") as f:
    data = json.load(f)

    df = pd.DataFrame(data['examples'])
    return df

In [8]:
def get_prompt(instruction,questions):
  prompts=[]
  for i in range(len(questions)):
    question = questions[i].split("Reply")[0]
    prompt = f"{instruction}\n\n{question}\n\nAnswer: "
    prompts.append(prompt)
  return prompts

In [9]:
def training(prompts,num_tokens=1):
  predictions=[]
  for i in range(len(prompts)):
    input_tokens = tokenizer(prompts[i],return_tensors="pt").to("cuda:0")
    output_tokens = model.generate(**input_tokens,max_new_tokens=num_tokens,
                                   do_sample=False,
                                   pad_token_id=tokenizer.eos_token_id,
                                   eos_token_id=tokenizer.eos_token_id)

    response = tokenizer.decode(output_tokens[0], skip_special_tokens=True).strip()
    pred_answer = response.split("Answer:")[1]
    print(f"Iteration {i}\n")
    print(f"Response: {pred_answer}")
    predictions.append(pred_answer)

  return predictions

## Task Casual Understanding

In [ ]:
dataset = load_json("/content/task_casual_understanding.json")

In [ ]:
dataset

                                                 input target
0    Question: Lauren and Jane work for the same co...    Yes
1    Question: Lauren and Jane work for the same co...    Yes
2    Question: The receptionist in the philosophy d...    Yes
3    Question: The receptionist in the philosophy d...     No
4    Question: Claire's parents bought her an old c...    Yes
..                                                 ...    ...
195  Question: A test tube contains a mixture. Sam ...    Yes
196  Question: Reagent X and Y are both added to a ...     No
197  Question: There is a test tube on the left and...    Yes
198  Question: Sam is heating Reagent X in a test t...    Yes
199  Question: Sam throws a poisonous test tube tow...     No

[200 rows x 2 columns]

In [ ]:
questions = dataset['input'].values.tolist()

In [ ]:
true_answers = dataset['target'].values.tolist()

In [ ]:
instruction = f"""Instruction: You are an AI assistant for casual understanding. Read the story and answer with exactly one word:
Yes (if you think majority of people will answer yes), No (if you think majority of people will answer no), or Ambiguous(If you think that majority of people do not know the answer) . Do not add explanations.
"""

In [ ]:
prompts = get_prompt(instruction,questions)

In [ ]:
prompts[0]

"Instruction: You are an AI assistant for casual understanding. Read the story and answer with exactly one word: \nYes (if you think majority of people will answer yes), No (if you think majority of people will answer no), or Ambiguous(If you think that majority of people do not know the answer) . Do not add explanations.\n\n\nQuestion: Lauren and Jane work for the same company. They each need to use a computer for work sometimes. Unfortunately, the computer isn't very powerful. If two people are logged on at the same time, it usually crashes. So the company decided to institute an official policy. It declared that Lauren would be the only one permitted to use the computer in the mornings and that Jane would be the only one permitted to use the computer in the afternoons. As expected, Lauren logged on the computer the next day at 9:00 am. But Jane decided to disobey the official policy. She also logged on at 9:00 am. The computer crashed immediately. Did Jane cause the computer to crash?  \n\nAnswer: "

In [ ]:
predictions = training(prompts,num_tokens=1)

Iteration 0

Response:   Yes
Iteration 1

Response:   Yes
Iteration 2

Response:   Yes
Iteration 3

Response:   Yes
Iteration 4

Response:   Yes
Iteration 5

Response:   No
Iteration 6

Response:   Yes
Iteration 7

Response:   Amb
Iteration 8

Response:   Alright
Iteration 9

Response:   Amb
Iteration 10

Response:   No
Iteration 11

Response:   No
Iteration 12

Response:   No
Iteration 13

Response:   Amb
Iteration 14

Response:   Yes
Iteration 15

Response:   Alright
Iteration 16

Response:   Let
Iteration 17

Response:   Amb
Iteration 18

Response:   Yes
Iteration 19

Response:   Yes
Iteration 20

Response:   Yes
Iteration 21

Response:   Alright
Iteration 22

Response:   Yes
Iteration 23

Response:   The
Iteration 24

Response:   Yes
Iteration 25

Response:   The
Iteration 26

Response:   Amb
Iteration 27

Response:   Amb
Iteration 28

Response:   Yes
Iteration 29

Response:   Yes
Iteration 30

Response:   Yes
Iteration 31

Response:   Yes
Iteration 32

Response:   No
Iteration 33

Response:   Yes
Iteration 34

Response:   Yes
Iteration 35

Response:   Yes
Iteration 36

Response:   Alright
Iteration 37

Response:   Yes
Iteration 38

Response:   Yes
Iteration 39

Response:   Yes
Iteration 40

Response:   Alright
Iteration 41

Response:   Alright
Iteration 42

Response:   Yes
Iteration 43

Response:   Alright
Iteration 44

Response:   Yes
Iteration 45

Response:   Yes
Iteration 46

Response:   Amb
Iteration 47

Response:   Yes
Iteration 48

Response:   Amb
Iteration 49

Response:   Yes
Iteration 50

Response:   No
Iteration 51

Response:   No
Iteration 52

Response:   Amb
Iteration 53

Response:   Amb
Iteration 54

Response:   Yes
Iteration 55

Response:   Yes
Iteration 56

Response:   Amb
Iteration 57

Response:   Amb
Iteration 58

Response:   The
Iteration 59

Response:   The
Iteration 60

Response:   Yes
Iteration 61

Response:   Yes
Iteration 62

Response:   Amb
Iteration 63

Response:   Amb
Iteration 64

Response:   Yes
Iteration 65

Response:   Yes
Iteration 66

Response:   Yes
Iteration 67

Response:   Yes
Iteration 68

Response:   No
Iteration 69

Response:   No
Iteration 70

Response:   Alright
Iteration 71

Response:   Alright
Iteration 72

Response:   Amb
Iteration 73

Response:   Alright
Iteration 74

Response:   Yes
Iteration 75

Response:   Yes
Iteration 76

Response:   No
Iteration 77

Response:   No
Iteration 78

Response:   Amb
Iteration 79

Response:   Yes
Iteration 80

Response:   Amb
Iteration 81

Response:   Amb
Iteration 82

Response:   Yes
Iteration 83

Response:   Amb
Iteration 84

Response:   Amb
Iteration 85

Response:   Amb
Iteration 86

Response:   No
Iteration 87

Response:   Amb
Iteration 88

Response:   Amb
Iteration 89

Response:   Amb
Iteration 90

Response:   Yes
Iteration 91

Response:   Yes
Iteration 92

Response:   Yes
Iteration 93

Response:   No
Iteration 94

Response:   Yes
Iteration 95

Response:   Yes
Iteration 96

Response:   Amb
Iteration 97

Response:   Yes
Iteration 98

Response:   Yes
Iteration 99

Response:   Let
Iteration 100

Response:   Yes
Iteration 101

Response:   Alright
Iteration 102

Response:   Yes
Iteration 103

Response:   No
Iteration 104

Response:   Yes
Iteration 105

Response:   No
Iteration 106

Response:   Yes
Iteration 107

Response:   Yes
Iteration 108

Response:   Yes
Iteration 109

Response:   Yes
Iteration 110

Response:   Yes
Iteration 111

Response:   Yes
Iteration 112

Response:   Yes
Iteration 113

Response:   Yes
Iteration 114

Response:   Yes
Iteration 115

Response:   Yes
Iteration 116

Response:   Yes
Iteration 117

Response:   Yes
Iteration 118

Response:   Alright
Iteration 119

Response:   Yes
Iteration 120

Response:   Alright
Iteration 121

Response:   Alright
Iteration 122

Response:   No
Iteration 123

Response:   No
Iteration 124

Response:   Amb
Iteration 125

Response:   Amb
Iteration 126

Response:   Amb
Iteration 127

Response:   Yes
Iteration 128

Response:   The
Iteration 129

Response:   Alright
Iteration 130

Response:   Yes
Iteration 131

Response:   Alright
Iteration 132

Response:   Yes
Iteration 133

Response:   Yes
Iteration 134

Response:   Alright
Iteration 135

Response:   Alright
Iteration 136

Response:   No
Iteration 137

Response:   The
Iteration 138

Response:   Alright
Iteration 139

Response:   Alright
Iteration 140

Response:   Yes
Iteration 141

Response:   Amb
Iteration 142

Response:   No
Iteration 143

Response:   No
Iteration 144

Response:   Amb
Iteration 145

Response:   Amb
Iteration 146

Response:   No
Iteration 147

Response:   No
Iteration 148

Response:   No
Iteration 149

Response:   Yes
Iteration 150

Response:   Yes
Iteration 151

Response:   Amb
Iteration 152

Response:   Yes
Iteration 153

Response:   Yes
Iteration 154

Response:   Yes
Iteration 155

Response:   No
Iteration 156

Response:   No
Iteration 157

Response:   No
Iteration 158

Response:   Amb
Iteration 159

Response:   Amb
Iteration 160

Response:   Amb
Iteration 161

Response:   Yes
Iteration 162

Response:   Yes
Iteration 163

Response:   No
Iteration 164

Response:   Yes
Iteration 165

Response:   Yes
Iteration 166

Response:   Yes
Iteration 167

Response:   Yes
Iteration 168

Response:   Amb
Iteration 169

Response:   Yes
Iteration 170

Response:   No
Iteration 171

Response:   Amb
Iteration 172

Response:   The
Iteration 173

Response:   Amb
Iteration 174

Response:   Let
Iteration 175

Response:   Amb
Iteration 176

Response:   Let
Iteration 177

Response:   Amb
Iteration 178

Response:   No
Iteration 179

Response:   Amb
Iteration 180

Response:   Amb
Iteration 181

Response:   Amb
Iteration 182

Response:   Amb
Iteration 183

Response:   Yes
Iteration 184

Response:   Amb
Iteration 185

Response:   No
Iteration 186

Response:   The
Iteration 187

Response:   Amb
Iteration 188

Response:   Yes
Iteration 189

Response:   Amb
Iteration 190

Response:   Amb
Iteration 191

Response:   Amb
Iteration 192

Response:   No
Iteration 193

Response:   Yes
Iteration 194

Response:   Amb
Iteration 195

Response:   Let
Iteration 196

Response:   Amb
Iteration 197

Response:   Yes
Iteration 198

Response:   Amb
Iteration 199

Response:   No

In [ ]:
predictions[:10]

['  Yes',
 '  Yes',
 '  Yes',
 '  Yes',
 '  Yes',
 '  No',
 '  Yes',
 '  Amb',
 '  Alright',
 '  Amb']

In [ ]:
predictions = [elem.strip() for elem in predictions]
predictions[:10]

['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Amb', 'Alright', 'Amb']

In [ ]:
predictions = [elem if elem=="Yes" or elem=="No" else "Ambiguous" for elem in predictions]
predictions[:10]

['Yes',
 'Yes',
 'Yes',
 'Yes',
 'Yes',
 'No',
 'Yes',
 'Ambiguous',
 'Ambiguous',
 'Ambiguous']

In [ ]:
print(classification_report(true_answers,predictions,zero_division=0))

              precision    recall  f1-score   support

   Ambiguous       0.20      0.38      0.26        45
          No       0.59      0.24      0.34        80
         Yes       0.42      0.47      0.44        75

    accuracy                           0.35       200
   macro avg       0.41      0.36      0.35       200
weighted avg       0.44      0.35      0.36       200

## Task Movie Recommendation

In [ ]:
dataset = load_json("/content/task_movie_recommendation.json")

In [ ]:
dataset

                                                 input target
0    Which option has more similar movies in terms ...    (E)
1    Which option has more similar movies in terms ...    (C)
2    Which option has more similar movies in terms ...    (C)
3    Which option has more similar movies in terms ...    (A)
4    Which option has more similar movies in terms ...    (I)
..                                                 ...    ...
195  Which option has more similar movies in terms ...    (E)
196  Which option has more similar movies in terms ...    (E)
197  Which option has more similar movies in terms ...    (E)
198  Which option has more similar movies in terms ...    (A)
199  Which option has more similar movies in terms ...    (F)

[200 rows x 2 columns]

In [ ]:
dataset["target"].value_counts()

target
(A)    26
(G)    22
(H)    21
(E)    21
(J)    20
(D)    20
(C)    18
(F)    18
(B)    17
(I)    17
Name: count, dtype: int64

In [ ]:
questions = dataset['input'].values.tolist()

In [ ]:
true_answers = dataset['target'].values.tolist()

In [ ]:
true_answers = [x.strip("()").upper() for x in true_answers]
true_answers[:10]

['E', 'C', 'C', 'A', 'I', 'D', 'B', 'F', 'D', 'H']

In [ ]:
instruction=f"""Instruction: You are an AI assistant that determines which group of movies is most similar.
Answer only with the one of the letters (**A**, **B**, **C**, **D**, **E**, **F**, **G**, **H**, **I**, or **J**) of the group that is most similar and then stop immediately. Do not write anything else.
Final output format: A,B,C,D,E,F,G,H,I or J
"""

In [ ]:
prompts = get_prompt(instruction,questions)

In [ ]:
prompts[1]

'Instruction: You are an AI assistant that determines which group of movies is most similar. \nAnswer only with the one of the letters (**A**, **B**, **C**, **D**, **E**, **F**, **G**, **H**, **I**, or **J**) of the group that is most similar and then stop immediately. Do not write anything else.\nFinal output format: A,B,C,D,E,F,G,H,I or J\n\n\nWhich option has more similar movies in terms of whether a group of people will like them or not?\nOptions:\n(A) Street Fighter II The Animated Movie, The Sixth Sense, The Matrix, The Shawshank Redemption, Terminator 2 Judgment Day\n(B) The Boy Who Could Fly, The Sheltering Sky, Forrest Gump, Terminator 2 Judgment Day, The Matrix\n(C) Forrest Gump, The Shawshank Redemption, Terminator 2 Judgment Day, The Matrix, The Sixth Sense\n(D) The Boy Who Could Fly, The Sheltering Sky, Street Fighter II The Animated Movie, The Sixth Sense, Terminator 2 Judgment Day\n(E) The Matrix, The Boy Who Could Fly, Forrest Gump, The Shawshank Redemption, The Sixth Sense\n(F) The Boy Who Could Fly, The Matrix, Terminator 2 Judgment Day, The Sixth Sense, Forrest Gump\n(G) The Shawshank Redemption, Street Fighter II The Animated Movie, The Sheltering Sky, The Matrix, The Boy Who Could Fly\n(H) Street Fighter II The Animated Movie, The Matrix, The Sixth Sense, The Shawshank Redemption, The Sheltering Sky\n(I) The Sheltering Sky, Street Fighter II The Animated Movie, Forrest Gump, Terminator 2 Judgment Day, The Boy Who Could Fly\n(J) Street Fighter II The Animated Movie, The Sixth Sense, The Boy Who Could Fly, The Shawshank Redemption, Forrest Gump\n\n\nAnswer: '

In [ ]:
predictions = training(prompts,num_tokens=1)

Iteration 0

Response:   J
Iteration 1

Response:   C
Iteration 2

Response:   To
Iteration 3

Response:   To
Iteration 4

Response:   I
Iteration 5

Response:   D
Iteration 6

Response:   G
Iteration 7

Response:   F
Iteration 8

Response:   D
Iteration 9

Response:   G
Iteration 10

Response:   I
Iteration 11

Response:   G
Iteration 12

Response:   I
Iteration 13

Response:   I
Iteration 14

Response:   G
Iteration 15

Response:   The
Iteration 16

Response:   D
Iteration 17

Response:   E
Iteration 18

Response:   G
Iteration 19

Response:   I
Iteration 20

Response:   To
Iteration 21

Response:   G
Iteration 22

Response:   H
Iteration 23

Response:   H
Iteration 24

Response:   D
Iteration 25

Response:   I
Iteration 26

Response:   D
Iteration 27

Response:   H
Iteration 28

Response:   J
Iteration 29

Response:   J
Iteration 30

Response:   I
Iteration 31

Response:   G
Iteration 32

Response:   D
Iteration 33

Response:   F
Iteration 34

Response:   I
Iteration 35

Response:   I
Iteration 36

Response:   F
Iteration 37

Response:   H
Iteration 38

Response:   F
Iteration 39

Response:   J
Iteration 40

Response:   To
Iteration 41

Response:   I
Iteration 42

Response:   I
Iteration 43

Response:   I
Iteration 44

Response:   J
Iteration 45

Response:   I
Iteration 46

Response:   F
Iteration 47

Response:   G
Iteration 48

Response:   G
Iteration 49

Response:   I
Iteration 50

Response:   I
Iteration 51

Response:   G
Iteration 52

Response:   I
Iteration 53

Response:   I
Iteration 54

Response:   I
Iteration 55

Response:   H
Iteration 56

Response:   I
Iteration 57

Response:   I
Iteration 58

Response:   I
Iteration 59

Response:   F
Iteration 60

Response:   F
Iteration 61

Response:   G
Iteration 62

Response:   G
Iteration 63

Response:   G
Iteration 64

Response:   G
Iteration 65

Response:   H
Iteration 66

Response:   To
Iteration 67

Response:   I
Iteration 68

Response:   F
Iteration 69

Response:   D
Iteration 70

Response:   H
Iteration 71

Response:   I
Iteration 72

Response:   To
Iteration 73

Response:   J
Iteration 74

Response:   G
Iteration 75

Response:   I
Iteration 76

Response:   I
Iteration 77

Response:   H
Iteration 78

Response:   D
Iteration 79

Response:   F
Iteration 80

Response:   J
Iteration 81

Response:   H
Iteration 82

Response:   J
Iteration 83

Response:   I
Iteration 84

Response:   I
Iteration 85

Response:   F
Iteration 86

Response:   To
Iteration 87

Response:   F
Iteration 88

Response:   J
Iteration 89

Response:   I
Iteration 90

Response:   G
Iteration 91

Response:   To
Iteration 92

Response:   H
Iteration 93

Response:   To
Iteration 94

Response:   D
Iteration 95

Response:   I
Iteration 96

Response:   G
Iteration 97

Response:   G
Iteration 98

Response:   J
Iteration 99

Response:   Answer
Iteration 100

Response:   J
Iteration 101

Response:   D
Iteration 102

Response:   G
Iteration 103

Response:   G
Iteration 104

Response:   I
Iteration 105

Response:   F
Iteration 106

Response:   H
Iteration 107

Response:   I
Iteration 108

Response:   I
Iteration 109

Response:   H
Iteration 110

Response:   I
Iteration 111

Response:   I
Iteration 112

Response:   J
Iteration 113

Response:   D
Iteration 114

Response:   I
Iteration 115

Response:   H
Iteration 116

Response:   G
Iteration 117

Response:   G
Iteration 118

Response:   I
Iteration 119

Response:   J
Iteration 120

Response:   I
Iteration 121

Response:   D
Iteration 122

Response:   I
Iteration 123

Response:   Let
Iteration 124

Response:   J
Iteration 125

Response:   To
Iteration 126

Response:   I
Iteration 127

Response:   I
Iteration 128

Response:   G
Iteration 129

Response:   I
Iteration 130

Response:   To
Iteration 131

Response:   I
Iteration 132

Response:   H
Iteration 133

Response:   G
Iteration 134

Response:   To
Iteration 135

Response:   F
Iteration 136

Response:   I
Iteration 137

Response:   J
Iteration 138

Response:   I
Iteration 139

Response:   I
Iteration 140

Response:   I
Iteration 141

Response:   F
Iteration 142

Response:   G
Iteration 143

Response:   G
Iteration 144

Response:   H
Iteration 145

Response:   J
Iteration 146

Response:   J
Iteration 147

Response:   G
Iteration 148

Response:   I
Iteration 149

Response:   G
Iteration 150

Response:   J
Iteration 151

Response:   G
Iteration 152

Response:   I
Iteration 153

Response:   F
Iteration 154

Response:   I
Iteration 155

Response:   I
Iteration 156

Response:   G
Iteration 157

Response:   G
Iteration 158

Response:   J
Iteration 159

Response:   F
Iteration 160

Response:   H
Iteration 161

Response:   D
Iteration 162

Response:   I
Iteration 163

Response:   J
Iteration 164

Response:   J
Iteration 165

Response:   I
Iteration 166

Response:   I
Iteration 167

Response:   To
Iteration 168

Response:   To
Iteration 169

Response:   D
Iteration 170

Response:   I
Iteration 171

Response:   G
Iteration 172

Response:   I
Iteration 173

Response:   To
Iteration 174

Response:   I
Iteration 175

Response:   J
Iteration 176

Response:   G
Iteration 177

Response:   I
Iteration 178

Response:   F
Iteration 179

Response:   I
Iteration 180

Response:   D
Iteration 181

Response:   I
Iteration 182

Response:   I
Iteration 183

Response:   D
Iteration 184

Response:   H
Iteration 185

Response:   I
Iteration 186

Response:   F
Iteration 187

Response:   J
Iteration 188

Response:   H
Iteration 189

Response:   G
Iteration 190

Response:   G
Iteration 191

Response:   To
Iteration 192

Response:   G
Iteration 193

Response:   F
Iteration 194

Response:   F
Iteration 195

Response:   To
Iteration 196

Response:   D
Iteration 197

Response:   F
Iteration 198

Response:   H
Iteration 199

Response:   H

In [ ]:
predictions[:10]

['  J', '  C', '  To', '  To', '  I', '  D', '  G', '  F', '  D', '  G']

In [ ]:
predictions = [elem.strip() for elem in predictions]
predictions[:10]

['J', 'C', 'To', 'To', 'I', 'D', 'G', 'F', 'D', 'G']

In [ ]:
predictions = [elem if elem  in list("ABCDEFGHIJ") else "Unknown" for elem in predictions]
predictions[:10]

['J', 'C', 'Unknown', 'Unknown', 'I', 'D', 'G', 'F', 'D', 'G']

In [ ]:
print(classification_report(true_answers,predictions,zero_division=0))

              precision    recall  f1-score   support

           A       0.00      0.00      0.00        26
           B       0.00      0.00      0.00        17
           C       1.00      0.06      0.11        18
           D       0.47      0.40      0.43        20
           E       1.00      0.05      0.09        21
           F       0.38      0.44      0.41        18
           G       0.39      0.64      0.48        22
           H       0.40      0.38      0.39        21
           I       0.25      0.88      0.38        17
           J       0.39      0.45      0.42        20
     Unknown       0.00      0.00      0.00         0

    accuracy                           0.32       200
   macro avg       0.39      0.30      0.25       200
weighted avg       0.42      0.32      0.27       200

## Task Disambiguation QA

In [10]:
dataset = load_json("/content/task_disambiguationQA.json")

In [11]:
dataset['target'].value_counts()

target
(B)    25
(D)    24
(C)    23
(A)    22
(E)    17
(F)     7
(G)     1
(H)     1
Name: count, dtype: int64

In [12]:
questions = dataset['input'].values.tolist()

In [13]:
true_answers = dataset['target'].values.tolist()

In [14]:
true_answers = [x.strip("()").upper() for x in true_answers]
true_answers[:10]

['A', 'D', 'E', 'B', 'A', 'B', 'B', 'A', 'C', 'D']

In [15]:
instruction = f"""You are an AI assistant solving a pronoun disambiguation task.

For each sentence:
- Identify what the pronoun(s) most likely refer to based on common sense.
- If more than one interpretation is equally plausible, select “Ambiguous”.

Rules:
- Do not assume information that is not stated.
- Do not infer intent beyond what is commonly assumed.
- Choose exactly one answer from (A)–(H) based on available letters.

Final answer format:
(A), (B), (C), (D), (E), (H), (G), or (F)
"""

In [16]:
prompts = get_prompt(instruction,questions)

In [17]:
prompts[1]

'You are an AI assistant solving a pronoun disambiguation task.\n\nFor each sentence:\n- Identify what the pronoun(s) most likely refer to based on common sense.\n- If more than one interpretation is equally plausible, select “Ambiguous”.\n\nRules:\n- Do not assume information that is not stated.\n- Do not infer intent beyond what is commonly assumed.\n- Choose exactly one answer from (A)–(H) based on available letters.\n\nFinal answer format:\n(A), (B), (C), (D), (E), (H), (G), or (F)\n\n\nHere is a sentence with pronoun(s) whose antecedent(s) can either be derived from the context or is ambiguous.\nSentence: The designer called the janitor and asked him to clean the room as soon as possible, but he went to fetch a cup of coffee first and then returned to his desk.\nWhich of the following options correctly explains the antecedent(s) of the pronoun(s)?\n(A) Designer is cleaning the room as soon as possible and got coffee.\n(B) Janitor is cleaning the room as soon as possible and got coffee.\n(C) Designer is cleaning the room as soon as possible and janitor got coffee.\n(D) Janitor is cleaning the room as soon as possible and designer got coffee.\n(E) Ambiguous.\n\nAnswer: '

In [27]:
predictions = training(prompts,num_tokens=3)

Iteration 0

Response:   (E)
Iteration 1

Response:   (E)
Iteration 2

Response:   (E)
Iteration 3

Response:   (E)
Iteration 4

Response:   (D)
Iteration 5

Response:   (E)
Iteration 6

Response:   (C)
Iteration 7

Response:   (D)
Iteration 8

Response:   (B)
Iteration 9

Response:   (D)
Iteration 10

Response:   (C)
Iteration 11

Response:   (E)
Iteration 12

Response:   (C)
Iteration 13

Response:   (B)
Iteration 14

Response:   (C)
Iteration 15

Response:   (E)
Iteration 16

Response:   (D)
Iteration 17

Response:   (B)
Iteration 18

Response:   (E)
Iteration 19

Response:   (C)
Iteration 20

Response:   (B)
Iteration 21

Response:   (D)
Iteration 22

Response:   (D)
Iteration 23

Response:   (C)
Iteration 24

Response:   (C)
Iteration 25

Response:   (D)
Iteration 26

Response:   (E)
Iteration 27

Response:   Let's analyze
Iteration 28

Response:   Let's analyze
Iteration 29

Response:   Let's analyze
Iteration 30

Response:   (A),
Iteration 31

Response:   (C)
Iteration 32

Response:   Let's analyze
Iteration 33

Response:   (E)
Iteration 34

Response:   (E)
Iteration 35

Response:   Let's analyze
Iteration 36

Response:   (E)
Iteration 37

Response:   Let's analyze
Iteration 38

Response:   (F)
Iteration 39

Response:   (E)
Iteration 40

Response:   Let's analyze
Iteration 41

Response:   Let's analyze
Iteration 42

Response:   (B)
Iteration 43

Response:   (E)
Iteration 44

Response:   (C)
Iteration 45

Response:   Let's analyze
Iteration 46

Response:   Let's analyze
Iteration 47

Response:   Let's analyze
Iteration 48

Response:   Let's analyze
Iteration 49

Response:   (B)
Iteration 50

Response:   (F)
Iteration 51

Response:   (E)
Iteration 52

Response:   (F)
Iteration 53

Response:   (E)
Iteration 54

Response:   (D)
Iteration 55

Response:   (D)
Iteration 56

Response:   (C)
Iteration 57

Response:   Let's analyze
Iteration 58

Response:   (E)
Iteration 59

Response:   (D)
Iteration 60

Response:   Let's analyze
Iteration 61

Response:   (E)
Iteration 62

Response:   (E)
Iteration 63

Response:   (B)
Iteration 64

Response:   (B)
Iteration 65

Response:   Let's analyze
Iteration 66

Response:   (D)
Iteration 67

Response:   (C)
Iteration 68

Response:   (E)
Iteration 69

Response:   (D)
Iteration 70

Response:   (D)
Iteration 71

Response:   (A),
Iteration 72

Response:   (E)
Iteration 73

Response:   (C)
Iteration 74

Response:   (B)
Iteration 75

Response:   (C)
Iteration 76

Response:   (D)
Iteration 77

Response:   (B)
Iteration 78

Response:   (E)
Iteration 79

Response:   (B)
Iteration 80

Response:   (C)
Iteration 81

Response:   (E)
Iteration 82

Response:   (B)
Iteration 83

Response:   (A),
Iteration 84

Response:   (D)
Iteration 85

Response:   (D)
Iteration 86

Response:   (C)
Iteration 87

Response:   (C)
Iteration 88

Response:   (E)
Iteration 89

Response:   (B)
Iteration 90

Response:   (F)
Iteration 91

Response:   Let's analyze
Iteration 92

Response:   (E)
Iteration 93

Response:   (E)
Iteration 94

Response:   (E)
Iteration 95

Response:   (E)
Iteration 96

Response:   (C)
Iteration 97

Response:   (C)
Iteration 98

Response:   (C)
Iteration 99

Response:   (B)
Iteration 100

Response:   (D)
Iteration 101

Response:   (C)
Iteration 102

Response:   (E)
Iteration 103

Response:   (E)
Iteration 104

Response:   (E)
Iteration 105

Response:   (E)
Iteration 106

Response:   (D)
Iteration 107

Response:   (E)
Iteration 108

Response:   (E)
Iteration 109

Response:   Let's analyze
Iteration 110

Response:   (F)
Iteration 111

Response:   (F)
Iteration 112

Response:   (C)
Iteration 113

Response:   Let's analyze
Iteration 114

Response:   (F)
Iteration 115

Response:   (D)
Iteration 116

Response:   (E)
Iteration 117

Response:   (B)
Iteration 118

Response:   (E)
Iteration 119

Response:   (E)

In [28]:
predictions[:10]

['  (E)',
 '  (E)',
 '  (E)',
 '  (E)',
 '  (D)',
 '  (E)',
 '  (C)',
 '  (D)',
 '  (B)',
 '  (D)']

In [29]:
predictions = [x.strip() for x in predictions]
predictions[:10]

['(E)', '(E)', '(E)', '(E)', '(D)', '(E)', '(C)', '(D)', '(B)', '(D)']

In [30]:
predictions = [x.strip("()").upper() for x in predictions]
predictions

['E',
 'E',
 'E',
 'E',
 'D',
 'E',
 'C',
 'D',
 'B',
 'D',
 'C',
 'E',
 'C',
 'B',
 'C',
 'E',
 'D',
 'B',
 'E',
 'C',
 'B',
 'D',
 'D',
 'C',
 'C',
 'D',
 'E',
 "LET'S ANALYZE",
 "LET'S ANALYZE",
 "LET'S ANALYZE",
 'A),',
 'C',
 "LET'S ANALYZE",
 'E',
 'E',
 "LET'S ANALYZE",
 'E',
 "LET'S ANALYZE",
 'F',
 'E',
 "LET'S ANALYZE",
 "LET'S ANALYZE",
 'B',
 'E',
 'C',
 "LET'S ANALYZE",
 "LET'S ANALYZE",
 "LET'S ANALYZE",
 "LET'S ANALYZE",
 'B',
 'F',
 'E',
 'F',
 'E',
 'D',
 'D',
 'C',
 "LET'S ANALYZE",
 'E',
 'D',
 "LET'S ANALYZE",
 'E',
 'E',
 'B',
 'B',
 "LET'S ANALYZE",
 'D',
 'C',
 'E',
 'D',
 'D',
 'A),',
 'E',
 'C',
 'B',
 'C',
 'D',
 'B',
 'E',
 'B',
 'C',
 'E',
 'B',
 'A),',
 'D',
 'D',
 'C',
 'C',
 'E',
 'B',
 'F',
 "LET'S ANALYZE",
 'E',
 'E',
 'E',
 'E',
 'C',
 'C',
 'C',
 'B',
 'D',
 'C',
 'E',
 'E',
 'E',
 'E',
 'D',
 'E',
 'E',
 "LET'S ANALYZE",
 'F',
 'F',
 'C',
 "LET'S ANALYZE",
 'F',
 'D',
 'E',
 'B',
 'E',
 'E']

In [31]:
predictions_new = [x.strip("),") for x in predictions]
predictions_new

['E',
 'E',
 'E',
 'E',
 'D',
 'E',
 'C',
 'D',
 'B',
 'D',
 'C',
 'E',
 'C',
 'B',
 'C',
 'E',
 'D',
 'B',
 'E',
 'C',
 'B',
 'D',
 'D',
 'C',
 'C',
 'D',
 'E',
 "LET'S ANALYZE",
 "LET'S ANALYZE",
 "LET'S ANALYZE",
 'A',
 'C',
 "LET'S ANALYZE",
 'E',
 'E',
 "LET'S ANALYZE",
 'E',
 "LET'S ANALYZE",
 'F',
 'E',
 "LET'S ANALYZE",
 "LET'S ANALYZE",
 'B',
 'E',
 'C',
 "LET'S ANALYZE",
 "LET'S ANALYZE",
 "LET'S ANALYZE",
 "LET'S ANALYZE",
 'B',
 'F',
 'E',
 'F',
 'E',
 'D',
 'D',
 'C',
 "LET'S ANALYZE",
 'E',
 'D',
 "LET'S ANALYZE",
 'E',
 'E',
 'B',
 'B',
 "LET'S ANALYZE",
 'D',
 'C',
 'E',
 'D',
 'D',
 'A',
 'E',
 'C',
 'B',
 'C',
 'D',
 'B',
 'E',
 'B',
 'C',
 'E',
 'B',
 'A',
 'D',
 'D',
 'C',
 'C',
 'E',
 'B',
 'F',
 "LET'S ANALYZE",
 'E',
 'E',
 'E',
 'E',
 'C',
 'C',
 'C',
 'B',
 'D',
 'C',
 'E',
 'E',
 'E',
 'E',
 'D',
 'E',
 'E',
 "LET'S ANALYZE",
 'F',
 'F',
 'C',
 "LET'S ANALYZE",
 'F',
 'D',
 'E',
 'B',
 'E',
 'E']

In [32]:
predictions = [elem if elem  in list("ABCDEFGH") else "Unknown" for elem in predictions_new]
predictions

['E',
 'E',
 'E',
 'E',
 'D',
 'E',
 'C',
 'D',
 'B',
 'D',
 'C',
 'E',
 'C',
 'B',
 'C',
 'E',
 'D',
 'B',
 'E',
 'C',
 'B',
 'D',
 'D',
 'C',
 'C',
 'D',
 'E',
 'Unknown',
 'Unknown',
 'Unknown',
 'A',
 'C',
 'Unknown',
 'E',
 'E',
 'Unknown',
 'E',
 'Unknown',
 'F',
 'E',
 'Unknown',
 'Unknown',
 'B',
 'E',
 'C',
 'Unknown',
 'Unknown',
 'Unknown',
 'Unknown',
 'B',
 'F',
 'E',
 'F',
 'E',
 'D',
 'D',
 'C',
 'Unknown',
 'E',
 'D',
 'Unknown',
 'E',
 'E',
 'B',
 'B',
 'Unknown',
 'D',
 'C',
 'E',
 'D',
 'D',
 'A',
 'E',
 'C',
 'B',
 'C',
 'D',
 'B',
 'E',
 'B',
 'C',
 'E',
 'B',
 'A',
 'D',
 'D',
 'C',
 'C',
 'E',
 'B',
 'F',
 'Unknown',
 'E',
 'E',
 'E',
 'E',
 'C',
 'C',
 'C',
 'B',
 'D',
 'C',
 'E',
 'E',
 'E',
 'E',
 'D',
 'E',
 'E',
 'Unknown',
 'F',
 'F',
 'C',
 'Unknown',
 'F',
 'D',
 'E',
 'B',
 'E',
 'E']

In [33]:
print(classification_report(true_answers,predictions,zero_division=0))

              precision    recall  f1-score   support

           A       0.33      0.05      0.08        22
           B       0.40      0.24      0.30        25
           C       0.52      0.48      0.50        23
           D       0.53      0.42      0.47        24
           E       0.22      0.47      0.30        17
           F       0.43      0.43      0.43         7
           G       0.00      0.00      0.00         1
           H       0.00      0.00      0.00         1
     Unknown       0.00      0.00      0.00         0

    accuracy                           0.33       120
   macro avg       0.27      0.23      0.23       120
weighted avg       0.41      0.33      0.33       120

## Task: Boolean Expressions

In [34]:
dataset = load_json("/content/task_boolean_expressions.json")

In [35]:
dataset

                                                 input target
0    From the following five expressions, only one ...    (E)
1    From the following five expressions, only one ...    (C)
2    From the following five expressions, only one ...    (E)
3    From the following five expressions, only one ...    (D)
4    From the following five expressions, only one ...    (C)
..                                                 ...    ...
195  From the following five expressions, only one ...    (A)
196  From the following five expressions, only one ...    (B)
197  From the following five expressions, only one ...    (B)
198  From the following five expressions, only one ...    (C)
199  From the following five expressions, only one ...    (A)

[200 rows x 2 columns]

In [36]:
dataset["target"].value_counts()

target
(E)    43
(B)    41
(C)    40
(A)    39
(D)    37
Name: count, dtype: int64

In [37]:
questions = dataset["input"].values.tolist()

In [38]:
true_answers = dataset["target"].values.tolist()

In [39]:
true_answers = [x.strip("()").upper() for x in true_answers]
true_answers[:10]

['E', 'C', 'E', 'D', 'C', 'D', 'C', 'D', 'A', 'A']

In [40]:
instruction=f"""You are evaluating boolean expressions.

Exactly one option is True.

Output format rules:
- Output ONLY one of the following exact strings:
(A)
(B)
(C)
(D)
(E)

Do NOT use LaTeX.
Do NOT use special symbols.
Do NOT add explanations.
Do NOT add whitespace or extra characters.
"""

In [41]:
prompts = get_prompt(instruction,questions)

In [42]:
prompts[0]

'You are evaluating boolean expressions.\n\nExactly one option is True.\n\nOutput format rules:\n- Output ONLY one of the following exact strings:\n(A)\n(B)\n(C)\n(D)\n(E)\n\nDo NOT use LaTeX.\nDo NOT use special symbols.\nDo NOT add explanations.\nDo NOT add whitespace or extra characters.\n\n\nFrom the following five expressions, only one evaluates to true. Which one is it?\n\n(A) not (not (not (not (False) or (-5 - (1 / -5) is greater than -7)) or (not (False) or (-5 * -10 + -5 * -6 is greater than -4 * 6))) or (not (not (False) or (False)) or (not not not (-3 - (-2 / 4) is greater than -6) and not not (The capital of India is Mumbai.)))) and (not (not (not (The capital of the Nigeria is Abuja.) or (-7 - (-4 / 7) > 4)) or (not (-6 - (-7 / -5) > -6) and (True))) and (not not ((-1 * 9 is less than or equal to -6) or (-4 * 10 + -1 * -7 <= 9 * 10)) or not not not (not not (6 * -2 is less than or equal to 4) or not not not (-5 * 9 + 6 * -3 <= -9 * 6))))\n(B) ((not (not not not (not (not (not not not (not not (not (not (max(-3, 8, 5, -2) - min(-3, 8, 5, -2) <= 4) and (False)) or (max(-6, 8, 5, -1) - min(-6, 8, 5, -1) <= 9)) or not not not (-6 - (9 / -1) is less than or equal to 6)) and not not (The capital of Afghanistan is Kabul.)) or (1 - (5 / -2) > 4)) or (True)) and not not (-3 * -8 <= 1)) and (9 * -1 + -6 * 7 > 10 * 10)) or (The capital of Denmark is Aarhus.)) and (9 * 8 + 7 * 10 is less than or equal to 5 * 10)\n(C) not ((not not (not not (not (not not (not (not not not (5 - (6 / 2) > 5) and not not (True)) or (3 * -7 + 3 * -2 <= -6 * 2)) or not not not (False)) and (-9 - (-2 / 3) > 6)) or not not not (max(8, -1, -7, -6) - min(8, -1, -7, -6) is greater than 1)) or not not not (max(9, -4, -3, -4) - min(9, -4, -3, -4) is greater than 3)) and (The capital of Turkey is Istanbul.)) and (2 * 3 + 10 * -9 > -7 * -8)\n(D) not (not (not (not (The capital of Jordan is Amman.) or (max(7, 3, -2, 10) - min(7, 3, -2, 10) is greater than 7)) or (not not not (The capital of Colombia is Bogota.) and not not (The capital of Afghanistan is Kandahar.))) and (not (not not (-4 - (2 / -1) <= -6) or not not not (max(8, -6, -6, 9) - min(8, -6, -6, 9) is greater than 1)) or (not (The capital of Iraq is Beirut.) or (-6 * 1 > -6)))) and (not not not (not not not (not (The capital of Norway is Bergen.) and (The capital of Norway is Bergen.)) and not not (not not not (True) and not not (The capital of Denmark is Copenhagen.))) and not not (not (not (True) or (The capital of Canada is Ottawa.)) and ((False) or (max(9, 3, -7, 9) - min(9, 3, -7, 9) is greater than 6))))\n(E) not ((not (not (not not (not not ((not (not (not ((False) or (1 * 6 + 6 * 1 <= -10 * -4)) and (-6 * 7 > 5)) or (-3 * -3 + 3 * -2 <= -5 * -7)) or (The capital of Colombia is Medellin.)) or (-3 * 6 > 6)) or not not not (max(-10, 9, -2, -7) - min(-10, 9, -2, -7) is greater than 3)) or not not not (-3 * -2 + -4 * -5 is greater than 1 * 5)) or (7 * -3 > -9)) or (max(2, -4, 3, -3) - min(2, -4, 3, -3) > 8)) and (False)) and (8 * -2 is less than or equal to -8)\n\n\nAnswer: '

In [43]:
predictions = training(prompts,num_tokens=3)

Iteration 0

Response:   (D)
Iteration 1

Response:   (E)
Iteration 2

Response:   (E)
Iteration 3

Response:   (E)
Iteration 4

Response:   Let's break
Iteration 5

Response:   (D)
Iteration 6

Response:   (D)
Iteration 7

Response:   (D)
Iteration 8

Response:   Let's break
Iteration 9

Response:   (D)
Iteration 10

Response:   Let's break
Iteration 11

Response:   (D)
Iteration 12

Response:   (E)
Iteration 13

Response:   (D)
Iteration 14

Response:   (D)
Iteration 15

Response:   (E)
Iteration 16

Response:   (E)
Iteration 17

Response:   (D)
Iteration 18

Response:   (D)
Iteration 19

Response:   (E)
Iteration 20

Response:   (E)
Iteration 21

Response:   (E)
Iteration 22

Response:   (E)
Iteration 23

Response:   (D)
Iteration 24

Response:   (D)
Iteration 25

Response:   Let's break
Iteration 26

Response:   (D)
Iteration 27

Response:   (D)
Iteration 28

Response:   (D)
Iteration 29

Response:   (D)
Iteration 30

Response:   (D)
Iteration 31

Response:   (E)
Iteration 32

Response:   (D)
Iteration 33

Response:   (E)
Iteration 34

Response:   (D)
Iteration 35

Response:   (D)
Iteration 36

Response:   (E)
Iteration 37

Response:   (D)
Iteration 38

Response:   (D)
Iteration 39

Response:   (D)
Iteration 40

Response:   (D)
Iteration 41

Response:   (D)
Iteration 42

Response:   (D)
Iteration 43

Response:   (D)
Iteration 44

Response:   (D)
Iteration 45

Response:   (D)
Iteration 46

Response:   (D)
Iteration 47

Response:   (E)
Iteration 48

Response:   (D)
Iteration 49

Response:   Let's break
Iteration 50

Response:   (E)
Iteration 51

Response:   (D)
Iteration 52

Response:   (D)
Iteration 53

Response:   (D)
Iteration 54

Response:   (D)
Iteration 55

Response:   (D)
Iteration 56

Response:   (D)
Iteration 57

Response:   (A)
Iteration 58

Response:   (E)
Iteration 59

Response:   (D)
Iteration 60

Response:   (D)
Iteration 61

Response:   (D)
Iteration 62

Response:   (E)
Iteration 63

Response:   (D)
Iteration 64

Response:   (D)
Iteration 65

Response:   (D)
Iteration 66

Response:   (D)
Iteration 67

Response:   (D)
Iteration 68

Response:   (D)
Iteration 69

Response:   (D)
Iteration 70

Response:   (D)
Iteration 71

Response:   (A)
Iteration 72

Response:   (E)
Iteration 73

Response:   (D)
Iteration 74

Response:   (D)
Iteration 75

Response:   (E)
Iteration 76

Response:   (D)
Iteration 77

Response:   (D)
Iteration 78

Response:   (D)
Iteration 79

Response:   (D)
Iteration 80

Response:   (D)
Iteration 81

Response:   (E)
Iteration 82

Response:   (E)
Iteration 83

Response:   (E)
Iteration 84

Response:   (E)
Iteration 85

Response:   (D)
Iteration 86

Response:   (D)
Iteration 87

Response:   (E)
Iteration 88

Response:   (D)
Iteration 89

Response:   (D)
Iteration 90

Response:   (D)
Iteration 91

Response:   (D)
Iteration 92

Response:   (D)
Iteration 93

Response:   (D)
Iteration 94

Response:   (D)
Iteration 95

Response:   (D)
Iteration 96

Response:   (E)
Iteration 97

Response:   (E)
Iteration 98

Response:   (D)
Iteration 99

Response:   (A)
Iteration 100

Response:   (D)
Iteration 101

Response:   (D)
Iteration 102

Response:   (D)
Iteration 103

Response:   (D)
Iteration 104

Response:   Let's break
Iteration 105

Response:   (E)
Iteration 106

Response:   (D)
Iteration 107

Response:   (D)
Iteration 108

Response:   (D)
Iteration 109

Response:   (E)
Iteration 110

Response:   (D)
Iteration 111

Response:   (D)
Iteration 112

Response:   (D)
Iteration 113

Response:   (E)
Iteration 114

Response:   (D)
Iteration 115

Response:   (D)
Iteration 116

Response:   (A)
Iteration 117

Response:   (D)
Iteration 118

Response:   (E)
Iteration 119

Response:   (D)
Iteration 120

Response:   (D)
Iteration 121

Response:   (E)
Iteration 122

Response:   (D)
Iteration 123

Response:   (E)
Iteration 124

Response:   (E)
Iteration 125

Response:   (D)
Iteration 126

Response:   (D)
Iteration 127

Response:   (D)
Iteration 128

Response:   (E)
Iteration 129

Response:   (D)
Iteration 130

Response:   (E)
Iteration 131

Response:   (E)
Iteration 132

Response:   (D)
Iteration 133

Response:   (D)
Iteration 134

Response:   (D)
Iteration 135

Response:   (D)
Iteration 136

Response:   (D)
Iteration 137

Response:   (D)
Iteration 138

Response:   (D)
Iteration 139

Response:   (D)
Iteration 140

Response:   (E)
Iteration 141

Response:   (D)
Iteration 142

Response:   (D)
Iteration 143

Response:   (E)
Iteration 144

Response:   (D)
Iteration 145

Response:   (D)
Iteration 146

Response:   (D)
Iteration 147

Response:   (D)
Iteration 148

Response:   (D)
Iteration 149

Response:   (D)
Iteration 150

Response:   (D)
Iteration 151

Response:   (D)
Iteration 152

Response:   (E)
Iteration 153

Response:   (E)
Iteration 154

Response:   (D)
Iteration 155

Response:   (D)
Iteration 156

Response:   (D)
Iteration 157

Response:   Let's break
Iteration 158

Response:   (D)
Iteration 159

Response:   (D)
Iteration 160

Response:   (D)
Iteration 161

Response:   (D)
Iteration 162

Response:   (E)
Iteration 163

Response:   (E)
Iteration 164

Response:   (D)
Iteration 165

Response:   (D)
Iteration 166

Response:   (D)
Iteration 167

Response:   (D)
Iteration 168

Response:   (E)
Iteration 169

Response:   (D)
Iteration 170

Response:   (E)
Iteration 171

Response:   (E)
Iteration 172

Response:   (D)
Iteration 173

Response:   (E)
Iteration 174

Response:   (E)
Iteration 175

Response:   (D)
Iteration 176

Response:   (D)
Iteration 177

Response:   (D)
Iteration 178

Response:   (E)
Iteration 179

Response:   (D)
Iteration 180

Response:   (E)
Iteration 181

Response:   (D)
Iteration 182

Response:   (E)
Iteration 183

Response:   Let's break
Iteration 184

Response:   (D)
Iteration 185

Response:   (D)
Iteration 186

Response:   (D)
Iteration 187

Response:   Let's break
Iteration 188

Response:   (E)
Iteration 189

Response:   (E)
Iteration 190

Response:   (E)
Iteration 191

Response:   (D)
Iteration 192

Response:   (D)
Iteration 193

Response:   (E)
Iteration 194

Response:   (D)
Iteration 195

Response:   (D)
Iteration 196

Response:   (D)
Iteration 197

Response:   Let's break
Iteration 198

Response:   (D)
Iteration 199

Response:   (E)

In [44]:
predictions[:10]

['  (D)',
 '  (E)',
 '  (E)',
 '  (E)',
 "  Let's break",
 '  (D)',
 '  (D)',
 '  (D)',
 "  Let's break",
 '  (D)']

In [45]:
predictions = [x.strip() for x in predictions]
predictions[:10]

['(D)',
 '(E)',
 '(E)',
 '(E)',
 "Let's break",
 '(D)',
 '(D)',
 '(D)',
 "Let's break",
 '(D)']

In [46]:
predictions = [x.strip("()").upper() for x in predictions]
predictions

['D',
 'E',
 'E',
 'E',
 "LET'S BREAK",
 'D',
 'D',
 'D',
 "LET'S BREAK",
 'D',
 "LET'S BREAK",
 'D',
 'E',
 'D',
 'D',
 'E',
 'E',
 'D',
 'D',
 'E',
 'E',
 'E',
 'E',
 'D',
 'D',
 "LET'S BREAK",
 'D',
 'D',
 'D',
 'D',
 'D',
 'E',
 'D',
 'E',
 'D',
 'D',
 'E',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'E',
 'D',
 "LET'S BREAK",
 'E',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'A',
 'E',
 'D',
 'D',
 'D',
 'E',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'A',
 'E',
 'D',
 'D',
 'E',
 'D',
 'D',
 'D',
 'D',
 'D',
 'E',
 'E',
 'E',
 'E',
 'D',
 'D',
 'E',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'E',
 'E',
 'D',
 'A',
 'D',
 'D',
 'D',
 'D',
 "LET'S BREAK",
 'E',
 'D',
 'D',
 'D',
 'E',
 'D',
 'D',
 'D',
 'E',
 'D',
 'D',
 'A',
 'D',
 'E',
 'D',
 'D',
 'E',
 'D',
 'E',
 'E',
 'D',
 'D',
 'D',
 'E',
 'D',
 'E',
 'E',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'E',
 'D',
 'D',
 'E',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'E',
 'E',
 'D',
 'D',
 'D',
 "LET'S BREAK",
 'D',
 'D',
 'D',
 'D',
 'E',
 'E',
 'D',
 'D',
 'D',
 'D',
 'E',
 'D',
 'E',
 'E',
 'D',
 'E',
 'E',
 'D',
 'D',
 'D',
 'E',
 'D',
 'E',
 'D',
 'E',
 "LET'S BREAK",
 'D',
 'D',
 'D',
 "LET'S BREAK",
 'E',
 'E',
 'E',
 'D',
 'D',
 'E',
 'D',
 'D',
 'D',
 "LET'S BREAK",
 'D',
 'E']

In [47]:
predictions = [elem if elem  in list("ABCDE") else "Unknown" for elem in predictions]
predictions

['D',
 'E',
 'E',
 'E',
 'Unknown',
 'D',
 'D',
 'D',
 'Unknown',
 'D',
 'Unknown',
 'D',
 'E',
 'D',
 'D',
 'E',
 'E',
 'D',
 'D',
 'E',
 'E',
 'E',
 'E',
 'D',
 'D',
 'Unknown',
 'D',
 'D',
 'D',
 'D',
 'D',
 'E',
 'D',
 'E',
 'D',
 'D',
 'E',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'E',
 'D',
 'Unknown',
 'E',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'A',
 'E',
 'D',
 'D',
 'D',
 'E',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'A',
 'E',
 'D',
 'D',
 'E',
 'D',
 'D',
 'D',
 'D',
 'D',
 'E',
 'E',
 'E',
 'E',
 'D',
 'D',
 'E',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'E',
 'E',
 'D',
 'A',
 'D',
 'D',
 'D',
 'D',
 'Unknown',
 'E',
 'D',
 'D',
 'D',
 'E',
 'D',
 'D',
 'D',
 'E',
 'D',
 'D',
 'A',
 'D',
 'E',
 'D',
 'D',
 'E',
 'D',
 'E',
 'E',
 'D',
 'D',
 'D',
 'E',
 'D',
 'E',
 'E',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'E',
 'D',
 'D',
 'E',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'D',
 'E',
 'E',
 'D',
 'D',
 'D',
 'Unknown',
 'D',
 'D',
 'D',
 'D',
 'E',
 'E',
 'D',
 'D',
 'D',
 'D',
 'E',
 'D',
 'E',
 'E',
 'D',
 'E',
 'E',
 'D',
 'D',
 'D',
 'E',
 'D',
 'E',
 'D',
 'E',
 'Unknown',
 'D',
 'D',
 'D',
 'Unknown',
 'E',
 'E',
 'E',
 'D',
 'D',
 'E',
 'D',
 'D',
 'D',
 'Unknown',
 'D',
 'E']

In [48]:
print(classification_report(true_answers,predictions,zero_division=0))

              precision    recall  f1-score   support

           A       0.00      0.00      0.00        39
           B       0.00      0.00      0.00        41
           C       0.00      0.00      0.00        40
           D       0.20      0.70      0.31        37
           E       0.20      0.26      0.22        43
     Unknown       0.00      0.00      0.00         0

    accuracy                           0.18       200
   macro avg       0.07      0.16      0.09       200
weighted avg       0.08      0.18      0.11       200