# Evaluation on Vezilka LLM using BBEH benchmark for reasoning tasks

In [1]:
!pip install bitsandbytes

Collecting bitsandbytes
  Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.9.0+cu128)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.20.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.13.1.3)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)
Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl (59.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.1/59.1 MB 14.0 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.49.1

In [2]:
import json
import torch
import pandas as pd
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from sklearn.metrics import classification_report

In [3]:
from huggingface_hub import login
login()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [4]:
model_name = "finki-ukim/VezilkaLLM"

In [5]:
bitsandbytes_config = BitsAndBytesConfig(load_in_4bit=True,
                                         bnb_4bit_compute_dtype=torch.float16,
                                         bnb_4bit_quant_type='nf4',
                                         bnb_4bit_use_double_quant=True)

In [6]:
tokenizer = AutoTokenizer.from_pretrained(model_name)
model= AutoModelForCausalLM.from_pretrained(model_name,
                                             quantization_config=bitsandbytes_config,
                                             device_map="auto",
                                             offload_folder="offload")

config.json:   0%|          | 0.00/934 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/33.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

The following generation flags are not valid and may be ignored: ['cache_implementation']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Loading weights:   0%|          | 0/444 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/195 [00:00<?, ?B/s]

In [7]:
def load_json(path):
  with open(path,"r") as f:
    data = json.load(f)

    df = pd.DataFrame(data['examples'])
    return df

In [8]:
def get_prompt(instruction,questions):
  prompts=[]
  for i in range(len(questions)):
    question = questions[i].split("Reply")[0]
    prompt = f"{instruction}\n\n{question}\n\nAnswer: "
    prompts.append(prompt)
  return prompts

In [9]:
def training(prompts,num_tokens=1):
  predictions=[]
  for i in range(len(prompts)):
    input_tokens = tokenizer(prompts[i],return_tensors="pt").to("cuda:0")
    output_tokens = model.generate(**input_tokens,max_new_tokens=num_tokens,
                                   do_sample=False,
                                   pad_token_id=tokenizer.eos_token_id,
                                   eos_token_id=tokenizer.eos_token_id)

    response = tokenizer.decode(output_tokens[0], skip_special_tokens=True).strip()
    pred_answer = response.split("Answer:")[1]
    print(f"Iteration {i}\n")
    print(f"Response: {pred_answer}")
    predictions.append(pred_answer)

  return predictions

## Task Casual Understanding

In [10]:
dataset = load_json("/content/task_casual_understanding.json")

In [11]:
dataset

                                                 input target
0    Question: Lauren and Jane work for the same co...    Yes
1    Question: Lauren and Jane work for the same co...    Yes
2    Question: The receptionist in the philosophy d...    Yes
3    Question: The receptionist in the philosophy d...     No
4    Question: Claire's parents bought her an old c...    Yes
..                                                 ...    ...
195  Question: A test tube contains a mixture. Sam ...    Yes
196  Question: Reagent X and Y are both added to a ...     No
197  Question: There is a test tube on the left and...    Yes
198  Question: Sam is heating Reagent X in a test t...    Yes
199  Question: Sam throws a poisonous test tube tow...     No

[200 rows x 2 columns]

In [12]:
questions = dataset['input'].values.tolist()

In [13]:
true_answers = dataset['target'].values.tolist()

In [14]:
instruction = f"""Instruction: You are an AI assistant for casual understanding. Read the story and answer with exactly one word:
Yes (if you think majority of people will answer yes), No (if you think majority of people will answer no), or Ambiguous(If you think that majority of people do not know the answer) . Do not add explanations.
"""

In [15]:
prompts = get_prompt(instruction,questions)

In [16]:
prompts[0]

"Instruction: You are an AI assistant for casual understanding. Read the story and answer with exactly one word:\nYes (if you think majority of people will answer yes), No (if you think majority of people will answer no), or Ambiguous(If you think that majority of people do not know the answer) . Do not add explanations.\n\n\nQuestion: Lauren and Jane work for the same company. They each need to use a computer for work sometimes. Unfortunately, the computer isn't very powerful. If two people are logged on at the same time, it usually crashes. So the company decided to institute an official policy. It declared that Lauren would be the only one permitted to use the computer in the mornings and that Jane would be the only one permitted to use the computer in the afternoons. As expected, Lauren logged on the computer the next day at 9:00 am. But Jane decided to disobey the official policy. She also logged on at 9:00 am. The computer crashed immediately. Did Jane cause the computer to crash?  \n\nAnswer: "

In [19]:
predictions = training(prompts,num_tokens=5)

Iteration 0

Response:
No
Explanation:
Iteration 1

Response:
No
Explanation:
Iteration 2

Response:
No
Explanation:
Iteration 3

Response:
No
Explanation:
Iteration 4

Response:
No
Explanation:
Iteration 5

Response:
No
Explanation:
Iteration 6

Response:
No
Explanation:
Iteration 7

Response:
No
Explanation:
Iteration 8

Response:
No
Explanation:
Iteration 9

Response:
No
Explanation:
Iteration 10

Response:
No
Explanation:
Iteration 11

Response:
No
Explanation:
Iteration 12

Response:
No
Explanation:
Iteration 13

Response:
No
Explanation:
Iteration 14

Response:
No
Explanation:
Iteration 15

Response:
Ambiguous
Explanation
Iteration 16

Response:
Ambiguous
Explanation
Iteration 17

Response:
No
Explanation:
Iteration 18

Response:
No
Explanation:
Iteration 19

Response:
No
Explanation:
Iteration 20

Response:
No
Explanation:
Iteration 21

Response:
No
Explanation:
Iteration 22

Response:
No
Explanation:
Iteration 23

Response:
No
Explanation:
Iteration 24

Response:
No
Explanation:
Iteration 25

Response:
No
Explanation:
Iteration 26

Response:
No
Explanation:
Iteration 27

Response:
No
Explanation:
Iteration 28

Response:
No
Explanation:
Iteration 29

Response:
No
Explanation:
Iteration 30

Response:
No
Explanation:
Iteration 31

Response:
No
Explanation:
Iteration 32

Response:
No
Explanation:
Iteration 33

Response:
No
Explanation:
Iteration 34

Response:
No
Explanation:
Iteration 35

Response:
No
Explanation:
Iteration 36

Response:
No
Explanation:
Iteration 37

Response:
No
Explanation:
Iteration 38

Response:
No
Explanation:
Iteration 39

Response:
No
Explanation:
Iteration 40

Response:
No
Explanation:
Iteration 41

Response:
No
Explanation:
Iteration 42

Response:
No
Explanation:
Iteration 43

Response:
No
Explanation:
Iteration 44

Response:
No
Explanation:
Iteration 45

Response:
No
Explanation:
Iteration 46

Response:
No
Explanation:
Iteration 47

Response:
No
Explanation:
Iteration 48

Response:
No
Explanation:
Iteration 49

Response:
No
Explanation:
Iteration 50

Response:
No
Explanation:
Iteration 51

Response:
No
Explanation:
Iteration 52

Response:
No
Explanation:
Iteration 53

Response:
No
Explanation:
Iteration 54

Response:
No
Explanation:
Iteration 55

Response:
No
Explanation:
Iteration 56

Response:
No
Explanation:
Iteration 57

Response:
No
Explanation:
Iteration 58

Response:
No
Explanation:
Iteration 59

Response:
No
Explanation:
Iteration 60

Response:
No
Explanation:
Iteration 61

Response:
No
Explanation:
Iteration 62

Response:
No
Explanation:
Iteration 63

Response:
No
Explanation:
Iteration 64

Response:
No
Explanation:
Iteration 65

Response:
No
Explanation:
Iteration 66

Response:
Bill did not cause
Iteration 67

Response:
No
Explanation:
Iteration 68

Response:
No
Explanation:
Iteration 69

Response:
No
Explanation:
Iteration 70

Response:
No
Explanation:
Iteration 71

Response:
No
Explanation:
Iteration 72

Response:
No
Explanation:
Iteration 73

Response:
No
Explanation:
Iteration 74

Response:
No
Explanation:
Iteration 75

Response:
No
Explanation:
Iteration 76

Response:
No
Explanation:
Iteration 77

Response:
No
Explanation:
Iteration 78

Response:
No
Explanation:
Iteration 79

Response:
No
Explanation:
Iteration 80

Response:
No
Explanation:
Iteration 81

Response:
No
Explanation:
Iteration 82

Response:
No
Explanation:
Iteration 83

Response:
No
Explanation:
Iteration 84

Response:
No
Explanation:
Iteration 85

Response:
No
Explanation:
Iteration 86

Response:
No
Explanation:
Iteration 87

Response:
No
Explanation:
Iteration 88

Response:
No
Explanation:
Iteration 89

Response:
No
Explanation:
Iteration 90

Response:
No
Explanation:
Iteration 91

Response:
No
Explanation:
Iteration 92

Response:
No
Explanation:
Iteration 93

Response:
No
Explanation:
Iteration 94

Response:
No
Explanation:
Iteration 95

Response:
No
Explanation:
Iteration 96

Response:
No
Explanation:
Iteration 97

Response:
No
Explanation:
Iteration 98

Response:
No
Explanation:
Iteration 99

Response:
No
Explanation:
Iteration 100

Response:
No
Explanation:
Iteration 101

Response:
No
Explanation:
Iteration 102

Response:
No
Explanation:
Iteration 103

Response:
No
Explanation:
Iteration 104

Response:
No
Explanation:
Iteration 105

Response:
No
Explanation:
Iteration 106

Response:
No
Explanation:
Iteration 107

Response:
No
Explanation:
Iteration 108

Response:
No
Explanation:
Iteration 109

Response:
No
Explanation:
Iteration 110

Response:
No
Explanation:
Iteration 111

Response:
No
Explanation:
Iteration 112

Response:
No
Explanation:
Iteration 113

Response:
No
Explanation:
Iteration 114

Response:
No
Explanation:
Iteration 115

Response:
No
Explanation:
Iteration 116

Response:
No
Explanation:
Iteration 117

Response:
No
Explanation:
Iteration 118

Response:
No
Explanation:
Iteration 119

Response:
No
Explanation:
Iteration 120

Response:
No
Explanation:
Iteration 121

Response:
No
Explanation:
Iteration 122

Response:
Ambiguous
Explanation
Iteration 123

Response:
Ambiguous
Explanation
Iteration 124

Response:
No
Explanation:
Iteration 125

Response:
No
Explanation:
Iteration 126

Response:
No
Explanation:
Iteration 127

Response:
No
Explanation:
Iteration 128

Response:
No
Explanation:
Iteration 129

Response:
No
Explanation:
Iteration 130

Response:
No
Explanation:
Iteration 131

Response:
No
Explanation:
Iteration 132

Response:
No
Explanation:
Iteration 133

Response:
No
Explanation:
Iteration 134

Response:
No
Explanation:
Iteration 135

Response:
No
Explanation:
Iteration 136

Response:
Ambiguous
Explanation
Iteration 137

Response:
Ambiguous
Explanation
Iteration 138

Response:
Ambiguous
Explanation
Iteration 139

Response:
Ambiguous
Explanation
Iteration 140

Response:
No
Explanation:
Iteration 141

Response:
No
Explanation:
Iteration 142

Response:
No
Explanation:
Iteration 143

Response:
No
Explanation:
Iteration 144

Response:
No
Explanation:
Iteration 145

Response:
No
Explanation:
Iteration 146

Response:
No
Explanation:
Iteration 147

Response:
No
Explanation:
Iteration 148

Response:
Ambiguous
Explanation
Iteration 149

Response:
No
Iteration 150

Response:
No
Explanation:
Iteration 151

Response:
No
Explanation:
Iteration 152

Response:
No
Explanation:
Iteration 153

Response:
No
Explanation:
Iteration 154

Response:
No
Explanation:
Iteration 155

Response:
No
Explanation:
Iteration 156

Response:
No
Explanation:
Iteration 157

Response:
No
Explanation:
Iteration 158

Response:
No
Explanation:
Iteration 159

Response:
No
Explanation:
Iteration 160

Response:
No
Explanation:
Iteration 161

Response:
No
Explanation:
Iteration 162

Response:
No
Explanation:
Iteration 163

Response:
Ambiguous
Explanation
Iteration 164

Response:
No
Iteration 165

Response:
No
Explanation:
Iteration 166

Response:
No
Explanation:
Iteration 167

Response:
No
Explanation:
Iteration 168

Response:
No
Explanation:
Iteration 169

Response:
No
Explanation:
Iteration 170

Response:
No
Explanation:
Iteration 171

Response:
No
Explanation:
Iteration 172

Response:
No
Explanation:
Iteration 173

Response:
No
Explanation:
Iteration 174

Response:
No
Explanation:
Iteration 175

Response:
No
Explanation:
Iteration 176

Response:
No
Explanation:
Iteration 177

Response:
No
Explanation:
Iteration 178

Response:
No
Explanation:
Iteration 179

Response:
No
Explanation:
Iteration 180

Response:
No
Explanation:
Iteration 181

Response:
No
Explanation:
Iteration 182

Response:
No
Explanation:
Iteration 183

Response:
No
Explanation:
Iteration 184

Response:
No
Explanation:
Iteration 185

Response:
No
Explanation:
Iteration 186

Response:
No
Explanation:
Iteration 187

Response:
No
Explanation:
Iteration 188

Response:
No
Explanation:
Iteration 189

Response:
No
Explanation:
Iteration 190

Response:
No
Explanation:
Iteration 191

Response:
No
Explanation:
Iteration 192

Response:
No
Explanation:
Iteration 193

Response:
No
Explanation:
Iteration 194

Response:
No
Explanation:
Iteration 195

Response:
No
Explanation:
Iteration 196

Response:
No
Explanation:
Iteration 197

Response:
No
Explanation:
Iteration 198

Response:
No
Explanation:
Iteration 199

Response:
No
Explanation:

In [20]:
predictions[:10]

[' \nNo\nExplanation:',
 ' \nNo\nExplanation:',
 ' \nNo\nExplanation:',
 ' \nNo\nExplanation:',
 ' \nNo\nExplanation:',
 ' \nNo\nExplanation:',
 ' \nNo\nExplanation:',
 ' \nNo\nExplanation:',
 ' \nNo\nExplanation:',
 ' \nNo\nExplanation:']

In [21]:
predictions = [elem.split("Explanation:")[0].strip() for elem in predictions]
predictions[:10]

['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No']

In [23]:
predictions

['No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Ambiguous\nExplanation',
 'Ambiguous\nExplanation',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Bill did not cause',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Ambiguous\nExplanation',
 'Ambiguous\nExplanation',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Ambiguous\nExplanation',
 'Ambiguous\nExplanation',
 'Ambiguous\nExplanation',
 'Ambiguous\nExplanation',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Ambiguous\nExplanation',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Ambiguous\nExplanation',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No']

In [24]:
predictions = [elem.split("\n")[0] for elem in predictions]
predictions

['No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Ambiguous',
 'Ambiguous',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Bill did not cause',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Ambiguous',
 'Ambiguous',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Ambiguous',
 'Ambiguous',
 'Ambiguous',
 'Ambiguous',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Ambiguous',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'Ambiguous',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No',
 'No']

In [25]:
predictions = [elem if elem=="Yes" or elem=="No" else "Ambiguous" for elem in predictions]
predictions[:10]

['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No']

In [26]:
print(classification_report(true_answers,predictions,zero_division=0))

              precision    recall  f1-score   support

   Ambiguous       0.27      0.07      0.11        45
          No       0.40      0.94      0.56        80
         Yes       0.00      0.00      0.00        75

    accuracy                           0.39       200
   macro avg       0.22      0.33      0.22       200
weighted avg       0.22      0.39      0.25       200

## Task Movie Recommendation

In [27]:
dataset = load_json("/content/task_movie_recommendation.json")

In [28]:
dataset

                                                 input target
0    Which option has more similar movies in terms ...    (E)
1    Which option has more similar movies in terms ...    (C)
2    Which option has more similar movies in terms ...    (C)
3    Which option has more similar movies in terms ...    (A)
4    Which option has more similar movies in terms ...    (I)
..                                                 ...    ...
195  Which option has more similar movies in terms ...    (E)
196  Which option has more similar movies in terms ...    (E)
197  Which option has more similar movies in terms ...    (E)
198  Which option has more similar movies in terms ...    (A)
199  Which option has more similar movies in terms ...    (F)

[200 rows x 2 columns]

In [29]:
dataset["target"].value_counts()

target
(A)    26
(G)    22
(H)    21
(E)    21
(J)    20
(D)    20
(C)    18
(F)    18
(B)    17
(I)    17
Name: count, dtype: int64

In [30]:
questions = dataset['input'].values.tolist()

In [31]:
true_answers = dataset['target'].values.tolist()

In [32]:
true_answers = [x.strip("()").upper() for x in true_answers]
true_answers[:10]

['E', 'C', 'C', 'A', 'I', 'D', 'B', 'F', 'D', 'H']

In [33]:
instruction=f"""Instruction: You are an AI assistant that determines which group of movies is most similar.
Answer only with the one of the letters (**A**, **B**, **C**, **D**, **E**, **F**, **G**, **H**, **I**, or **J**) of the group that is most similar and then stop immediately. Do not write anything else.
Final output format: A,B,C,D,E,F,G,H,I or J
"""

In [34]:
prompts = get_prompt(instruction,questions)

In [35]:
prompts[1]

'Instruction: You are an AI assistant that determines which group of movies is most similar.\nAnswer only with the one of the letters (**A**, **B**, **C**, **D**, **E**, **F**, **G**, **H**, **I**, or **J**) of the group that is most similar and then stop immediately. Do not write anything else.\nFinal output format: A,B,C,D,E,F,G,H,I or J\n\n\nWhich option has more similar movies in terms of whether a group of people will like them or not?\nOptions:\n(A) Street Fighter II The Animated Movie, The Sixth Sense, The Matrix, The Shawshank Redemption, Terminator 2 Judgment Day\n(B) The Boy Who Could Fly, The Sheltering Sky, Forrest Gump, Terminator 2 Judgment Day, The Matrix\n(C) Forrest Gump, The Shawshank Redemption, Terminator 2 Judgment Day, The Matrix, The Sixth Sense\n(D) The Boy Who Could Fly, The Sheltering Sky, Street Fighter II The Animated Movie, The Sixth Sense, Terminator 2 Judgment Day\n(E) The Matrix, The Boy Who Could Fly, Forrest Gump, The Shawshank Redemption, The Sixth Sense\n(F) The Boy Who Could Fly, The Matrix, Terminator 2 Judgment Day, The Sixth Sense, Forrest Gump\n(G) The Shawshank Redemption, Street Fighter II The Animated Movie, The Sheltering Sky, The Matrix, The Boy Who Could Fly\n(H) Street Fighter II The Animated Movie, The Matrix, The Sixth Sense, The Shawshank Redemption, The Sheltering Sky\n(I) The Sheltering Sky, Street Fighter II The Animated Movie, Forrest Gump, Terminator 2 Judgment Day, The Boy Who Could Fly\n(J) Street Fighter II The Animated Movie, The Sixth Sense, The Boy Who Could Fly, The Shawshank Redemption, Forrest Gump\n\n\nAnswer: '

In [42]:
predictions = training(prompts,num_tokens=3)

Iteration 0

Response:
The option
Iteration 1

Response:
A
Iteration 2

Response:
A
Iteration 3

Response:
A,
Iteration 4

Response:
A
Iteration 5

Response:
A
Iteration 6

Response:  12 Angry
Iteration 7

Response:
A
Iteration 8

Response:
A
Iteration 9

Response:
A
Iteration 10

Response:
The group
Iteration 11

Response:
A
Iteration 12

Response:
A
Iteration 13

Response:
The group
Iteration 14

Response:
The option
Iteration 15

Response:
A
Iteration 16

Response:
The Art
Iteration 17

Response:
A
Iteration 18

Response:
A
Iteration 19

Response:  1.
Iteration 20

Response:
A
Iteration 21

Response:
A
Iteration 22

Response:
A
Iteration 23

Response:
A
Iteration 24

Response:
The option
Iteration 25

Response:
A
Iteration 26

Response:
A
Iteration 27

Response:
A
Iteration 28

Response:
A
Iteration 29

Response:
A
Iteration 30

Response:
The option
Iteration 31

Response:
A
Iteration 32

Response:
A
Iteration 33

Response:
A
Iteration 34

Response:
A
Iteration 35

Response:
A
Iteration 36

Response:
The option
Iteration 37

Response:
A,
Iteration 38

Response:
A
Iteration 39

Response:
A,
Iteration 40

Response:
A
Iteration 41

Response:
A
Iteration 42

Response:
A
Iteration 43

Response:
A
Iteration 44

Response:
A
Iteration 45

Response:
The option
Iteration 46

Response:
Gint
Iteration 47

Response:
A
Iteration 48

Response:
A
Iteration 49

Response:
A
Iteration 50

Response:
H
Iteration 51

Response:
G
Iteration 52

Response:
A
Iteration 53

Response:
A
Iteration 54

Response:
A
Iteration 55

Response:
A
Iteration 56

Response:
G
Iteration 57

Response:
A
Iteration 58

Response:
The option
Iteration 59

Response:
A
Iteration 60

Response:
A
Iteration 61

Response:
I
Iteration 62

Response:
A
Iteration 63

Response:
The option
Iteration 64

Response:
A
Iteration 65

Response:
A
Iteration 66

Response:
A
Iteration 67

Response:
A
Iteration 68

Response:
A
Iteration 69

Response:
The Shaw
Iteration 70

Response:
A
Iteration 71

Response:
A
Iteration 72

Response:
A
Iteration 73

Response:
A
Iteration 74

Response:
A
Iteration 75

Response:
A
Iteration 76

Response:
A
Iteration 77

Response:
The group
Iteration 78

Response:
A
Iteration 79

Response:
A
Iteration 80

Response:
A
Iteration 81

Response:
The option
Iteration 82

Response:
A
Iteration 83

Response:
A
Iteration 84

Response:
A
Iteration 85

Response:
The option
Iteration 86

Response:
A,
Iteration 87

Response:
A
Iteration 88

Response:
A
Iteration 89

Response:
A
Iteration 90

Response:
A
Iteration 91

Response:
A
Iteration 92

Response:
A
Iteration 93

Response:
A
Iteration 94

Response:
A
Iteration 95

Response:
The option
Iteration 96

Response:
A
Iteration 97

Response:
A
Iteration 98

Response:
A
Iteration 99

Response:
The Good
Iteration 100

Response:
A
Iteration 101

Response:
A
Iteration 102

Response:
A
Iteration 103

Response:
A
Iteration 104

Response:
A
Iteration 105

Response:
A
Iteration 106

Response:
A
Iteration 107

Response:
A
Iteration 108

Response:
A
Iteration 109

Response:
The option
Iteration 110

Response:
The option
Iteration 111

Response:
The option
Iteration 112

Response:
A,
Iteration 113

Response:
A
Iteration 114

Response:
A
Iteration 115

Response:
A
Iteration 116

Response:
The group
Iteration 117

Response:
G
Iteration 118

Response:
The group
Iteration 119

Response:
A
Iteration 120

Response:
I
Iteration 121

Response:
A,
Iteration 122

Response:
A
Iteration 123

Response:  1.
Iteration 124

Response:
(A
Iteration 125

Response:
The group
Iteration 126

Response:
A
Iteration 127

Response:
The group
Iteration 128

Response:
The option
Iteration 129

Response:
A
Iteration 130

Response:
The option
Iteration 131

Response:
A
Iteration 132

Response:
A
Iteration 133

Response:
A
Iteration 134

Response:
A
Iteration 135

Response:
A
Iteration 136

Response:
The option
Iteration 137

Response:
A
Iteration 138

Response:
A
Iteration 139

Response:
A
Iteration 140

Response:
A
Iteration 141

Response:
A
Iteration 142

Response:
The Ew
Iteration 143

Response:
G
Iteration 144

Response:
A
Iteration 145

Response:
A
Iteration 146

Response:
The group
Iteration 147

Response:
A
Iteration 148

Response:
G
Iteration 149

Response:
A
Iteration 150

Response:
A
Iteration 151

Response:
I
Iteration 152

Response:
A
Iteration 153

Response:
The option
Iteration 154

Response:
A,
Iteration 155

Response:
A
Iteration 156

Response:
A
Iteration 157

Response:
The option
Iteration 158

Response:
A
Iteration 159

Response:
The group
Iteration 160

Response:
A
Iteration 161

Response:
The group
Iteration 162

Response:
A
Iteration 163

Response:
A
Iteration 164

Response:
A
Iteration 165

Response:
The group
Iteration 166

Response:
The group
Iteration 167

Response:
A
Iteration 168

Response:
A
Iteration 169

Response:
The group
Iteration 170

Response:
The Terminator
Iteration 171

Response:
G
Iteration 172

Response:
The option
Iteration 173

Response:
A
Iteration 174

Response:  1.
Iteration 175

Response:
A
Iteration 176

Response:
A
Iteration 177

Response:
The Silence
Iteration 178

Response:
A
Iteration 179

Response:
The option
Iteration 180

Response:
A
Iteration 181

Response:
A
Iteration 182

Response:
I
Iteration 183

Response:
A
Iteration 184

Response:
A
Iteration 185

Response:
A
Iteration 186

Response:
A
Iteration 187

Response:
A
Iteration 188

Response:
A
Iteration 189

Response:
I
Iteration 190

Response:
A
Iteration 191

Response:
A
Iteration 192

Response:
A,
Iteration 193

Response:
A
Iteration 194

Response:
A
Iteration 195

Response:
A
Iteration 196

Response:
A
Iteration 197

Response:
A
Iteration 198

Response:
A
Iteration 199

Response:
The option

In [43]:
predictions

[' \nThe option',
 ' \nA',
 ' \nA',
 ' \nA,',
 ' \nA',
 ' \nA',
 ' 12 Angry',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nThe group',
 ' \nA',
 ' \nA',
 ' \nThe group',
 ' \nThe option',
 ' \nA',
 ' \nThe Art',
 ' \nA',
 ' \nA',
 ' 1.',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nThe option',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nThe option',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nThe option',
 ' \nA,',
 ' \nA',
 ' \nA,',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nThe option',
 ' \nGint',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nH',
 ' \nG',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nG',
 ' \nA',
 ' \nThe option',
 ' \nA',
 ' \nA',
 ' \nI',
 ' \nA',
 ' \nThe option',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nThe Shaw',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nThe group',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nThe option',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nThe option',
 ' \nA,',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nThe option',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nThe Good',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nThe option',
 ' \nThe option',
 ' \nThe option',
 ' \nA,',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nThe group',
 ' \nG',
 ' \nThe group',
 ' \nA',
 ' \nI',
 ' \nA,',
 ' \nA',
 ' 1.',
 ' \n(A',
 ' \nThe group',
 ' \nA',
 ' \nThe group',
 ' \nThe option',
 ' \nA',
 ' \nThe option',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nThe option',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nThe Ew',
 ' \nG',
 ' \nA',
 ' \nA',
 ' \nThe group',
 ' \nA',
 ' \nG',
 ' \nA',
 ' \nA',
 ' \nI',
 ' \nA',
 ' \nThe option',
 ' \nA,',
 ' \nA',
 ' \nA',
 ' \nThe option',
 ' \nA',
 ' \nThe group',
 ' \nA',
 ' \nThe group',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nThe group',
 ' \nThe group',
 ' \nA',
 ' \nA',
 ' \nThe group',
 ' \nThe Terminator',
 ' \nG',
 ' \nThe option',
 ' \nA',
 ' 1.',
 ' \nA',
 ' \nA',
 ' \nThe Silence',
 ' \nA',
 ' \nThe option',
 ' \nA',
 ' \nA',
 ' \nI',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nI',
 ' \nA',
 ' \nA',
 ' \nA,',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nA',
 ' \nThe option']

In [45]:
predictions = [elem.strip() for elem in predictions]
predictions

['The option',
 'A',
 'A',
 'A,',
 'A',
 'A',
 '12 Angry',
 'A',
 'A',
 'A',
 'The group',
 'A',
 'A',
 'The group',
 'The option',
 'A',
 'The Art',
 'A',
 'A',
 '1.',
 'A',
 'A',
 'A',
 'A',
 'The option',
 'A',
 'A',
 'A',
 'A',
 'A',
 'The option',
 'A',
 'A',
 'A',
 'A',
 'A',
 'The option',
 'A,',
 'A',
 'A,',
 'A',
 'A',
 'A',
 'A',
 'A',
 'The option',
 'Gint',
 'A',
 'A',
 'A',
 'H',
 'G',
 'A',
 'A',
 'A',
 'A',
 'G',
 'A',
 'The option',
 'A',
 'A',
 'I',
 'A',
 'The option',
 'A',
 'A',
 'A',
 'A',
 'A',
 'The Shaw',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'The group',
 'A',
 'A',
 'A',
 'The option',
 'A',
 'A',
 'A',
 'The option',
 'A,',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'The option',
 'A',
 'A',
 'A',
 'The Good',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'The option',
 'The option',
 'The option',
 'A,',
 'A',
 'A',
 'A',
 'The group',
 'G',
 'The group',
 'A',
 'I',
 'A,',
 'A',
 '1.',
 '(A',
 'The group',
 'A',
 'The group',
 'The option',
 'A',
 'The option',
 'A',
 'A',
 'A',
 'A',
 'A',
 'The option',
 'A',
 'A',
 'A',
 'A',
 'A',
 'The Ew',
 'G',
 'A',
 'A',
 'The group',
 'A',
 'G',
 'A',
 'A',
 'I',
 'A',
 'The option',
 'A,',
 'A',
 'A',
 'The option',
 'A',
 'The group',
 'A',
 'The group',
 'A',
 'A',
 'A',
 'The group',
 'The group',
 'A',
 'A',
 'The group',
 'The Terminator',
 'G',
 'The option',
 'A',
 '1.',
 'A',
 'A',
 'The Silence',
 'A',
 'The option',
 'A',
 'A',
 'I',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'I',
 'A',
 'A',
 'A,',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'The option']

In [46]:
predictions = [elem if elem  in list("ABCDEFGHIJ") else "Unknown" for elem in predictions]
predictions

['Unknown',
 'A',
 'A',
 'Unknown',
 'A',
 'A',
 'Unknown',
 'A',
 'A',
 'A',
 'Unknown',
 'A',
 'A',
 'Unknown',
 'Unknown',
 'A',
 'Unknown',
 'A',
 'A',
 'Unknown',
 'A',
 'A',
 'A',
 'A',
 'Unknown',
 'A',
 'A',
 'A',
 'A',
 'A',
 'Unknown',
 'A',
 'A',
 'A',
 'A',
 'A',
 'Unknown',
 'Unknown',
 'A',
 'Unknown',
 'A',
 'A',
 'A',
 'A',
 'A',
 'Unknown',
 'Unknown',
 'A',
 'A',
 'A',
 'H',
 'G',
 'A',
 'A',
 'A',
 'A',
 'G',
 'A',
 'Unknown',
 'A',
 'A',
 'I',
 'A',
 'Unknown',
 'A',
 'A',
 'A',
 'A',
 'A',
 'Unknown',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'Unknown',
 'A',
 'A',
 'A',
 'Unknown',
 'A',
 'A',
 'A',
 'Unknown',
 'Unknown',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'Unknown',
 'A',
 'A',
 'A',
 'Unknown',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'Unknown',
 'Unknown',
 'Unknown',
 'Unknown',
 'A',
 'A',
 'A',
 'Unknown',
 'G',
 'Unknown',
 'A',
 'I',
 'Unknown',
 'A',
 'Unknown',
 'Unknown',
 'Unknown',
 'A',
 'Unknown',
 'Unknown',
 'A',
 'Unknown',
 'A',
 'A',
 'A',
 'A',
 'A',
 'Unknown',
 'A',
 'A',
 'A',
 'A',
 'A',
 'Unknown',
 'G',
 'A',
 'A',
 'Unknown',
 'A',
 'G',
 'A',
 'A',
 'I',
 'A',
 'Unknown',
 'Unknown',
 'A',
 'A',
 'Unknown',
 'A',
 'Unknown',
 'A',
 'Unknown',
 'A',
 'A',
 'A',
 'Unknown',
 'Unknown',
 'A',
 'A',
 'Unknown',
 'Unknown',
 'G',
 'Unknown',
 'A',
 'Unknown',
 'A',
 'A',
 'Unknown',
 'A',
 'Unknown',
 'A',
 'A',
 'I',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'I',
 'A',
 'A',
 'Unknown',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'Unknown']

In [47]:
print(classification_report(true_answers,predictions,zero_division=0))

              precision    recall  f1-score   support

           A       0.16      0.81      0.26        26
           B       0.00      0.00      0.00        17
           C       0.00      0.00      0.00        18
           D       0.00      0.00      0.00        20
           E       0.00      0.00      0.00        21
           F       0.00      0.00      0.00        18
           G       0.50      0.14      0.21        22
           H       0.00      0.00      0.00        21
           I       0.00      0.00      0.00        17
           J       0.00      0.00      0.00        20
     Unknown       0.00      0.00      0.00         0

    accuracy                           0.12       200
   macro avg       0.06      0.09      0.04       200
weighted avg       0.08      0.12      0.06       200

## Task Disambiguation QA

In [48]:
dataset = load_json("/content/task_disambiguationQA.json")

In [49]:
dataset['target'].value_counts()

target
(B)    25
(D)    24
(C)    23
(A)    22
(E)    17
(F)     7
(G)     1
(H)     1
Name: count, dtype: int64

In [50]:
questions = dataset['input'].values.tolist()

In [51]:
true_answers = dataset['target'].values.tolist()

In [52]:
true_answers = [x.strip("()").upper() for x in true_answers]
true_answers[:10]

['A', 'D', 'E', 'B', 'A', 'B', 'B', 'A', 'C', 'D']

In [53]:
instruction = f"""You are an AI assistant solving a pronoun disambiguation task.

For each sentence:
- Identify what the pronoun(s) most likely refer to based on common sense.
- If more than one interpretation is equally plausible, select “Ambiguous”.

Rules:
- Do not assume information that is not stated.
- Do not infer intent beyond what is commonly assumed.
- Choose exactly one answer from (A)–(H) based on available letters.

Final answer format:
(A), (B), (C), (D), (E), (H), (G), or (F)
"""

In [54]:
prompts = get_prompt(instruction,questions)

In [55]:
prompts[1]

'You are an AI assistant solving a pronoun disambiguation task.\n\nFor each sentence:\n- Identify what the pronoun(s) most likely refer to based on common sense.\n- If more than one interpretation is equally plausible, select “Ambiguous”.\n\nRules:\n- Do not assume information that is not stated.\n- Do not infer intent beyond what is commonly assumed.\n- Choose exactly one answer from (A)–(H) based on available letters.\n\nFinal answer format:\n(A), (B), (C), (D), (E), (H), (G), or (F)\n\n\nHere is a sentence with pronoun(s) whose antecedent(s) can either be derived from the context or is ambiguous.\nSentence: The designer called the janitor and asked him to clean the room as soon as possible, but he went to fetch a cup of coffee first and then returned to his desk.\nWhich of the following options correctly explains the antecedent(s) of the pronoun(s)?\n(A) Designer is cleaning the room as soon as possible and got coffee.\n(B) Janitor is cleaning the room as soon as possible and got coffee.\n(C) Designer is cleaning the room as soon as possible and janitor got coffee.\n(D) Janitor is cleaning the room as soon as possible and designer got coffee.\n(E) Ambiguous.\n\nAnswer: '

In [56]:
predictions = training(prompts,num_tokens=3)

Iteration 0

Response:
(C
Iteration 1

Response:
(A
Iteration 2

Response:
(C
Iteration 3

Response:
(A
Iteration 4

Response:
(C
Iteration 5

Response:
(B
Iteration 6

Response:
(C
Iteration 7

Response:
(A
Iteration 8

Response:
(B
Iteration 9

Response:
(C
Iteration 10

Response:
(C
Iteration 11

Response:
(A
Iteration 12

Response:
(C
Iteration 13

Response:
(C
Iteration 14

Response:
(C
Iteration 15

Response:
(C
Iteration 16

Response:
(A
Iteration 17

Response:
(C
Iteration 18

Response:
(A
Iteration 19

Response:
(B
Iteration 20

Response:
(B
Iteration 21

Response:
(A
Iteration 22

Response:
(B
Iteration 23

Response:
(C
Iteration 24

Response:
(C
Iteration 25

Response:
(A
Iteration 26

Response:
(A
Iteration 27

Response:
(B
Iteration 28

Response:
(A
Iteration 29

Response:
(A
Iteration 30

Response:
(A
Iteration 31

Response:
(A
Iteration 32

Response:
(A
Iteration 33

Response:
(C
Iteration 34

Response:
(B
Iteration 35

Response:
(A
Iteration 36

Response:
(A
Iteration 37

Response:
(A
Iteration 38

Response:
(A
Iteration 39

Response:
(C
Iteration 40

Response:
(C
Iteration 41

Response:
(A
Iteration 42

Response:
(A
Iteration 43

Response:
(A
Iteration 44

Response:
(A
Iteration 45

Response:
(A
Iteration 46

Response:
(C
Iteration 47

Response:
(B
Iteration 48

Response:
(A
Iteration 49

Response:
(A
Iteration 50

Response:
(C
Iteration 51

Response:
(E
Iteration 52

Response:
(A
Iteration 53

Response:
(C
Iteration 54

Response:
(B
Iteration 55

Response:
(C
Iteration 56

Response:
(C
Iteration 57

Response:
(A
Iteration 58

Response:
(A
Iteration 59

Response:
(A
Iteration 60

Response:
(A
Iteration 61

Response:
(A
Iteration 62

Response:
(E
Iteration 63

Response:
(C
Iteration 64

Response:
(C
Iteration 65

Response:
(A
Iteration 66

Response:
(C
Iteration 67

Response:
(C
Iteration 68

Response:
(A
Iteration 69

Response:
(A
Iteration 70

Response:
(C
Iteration 71

Response:
(A
Iteration 72

Response:
(A
Iteration 73

Response:
(A
Iteration 74

Response:
(A
Iteration 75

Response:
(C
Iteration 76

Response:
(A
Iteration 77

Response:
(C
Iteration 78

Response:
(A
Iteration 79

Response:
(A
Iteration 80

Response:
(C
Iteration 81

Response:
(C
Iteration 82

Response:
(C
Iteration 83

Response:
(A
Iteration 84

Response:
(C
Iteration 85

Response:
(C
Iteration 86

Response:
(C
Iteration 87

Response:
(C
Iteration 88

Response:
(C
Iteration 89

Response:
(B
Iteration 90

Response:
(A
Iteration 91

Response:
(A
Iteration 92

Response:
(A
Iteration 93

Response:
(A
Iteration 94

Response:
(C
Iteration 95

Response:
(A
Iteration 96

Response:
(C
Iteration 97

Response:
(C
Iteration 98

Response:
(B
Iteration 99

Response:
(A
Iteration 100

Response:
(C
Iteration 101

Response:
(C
Iteration 102

Response:
(C
Iteration 103

Response:
(C
Iteration 104

Response:
(B
Iteration 105

Response:
(B
Iteration 106

Response:
(A
Iteration 107

Response:
(A
Iteration 108

Response:
(C
Iteration 109

Response:
(B
Iteration 110

Response:
(A
Iteration 111

Response:
(E
Iteration 112

Response:
(C
Iteration 113

Response:
(C
Iteration 114

Response:
(D
Iteration 115

Response:
(A
Iteration 116

Response:
(B
Iteration 117

Response:
(A
Iteration 118

Response:
(D
Iteration 119

Response:
(A

In [57]:
predictions

[' \n(C',
 ' \n(A',
 ' \n(C',
 ' \n(A',
 ' \n(C',
 ' \n(B',
 ' \n(C',
 ' \n(A',
 ' \n(B',
 ' \n(C',
 ' \n(C',
 ' \n(A',
 ' \n(C',
 ' \n(C',
 ' \n(C',
 ' \n(C',
 ' \n(A',
 ' \n(C',
 ' \n(A',
 ' \n(B',
 ' \n(B',
 ' \n(A',
 ' \n(B',
 ' \n(C',
 ' \n(C',
 ' \n(A',
 ' \n(A',
 ' \n(B',
 ' \n(A',
 ' \n(A',
 ' \n(A',
 ' \n(A',
 ' \n(A',
 ' \n(C',
 ' \n(B',
 ' \n(A',
 ' \n(A',
 ' \n(A',
 ' \n(A',
 ' \n(C',
 ' \n(C',
 ' \n(A',
 ' \n(A',
 ' \n(A',
 ' \n(A',
 ' \n(A',
 ' \n(C',
 ' \n(B',
 ' \n(A',
 ' \n(A',
 ' \n(C',
 ' \n(E',
 ' \n(A',
 ' \n(C',
 ' \n(B',
 ' \n(C',
 ' \n(C',
 ' \n(A',
 ' \n(A',
 ' \n(A',
 ' \n(A',
 ' \n(A',
 ' \n(E',
 ' \n(C',
 ' \n(C',
 ' \n(A',
 ' \n(C',
 ' \n(C',
 ' \n(A',
 ' \n(A',
 ' \n(C',
 ' \n(A',
 ' \n(A',
 ' \n(A',
 ' \n(A',
 ' \n(C',
 ' \n(A',
 ' \n(C',
 ' \n(A',
 ' \n(A',
 ' \n(C',
 ' \n(C',
 ' \n(C',
 ' \n(A',
 ' \n(C',
 ' \n(C',
 ' \n(C',
 ' \n(C',
 ' \n(C',
 ' \n(B',
 ' \n(A',
 ' \n(A',
 ' \n(A',
 ' \n(A',
 ' \n(C',
 ' \n(A',
 ' \n(C',
 ' \n(C',
 ' \n(B',
 ' \n(A',
 ' \n(C',
 ' \n(C',
 ' \n(C',
 ' \n(C',
 ' \n(B',
 ' \n(B',
 ' \n(A',
 ' \n(A',
 ' \n(C',
 ' \n(B',
 ' \n(A',
 ' \n(E',
 ' \n(C',
 ' \n(C',
 ' \n(D',
 ' \n(A',
 ' \n(B',
 ' \n(A',
 ' \n(D',
 ' \n(A']

In [58]:
predictions = [x.strip() for x in predictions]
predictions

['(C',
 '(A',
 '(C',
 '(A',
 '(C',
 '(B',
 '(C',
 '(A',
 '(B',
 '(C',
 '(C',
 '(A',
 '(C',
 '(C',
 '(C',
 '(C',
 '(A',
 '(C',
 '(A',
 '(B',
 '(B',
 '(A',
 '(B',
 '(C',
 '(C',
 '(A',
 '(A',
 '(B',
 '(A',
 '(A',
 '(A',
 '(A',
 '(A',
 '(C',
 '(B',
 '(A',
 '(A',
 '(A',
 '(A',
 '(C',
 '(C',
 '(A',
 '(A',
 '(A',
 '(A',
 '(A',
 '(C',
 '(B',
 '(A',
 '(A',
 '(C',
 '(E',
 '(A',
 '(C',
 '(B',
 '(C',
 '(C',
 '(A',
 '(A',
 '(A',
 '(A',
 '(A',
 '(E',
 '(C',
 '(C',
 '(A',
 '(C',
 '(C',
 '(A',
 '(A',
 '(C',
 '(A',
 '(A',
 '(A',
 '(A',
 '(C',
 '(A',
 '(C',
 '(A',
 '(A',
 '(C',
 '(C',
 '(C',
 '(A',
 '(C',
 '(C',
 '(C',
 '(C',
 '(C',
 '(B',
 '(A',
 '(A',
 '(A',
 '(A',
 '(C',
 '(A',
 '(C',
 '(C',
 '(B',
 '(A',
 '(C',
 '(C',
 '(C',
 '(C',
 '(B',
 '(B',
 '(A',
 '(A',
 '(C',
 '(B',
 '(A',
 '(E',
 '(C',
 '(C',
 '(D',
 '(A',
 '(B',
 '(A',
 '(D',
 '(A']

In [59]:
predictions = [x.strip("(").upper() for x in predictions]
predictions

['C',
 'A',
 'C',
 'A',
 'C',
 'B',
 'C',
 'A',
 'B',
 'C',
 'C',
 'A',
 'C',
 'C',
 'C',
 'C',
 'A',
 'C',
 'A',
 'B',
 'B',
 'A',
 'B',
 'C',
 'C',
 'A',
 'A',
 'B',
 'A',
 'A',
 'A',
 'A',
 'A',
 'C',
 'B',
 'A',
 'A',
 'A',
 'A',
 'C',
 'C',
 'A',
 'A',
 'A',
 'A',
 'A',
 'C',
 'B',
 'A',
 'A',
 'C',
 'E',
 'A',
 'C',
 'B',
 'C',
 'C',
 'A',
 'A',
 'A',
 'A',
 'A',
 'E',
 'C',
 'C',
 'A',
 'C',
 'C',
 'A',
 'A',
 'C',
 'A',
 'A',
 'A',
 'A',
 'C',
 'A',
 'C',
 'A',
 'A',
 'C',
 'C',
 'C',
 'A',
 'C',
 'C',
 'C',
 'C',
 'C',
 'B',
 'A',
 'A',
 'A',
 'A',
 'C',
 'A',
 'C',
 'C',
 'B',
 'A',
 'C',
 'C',
 'C',
 'C',
 'B',
 'B',
 'A',
 'A',
 'C',
 'B',
 'A',
 'E',
 'C',
 'C',
 'D',
 'A',
 'B',
 'A',
 'D',
 'A']

In [60]:
print(classification_report(true_answers,predictions,zero_division=0))

              precision    recall  f1-score   support

           A       0.17      0.41      0.24        22
           B       0.40      0.24      0.30        25
           C       0.30      0.61      0.41        23
           D       0.50      0.04      0.08        24
           E       0.67      0.12      0.20        17
           F       0.00      0.00      0.00         7
           G       0.00      0.00      0.00         1
           H       0.00      0.00      0.00         1

    accuracy                           0.27       120
   macro avg       0.25      0.18      0.15       120
weighted avg       0.37      0.27      0.23       120

## Task: Boolean Expressions

In [61]:
dataset = load_json("/content/task_boolean_expressions.json")

In [62]:
dataset

                                                 input target
0    From the following five expressions, only one ...    (E)
1    From the following five expressions, only one ...    (C)
2    From the following five expressions, only one ...    (E)
3    From the following five expressions, only one ...    (D)
4    From the following five expressions, only one ...    (C)
..                                                 ...    ...
195  From the following five expressions, only one ...    (A)
196  From the following five expressions, only one ...    (B)
197  From the following five expressions, only one ...    (B)
198  From the following five expressions, only one ...    (C)
199  From the following five expressions, only one ...    (A)

[200 rows x 2 columns]

In [63]:
dataset["target"].value_counts()

target
(E)    43
(B)    41
(C)    40
(A)    39
(D)    37
Name: count, dtype: int64

In [64]:
questions = dataset["input"].values.tolist()

In [65]:
true_answers = dataset["target"].values.tolist()

In [66]:
true_answers = [x.strip("()").upper() for x in true_answers]
true_answers[:10]

['E', 'C', 'E', 'D', 'C', 'D', 'C', 'D', 'A', 'A']

In [67]:
instruction=f"""You are evaluating boolean expressions.

Exactly one option is True.

Output format rules:
- Output ONLY one of the following exact strings:
(A)
(B)
(C)
(D)
(E)

Do NOT use LaTeX.
Do NOT use special symbols.
Do NOT add explanations.
Do NOT add whitespace or extra characters.
"""

In [68]:
prompts = get_prompt(instruction,questions)

In [69]:
prompts[0]

'You are evaluating boolean expressions.\n\nExactly one option is True.\n\nOutput format rules:\n- Output ONLY one of the following exact strings:\n(A)\n(B)\n(C)\n(D)\n(E)\n\nDo NOT use LaTeX.\nDo NOT use special symbols.\nDo NOT add explanations.\nDo NOT add whitespace or extra characters.\n\n\nFrom the following five expressions, only one evaluates to true. Which one is it?\n\n(A) not (not (not (not (False) or (-5 - (1 / -5) is greater than -7)) or (not (False) or (-5 * -10 + -5 * -6 is greater than -4 * 6))) or (not (not (False) or (False)) or (not not not (-3 - (-2 / 4) is greater than -6) and not not (The capital of India is Mumbai.)))) and (not (not (not (The capital of the Nigeria is Abuja.) or (-7 - (-4 / 7) > 4)) or (not (-6 - (-7 / -5) > -6) and (True))) and (not not ((-1 * 9 is less than or equal to -6) or (-4 * 10 + -1 * -7 <= 9 * 10)) or not not not (not not (6 * -2 is less than or equal to 4) or not not not (-5 * 9 + 6 * -3 <= -9 * 6))))\n(B) ((not (not not not (not (not (not not not (not not (not (not (max(-3, 8, 5, -2) - min(-3, 8, 5, -2) <= 4) and (False)) or (max(-6, 8, 5, -1) - min(-6, 8, 5, -1) <= 9)) or not not not (-6 - (9 / -1) is less than or equal to 6)) and not not (The capital of Afghanistan is Kabul.)) or (1 - (5 / -2) > 4)) or (True)) and not not (-3 * -8 <= 1)) and (9 * -1 + -6 * 7 > 10 * 10)) or (The capital of Denmark is Aarhus.)) and (9 * 8 + 7 * 10 is less than or equal to 5 * 10)\n(C) not ((not not (not not (not (not not (not (not not not (5 - (6 / 2) > 5) and not not (True)) or (3 * -7 + 3 * -2 <= -6 * 2)) or not not not (False)) and (-9 - (-2 / 3) > 6)) or not not not (max(8, -1, -7, -6) - min(8, -1, -7, -6) is greater than 1)) or not not not (max(9, -4, -3, -4) - min(9, -4, -3, -4) is greater than 3)) and (The capital of Turkey is Istanbul.)) and (2 * 3 + 10 * -9 > -7 * -8)\n(D) not (not (not (not (The capital of Jordan is Amman.) or (max(7, 3, -2, 10) - min(7, 3, -2, 10) is greater than 7)) or (not not not (The capital of Colombia is Bogota.) and not not (The capital of Afghanistan is Kandahar.))) and (not (not not (-4 - (2 / -1) <= -6) or not not not (max(8, -6, -6, 9) - min(8, -6, -6, 9) is greater than 1)) or (not (The capital of Iraq is Beirut.) or (-6 * 1 > -6)))) and (not not not (not not not (not (The capital of Norway is Bergen.) and (The capital of Norway is Bergen.)) and not not (not not not (True) and not not (The capital of Denmark is Copenhagen.))) and not not (not (not (True) or (The capital of Canada is Ottawa.)) and ((False) or (max(9, 3, -7, 9) - min(9, 3, -7, 9) is greater than 6))))\n(E) not ((not (not (not not (not not ((not (not (not ((False) or (1 * 6 + 6 * 1 <= -10 * -4)) and (-6 * 7 > 5)) or (-3 * -3 + 3 * -2 <= -5 * -7)) or (The capital of Colombia is Medellin.)) or (-3 * 6 > 6)) or not not not (max(-10, 9, -2, -7) - min(-10, 9, -2, -7) is greater than 3)) or not not not (-3 * -2 + -4 * -5 is greater than 1 * 5)) or (7 * -3 > -9)) or (max(2, -4, 3, -3) - min(2, -4, 3, -3) > 8)) and (False)) and (8 * -2 is less than or equal to -8)\n\n\nAnswer: '

In [71]:
predictions = training(prompts,num_tokens=1)

Iteration 0

Response:  1
Iteration 1

Response:  1
Iteration 2

Response:  1
Iteration 3

Response:  1
Iteration 4

Response:  1
Iteration 5

Response:  1
Iteration 6

Response:  1
Iteration 7

Response:  1
Iteration 8

Response:  1
Iteration 9

Response:  1
Iteration 10

Response:  1
Iteration 11

Response:  1
Iteration 12

Response:  1
Iteration 13

Response:  1
Iteration 14

Response:  1
Iteration 15

Response:  1
Iteration 16

Response:  1
Iteration 17

Response:  1
Iteration 18

Response:  1
Iteration 19

Response:  1
Iteration 20

Response:  1
Iteration 21

Response:  1
Iteration 22

Response:  1
Iteration 23

Response:  1
Iteration 24

Response:  1
Iteration 25

Response:  1
Iteration 26

Response:  1
Iteration 27

Response:  1
Iteration 28

Response:  1
Iteration 29

Response:  1
Iteration 30

Response:  1
Iteration 31

Response:  1
Iteration 32

Response:  1
Iteration 33

Response:  1
Iteration 34

Response:  1
Iteration 35

Response:  1
Iteration 36

Response:  1
Iteration 37

Response:  1
Iteration 38

Response:  1
Iteration 39

Response:  1
Iteration 40

Response:  1
Iteration 41

Response:  1
Iteration 42

Response:  1
Iteration 43

Response:  1
Iteration 44

Response:  1
Iteration 45

Response:  1
Iteration 46

Response:  1
Iteration 47

Response:  1
Iteration 48

Response:  1
Iteration 49

Response:  1
Iteration 50

Response:  1
Iteration 51

Response:  1
Iteration 52

Response:  1
Iteration 53

Response:  1
Iteration 54

Response:  1
Iteration 55

Response:  1
Iteration 56

Response:  1
Iteration 57

Response:  1
Iteration 58

Response:  1
Iteration 59

Response:  1
Iteration 60

Response:  1
Iteration 61

Response:  1
Iteration 62

Response:  1
Iteration 63

Response:  1
Iteration 64

Response:  1
Iteration 65

Response:  1
Iteration 66

Response:  1
Iteration 67

Response:  1
Iteration 68

Response:  1
Iteration 69

Response:  1
Iteration 70

Response:  1
Iteration 71

Response:  1
Iteration 72

Response:  1
Iteration 73

Response:  1
Iteration 74

Response:  1
Iteration 75

Response:  1
Iteration 76

Response:  1
Iteration 77

Response:  1
Iteration 78

Response:  1
Iteration 79

Response:  1
Iteration 80

Response:  1
Iteration 81

Response:  1
Iteration 82

Response:  1
Iteration 83

Response:  1
Iteration 84

Response:  1
Iteration 85

Response:  1
Iteration 86

Response:  1
Iteration 87

Response:  1
Iteration 88

Response:  1
Iteration 89

Response:  1
Iteration 90

Response:  1
Iteration 91

Response:  1
Iteration 92

Response:  1
Iteration 93

Response:  ________________
Iteration 94

Response:  1
Iteration 95

Response:  1
Iteration 96

Response:  1
Iteration 97

Response:  1
Iteration 98

Response:  1
Iteration 99

Response:  1
Iteration 100

Response:  1
Iteration 101

Response:  1
Iteration 102

Response:  1
Iteration 103

Response:  1
Iteration 104

Response:  1
Iteration 105

Response:  1
Iteration 106

Response:  1
Iteration 107

Response:  1
Iteration 108

Response:  1
Iteration 109

Response:  1
Iteration 110

Response:  1
Iteration 111

Response:  1
Iteration 112

Response:  1
Iteration 113

Response:  1
Iteration 114

Response:  1
Iteration 115

Response:  1
Iteration 116

Response:  1
Iteration 117

Response:  1
Iteration 118

Response:  1
Iteration 119

Response:  1
Iteration 120

Response:  1
Iteration 121

Response:  1
Iteration 122

Response:  1
Iteration 123

Response:  1
Iteration 124

Response:  1
Iteration 125

Response:  1
Iteration 126

Response:  1
Iteration 127

Response:  1
Iteration 128

Response:  1
Iteration 129

Response:  1
Iteration 130

Response:  1
Iteration 131

Response:  1
Iteration 132

Response:  1
Iteration 133

Response:  1
Iteration 134

Response:  1
Iteration 135

Response:  1
Iteration 136

Response:  1
Iteration 137

Response:  1
Iteration 138

Response:  1
Iteration 139

Response:  1
Iteration 140

Response:  1
Iteration 141

Response:  1
Iteration 142

Response:  1
Iteration 143

Response:  1
Iteration 144

Response:  1
Iteration 145

Response:  1
Iteration 146

Response:  1
Iteration 147

Response:  1
Iteration 148

Response:  1
Iteration 149

Response:  1
Iteration 150

Response:  1
Iteration 151

Response:  1
Iteration 152

Response:  1
Iteration 153

Response:  1
Iteration 154

Response:  1
Iteration 155

Response:  1
Iteration 156

Response:  1
Iteration 157

Response:  1
Iteration 158

Response:  1
Iteration 159

Response:  1
Iteration 160

Response:  1
Iteration 161

Response:  1
Iteration 162

Response:  1
Iteration 163

Response:  1
Iteration 164

Response:  1
Iteration 165

Response:  1
Iteration 166

Response:  1
Iteration 167

Response:  1
Iteration 168

Response:  1
Iteration 169

Response:  1
Iteration 170

Response:  1
Iteration 171

Response:  1
Iteration 172

Response:  1
Iteration 173

Response:  1
Iteration 174

Response:  1
Iteration 175

Response:  1
Iteration 176

Response:  1
Iteration 177

Response:  1
Iteration 178

Response:  1
Iteration 179

Response:  1
Iteration 180

Response:  1
Iteration 181

Response:  1
Iteration 182

Response:  1
Iteration 183

Response:  1
Iteration 184

Response:  1
Iteration 185

Response:  1
Iteration 186

Response:  1
Iteration 187

Response:  1
Iteration 188

Response:  1
Iteration 189

Response:  1
Iteration 190

Response:  1
Iteration 191

Response:  1
Iteration 192

Response:  1
Iteration 193

Response:  1
Iteration 194

Response:  1
Iteration 195

Response:  1
Iteration 196

Response:  1
Iteration 197

Response:  1
Iteration 198

Response:  1
Iteration 199

Response:  1

In [72]:
predictions

[' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' ________________',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1',
 ' 1']

In [73]:
predictions = [x.strip() for x in predictions]
predictions

['1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '________________',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1']

In [74]:
predictions = ['A' if x =='1' else 'Unknown' for x in predictions]
predictions

['A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'Unknown',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A',
 'A']

In [75]:
print(classification_report(true_answers,predictions,zero_division=0))

              precision    recall  f1-score   support

           A       0.20      1.00      0.33        39
           B       0.00      0.00      0.00        41
           C       0.00      0.00      0.00        40
           D       0.00      0.00      0.00        37
           E       0.00      0.00      0.00        43
     Unknown       0.00      0.00      0.00         0

    accuracy                           0.20       200
   macro avg       0.03      0.17      0.05       200
weighted avg       0.04      0.20      0.06       200