# Evaluation on Gemma-3-4b-it using FLORES+ benchmark for translation tasks

In [1]:
!pip install bitsandbytes

Collecting bitsandbytes
  Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.9.0+cu128)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.20.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.13.1.3)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)
Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl (59.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.1/59.1 MB 13.9 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.49.1

In [2]:
!pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (1.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.20.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.5.4)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.21.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.1.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.22.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface-hub>=0.7.0->evaluate) (8.3.1)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 9.1 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [3]:
!pip install sacrebleu

Collecting sacrebleu
  Downloading sacrebleu-2.6.0-py3-none-any.whl.metadata (39 kB)
Collecting portalocker (from sacrebleu)
  Downloading portalocker-3.2.0-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (2025.11.3)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (0.9.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (2.0.2)
Collecting colorama (from sacrebleu)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (6.0.2)
Downloading sacrebleu-2.6.0-py3-none-any.whl (100 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 11.5 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading portalocker-3.2.0-py3-none-any.whl (22 kB)
Installing collected packages: portalocker, colorama, sacrebleu
Successfully installed colorama-0.4.6 portalocker-3.2.0 sacrebleu-2.6.0

In [4]:
import torch
from datasets import load_dataset
import pandas as pd
import sacrebleu
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from evaluate import load

In [5]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [6]:
from huggingface_hub import login
login()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [7]:
ds_mkd = load_dataset("openlanguagedata/flores_plus", "mkd_Cyrl")

README.md:   0%|          | 0.00/73.9k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/224 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/219 [00:00<?, ?it/s]

mkd_Cyrl.jsonl:   0%|          | 0.00/535k [00:00<?, ?B/s]

mkd_Cyrl.jsonl:   0%|          | 0.00/559k [00:00<?, ?B/s]

Generating dev split: 0 examples [00:00, ? examples/s]

Generating devtest split: 0 examples [00:00, ? examples/s]

In [8]:
ds_eng = load_dataset("openlanguagedata/flores_plus", "eng_Latn")

Resolving data files:   0%|          | 0/224 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/219 [00:00<?, ?it/s]

eng_Latn.jsonl:   0%|          | 0.00/423k [00:00<?, ?B/s]

eng_Latn.jsonl:   0%|          | 0.00/440k [00:00<?, ?B/s]

Generating dev split: 0 examples [00:00, ? examples/s]

Generating devtest split: 0 examples [00:00, ? examples/s]

In [9]:
ds_mkd

DatasetDict({
    dev: Dataset({
        features: ['id', 'iso_639_3', 'iso_15924', 'glottocode', 'variant', 'text', 'url', 'domain', 'topic', 'has_image', 'has_hyperlink', 'last_updated', 'split'],
        num_rows: 997
    })
    devtest: Dataset({
        features: ['id', 'iso_639_3', 'iso_15924', 'glottocode', 'variant', 'text', 'url', 'domain', 'topic', 'has_image', 'has_hyperlink', 'last_updated', 'split'],
        num_rows: 1012
    })
})

In [10]:
ds_eng

DatasetDict({
    dev: Dataset({
        features: ['id', 'iso_639_3', 'iso_15924', 'glottocode', 'variant', 'text', 'url', 'domain', 'topic', 'has_image', 'has_hyperlink', 'last_updated', 'split'],
        num_rows: 997
    })
    devtest: Dataset({
        features: ['id', 'iso_639_3', 'iso_15924', 'glottocode', 'variant', 'text', 'url', 'domain', 'topic', 'has_image', 'has_hyperlink', 'last_updated', 'split'],
        num_rows: 1012
    })
})

In [11]:
dataset_mkd = ds_mkd['dev'].to_pandas()
dataset_mkd

,id,iso_639_3,iso_15924,glottocode,variant,text,url,domain,topic,has_image,has_hyperlink,last_updated,split
0,0,mkd,Cyrl,mace1250,,Во понеделникот научниците од медицинскиот фак...,https://en.wikinews.org/wiki/Scientists_say_ne...,wikinews,health,yes,yes,1.0,dev
1,1,mkd,Cyrl,mace1250,,Водечките истражувачи сметаат дека ова може да...,https://en.wikinews.org/wiki/Scientists_say_ne...,wikinews,health,yes,yes,1.0,dev
2,2,mkd,Cyrl,mace1250,,JAS 39C Грипен се сруши на писта околу 9:30 am...,https://en.wikinews.org/wiki/Fighter_jet_crash...,wikinews,accident,yes,yes,1.0,dev
3,3,mkd,Cyrl,mace1250,,"Утврдено е дека пилот бил Дилокрит Патави, вод...",https://en.wikinews.org/wiki/Fighter_jet_crash...,wikinews,accident,yes,yes,1.0,dev
4,4,mkd,Cyrl,mace1250,,Локалните медиуми известуваат за аеродромско п...,https://en.wikinews.org/wiki/Fighter_jet_crash...,wikinews,accident,yes,yes,1.0,dev
...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,992,mkd,Cyrl,mace1250,,Туристичката сезона на ридските станици во гла...,https://en.wikivoyage.org/wiki/Hill_stations_i...,wikivoyage,Natural wonders/Hill stations in India,yes,no,1.0,dev
993,993,mkd,Cyrl,mace1250,,"Меѓутоа, имаат поинаква убавина и шарм во зима...",https://en.wikivoyage.org/wiki/Hill_stations_i...,wikivoyage,Natural wonders/Hill stations in India,yes,no,1.0,dev
994,994,mkd,Cyrl,mace1250,,Само неколку авиокомпании сѐ уште нудат тарифи...,https://en.wikivoyage.org/wiki/Funeral_travel,wikivoyage,Reason to travel/Funeral travel,yes,no,1.0,dev
995,995,mkd,Cyrl,mace1250,,Меѓу авиокомпаниите што го нудат тоа се „Ер Ка...,https://en.wikivoyage.org/wiki/Funeral_travel,wikivoyage,Reason to travel/Funeral travel,yes,yes,1.0,dev
996,996,mkd,Cyrl,mace1250,,"Во секој случај, мора да резервирате преку тел...",https://en.wikivoyage.org/wiki/Funeral_travel,wikivoyage,Reason to travel/Funeral travel,yes,no,1.0,dev

In [12]:
dataset_eng = ds_eng['dev'].to_pandas()
dataset_eng

,id,iso_639_3,iso_15924,glottocode,variant,text,url,domain,topic,has_image,has_hyperlink,last_updated,split
0,0,eng,Latn,stan1293,,"On Monday, scientists from the Stanford Univer...",https://en.wikinews.org/wiki/Scientists_say_ne...,wikinews,health,yes,yes,1.0,dev
1,1,eng,Latn,stan1293,,Lead researchers say this may bring early dete...,https://en.wikinews.org/wiki/Scientists_say_ne...,wikinews,health,yes,yes,1.0,dev
2,2,eng,Latn,stan1293,,The JAS 39C Gripen crashed onto a runway at ar...,https://en.wikinews.org/wiki/Fighter_jet_crash...,wikinews,accident,yes,yes,1.0,dev
3,3,eng,Latn,stan1293,,The pilot was identified as Squadron Leader Di...,https://en.wikinews.org/wiki/Fighter_jet_crash...,wikinews,accident,yes,yes,1.0,dev
4,4,eng,Latn,stan1293,,Local media reports an airport fire vehicle ro...,https://en.wikinews.org/wiki/Fighter_jet_crash...,wikinews,accident,yes,yes,1.0,dev
...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,992,eng,Latn,stan1293,,The tourist season for the hill stations gener...,https://en.wikivoyage.org/wiki/Hill_stations_i...,wikivoyage,Natural wonders/Hill stations in India,yes,no,1.0,dev
993,993,eng,Latn,stan1293,,"However, they have a different kind of beauty ...",https://en.wikivoyage.org/wiki/Hill_stations_i...,wikivoyage,Natural wonders/Hill stations in India,yes,no,1.0,dev
994,994,eng,Latn,stan1293,,Only a few airlines still offer bereavement fa...,https://en.wikivoyage.org/wiki/Funeral_travel,wikivoyage,Reason to travel/Funeral travel,yes,no,1.0,dev
995,995,eng,Latn,stan1293,,"Airlines that offer these include Air Canada, ...",https://en.wikivoyage.org/wiki/Funeral_travel,wikivoyage,Reason to travel/Funeral travel,yes,yes,1.0,dev
996,996,eng,Latn,stan1293,,"In all cases, you must book by phone directly ...",https://en.wikivoyage.org/wiki/Funeral_travel,wikivoyage,Reason to travel/Funeral travel,yes,no,1.0,dev

In [13]:
text_mkd = dataset_mkd['text'].values.tolist()[:100]
text_eng = dataset_eng['text'].values.tolist()[:100]

In [14]:
len(text_mkd)

100

In [15]:
len(text_eng)

100

In [16]:
text_mkd[:10]

['Во понеделникот научниците од медицинскиот факултет на Универзитетот Стенфорд објавија дека измислиле нова алатка за дијагностицирање со којашто се подредуваат клетките според типови: се работи за мал чип за печатење кој може да се произведе со помош на стандардни инк-џет печатачи, и тоа по цена од околу еден американски цент.',
 'Водечките истражувачи сметаат дека ова може да доведе до рано откривање на рак, туберколоза, ХИВ и маларија кај пациенти кои живеат во земји со низок животен стандард, каде стапката на преживување од болести како рак на дојка може да биде двојно пониска отколку во побогатите држави.',
 'JAS 39C Грипен се сруши на писта околу 9:30 am по локално време (2:30 UTC) и експлодираше, поради што аеродромот е затворен за комерцијални летови.',
 'Утврдено е дека пилот бил Дилокрит Патави, водачот на ескадрилата.',
 'Локалните медиуми известуваат за аеродромско противпожарно возило кое се превртело додека пожарникарите во него одговарале на повик.',
 '28-годишниот Видал од Севиља се придружи на екипата на Барселона.',
 'Откако се пресели во главниот град на Каталонија Видал одигра 49 натпревари за клубот.',
 'Протестот започна околу 11:00 часот по локално време (UTC+1) во Вајтхол, на спротивната страна од влезот чуван од полицијата на Даунинг Стрит, службената резиденција на премиерот.',
 'Веднаш по 11:00 часот демонстрантите го блокираа сообраќајот кон север во Вајтхол.',
 'Во 11:20 часот, полицијата побара од протестантите да повлечат на тротоарот, наведувајќи дека тие треба да ги урамнотежат правото на протестирање со застојот во сообраќајот.']

In [17]:
text_eng[:10]

['On Monday, scientists from the Stanford University School of Medicine announced the invention of a new diagnostic tool that can sort cells by type: a tiny printable chip that can be manufactured using standard inkjet printers for possibly about one U.S. cent each.',
 'Lead researchers say this may bring early detection of cancer, tuberculosis, HIV and malaria to patients in low-income countries, where the survival rates for illnesses such as breast cancer can be half those of richer countries.',
 'The JAS 39C Gripen crashed onto a runway at around 9:30 am local time (0230 UTC) and exploded, closing the airport to commercial flights.',
 'The pilot was identified as Squadron Leader Dilokrit Pattavee.',
 'Local media reports an airport fire vehicle rolled over while responding.',
 '28-year-old Vidal had joined Barça three seasons ago, from Sevilla.',
 'Since moving to the Catalan-capital, Vidal had played 49 games for the club.',
 "The protest started around 11:00 local time (UTC+1) on Whitehall opposite the police-guarded entrance to Downing Street, the Prime Minister's official residence.",
 'Just after 11:00, protesters blocked traffic on the northbound carriage in Whitehall.',
 'At 11:20, the police asked the protesters to move back on to the pavement, stating that they needed to balance the right to protest with the traffic building up.']

In [18]:
model_name = "google/gemma-3-4b-it"

In [19]:
bitsandbytes_config = BitsAndBytesConfig(load_in_4bit=True,
                                         bnb_4bit_compute_dtype=torch.float16,
                                         bnb_4bit_quant_type='nf4',
                                         bnb_4bit_use_double_quant=True)

In [20]:
tokenizer = AutoTokenizer.from_pretrained(model_name,padding_side="left")
model = AutoModelForCausalLM.from_pretrained(model_name,
                                             quantization_config=bitsandbytes_config,
                                             device_map="auto",
                                             offload_folder="offload")

config.json:   0%|          | 0.00/855 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.16M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/33.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/90.6k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/883 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/215 [00:00<?, ?B/s]

In [21]:
def get_prompt_mkd(instruction,text,language):
  return f"{instruction}\nТекст:{text}\nОдговор ({language}):"

In [22]:
def get_prompt_srb(instruction,text,language):
  return f"{instruction}\nТекст:{text}\nОдговор ({language}):"

In [23]:
def get_prompt_bug(instruction,text,language):
  return f"{instruction}\nТекст:{text}\nОтговор ({language}):"

In [24]:
def get_prompt_eng(instruction,text,language):
  return f"{instruction}\nText:{text}\nResponse ({language}):"

In [26]:
def batch_translate(texts,instruction, batch_size=8, max_new_tokens=256,lang_code="eng",language="English"):
    all_preds = []
    tokenizer.pad_token = tokenizer.eos_token
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]

        if lang_code=="mkd":
          prompts = [[{"role": "user", "content":get_prompt_mkd(instruction,t,language)}] for t in batch]
        elif lang_code == "bug":
          prompts = [[{"role": "user", "content":get_prompt_bug(instruction,t,language)}] for t in batch]
        elif lang_code == "srb":
          prompts = [[{"role": "user", "content":get_prompt_srb(instruction,t,language)}] for t in batch]
        else:
          prompts = [[{"role": "user", "content":get_prompt_eng(instruction,t,language)}] for t in batch]

        inputs = tokenizer.apply_chat_template(
            prompts,
            add_generation_prompt=True,
            tokenize=True,
            return_tensors="pt",
            padding=True,
            truncation=True
        ).to(model.device)

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=max_new_tokens,
                temperature=0.0,
                do_sample=False,
                repetition_penalty=1.1,
                pad_token_id=tokenizer.eos_token_id,
                eos_token_id=tokenizer.eos_token_id
            )

        input_len = inputs.input_ids.shape[1]
        decoded = tokenizer.batch_decode(outputs[:, input_len:], skip_special_tokens=True)

        for translation in decoded:
            print(f"Batch {i}")
            clean_translation = translation.split("\n")[0].strip()
            all_preds.append(clean_translation)
            print(f"Result: {clean_translation}\n")

    return all_preds

In [27]:
from nltk.tokenize import sent_tokenize

def first_sentence(text):
    sents = sent_tokenize(text)
    return sents[0] if sents else text

In [28]:
bleu = load('bleu')

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading extra modules:   0%|          | 0.00/1.55k [00:00<?, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

## Few-Shot Mono-lingual prompt (MKD->ENG)

In [29]:
instruction = f"""Преведи го следниот текст од **Македонски** во **Англиски**.Само испечати го преводот на англиски. Не додавај никакви објаснувања или дополнителни примери.
  Пример 1
  Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
  Одговор (Англиски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
  Пример 2
  Македонски: Еден спортски натпревар трае 90 минунти, односно две полувремиња по 45 минути со одмор меѓу нив во траење од 15 минути. Ако има подолги прекини во играта, таа се продолжува така што се надополнува изгубеното време.
  Одговор (Англиски): A sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.
  Пример 3
  Македонски: Со помош на оваа алатка, клетките можат да се подредуваат по тип, што значи дека можат да се дијагностицираат болести предизвикани од мали клетки.
  Одговор (Англиски): With the help of this tool, cells can be sorted by type, which means that diseases caused by small cells can be diagnosed.
  Пример 4
  Македонски: Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
  Одговор (Англиски): This study focuses on the development of new methods for data analysis.
  Пример 5
  Македонски: Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.
  Одговор (Англиски): In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
"""

In [30]:
predictions_eng = batch_translate(text_mkd,instruction,max_new_tokens=128,lang_code="mkd",language="Англиски")

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Batch 0
Result: On Monday, scientists from Stanford University’s medical school announced that they had invented a new tool for diagnosing purposes, allowing cells to be sorted by type. It is a small chip for printing that can be produced using standard ink-jet printers, and costs approximately one US cent.

Batch 0
Result: Leading researchers believe this could lead to early detection of cancer, tuberculosis, HIV, and malaria among patients living in low-income countries, where survival rates from diseases such as breast cancer may be twice as low as in wealthier nations.

Batch 0
Result: The JAS 39 Gripen crashed on the runway around 9:30 AM local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights.

Batch 0
Result: It was ascertained that the pilot was Dilokrit Patavi, the squadron leader.

Batch 0
Result: Local media report on an airport fire truck that overturned while firefighters responded to the call.

Batch 0
Result: 28-year-old Vidal from Seville joined Barcelona’s team.

Batch 0
Result: After moving to the capital of Catalonia, Vidal played 49 matches for the club.

Batch 0
Result: The protest began around 11:00 AM local time (UTC+1) in Whitehall, across from the entrance guarded by police near Downing Street, the prime minister’s official residence.

Batch 8
Result: Immediately after 11:00 AM, protesters blocked traffic heading north towards Whitehall.

Batch 8
Result: At 11:20 AM, the police requested protesters to move off the sidewalk, citing the need to balance the right to protest with traffic congestion.

Batch 8
Result: Around 11:29 AM, the protest moved onto Whitehall, near Trafalgar Square, passing by Strand, going past Aldwych and through Kingsway towards Holborn, where the Conservative Party was holding its Spring Forum at the Grand Connaught Rooms hotel.

Batch 8
Result: Nadal’s personal record against the Canadian is 7 - 2.

Batch 8
Result: Recently lost to Ronnić at the Brisbane Open.

Batch 8
Result: Nadal won 88% of the points on the net in the match, earning 76 points in the first service.

Batch 8
Result: After the match, the King of the land said: “I am simply very excited to be back in the final rounds of the most important events. I’m here to try and win.”

Batch 8
Result: "The Panama Papers" is an all-encompassing term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were disclosed in print during spring 2016.

Batch 16
Result: According to documents, fourteen banks helped wealthy clients hide billions of dollars in assets in order to conceal taxes and avoid other laws.

Batch 16
Result: The British newspaper “The Guardian” reported that “Deutsche Bank” controlled approximately one-third of the 1200 provisional companies used to achieve that.

Batch 16
Result: This led to protests around the world, a certain number of criminal prosecutions, and the resignations of the prime ministers of Iceland and Pakistan.

Batch 16
Result: Born in Hong Kong, Stu studied at New York University and Harvard Law School, and he had a permanent American “green card.”

Batch 16
Result: He implicitly suggested during the elections that Ma could escape the country in case of a crisis.

Batch 16
Result: He also claimed that Photogenic Ma was more about style than substance.

Batch 16
Result: Despite these accusations, Ma easily won with a platform representing closer ties with continental China.

Batch 16
Result: Today’s player of the day is Alex Ovechkin from the Washington Capitals team.

Batch 24
Result: Washington defeated Atlanta Thrashers 5-3, scoring 2 goals and recording 2 assists.

Batch 24
Result: Ovechkin’s first assist was for Niklas Bäckström’s winning goal.

Batch 24
Result: His second goal of the evening was the 60th of the season, making him the first player since the 1995-96 season to score 60 or more goals in a single season, a record previously held by Jaromir Jagr and Mario Lemieux.

Batch 24
Result: Batten was ranked 190th on the list of the 400 richest Americans in 2008 with a fortune estimated at $2.3 billion.

Batch 24
Result: He graduated from Virginia College of Arts and Sciences in 1950 and was recognized as an important benefactor to the institution.

Batch 24
Result: The Iraqi prison “Abu Ghraib” was set ablaze during a riot.

Batch 24
Result: The prison became widely known after allegations of abuse of prisoners were uncovered following its takeover by American military forces.

Batch 24
Result: Peugeot Junior collided with the Singapore Grand Prix 2008 immediately after Fernando Alonso’s early pit stop, followed by the deployment of the safety car.

Batch 32
Result: While Boldyke waited for Alonso to go fill up the safety car fuel, he took over the lead to secure the victory.

Batch 32
Result: Pierre Gasly was released after the Hungarian Grand Prix in 2009.

Batch 32
Result: At exactly 8:46 AM, there was a commotion throughout the city, marking precisely the moment when the first airplane hit its target.

Batch 32
Result: Two beams of light were set to shine towards the night sky.

Batch 32
Result: Construction is ongoing for five new cloud centers at the location, with a transportation center and memorial park in the middle.

Batch 32
Result: PBS series has more than two dozen Emmy Awards and is broadcast only by Sesame Street and Mr. Rogers’ Neighborhood.

Batch 32
Result: Each episode of the show focused on a topic from a specific book, and then that topic was explored through multiple stories.

Batch 32
Result: Additionally, each show will provide book recommendations that every child should request when visiting the library.

Batch 40
Result: John Grant, from WNED Buffalo (“Reading Rainbow’s home base”), said, “Reading Rainbow taught children why they should read… a love of reading – [the series] encourages children to pick up a book and read.”

Batch 40
Result: Some people, including John Grant, believe that the church-financier and the change of philosophy regarding educational programs contributed to the interruption of the broadcast.

Batch 40
Result: The storm was located 645 miles (1040 km) west of the Green Reef Islands and is likely to dissipate before posing any threat to land areas, meteorologists say.

Batch 40
Result: Currently, Fred is covering winds blowing at 105 miles per hour (165 km/h) and moving towards the northwest.

Batch 40
Result: Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic since satellite imagery was first developed, but it is only the third major hurricane recorded east of 35° W.

Batch 40
Result: On September 24, 1759, Arthur Ginny signed a 9,000-year contract for St. James’s Gate Brewery in Dublin, Ireland.

Batch 40
Result: 250 years later, “Genis” had grown into a global business with an annual turnover of 10 billion euros (14.7 billion dollars).

Batch 40
Result: Joni Ridders, a driver for the A1GP team from New Zealand, today created a historic event by legally crossing the Auckland Harbour Bridge in New Zealand at the fastest speed ever recorded.

Batch 48
Result: Mr. Reed managed to drive the New Zealand A1GP car, Black Beauty, across the bridge seven times at speeds over 160 km/h.

Batch 48
Result: The New Zealand police faced a problem when using radar to determine speeds to see how fast Mr. Reed was traveling, due to the height of Black Diamond. The only time the police managed to catch Mr. Reed was when he slowed down to 160 km/h.

Batch 48
Result: In the last 3 months, over 80 detainees have been released from the detention center without being formally charged.

Batch 48
Result: In April of this year, Judge Glin issued an order for a temporary restriction against the institution for expedited release of those detained for more than 24 hours after arrest who had not been heard by a judicial commissioner.

Batch 48
Result: The commissioner determines bail, if allowed, and formalizes the charges filed by the officer who conducted the arrests. Subsequently, the charges are entered into the state computer system where the case is tracked.

Batch 48
Result: This hearing will determine the date for trial for the defendant to expedite the verdict.

Batch 48
Result: Peter Costello, the Australian Treasurer and the man with the greatest potential to replace Prime Minister John Howard as leader of the Liberal Party, expressed his support for the nuclear energy industry in Australia.

Batch 48
Result: Mr. Kostelo stated that when nuclear reactors become economically sustainable, Australia will begin using them.

Batch 56
Result: “If we’re talking commercially, we need to have it. I.e., there’s essentially no objection to nuclear energy,” Mr. Costelo said.

Batch 56
Result: According to Ansa, “the police were concerned about several high-level attacks they feared could trigger a succession war in full swing.”

Batch 56
Result: The police announced that Lo Piccolo had control because he was Provenzano’s right-hand man in Palermo, and his greater experience earned him respect from the older generation of bosses who followed Provenzano’s policy of remaining as hidden as possible while strengthening their network of authority.

Batch 56
Result: These bosses were apprehended by Provenzano when he ended the war sparked by Rina against the state that took the lives of “crusaders” of the mafia, Giovanni Falcone and Paolo Borsellino in 1992.

Batch 56
Result: The CEO of Apple, Steve Jobs, unveiled the device onstage while pulling out an iPhone from his jeans pocket.

Batch 56
Result: During his 2-hour speech, he stated that “Apple will invent the phone again, Today we will create history.”

Batch 56
Result: Brazil is the largest Roman Catholic country in the world, and the Roman Catholic Church is constantly opposed to the legalization of same-sex marriage in the country.

Batch 56
Result: The Brazilian State Congress has been debating the legalization of such civil unions for ten years; nevertheless, such marriages are currently legal only in Rio Grande do Sul.

Batch 64
Result: The original draft law was drafted by Marta Suplicio, the former mayor of São Paulo. The proposed legislation, after her modifications, is now in the hands of Roberto Jefferson.

Batch 64
Result: Protestants hope to collect 1.2 million signatures for the petition they will present to Congress in November.

Batch 64
Result: Following it becoming apparent that many families were seeking legal assistance to deal with incontinence, a meeting was held on March 20th at the Community Legal Center in East Bay for victims of housing fraud.

Batch 64
Result: When the residents started sharing what had happened to them, it became clear to most of the involved families that Caroline Wilson from DHA had stolen their security deposits and had fled the city.

Batch 64
Result: Residents of Lockwood Gardens believe that 40 families or more may be facing eviction because they’ve learned that the police force OHA is investigating other properties for public housing in Auckland that may be involved in residential fraud.

Batch 64
Result: Bento canceled his performance that was supposed to take place at the military memorial stadium on Maui, where 9000 fans were expected to attend, and apologized to the fans.

Batch 64
Result: Benddo Management Inc.’s management company, HK Management Inc., did not issue an official statement regarding the reasons for the cancellation on September 20th, but the following day stated that it was due to a logistical problem.

Batch 64
Result: The well-known Greek lawyers, Sakis K€haioglou and George Nikolopoulos, are imprisoned in Korydallos Prison in Athens after being found guilty of bribery and corruption.

Batch 72
Result: As a result, a major scandal erupted within the Greek legal community following the revelation of illegal activities carried out by judges, lawyers, attorneys, and defenders over the previous years.

Batch 72
Result: Several weeks ago, following information published by journalist Makis Triantafilopoulos in his popular television show “Zoungla” on Alpha TV, MP and lawyer Petros Mantouvalos resigned because members of his cabinet were involved in accepting bribes and corruption.

Batch 72
Result: In addition, Supreme Court Justice Evangelor Kalusis is in custody due to corruption and misconduct.

Batch 72
Result: Roberts steadfastly refused to discuss his beliefs about when life begins, which is an important question considering the ethics of abortion, stating that it would be unethical to comment on the specific details of potential cases.

Batch 72
Result: However, she reaffirmed her previous statement that Roe v. Wade is “the standard,” emphasizing the importance of consistent rulings from the Supreme Court.

Batch 72
Result: He also confirmed his belief in the undisputed right to privacy, which influenced Roe’s decision.

Batch 72
Result: Maruchidore finished at the top of the table, six points ahead of Nusa, who is second.

Batch 72
Result: The two teams met in the grand semi-final, where Nusa won by 11 points difference.

Batch 80
Result: Marudzor defeated Kabultur in the preliminary final.

Batch 80
Result: Hesperonychus elizabethae is a species of the family Dromaeosauridae closely related to Velociraptor.

Batch 80
Result: It is believed that this warm-blooded bird-grabbler with feathers upright along its body standing on two legs, like claws such as those of Velociraptor.

Batch 80
Result: His second claw was larger, giving rise to the name Hesperonychus, meaning “western claw.”

Batch 80
Result: Extreme weather conditions, including breaking frost, are hindering rescue efforts.

Batch 80
Result: Pitmman indicates that the conditions will not improve until next week.

Batch 80
Result: According to Pittman, the thickness and extent of the sea ice is the worst it’s ever been for seal hunters in the past 15 years.

Batch 80
Result: Today, in Red Lake County, after the funerals of Jeff Weise and three of the nine victims, news spread that another student had been arrested in connection with the school shooting from March 21st.

Batch 88
Result: Government officials have not made many official statements, except to confirm today’s arrest.

Batch 88
Result: However, a source familiar with the investigation into “Minneapolis Star-Tribune” stated that it was Louis Jurden, the 16-year-old son of the tribal president of Red Lake, Floyd Jurden.

Batch 88
Result: Currently, it is unknown what charges will be filed, nor how the authorities came upon the boy, but proceedings against the minor have begun in federal court.

Batch 88
Result: Lodin also stated that officials decided to cancel the second round of elections to save Afghans from expenses and to avoid security risks associated with further voting.

Batch 88
Result: Diplomats stated they had found enough ambiguities in the Afghan constitution to determine that a second round of elections was unnecessary.

Batch 88
Result: This contradicts previous statements, which stated that canceling the second round would be unconstitutional.

Batch 88
Result: The aircraft was headed towards Irkutsk and was being piloted by domestic troops.

Batch 88
Result: An investigation was launched to examine it.

Batch 96
Result: II-76 was the largest component of both the Russian and Soviet military since the 1970s, which suffered a serious accident in Russia last month.

Batch 96
Result: On October 7th, the engine detached during takeoff, without any injuries. After this accident, Russia briefly landed the Il-76s.

Batch 96
Result: 800 miles of the Trans-Alaska pipeline were shut down following thousands of severe oil storms south of Ferbence, Alaska.

Batch 96
Result: Following a routine test of the fire suppression system, a power outage occurred, causing valves to open and raw oil to spill near Pump Station 9 at Fort Gril.

In [31]:
references = [[ref] for ref in text_eng]
references[:10]

[['On Monday, scientists from the Stanford University School of Medicine announced the invention of a new diagnostic tool that can sort cells by type: a tiny printable chip that can be manufactured using standard inkjet printers for possibly about one U.S. cent each.'],
 ['Lead researchers say this may bring early detection of cancer, tuberculosis, HIV and malaria to patients in low-income countries, where the survival rates for illnesses such as breast cancer can be half those of richer countries.'],
 ['The JAS 39C Gripen crashed onto a runway at around 9:30 am local time (0230 UTC) and exploded, closing the airport to commercial flights.'],
 ['The pilot was identified as Squadron Leader Dilokrit Pattavee.'],
 ['Local media reports an airport fire vehicle rolled over while responding.'],
 ['28-year-old Vidal had joined Barça three seasons ago, from Sevilla.'],
 ['Since moving to the Catalan-capital, Vidal had played 49 games for the club.'],
 ["The protest started around 11:00 local time (UTC+1) on Whitehall opposite the police-guarded entrance to Downing Street, the Prime Minister's official residence."],
 ['Just after 11:00, protesters blocked traffic on the northbound carriage in Whitehall.'],
 ['At 11:20, the police asked the protesters to move back on to the pavement, stating that they needed to balance the right to protest with the traffic building up.']]

In [34]:
bleu.compute(predictions=predictions_eng, references=references)

{'bleu': 0.2996014953454786,
 'precisions': [0.6294277929155313,
  0.3689752936411503,
  0.23427606585056987,
  0.1480828558836492],
 'brevity_penalty': 1.0,
 'length_ratio': 1.025958466453674,
 'translation_length': 2569,
 'reference_length': 2504}

In [35]:
chrf_score = sacrebleu.corpus_chrf(predictions_eng, references)
print(f"chrF: {chrf_score.score:.2f}")

chrF: 54.08

## Few-Shot Cross-lingual prompt (MKD->ENG) in english language

In [36]:
instruction = f"""Translate the following text from **Macedonian** to **English**. Only output the translation. Do not add explanations.
  Example 1
  Macedonian: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
  Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
  Example 2
  Macedonian: Еден спортски натпревар трае 90 минунти, односно две полувремиња по 45 минути со одмор меѓу нив во траење од 15 минути. Ако има подолги прекини во играта, таа се продолжува така што се надополнува изгубеното време.
  Response (English): A sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.
  Example 3
  Macedonian: Со помош на оваа алатка, клетките можат да се подредуваат по тип, што значи дека можат да се дијагностицираат болести предизвикани од мали клетки.
  Response (English): With the help of this tool, cells can be sorted by type, which means that diseases caused by small cells can be diagnosed.
  Example 4
  Macedonian: Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
  Response (English): This study focuses on the development of new methods for data analysis.
  Example 5
  Macedonian: Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.
  Response (English): In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
"""

In [37]:
predictions_eng = batch_translate(text_mkd,instruction,max_new_tokens=128)

Batch 0
Result: On Monday, scientists from Stanford University’s medical school announced that they had invented a new tool for diagnosing, whereby cells are sorted according to types: it’s a small chip for printing that can be produced using standard ink-jet printers, and at a price of about one US cent.

Batch 0
Result: Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV, and malaria among patients living in low-income countries, where the survival rate of diseases such as breast cancer may be twice as low as in wealthier nations.

Batch 0
Result: A JAS 39C Gripen crashed on the runway around 9:30 AM local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights.

Batch 0
Result: It has been determined that the pilot was Dilokrit Patavi, the squadron leader.

Batch 0
Result: Local media report on an airport fire truck that overturned while firefighters responded to the call.

Batch 0
Result: 28-year-old Vidal from Seville joined Barcelona’s team.

Batch 0
Result: After moving to the capital of Catalonia, Vidal played 49 matches for the club.

Batch 0
Result: The protest began around 11:00 AM local time (UTC+1) in Whitehall, across from the entrance guarded by police on Downing Street, the official residence of the prime minister.

Batch 8
Result: Immediately after 11:00 AM, the protesters blocked traffic heading north towards Whitehall.

Batch 8
Result: At 11:20 AM, the police requested the protesters to move off the sidewalk, citing that they needed to balance the right to protest with traffic congestion.

Batch 8
Result: Around 11:29 AM, the protest moved towards Whitehall, near Trafalgar Square, along Strand, passing by Aldwych and through Kingsway to Holborn, where the Conservative Party was holding its Spring Forum at the Grand Connaught Rooms hotel.

Batch 8
Result: Rafael Nadal’s personal record against the Canadian is 7 - 2.

Batch 8
Result: Recently, he lost to Raninik at the Brisbane Open.

Batch 8
Result: Nadal won 88% of the points on the net in the match, earning 76 points in the first service.

Batch 8
Result: After the competition, the King of the land said: “I am simply very excited to be back in the final rounds of the most important events. I’m here to try and win.”

Batch 8
Result: “Panama Papers” is an all-encompassing term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were disclosed in print during the spring of 2016.

Batch 16
Result: According to the documents, fourteen banks helped wealthy clients hide assets worth billions of American dollars in order to conceal taxes and avoid other laws.

Batch 16
Result: The British newspaper “The Guardian” reported that “Deutsche Bank” controlled approximately one-third of the 1200 provisional companies used to achieve that.

Batch 16
Result: This led to protests organized throughout the world, a certain number of criminal prosecutions, and the prime ministers of Iceland and Pakistan resigned.

Batch 16
Result: Born in Hong Kong, he studied at New York University and Harvard Law School, and had a permanent American “green card”.

Batch 16
Result: He implied during the elections that Ma could escape the country in case of a crisis.

Batch 16
Result: He also claimed that Photogenic Ma was more about style than substance.

Batch 16
Result: Despite these accusations, Ma easily won with a platform representing closer ties with continental China.

Batch 16
Result: Today’s player of the day is Alex Ovechkin from the Washington Capitals team.

Batch 24
Result: There were 2 goals and 2 assists in Washington’s 5-3 victory over the Atlanta Thrashers.

Batch 24
Result: Ovechkin’s first assist of the night was for the winning goal by rookie Nicklas Bäckström.

Batch 24
Result: His second goal of the evening was the 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96 when Jaromir Jagr and Mario Lemieux set that record.

Batch 24
Result: Batten was ranked 190th on the list of the 400 richest Americans for 2008 with a fortune estimated at $2.3 billion.

Batch 24
Result: He graduated from the College of Arts and Sciences at Virginia University in 1950 and was recognized as an important donor to the institution.

Batch 24
Result: The Iraqi prison “Abu Graib” was set ablaze during a riot.

Batch 24
Result: The prison became quietly famous after abuse of prisoners was revealed following its takeover by American military forces.

Batch 24
Result: Pierre Junior collided with the Singapore Grand Prix 2008 immediately after Fernando Alonso’s early pit stop, followed by the deployment of the safety car.

Batch 32
Result: While the Bolides ahead of Alonso went to fill up fuel in the security car, he took over the lead to come out victorious.

Batch 32
Result: Pierre Gasly was released after the Hungarian Grand Prix in 2009.

Batch 32
Result: At exactly 8:46 AM, there was a commotion throughout the city, marking precisely the moment when the first airplane hit its target.

Batch 32
Result: Two beams of light were set to shine towards the night sky.

Batch 32
Result: The construction is ongoing for five new cloud centers at the location, with a transportation center and memorial park in the middle.

Batch 32
Result: PBS series has more than two dozen Emmy Awards and is broadcast only by Sesame Street and Mr. Rogers’ Neighborhood.

Batch 32
Result: Each episode of the show focused on a topic from a specific book, and then that topic was explored through multiple stories.

Batch 32
Result: Also, each show will provide recommendations for books that every child should request when going to the library.

Batch 40
Result: John Grant, from WNED Buffalo (“Reading Rainbow’s station host”), said, “Reading Rainbow taught children why they should read… a love of reading – [the series] encourages children to take a book and read.”

Batch 40
Result: Some people, including John Grant, believe that the church-financier and the change of philosophy regarding educational programs contributed to the interruption of the broadcast.

Batch 40
Result: Severe weather has been located 645 miles (1040 km) west of the Green Bay islands and will likely dissipate before posing any threat to land areas, meteorologists say.

Batch 40
Result: Currently, Fred is covering winds blowing at speeds of 105 miles per hour (165 km/h) and moving towards the northwest.

Batch 40
Result: Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic since the advent of satellite imagery, but it’s only the third major hurricane recorded east of 35° W.

Batch 40
Result: On September 24, 1759, Arthur Ginny signed a 9,000-year contract for St. James’s Gate Brewery in Dublin, Ireland.

Batch 40
Result: 250 years later, “Genis” grew into a global business with an annual turnover of 10 billion euros (14.7 billion dollars).

Batch 40
Result: Joni Ridders, a transporter for the A1GP team from New Zealand, today created a historical event by legally crossing the Auckland Harbour Bridge in New Zealand at record speed.

Batch 48
Result: Mr. Reed managed to drive the New Zealand A1GP car, Black Beauty, at speeds over 160 km/h seven times across the bridge.

Batch 48
Result: The New Zealand police are facing a problem when using radar to determine speeds to see how fast Mr. Reed is moving, due to the height of Black Diamond. The only time the police managed to catch Mr. Reed was when he slowed down to 160 km/h.

Batch 48
Result: In the last 3 months, over 80 detainees have been released from the Detention Center without being formally charged.

Batch 48
Result: In April of this year, Judge Glin issued an order for a temporary restriction against the institution for accelerating the release of those detained for more than 24 hours after arrest who had not been heard by a judicial commissioner.

Batch 48
Result: The commissioner determines bail, if allowed, and formalizes the charges filed by the official who conducted the arrests. Subsequently, the charges are entered into the state computer system where the case is tracked.

Batch 48
Result: The date for trial will be determined in this hearing for the defendant.

Batch 48
Result: Peter Costello, the Australian Minister of Finance and the man with the greatest potential to replace Prime Minister John Howard as leader of the Liberal Party, expressed his support for the nuclear energy industry in Australia.

Batch 48
Result: Mr. Costello said that when nuclear reactors become economically sustainable, Australia will begin using them.

Batch 56
Result: “If we’re talking commercially, we need to have it. I.e., in principle, there’s no objection to nuclear energy,” Mr. Kostelo said.

Batch 56
Result: According to Ansa, “the police were concerned about several high-level attacks they feared could trigger a succession war in full swing.”

Batch 56
Result: The police announced that Lo Piccolo had control because he was Provenzano’s right hand man in Palermo, and his greater experience earned respect from the older generation bosses who followed Provenzano’s policy of remaining as hidden as possible while strengthening their network of authority.

Batch 56
Result: These bosses were apprehended by Provenzano when he ended the war sparked by Rina against the state that took the lives of “crusaders” of the mafia, Giovanni Falcone and Paolo Borsellino in 1992.

Batch 56
Result: The CEO of Apple, Steve Jobs, unveiled the device onstage while pulling out an iPhone from his jeans pocket.

Batch 56
Result: During his 2-hour speech, he stated that “Apple will invent the phone again. Today we will create history.”

Batch 56
Result: Brazil is the largest Roman Catholic country in the world, and the Roman Catholic Church is constantly opposed to the legalization of same-sex marriage in the country.

Batch 56
Result: The Brazilian National Congress has been debating the legalization of civil unions for ten years; nevertheless, such marriages are currently legal only in Rio Grande do Sul.

Batch 64
Result: The original draft law was drafted by Marta Suplici, the former mayor of São Paulo. The proposed legislation, after her modifications, is now in the hands of Roberto Jefferson.

Batch 64
Result: Protestants hope to collect 1.2 million signatures for the petition they will present to Congress in November.

Batch 64
Result: After it became apparent that many families were seeking legal assistance to deal with incontinence, a meeting was held on March 20th at the Community Legal Center in East Bay for victims of housing fraud.

Batch 64
Result: When the residents started sharing what had happened to them, most of the involved families suddenly realized that Caroline Wilson from DHA had stolen their security deposits and had fled the city.

Batch 64
Result: Tenants at Lockwood Gardens believe that 40 families or more may be facing eviction because they’ve learned that the police OHA is investigating other properties for public housing and could be involved in residential fraud.

Batch 64
Result: Bendo canceled his performance that was supposed to take place at the military memorial stadium on Maui, where 9000 fans were expected to attend, and apologized to the fans.

Batch 64
Result: The management company of Bendot, HK Management Inc., did not issue an official statement regarding the reasons for the cancellation on September 20th, but the next day stated that it was due to a logistical problem.

Batch 64
Result: The well-known Greek lawyers, Sakis K€haioglou and George Nikolopoulos, are imprisoned in Koridallos prison in Athens after being found guilty of bribery and corruption.

Batch 72
Result: Because of that, a major scandal arose within the Greek legal community due to the revelation of illegal actions carried out by judges, lawyers, attorneys, and defenders over the previous years.

Batch 72
Result: A few weeks ago, following information published by journalist Makis Triantafilopoulos in his popular television show “Zoungla” on Alpha TV, MP and lawyer Petros Mantouvalos resigned because members of his cabinet were involved in accepting bribes and corruption.

Batch 72
Result: In addition to that, Supreme Judge Evangelor Kalusidis is under arrest due to corruption and abuse of power.

Batch 72
Result: Roberts stubbornly refused to talk about his beliefs regarding when life begins, which is an important question considering the ethics of abortion, stating that it would be unethical to comment on the specific details of potential cases.

Batch 72
Result: However, she confirmed her previous statement that Roe v. Wade is “the standard,” emphasizing the importance of consistent rulings by the Supreme Court.

Batch 72
Result: He also confirmed that he believes in the undisputed right to privacy, which influenced Roe’s decision.

Batch 72
Result: Maruchidore finished at the top of the leaderboard, with six points ahead of Nusa, who is second place.

Batch 72
Result: The two teams met in the grand semi-final, where Nusa came out victorious with an 11-point lead.

Batch 80
Result: Then Marudikor defeated Kabultur in the preliminary final.

Batch 80
Result: Hesperonychus elizabethae is a species of the family Dromaeosauridae that is closely related to velociraptor.

Batch 80
Result: It is believed that this warm-blooded bird – a goutbird – with feathers standing upright on its two legs, like claws as seen in Velociraptor.

Batch 80
Result: His second claw was larger, giving rise to the name Hesperonychus, meaning “western claw.”

Batch 80
Result: Extreme weather conditions, including freezing frost, are hindering rescue efforts.

Batch 80
Result: Pitmān noted that the conditions will not improve until next week.

Batch 80
Result: According to Pittman, the amount and thickness of sea ice is the worst it’s ever been for seal hunters in the past 15 years.

Batch 80
Result: Today, in the Red Lake municipality, after the funerals were held for Jeff Weiss and three of the nine victims, news spread that another student had been arrested in connection with the school shooting on March 21st.

Batch 88
Result: The authorities officially said very little, except confirming today’s arrest.

Batch 88
Result: However, a source with knowledge of the “Minneapolis Star-Tribune” investigation stated that it was Louis Jurden, the 16-year-old son of the tribal president of Red Lake, Floyd Jurden.

Batch 88
Result: Currently, it is unknown what charges will be filed, nor how the authorities came to the boy, but the proceedings against the minor have begun in federal court.

Batch 88
Result: Also, Lodin stated that officials decided to cancel the second round of elections to save Afghans from expenses and to avoid security risks from further voting.

Batch 88
Result: Diplomats said they found enough ambiguities in the Afghan constitution to determine that a second round of elections was unnecessary.

Batch 88
Result: This contradicts previous statements, which stated that canceling the second round would be unconstitutional.

Batch 88
Result: The airplane was headed towards Irkutsk and was being piloted by internal troops.

Batch 88
Result: An investigation was launched to examine it.

Batch 96
Result: II-76 was the largest component in both the Russian and Soviet military since the 1970s, which recently experienced a serious accident in Russia last month.

Batch 96
Result: On October 7th, the engine detached during takeoff, without injuries. After that accident, Russia briefly landed the Il-76s.

Batch 96
Result: 800 miles of the Trans-Alaska pipeline were shut down after the expiration of thousands of oil storms south of Ferbence, Alaska.

Batch 96
Result: After a routine test of the fire suppression system, a power outage occurred which caused the pressure valves to open and raw oil to spill near pump station 9 at Fort Griley.

In [38]:
references = [[ref] for ref in text_eng]
references[:10]

[['On Monday, scientists from the Stanford University School of Medicine announced the invention of a new diagnostic tool that can sort cells by type: a tiny printable chip that can be manufactured using standard inkjet printers for possibly about one U.S. cent each.'],
 ['Lead researchers say this may bring early detection of cancer, tuberculosis, HIV and malaria to patients in low-income countries, where the survival rates for illnesses such as breast cancer can be half those of richer countries.'],
 ['The JAS 39C Gripen crashed onto a runway at around 9:30 am local time (0230 UTC) and exploded, closing the airport to commercial flights.'],
 ['The pilot was identified as Squadron Leader Dilokrit Pattavee.'],
 ['Local media reports an airport fire vehicle rolled over while responding.'],
 ['28-year-old Vidal had joined Barça three seasons ago, from Sevilla.'],
 ['Since moving to the Catalan-capital, Vidal had played 49 games for the club.'],
 ["The protest started around 11:00 local time (UTC+1) on Whitehall opposite the police-guarded entrance to Downing Street, the Prime Minister's official residence."],
 ['Just after 11:00, protesters blocked traffic on the northbound carriage in Whitehall.'],
 ['At 11:20, the police asked the protesters to move back on to the pavement, stating that they needed to balance the right to protest with the traffic building up.']]

In [39]:
bleu.compute(predictions=predictions_eng, references=references)

{'bleu': 0.3158559721082145,
 'precisions': [0.6361185983827493,
  0.37685222266720064,
  0.2503128911138924,
  0.16586852416195036],
 'brevity_penalty': 1.0,
 'length_ratio': 1.0371405750798721,
 'translation_length': 2597,
 'reference_length': 2504}

In [40]:
chrf_score = sacrebleu.corpus_chrf(predictions_eng, references)
print(f"chrF: {chrf_score.score:.2f}")

chrF: 55.34

## Few-Shot Cross-lingual prompt (MKD->ENG) in serbian language

In [41]:
instruction= f"""Преведи следећи текст са **Македонског** на **Енглески** језик.
Само испиши превод. Не додавај никаква објашњења.

Пример 1
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 2
Македонски: Еден спортски натпревар трае 90 минути, односно две полувремиња по 45 минути со одмор помеѓу нив во траење од 15 минути. Ако има подолги прекини во играта, таа се продолжува така што се надополнува изгубеното време.
Одговор (Енглески): A sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.

Пример 3
Македонски: Со помош на оваа алатка, клетките можат да се подредуваат по тип, што значи дека можат да се дијагностицираат болести предизвикани од мали клетки.
Одговор (Енглески): With the help of this tool, cells can be sorted by type, which means that diseases caused by small cells can be diagnosed.

Пример 4
Македонски: Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Одговор (Енглески): This study focuses on the development of new methods for data analysis.

Пример 5
Македонски: Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.
Одговор (Енглески): In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
"""

In [42]:
predictions_eng = batch_translate(text_mkd,instruction,max_new_tokens=128,lang_code="srb",language="Енглески")

Batch 0
Result: On Monday, scientists from Stanford University’s medical school announced they had invented a new tool for diagnosing diseases by sorting cells according to their types. It’s a small chip for printing that can be produced using standard ink-jet printers, costing around one US cent.

Batch 0
Result: Leading researchers believe this could lead to early detection of cancer, tuberculosis, HIV, and malaria among patients living in low-income countries, where survival rates from diseases such as breast cancer may be twice as low as in wealthier nations.

Batch 0
Result: A JAS 39C Gripen crashed around 9:30 AM local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights.

Batch 0
Result: It has been determined that the pilot was Dilokrit Patavi, the squadron leader.

Batch 0
Result: Local media report on an airport fire truck that overturned while firefighters responded to the call.

Batch 0
Result: 28-year-old Vidal from Seville joined Barcelona’s team.

Batch 0
Result: After moving to the capital of Catalonia, Vidal played 49 matches for the club.

Batch 0
Result: The protest began around 11:00 AM local time (UTC+1) in Whitehall, across from the entrance guarded by police near Downing Street, the official residence of the prime minister.

Batch 8
Result: Immediately after 11:00 AM, protesters blocked traffic heading north towards Whitehall.

Batch 8
Result: At 11:20 AM, the police requested protesters to move off the sidewalk, citing that they needed to balance the right to protest with traffic congestion.

Batch 8
Result: Around 11:29 AM, the protest moved towards Whitehall, near Trafalgar Square, passing by Strand, going past Aldwych and through Kingsway to Holborn, where the Conservative Party was holding its Spring Forum at the Grand Connaught Rooms hotel.

Batch 8
Result: Nadal’s personal record against the Canadian is 7 - 2.

Batch 8
Result: Recently lost to Ronnqvist at the Brisbane Open.

Batch 8
Result: Nadal won 88% of the points on the net in the match, earning 76 points in the first service.

Batch 8
Result: After the match, the King of the land said: “I am simply very excited to be back in the final rounds of the most important events. I’m here to try and win.”

Batch 8
Result: "The Panama Papers" is an all-encompassing term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were disclosed in the press during spring 2016.

Batch 16
Result: According to documents, fourteen banks helped wealthy clients hide billions of dollars in assets in order to conceal taxes and avoid other laws.

Batch 16
Result: The British newspaper “The Guardian” reported that “Deutsche Bank” controlled approximately one-third of the 1200 provisional companies used to achieve that.

Batch 16
Result: This led to protests around the world, a certain number of criminal prosecutions, and the prime ministers of Iceland and Pakistan resigned.

Batch 16
Result: Born in Hong Kong, Stu studied at New York University and Harvard Law School, and he also had a permanent American “green card.”

Batch 16
Result: He implied during the elections that Ma could escape the country in case of a crisis.

Batch 16
Result: He also claimed that photogenic Ma was more about style than substance.

Batch 16
Result: Despite these accusations, Ma easily won with a platform representing closer ties with continental China.

Batch 16
Result: Today’s player of the day is Alex Ovechkin from the Washington Capitals team.

Batch 24
Result: He scored 2 goals and 2 assists in Washington’s 5-3 victory over the Atlanta Thrashers.

Batch 24
Result: Ovechkin’s first assist was for the winning goal scored by rookie Nicklas Bäckström.

Batch 24
Result: His second goal of the evening was the 60th of the season, making him the first player since 1995-96 to score 60 or more goals in a single season, a record previously held by Jaromir Jagr and Mario Lemieux.

Batch 24
Result: Batten was ranked 190th on the list of the 400 richest Americans in 2008 with a fortune estimated at $2.3 billion.

Batch 24
Result: He graduated from Virginia College of Arts and Sciences in 1950 and was recognized as an important benefactor to the institution.

Batch 24
Result: The Iraqi prison "Abu Graib" went up in flames during a riot.

Batch 24
Result: The prison became quietly famous after allegations of abuse of prisoners were uncovered following its takeover by American military forces.

Batch 24
Result: Peugeot Junior collided with the Singapore Grand Prix 2008 immediately after Fernando Alonso’s premature pit stop, followed by the deployment of the safety car.

Batch 32
Result: While the болиde before Alonso went to fill up the safety car, he took over the lead to secure the victory.

Batch 32
Result: Pierre Pommared was released after the Hungarian Grand Prix in 2009.

Batch 32
Result: At exactly 8:46 AM, a commotion spread throughout the city, marking the exact moment when the first airplane hit its target.

Batch 32
Result: Two beams of light were set to shine towards the night sky.

Batch 32
Result: Construction is ongoing for five new cloud centers at the location, along with a transportation center and memorial park in the middle.

Batch 32
Result: PBS series has over two dozen Emmy Awards and is broadcast only by Sesame Street and Mister Rogers’ Neighborhood.

Batch 32
Result: Each episode of the show focused on a topic from a specific book, and then that topic was explored through multiple stories.

Batch 32
Result: Also, each show will provide recommendations for books that every child should request when going to the library.

Batch 40
Result: John Grant, from WNED Buffalo (“Reading Rainbow’s home base”), said, “Reading Rainbow taught children why they should read… a love of reading – [the series] encourages children to pick up a book and read.”

Batch 40
Result: Some people, including John Grant, believe that the church-financier and the change in philosophy regarding educational programs contributed to the interruption of the broadcast.

Batch 40
Result: The storm was located 645 miles (1040 km) west of the Green Bay islands and will likely dissipate before posing any threat to land areas, meteorologists say.

Batch 40
Result: Currently, Fred is covering winds blowing at speeds of 105 miles per hour (165 km/h) and moving towards the northwest.

Batch 40
Result: Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic since satellite imagery was first developed, but it’s only the third major hurricane recorded east of 35° W.

Batch 40
Result: On September 24, 1759, Arthur Ginny signed a 9,000-year contract for St. James’s Gate Brewery in Dublin, Ireland.

Batch 40
Result: 250 years later, “Ginius” had grown into a global business with an annual turnover of 10 billion euros (14.7 billion dollars).

Batch 40
Result: Jonny Reid, a GP Racing driver from New Zealand, today created a historic event by legally breaking the 48-year record while passing over the Auckland Harbour Bridge in New Zealand.

Batch 48
Result: Mr. Reid managed to drive the New Zealand A1GP car seven times across the bridge at speeds over 160 km/h, nicknamed "Black Beauty".

Batch 48
Result: The New Zealand police are facing a problem when using radar to measure speeds to see how fast Mr. Reed is moving, due to the height of Black Diamond. The only time the police managed to catch Mr. Reed was when he slowed down to 160 km/h.

Batch 48
Result: In the last three months, over 80 detainees have been released from the detention center without being formally charged.

Batch 48
Result: In April of this year, Judge Glint issued an order temporarily restricting the institution for expedited release of those detained for more than 24 hours after arrest who had not been heard by a court commissioner.

Batch 48
Result: The commissioner determines bail, if allowed, and formalizes the charges filed by the officer who conducted the arrests. Subsequently, the charges are entered into the state computer system where the case is monitored.

Batch 48
Result: The date for trial will be determined in this hearing for the defendant.

Batch 48
Result: Peter Costello, the Australian Minister of Finance and the man with the greatest potential to replace Prime Minister John Howard as leader of the Liberal Party, expressed his support for the nuclear energy industry in Australia.

Batch 48
Result: Mr. Kostelo said that when nuclear reactors become economically sustainable, Australia will begin using them.

Batch 56
Result: “If we’re talking commercially, we need to have it. I.e., there’s essentially no objection to nuclear energy,” Mr. Costelo said.

Batch 56
Result: According to Ansa, “the police were concerned about several high-level attacks they feared could trigger a succession war in full swing.”

Batch 56
Result: The police announced that Lo Piccolo had control because he was Provenzano’s right hand man in Palermo, and his greater experience earned him respect from the older generation bosses who followed Provenzano’s policy of remaining as hidden as possible while strengthening their network of authority.

Batch 56
Result: These bosses were apprehended by Provenzano when he ended the war sparked by Rina against the state that took the lives of “crusaders” of the mafia, Giovanni Falcone and Paolo Borsellino in 1992.

Batch 56
Result: Apple’s CEO, Steve Jobs, unveiled the device onstage while pulling out an iPhone from his jeans pocket.

Batch 56
Result: During his 2-hour speech, he stated that “Apple will invent the phone again, and Today will create history.”

Batch 56
Result: Brazil is the largest Roman Catholic country in the world, and the Roman Catholic Church is constantly opposed to the legalization of same-sex marriage in the country.

Batch 56
Result: The Brazilian State Congress has been debating the legalization of civil unions for ten years; nevertheless, such civil marriages are currently legal only in Rio Grande do Sul.

Batch 64
Result: The original draft law was drafted by Marta Suplicio, former mayor of São Paulo. The proposed legislation, after being revised, is now in the hands of Roberto Jefferson.

Batch 64
Result: Protestants hope to collect 1.2 million signatures for the petition they will present to Congress in November.

Batch 64
Result: After it became apparent that many families were seeking legal assistance to deal with leaks, a meeting was held on March 20 at the Community Legal Center in East Bay for victims of housing fraud.

Batch 64
Result: When the residents started sharing what had happened to them, it became clear to most of the involved families that Caroline Wilson from DHA had stolen their security deposits and fled the city.

Batch 64
Result: Residents of Lockwood Gardens believe that 40 families or more may be facing eviction because they’ve learned that the police unit OHA is investigating other properties for public housing and could be involved in residential fraud.

Batch 64
Result: Bento canceled his performance that was supposed to take place at the military memorial stadium on Maui, where 9000 fans were expected to attend, and apologized to the fans.

Batch 64
Result: The management company of Bend, HK Management Inc., did not issue an official statement regarding the reasons for the cancellation on September 20th, but the following day stated that it was due to a logistical problem.

Batch 64
Result: The well-known Greek lawyers, Sakis K€haioglou and George Nikolopoulos, are imprisoned in Koridallos prison in Athens after being found guilty of bribery and corruption.

Batch 72
Result: As a result, a major scandal erupted within the Greek legal community following the revelation of illegal activities carried out by judges, lawyers, attorneys, and defenders over the previous years.

Batch 72
Result: Several weeks ago, following information published by journalist Makis Triantafilopoulos in his popular television show “Zoungla” on Alpha TV, MP and lawyer Petros Mantouvalos resigned because members of his cabinet were involved in accepting bribes and corruption.

Batch 72
Result: In addition, Supreme Judge Evangelor Kalusis is under arrest due to corruption and abuse of power.

Batch 72
Result: Roberts stubbornly refused to discuss his beliefs about when life begins, stating that it was an important question considering the ethics of abortion, adding that it would be unethical to comment on the specific details of potential cases.

Batch 72
Result: However, she confirmed her previous statement that Roe v. Wade is “the main standard,” emphasizing the importance of consistent rulings from the Supreme Court.

Batch 72
Result: He also confirmed his belief in the undisputed right to privacy, which influenced Roe’s decision.

Batch 72
Result: Maruchidore finished at the top of the leaderboard, six points ahead of Nusa, who is second.

Batch 72
Result: The two teams met in the grand semi-final, where Nusa won by 11 points difference.

Batch 80
Result: Then Maruchidur defeated Kabultur in the preliminary final.

Batch 80
Result: Hesperonychus elizabethae is a species of the family Dromaeosauridae closely related to velociraptor.

Batch 80
Result: It is believed that this warm-blooded bird-grabbler with feathers upright along its body walking on two legs, like raptors.

Batch 80
Result: His second claw was larger, giving rise to the name Hesperonychus, meaning “western claw.”

Batch 80
Result: Extreme weather conditions, including breaking ice, are hindering rescue efforts.

Batch 80
Result: Pittman indicates that the conditions will not improve until next week.

Batch 80
Result: According to Pittman, the amount and thickness of sea ice is the worst it’s ever been for seal hunters in the past 15 years.

Batch 80
Result: Today, in the Red Lake municipality, after the funerals were held for Jeff Weiss and three of the nine victims, news spread that another student had been arrested in connection with the school shooting from March 21st.

Batch 88
Result: Government officials haven’t made many official statements, except to confirm today’s arrest.

Batch 88
Result: However, a source familiar with the investigation into “Minneapolis Star-Tribune” revealed that it was Louis Jurden, the 16-year-old son of the tribal president of Red Lake, Floyd Jurden.

Batch 88
Result: Currently, it is not known what charges will be filed, nor how the authorities came upon the boy, but proceedings against the minor have begun in federal court.

Batch 88
Result: Lodin also stated that officials decided to cancel the second round of elections to save Afghans from expenses and to avoid security risks associated with further voting.

Batch 88
Result: Diplomats said they had found enough ambiguities in the Afghan constitution to determine that a second round of elections was unnecessary.

Batch 88
Result: This contradicts previous statements, which stated that canceling the second round would be unconstitutional.

Batch 88
Result: The aircraft was heading towards Irkutsk and was being piloted by domestic troops.

Batch 88
Result: An investigation was launched to examine it.

Batch 96
Result: II-76 was the largest component in both the Russian and Soviet military since the 1970s, which recently experienced a serious accident in Russia last month.

Batch 96
Result: On October 7th, the engine detached during takeoff, without any injuries. After this incident, Russia briefly landed the Il-76s.

Batch 96
Result: 800 miles of the Trans-Alaska pipeline system were shut down after thousands of storms erupted south of Fairbanks, Alaska.

Batch 96
Result: After a routine test of the fire control system, a power outage occurred, causing valves to open and raw oil to spill near Pump Station 9 at Fort Grilli.

In [43]:
references = [[ref] for ref in text_eng]
references[:10]

[['On Monday, scientists from the Stanford University School of Medicine announced the invention of a new diagnostic tool that can sort cells by type: a tiny printable chip that can be manufactured using standard inkjet printers for possibly about one U.S. cent each.'],
 ['Lead researchers say this may bring early detection of cancer, tuberculosis, HIV and malaria to patients in low-income countries, where the survival rates for illnesses such as breast cancer can be half those of richer countries.'],
 ['The JAS 39C Gripen crashed onto a runway at around 9:30 am local time (0230 UTC) and exploded, closing the airport to commercial flights.'],
 ['The pilot was identified as Squadron Leader Dilokrit Pattavee.'],
 ['Local media reports an airport fire vehicle rolled over while responding.'],
 ['28-year-old Vidal had joined Barça three seasons ago, from Sevilla.'],
 ['Since moving to the Catalan-capital, Vidal had played 49 games for the club.'],
 ["The protest started around 11:00 local time (UTC+1) on Whitehall opposite the police-guarded entrance to Downing Street, the Prime Minister's official residence."],
 ['Just after 11:00, protesters blocked traffic on the northbound carriage in Whitehall.'],
 ['At 11:20, the police asked the protesters to move back on to the pavement, stating that they needed to balance the right to protest with the traffic building up.']]

In [44]:
bleu.compute(predictions=predictions_eng, references=references)

{'bleu': 0.30872810028985576,
 'precisions': [0.6340607950116913,
  0.3767234387672344,
  0.24344885883347422,
  0.1562224183583407],
 'brevity_penalty': 1.0,
 'length_ratio': 1.0247603833865815,
 'translation_length': 2566,
 'reference_length': 2504}

In [45]:
chrf_score = sacrebleu.corpus_chrf(predictions_eng, references)
print(f"chrF: {chrf_score.score:.2f}")

chrF: 53.90

## Few-Shot Cross-lingual prompt (MKD->ENG) in bulgarian language

In [46]:
instruction = f"""Преведи следния текст от **Македонски** на **Английски** език.
Само отпечатай превода на английски. Не добавяй никакви обяснения.

Пример 1
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 2
Македонски: Еден спортски натпревар трае 90 минути, односно две полувремиња по 45 минути со одмор помеѓу нив во траење од 15 минути. Ако има подолги прекини во играта, таа се продолжува така што се надополнува изгубеното време.
Отговор (Английски): A sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.

Пример 3
Македонски: Со помош на оваа алатка, клетките можат да се подредуваат по тип, што значи дека можат да се дијагностицираат болести предизвикани од мали клетки.
Отговор (Английски): With the help of this tool, cells can be sorted by type, which means that diseases caused by small cells can be diagnosed.

Пример 4
Македонски: Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Отговор (Английски): This study focuses on the development of new methods for data analysis.

Пример 5
Македонски: Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.
Отговор (Английски): In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
"""

In [47]:
predictions_eng = batch_translate(text_mkd,instruction,max_new_tokens=128,lang_code="bug",language="Английски")

Batch 0
Result: On Monday, scientists from Stanford University’s medical school announced that they had invented a new tool for diagnosing purposes, whereby cells are sorted according to types: it is a small chip for printing that can be produced using standard ink-jet printers, and at a price of about one US cent.

Batch 0
Result: Leading researchers believe this could lead to early detection of cancer, tuberculosis, HIV, and malaria among patients living in low-income countries, where survival rates from diseases such as breast cancer may be twice as low as in wealthier nations.

Batch 0
Result: A JAS 39C Gripen crashed near 9:30 AM local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights.

Batch 0
Result: It has been established that the pilot was Dilokrit Patavi, the squadron leader.

Batch 0
Result: Local media report on an airport fire truck that overturned while firefighters responded to the call.

Batch 0
Result: 28-year-old Vidal from Seville joined Barcelona’s team.

Batch 0
Result: After moving to the capital of Catalonia, Vidal played 49 matches for the club.

Batch 0
Result: The protest began around 11:00 AM local time (UTC+1) in Whitehall, across from the entrance guarded by police near Downing Street, the official residence of the prime minister.

Batch 8
Result: Immediately after 11:00 AM, protesters blocked traffic heading north towards Whitehall.

Batch 8
Result: At 11:20 AM, the police requested the protesters to move off the sidewalk, citing that they needed to balance the right to protest with traffic congestion.

Batch 8
Result: Around 11:29 AM, the protest moved towards Whitehall, near Trafalgar Square, passing by Strand, going past Aldwych and through Kingsway to Holborn, where the Conservative Party was holding its Spring Forum at the Grand Connaught Rooms hotel.

Batch 8
Result: Rafael Nadal’s personal record against the Canadian is 7 – 2.

Batch 8
Result: Recently lost to Ronic in the Brisbane Open.

Batch 8
Result: Nadal won 88% of the points on the net in the match, earning 76 points in the first service.

Batch 8
Result: After the competition, the King of the land said: “I am simply very excited to be back in the final rounds of the most important events. I’m here to try and win.”

Batch 8
Result: "The Panama Papers" is an all-encompassing term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were disclosed in the press during spring 2016.

Batch 16
Result: According to documents, fourteen banks helped wealthy clients hide billions of dollars in assets in order to conceal taxes and avoid other laws.

Batch 16
Result: The British newspaper “The Guardian” reported that “Deutsche Bank” controlled approximately one-third of the 1200 provisional companies used to achieve that.

Batch 16
Result: This led to protests organized throughout the world, a certain number of criminal prosecutions, and the prime ministers of Iceland and Pakistan resigned.

Batch 16
Result: Born in Hong Kong, he studied at New York University and Harvard Law School, and had a permanent American “green card”.

Batch 16
Result: He implied during the elections that Ma could escape the country in case of a crisis.

Batch 16
Result: He also claimed that Photogenic Ma was more about style than substance.

Batch 16
Result: Despite these accusations, Ma easily won with a platform representing closer ties with continental China.

Batch 16
Result: Today’s player of the day is Alex Ovechkin from the Washington Capitals team.

Batch 24
Result: There were 2 goals and 2 assists in Washington’s 5-3 victory over the Atlanta Thrashers.

Batch 24
Result: Ovechkin’s first assist was for the winning goal scored by rookie Nicklas Bäckström.

Batch 24
Result: His second goal of the evening was the 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96 when Jaromir Jagr and Mario Lemieux set that record.

Batch 24
Result: Batten was ranked 190th on the list of the 400 richest Americans in 2008 with a fortune estimated at $2.3 billion.

Batch 24
Result: He graduated from Virginia College of Arts and Sciences in 1950 and was recognized as an important benefactor to the institution.

Batch 24
Result: The Iraqi prison "Abu Graib" was set ablaze during a riot.

Batch 24
Result: The prison became widely known after allegations of abuse of prisoners were uncovered following its takeover by American military forces.

Batch 24
Result: Peu Junior collided with the Singapore Grand Prix 2008 immediately after Fernando Alonso’s early pit stop, followed by the deployment of the safety car.

Batch 32
Result: While Bolide ahead of Alonso went to fill up the fuel of the safety car, he took over the lead to achieve victory.

Batch 32
Result: Pierre Pomméditerranée was released after the Hungarian Grand Prix in 2009.

Batch 32
Result: At exactly 8:46 AM, there was a commotion throughout the city, marking the exact moment when the first airplane hit its target.

Batch 32
Result: Two beams of light were set to shine towards the night sky.

Batch 32
Result: The construction is ongoing at the location for five new cloud centers, along with a transportation center and memorial park in the middle.

Batch 32
Result: PBS series has more than two dozen Emmy Awards and is broadcast only by Sesame Street and Mr. Rogers’ Neighborhood.

Batch 32
Result: Each episode of the show focused on a topic from a specific book, and then that topic was explored through multiple stories.

Batch 32
Result: Also, each show will provide recommendations for books that every child should request when going to the library.

Batch 40
Result: John Grant, from WNED Buffalo (“Reading Rainbow’s home base”), said, “Reading Rainbow taught children why they should read… a love of reading – [the series] encourages children to pick up a book and read.”

Batch 40
Result: Some people, including John Grant, believe that the church-financier and the change in philosophy regarding educational programs have contributed to the interruption of the broadcast.

Batch 40
Result: The storm was located 645 miles (1040 km) west of the Green Bay islands and will likely dissipate before posing any threat to land areas, meteorologists say.

Batch 40
Result: Currently, Fred is covering winds blowing at speeds of 105 miles per hour (165 km/h) and moving towards the northwest.

Batch 40
Result: Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic since the advent of satellite imagery, but it is only the third major hurricane recorded east of 35° W.

Batch 40
Result: On September 24, 1759, Arthur Ginny signed a 9,000-year contract for St. James’s Gate Brewery in Dublin, Ireland.

Batch 40
Result: 250 years later, “Genius” had grown into a global business with an annual turnover of 10 billion euros (14.7 billion dollars).

Batch 40
Result: Jonny Reid, a GP Racing driver from New Zealand, today made a historic event by legally crossing the 48-year-old Auckland Harbour Bridge in New Zealand at record speed.

Batch 48
Result: Mr. Reed managed to drive the New Zealand A1GP car, Black Beauty, over the bridge seven times at speeds exceeding 160 km/h.

Batch 48
Result: The New Zealand police face a problem when using radar to determine speeds to see how fast Mr. Reed is moving, due to the height of Black Diamond. The only time the police managed to catch Mr. Reed was when he slowed down to 160 km/h.

Batch 48
Result: In the last 3 months, over 80 detainees have been released from the detention center without being formally charged.

Batch 48
Result: In April of this year, Judge Glin issued an order for a temporary restriction against the institution for expedited release of those detained for more than 24 hours after arrest who had not been heard by a court commissioner.

Batch 48
Result: The commissioner determines bail, if allowed, and formalizes the charges filed by the officer who conducted the arrests. Subsequently, the charges are entered into the state computer system where the case is monitored.

Batch 48
Result: The hearing will determine the date for the defendant’s right to a speedy trial.

Batch 48
Result: Peter Costello, the Australian Minister of Finance and the man with the greatest potential to replace Prime Minister John Howard as leader of the Liberal Party, expressed his support for the nuclear energy industry in Australia.

Batch 48
Result: Mr. Kostelo stated that when nuclear reactors become economically sustainable, Australia will begin using them.

Batch 56
Result: “If we’re talking commercially, we need to have it. I.e., in principle, there’s no objection to nuclear energy,” Mr. Kostelo said.

Batch 56
Result: According to Ansa, “the police were concerned about several high-level attacks they feared could trigger a succession war in full swing.”

Batch 56
Result: The police announced that Lo Piccolo had control because he was Provenzano’s right-hand man in Palermo, and his greater experience earned him respect from the older generation of bosses who followed Provenzano’s policy of remaining as hidden as possible while strengthening their network of authority.

Batch 56
Result: These bosses were apprehended by Provenzano when he ended the war sparked by Rina against the state that took the lives of “crusaders” of the mafia, Giovanni Falcone and Paolo Borsellino in 1992.

Batch 56
Result: The CEO of Apple, Steve Jobs, unveiled the device onstage while pulling out an iPhone from his jeans pocket.

Batch 56
Result: During his 2-hour speech, he stated that “Apple will invent the phone again, Today we will create history.”

Batch 56
Result: Brazil is the largest Roman Catholic country in the world, and the Roman Catholic Church is constantly opposed to the legalization of same-sex marriage in the country.

Batch 56
Result: The Brazilian State Congress has been debating the legalization of such civil unions for ten years; nevertheless, such marriages are currently legal only in Rio Grande do Sul.

Batch 64
Result: The original draft law was drafted by Marta Suplicio, former mayor of São Paulo. The proposed legislation, after her modifications, is now in the hands of Roberto Jefferson.

Batch 64
Result: Protestants hope to collect 1.2 million signatures for the petition they will present to the National Congress in November.

Batch 64
Result: After it became apparent that many families were seeking legal assistance to deal with leaks, a meeting was held at the Community Legal Center in East Bay on March 20th for victims of housing fraud.

Batch 64
Result: When the residents started sharing what had happened to them, it became clear to most of the involved families that Caroline Wilson from DHA had stolen their security deposits and had fled the city.

Batch 64
Result: Residents of Lockwood Gardens believe that there may be 40 families or more facing eviction because they have learned that the police force OHA is investigating other properties for public housing in Auckland, which may be involved in residential fraud.

Batch 64
Result: Bendo canceled his performance that was supposed to take place at the military memorial stadium on Maui, where 9000 fans were expected to attend, and apologized to the fans.

Batch 64
Result: The management company of Bend, HK Management Inc., did not issue an official statement regarding the reasons for the cancellation on September 20th, but the following day stated that it was due to a logistical problem.

Batch 64
Result: The well-known Greek lawyers, Sakis K€haioglou and George Nikolopoulos, are imprisoned in Koridallos prison in Athens after being found guilty of bribery and corruption.

Batch 72
Result: Due to this, a major scandal erupted within the Greek legal community following the revelation of illegal activities carried out by judges, lawyers, attorneys, and defenders over the previous years.

Batch 72
Result: Several weeks ago, following information published by journalist Makis Triantafilopoulos in his popular television show “Zoungla” on Alpha TV, MP and lawyer Petros Mantouvalos resigned because members of his cabinet were involved in accepting bribes and corruption.

Batch 72
Result: In addition, Supreme Court Justice Evangelor Kaluslis is under arrest due to corruption and abuse of power.

Batch 72
Result: Roberts vehemently refused to discuss his beliefs about when life begins, which is an important question considering the ethics of abortion, stating that it would be unethical to comment on the specific details of potential cases.

Batch 72
Result: However, she confirmed her previous statement that *Roe v. Wade* is “the standard,” emphasizing the importance of consistent rulings from the Supreme Court.

Batch 72
Result: He also confirmed his belief in the undisputed right to privacy, which influenced Roe’s decision.

Batch 72
Result: Maruchidore finished at the top of the leaderboard, six points ahead of Nusa, who is second.

Batch 72
Result: The two teams met in the grand semi-final, where Nussa came to victory with an 11-point difference.

Batch 80
Result: Marudzor defeated Kabultur in the preliminary final.

Batch 80
Result: Hesperonychus elizabethae is a species of the family Dromaeosauridae closely related to velociraptor.

Batch 80
Result: It is believed that this warm-blooded bird-grabbler with feathers upright along its body walking on two legs, like raptors.

Batch 80
Result: His second claw was larger, giving rise to the name Hesperonychus, meaning “western claw.”

Batch 80
Result: Extreme weather conditions, including freezing frost, are hindering rescue efforts.

Batch 80
Result: Pitmān indicates that the conditions will not improve until next week.

Batch 80
Result: According to Pittman, the amount and thickness of sea ice is the worst it’s ever been for seal hunters in the past 15 years.

Batch 80
Result: Today, in the Red Lake municipality, after the funerals of Jeff Weiss and three of the nine victims were held, news spread that another student had been arrested in connection with the school shooting from March 21st.

Batch 88
Result: The authorities have not officially said much, except to confirm today’s arrest.

Batch 88
Result: However, a source from investigative research on “Minneapolis Star-Tribune” stated that it was Louis Jurden, the 16-year-old son of the tribal president of Red Lake, Floyd Jurden.

Batch 88
Result: At present, it is not known what charges will be filed, nor how the authorities came upon the boy, but proceedings against the minor have begun in a federal court.

Batch 88
Result: Lodin also stated that officials decided to cancel the second round of elections to save Afghans from expenses and to avoid security risks associated with another vote.

Batch 88
Result: Diplomats stated they had found enough ambiguities in the Afghan constitution to determine that a second round of elections was unnecessary.

Batch 88
Result: This contradicts previous statements, which stated that canceling the second round would be unconstitutional.

Batch 88
Result: The aircraft was headed towards Irkutsk and was being piloted by internal troops.

Batch 88
Result: An investigation was launched to examine it.

Batch 96
Result: II-76 was the largest component of both the Russian and Soviet military since the 1970s, which recently experienced a serious accident in Russia last month.

Batch 96
Result: On October 7th, the engine detached during takeoff, without any injuries. After this accident, Russia briefly landed the Il-76s.

Batch 96
Result: 800 miles of the Trans-Alaska pipeline system were shut down after thousands of storms erupted south of Ferbence, Alaska.

Batch 96
Result: After a routine test of the fire control system, a power outage occurred, causing valves to open and raw oil to spill near pump station 9 at Fort Grille.

In [48]:
references = [[ref] for ref in text_eng]
references[:10]

[['On Monday, scientists from the Stanford University School of Medicine announced the invention of a new diagnostic tool that can sort cells by type: a tiny printable chip that can be manufactured using standard inkjet printers for possibly about one U.S. cent each.'],
 ['Lead researchers say this may bring early detection of cancer, tuberculosis, HIV and malaria to patients in low-income countries, where the survival rates for illnesses such as breast cancer can be half those of richer countries.'],
 ['The JAS 39C Gripen crashed onto a runway at around 9:30 am local time (0230 UTC) and exploded, closing the airport to commercial flights.'],
 ['The pilot was identified as Squadron Leader Dilokrit Pattavee.'],
 ['Local media reports an airport fire vehicle rolled over while responding.'],
 ['28-year-old Vidal had joined Barça three seasons ago, from Sevilla.'],
 ['Since moving to the Catalan-capital, Vidal had played 49 games for the club.'],
 ["The protest started around 11:00 local time (UTC+1) on Whitehall opposite the police-guarded entrance to Downing Street, the Prime Minister's official residence."],
 ['Just after 11:00, protesters blocked traffic on the northbound carriage in Whitehall.'],
 ['At 11:20, the police asked the protesters to move back on to the pavement, stating that they needed to balance the right to protest with the traffic building up.']]

In [49]:
bleu.compute(predictions=predictions_eng, references=references)

{'bleu': 0.31541998105181024,
 'precisions': [0.6354166666666666,
  0.3812199036918138,
  0.2504180602006689,
  0.1631762652705061],
 'brevity_penalty': 1.0,
 'length_ratio': 1.035143769968051,
 'translation_length': 2592,
 'reference_length': 2504}

In [50]:
chrf_score = sacrebleu.corpus_chrf(predictions_eng, references)
print(f"chrF: {chrf_score.score:.2f}")

chrF: 55.54

## Few-Shot Mono-lingual prompt (ENG->MKD)

In [51]:
instruction = f"""Translate the following text from **English** into **Macedonian**. Only output the translation. Do not add explanations.
  Example 1
  English: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
  Response (Macedonian): Во понеделник, во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
  Example 2
  English: A sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.
  Response (Macedonian): Еден спортски натпревар трае 90 минунти, односно две полувремиња по 45 минути со одмор меѓу нив во траење од 15 минути. Ако има подолги прекини во играта, таа се продолжува така што се надополнува изгубеното време.
  Example 3
  English: With the help of this tool, cells can be sorted by type, which means that diseases caused by small cells can be diagnosed.
  Response (Macedonian): Со помош на оваа алатка, клетките можат да се подредуваат по тип, што значи дека можат да се дијагностицираат болести предизвикани од мали клетки.
  Example 4
  English: This study focuses on the development of new methods for data analysis.
  Response (Macedonian)): Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
  Example 5
  English: In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
  Response (Macedonian): Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.
"""

In [52]:
predictions_mkd = batch_translate(text_eng,instruction,max_new_tokens=128,language="Macedonian")

Batch 0
Result: Во вторник, научници од Школот за медицина при Универзитетот Стенфорд објавија дека произведени е нов дијагностички инструмент кој може да ги сортира клетките според вид: мал, штамлив чип кој може да биде произведен користејќи стандардни струјни принтери за можноста да се направи за околу една американска центар.

Batch 0
Result: Главните истражувачи велат дека ова може да доведе до ран детектирање на рак, туберкулоза, ХИВ и маларија кај пациентите во земјите со низок доход, каде што стапките на преживување за болести како ракот на матката можат да бидат половина од оние во богатите земји.

Batch 0
Result: Јасе 39Ц Грипен се урна на писта околу 9:30 наутро локално време (0230 UTC) и експлодираше, затворајќи го адиропорт за комерцијални полети.

Batch 0
Result: Пилотот беше идентификуван како Скваерн Лиддер Дилиокрит Паттавеи.

Batch 0
Result: Локалните медиуми ја сообщаваат пожарната возилка на авионската леталиштем наскоро се преклопувала додека реагирала.

Batch 0
Result: Видал, кој е на 28 години, се приклучи на Барса пред три сезони, од Севиља.

Batch 0
Result: По преселување во кадената на Каталонија, Видал одигра 49 натвки за клубот.

Batch 0
Result: Протестот започна околу 11:00 локално време (UTC+1) на Вајтлиха спротивно на полициски надворешна врата кон Донинг Стрит, официјалната резиденција на премиерката.

Batch 8
Result: Неколку минути по 11:00 часот, демонстрантите блокираа сообраќејот на северната патека во Вајтлиха.

Batch 8
Result: Во 11:20, полицијата побара од протестувалиците да се вратат на патеката, со тврдење дека треба да ја балансираат правото на протест со зголемувањето на сообраќејот.

Batch 8
Result: Околу 11:29, протестот се крена над Вајтли, покрај Трафаларска плоштаница, покрај Стренд, минувајќи покрај Алдвич и кон Кингсваи кон Холборн каде што Конзервативната партија одржувале свој Форум за пролет во хотелот Гранд Коннокнут Ромс.

Batch 8
Result: Рекордот на Надал против Канадскиот играч е 7-2.

Batch 8
Result: Непостојуваше неодамна против Раоник на Отвореното во Брисбен.

Batch 8
Result: Надал освои 88% нет точки во натпредакот, заработувајќи 76 точки во првиот сервис.

Batch 8
Result: По натпреварот, кралот на глина рече: „Јас сум само возбуден што сум повторно во финалето на најважните настани. Јас сум тука да се обидам да го осволам овој натпреварувач.“

Batch 8
Result: „Панама гири“ е општ термин за околку десет милиони документи од правната фирма „Мосак Фонсека“ од Панама, кои беа изложени пред приопштението во пролетта 2016 година.

Batch 16
Result: Документата покажаа дека 14 банки помогнал на богатите клиенти да скриват милиарди американски долари богатство за да избегнат данок и други регулации.

Batch 16
Result: Британското весник "The Guardian" наведна дека Deutche Bank контролираше околу третина од 1200-те компании-самостојки кои се користеа за остварување на ова.

Batch 16
Result: Се одржаа протести широко низ светот, повеќе криминални достави и лидерите на владите на Исланд и Пакистан конечно отстапија.

Batch 16
Result: Роден во Хонг Конг, Ма студирал на Универзитет во Њујорк и Правен факултет во Харвард, и некогаш имал американска перманентна адреса “зелен картон”.

Batch 16
Result: Хсиеј наведна во времето на изборите дека Ма може да избегне земјата за време на криза.

Batch 16
Result: Хсие додаде и аргумент дека фотогеничната Ма беше повеќе стил отколку суштина.

Batch 16
Result: Неколку спротивно овие обвинувања, Ма победи убедително на платформа која бара поблизок контакт со кинеската копница.

Batch 16
Result: Играчот на ден за денес е Алекс Овечкин од Вашингтон Кепз.

Batch 24
Result: Тој постигна 2 голови и 2 асистенции во победата на Вашингтон над Атланта Трасхери со резултат 5-3.

Batch 24
Result: Првиот асист на Ovechkin токму вечерва беше на головозавршниот погодок од новак Никлас Бакстром.

Batch 24
Result: Неговиот втордицен гол вечерва беше неговиот 60-ти гол сезонава, станувајќи прв играч кој постигнувал 60 или повеќе голови во сезоната од 1995-96 година, кога Јаромир Јагр и Марио Лемиев секој ја достигнал таа потрага.

Batch 24
Result: Батман беше ранкуван на 190-то место на листата на 400 најбогати Американци во 2008 година, со проценети богатство од 2.3 милијарди долари.

Batch 24
Result: Тој се дипломираше на Колеџот за уметности и науки при Универзитетот во Вирџинија во 1950 година и беше значаен донатор за таа институција.

Batch 24
Result: Затворската каса во Абу Гариб, Ирак, била запалена за време на беспорядък.

Batch 24
Result: Затворот стана познат после откритието за злопотреб у на затовот кога американските сили ја презедоа контролата.

Batch 24
Result: Пикет Јр. се повреди во Гран при на Сингапур 2008 токму после рана спирување во паркот за Фернандо Алонсо, што доведе до активирање на сината кола.

Batch 32
Result: Кога автомобилите пред Алونسо влегоа во гаражата за доцнежливо полнење под ситечки, тој се површи во релето и освои победа.

Batch 32
Result: Пикет Јр. беше отстранет по Гран при на Унгарија во 2009 година.

Batch 32
Result: Во точно 8:46 часот, над градот дојде мртовна тишина, означувајќи ги точните моменти кога првиот авион-ракет погоди својата цел.

Batch 32
Result: Две зраци светлина биле поставени да укажуваат кон небото низ ноќта.

Batch 32
Result: Изградта е во тек на пет нови небогрижи на локацијата, со транспортен центар и парк на меморија во просторот во средина.

Batch 32
Result: Посебното шоу на ПБС има повеќе од дваесет награди Еми награда, а неговата потрага е само малку полека од Сезам утрина и "Мистер Роџерс' соседство".

Batch 32
Result: Секоја епизода од шоуто би се фокусирала на тема во специфична книга и потоа ја би могла да ја истражи преку повеќе приказни.

Batch 32
Result: Секоја постава би исто така нудерила препорачања за книги кои децата треба да ги бараат кога одат во библиотеката.

Batch 40
Result: Џон Грант, од WNED Buffalo (станицата на „Ридинг раинбоу“), рече: „Ридинг раинбоу научи децата зошто да читаат,... љубов кон читањето — [шобот] ги охранија децата да вземат книга и да читаат.“

Batch 40
Result: Некои, вклучувајќи го иЏон Грант, веруваат дека и финансискиот проблем и промената во филозофијата на образованите телевизиски програми придонесоа за завршувањето на серијата.

Batch 40
Result: Се смета дека бурата, која се наоѓа околу 645 милји (1040 км) западно од островите Капе Верде, ќе се разреши пред да ги закачи земните простори, наведуваат прогнозистите.

Batch 40
Result: Федор моментално има ветер од 105 милји на час (165 км/h) и се движи кон северозапад.

Batch 40
Result: Федор е најсилниот тропски циклон досега регистриран на источни и јужни делови на Атлантикот од појавата на сателисните слики, а само третиот мажен ураган во историјата источно од 35°Д.

Batch 40
Result: На 24 септември 1759 година, Артур Гасин поставува 9.000 годишна концесија за пивоварната Сент Јемс Гејт во Даблин, Ирска.

Batch 40
Result: По 250 години, Гуинс растe до глобален бизнис кој годишно генерира 10 милијарди евра (14.7 милијарди американски долари).

Batch 40
Result: Џони Рид, ко-воzaч за тимот A1GP Новозеланд, денес направи историска улогина со тоа што легално го управли најбрзото патување над 48-годишниот Акулендски пристанишен мост, Нов Зеланд.

Batch 48
Result: Мистер Реид успеа да го управува автомобилот на Нова Зеландија A1GP, "Black Beauty" со брзини над 160 км/h седам пати прекуสะвртот.

Batch 48
Result: Полицијата од Нова Зеландија имаше проблеми да користат своите радари за мерење на брзината за да го видат колку забрза Mr Reid поради фактот дека Black Beauty е многу низок, а полицијата успеа да го регистрира Mr Reid само кога забрза до 160 км/h.

Batch 48
Result: Во последните 3 месеци, повеќе од 80 притворени лица биле ослободени од Централната стапаница без формално обвинение.

Batch 48
Result: На април оваа година, судот на Јон Главин издаде временно нарежение против обемот за принуда на ослободување на оние задржени повеќе од 24 часа по прием каде што не добиле слушање од судовиот комунатор.

Batch 48
Result: Комisionерот поставува казна за отпочнување, ако биде одобрена, и формализира обвиненијата доставени од офицерот кој ги задържа. Обвиненијата потоа се вметнуват во компјутерната база на податоци на државата каде што случајот се следи.

Batch 48
Result: Огнот и означува датум за правото на осомниченокот на брзо судење.

Batch 48
Result: Питер Костело, австралиски финансерот и човек највероватно да ја замени шефката на Либералната партија, Јохн Хавард, го крена поддршката за нуклеарна енергетска индустрија во Австралија.

Batch 48
Result: Мистер Костело рече дека кога нуклеарната генерирачка енергија ќе стане економски прифалива, Австралија треба да го проследи нејзиното користење.

Batch 56
Result: „Ако почне да се користи комерцијално, треба да го добиеме. Тоа е, нема првобитна возраза кон нуклеарната енергија“, рече Столсто.

Batch 56
Result: Според АНСА, “полицијата била загричена поради неколку силни удари кои ги сакаат да може да започне целосна војна за наследство.”

Batch 56
Result: Полицијата рече дека Ло Пиколо имаше предност бидејќе бил десникот на Провенцовано во Палермо и неговиот поголем искуство го доби довербата на постарата генерација на босови додека ја следеа политиката на Провенцовано да остане колку што е можно помалку видлив додека ги засилуваа своите мрежи за моќ.

Batch 56
Result: Овие босови биле огранитени од Провенцовано кога тој го запре над војната водена од Риина против државата која го доби и Жанвио Фалоне и Паоло Борселино во 1992 година.

Batch 56
Result: Р затоа, шефот на компанијата Apple, Стив Џобс, ја представиле уредната со тоа што крена сцена и извлече телефонот iPhone од карсекот на панталите.

Batch 56
Result: За време на неговата два часа долга реториска увертюра, тој изјави дека „Денес Апл ќе го преобрази телефонот, денес ќе правиме историја“.

Batch 56
Result: Бразил е најголемата земја со римско католички верници на светот, а Римската католичка црква континуирано се спротивува на легализирањето на еднополовата браковална практика во земјата.

Batch 56
Result: Националниот конгрес на Бразил дебатираше за легализирање уште 10 години, а вакви браковишта моментално се законни само во Рио Гранде до Сул.

Batch 64
Result: Предложете ја оригиналната сметка беше напишана од порасната градоначалница на Сао Пауло, Марта Супици. Предложените закони, по што беа изменети, сега се во раце на Роберто Џеферсон.

Batch 64
Result: Протестантите се надеваат да соберат петиција од 1,2 милион потписи за да ја предат на Националниот конгрес во ноември.

Batch 64
Result: Подеднаква невидливоста дека многу фамилии бараат правна помош за да се борат против изгонувањето, беше одржана средба на 20 март во Централната правна служба на источниот брег за жртвите на шинема со станот.

Batch 64
Result: Кога ги починителите започнаа да споделуваат што им се случило, повеќето од семејствата вклучени внемајќи го сознавањето дека Каролин Вилсон од OHA ги украдна депозитите за обезбедување и избегаа од градот.

Batch 64
Result: Севдачите во Локвуд Гарденс веруваат дека може да има уште 40 фамилии или повеќе кои бидат процесувани за искршување, бидејќи научија дека полицијата на OHA исто така ги истражува други обло поставени во Окланд кои би можеле да бидат вклучени во скапокот со станките.

Batch 64
Result: Групата откажа онатпрема на стадион „Војна патека“ во Мауи, кој требало да го посетуваат 9.000 луѓе, и се извини на фановите.

Batch 64
Result: Управната компанија на групата „ХК Мениџмент Инц.“ немаше првобитна причина кога ја отфрлија на 20 септември, но следната ден ги навеле логистички причини.

Batch 64
Result: Светрените грчки адвокати, Сакис Кечагиолу и Ѓорѓе Николакулос биле затворени во Коридалус, пазарите на Атина, бидејќи биле прогласени виновници за земање попуштаи и корупција.

Batch 72
Result: Како резултат на тоа, се појави голем скандал во гршката правна заедница поради откривањето на незаконски постапки кои ги стореа судии, адвокати, советодатели и обвирувачи во минатите години.

Batch 72
Result: Пред неколку недели, по информациите објавени од новинарката Макис Триантафилопулос во нејзиното популарно телевизиско шоу “Ζούγκλα” во Алка, пратеникот и адвокат Петрос Мантувалос беше отстранет од неговите позиции бидејќи ги имал неговите канцеларија во незаконска корупција и злоупотреба на службена должност.

Batch 72
Result: Освен тоа, врховниот судија Евангелос Калусис е притворён бидејќи беше осуден за корупција и дегенеративно однесување.

Batch 72
Result: Робертс рамнодуштно одби да каже кога верува дека животот почнува, важен прашалник при разгледокот на етиката поврзана со абортувањето, ресекајќи дека би било неетично да коментира спецификите на веројасните случаи.

Batch 72
Result: Сепак, тој повторно ја изјави нејзиното ранечко тврдење дека „Roe v. Wade“ е “одлуката која е утвдена како закон на државата”, ги напоменувајќи важноста на конзистентните судови на Врховниот суд.

Batch 72
Result: Тој исто така поттикна дека верувал во имплицираното право на приватност кое зависело од решението Ро.

Batch 72
Result: Маруохидор заврши на врвот на таблата, шест точки испред Носа во втор ред.

Batch 72
Result: Дветите страни ќе се сретат во големото полуфинале каде што Носа победи со 11 точки.

Batch 80
Result: Маручидоре потоа победи над Кабултур во финалето пред квалификацијата.

Batch 80
Result: Hesperonychus elizabethae е вид од фамилијата Дромаеозаврида и е удавен брат на Велоцираптор.

Batch 80
Result: Оваа полно пернато, топли крвни растенија, птица делот беше верувано дека шеткало вертикално на два нога со дланки како кај Велоцираптор.

Batch 80
Result: Нејзината втора прст беше поголема, што доведе до името Хеспероникус, кое значи “западна прст”.

Batch 80
Result: Освен топлата, екстремните временски услови го нарушуваат наподот на спасувањето.

Batch 80
Result: Питман предложи дека условите нема да се подопрат до некоја покрајдна недела.

Batch 80
Result: Количеството и дебелината на ледените паковања, според Питман, е најлошата која била до сега за ловците на тюлени за последните 15 години.

Batch 80
Result: Вестите се ширеа во општата заедница Ред Лејк денес, бидејќи се одржаа погребни церемонии заЏеф Вејс и три од деветте жртви, додека уште еден ученик беше арестуван во врска со наоружавањето во училиште на 21 март.

Batch 88
Result: Официјално, властите рекоа малку, освен денес да потпорат арестот.

Batch 88
Result: Сепак, извор близок до распитката му рече на Minneapolis Star-Tribune дека тоа е Луј Журдан, 16-годишниот син на претседавачот на племенското јадро Ред Лејк, Флод Журдан.

Batch 88
Result: Не е познато на овие вести какви обвиненија ќе бидат доставени или што го довело надлежноста кон дедото, но федерален суд започна постапки за помлад особено.

Batch 88
Result: Лодин исто така рече дека официјалните лица одлучиле да го отcancelledувањето на втор настап за да ги спасат Афганците трошоците и ризикот од безбедност од друга изборна процедура.

Batch 88
Result: Дипломатите рекоа дека пронашле доволно нејасност во афганистанската уставна согласност за да го одлучат рулетот како бесценовен.

Batch 88
Result: Ова се спротивно на поранешните извештаи, кои рекле дека отпадот на повторното гласање би било во супротна согласност со уставот.

Batch 88
Result: Авионот бил насочен кон Иркутск и се водеше од внатрешни трупи.

Batch 88
Result: Една истрага беше установена за да се истражи.

Batch 96
Result: Ил-76 веќе долго е важен дел и на руската и советската воена армија од 1970тите, а минатиот месец го доживеа сериозен инцидент во Русија.

Batch 96
Result: На 7 октомври, моторот се оддело на полето при исликување, без повредени луѓе. Русија воведуваше внатрешна забрана за летање на Ил-76 по тоа несреќа.

Batch 96
Result: 800 милји од системот на транс-Алкаска гасоводоводна линија биле затворени поради протеклина на илјада бочилки суров нефт јужно од Фаирбанкс, Алкаса.

Batch 96
Result: По дефектот на струја следен по редовен тест на системот за пожарна команда, вентилите за ослободување притисок се отвориле и прљаво масло ис curio near pump station 9 на Ft Greely.

In [53]:
references = [[ref] for ref in text_mkd]
references[:10]

[['Во понеделникот научниците од медицинскиот факултет на Универзитетот Стенфорд објавија дека измислиле нова алатка за дијагностицирање со којашто се подредуваат клетките според типови: се работи за мал чип за печатење кој може да се произведе со помош на стандардни инк-џет печатачи, и тоа по цена од околу еден американски цент.'],
 ['Водечките истражувачи сметаат дека ова може да доведе до рано откривање на рак, туберколоза, ХИВ и маларија кај пациенти кои живеат во земји со низок животен стандард, каде стапката на преживување од болести како рак на дојка може да биде двојно пониска отколку во побогатите држави.'],
 ['JAS 39C Грипен се сруши на писта околу 9:30 am по локално време (2:30 UTC) и експлодираше, поради што аеродромот е затворен за комерцијални летови.'],
 ['Утврдено е дека пилот бил Дилокрит Патави, водачот на ескадрилата.'],
 ['Локалните медиуми известуваат за аеродромско противпожарно возило кое се превртело додека пожарникарите во него одговарале на повик.'],
 ['28-годишниот Видал од Севиља се придружи на екипата на Барселона.'],
 ['Откако се пресели во главниот град на Каталонија Видал одигра 49 натпревари за клубот.'],
 ['Протестот започна околу 11:00 часот по локално време (UTC+1) во Вајтхол, на спротивната страна од влезот чуван од полицијата на Даунинг Стрит, службената резиденција на премиерот.'],
 ['Веднаш по 11:00 часот демонстрантите го блокираа сообраќајот кон север во Вајтхол.'],
 ['Во 11:20 часот, полицијата побара од протестантите да повлечат на тротоарот, наведувајќи дека тие треба да ги урамнотежат правото на протестирање со застојот во сообраќајот.']]

In [54]:
bleu.compute(predictions=predictions_mkd, references=references)

{'bleu': 0.18143717987881253,
 'precisions': [0.5106811769447803,
  0.23981520369592607,
  0.13327487943884261,
  0.07290233837689133],
 'brevity_penalty': 0.9768934704505555,
 'length_ratio': 0.9771563607719574,
 'translation_length': 2481,
 'reference_length': 2539}

In [55]:
chrf_score = sacrebleu.corpus_chrf(predictions_mkd, references)
print(f"chrF: {chrf_score.score:.2f}")

chrF: 46.60

## Few-Shot Cross-lingual prompt (ENG->MKD) in macedonian language

In [56]:
instruction = f"""Преведи го следниот текст од **Англиски** во **Македонски**. Само испечати го преводот на македонски јазик. Не додавај никакви објаснувања или дополнителни примери.
  Пример 1
  Англиски: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
  Одговор (Македонски): Во понеделник, во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
  Пример 2
  Англиски: A sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.
  Одговор (Македонски): Еден спортски натпревар трае 90 минунти, односно две полувремиња по 45 минути со одмор меѓу нив во траење од 15 минути. Ако има подолги прекини во играта, таа се продолжува така што се надополнува изгубеното време.
  Пример 3
  Англиски: With the help of this tool, cells can be sorted by type, which means that diseases caused by small cells can be diagnosed.
  Одговор (Македонски): Со помош на оваа алатка, клетките можат да се подредуваат по тип, што значи дека можат да се дијагностицираат болести предизвикани од мали клетки.
  Пример 4
  Англиски: This study focuses on the development of new methods for data analysis.
  Одговор (Македонски): Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
  Пример 5
  Англиски: In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
  Одговор (Македонски): Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.
"""

In [57]:
predictions_mkd = batch_translate(text_eng,instruction,max_new_tokens=128,lang_code="mkd",language="Македонски")

Batch 0
Result: Во вторник, научници од Школот за медицина на Универзитетот Стенфорд објавија за откритие на нова дијагностичка алатка која може да ги сортира клетките по вид: мал принтер кој може да се произведе користејќи стандардни струјни принтери за можноста да се направи за околу една американска цента по парче.

Batch 0
Result: Главните истражувачи велат дека ова може да доведе до ранко откривање на рак, туберкулоза, ХИВ и маларија кај пациентите во земјите со низок доход, каде што стапките на преживување за болести како ракот на матката честопати бидат половина од оние во богатите земји.

Batch 0
Result: Јасе 39Ц Грипен се урна на писта околу 9:30 часот локално време (0230 UTC) и експлодираше, што го затвори аеролифтот за комерцијални полети.

Batch 0
Result: Пилото беше идентификуван како Сквадрон лидер Дилиокрит Паттавеи.

Batch 0
Result: Локалните медиуми ја сообщаваат пожарната возилка на авионската леталиштем набавка се преклошила додека реагираше.

Batch 0
Result: Видал, кој е на 28 години, се приклучи на Барса пред три сезони, од Севиља.

Batch 0
Result: По преселување во кадената на Каталонија, Видал одиграл 49 натвки за клубот.

Batch 0
Result: Протестот започна околу 11:00 локално време (UTC+1) на Вајтлиха спротивно на полициски надворешна врата кон Донинг Стрит, официјалната резиденција на премиерката.

Batch 8
Result: Непосредно по 11:00 часот, демонстрантите блокираа сообраќеј на северната патека во Вајтлиха.

Batch 8
Result: Во 11:20, полицијата побара од протестувачите да се вратат на патеката, со образложение дека треба да ги балансираат правото на протест со зголемувањето на сообраќејот.

Batch 8
Result: Околу 11:29, протестот се движеше нагоре низ Вајтхолл, покрај Трафалгарскиот плоштак, покрај Стренд, минувајќи покрај Алдвик и нагоре кај Кингсваи кон Хоборн каде што Конзервативната партија одржа својот Спешен форум во хотелот Гранд Коннаурт Ромс.

Batch 8
Result: Рекордот на Надал против канадскиот играч е 7-2.

Batch 8
Result: Непостои против пораза од Раоник во Отвореното во Брисбен.

Batch 8
Result: Надал освои 88% нетни точки во натпредакот, освојувајќи 76 точки во првиот сервис.

Batch 8
Result: По натпреварот, Кралот на Песок рече: „Јас сум само возбуден што повторно сум во финалето на најважните настани. Јастум тука за да се обидам да го осволам овој натпреварувач.“

Batch 8
Result: “Панама Пеперс” е општо приемлив термин за околку десет милиони документи од правната фирма во Панама, Мосак Фонсека, кои беа изложени пред медиумите во пролетта 2016 година.

Batch 16
Result: Документата покажаа дека 14 банки помогнала на богатите клиенти да скрии ги милиардите американски долари богатство за да избегнат данок и други регулации.

Batch 16
Result: Британското весник "The Guardian" наведна дека Deutche Bank контролираше околу третина од 1200 компании-самостојки кои беа користени за остварување на ова.

Batch 16
Result: Подека имаше протести широко во светот, повеќе криминални достави и лидерите на владите на Исланд и Пакистан конечно отстапија.

Batch 16
Result: Родена во Хонг Конг, Ма учеше на Универзитет во Нов Јорк и Правен факултет во Харвард, и некогаш имала американска трајна резиденција “зелен картон”.

Batch 16
Result: Хсиеј намекна за време на изборите дека Ма може да избегне земјата за време на криза.

Batch 16
Result: Хсие додаде и аргументираше дека фотогеничната Ма била повеќе стил отколку суштина.

Batch 16
Result: Немајќи ги вашите предислови, туку гледајќи само да го преведем текстот, еве го преводот:

Batch 16
Result: Играчот на денот денес е Алекс Овечкин од Вашингтон Кепз.

Batch 24
Result: Тој постигна 2 голови и 2 асистенции во победата на Вашингтон над Атланта Трасхерс со резултат 5-3.

Batch 24
Result: Првата асистенција на Ovechkin токму вечерва беше на головозавршниот погодок на новак Никлас Бакстром.

Batch 24
Result: Ова втори погодок на ноќта беше неговиот 60ти погодок сезонава, станувајќи прв играч кој постигна 60 или повеќе голови во сезоната од 1995-96, кога Јаромир Јагр и Марио Лемиев секој стигна до тоа знамење.

Batch 24
Result: Батен беше рангиран на 190-то место на листата на 400 најбогати Американци во 2008 година, со проценето богатство од 2.3 милиарди долари.

Batch 24
Result: Тој се дипломираше на Колеџот за уметности и науки на Универзитетот во Вирџинија во 1950 година и беше значаен донатор за таа институција.

Batch 24
Result: Затворската каса во Абу Гариб, Ирак, бил запален за време на беспорядък.

Batch 24
Result: Затворот стана познат после откритие на злопотворивоста кон затворниците кога американските сили ги презедеа.

Batch 24
Result: Пикет Јр. се повреди во Гран при на Сингапур 2008 непосредливо после рана спиерка за Фернандо Алонсо, предизвикувајќи ја синатата кола.

Batch 32
Result: Кога автомобилите пред Алونسо влегоа во гаража за доливање во рамките на безбедноста, тој се поврза во пакулот и освои победа.

Batch 32
Result: Пикет Јр. беше отстранет по Гранд привредата на Венгрија во 2009 година.

Batch 32
Result: На точно 8:46 часот, над градот се спушти тишина, означувајќи ги токму вообичаениот момент кога првиот авион-ракет погоди својата цел.

Batch 32
Result: Две зраци светлина биле поставени да укажуваат кон небото низ ноќта.

Batch 32
Result: Изградта е во тек за пет нови небогрижи на локацијата, со транспортен центар и парк на меморија во средината.

Batch 32
Result: PBS шоуто има повеќе од дваесет награди "Емии", а неговата потрага е само полека од онаа на "Сесми Стреет" и "Мстер Роџерс’ Наборбиг”.

Batch 32
Result: Секоја епизода од шоуто би се фокусирала на тема во специфична книга и потоа би ја истражувала таа тема преку повеќе нарачања.

Batch 32
Result: Секоја емисија би исто така нудерила препорачања за книги кои децата треба да ги бараат кога одат во библиотеката.

Batch 40
Result: Џон Грант, од WNED Buffalo (станцијата на Reading Rainbow) рече: „Reading Rainbow научи децата зошто да читаат,... љубов кон читањето — [шобот] ги охрабра научениците да вземат книга и да читаат.“

Batch 40
Result: Некои, вклучувајќи го иЏон Грант, веруваат дека и финансискиот проблем и промената во филозофијата на програмите за образователска телевизија придонесоа за завршувањето на серијата.

Batch 40
Result: Наводната бура, која се наоѓа околу 645 милии (1040 км) западно од островите Кап де Верде, веројатно ќе се разреши пред да ги закажува некои копнени простори, наведуваат прогнозистите.

Batch 40
Result: Фред моментално има ветер од 105 милји на час (165 км/h) и се движи кон северозапад.

Batch 40
Result: Фред е најсилниот тропски циклон досега регистриран на источни и јужни делини на Атлантикот од појавата на сателисните слики, и само третиот мажен ураган во историјата источно од 35°ЗД.

Batch 40
Result: На 24 септември 1759 година, Артур Гаус сепак потпиша налог за 9.000 годишна концесија за пивоварната Сент Јемс Гејт во Даблин, Ирска.

Batch 40
Result: 250 години подоцна, Гуинс е згратен на глобален бизнис кој годишно генерира 10 милијарди евра (14.7 милијарди американски долари).

Batch 40
Result: Џони Рид, ко-воzaч на екипата A1GP Нова Зеландија, денес направи историска увертка со тоа што легално го управуваше најбрзото патување над 48-годишниот пристанишен мост АUCKLAND, Нова Зеландија.

Batch 48
Result: Мистер Реид успеа да управува со A1GP автомобилот на Нова Зеландија, "Black Beauty" со брзини над 160 км/h седам пати преку мостот.

Batch 48
Result: Полицијата на Нова Зеландија имаше проблеми да користат своите радари за мерење на брзината за да ги добијат информациите колку што забрзо одеше господинот Раид поради фактот дека коњот Блек Беј е многу низок, а полицијата успеа да го регистрираат господинот Раид само кога забрза до 160км/h.

Batch 48
Result: Во последните 3 месеци, повеќе од 80 особени невинни биле ослободени од Централната касарна без формално обвинение.

Batch 48
Result: На април годинава, судот на Јуџин издаде временно наречение против установата за да ја принуди ослободувањето на оние задржени повеќе од 24 часа по прием, кои не добиле слушање пред судовиот комисар.

Batch 48
Result: Комisionерот поставува кауција, ако биде одобрена, и формализира обвиненијата доставени од офицерот кој ги задържа. Обвиненијата потоа се вметнуват во компјутерната база на податоци на државата каде што случајот се следи.

Batch 48
Result: Огнот исто така означува датум за правото на осомничењето на брзо судење.

Batch 48
Result: Питер Костело, австралиски финансерот и човек најверојатно да наследи премиерката Џон Хавард како лидер на Либералната партија, ја истакна својата поддршка кон нуклеарна енергетска индустрија во Австралија.

Batch 48
Result: Ми Костело рече дека кога нуклеарната генерирачка способност ќе стане економски видна, Австралија треба да го проследи нејзиното користење.

Batch 56
Result: „Ако почне да се користи комерцијално, треба да го добиеме. Тоа значи, нема отстапност во принципите“, рече Костело.

Batch 56
Result: Според АНСА, „полицијата била загричена поради неколку силни удари на високо ниво кои ги сакаа да започнат целосна војна за наследство.“

Batch 56
Result: Полицијата рече дека Ло Пиколо имаше надлежникот бидејќе бил десниот рак на Провенцовано во Палермо и неговиот поголем искуство го добило почитувањето на постарата генерација на босови додека ги следеа политиките на Провенцовано за останување колку што е можно помалку и за засилување на нивната мрежа на власт.

Batch 56
Result: Овие шефови биле огранитени од Провенцовано кога тој ги запре на војната водена од Риина против државата која го доби и Жанвио Фалоне и Паоло Борселини во 1992 година.

Batch 56
Result: Извршниот директор на Apple, Стив Джобс, ја представил уредната со тоа што кренал на сцена и извлекол iPhone од карсекот на неговите панталоне.

Batch 56
Result: За време на неговата два часа долга реч, тој изјави дека „Денес Апл ќе го преобрази телефонот, денес ќе правиме историја“.

Batch 56
Result: Бразил е најголемиот Римско-католички град на Земјата, а Римската католичка црква континуирано се спротивува на легализирањето на еднополовата брачна согласност во земјата.

Batch 56
Result: Националниот конгрес на Бразил ги дебатира легализирањето уште 10 години, а ваквите цивилни браковински церемонии моментално се законни само во Рио Гранде ду Сул.

Batch 64
Result: Оригентниот предлог беше напишан од пораснатата градонаредник на Сао Пауло, Марта Супици. Предложетелното законување, по што беше изменето, сега е во рацете на Роберто Жеферсон.

Batch 64
Result: Протестантите се надеваат да соберат петиција со 1,2 милион потписи за да ја претстават кон Националниот Конгрес во ноември.

Batch 64
Result: По што станало очигледно дека многу фамилии бараат правна помош за да се борат против изгонувањето, беше одржана средба на 20 март во Централната правна служба на источниот брег за жртвите на скапоцена вежба со стан.

Batch 64
Result: Кога ги споделија настаните што се слушнале, повеќето фамилии вклучени внемајќи ги сознание дека Каролин Вилсон од OHA ги украдела депозитите за обезбедување и избегаа од градот.

Batch 64
Result: Наставниците во Локвуд Гарденс веруваат дека може да има уште 40 фамилии или повеќе кои бидат во опасност од искршување, бидејќи научија дека полицијата на OHA исто така ги истражува други стански објекти во Окланд кои можат да бидат вклучени во правната превара.

Batch 64
Result: На групата ја отмена својата концерт во стадионот „Војна патека“ на Мауи, која требаше да биде посетувана од 9.000 луѓе, и се извини кон фановите.

Batch 64
Result: Управната компанија на групата „Бенд“, HK Management Inc., нема да ги наведат првичните причини кога откажаа на 20 септември, туку следната одредница беше дадена наредниот ден.

Batch 64
Result: Постаритете ги грчките адвокати, Сакис Кечагиолу и Џорџ Николакуполи биле затворени во центарското заточение на Коридал в Атина, бидејќи биле признати виновни за земачкe на мито и корупција.

Batch 72
Result: Како резултат на тоа, се подеси скандал во гршката правна заедница поради откривањето на незаконски постапки кои ги стореа судии, адвокати, советодатели и обвирувачи во минатите години.

Batch 72
Result: Пред неколку недели, по информациите објавени од новинарката Макис Триантафилопулос во нејзиното популарно телевизиско шоу "Зоугла" во Alpha TV, пратеникот и адвокат Петрос Мантувалос беше отстранет од неговите позиции бидејќи ги имал вклучено во незаконски корупционерски практики.

Batch 72
Result: Освен тоа, врховниот судија Евангелос Калусис е затворено поради користење на корупција и деликвентно однесување.

Batch 72
Result: Робертс рамнодуштно одби да каже кога верува дека животот почнува, важен прашалник при разгледокот на етиката на абортурите, ресекајќи дека би било неетично да коментира спецификите на веројасните случаи.

Batch 72
Result: Сепак, тој повтори неговото сфалено мислење дека случајот Roe v. Wade е “одлуката поставена како закон на државата”, ги напоменувајќи важноста на конзистентните судови на Врховниот суд.

Batch 72
Result: Тој исто така поттикна дека верувал во имплицираното право на приватност кое зависело од решението Ро.

Batch 72
Result: Маррухидор заврши на врвот на таблата, шест точки испред Носа во втор ред.

Batch 72
Result: Двете страни ќе се сретнувале во големото полуфинале каде што Носа победи со 11 точки.

Batch 80
Result: Маррухидор потоа победи над Кабултур во полуфиналето.

Batch 80
Result: Hesperonychus elizabethae е вид од фамилијата Дромаеозаврида и е роднина на Велоцираптор.

Batch 80
Result: Оваа полно перната, топли крвни животни птица од репката била сметана дека ходила стопа на два нога со дланки како кај Velociraptor.

Batch 80
Result: Нејзината втора прст беше по голема, што доведе до името Хесперионикус, кое значи “западна прст”.

Batch 80
Result: Освен удирањето со ледот, екстремните временски услови ги нарушуваат напорите за спасување.

Batch 80
Result: Питман предложи дека условите нема да се подобрат пред неколку недели.

Batch 80
Result: Количеството и дебелината на ледените паковања, според Питман, е најлошата која е забележана за ледери во последните 15 години.

Batch 80
Result: Вестите се ширеа во општината Ред Лејк денес кога се одржаа погребни церемонии заЏеф Вејс и три од деветте жртви, бидејќи уште еден ученик беше арестуван во врза со насилството во училиштето од 21 март.

Batch 88
Result: Овластувањето неофицијално констатираше само дека денес беше одземен еден човек.

Batch 88
Result: Сепак, извор со знаења за истрагата му рече на Minneapolis Star-Tribune дека тоа беше Луи Журдан, 16-годишниот син на претседавачот на резервацијата Ред Лејк Флод Журдан.

Batch 88
Result: Не е познато на овие вести какви обвиненија ќе бидат доставени или што ги довело властите кон дедото, но во федерален центар започнале постапки за помлад случај.

Batch 88
Result: Лодин исто така рече дека официјалните лица одлучиле да го отcancelled повторниот избир за да ги спасат Афганците трошоците и ризикот од безбедност од друга изборна процедура.

Batch 88
Result: Дипломати рекоа дека пронашле доволно нејасност во афганската уставна рамка за да го одлучат рулетот како бесцелен.

Batch 88
Result: Ова се спротивно на поранешните извештаи, кои рекле дека оттекувањето на повторното гласање би било против уставната постапка.

Batch 88
Result: Авионот бил насочен кон Иркутск и бил управуван од внатрешни трупи.

Batch 88
Result: Една истрага беше установена за да се истражи.

Batch 96
Result: Ил-76 биле важна компонента на руската и советската воена армија од 1970-тите, а веќе го исплашија сериозен инцидент во Русија минатиот месец.

Batch 96
Result: На 7 октомври моторот се оддело на полето при исфрлување, без повредени луѓе. Русија воведуваше внатрешна забрана за полетување на Ил-76 по тоа несреќа.

Batch 96
Result: 800 милји од системот на Транс-Алкаска гасоводова биле затворени поради протекда на илјада бочилки сурова нафта јужно од Фаирбанкс, Алкаса.

Batch 96
Result: Поплак следеше по редовен тест на системот за пожарна команда, што доведе до отворање на растеремите и протекливост на нафта блиску до насојницата на Fort Greely 9.

In [58]:
references = [[ref] for ref in text_mkd]
references[:10]

[['Во понеделникот научниците од медицинскиот факултет на Универзитетот Стенфорд објавија дека измислиле нова алатка за дијагностицирање со којашто се подредуваат клетките според типови: се работи за мал чип за печатење кој може да се произведе со помош на стандардни инк-џет печатачи, и тоа по цена од околу еден американски цент.'],
 ['Водечките истражувачи сметаат дека ова може да доведе до рано откривање на рак, туберколоза, ХИВ и маларија кај пациенти кои живеат во земји со низок животен стандард, каде стапката на преживување од болести како рак на дојка може да биде двојно пониска отколку во побогатите држави.'],
 ['JAS 39C Грипен се сруши на писта околу 9:30 am по локално време (2:30 UTC) и експлодираше, поради што аеродромот е затворен за комерцијални летови.'],
 ['Утврдено е дека пилот бил Дилокрит Патави, водачот на ескадрилата.'],
 ['Локалните медиуми известуваат за аеродромско противпожарно возило кое се превртело додека пожарникарите во него одговарале на повик.'],
 ['28-годишниот Видал од Севиља се придружи на екипата на Барселона.'],
 ['Откако се пресели во главниот град на Каталонија Видал одигра 49 натпревари за клубот.'],
 ['Протестот започна околу 11:00 часот по локално време (UTC+1) во Вајтхол, на спротивната страна од влезот чуван од полицијата на Даунинг Стрит, службената резиденција на премиерот.'],
 ['Веднаш по 11:00 часот демонстрантите го блокираа сообраќајот кон север во Вајтхол.'],
 ['Во 11:20 часот, полицијата побара од протестантите да повлечат на тротоарот, наведувајќи дека тие треба да ги урамнотежат правото на протестирање со застојот во сообраќајот.']]

In [59]:
bleu.compute(predictions=predictions_mkd, references=references)

{'bleu': 0.18670442399530277,
 'precisions': [0.5127996749288907,
  0.24904701397712833,
  0.13976116762494473,
  0.07727903748264692],
 'brevity_penalty': 0.968802570797529,
 'length_ratio': 0.9692792437967703,
 'translation_length': 2461,
 'reference_length': 2539}

In [60]:
chrf_score = sacrebleu.corpus_chrf(predictions_mkd, references)
print(f"chrF: {chrf_score.score:.2f}")

chrF: 47.32

## Few-Shot Cross-lingual prompt (ENG->MKD) in serbian language

In [61]:
instruction = f"""Преведи следећи текст са **Eнглеског** на **Mакедонски** језик.
Само испиши превод на македонски језик. Не додавај никаква објашњења или додатне примере.

Пример 1
Енглески: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Одговор (Mакедонски): Во понеделник, во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.

Пример 2
Енглески: A sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.
Одговор (Mакедонски): Еден спортски натпревар трае 90 минути, односно две полувремиња по 45 минути со одмор помеѓу нив во траење од 15 минути. Ако има подолги прекини во играта, таа се продолжува така што се надополнува изгубеното време.

Пример 3
Енглески: With the help of this tool, cells can be sorted by type, which means that diseases caused by small cells can be diagnosed.
Одговор (Mакедонски): Со помош на оваа алатка, клетките можат да се подредуваат по тип, што значи дека можат да се дијагностицираат болести предизвикани од мали клетки.

Пример 4
Енглески: This study focuses on the development of new methods for data analysis.
Одговор (Mакедонски): Оваа студија се фокусира на развојот на нови методи за анализа на податоци.

Пример 5
Енглески: In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
Одговор (Mакедонски): Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.
"""

In [62]:
predictions_mkd = batch_translate(text_eng,instruction,max_new_tokens=128,lang_code="srb",language="Македонски")

Batch 0
Result: На понеделник, научници од Школот за медицина при Универзитетот Стенфорд ја анонсираа иновацијата на нова дијагностичка алатка која може да сортира клетки според вид: мал принтер кој може да се произведе користејќи стандардни струјни принтери за можноста да се направи за околу една американска центар.

Batch 0
Result: Главните истражувачи велат дека ова може да доведе до ран детектирање на рак, туберкулоза, ХИВ и маларија кај пациентите во земјите со низок доход, каде што стопата на преживување за болести како ракот на матката може да биде половина од онаа во богатите земји.

Batch 0
Result: JAS 39C Gripen се урна на писта околу 9:30 бирол локално време (0230 UTC) и експлодираше, што го затвори авиолетот за комерцијални летови.

Batch 0
Result: Пилото беше идентификуван како Сквадрон лидер Дилиокрит Паттавеи.

Batch 0
Result: Локалните медиуми ја сообщаваат пожарната возилка на авионската леталиштем располагање се преклопувала додека реагирала.

Batch 0
Result: Видал, кој е на 28 години, се приклучи на Барса пред три сезони, од Севиља.

Batch 0
Result: По преселување во кадената, Видал одигра 49 натпревари за клубот.

Batch 0
Result: Протестот започна околу 11:00 локално време (UTC+1) на Вајтлиха спротивно на полициски заштитен пат кон Донинг Стрит, официјалната резиденција на премиерката.

Batch 8
Result: Непосредно по 11:00 часот, демонстрантите блокираа сообраќеј на северната патека во Вајтхолл.

Batch 8
Result: Во 11:20, полицијата побара од протестувалиците да се вратат на патеката, со образложение дека треба да ја балансираат правото на протест со зголемувањето на сообраќејот.

Batch 8
Result: Околу 11:29, протестот се крена над Вајтли, покрај Трафалгарскиот пловидбен парк, покрај Стренд, минувајќи покрај Алдвич и кон Кингсваи во насока кон Холборн каде што Конзервативната партија одржа свој весник на пролет во хотелот Гранд Коннокнут Ромс.

Batch 8
Result: Рекордот на Надал во директните дуели против Канаданецот е 7-2.

Batch 8
Result: Непостои го поразот од Раоник на Отвореното во Бризбејн.

Batch 8
Result: Надал освои 88% нетни поели во натпреварот, освојувајќи 76 поели во првиот сервис.

Batch 8
Result: По натпреварот, Кралицата на Песок рече: „Јас сум само возбудено поради враќањето во финалето на најважните настани. Јастувам да опитам да го осволам овој натпревар.“

Batch 8
Result: “Панама Пејперс” е општ термин за околку десет милиони документи од правната фирма Мосак Фонсека во Панама, кои беа изложени пред приопштение во пролетта 2016 година.

Batch 16
Result: Документата покажаа дека 14 банки помогнал на богатите клиенти да скриија милиарди американски долари богатство за да избегнат данок и други регулации.

Batch 16
Result: Британското весник "The Guardian" наведна дека Deutche Bank контролираше околу третина од 1200 компании-самостојки кои беа користени за остварување на ова.

Batch 16
Result: Се одржаа протести широко во светот, повеќе кривични достави и лидерите на владите на Исланд и Пакистан конечно отстапија.

Batch 16
Result: Родена во Хонг Конг, Ма студираше на Универзитет во Њујорк и Правен факултет во Харвард, и некогаш ја држела американската перманентна адреса “зелен картон”.

Batch 16
Result: Хсиеј го укажа подоцна на изборите дека Ма може да избегне земјата за време на криза.

Batch 16
Result: Хсие додаде и аргумент дека фотогеничната Ма беше повеќе стил отколку суштината.

Batch 16
Result: Неколку гичеше овие обвинувања, Ма победи убедително на платформа која бара поблизок контакт со Кинескиот континент.

Batch 16
Result: Играчот на ден денес е Алекс Овечкин од Вашингтон Кепз.

Batch 24
Result: Тој постигна 2 гола и 2 асистенции во победата на Вашингтон над Атланта Трасхери со резултат 5-3.

Batch 24
Result: Првиот асист на Ovechkin токму вечерва беше на головозавршниот погодок од новак Никлас Бакстром.

Batch 24
Result: Ова го втор погодок на ноќта беше неговиот 60ти погодок сезонава, станувајќи прв играч кој постигна 60 или повеќе голови во сезоната од 1995-96 година, кога Јаромир Јагр и Марио Лемиев секој ја достигнал таа врест.

Batch 24
Result: Батман беше ранкуван на 190-то место на листата на 400 најбогати Американци во 2008 година, со проценети богатство од 2.3 милијарди долари.

Batch 24
Result: Тој се дипломираше на Факултот за либерални науки на Универзитетот во Вирџинија во 1950 година и беше значаен донатор за таа институција.

Batch 24
Result: Затворската каса во Абу Гариб, Ирак, беше запалена за време на беспорядци.

Batch 24
Result: Затворот стануваше познат после откритието за злопотворително третирање на примарите кога американските сили ја презедеа контролата.

Batch 24
Result: Пикет Јр. се повреди во Гранд привремата во Сингапур 2008 непосредно потоа што Фернандо Алонсо направи рано стоп во бокса за сервис, што предизвика излез на сината кола.

Batch 32
Result: Кога автомобилите пред Алونسо влекоа во гаража за доливање, тој се пласи среде шината и освои победа.

Batch 32
Result: Пикет Јр. беше отстранет по Гран при на Унгарија во 2009 година.

Batch 32
Result: На точно 8:46 часот, над градот се спушти тишина, означувајќи го токму моментот кога првиот авион-ракет погоди својата цел.

Batch 32
Result: Две зраци светлина биле поставени да укажуваат кон небото среде ноќ.

Batch 32
Result: Изградбата е во тек на пет нови небосмета на локацијата, со транспортен центар и парк на меморија во просторот во средината.

Batch 32
Result: PBS шоуто има повеќе од дваесет Emmy награди, а неговата потрага е само малку полека од Sesame Street и Mister Rogers' Neighborhood.

Batch 32
Result: Секоја епизода од шоуто би се фокусирала на тема од специфична книга и потоа ја би требало да ја истражи онаа темата преку повеќе приказни.

Batch 32
Result: Секоја уредба би исто така нудерила препорачања за книги кои децата треба да ги бараат кога одат во библиотеката.

Batch 40
Result: Џон Грант, од WNED Buffalo (станицата каде што е дома за “Reading Rainbow”) рече: „Reading Rainbow научи децата зошто да читаат,... љубов кон читањето — [шобот] ги охрабра научникот децата да вземат книга и да читаат.“

Batch 40
Result: Некои луѓе, вклучувајќи го иЏон Грант, веруваат дека комбинација од финансиски проблеми и промена во филозофијата на програмите за образователска телевизија придонесоа за крајот на серијата.

Batch 40
Result: Навредата, која се наоѓа околу 645 милии (1040 км) западно од островите Капе Верде, веројатно ќе се разредува пред да ги закачи неколку земни простори, наведуваат прогнозистите.

Batch 40
Result: Фери моментално има ветер од 105 милји на час (165 км/h) и се движи на северозапад.

Batch 40
Result: Фери е најсилниот тропски циклон досега регистриран на источни и јужни делови на Атлантикот од појавата на сателисните слики, и само трендиот голем ураган во историјата источно од 35°Д.

Batch 40
Result: На 24 септември 1759 година, Арттур Гасин сигнираше договор за наем од 9,000 години за пивоварната Сент Јемес Гејт во Даблин, Ирска.

Batch 40
Result: 250 години подоцна, Гуинс стана глобален бизнис кој годишно генерира 10 милијарди евра (14.7 милијарди американски долари).

Batch 40
Result: Џони Рид, ко-воzaч за тимот A1GP Новозеланд, денес направи историска увертка со тоа што легално го крена најбрзото време над 48-годишниот Акулендскиот пристанишен мост во Нова Зеландија.

Batch 48
Result: Мистер Реид управлише со A1GP автомобилот на Нова Зеландија, "Black Beauty", со брзини над 160 км/h седам пати преку мостот.

Batch 48
Result: Полицијата од Нови Зеланд имаше проблеми да користат своите радари за мерење на брзина за да го добијат колку беше брз Мистер Рид поради фактот дека Бела Лептима е многу ниска, а полицијата успеа да ја регистрира брзината на Мистер Рид само кога забрза до 160 км/h.

Batch 48
Result: Во последните 3 месеци, повеќе од 80 притворени лица биле ослободени од Централната касарна без формално обвинение.

Batch 48
Result: На април годинава, судот на примарен суд издаде вреќна забрана против установата за да ја принудат ослободот на оние задржени повеќе од 24 часа по прием, кои не добиле слушање од судови комисар.

Batch 48
Result: Комisionерот поставува кауција, ако биде одобрена, и формализира ги обвинението водено од офицерот кој го задържа. Обвинението потоа се вметнува во компјутерската база на податоци на државата каде што случајот се следи.

Batch 48
Result: Овие слушања исто така означуваат датум за правото на осомничените на брзо судење.

Batch 48
Result: Питер Костело, австралиски финансерот и човек највероватно да ја наследи функцијата поранешна шеф на Либералната партија, ја изглакна својата поддршка за нуклеарна енергетска индустрија во Австралија.

Batch 48
Result: Ми Костело рече дека кога нуклеарната генерирачка способност ќе стане економски прифалива, Австралија треба да го проследи нејзиното користење.

Batch 56
Result: „Ако почне да се користи комерцијално, треба да го добиеме тоа“, рече Костело. „Тоест, нема првобитна возразна за нуклеарната енергија“, рече Костело.

Batch 56
Result: Според АНСА, „полицијата била загричена поради неколку силни удари на високо ниво кои ги сакаа да започнат целосна војна за наследство.“

Batch 56
Result: Полицијата рече дека Ло Пиколо имаше предност бидејќи бил десниот раце на Провенцовано во Палермо и неговиот поголем опит го добил почитувањето на постарата генерација на босови додека ја преземаа политиката на Провенцовано да останат колку што е можно помиртени додека ги засилуваа своите мрежи за моќ.

Batch 56
Result: Овие босови биле огранитени од Провенцовано кога тој го запре вторјото војната водена од Риина против државата која го доби и Жанвио Фалоне и Паоло Борселино во 1992 година.

Batch 56
Result: Извршниот директор на Apple, Стив Џобс, ја представил уредната со тоа што кренал на сцена и извлекол iPhone од карсекот на панталона.

Batch 56
Result: За време на неговата два часа долга реториска уверзување, тој изјави дека „Денес Апл ќе го преопредели телефонот, денес ќе правиме историја“.

Batch 56
Result: Бразил е најголемата земја со римско католички верници на светот, а Римската катедрала постојанo се спротивува на легализирање на бракот помеѓу луѓе од ист пол во државата.

Batch 56
Result: Националниот конгрес на Бразил дебатираше за легализирање уште 10 години, а вакви браковишта моментално се законни само во Рио Гранди До Сул.

Batch 64
Result: Исклучителните детали беа напишани од пораснатата градоначалница на Сао Пауло, Марта Суплици. Предложете ја законската рамка, по што беше изменета, сега е во рацете на Роберто Џеферсон.

Batch 64
Result: Протестантите се надеваат да соберат петиција со 1,2 милион потписи за да ја предат на Националниот конгрес во ноември.

Batch 64
Result: По што се покажало дека многу фамилии бараат правна помош за да се борат против изгонувањето, на 20 март беше одржана средба на Централната за општествена правда на Источен брег за жртвите на шверцувањето со станари.

Batch 64
Result: Кога членовите започнаа да ги споделуваат настаните кои се слушнале, повеќето фамилии вклучени внемајќа внемајќа внемајќа внемајќа внемајќа внемајќа внемајќа внемајќа внемајќа внемајќа внемајќа внемајќа внемајќа внемајќа внемајќа внемајќа внемајќа внемајќа внемајќа вне

Batch 64
Result: Станувачките во Локвуд Гарденс веруваат дека можеби уште 40 фамилии или повеќе ќе бидат изглумени, бидејќи научија дека полицијата на OHA исто така ги истражува други стански објекти во Окланд кои можат да бидат вклучени во скапоцена наредба за домување.

Batch 64
Result: Групата откажа и настапот на стадионот „Војна меморија“ на Мауи, кој требало да го посетуваат 9.000 фанови, и се извини кон обожавачите.

Batch 64
Result: Управната компанија на групацијата „ХК Мениџмент Инц.“ немаше првобитна причина кога ја отфрлија наредката на 20 септември, но следувадневно ги наведе логистички причини.

Batch 64
Result: Постаритете гилемски адвокати, Сакис Кечагиолу и Џорџ Николакулос биле затворени во Коридалус, земалиште во Атина, бидејќи биле признати виновни за злоупотреба на службена должност и корупција.

Batch 72
Result: Како резултат на тоа, се појави голем скандал во гршката правна заедница поради откривањето на незаконски постапки кои ги стореа судиите, адвокатските уредници, адвокати и обвинитите во минатиот период.

Batch 72
Result: Пред неколку недели, по информациите објавени од новинарката Макис Триантафилопулос во нејзиното популарно телевизиско шоу "Зоугла" во Алка ТВ, пратеникот и адвокат Петрос Мантувалос беше отстранет од неговите канцеларии бидејќи учествувал во незаконски корупција и злоупотреба на службена должност.

Batch 72
Result: Постоечкиот врховен судија Евангелос Калусис е притворён бидејќи беше осуден за корупција и деликвентно однесување.

Batch 72
Result: Робертс рамнодуштно одби да каже кога верува дека животот почнува, важен прашалник при разгледокот на етиката на абортурите, ресекајќи дека би било неетично да коментира спецификите на веројасните случаи.

Batch 72
Result: Сепак, тој повторно ја поттикна својата поранешна изјава дека случајот Roe v. Wade е “утврдена закон на државата”, нагласувајќи го значењето на конзистентните судови на Врховниот суд.

Batch 72
Result: Тој исто така поттикна дека верувал во имплицираното право на приватност кое зависело од решението Ро.

Batch 72
Result: Маррухидор заврши на врвот на таблата, шест точки пред Носа на втор место.

Batch 72
Result: Двете страни ќе се сретнувале во големото полуфинале каде што Носа победи со 11 точки.

Batch 80
Result: Маррухидор потоа победи над Кабултур во квалификационите финалето.

Batch 80
Result: Hesperonychus elizabethae е вид од фамилијата Дромаеозаврида и е удавен брат на Велоцираптор.

Batch 80
Result: Оваа полно перната, топли крвни птица од репчење била сметана дека хоќа вертикално со два крака и нокти како кај Велоцираптор.

Batch 80
Result: Нејзината втора прст беше поголема, што доведе до името Хесперионикус, кое значи “западна прст”.

Batch 80
Result: Освен чествувајќиот лед, екстремните временски услови го нарушуваат наподот на спасувањето.

Batch 80
Result: Питман предложи дека условите нема да се подотворат пред неколку недели.

Batch 80
Result: Количеството и дебелината на леденикот, според Питман, е најлошата која е забележана за ледените лужици последните 15 години.

Batch 80
Result: Вестите се ширеа во општата заедница Ред Лејк денес кога се одржаа погребни церемонии заЏеф Вејс и три од деветте жртви, бидејќи уште еден ученик беше приведен поради врзаноста со настраданите од стрелбите во училиштето на 21 март.

Batch 88
Result: Овластувањето неофицијално потпорна само со потврдата за денес одземенот арест.

Batch 88
Result: Сепак, извор блисок до распитката му рече на Minneapolis Star-Tribune дека тоа е Луи Џурдан, 16-годишниот син на предводник на племето Ред Лејк, Флоид Џурдан.

Batch 88
Result: Не е познато на овие вести какви обвинетe ќе бидат ставени или што го довело надлежностите кон дедото, но во федерален центар започнале постапки за помлад особено.

Batch 88
Result: Лодин исто така рече дека официјалните лица одлучија да го отcancelledувањето на втортиот круг за да ги спасат Афганците трошоците и ризикот од безбедност од друга изборна процедура.

Batch 88
Result: Дипломатите рекоа дека пронашле доволно нејасност во афганиската уставна согласност за да го одлучат рулетот како бесцелна.

Batch 88
Result: Ова се спротивно на поранешните извештаи, кои рекле дека отпадот на повторната гласачка би била против уставот.

Batch 88
Result: Авионот бил насочен кон Иркутск и бил управуван од внатрешни трупи.

Batch 88
Result: Се основа истрага за истражување.

Batch 96
Result: Ил-76 би бил важен дел и на руската и советската војска од 1970-тите, а минатиот месец веќе го доживеа сериозен инцидент.

Batch 96
Result: На 7 октомври, моторот се оддели во полето при поцелодот, без повредени. Русија воведуваше внатрешна забрана за полети на Ил-76 по овој инцидент.

Batch 96
Result: 800 милји од системот на транс-Аласка делфина биле затворени поради протеклина на илјада бочилки суров нефт јужно од Фаирбанкс, Алкаса.

Batch 96
Result: Неисправност на струја по тест на системот за пожарна команда предизвика отворање на растеретнителни вентили и протекло масло околку насоката за пумпа во Форт Грели 9.

In [63]:
references = [[ref] for ref in text_mkd]
references[:10]

[['Во понеделникот научниците од медицинскиот факултет на Универзитетот Стенфорд објавија дека измислиле нова алатка за дијагностицирање со којашто се подредуваат клетките според типови: се работи за мал чип за печатење кој може да се произведе со помош на стандардни инк-џет печатачи, и тоа по цена од околу еден американски цент.'],
 ['Водечките истражувачи сметаат дека ова може да доведе до рано откривање на рак, туберколоза, ХИВ и маларија кај пациенти кои живеат во земји со низок животен стандард, каде стапката на преживување од болести како рак на дојка може да биде двојно пониска отколку во побогатите држави.'],
 ['JAS 39C Грипен се сруши на писта околу 9:30 am по локално време (2:30 UTC) и експлодираше, поради што аеродромот е затворен за комерцијални летови.'],
 ['Утврдено е дека пилот бил Дилокрит Патави, водачот на ескадрилата.'],
 ['Локалните медиуми известуваат за аеродромско противпожарно возило кое се превртело додека пожарникарите во него одговарале на повик.'],
 ['28-годишниот Видал од Севиља се придружи на екипата на Барселона.'],
 ['Откако се пресели во главниот град на Каталонија Видал одигра 49 натпревари за клубот.'],
 ['Протестот започна околу 11:00 часот по локално време (UTC+1) во Вајтхол, на спротивната страна од влезот чуван од полицијата на Даунинг Стрит, службената резиденција на премиерот.'],
 ['Веднаш по 11:00 часот демонстрантите го блокираа сообраќајот кон север во Вајтхол.'],
 ['Во 11:20 часот, полицијата побара од протестантите да повлечат на тротоарот, наведувајќи дека тие треба да ги урамнотежат правото на протестирање со застојот во сообраќајот.']]

In [64]:
bleu.compute(predictions=predictions_mkd, references=references)

{'bleu': 0.1764252625298047,
 'precisions': [0.5010150223304912,
  0.23487092678798138,
  0.1316836058329651,
  0.07073509015256588],
 'brevity_penalty': 0.9696145293904797,
 'length_ratio': 0.9700669554942891,
 'translation_length': 2463,
 'reference_length': 2539}

In [65]:
chrf_score = sacrebleu.corpus_chrf(predictions_mkd, references)
print(f"chrF: {chrf_score.score:.2f}")

chrF: 45.90

## Few-Shot Cross-lingual prompt (ENG->MKD) in bulgarian language

In [66]:
instruction = f"""Преведи следния текст от **Aнглийски** на **Mакедонски** език.
Само отпечатай превода на македонски език. Не добавяй никакви обяснения или допълнителни примери.

Пример 1
Английски: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Отговор (Mакедонски): Во понеделник, во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.

Пример 2
Английски: A sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.
Отговор (Mакедонски): Еден спортски натпревар трае 90 минути, односно две полувремиња по 45 минути со одмор помеѓу нив во траење од 15 минути. Ако има подолги прекини во играта, таа се продолжува така што се надополнува изгубеното време.

Пример 3
Английски: With the help of this tool, cells can be sorted by type, which means that diseases caused by small cells can be diagnosed.
Отговор (Mакедонски): Со помош на оваа алатка, клетките можат да се подредуваат по тип, што значи дека можат да се дијагностицираат болести предизвикани од мали клетки.

Пример 4
Английски: This study focuses on the development of new methods for data analysis.
Отговор (Mакедонски): Оваа студија се фокусира на развојот на нови методи за анализа на податоци.

Пример 5
Английски: In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
Отговор (Mакедонски): Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.
"""

In [67]:
predictions_mkd = batch_translate(text_eng,instruction,max_new_tokens=128,lang_code="bug",language="Македонски")

Batch 0
Result: Во вторник, научници од Школот за медицина на Универзитетот Стенфорд го анонсираа иновацијата на нова дијагностичка алатка која може да ги сортира клетките според вид: мал принтер кој може да се произведе користејќи стандардни струјни принтери за можноста да се направи за околу една американска центар.

Batch 0
Result: Главните истражувачи велат дека ова може да доведе до ранко детектирање на рак, туберкулоза, ХИВ и маларија кај пациентите во земјите со низок доход, каде што стапките на преживување за болести како ракот на матката честопати бидат половина од оние во богатите земји.

Batch 0
Result: Јасе 39Ц Грипен се урна на писта околу 9:30 биро локално време (0230 UTC) и експлодираше, затворајќи ги авиолетите.

Batch 0
Result: Пилото беше идентификуван како Сквадрон лидер Дилиокрит Паттавеи.

Batch 0
Result: Локалните медиуми ја сообщаваат пожарната возилка на авионската леталиштем набавка се преклопи додека реагираше.

Batch 0
Result: Видал, кој е на 28 години, се приклучи на Барса пред три сезони, од Севиља.

Batch 0
Result: Околку што играше за клубот откако се пресели во кадената на каталонците, биле 49 игри.

Batch 0
Result: Протестот започна околу 11:00 локално време (UTC+1) на Вајтлиха спротивно на полициски надворешна врата до Донинг Стрит, официјалната резиденција на премиерката.

Batch 8
Result: Непосредно по 11:00 часот, демонстрантите блокираа сообраќеј на северната патека во Вајтлиха.

Batch 8
Result: Во 11:20, полицијата побара од протестувачите да се вратат на патеката, со образложение дека треба да ја балансираат правото на протест со зголемувањето на сообраќејот.

Batch 8
Result: Около 11:29, протестот се промовираше на Вајтли, покрај Трафалгарскиот плоштак, покрај Стренд, минувајќи покрај Алдвик и кон Кингсваи кон Хоборн каде што Конзервативната партија одржа својот Спешен форум во хотелот Гранд Коннафт Ромс.

Batch 8
Result: Рекордот на Надал против Канадците е 7-2.

Batch 8
Result: Непостојуваше.

Batch 8
Result: Надал освоеше 88% нетни точки во натпредакот, заработувајќи 76 точки во првиот сервис.

Batch 8
Result: По натпреварот, кралот на глина рече: „Јас сум само возбуден што повторно сум во финалето на најважните настани. Јастум тука за да се обидам да го осволам овој натпреварувач.“

Batch 8
Result: “Панама Пеперс” е општо приемлив термин за околку десет милиони документи од правната фирма „Мосак Фонсека“ од Панама, кои беа изложени пред медиумите во пролетта 2016 година.

Batch 16
Result: Документата покажаа дека 14 банки помогнала на богатите клиенти да скриија милиарди американски долари богатство за да избегнат данок и други регулации.

Batch 16
Result: Весникот „The Guardian“ од Лондон наведна дека Доитче Банк контролирал околу третина од 1200 компании-самостојки кои биле користени за остварување на ова.

Batch 16
Result: Подека протести ширеше низ светот, повеќе криминални достави и лидерите на владите на Исланд и Пакистан конечно отстапија.

Batch 16
Result: Родена во Хонг Конг, Ма студираше на Универзитет во Њујорк и Правен факултет во Харвард и некогаш ја држела американската перманентна адреса “зелен картон”.

Batch 16
Result: Хсиеј го укажа подоцна на изборите дека Ма може да избегне земјата за време на криза.

Batch 16
Result: Хсие подоцна тврдеше дека фотогеничната Ма беше повеќе стил отколку суштината.

Batch 16
Result: Неколку спротивно на овие обвинувања, Ма победи убедително на платформа која бара поблизок контакт со Кинескиот континент.

Batch 16
Result: Играчот на денот денес е Алекс Овечкин од "Washington Capitals".

Batch 24
Result: Тој постигна 2 гола и 2 асистенции во победата на Вашингтон над Атланта Трасхери со резултат 5-3.

Batch 24
Result: Првиот асист на Ovechkin токму вечерта беше на головозавршниот погодок од новак Никлас Бакстром.

Batch 24
Result: Овавто го постигна втор погодок вечерва, неговиот 60ти во сезоната, станувајќи прв играч кој постигнувал 60 или повеќе голови во сезона од 1995-96 година, кога Јаромир Јагр и Марио Лемиев секој ја достигнал таа врест.

Batch 24
Result: Батън беше рансен на 190-то место на листата на 400 најбогати Американци во 2008 година, со проценети богатство од 2.3 милиарди долари.

Batch 24
Result: Тој се дипломираше на Факултот за либерални науки на Универзитетот во Вирџинија во 1950 година и беше значаен донатор за таа институција.

Batch 24
Result: Затворската каса во Абу Гариб, во Ирак, била запалена за време на беспорядък.

Batch 24
Result: Затворот стана познат после што беше откриена употреба на на силување на затвореници откако американските сили ја презедоа контролата.

Batch 24
Result: Пикет Јр. се повреди во Гранд При во Сингапур 2008 непосредком по рана техничка станица за Фернандо Алонсо, предизвикувајќи ја сината кола.

Batch 32
Result: Кога автомобилите пред Алونسо влегоа во гаража за доцнежливо полнење под ситечки, тој се пласи на првото место во составот и освои победа.

Batch 32
Result: Пикет Јр. беше отстранет по Гран при на Унгарија во 2009 година.

Batch 32
Result: Во точно 8:46 часот, над градот дојде мртовна тишина, означувајќи го токму моментот кога првиот авион удари својата цел.

Batch 32
Result: Две зраци светлина биле поставени да укават кон небото низ ноќта.

Batch 32
Result: Изградбата е во тек на пет нови небогрижи на локацијата, со транспортен центар и парк на меморија во средината.

Batch 32
Result: PBS шоуто има повеќе од дваесет награди "Емии", а неговата потрага е само малку полека од "Сесми Стреет" и "Мистер Роџерс’ Наборби”.

Batch 32
Result: Секоја епизода од шоуто би се фокусирала на тема во специфична книга и потоа ја би могла да ја истражи онаа темата преку повеќе нарачања.

Batch 32
Result: Секоја емисија исто така би нудерила препорачања за книги кои децата треба да ги бараат кога одат во библиотеката.

Batch 40
Result: Џон Грант, од WNED Бафалo (станицата каде што е дома на “Реалити бои”) рече: „Реалити бои научи децата зошто да читаат,... љубов кон читањето — [шобот] ги охрабра научниците да вземат книга и да читаат.“

Batch 40
Result: Некои луѓе, вклучувајќи го иЏон Грант, веруваат дека комбинација од финансиски проблеми и промена во филозофијата на програмите за образователска телевизија допринесоа за завршување на серијата.

Batch 40
Result: Се смета дека бурата, која се наоѓа околу 645 милји (1040 км) западно од островите Капе Верде, ќе се разреши пред да ги закачи земјата кој било регион, наведуваат прогнозистите.

Batch 40
Result: Фе́ред во моментов има ветер од 105 милји на час (165 км/h) и се движи кон северозапад.

Batch 40
Result: Ферод е најсилната тропска циклон која досега е регистрирана на источни и јужни делови на Атлантикот од појавата на сателисните слики, и само третата голема хурикан во историјата источно од 35°ЗД.

Batch 40
Result: На 24 септември 1759 година, Артур Гаус се потпиши за 9.000 годишна концесија за пивоварната Сент Јемс Гејт во Даблин, Ирска.

Batch 40
Result: 250 години подоцна, Гуинс стана глобален бизнис кој годишно генерира 10 милиарди евра (14.7 милијарди долари).

Batch 40
Result: Џони Рид, ко-воzaч на тимот A1GP Новозеланд, денес направи историска улогина со тоа што легално го крена најбрзото време над 48-годишниот Акулендскиот пристанишен мост во Нова Зеландија.

Batch 48
Result: Мистер Реид успеа да го управува автомобилот на A1GP на Нова Зеландија, "Black Beauty" седам пати над сводот на брзини над 160 км/h.

Batch 48
Result: Полицијата на Нова Зеландија имаше проблеми да користат своите радари за мерење на брзината за да го добијат колку забрзина беше на господинот Раид поради фактот дека Белечката е многу ниска, а полицијата успеа да ја регистрира забрзанетоста на господинот Раид само кога тој се забрза до 160 км/h.

Batch 48
Result: Во последните 3 месеци, повеќе од 80 особени уапсени биле ослободени од Централната касарна без формално обвинение.

Batch 48
Result: Во април годинашноста, судија Глин издаде вреќа заказна за установата за да ја принуди ослободувањето на оние задржени повеќе од 24 часа по прием, кои не добиле слушање пред судот комисар.

Batch 48
Result: Комisionерот поставува казна за задржување, ако биде одобрена, и формализира обвиненијата доставени од офицерот кој ги спречил. Обвиненијата потоа се вметнуваат во компјутерската база на податоци на државата каде што случајот се следи.

Batch 48
Result: Овие слушања исто така означуваат датум за правото на осомничењето на брзо судење.

Batch 48
Result: Питер Костело, австралиски финансерот и човек најверојатно да ја наследи функцијата поранешна шеф на Либералната партија, ги оцени поддршката за нуклеарна енергетска индустрија во Австралија.

Batch 48
Result: Ми Костело рече дека кога нуклеарната генерирачка енергија ќе стане економски видна, Австралија треба да го проследи нејзиното користење.

Batch 56
Result: „Ако почне да се користи комерцијално, треба да го добиеме тоа. Тоест, нема првобитна возразна кон нуклеарната енергија“, рече Костело.

Batch 56
Result: Според АНСА, „полицијата била загричена поради неколку силни удари на високо ниво кои ги сакаа да започнат воена борба за наследство.“

Batch 56
Result: Полицијата рече дека Ло Пиколо имаше предност бидејќи бил десниот раце на Провенцовано во Палермо и неговиот поголем искуство го добиле почит од постарата генерација на босови додека ја следеа политиката на Провенцовано да останат колку што е можно помалку видлив додека ги засилуваа своите мрежи на власт.

Batch 56
Result: Овие шефови биле огранитени од Провенцовано кога тој го запре надворешниот конфликт водено од Риина против државата, кој го одзеде животите на мафионските борци Џовани Фалоне и Паоло Борселино во 1992 година.

Batch 56
Result: Извршниот директор на Apple, Стив Джобс, ја представил уредната со тоа што кренал на сцена и го извлекол iPhone-от од карсекот на неговите панталоне.

Batch 56
Result: Во неговата два часа долга реториска увертка, тој изјави дека „Денес Апл ќе го преопредели телефонот, денес ќе правиме историја“.

Batch 56
Result: Бразил е најголемата земја со римско католички верници на светот, а Римската катедралска црква постојанo се спротивува на легализирањето на еднополовата брачна слобода во земјата.

Batch 56
Result: Националниот конгрес на Бразил ги дебатира легализирањето уште 10 години, а вакви браковишта моментално се законни само во Рио Гранде до Сул.

Batch 64
Result: Исклучителната сметка беше напишана од пораснатата градоначалница на Сао Пауло, Марта Супици. Предложените закони, по што беа изменети, сега се во рацете на Роберто Жеферсон.

Batch 64
Result: Протестантите се надеваат да соберат петиција со 1,2 милион потписи за да ја претстават пред Националниот конгрес во ноември.

Batch 64
Result: По што се покажало дека многу фамилии барале правна помош за да се борат против изгонувањето, на 20 март беше одржана средба на Централната за општествена правда на Источен брег за жртвите на шверцувањето со станот.

Batch 64
Result: Кога членовите започнале да ги споделуваат настаните кои се слушнале, повеќето фамилии вклучени внемајќи го сознавањето дека Каролин Вилсон од OHA украдна нивни депозити за обезбедување и избегаа од градот.

Batch 64
Result: Тенантсите во Локвуд Гарденс веруваат дека може да има уште 40 фамилии или повеќе кои бидат поврзани со искршување од стан, бидејќи научија дека полицијата на OHA исто така ги истражува други градски становишта во Окланд кои можат да бидат вклучени во скапокот за домување.

Batch 64
Result: Групата ја откажа насловата на стадионот Мауи’с Вар Меморариал, која требаше да биде посетувана од 9.000 луѓе, и се извини кон фановите.

Batch 64
Result: Управната компанија на групата „Бенд“, ХК Мениџмент Инк., не даде првобитна причина кога ја откажаа на 20 септември, туку обвинија со логистички причини следнавиот ден.

Batch 64
Result: Постарите грчки адвокати, Сакис Кечагиолог и Џорџ Николакулос биле затворени во Коридалус, земајќи ги осудени за злоупотреба на службена должност и корупција.

Batch 72
Result: Како резултат на тоа, се подеси скандал во грзото правно општество поради откривање на незаконски постапки кои ги стореле судиите, адвокатите, советодателите и обвирувачите во минативетите години.

Batch 72
Result: Пред неколку недели, по информациите објавени од новинарката Макис Триантафилопулос во нејзиното популарно телевизиско шоу "Зоугла" во Алка ТВ, пратеникот и адвокат Петрос Мантувалос беше отстранет од неговите канцеларии бидејќи ги имал вклучено во незаконски корупција и злоупотреба на службена должност.

Batch 72
Result: Постојано, врховниот судија Евангелос Калусис е уапсен бидејќи беше признат за виновен за корупција и деликвентно однесување.

Batch 72
Result: Робертс рамнодуштно одби да каже кога верува дека животот почнува, важен прашалник кога се разгледуваат етиката на абортурите, ресекајќи дека би било неетично да коментира спецификите на веројасните случаи.

Batch 72
Result: Сепак, тој повторно ја изјави нејзиното рана тврдење дека случајот Roe v. Wade е “утврдена закон на државата”, нагласувајќи ги важноста на конзистентните судови на Врховниот суд.

Batch 72
Result: Тој исто така поттикна, дека верувал во имплицираното право на приватност кое зависело од решението Ро.

Batch 72
Result: Маррухидор заврши на врвот на таблата, шест точки испред Носа во втор ред.

Batch 72
Result: Двете страни ќе се сретат во големото полуфинале каде што Носа победи со 11 точки.

Batch 80
Result: Маррухидор потоа победи над Кабултур во финалето пред квалификацијата.

Batch 80
Result: Hesperonychus elizabethae е вид од фамилијата Дромаеозаврида и е роднина на Велоцираптор.

Batch 80
Result: Оваа полно пернато, крвни птица од реворот била сметаа дека оди со два крака, со нокти слично на Велоцираптор.

Batch 80
Result: Нејзината втора прст беше по голема, што доведе до името Хеспероникус, кое значи “западна прст”.

Batch 80
Result: Освен стравотната ледена маса, екстремните временски услови го нарушуваат наподот на спасувањето.

Batch 80
Result: Питман предложи дека условите нема да се подотворат до некоја покрај следнава недела.

Batch 80
Result: Количеството и дебелината на ледените паковања, според Питман, е најлошата која била забележана за ледењето во последните 15 години.

Batch 80
Result: Вестите се ширеа во општата заедница Ред Лејк денес кога се одржаа погребни церемонии заЏеф Вејс и три од деветте жртви, додека уште еден ученик беше приведен во врска со наоружавањето во училиштето на 21 март.

Batch 88
Result: Овласта одржи малку зборување официјално освен за да потпорат денес уапнувањето.

Batch 88
Result: Сепак, извор со знаења за истрагата му рече на Minneapolis Star-Tribune дека тоа беше Луи Журдан, 16-годишниот син на претседавачот на племенското јадро Ред Лејк Флод Журдан.

Batch 88
Result: Не е познато на овие моменти кои обвинет ќе биде или што го довело авторитетот кон дедото, но во федерален центар започнале постапки за помлад особено.

Batch 88
Result: Лодин исто така рече дека официјалните лица одлучиле да го уапнаат повторното гласање во рок да се спасат Афганците од трошоците и ризикот од безбедност од друга избор.

Batch 88
Result: Дипломатите рекоа дека пронашле доволно нејасност во афганиската уставна согласност за да го одлучат рулетот како бесцелен.

Batch 88
Result: Ова се спротивно на поранешните извештаи, кои рекле дека отстранувањето на повторното гласање би било против уставната согласност.

Batch 88
Result: Авионот бил насочен кон Иркутск и бил управуван од внатрешни трупи.

Batch 88
Result: Една истрага беше установена за истражување.

Batch 96
Result: Ил-76 би бил важен дел и на руската и советската воена армија од 1970-тите, а минатиот месец веќе го доживеа сериозен инцидент.

Batch 96
Result: На 7 октомври, двигател се оддело на исфрлување, без повреди. Русија кратко ги стави во застој Ил-76 по тоа несреќа.

Batch 96
Result: 800 милји од системот на Транс-Аласка делфина биле затворени поради протекда на илјада бочилки суров петрол јужно од Фаирбанкс, Алкаса.

Batch 96
Result: По дефект на електричната инсталација следен по тест на системот за пожарна безбедност, се отворија релефите и прљаво масло ис curio near pump station 9 на Ft Greely.

In [68]:
references = [[ref] for ref in text_mkd]
references[:10]

[['Во понеделникот научниците од медицинскиот факултет на Универзитетот Стенфорд објавија дека измислиле нова алатка за дијагностицирање со којашто се подредуваат клетките според типови: се работи за мал чип за печатење кој може да се произведе со помош на стандардни инк-џет печатачи, и тоа по цена од околу еден американски цент.'],
 ['Водечките истражувачи сметаат дека ова може да доведе до рано откривање на рак, туберколоза, ХИВ и маларија кај пациенти кои живеат во земји со низок животен стандард, каде стапката на преживување од болести како рак на дојка може да биде двојно пониска отколку во побогатите држави.'],
 ['JAS 39C Грипен се сруши на писта околу 9:30 am по локално време (2:30 UTC) и експлодираше, поради што аеродромот е затворен за комерцијални летови.'],
 ['Утврдено е дека пилот бил Дилокрит Патави, водачот на ескадрилата.'],
 ['Локалните медиуми известуваат за аеродромско противпожарно возило кое се превртело додека пожарникарите во него одговарале на повик.'],
 ['28-годишниот Видал од Севиља се придружи на екипата на Барселона.'],
 ['Откако се пресели во главниот град на Каталонија Видал одигра 49 натпревари за клубот.'],
 ['Протестот започна околу 11:00 часот по локално време (UTC+1) во Вајтхол, на спротивната страна од влезот чуван од полицијата на Даунинг Стрит, службената резиденција на премиерот.'],
 ['Веднаш по 11:00 часот демонстрантите го блокираа сообраќајот кон север во Вајтхол.'],
 ['Во 11:20 часот, полицијата побара од протестантите да повлечат на тротоарот, наведувајќи дека тие треба да ги урамнотежат правото на протестирање со застојот во сообраќајот.']]

In [69]:
bleu.compute(predictions=predictions_mkd, references=references)

{'bleu': 0.1794183485813784,
 'precisions': [0.5044462409054163,
  0.2337826453243471,
  0.1310466138962181,
  0.07448275862068965],
 'brevity_penalty': 0.974068896988146,
 'length_ratio': 0.974399369830642,
 'translation_length': 2474,
 'reference_length': 2539}

In [70]:
chrf_score = sacrebleu.corpus_chrf(predictions_mkd, references)
print(f"chrF: {chrf_score.score:.2f}")

chrF: 46.09