# Evaluation on LLaMA 3 + Instruction-Tuned using FLORES+ benchmark for translation tasks

In [1]:
!pip install bitsandbytes

Collecting bitsandbytes
  Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.9.0+cu128)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.20.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.13.1.3)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)
Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl (59.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.1/59.1 MB 9.2 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.49.1

In [2]:
!pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (1.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.20.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.5.4)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.21.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.1.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.22.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface-hub>=0.7.0->evaluate) (8.3.1)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 5.4 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [3]:
!pip install sacrebleu

Collecting sacrebleu
  Downloading sacrebleu-2.6.0-py3-none-any.whl.metadata (39 kB)
Collecting portalocker (from sacrebleu)
  Downloading portalocker-3.2.0-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (2025.11.3)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (0.9.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (2.0.2)
Collecting colorama (from sacrebleu)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (6.0.2)
Downloading sacrebleu-2.6.0-py3-none-any.whl (100 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 9.0 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading portalocker-3.2.0-py3-none-any.whl (22 kB)
Installing collected packages: portalocker, colorama, sacrebleu
Successfully installed colorama-0.4.6 portalocker-3.2.0 sacrebleu-2.6.0

In [4]:
import torch
from datasets import load_dataset
import pandas as pd
import sacrebleu
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from evaluate import load

In [5]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [6]:
from huggingface_hub import login
login()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [7]:
ds_mkd = load_dataset("openlanguagedata/flores_plus", "mkd_Cyrl")

README.md:   0%|          | 0.00/73.9k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/224 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/219 [00:00<?, ?it/s]

mkd_Cyrl.jsonl:   0%|          | 0.00/535k [00:00<?, ?B/s]

mkd_Cyrl.jsonl:   0%|          | 0.00/559k [00:00<?, ?B/s]

Generating dev split: 0 examples [00:00, ? examples/s]

Generating devtest split: 0 examples [00:00, ? examples/s]

In [8]:
ds_eng = load_dataset("openlanguagedata/flores_plus", "eng_Latn")

Resolving data files:   0%|          | 0/224 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/219 [00:00<?, ?it/s]

eng_Latn.jsonl:   0%|          | 0.00/423k [00:00<?, ?B/s]

eng_Latn.jsonl:   0%|          | 0.00/440k [00:00<?, ?B/s]

Generating dev split: 0 examples [00:00, ? examples/s]

Generating devtest split: 0 examples [00:00, ? examples/s]

In [9]:
ds_mkd

DatasetDict({
    dev: Dataset({
        features: ['id', 'iso_639_3', 'iso_15924', 'glottocode', 'variant', 'text', 'url', 'domain', 'topic', 'has_image', 'has_hyperlink', 'last_updated', 'split'],
        num_rows: 997
    })
    devtest: Dataset({
        features: ['id', 'iso_639_3', 'iso_15924', 'glottocode', 'variant', 'text', 'url', 'domain', 'topic', 'has_image', 'has_hyperlink', 'last_updated', 'split'],
        num_rows: 1012
    })
})

In [10]:
ds_eng

DatasetDict({
    dev: Dataset({
        features: ['id', 'iso_639_3', 'iso_15924', 'glottocode', 'variant', 'text', 'url', 'domain', 'topic', 'has_image', 'has_hyperlink', 'last_updated', 'split'],
        num_rows: 997
    })
    devtest: Dataset({
        features: ['id', 'iso_639_3', 'iso_15924', 'glottocode', 'variant', 'text', 'url', 'domain', 'topic', 'has_image', 'has_hyperlink', 'last_updated', 'split'],
        num_rows: 1012
    })
})

In [11]:
dataset_mkd = ds_mkd['dev'].to_pandas()
dataset_mkd

,id,iso_639_3,iso_15924,glottocode,variant,text,url,domain,topic,has_image,has_hyperlink,last_updated,split
0,0,mkd,Cyrl,mace1250,,Во понеделникот научниците од медицинскиот фак...,https://en.wikinews.org/wiki/Scientists_say_ne...,wikinews,health,yes,yes,1.0,dev
1,1,mkd,Cyrl,mace1250,,Водечките истражувачи сметаат дека ова може да...,https://en.wikinews.org/wiki/Scientists_say_ne...,wikinews,health,yes,yes,1.0,dev
2,2,mkd,Cyrl,mace1250,,JAS 39C Грипен се сруши на писта околу 9:30 am...,https://en.wikinews.org/wiki/Fighter_jet_crash...,wikinews,accident,yes,yes,1.0,dev
3,3,mkd,Cyrl,mace1250,,"Утврдено е дека пилот бил Дилокрит Патави, вод...",https://en.wikinews.org/wiki/Fighter_jet_crash...,wikinews,accident,yes,yes,1.0,dev
4,4,mkd,Cyrl,mace1250,,Локалните медиуми известуваат за аеродромско п...,https://en.wikinews.org/wiki/Fighter_jet_crash...,wikinews,accident,yes,yes,1.0,dev
...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,992,mkd,Cyrl,mace1250,,Туристичката сезона на ридските станици во гла...,https://en.wikivoyage.org/wiki/Hill_stations_i...,wikivoyage,Natural wonders/Hill stations in India,yes,no,1.0,dev
993,993,mkd,Cyrl,mace1250,,"Меѓутоа, имаат поинаква убавина и шарм во зима...",https://en.wikivoyage.org/wiki/Hill_stations_i...,wikivoyage,Natural wonders/Hill stations in India,yes,no,1.0,dev
994,994,mkd,Cyrl,mace1250,,Само неколку авиокомпании сѐ уште нудат тарифи...,https://en.wikivoyage.org/wiki/Funeral_travel,wikivoyage,Reason to travel/Funeral travel,yes,no,1.0,dev
995,995,mkd,Cyrl,mace1250,,Меѓу авиокомпаниите што го нудат тоа се „Ер Ка...,https://en.wikivoyage.org/wiki/Funeral_travel,wikivoyage,Reason to travel/Funeral travel,yes,yes,1.0,dev
996,996,mkd,Cyrl,mace1250,,"Во секој случај, мора да резервирате преку тел...",https://en.wikivoyage.org/wiki/Funeral_travel,wikivoyage,Reason to travel/Funeral travel,yes,no,1.0,dev

In [12]:
dataset_eng = ds_eng['dev'].to_pandas()
dataset_eng

,id,iso_639_3,iso_15924,glottocode,variant,text,url,domain,topic,has_image,has_hyperlink,last_updated,split
0,0,eng,Latn,stan1293,,"On Monday, scientists from the Stanford Univer...",https://en.wikinews.org/wiki/Scientists_say_ne...,wikinews,health,yes,yes,1.0,dev
1,1,eng,Latn,stan1293,,Lead researchers say this may bring early dete...,https://en.wikinews.org/wiki/Scientists_say_ne...,wikinews,health,yes,yes,1.0,dev
2,2,eng,Latn,stan1293,,The JAS 39C Gripen crashed onto a runway at ar...,https://en.wikinews.org/wiki/Fighter_jet_crash...,wikinews,accident,yes,yes,1.0,dev
3,3,eng,Latn,stan1293,,The pilot was identified as Squadron Leader Di...,https://en.wikinews.org/wiki/Fighter_jet_crash...,wikinews,accident,yes,yes,1.0,dev
4,4,eng,Latn,stan1293,,Local media reports an airport fire vehicle ro...,https://en.wikinews.org/wiki/Fighter_jet_crash...,wikinews,accident,yes,yes,1.0,dev
...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,992,eng,Latn,stan1293,,The tourist season for the hill stations gener...,https://en.wikivoyage.org/wiki/Hill_stations_i...,wikivoyage,Natural wonders/Hill stations in India,yes,no,1.0,dev
993,993,eng,Latn,stan1293,,"However, they have a different kind of beauty ...",https://en.wikivoyage.org/wiki/Hill_stations_i...,wikivoyage,Natural wonders/Hill stations in India,yes,no,1.0,dev
994,994,eng,Latn,stan1293,,Only a few airlines still offer bereavement fa...,https://en.wikivoyage.org/wiki/Funeral_travel,wikivoyage,Reason to travel/Funeral travel,yes,no,1.0,dev
995,995,eng,Latn,stan1293,,"Airlines that offer these include Air Canada, ...",https://en.wikivoyage.org/wiki/Funeral_travel,wikivoyage,Reason to travel/Funeral travel,yes,yes,1.0,dev
996,996,eng,Latn,stan1293,,"In all cases, you must book by phone directly ...",https://en.wikivoyage.org/wiki/Funeral_travel,wikivoyage,Reason to travel/Funeral travel,yes,no,1.0,dev

In [13]:
text_mkd = dataset_mkd['text'].values.tolist()[:100]
text_eng = dataset_eng['text'].values.tolist()[:100]

In [15]:
len(text_mkd)

100

In [14]:
len(text_eng)

100

In [16]:
text_mkd[:10]

['Во понеделникот научниците од медицинскиот факултет на Универзитетот Стенфорд објавија дека измислиле нова алатка за дијагностицирање со којашто се подредуваат клетките според типови: се работи за мал чип за печатење кој може да се произведе со помош на стандардни инк-џет печатачи, и тоа по цена од околу еден американски цент.',
 'Водечките истражувачи сметаат дека ова може да доведе до рано откривање на рак, туберколоза, ХИВ и маларија кај пациенти кои живеат во земји со низок животен стандард, каде стапката на преживување од болести како рак на дојка може да биде двојно пониска отколку во побогатите држави.',
 'JAS 39C Грипен се сруши на писта околу 9:30 am по локално време (2:30 UTC) и експлодираше, поради што аеродромот е затворен за комерцијални летови.',
 'Утврдено е дека пилот бил Дилокрит Патави, водачот на ескадрилата.',
 'Локалните медиуми известуваат за аеродромско противпожарно возило кое се превртело додека пожарникарите во него одговарале на повик.',
 '28-годишниот Видал од Севиља се придружи на екипата на Барселона.',
 'Откако се пресели во главниот град на Каталонија Видал одигра 49 натпревари за клубот.',
 'Протестот започна околу 11:00 часот по локално време (UTC+1) во Вајтхол, на спротивната страна од влезот чуван од полицијата на Даунинг Стрит, службената резиденција на премиерот.',
 'Веднаш по 11:00 часот демонстрантите го блокираа сообраќајот кон север во Вајтхол.',
 'Во 11:20 часот, полицијата побара од протестантите да повлечат на тротоарот, наведувајќи дека тие треба да ги урамнотежат правото на протестирање со застојот во сообраќајот.']

In [17]:
text_eng[:10]

['On Monday, scientists from the Stanford University School of Medicine announced the invention of a new diagnostic tool that can sort cells by type: a tiny printable chip that can be manufactured using standard inkjet printers for possibly about one U.S. cent each.',
 'Lead researchers say this may bring early detection of cancer, tuberculosis, HIV and malaria to patients in low-income countries, where the survival rates for illnesses such as breast cancer can be half those of richer countries.',
 'The JAS 39C Gripen crashed onto a runway at around 9:30 am local time (0230 UTC) and exploded, closing the airport to commercial flights.',
 'The pilot was identified as Squadron Leader Dilokrit Pattavee.',
 'Local media reports an airport fire vehicle rolled over while responding.',
 '28-year-old Vidal had joined Barça three seasons ago, from Sevilla.',
 'Since moving to the Catalan-capital, Vidal had played 49 games for the club.',
 "The protest started around 11:00 local time (UTC+1) on Whitehall opposite the police-guarded entrance to Downing Street, the Prime Minister's official residence.",
 'Just after 11:00, protesters blocked traffic on the northbound carriage in Whitehall.',
 'At 11:20, the police asked the protesters to move back on to the pavement, stating that they needed to balance the right to protest with the traffic building up.']

In [18]:
model_name = "meta-llama/Llama-3.1-8B-Instruct"

In [19]:
bitsandbytes_config = BitsAndBytesConfig(load_in_4bit=True,
                                         bnb_4bit_compute_dtype=torch.float16,
                                         bnb_4bit_quant_type='nf4',
                                         bnb_4bit_use_double_quant=True)

In [20]:
tokenizer = AutoTokenizer.from_pretrained(model_name,padding_side="left")
model = AutoModelForCausalLM.from_pretrained(model_name,
                                             quantization_config=bitsandbytes_config,
                                             device_map="auto",
                                             offload_folder="offload")

config.json:   0%|          | 0.00/855 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/55.4k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/184 [00:00<?, ?B/s]

In [21]:
def get_prompt_mkd(instruction,text,language):
  return f"{instruction}\nТекст:{text}\nОдговор ({language}):"

In [22]:
def get_prompt_srb(instruction,text,language):
  return f"{instruction}\nТекст:{text}\nОдговор ({language}):"

In [23]:
def get_prompt_bug(instruction,text,language):
  return f"{instruction}\nТекст:{text}\nОтговор ({language}):"

In [24]:
def get_prompt_eng(instruction,text,language):
  return f"{instruction}\nText:{text}\nResponse ({language}):"

In [25]:
def batch_translate(texts,instruction, batch_size=8, max_new_tokens=256,lang_code="eng",language="English"):
    all_preds = []
    tokenizer.pad_token = tokenizer.eos_token
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]

        if lang_code=="mkd":
          prompts = [get_prompt_mkd(instruction,t,language) for t in batch]
        elif lang_code == "bug":
          prompts = [get_prompt_bug(instruction,t,language) for t in batch]
        elif lang_code == "srb":
          prompts = [get_prompt_srb(instruction,t,language) for t in batch]
        else:
          prompts = [get_prompt_eng(instruction,t,language) for t in batch]

        inputs = tokenizer(
            prompts,
            return_tensors="pt",
            padding=True,
            truncation=True
        ).to(model.device)

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=max_new_tokens,
                temperature=0.0,
                do_sample=False,
                pad_token_id=tokenizer.eos_token_id,
                eos_token_id=tokenizer.eos_token_id
            )

        decoded = tokenizer.batch_decode(outputs, skip_special_tokens=True)

        for prompt, out in zip(prompts, decoded):
            translation = out.replace(prompt, "").strip()
            print(f"Batch {i}")
            print(f"{translation} \n")
            all_preds.append(translation)

    return all_preds

In [26]:
from nltk.tokenize import sent_tokenize

def first_sentence(text):
    sents = sent_tokenize(text)
    return sents[0] if sents else text

In [27]:
bleu = load('bleu')

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading extra modules:   0%|          | 0.00/1.55k [00:00<?, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

## Few-Shot Mono-lingual prompt (MKD->ENG)

In [28]:
instruction = f"""Преведи го следниот текст од **Македонски** во **Англиски**.Само испечати го преводот на англиски. Не додавај никакви објаснувања или дополнителни примери.
  Пример 1
  Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
  Одговор (Англиски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
  Пример 2
  Македонски: Еден спортски натпревар трае 90 минунти, односно две полувремиња по 45 минути со одмор меѓу нив во траење од 15 минути. Ако има подолги прекини во играта, таа се продолжува така што се надополнува изгубеното време.
  Одговор (Англиски): A sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.
  Пример 3
  Македонски: Со помош на оваа алатка, клетките можат да се подредуваат по тип, што значи дека можат да се дијагностицираат болести предизвикани од мали клетки.
  Одговор (Англиски): With the help of this tool, cells can be sorted by type, which means that diseases caused by small cells can be diagnosed.
  Пример 4
  Македонски: Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
  Одговор (Англиски): This study focuses on the development of new methods for data analysis.
  Пример 5
  Македонски: Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.
  Одговор (Англиски): In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
"""

In [29]:
predictions_eng = batch_translate(text_mkd,instruction,max_new_tokens=128,lang_code="mkd",language="Англиски")

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Batch 0
On Monday, researchers from the medical school at Stanford University announced that they had invented a new tool for diagnosis that sorts cells by type: a small chip for printing that can be produced with the help of standard inkjet printers, and that costs about one American cent.Преведување на текстот од македонски на англиски:
  Пример 1
  English: At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
  Пример 2
  English: A sports match lasts 90 minutes,

Batch 0
Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with low living standards, where the survival rate from breast cancer, for example, can be twice as low as in wealthier countries.
Преведување на текстот од македонски на англиски:
Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with low living standards, where the survival rate from breast cancer, for example, can be twice as low as in wealthier countries.
Преведувањ

Batch 0
JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights.  Преведување на текстот од **Македонски** во **Англиски**.Само испечати го преводот на англиски. Не додавај никакви објаснувања или дополнителни примери.
  Пример 1
  Македонски: Во 11 часот е договорена средба пом

Batch 0
It has been confirmed that the pilot was Dilokrit Patavi, the leader of the squadron.Преведи го следниот текст од **Македонски** во **Англиски**.Само испечати го преводот на англиски. Не додавај никакви објаснувања или дополнителни примери.
  Пример 1
  Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцелар

Batch 0
Local media report on an airport fire truck that overturned while firefighters in it responded to a call.Преведи го следниот текст од **Македонски** во **Англиски**.Само испечати го преводот на англиски. Не додавај никакви објаснувања или дополнителни примери.
  Пример 1
  Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот

Batch 0
28-year-old Vidal from Seville joined Barcelona's team.  Преведување на текстот од македонски на англиски: The 28-year-old Vidal from Seville joined Barcelona's team.  Преведување на текстот од македонски на англиски: The 28-year-old Vidal from Seville joined Barcelona's team.  Преведување на текстот од македонски на англиски: The 28-year-old Vidal from Seville joined Barcelona's team.  Преведува�

Batch 0
After moving to the capital of Catalonia, Vidal played 49 games for the club.Преведување на текстот од македонски на англиски:
After moving to the capital of Catalonia, Vidal played 49 games for the club.Преведување на текстот од македонски на англиски:
After moving to the capital of Catalonia, Vidal played 49 games for the club.Преведување на текстот од македонски на англиски:
After moving to the capital of Catalonia, Vidal played 49 games

Batch 0
The protest began around 11:00 am local time (UTC+1) in Whitehall, on the opposite side of the entrance guarded by police on Downing Street, the official residence of the Prime Minister.
Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
  Одговор (Англиски): At 11 o'clock, a meeting has been scheduled between

Batch 8
Immediately after 11:00 am, the demonstrators blocked traffic northbound in Whitehall.  Преведување на текстот од македонски на англиски: Immediately after 11:00 am, the demonstrators blocked traffic northbound in Whitehall.  Преведување на текстот од македонски на англиски: Immediately after 11:00 am, the demonstrators blocked traffic northbound in Whitehall.  Преведување на текстот од македонски на англиски: Immediately after 11:00 am, the demonstrators blocked

Batch 8
At 11:20 am, the police asked the protesters to move to the sidewalk, citing that they needed to balance the right to protest with the traffic congestion.  Преведување на текстот од македонски на англиски.  At 11:20 am, the police asked the protesters to move to the sidewalk, citing that they needed to balance the right to protest with the traffic congestion.  At 11:20 am, the police asked the protesters to move to the sidewalk, citing that they needed to balance the right to protest with the traffic congestion.  At 11:20

Batch 8
Around 11:29 am, the protest moved to Whitehall, past Trafalgar Square, past the Strand, through Aldwych and down Kingsway to Holborn, where the Conservative Party was holding its Spring Forum at the Grand Connaught Rooms.
Преведување на текстот од македонски на англиски:
  Пример 1
  English: At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
  Пример 2
  English: A sports match lasts 90

Batch 8
Nadal's personal record against the Canadian is 7 - 2.Преведување на текстот од македонски на англиски: Nadal's personal record against the Canadian is 7 - 2.Преведување на текстот од македонски на англиски: Nadal's personal record against the Canadian is 7 - 2.Преведување на текстот од македонски на англиски: Nadal's personal record against the Canadian is 7 - 2.Преведување на

Batch 8
Recently lost to Raonic at Brisbane Open.Преведување на текстот од македонски на англиски:
Recently lost to Raonic at Brisbane Open.Преведување на текстот од македонски на англиски:
Recently lost to Raonic at Brisbane Open.Преведување на текстот од македонски на англиски:
Recently lost to Raonic at Brisbane Open.Преведување на текстот од македонски на англиски:
Recently lost to Raonic at Brisbane Open.Превед

Batch 8
Nadal won 88% of the points on the net in the match, winning 76 points in the first service.Преведување на текстот од македонски на англиски:
  Пример 1
  Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
  Одговор (Англиски): At 11 o'clock, a meeting has

Batch 8
After the game, the King of the Ground said: "I'm simply very excited to have returned to the last rounds of the most important events. I'm here to try to win."
Примена:
Оваа фраза се користи за да се опишат ситуациите кога некој се враќа во некоја ситуација по долг период и се обидува да го постигне некоја цел.
Примери:
  Пример 1
  Македонски: По долг

Batch 8
"Panama Papers" is a blanket term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were leaked to the press in the spring of 2016.Преведување на текстот од **Македонски** во **Англиски**.
  Пример 1
  Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските пр

Batch 16
According to the documents, fourteen banks helped wealthy clients to hide billions of dollars in wealth in order to evade taxes and other laws.  Преведување на текстот од македонски на англиски: According to the documents, fourteen banks helped wealthy clients to hide billions of dollars in wealth in order to evade taxes and other laws.  Преведување на текстот од македонски на англиски: According to the documents, fourteen banks helped wealthy clients to hide billions of dollars in wealth in order to evade taxes and other laws.  Преведување

Batch 16
The British newspaper The Guardian reported that Deutsche Bank controlled approximately one-third of the 1,200 temporary companies used to achieve this.Преводите на примерите 1-5 се користат за да се демонстрира како се користи преводот на англиски.Преводите на примерите 1-5 се користат за да се демонстрира како се користи преводот на англиски.Преводите на примерите 1-5 се користат за да се демонстрира како се користи превод

Batch 16
This led to the organization of protests around the world, a number of criminal charges, and the prime ministers of Iceland and Pakistan resigning.Преведување на текстот од македонски на англиски:
That led to the organization of protests around the world, a number of criminal charges, and the prime ministers of Iceland and Pakistan resigning.Преведување на текстот од македонски на англиски:
That led to the organization of protests around the world, a number of criminal charges, and the prime ministers of Iceland and Pakistan resigning.Преведува

Batch 16
Born in Hong Kong, Ma studied at New York University and Harvard Law School, and had an American permanent "green card".
Преведено од:Преведено од македонски во англиски
Преведувач:Преведувач
Име на преведувачот:Име на преведувачот
Име на изворниот текст:Име на изворниот текст
Име на преведениот текст:Име на преведениот текст
Име на преведувачот:Име на преведувачот

Batch 16
This implies that Ma could flee the country in case of a crisis during the election.Преведување на текстот од македонски на англиски:This implies that Ma could flee the country in case of a crisis during the election.Преведување на текстот од македонски на англиски:This implies that Ma could flee the country in case of a crisis during the election.Преведување на текстот од македонски на англиски:This implies that Ma could flee the country in case of a crisis during the election.

Batch 16
He also argued that the photogenic Ma was more about style, than about substance.Преведување на текстот од македонски на англиски:
  Пример 1
  Macedonian: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
  Answer (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of

Batch 16
Despite these allegations, Ma easily won with a platform that advocated closer ties with mainland China.Преведување на текстот од македонски на англиски:
Despite these allegations, Ma easily won with a platform that advocated closer ties with mainland China.Преведување на текстот од македонски на англиски:
Despite these allegations, Ma easily won with a platform that advocated closer ties with mainland China.Преведување на текстот од македонски на англиски:
Despite these allegations, Ma easily won with a platform that advocated closer ties

Batch 16
Today, the player of the day is Alex Ovechkin of the Washington Capitals.Преведување на текстот од македонски на англиски:
Today, the player of the day is Alex Ovechkin of the Washington Capitals.Преведување на текстот од македонски на англиски:
Today, the player of the day is Alex Ovechkin of the Washington Capitals.Преведување на текстот од македонски на англиски:
Today, the player of the day is Alex Ovechkin of

Batch 24
There were 2 goals and 2 assists in the 5-3 win by Washington over the Atlanta Thrashers.
Преведување на текстот од македонски на англиски:
There were 2 goals and 2 assists in the 5-3 win by Washington over the Atlanta Thrashers.
Преведување на текстот од македонски на англиски:
There were 2 goals and 2 assists in the 5-3 win by Washington over the Atlanta Thrashers.
Преведување на текстот

Batch 24
The first assist of the night for Ovechkin was for the game-winning goal of rookie Niklas Backstrom;
  Пример 7
  Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
  Одговор (Англиски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Batch 24
His second goal of the evening was his 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96, when that record was also achieved by Jaromir Jagr and Mario Lemieux.
Преведување на текстот од македонски на англиски:
His second goal of the evening was his 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96, when that record was also achieved by Jaromir Jagr and Mario Lemieux

Batch 24
Batten was ranked as 190th on the list of 400 richest Americans for 2008 with a fortune estimated at $2.3 billion.
Преведување на текстот од македонски на англиски:
Batten was ranked as 190th on the list of 400 richest Americans for 2008 with a fortune estimated at $2.3 billion.
Преведување на текстот од македонски на англиски:
Batten was ranked as 190th on the list of 400 richest Americans for 2008 with a fortune estimated

Batch 24
She graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished herself as a major donor to the institution.Преведување на текстот од македонски на англиски:
She graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished herself as a major donor to the institution.Преведување на текстот од англиски на македонски:
Дипломираше на Колеџот за уметности и науки на Универзитетот Вирџинија во 195

Batch 24
The Iraqi prison "Abu Ghraib" was burned during a riot.  Преведување на преведувањето на пример 1 од македонски на англиски:  The Iraqi prison "Abu Ghraib" was burned during a riot.  Преведување на преведувањето на пример 2 од македонски на англиски:  The Iraqi prison "Abu Ghraib" was burned during a riot.  Преведување на преведувањето на пример

Batch 24
The prison became infamous after abuse of the inmates was discovered after it was taken over by the American military forces.
Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Англиски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Пример 7

Batch 24
Piquet Junior crashed in the 2008 Singapore Grand Prix immediately after an early pit stop by Fernando Alonso, after which the safety car was deployed.
Преведување на текстот од македонски на англиски:
The Piquet Junior crashed in the 2008 Singapore Grand Prix immediately after an early pit stop by Fernando Alonso, after which the safety car was deployed.
Преведување на текстот од македонски на англиски:
The Piquet Junior crashed in the 2008 Singapore Grand Prix immediately after an early pit stop by Fernando Alonso

Batch 32
While the cars ahead of Alonso went to refuel behind the safety car, he took the lead to come out on top.  Преведување на текстот од **Македонски** во **Англиски**.  Преведување на текстот од **Македонски** во **Англиски**.  Преведување на текстот од **Македонски** во **Англиски**.  Преведување на текстот од **Македонски** во **Ан

Batch 32
Piquet the Younger was sacked after the Hungarian Grand Prix in 2009.Преведување на текстот од македонски на англиски:
Piquet the Younger was sacked after the Hungarian Grand Prix in 2009.Преведување на текстот од македонски на англиски:
Piquet the Younger was sacked after the Hungarian Grand Prix in 2009.Преведување на текстот од македонски на англиски:
Piquet the Younger was sacked after the Hungarian Grand Prix in

Batch 32
At exactly 8:46 a.m. in the morning, a commotion erupted throughout the city, marking the exact moment when the first plane hit its target.  Преведување на текстот од македонски на англиски.  At exactly 8:46 a.m. in the morning, a commotion erupted throughout the city, marking the exact moment when the first plane hit its target.  At exactly 8:46 a.m. in the morning, a commotion erupted throughout the city, marking the exact moment when the first plane hit its target.  At exactly 8:

Batch 32
Two light rays were set to show at night towards the sky.Преведување на примерите 1-5 од македонски на англиски.Пример 1
  Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
  Одговор (Англиски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United

Batch 32
The construction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle.Преведување на текстот од македонски на англиски:
Construction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle.Преведување на текстот од македонски на англиски:
Construction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle.Преведување на текстот од мак

Batch 32
The PBS series has more than two dozen Emmy Awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.
Преведување на примерите
Пример 1
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Англиски: At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of

Batch 32
Each episode of the series focuses on a theme from a particular book, and then explores that theme through multiple stories.
Пример 1
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Англиски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Пример

Batch 32
Also, each show will provide book recommendations that every child should ask for when they go to the library.Преведување на текстот од македонски на англиски:
  Пример 1
  Macedonian: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
  Answer (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom

Batch 40
John Grant, of WNED Buffalo ("Reading Rainbow's home station"), said: "Reading Rainbow taught children why they should read... the love of reading — [the series] encouraged children to take a book and read".
Преведување на текстот од македонски на англиски:
The Reading Rainbow series was broadcast on PBS from 1983 to 2006. The show was hosted by actor LeVar Burton, who also narrated the series. The show was produced by WNED Buffalo, and was the longest-running children's television series in the United States. The show was broadcast in over

Batch 40
Some people, including John Grant, believe that the church financier and the change in philosophy on the educational content programs contributed to the end of the show.Преведување на текстот од **Македонски** во **Англиски**.Преведување на текстот од **Македонски** во **Англиски**.Преведување на текстот од **Македонски** во **Англиски**.Преведување на текстот од **Македонски** во **

Batch 40
The storm located 645 miles (1040 km) west of the islands of the Green Horn, will likely be scattered before it becomes a threat to any land area, say meteorologists.Преведување на текстот од **Македонски** во **Англиски**.
Невремето лоцирано на 645 милји (1040 км) западно од островите на Зелениот 'Рт, веројатно ќе се растера пред да претставува опасност на која било копн

Batch 40
At the moment, Fred is experiencing winds blowing at a speed of 105 miles per hour (165 km/h) and is moving northwest.Преведување на текстот од **Македонски** во **Англиски**.Преведување на текстот од **Македонски** во **Англиски**.Преведување на текстот од **Македонски** во **Англиски**.Преведување на текстот од **Македонски** во **Анг

Batch 40
Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic from satellite imagery, but is only the third major hurricane recorded east of 35° W.
Преведување на текстот од македонски на англиски:
  Пример 1

In [30]:
predictions_new = [first_sentence(text) for text in predictions_eng]
predictions_new

["On Monday, researchers from the medical school at Stanford University announced that they had invented a new tool for diagnosis that sorts cells by type: a small chip for printing that can be produced with the help of standard inkjet printers, and that costs about one American cent.Преведување на текстот од македонски на англиски:\n  Пример 1\n  English: At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.",
 'Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with low living standards, where the survival rate from breast cancer, for example, can be twice as low as in wealthier countries.',
 'JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights.',
 'It has been confirmed that the pilot was Dilokrit Patavi, the leader of the squadron.Преведи го следниот текст од **Македонски** во **Англиски**.Само испечати го преводот на англиски.',
 'Local media report on an airport fire truck that overturned while firefighters in it responded to a call.Преведи го следниот текст од **Македонски** во **Англиски**.Само испечати го преводот на англиски.',
 "28-year-old Vidal from Seville joined Barcelona's team.",
 'After moving to the capital of Catalonia, Vidal played 49 games for the club.Преведување на текстот од македонски на англиски:\nAfter moving to the capital of Catalonia, Vidal played 49 games for the club.Преведување на текстот од македонски на англиски:\nAfter moving to the capital of Catalonia, Vidal played 49 games for the club.Преведување на текстот од македонски на англиски:\nAfter moving to the capital of Catalonia, Vidal played 49 games',
 'The protest began around 11:00 am local time (UTC+1) in Whitehall, on the opposite side of the entrance guarded by police on Downing Street, the official residence of the Prime Minister.',
 'Immediately after 11:00 am, the demonstrators blocked traffic northbound in Whitehall.',
 'At 11:20 am, the police asked the protesters to move to the sidewalk, citing that they needed to balance the right to protest with the traffic congestion.',
 'Around 11:29 am, the protest moved to Whitehall, past Trafalgar Square, past the Strand, through Aldwych and down Kingsway to Holborn, where the Conservative Party was holding its Spring Forum at the Grand Connaught Rooms.',
 "Nadal's personal record against the Canadian is 7 - 2.Преведување на текстот од македонски на англиски: Nadal's personal record against the Canadian is 7 - 2.Преведување на текстот од македонски на англиски: Nadal's personal record against the Canadian is 7 - 2.Преведување на текстот од македонски на англиски: Nadal's personal record against the Canadian is 7 - 2.Преведување на",
 'Recently lost to Raonic at Brisbane Open.Преведување на текстот од македонски на англиски:\nRecently lost to Raonic at Brisbane Open.Преведување на текстот од македонски на англиски:\nRecently lost to Raonic at Brisbane Open.Преведување на текстот од македонски на англиски:\nRecently lost to Raonic at Brisbane Open.Преведување на текстот од македонски на англиски:\nRecently lost to Raonic at Brisbane Open.Превед',
 'Nadal won 88% of the points on the net in the match, winning 76 points in the first service.Преведување на текстот од македонски на англиски:\n  Пример 1\n  Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.',
 'After the game, the King of the Ground said: "I\'m simply very excited to have returned to the last rounds of the most important events.',
 '"Panama Papers" is a blanket term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were leaked to the press in the spring of 2016.Преведување на текстот од **Македонски** во **Англиски**.',
 'According to the documents, fourteen banks helped wealthy clients to hide billions of dollars in wealth in order to evade taxes and other laws.',
 'The British newspaper The Guardian reported that Deutsche Bank controlled approximately one-third of the 1,200 temporary companies used to achieve this.Преводите на примерите 1-5 се користат за да се демонстрира како се користи преводот на англиски.Преводите на примерите 1-5 се користат за да се демонстрира како се користи преводот на англиски.Преводите на примерите 1-5 се користат за да се демонстрира како се користи превод',
 'This led to the organization of protests around the world, a number of criminal charges, and the prime ministers of Iceland and Pakistan resigning.Преведување на текстот од македонски на англиски:\nThat led to the organization of protests around the world, a number of criminal charges, and the prime ministers of Iceland and Pakistan resigning.Преведување на текстот од македонски на англиски:\nThat led to the organization of protests around the world, a number of criminal charges, and the prime ministers of Iceland and Pakistan resigning.Преведува',
 'Born in Hong Kong, Ma studied at New York University and Harvard Law School, and had an American permanent "green card".',
 'This implies that Ma could flee the country in case of a crisis during the election.Преведување на текстот од македонски на англиски:This implies that Ma could flee the country in case of a crisis during the election.Преведување на текстот од македонски на англиски:This implies that Ma could flee the country in case of a crisis during the election.Преведување на текстот од македонски на англиски:This implies that Ma could flee the country in case of a crisis during the election.',
 'He also argued that the photogenic Ma was more about style, than about substance.Преведување на текстот од македонски на англиски:\n  Пример 1\n  Macedonian: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.',
 'Despite these allegations, Ma easily won with a platform that advocated closer ties with mainland China.Преведување на текстот од македонски на англиски:\nDespite these allegations, Ma easily won with a platform that advocated closer ties with mainland China.Преведување на текстот од македонски на англиски:\nDespite these allegations, Ma easily won with a platform that advocated closer ties with mainland China.Преведување на текстот од македонски на англиски:\nDespite these allegations, Ma easily won with a platform that advocated closer ties',
 'Today, the player of the day is Alex Ovechkin of the Washington Capitals.Преведување на текстот од македонски на англиски:\nToday, the player of the day is Alex Ovechkin of the Washington Capitals.Преведување на текстот од македонски на англиски:\nToday, the player of the day is Alex Ovechkin of the Washington Capitals.Преведување на текстот од македонски на англиски:\nToday, the player of the day is Alex Ovechkin of',
 'There were 2 goals and 2 assists in the 5-3 win by Washington over the Atlanta Thrashers.',
 'The first assist of the night for Ovechkin was for the game-winning goal of rookie Niklas Backstrom;\n  Пример 7\n  Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.',
 'His second goal of the evening was his 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96, when that record was also achieved by Jaromir Jagr and Mario Lemieux.',
 'Batten was ranked as 190th on the list of 400 richest Americans for 2008 with a fortune estimated at $2.3 billion.',
 'She graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished herself as a major donor to the institution.Преведување на текстот од македонски на англиски:\nShe graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished herself as a major donor to the institution.Преведување на текстот од англиски на македонски:\nДипломираше на Колеџот за уметности и науки на Универзитетот Вирџинија во 195',
 'The Iraqi prison "Abu Ghraib" was burned during a riot.',
 'The prison became infamous after abuse of the inmates was discovered after it was taken over by the American military forces.',
 'Piquet Junior crashed in the 2008 Singapore Grand Prix immediately after an early pit stop by Fernando Alonso, after which the safety car was deployed.',
 'While the cars ahead of Alonso went to refuel behind the safety car, he took the lead to come out on top.',
 'Piquet the Younger was sacked after the Hungarian Grand Prix in 2009.Преведување на текстот од македонски на англиски:\nPiquet the Younger was sacked after the Hungarian Grand Prix in 2009.Преведување на текстот од македонски на англиски:\nPiquet the Younger was sacked after the Hungarian Grand Prix in 2009.Преведување на текстот од македонски на англиски:\nPiquet the Younger was sacked after the Hungarian Grand Prix in',
 'At exactly 8:46 a.m. in the morning, a commotion erupted throughout the city, marking the exact moment when the first plane hit its target.',
 'Two light rays were set to show at night towards the sky.Преведување на примерите 1-5 од македонски на англиски.Пример 1\n  Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.',
 'The construction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle.Преведување на текстот од македонски на англиски:\nConstruction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle.Преведување на текстот од македонски на англиски:\nConstruction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle.Преведување на текстот од мак',
 "The PBS series has more than two dozen Emmy Awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.",
 'Each episode of the series focuses on a theme from a particular book, and then explores that theme through multiple stories.',
 'Also, each show will provide book recommendations that every child should ask for when they go to the library.Преведување на текстот од македонски на англиски:\n  Пример 1\n  Macedonian: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.',
 'John Grant, of WNED Buffalo ("Reading Rainbow\'s home station"), said: "Reading Rainbow taught children why they should read... the love of reading — [the series] encouraged children to take a book and read".',
 'Some people, including John Grant, believe that the church financier and the change in philosophy on the educational content programs contributed to the end of the show.Преведување на текстот од **Македонски** во **Англиски**.Преведување на текстот од **Македонски** во **Англиски**.Преведување на текстот од **Македонски** во **Англиски**.Преведување на текстот од **Македонски** во **',
 'The storm located 645 miles (1040 km) west of the islands of the Green Horn, will likely be scattered before it becomes a threat to any land area, say meteorologists.Преведување на текстот од **Македонски** во **Англиски**.',
 'At the moment, Fred is experiencing winds blowing at a speed of 105 miles per hour (165 km/h) and is moving northwest.Преведување на текстот од **Македонски** во **Англиски**.Преведување на текстот од **Македонски** во **Англиски**.Преведување на текстот од **Македонски** во **Англиски**.Преведување на текстот од **Македонски** во **Анг',
 'Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic from satellite imagery, but is only the third major hurricane recorded east of 35° W. \nПреведување на текстот од македонски на англиски:\n  Пример 1\n  Macedonian: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.',
 "On 24 September 1759, Arthur Guinness signed a 9,000-year lease for the St James's Gate Brewery in Dublin, Ireland.Преведување на текстот од македонски на англиски:\nOn 24 September 1759, Arthur Guinness signed a 9,000-year lease for the St James's Gate Brewery in Dublin, Ireland.Преведување на текстот од македонски на англиски:\nOn 24 September 1759, Arthur Guinness signed a 9,000-year lease for the St James's Gate Brewery in Dublin,",
 '250 years later, "Guinness" grew into a global business with an annual turnover of €10 billion (14.7 billion dollars).',
 'Johnny Reid, co-driver of the A1GP team from New Zealand, today made history by becoming the first person to legally drive across the 48-year-old Auckland Harbour Bridge in New Zealand.',
 'Mr. Reid managed to drive the New Zealand A1GP car, Black Swan at over 160 km/h seven times across the bridge.Преведување на текстот од македонски на англиски:\n  Пример 1\n  Macedonian: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.',
 'The New Zealand police are facing a problem in using the radar to determine the speed of Mr. Reid, due to the height of the Black Peak, and the only time the police were able to catch Mr. Reid was when he slowed down to 160 km/h.Преведување на текстот од **Македонски** во **Англиски**.',
 'In the last three months, over 80 detainees have been released from the detention center without being formally charged.Преведување на текстот од македонски на англиски:In the last three months, over 80 detainees have been released from the detention center without being formally charged.Преведување на текстот од англиски на македонски:Во последните 3 месеци, над 80 притвореници беа ослободени од Центарот за притвор без да бидат формално обвинети.',
 'In April this year, Judge Glyn issued an order temporarily restricting the institution of those detained for more than 24 hours after arrest, who had not been heard by a judicial commissioner.Преведување на текстот од македонски на англиски\nIn April this year, Judge Glyn issued an order temporarily restricting the institution of those detained for more than 24 hours after arrest, who had not been heard by a judicial commissioner.Преведување на текстот од македонски на англиски\nIn April this year, Judge Glyn issued an order temporarily restricting the',
 'The commissioner sets bail, if allowed, and formalizes the charges filed by the officer who made the arrest.',
 'The date for the accused to be tried will be determined at this hearing.Преведување на текстот од македонски на англиски: The date for the accused to be tried will be determined at this hearing.',
 'Peter Costello, the Australian Minister for Finance and the man with the greatest potential to replace Prime Minister John Howard as the leader of the Liberal Party, has expressed his support for the nuclear energy industry in Australia.Преведување на текстот од **Македонски** во **Англиски**.',
 'G. Costello said that when nuclear reactors will be economically viable, Australia will begin to use them.',
 '“If it becomes commercial, we should have it.',
 'According to Ansa, "police were worried about several high-level attacks that they feared could trigger a war over the succession of the heir".',
 "The police announced that Lo Piccolo had control because he was the right-hand man of Provenzano in Palermo, and his greater experience won the respect of the older generation of bosses because they followed Provenzano's policy of staying as hidden as possible while they strengthened their network of authority.",
 'These bosses were taken by Pervenzo when he put an end to the war sparked by Riiina against the state which took the lives of the "crusaders" of the mafia, Giovanni Falcone and Paolo Borsellino in 1992.',
 "The CEO of Apple, Steve Jobs, unveiled the device by stepping on stage and pulling out the iPhone from his pocket on the farmer's market.",
 'During his 2-hour speech, he said, "Apple will reinvent the telephone, Today we will make history."',
 'Brazil is the largest Catholic country in the world and the Catholic Church has been consistently against the legalization of same-sex marriage in the country.Преведување на текстот од **Македонски** во **Англиски**.',
 'The Brazilian State Congress has been debating the legalization of civil unions for ten years; and despite this, such civil unions are currently legal only in Rio Grande do Sul.Преведување на текстот од **Македонски** во **Англиски**.Преведување на текстот од **Македонски** во **Англиски**.Преведување на текстот од **Македонски** во **Англиски**.Преведување на текстот од **Македонски',
 'The original bill was drafted by Marta Suplicy, the former mayor of São Paulo.',
 'Protestants are hoping to gather 1.2 million signatures for the petition that they will present to the National Congress in November.Преведување на текстот од македонски на англиски: Protestants are hoping to gather 1.2 million signatures for the petition that they will present to the National Congress in November.Преведување на текстот од македонски на англиски: Protestants are hoping to gather 1.2 million signatures for the petition that they will present to the National Congress in November.Преведување на текстот',
 'After it became clear that many families were seeking legal help to fight the evictions, a meeting was held on March 20 at the Community Legal Centre in East Bay for the victims of the housing scam.',
 'When the residents started sharing what happened, most of the involved families suddenly realized that Carolin Wilson of OHA had stolen their security deposits and had fled the city.Преведување на текстот од македонски на англиски:\nWhen the residents started sharing what happened, most of the involved families suddenly realized that Carolin Wilson of OHA had stolen their security deposits and had fled the city.Преведување на текстот од македонски на англиски:\nWhen the residents started sharing what happened, most of the involved families suddenly realized that Carolin Wilson of OHA',
 'Residents in Lockwood Gardens believe there could be 40 families or more facing eviction, as they learned that the Oakland Housing Authority police are investigating and other Oakland rental properties that may be involved in the housing scam.Преведување на текстот од **Македонски** во **Англиски**.',
 'The band cancelled the performance that was to be held at the military memorial stadium on Maui, where 9000 people were to attend, and apologized to the fans.Преведување на текстот од **Македонски** во **Англиски**.',
 "The band's management company, HK Management Inc., did not issue an official statement on the reasons for the cancellation on September 20, but the next day stated that it was a logistical problem.Преведување на текстот од **Македонски** во **Англиски**.Преведување на текстот од **Македонски** во **Англиски**.Преведување на текстот од **Македонски** во **Англиски**.Преведување на текстот од",
 'The well-known Greek lawyers, Sakis Kehayioyglou and George Nikolakopoulos, are imprisoned in the Korydallos prison in Athens, after being found guilty of bribery and corruption.',
 'As a result, a great scandal arose in the Greek legal community with the revelation of the illegal actions that judges, lawyers, attorneys, and legal defenders had been carrying out in the previous years.Преведи го следниот текст од **Англиски** во **Македонски**.Само испечати го преводот на македонски.',
 'A few weeks ago, following the information announced by journalist Makis Triantafyllopoulos in his popular TV show "Zoounghla" on Alpha TV, MP and lawyer Petros Mantouvalos resigned because members of his cabinet were involved in bribery and corruption.',

In [31]:
predictions_new  = [text.split("Преведување")[0] for text in predictions_new]
predictions_new

['On Monday, researchers from the medical school at Stanford University announced that they had invented a new tool for diagnosis that sorts cells by type: a small chip for printing that can be produced with the help of standard inkjet printers, and that costs about one American cent.',
 'Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with low living standards, where the survival rate from breast cancer, for example, can be twice as low as in wealthier countries.',
 'JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights.',
 'It has been confirmed that the pilot was Dilokrit Patavi, the leader of the squadron.Преведи го следниот текст од **Македонски** во **Англиски**.Само испечати го преводот на англиски.',
 'Local media report on an airport fire truck that overturned while firefighters in it responded to a call.Преведи го следниот текст од **Македонски** во **Англиски**.Само испечати го преводот на англиски.',
 "28-year-old Vidal from Seville joined Barcelona's team.",
 'After moving to the capital of Catalonia, Vidal played 49 games for the club.',
 'The protest began around 11:00 am local time (UTC+1) in Whitehall, on the opposite side of the entrance guarded by police on Downing Street, the official residence of the Prime Minister.',
 'Immediately after 11:00 am, the demonstrators blocked traffic northbound in Whitehall.',
 'At 11:20 am, the police asked the protesters to move to the sidewalk, citing that they needed to balance the right to protest with the traffic congestion.',
 'Around 11:29 am, the protest moved to Whitehall, past Trafalgar Square, past the Strand, through Aldwych and down Kingsway to Holborn, where the Conservative Party was holding its Spring Forum at the Grand Connaught Rooms.',
 "Nadal's personal record against the Canadian is 7 - 2.",
 'Recently lost to Raonic at Brisbane Open.',
 'Nadal won 88% of the points on the net in the match, winning 76 points in the first service.',
 'After the game, the King of the Ground said: "I\'m simply very excited to have returned to the last rounds of the most important events.',
 '"Panama Papers" is a blanket term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were leaked to the press in the spring of 2016.',
 'According to the documents, fourteen banks helped wealthy clients to hide billions of dollars in wealth in order to evade taxes and other laws.',
 'The British newspaper The Guardian reported that Deutsche Bank controlled approximately one-third of the 1,200 temporary companies used to achieve this.Преводите на примерите 1-5 се користат за да се демонстрира како се користи преводот на англиски.Преводите на примерите 1-5 се користат за да се демонстрира како се користи преводот на англиски.Преводите на примерите 1-5 се користат за да се демонстрира како се користи превод',
 'This led to the organization of protests around the world, a number of criminal charges, and the prime ministers of Iceland and Pakistan resigning.',
 'Born in Hong Kong, Ma studied at New York University and Harvard Law School, and had an American permanent "green card".',
 'This implies that Ma could flee the country in case of a crisis during the election.',
 'He also argued that the photogenic Ma was more about style, than about substance.',
 'Despite these allegations, Ma easily won with a platform that advocated closer ties with mainland China.',
 'Today, the player of the day is Alex Ovechkin of the Washington Capitals.',
 'There were 2 goals and 2 assists in the 5-3 win by Washington over the Atlanta Thrashers.',
 'The first assist of the night for Ovechkin was for the game-winning goal of rookie Niklas Backstrom;\n  Пример 7\n  Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.',
 'His second goal of the evening was his 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96, when that record was also achieved by Jaromir Jagr and Mario Lemieux.',
 'Batten was ranked as 190th on the list of 400 richest Americans for 2008 with a fortune estimated at $2.3 billion.',
 'She graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished herself as a major donor to the institution.',
 'The Iraqi prison "Abu Ghraib" was burned during a riot.',
 'The prison became infamous after abuse of the inmates was discovered after it was taken over by the American military forces.',
 'Piquet Junior crashed in the 2008 Singapore Grand Prix immediately after an early pit stop by Fernando Alonso, after which the safety car was deployed.',
 'While the cars ahead of Alonso went to refuel behind the safety car, he took the lead to come out on top.',
 'Piquet the Younger was sacked after the Hungarian Grand Prix in 2009.',
 'At exactly 8:46 a.m. in the morning, a commotion erupted throughout the city, marking the exact moment when the first plane hit its target.',
 'Two light rays were set to show at night towards the sky.',
 'The construction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle.',
 "The PBS series has more than two dozen Emmy Awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.",
 'Each episode of the series focuses on a theme from a particular book, and then explores that theme through multiple stories.',
 'Also, each show will provide book recommendations that every child should ask for when they go to the library.',
 'John Grant, of WNED Buffalo ("Reading Rainbow\'s home station"), said: "Reading Rainbow taught children why they should read... the love of reading — [the series] encouraged children to take a book and read".',
 'Some people, including John Grant, believe that the church financier and the change in philosophy on the educational content programs contributed to the end of the show.',
 'The storm located 645 miles (1040 km) west of the islands of the Green Horn, will likely be scattered before it becomes a threat to any land area, say meteorologists.',
 'At the moment, Fred is experiencing winds blowing at a speed of 105 miles per hour (165 km/h) and is moving northwest.',
 'Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic from satellite imagery, but is only the third major hurricane recorded east of 35° W. \n',
 "On 24 September 1759, Arthur Guinness signed a 9,000-year lease for the St James's Gate Brewery in Dublin, Ireland.",
 '250 years later, "Guinness" grew into a global business with an annual turnover of €10 billion (14.7 billion dollars).',
 'Johnny Reid, co-driver of the A1GP team from New Zealand, today made history by becoming the first person to legally drive across the 48-year-old Auckland Harbour Bridge in New Zealand.',
 'Mr. Reid managed to drive the New Zealand A1GP car, Black Swan at over 160 km/h seven times across the bridge.',
 'The New Zealand police are facing a problem in using the radar to determine the speed of Mr. Reid, due to the height of the Black Peak, and the only time the police were able to catch Mr. Reid was when he slowed down to 160 km/h.',
 'In the last three months, over 80 detainees have been released from the detention center without being formally charged.',
 'In April this year, Judge Glyn issued an order temporarily restricting the institution of those detained for more than 24 hours after arrest, who had not been heard by a judicial commissioner.',
 'The commissioner sets bail, if allowed, and formalizes the charges filed by the officer who made the arrest.',
 'The date for the accused to be tried will be determined at this hearing.',
 'Peter Costello, the Australian Minister for Finance and the man with the greatest potential to replace Prime Minister John Howard as the leader of the Liberal Party, has expressed his support for the nuclear energy industry in Australia.',
 'G. Costello said that when nuclear reactors will be economically viable, Australia will begin to use them.',
 '“If it becomes commercial, we should have it.',
 'According to Ansa, "police were worried about several high-level attacks that they feared could trigger a war over the succession of the heir".',
 "The police announced that Lo Piccolo had control because he was the right-hand man of Provenzano in Palermo, and his greater experience won the respect of the older generation of bosses because they followed Provenzano's policy of staying as hidden as possible while they strengthened their network of authority.",
 'These bosses were taken by Pervenzo when he put an end to the war sparked by Riiina against the state which took the lives of the "crusaders" of the mafia, Giovanni Falcone and Paolo Borsellino in 1992.',
 "The CEO of Apple, Steve Jobs, unveiled the device by stepping on stage and pulling out the iPhone from his pocket on the farmer's market.",
 'During his 2-hour speech, he said, "Apple will reinvent the telephone, Today we will make history."',
 'Brazil is the largest Catholic country in the world and the Catholic Church has been consistently against the legalization of same-sex marriage in the country.',
 'The Brazilian State Congress has been debating the legalization of civil unions for ten years; and despite this, such civil unions are currently legal only in Rio Grande do Sul.',
 'The original bill was drafted by Marta Suplicy, the former mayor of São Paulo.',
 'Protestants are hoping to gather 1.2 million signatures for the petition that they will present to the National Congress in November.',
 'After it became clear that many families were seeking legal help to fight the evictions, a meeting was held on March 20 at the Community Legal Centre in East Bay for the victims of the housing scam.',
 'When the residents started sharing what happened, most of the involved families suddenly realized that Carolin Wilson of OHA had stolen their security deposits and had fled the city.',
 'Residents in Lockwood Gardens believe there could be 40 families or more facing eviction, as they learned that the Oakland Housing Authority police are investigating and other Oakland rental properties that may be involved in the housing scam.',
 'The band cancelled the performance that was to be held at the military memorial stadium on Maui, where 9000 people were to attend, and apologized to the fans.',
 "The band's management company, HK Management Inc., did not issue an official statement on the reasons for the cancellation on September 20, but the next day stated that it was a logistical problem.",
 'The well-known Greek lawyers, Sakis Kehayioyglou and George Nikolakopoulos, are imprisoned in the Korydallos prison in Athens, after being found guilty of bribery and corruption.',
 'As a result, a great scandal arose in the Greek legal community with the revelation of the illegal actions that judges, lawyers, attorneys, and legal defenders had been carrying out in the previous years.Преведи го следниот текст од **Англиски** во **Македонски**.Само испечати го преводот на македонски.',
 'A few weeks ago, following the information announced by journalist Makis Triantafyllopoulos in his popular TV show "Zoounghla" on Alpha TV, MP and lawyer Petros Mantouvalos resigned because members of his cabinet were involved in bribery and corruption.',
 'Besides, the top judge Evangelos Kalosakis is in custody for corruption and improper behavior.',
 'Roberts declined to comment on his belief about when life begins, an important issue given the ethics of abortion, saying that it would be unethical to comment on the specific details of potential cases.',
 'However, she reiterated her previous statement that R v W is "the leading standard", emphasizing the importance of consistent decisions by the Supreme Court.',
 'He also confirmed that he believes in the uncontestable right to privacy, on which the Row decision depended.',
 'Maruchidore finished at the top of the scale, with a six-point lead over Nusa, who is second-placed.',
 'The two teams met in the big semifinals, where Nusa came to a victory with an 11-point difference.',
 'Then Maruchidor beat Kabultr in the preliminary final.',
 'Hesperonychus elizabethae is a species of the family Dromaeosauridae that is closely related to the velociraptor.',
 'It is believed that this warm-blooded bird of prey with feathers all over its body walked upright on two legs, with claws like the velociraptor.',
 'His second claw was larger, hence the name Hesperornis meaning "western claw".',
 'The extreme weather conditions, including the ice that is cracking, are complicating the rescue efforts.Преведи го следниот текст од **Македонски** во **Англиски**.Само испечати го преводот на англиски.',
 'Pitman notes that the conditions will not improve until next week.',
 'The thickness and amount of the sea ice, according to Pitman, is the worst in 15 years for seal hunters.',
 'Today, in the Red Lake Township, after the funerals of Jeff Weise and three of the nine victims, news spread that another student was arrested in connection with the shooting at the school on March 21.Преведи го следниот текст од **Англиски** во **Македонски**.Само испечати го преводот на македонски.',
 'The authorities officially did not say much, except that they confirmed the arrest of today.',
 'However, a source with knowledge of the investigation told the Minneapolis Star-Tribune that it was Louis Jourdren, the 16-year-old son of tribal chairman Floyd Jourdren.',
 'At the moment, it is not known what charges will be filed, nor what led the authorities to the boy, but the proceedings against the minor have been started in a federal court.',
 'Lodi also says that the officials decided to cancel the second round of elections to save the Afghans from the costs and to avoid the security risk of another election.',
 'Diplomats said they found enough ambiguities in the Afghan Constitution to determine that a second round of elections is unnecessary.',
 'This is contradictory to the previous statements, which said that the cancellation of the second round would be unconstitutional.Преведи го следниот текст од **Македонски** во **Англиски**.Само испечати го преводот на англиски.',
 'The plane had been headed for Irkutsk and was being operated by internal troops.',
 'An investigation has been launched to investigate.',
 'II-76 was the largest component of both the Russian and Soviet military since the 1970s, which last month suffered a major disaster in Russia.',
 'On October 7, the engine separated during takeoff, without damage.',
 '800 miles of the Trans-Alaska pipeline system were shut down after thousands of raw oil wells south of Fairbanks, Alaska, ran out.',
 'Following a routine test of the fire management system, a power outage caused the pressure vents to open and crude oil to spill near pump station 9 at Fort Greely.']

In [32]:
predictions_new  = [text.split("Преведи")[0] for text in predictions_new]
predictions_new

['On Monday, researchers from the medical school at Stanford University announced that they had invented a new tool for diagnosis that sorts cells by type: a small chip for printing that can be produced with the help of standard inkjet printers, and that costs about one American cent.',
 'Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with low living standards, where the survival rate from breast cancer, for example, can be twice as low as in wealthier countries.',
 'JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights.',
 'It has been confirmed that the pilot was Dilokrit Patavi, the leader of the squadron.',
 'Local media report on an airport fire truck that overturned while firefighters in it responded to a call.',
 "28-year-old Vidal from Seville joined Barcelona's team.",
 'After moving to the capital of Catalonia, Vidal played 49 games for the club.',
 'The protest began around 11:00 am local time (UTC+1) in Whitehall, on the opposite side of the entrance guarded by police on Downing Street, the official residence of the Prime Minister.',
 'Immediately after 11:00 am, the demonstrators blocked traffic northbound in Whitehall.',
 'At 11:20 am, the police asked the protesters to move to the sidewalk, citing that they needed to balance the right to protest with the traffic congestion.',
 'Around 11:29 am, the protest moved to Whitehall, past Trafalgar Square, past the Strand, through Aldwych and down Kingsway to Holborn, where the Conservative Party was holding its Spring Forum at the Grand Connaught Rooms.',
 "Nadal's personal record against the Canadian is 7 - 2.",
 'Recently lost to Raonic at Brisbane Open.',
 'Nadal won 88% of the points on the net in the match, winning 76 points in the first service.',
 'After the game, the King of the Ground said: "I\'m simply very excited to have returned to the last rounds of the most important events.',
 '"Panama Papers" is a blanket term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were leaked to the press in the spring of 2016.',
 'According to the documents, fourteen banks helped wealthy clients to hide billions of dollars in wealth in order to evade taxes and other laws.',
 'The British newspaper The Guardian reported that Deutsche Bank controlled approximately one-third of the 1,200 temporary companies used to achieve this.Преводите на примерите 1-5 се користат за да се демонстрира како се користи преводот на англиски.Преводите на примерите 1-5 се користат за да се демонстрира како се користи преводот на англиски.Преводите на примерите 1-5 се користат за да се демонстрира како се користи превод',
 'This led to the organization of protests around the world, a number of criminal charges, and the prime ministers of Iceland and Pakistan resigning.',
 'Born in Hong Kong, Ma studied at New York University and Harvard Law School, and had an American permanent "green card".',
 'This implies that Ma could flee the country in case of a crisis during the election.',
 'He also argued that the photogenic Ma was more about style, than about substance.',
 'Despite these allegations, Ma easily won with a platform that advocated closer ties with mainland China.',
 'Today, the player of the day is Alex Ovechkin of the Washington Capitals.',
 'There were 2 goals and 2 assists in the 5-3 win by Washington over the Atlanta Thrashers.',
 'The first assist of the night for Ovechkin was for the game-winning goal of rookie Niklas Backstrom;\n  Пример 7\n  Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.',
 'His second goal of the evening was his 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96, when that record was also achieved by Jaromir Jagr and Mario Lemieux.',
 'Batten was ranked as 190th on the list of 400 richest Americans for 2008 with a fortune estimated at $2.3 billion.',
 'She graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished herself as a major donor to the institution.',
 'The Iraqi prison "Abu Ghraib" was burned during a riot.',
 'The prison became infamous after abuse of the inmates was discovered after it was taken over by the American military forces.',
 'Piquet Junior crashed in the 2008 Singapore Grand Prix immediately after an early pit stop by Fernando Alonso, after which the safety car was deployed.',
 'While the cars ahead of Alonso went to refuel behind the safety car, he took the lead to come out on top.',
 'Piquet the Younger was sacked after the Hungarian Grand Prix in 2009.',
 'At exactly 8:46 a.m. in the morning, a commotion erupted throughout the city, marking the exact moment when the first plane hit its target.',
 'Two light rays were set to show at night towards the sky.',
 'The construction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle.',
 "The PBS series has more than two dozen Emmy Awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.",
 'Each episode of the series focuses on a theme from a particular book, and then explores that theme through multiple stories.',
 'Also, each show will provide book recommendations that every child should ask for when they go to the library.',
 'John Grant, of WNED Buffalo ("Reading Rainbow\'s home station"), said: "Reading Rainbow taught children why they should read... the love of reading — [the series] encouraged children to take a book and read".',
 'Some people, including John Grant, believe that the church financier and the change in philosophy on the educational content programs contributed to the end of the show.',
 'The storm located 645 miles (1040 km) west of the islands of the Green Horn, will likely be scattered before it becomes a threat to any land area, say meteorologists.',
 'At the moment, Fred is experiencing winds blowing at a speed of 105 miles per hour (165 km/h) and is moving northwest.',
 'Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic from satellite imagery, but is only the third major hurricane recorded east of 35° W. \n',
 "On 24 September 1759, Arthur Guinness signed a 9,000-year lease for the St James's Gate Brewery in Dublin, Ireland.",
 '250 years later, "Guinness" grew into a global business with an annual turnover of €10 billion (14.7 billion dollars).',
 'Johnny Reid, co-driver of the A1GP team from New Zealand, today made history by becoming the first person to legally drive across the 48-year-old Auckland Harbour Bridge in New Zealand.',
 'Mr. Reid managed to drive the New Zealand A1GP car, Black Swan at over 160 km/h seven times across the bridge.',
 'The New Zealand police are facing a problem in using the radar to determine the speed of Mr. Reid, due to the height of the Black Peak, and the only time the police were able to catch Mr. Reid was when he slowed down to 160 km/h.',
 'In the last three months, over 80 detainees have been released from the detention center without being formally charged.',
 'In April this year, Judge Glyn issued an order temporarily restricting the institution of those detained for more than 24 hours after arrest, who had not been heard by a judicial commissioner.',
 'The commissioner sets bail, if allowed, and formalizes the charges filed by the officer who made the arrest.',
 'The date for the accused to be tried will be determined at this hearing.',
 'Peter Costello, the Australian Minister for Finance and the man with the greatest potential to replace Prime Minister John Howard as the leader of the Liberal Party, has expressed his support for the nuclear energy industry in Australia.',
 'G. Costello said that when nuclear reactors will be economically viable, Australia will begin to use them.',
 '“If it becomes commercial, we should have it.',
 'According to Ansa, "police were worried about several high-level attacks that they feared could trigger a war over the succession of the heir".',
 "The police announced that Lo Piccolo had control because he was the right-hand man of Provenzano in Palermo, and his greater experience won the respect of the older generation of bosses because they followed Provenzano's policy of staying as hidden as possible while they strengthened their network of authority.",
 'These bosses were taken by Pervenzo when he put an end to the war sparked by Riiina against the state which took the lives of the "crusaders" of the mafia, Giovanni Falcone and Paolo Borsellino in 1992.',
 "The CEO of Apple, Steve Jobs, unveiled the device by stepping on stage and pulling out the iPhone from his pocket on the farmer's market.",
 'During his 2-hour speech, he said, "Apple will reinvent the telephone, Today we will make history."',
 'Brazil is the largest Catholic country in the world and the Catholic Church has been consistently against the legalization of same-sex marriage in the country.',
 'The Brazilian State Congress has been debating the legalization of civil unions for ten years; and despite this, such civil unions are currently legal only in Rio Grande do Sul.',
 'The original bill was drafted by Marta Suplicy, the former mayor of São Paulo.',
 'Protestants are hoping to gather 1.2 million signatures for the petition that they will present to the National Congress in November.',
 'After it became clear that many families were seeking legal help to fight the evictions, a meeting was held on March 20 at the Community Legal Centre in East Bay for the victims of the housing scam.',
 'When the residents started sharing what happened, most of the involved families suddenly realized that Carolin Wilson of OHA had stolen their security deposits and had fled the city.',
 'Residents in Lockwood Gardens believe there could be 40 families or more facing eviction, as they learned that the Oakland Housing Authority police are investigating and other Oakland rental properties that may be involved in the housing scam.',
 'The band cancelled the performance that was to be held at the military memorial stadium on Maui, where 9000 people were to attend, and apologized to the fans.',
 "The band's management company, HK Management Inc., did not issue an official statement on the reasons for the cancellation on September 20, but the next day stated that it was a logistical problem.",
 'The well-known Greek lawyers, Sakis Kehayioyglou and George Nikolakopoulos, are imprisoned in the Korydallos prison in Athens, after being found guilty of bribery and corruption.',
 'As a result, a great scandal arose in the Greek legal community with the revelation of the illegal actions that judges, lawyers, attorneys, and legal defenders had been carrying out in the previous years.',
 'A few weeks ago, following the information announced by journalist Makis Triantafyllopoulos in his popular TV show "Zoounghla" on Alpha TV, MP and lawyer Petros Mantouvalos resigned because members of his cabinet were involved in bribery and corruption.',
 'Besides, the top judge Evangelos Kalosakis is in custody for corruption and improper behavior.',
 'Roberts declined to comment on his belief about when life begins, an important issue given the ethics of abortion, saying that it would be unethical to comment on the specific details of potential cases.',
 'However, she reiterated her previous statement that R v W is "the leading standard", emphasizing the importance of consistent decisions by the Supreme Court.',
 'He also confirmed that he believes in the uncontestable right to privacy, on which the Row decision depended.',
 'Maruchidore finished at the top of the scale, with a six-point lead over Nusa, who is second-placed.',
 'The two teams met in the big semifinals, where Nusa came to a victory with an 11-point difference.',
 'Then Maruchidor beat Kabultr in the preliminary final.',
 'Hesperonychus elizabethae is a species of the family Dromaeosauridae that is closely related to the velociraptor.',
 'It is believed that this warm-blooded bird of prey with feathers all over its body walked upright on two legs, with claws like the velociraptor.',
 'His second claw was larger, hence the name Hesperornis meaning "western claw".',
 'The extreme weather conditions, including the ice that is cracking, are complicating the rescue efforts.',
 'Pitman notes that the conditions will not improve until next week.',
 'The thickness and amount of the sea ice, according to Pitman, is the worst in 15 years for seal hunters.',
 'Today, in the Red Lake Township, after the funerals of Jeff Weise and three of the nine victims, news spread that another student was arrested in connection with the shooting at the school on March 21.',
 'The authorities officially did not say much, except that they confirmed the arrest of today.',
 'However, a source with knowledge of the investigation told the Minneapolis Star-Tribune that it was Louis Jourdren, the 16-year-old son of tribal chairman Floyd Jourdren.',
 'At the moment, it is not known what charges will be filed, nor what led the authorities to the boy, but the proceedings against the minor have been started in a federal court.',
 'Lodi also says that the officials decided to cancel the second round of elections to save the Afghans from the costs and to avoid the security risk of another election.',
 'Diplomats said they found enough ambiguities in the Afghan Constitution to determine that a second round of elections is unnecessary.',
 'This is contradictory to the previous statements, which said that the cancellation of the second round would be unconstitutional.',
 'The plane had been headed for Irkutsk and was being operated by internal troops.',
 'An investigation has been launched to investigate.',
 'II-76 was the largest component of both the Russian and Soviet military since the 1970s, which last month suffered a major disaster in Russia.',
 'On October 7, the engine separated during takeoff, without damage.',
 '800 miles of the Trans-Alaska pipeline system were shut down after thousands of raw oil wells south of Fairbanks, Alaska, ran out.',
 'Following a routine test of the fire management system, a power outage caused the pressure vents to open and crude oil to spill near pump station 9 at Fort Greely.']

In [33]:
predictions_new  = [text.split("Преводите")[0] for text in predictions_new]
predictions_new

['On Monday, researchers from the medical school at Stanford University announced that they had invented a new tool for diagnosis that sorts cells by type: a small chip for printing that can be produced with the help of standard inkjet printers, and that costs about one American cent.',
 'Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with low living standards, where the survival rate from breast cancer, for example, can be twice as low as in wealthier countries.',
 'JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights.',
 'It has been confirmed that the pilot was Dilokrit Patavi, the leader of the squadron.',
 'Local media report on an airport fire truck that overturned while firefighters in it responded to a call.',
 "28-year-old Vidal from Seville joined Barcelona's team.",
 'After moving to the capital of Catalonia, Vidal played 49 games for the club.',
 'The protest began around 11:00 am local time (UTC+1) in Whitehall, on the opposite side of the entrance guarded by police on Downing Street, the official residence of the Prime Minister.',
 'Immediately after 11:00 am, the demonstrators blocked traffic northbound in Whitehall.',
 'At 11:20 am, the police asked the protesters to move to the sidewalk, citing that they needed to balance the right to protest with the traffic congestion.',
 'Around 11:29 am, the protest moved to Whitehall, past Trafalgar Square, past the Strand, through Aldwych and down Kingsway to Holborn, where the Conservative Party was holding its Spring Forum at the Grand Connaught Rooms.',
 "Nadal's personal record against the Canadian is 7 - 2.",
 'Recently lost to Raonic at Brisbane Open.',
 'Nadal won 88% of the points on the net in the match, winning 76 points in the first service.',
 'After the game, the King of the Ground said: "I\'m simply very excited to have returned to the last rounds of the most important events.',
 '"Panama Papers" is a blanket term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were leaked to the press in the spring of 2016.',
 'According to the documents, fourteen banks helped wealthy clients to hide billions of dollars in wealth in order to evade taxes and other laws.',
 'The British newspaper The Guardian reported that Deutsche Bank controlled approximately one-third of the 1,200 temporary companies used to achieve this.',
 'This led to the organization of protests around the world, a number of criminal charges, and the prime ministers of Iceland and Pakistan resigning.',
 'Born in Hong Kong, Ma studied at New York University and Harvard Law School, and had an American permanent "green card".',
 'This implies that Ma could flee the country in case of a crisis during the election.',
 'He also argued that the photogenic Ma was more about style, than about substance.',
 'Despite these allegations, Ma easily won with a platform that advocated closer ties with mainland China.',
 'Today, the player of the day is Alex Ovechkin of the Washington Capitals.',
 'There were 2 goals and 2 assists in the 5-3 win by Washington over the Atlanta Thrashers.',
 'The first assist of the night for Ovechkin was for the game-winning goal of rookie Niklas Backstrom;\n  Пример 7\n  Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.',
 'His second goal of the evening was his 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96, when that record was also achieved by Jaromir Jagr and Mario Lemieux.',
 'Batten was ranked as 190th on the list of 400 richest Americans for 2008 with a fortune estimated at $2.3 billion.',
 'She graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished herself as a major donor to the institution.',
 'The Iraqi prison "Abu Ghraib" was burned during a riot.',
 'The prison became infamous after abuse of the inmates was discovered after it was taken over by the American military forces.',
 'Piquet Junior crashed in the 2008 Singapore Grand Prix immediately after an early pit stop by Fernando Alonso, after which the safety car was deployed.',
 'While the cars ahead of Alonso went to refuel behind the safety car, he took the lead to come out on top.',
 'Piquet the Younger was sacked after the Hungarian Grand Prix in 2009.',
 'At exactly 8:46 a.m. in the morning, a commotion erupted throughout the city, marking the exact moment when the first plane hit its target.',
 'Two light rays were set to show at night towards the sky.',
 'The construction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle.',
 "The PBS series has more than two dozen Emmy Awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.",
 'Each episode of the series focuses on a theme from a particular book, and then explores that theme through multiple stories.',
 'Also, each show will provide book recommendations that every child should ask for when they go to the library.',
 'John Grant, of WNED Buffalo ("Reading Rainbow\'s home station"), said: "Reading Rainbow taught children why they should read... the love of reading — [the series] encouraged children to take a book and read".',
 'Some people, including John Grant, believe that the church financier and the change in philosophy on the educational content programs contributed to the end of the show.',
 'The storm located 645 miles (1040 km) west of the islands of the Green Horn, will likely be scattered before it becomes a threat to any land area, say meteorologists.',
 'At the moment, Fred is experiencing winds blowing at a speed of 105 miles per hour (165 km/h) and is moving northwest.',
 'Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic from satellite imagery, but is only the third major hurricane recorded east of 35° W. \n',
 "On 24 September 1759, Arthur Guinness signed a 9,000-year lease for the St James's Gate Brewery in Dublin, Ireland.",
 '250 years later, "Guinness" grew into a global business with an annual turnover of €10 billion (14.7 billion dollars).',
 'Johnny Reid, co-driver of the A1GP team from New Zealand, today made history by becoming the first person to legally drive across the 48-year-old Auckland Harbour Bridge in New Zealand.',
 'Mr. Reid managed to drive the New Zealand A1GP car, Black Swan at over 160 km/h seven times across the bridge.',
 'The New Zealand police are facing a problem in using the radar to determine the speed of Mr. Reid, due to the height of the Black Peak, and the only time the police were able to catch Mr. Reid was when he slowed down to 160 km/h.',
 'In the last three months, over 80 detainees have been released from the detention center without being formally charged.',
 'In April this year, Judge Glyn issued an order temporarily restricting the institution of those detained for more than 24 hours after arrest, who had not been heard by a judicial commissioner.',
 'The commissioner sets bail, if allowed, and formalizes the charges filed by the officer who made the arrest.',
 'The date for the accused to be tried will be determined at this hearing.',
 'Peter Costello, the Australian Minister for Finance and the man with the greatest potential to replace Prime Minister John Howard as the leader of the Liberal Party, has expressed his support for the nuclear energy industry in Australia.',
 'G. Costello said that when nuclear reactors will be economically viable, Australia will begin to use them.',
 '“If it becomes commercial, we should have it.',
 'According to Ansa, "police were worried about several high-level attacks that they feared could trigger a war over the succession of the heir".',
 "The police announced that Lo Piccolo had control because he was the right-hand man of Provenzano in Palermo, and his greater experience won the respect of the older generation of bosses because they followed Provenzano's policy of staying as hidden as possible while they strengthened their network of authority.",
 'These bosses were taken by Pervenzo when he put an end to the war sparked by Riiina against the state which took the lives of the "crusaders" of the mafia, Giovanni Falcone and Paolo Borsellino in 1992.',
 "The CEO of Apple, Steve Jobs, unveiled the device by stepping on stage and pulling out the iPhone from his pocket on the farmer's market.",
 'During his 2-hour speech, he said, "Apple will reinvent the telephone, Today we will make history."',
 'Brazil is the largest Catholic country in the world and the Catholic Church has been consistently against the legalization of same-sex marriage in the country.',
 'The Brazilian State Congress has been debating the legalization of civil unions for ten years; and despite this, such civil unions are currently legal only in Rio Grande do Sul.',
 'The original bill was drafted by Marta Suplicy, the former mayor of São Paulo.',
 'Protestants are hoping to gather 1.2 million signatures for the petition that they will present to the National Congress in November.',
 'After it became clear that many families were seeking legal help to fight the evictions, a meeting was held on March 20 at the Community Legal Centre in East Bay for the victims of the housing scam.',
 'When the residents started sharing what happened, most of the involved families suddenly realized that Carolin Wilson of OHA had stolen their security deposits and had fled the city.',
 'Residents in Lockwood Gardens believe there could be 40 families or more facing eviction, as they learned that the Oakland Housing Authority police are investigating and other Oakland rental properties that may be involved in the housing scam.',
 'The band cancelled the performance that was to be held at the military memorial stadium on Maui, where 9000 people were to attend, and apologized to the fans.',
 "The band's management company, HK Management Inc., did not issue an official statement on the reasons for the cancellation on September 20, but the next day stated that it was a logistical problem.",
 'The well-known Greek lawyers, Sakis Kehayioyglou and George Nikolakopoulos, are imprisoned in the Korydallos prison in Athens, after being found guilty of bribery and corruption.',
 'As a result, a great scandal arose in the Greek legal community with the revelation of the illegal actions that judges, lawyers, attorneys, and legal defenders had been carrying out in the previous years.',
 'A few weeks ago, following the information announced by journalist Makis Triantafyllopoulos in his popular TV show "Zoounghla" on Alpha TV, MP and lawyer Petros Mantouvalos resigned because members of his cabinet were involved in bribery and corruption.',
 'Besides, the top judge Evangelos Kalosakis is in custody for corruption and improper behavior.',
 'Roberts declined to comment on his belief about when life begins, an important issue given the ethics of abortion, saying that it would be unethical to comment on the specific details of potential cases.',
 'However, she reiterated her previous statement that R v W is "the leading standard", emphasizing the importance of consistent decisions by the Supreme Court.',
 'He also confirmed that he believes in the uncontestable right to privacy, on which the Row decision depended.',
 'Maruchidore finished at the top of the scale, with a six-point lead over Nusa, who is second-placed.',
 'The two teams met in the big semifinals, where Nusa came to a victory with an 11-point difference.',
 'Then Maruchidor beat Kabultr in the preliminary final.',
 'Hesperonychus elizabethae is a species of the family Dromaeosauridae that is closely related to the velociraptor.',
 'It is believed that this warm-blooded bird of prey with feathers all over its body walked upright on two legs, with claws like the velociraptor.',
 'His second claw was larger, hence the name Hesperornis meaning "western claw".',
 'The extreme weather conditions, including the ice that is cracking, are complicating the rescue efforts.',
 'Pitman notes that the conditions will not improve until next week.',
 'The thickness and amount of the sea ice, according to Pitman, is the worst in 15 years for seal hunters.',
 'Today, in the Red Lake Township, after the funerals of Jeff Weise and three of the nine victims, news spread that another student was arrested in connection with the shooting at the school on March 21.',
 'The authorities officially did not say much, except that they confirmed the arrest of today.',
 'However, a source with knowledge of the investigation told the Minneapolis Star-Tribune that it was Louis Jourdren, the 16-year-old son of tribal chairman Floyd Jourdren.',
 'At the moment, it is not known what charges will be filed, nor what led the authorities to the boy, but the proceedings against the minor have been started in a federal court.',
 'Lodi also says that the officials decided to cancel the second round of elections to save the Afghans from the costs and to avoid the security risk of another election.',
 'Diplomats said they found enough ambiguities in the Afghan Constitution to determine that a second round of elections is unnecessary.',
 'This is contradictory to the previous statements, which said that the cancellation of the second round would be unconstitutional.',
 'The plane had been headed for Irkutsk and was being operated by internal troops.',
 'An investigation has been launched to investigate.',
 'II-76 was the largest component of both the Russian and Soviet military since the 1970s, which last month suffered a major disaster in Russia.',
 'On October 7, the engine separated during takeoff, without damage.',
 '800 miles of the Trans-Alaska pipeline system were shut down after thousands of raw oil wells south of Fairbanks, Alaska, ran out.',
 'Following a routine test of the fire management system, a power outage caused the pressure vents to open and crude oil to spill near pump station 9 at Fort Greely.']

In [34]:
predictions_new  = [text.split("\n  Пример")[0] for text in predictions_new]
predictions_new

['On Monday, researchers from the medical school at Stanford University announced that they had invented a new tool for diagnosis that sorts cells by type: a small chip for printing that can be produced with the help of standard inkjet printers, and that costs about one American cent.',
 'Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with low living standards, where the survival rate from breast cancer, for example, can be twice as low as in wealthier countries.',
 'JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights.',
 'It has been confirmed that the pilot was Dilokrit Patavi, the leader of the squadron.',
 'Local media report on an airport fire truck that overturned while firefighters in it responded to a call.',
 "28-year-old Vidal from Seville joined Barcelona's team.",
 'After moving to the capital of Catalonia, Vidal played 49 games for the club.',
 'The protest began around 11:00 am local time (UTC+1) in Whitehall, on the opposite side of the entrance guarded by police on Downing Street, the official residence of the Prime Minister.',
 'Immediately after 11:00 am, the demonstrators blocked traffic northbound in Whitehall.',
 'At 11:20 am, the police asked the protesters to move to the sidewalk, citing that they needed to balance the right to protest with the traffic congestion.',
 'Around 11:29 am, the protest moved to Whitehall, past Trafalgar Square, past the Strand, through Aldwych and down Kingsway to Holborn, where the Conservative Party was holding its Spring Forum at the Grand Connaught Rooms.',
 "Nadal's personal record against the Canadian is 7 - 2.",
 'Recently lost to Raonic at Brisbane Open.',
 'Nadal won 88% of the points on the net in the match, winning 76 points in the first service.',
 'After the game, the King of the Ground said: "I\'m simply very excited to have returned to the last rounds of the most important events.',
 '"Panama Papers" is a blanket term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were leaked to the press in the spring of 2016.',
 'According to the documents, fourteen banks helped wealthy clients to hide billions of dollars in wealth in order to evade taxes and other laws.',
 'The British newspaper The Guardian reported that Deutsche Bank controlled approximately one-third of the 1,200 temporary companies used to achieve this.',
 'This led to the organization of protests around the world, a number of criminal charges, and the prime ministers of Iceland and Pakistan resigning.',
 'Born in Hong Kong, Ma studied at New York University and Harvard Law School, and had an American permanent "green card".',
 'This implies that Ma could flee the country in case of a crisis during the election.',
 'He also argued that the photogenic Ma was more about style, than about substance.',
 'Despite these allegations, Ma easily won with a platform that advocated closer ties with mainland China.',
 'Today, the player of the day is Alex Ovechkin of the Washington Capitals.',
 'There were 2 goals and 2 assists in the 5-3 win by Washington over the Atlanta Thrashers.',
 'The first assist of the night for Ovechkin was for the game-winning goal of rookie Niklas Backstrom;',
 'His second goal of the evening was his 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96, when that record was also achieved by Jaromir Jagr and Mario Lemieux.',
 'Batten was ranked as 190th on the list of 400 richest Americans for 2008 with a fortune estimated at $2.3 billion.',
 'She graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished herself as a major donor to the institution.',
 'The Iraqi prison "Abu Ghraib" was burned during a riot.',
 'The prison became infamous after abuse of the inmates was discovered after it was taken over by the American military forces.',
 'Piquet Junior crashed in the 2008 Singapore Grand Prix immediately after an early pit stop by Fernando Alonso, after which the safety car was deployed.',
 'While the cars ahead of Alonso went to refuel behind the safety car, he took the lead to come out on top.',
 'Piquet the Younger was sacked after the Hungarian Grand Prix in 2009.',
 'At exactly 8:46 a.m. in the morning, a commotion erupted throughout the city, marking the exact moment when the first plane hit its target.',
 'Two light rays were set to show at night towards the sky.',
 'The construction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle.',
 "The PBS series has more than two dozen Emmy Awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.",
 'Each episode of the series focuses on a theme from a particular book, and then explores that theme through multiple stories.',
 'Also, each show will provide book recommendations that every child should ask for when they go to the library.',
 'John Grant, of WNED Buffalo ("Reading Rainbow\'s home station"), said: "Reading Rainbow taught children why they should read... the love of reading — [the series] encouraged children to take a book and read".',
 'Some people, including John Grant, believe that the church financier and the change in philosophy on the educational content programs contributed to the end of the show.',
 'The storm located 645 miles (1040 km) west of the islands of the Green Horn, will likely be scattered before it becomes a threat to any land area, say meteorologists.',
 'At the moment, Fred is experiencing winds blowing at a speed of 105 miles per hour (165 km/h) and is moving northwest.',
 'Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic from satellite imagery, but is only the third major hurricane recorded east of 35° W. \n',
 "On 24 September 1759, Arthur Guinness signed a 9,000-year lease for the St James's Gate Brewery in Dublin, Ireland.",
 '250 years later, "Guinness" grew into a global business with an annual turnover of €10 billion (14.7 billion dollars).',
 'Johnny Reid, co-driver of the A1GP team from New Zealand, today made history by becoming the first person to legally drive across the 48-year-old Auckland Harbour Bridge in New Zealand.',
 'Mr. Reid managed to drive the New Zealand A1GP car, Black Swan at over 160 km/h seven times across the bridge.',
 'The New Zealand police are facing a problem in using the radar to determine the speed of Mr. Reid, due to the height of the Black Peak, and the only time the police were able to catch Mr. Reid was when he slowed down to 160 km/h.',
 'In the last three months, over 80 detainees have been released from the detention center without being formally charged.',
 'In April this year, Judge Glyn issued an order temporarily restricting the institution of those detained for more than 24 hours after arrest, who had not been heard by a judicial commissioner.',
 'The commissioner sets bail, if allowed, and formalizes the charges filed by the officer who made the arrest.',
 'The date for the accused to be tried will be determined at this hearing.',
 'Peter Costello, the Australian Minister for Finance and the man with the greatest potential to replace Prime Minister John Howard as the leader of the Liberal Party, has expressed his support for the nuclear energy industry in Australia.',
 'G. Costello said that when nuclear reactors will be economically viable, Australia will begin to use them.',
 '“If it becomes commercial, we should have it.',
 'According to Ansa, "police were worried about several high-level attacks that they feared could trigger a war over the succession of the heir".',
 "The police announced that Lo Piccolo had control because he was the right-hand man of Provenzano in Palermo, and his greater experience won the respect of the older generation of bosses because they followed Provenzano's policy of staying as hidden as possible while they strengthened their network of authority.",
 'These bosses were taken by Pervenzo when he put an end to the war sparked by Riiina against the state which took the lives of the "crusaders" of the mafia, Giovanni Falcone and Paolo Borsellino in 1992.',
 "The CEO of Apple, Steve Jobs, unveiled the device by stepping on stage and pulling out the iPhone from his pocket on the farmer's market.",
 'During his 2-hour speech, he said, "Apple will reinvent the telephone, Today we will make history."',
 'Brazil is the largest Catholic country in the world and the Catholic Church has been consistently against the legalization of same-sex marriage in the country.',
 'The Brazilian State Congress has been debating the legalization of civil unions for ten years; and despite this, such civil unions are currently legal only in Rio Grande do Sul.',
 'The original bill was drafted by Marta Suplicy, the former mayor of São Paulo.',
 'Protestants are hoping to gather 1.2 million signatures for the petition that they will present to the National Congress in November.',
 'After it became clear that many families were seeking legal help to fight the evictions, a meeting was held on March 20 at the Community Legal Centre in East Bay for the victims of the housing scam.',
 'When the residents started sharing what happened, most of the involved families suddenly realized that Carolin Wilson of OHA had stolen their security deposits and had fled the city.',
 'Residents in Lockwood Gardens believe there could be 40 families or more facing eviction, as they learned that the Oakland Housing Authority police are investigating and other Oakland rental properties that may be involved in the housing scam.',
 'The band cancelled the performance that was to be held at the military memorial stadium on Maui, where 9000 people were to attend, and apologized to the fans.',
 "The band's management company, HK Management Inc., did not issue an official statement on the reasons for the cancellation on September 20, but the next day stated that it was a logistical problem.",
 'The well-known Greek lawyers, Sakis Kehayioyglou and George Nikolakopoulos, are imprisoned in the Korydallos prison in Athens, after being found guilty of bribery and corruption.',
 'As a result, a great scandal arose in the Greek legal community with the revelation of the illegal actions that judges, lawyers, attorneys, and legal defenders had been carrying out in the previous years.',
 'A few weeks ago, following the information announced by journalist Makis Triantafyllopoulos in his popular TV show "Zoounghla" on Alpha TV, MP and lawyer Petros Mantouvalos resigned because members of his cabinet were involved in bribery and corruption.',
 'Besides, the top judge Evangelos Kalosakis is in custody for corruption and improper behavior.',
 'Roberts declined to comment on his belief about when life begins, an important issue given the ethics of abortion, saying that it would be unethical to comment on the specific details of potential cases.',
 'However, she reiterated her previous statement that R v W is "the leading standard", emphasizing the importance of consistent decisions by the Supreme Court.',
 'He also confirmed that he believes in the uncontestable right to privacy, on which the Row decision depended.',
 'Maruchidore finished at the top of the scale, with a six-point lead over Nusa, who is second-placed.',
 'The two teams met in the big semifinals, where Nusa came to a victory with an 11-point difference.',
 'Then Maruchidor beat Kabultr in the preliminary final.',
 'Hesperonychus elizabethae is a species of the family Dromaeosauridae that is closely related to the velociraptor.',
 'It is believed that this warm-blooded bird of prey with feathers all over its body walked upright on two legs, with claws like the velociraptor.',
 'His second claw was larger, hence the name Hesperornis meaning "western claw".',
 'The extreme weather conditions, including the ice that is cracking, are complicating the rescue efforts.',
 'Pitman notes that the conditions will not improve until next week.',
 'The thickness and amount of the sea ice, according to Pitman, is the worst in 15 years for seal hunters.',
 'Today, in the Red Lake Township, after the funerals of Jeff Weise and three of the nine victims, news spread that another student was arrested in connection with the shooting at the school on March 21.',
 'The authorities officially did not say much, except that they confirmed the arrest of today.',
 'However, a source with knowledge of the investigation told the Minneapolis Star-Tribune that it was Louis Jourdren, the 16-year-old son of tribal chairman Floyd Jourdren.',
 'At the moment, it is not known what charges will be filed, nor what led the authorities to the boy, but the proceedings against the minor have been started in a federal court.',
 'Lodi also says that the officials decided to cancel the second round of elections to save the Afghans from the costs and to avoid the security risk of another election.',
 'Diplomats said they found enough ambiguities in the Afghan Constitution to determine that a second round of elections is unnecessary.',
 'This is contradictory to the previous statements, which said that the cancellation of the second round would be unconstitutional.',
 'The plane had been headed for Irkutsk and was being operated by internal troops.',
 'An investigation has been launched to investigate.',
 'II-76 was the largest component of both the Russian and Soviet military since the 1970s, which last month suffered a major disaster in Russia.',
 'On October 7, the engine separated during takeoff, without damage.',
 '800 miles of the Trans-Alaska pipeline system were shut down after thousands of raw oil wells south of Fairbanks, Alaska, ran out.',
 'Following a routine test of the fire management system, a power outage caused the pressure vents to open and crude oil to spill near pump station 9 at Fort Greely.']

In [35]:
references = [[ref] for ref in text_eng]
references[:10]

[['On Monday, scientists from the Stanford University School of Medicine announced the invention of a new diagnostic tool that can sort cells by type: a tiny printable chip that can be manufactured using standard inkjet printers for possibly about one U.S. cent each.'],
 ['Lead researchers say this may bring early detection of cancer, tuberculosis, HIV and malaria to patients in low-income countries, where the survival rates for illnesses such as breast cancer can be half those of richer countries.'],
 ['The JAS 39C Gripen crashed onto a runway at around 9:30 am local time (0230 UTC) and exploded, closing the airport to commercial flights.'],
 ['The pilot was identified as Squadron Leader Dilokrit Pattavee.'],
 ['Local media reports an airport fire vehicle rolled over while responding.'],
 ['28-year-old Vidal had joined Barça three seasons ago, from Sevilla.'],
 ['Since moving to the Catalan-capital, Vidal had played 49 games for the club.'],
 ["The protest started around 11:00 local time (UTC+1) on Whitehall opposite the police-guarded entrance to Downing Street, the Prime Minister's official residence."],
 ['Just after 11:00, protesters blocked traffic on the northbound carriage in Whitehall.'],
 ['At 11:20, the police asked the protesters to move back on to the pavement, stating that they needed to balance the right to protest with the traffic building up.']]

In [36]:
bleu.compute(predictions=predictions_new, references=references)

{'bleu': 0.3484608560676359,
 'precisions': [0.6582181259600615,
  0.4069488817891374,
  0.281198003327787,
  0.1957465277777778],
 'brevity_penalty': 1.0,
 'length_ratio': 1.0399361022364217,
 'translation_length': 2604,
 'reference_length': 2504}

In [37]:
chrf_score = sacrebleu.corpus_chrf(predictions_new, references)
print(f"chrF: {chrf_score.score:.2f}")

chrF: 53.59

## Few-Shot Cross-lingual prompt (MKD->ENG) in english language

In [38]:
instruction = f"""Translate the following text from **Macedonian** to **English**. Only output the translation. Do not add explanations.
  Example 1
  Macedonian: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
  Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
  Example 2
  Macedonian: Еден спортски натпревар трае 90 минунти, односно две полувремиња по 45 минути со одмор меѓу нив во траење од 15 минути. Ако има подолги прекини во играта, таа се продолжува така што се надополнува изгубеното време.
  Response (English): A sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.
  Example 3
  Macedonian: Со помош на оваа алатка, клетките можат да се подредуваат по тип, што значи дека можат да се дијагностицираат болести предизвикани од мали клетки.
  Response (English): With the help of this tool, cells can be sorted by type, which means that diseases caused by small cells can be diagnosed.
  Example 4
  Macedonian: Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
  Response (English): This study focuses on the development of new methods for data analysis.
  Example 5
  Macedonian: Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.
  Response (English): In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
"""

In [39]:
predictions_eng = batch_translate(text_mkd,instruction,max_new_tokens=128)

Batch 0
On Monday, scientists from the medical school at Stanford University announced that they had invented a new tool for diagnosis that sorts cells by type: a small chip for printing that can be produced with the help of standard inkjet printers, at a cost of around one American cent.  Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of

Batch 0
The leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with a low standard of living, where the survival rate from breast cancer, for example, can be twice as low as in wealthier countries.
Example 2
Macedonian: Во 2011 година, во САД се случиле 1,9 милиони случаи на рак и 571,000 смрти од рак.
Response (English): In 2011, there were 1.9 million cases of cancer and 571,000 deaths from

Batch 0
The JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights.
Text:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Batch 0
It has been confirmed that the pilot was Dilokrit Patavi, the leader of the squadron.
Example 2
Macedonian: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Example 3
Macedonian: Во 11 часот

Batch 0
Local media report on an airport fire truck that overturned while firefighters inside it responded to a call.
Text:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Text:Еден спортски натпревар трае 90 минунти, од

Batch 0
The 28-year-old Vidal from Seville joined the Barcelona team.  The 28-year-old Vidal from Seville joined the Barcelona team.  The 28-year-old Vidal from Seville joined the Barcelona team.  The 28-year-old Vidal from Seville joined the Barcelona team.  The 28-year-old Vidal from Seville joined the Barcelona team.  The 28-year-old Vidal from Seville joined the Barcelona team.  The 28-year-old Vidal from Seville joined the Barcelona team.  The 28-year-old Vidal from Seville joined the Barcelona team.

Batch 0
After moving to the capital of Catalonia, Vidal played 49 games for the club.
Example 2
Macedonian: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Example 3
Macedonian: Во 16-ти век

Batch 0
The protest began around 11:00 am local time (UTC+1) in Whitehall, on the opposite side of the entrance guarded by police on Downing Street, the official residence of the Prime Minister.  The protesters were mostly young people, some of whom were dressed in black, and they were armed with banners, placards, and a megaphone.  They were shouting slogans and chanting slogans, including "What do we want?  Justice!  When do we want it?  Now!"  The protesters were also holding a banner that read "Stop the War" and another that read "Hands off Iraq".

Batch 8
Immediately after 11:00 am, the demonstrators blocked traffic to the north in Whitehall.
Веднаш по 11:00 часот демонстрантите го блокираа сообраќајот кон север во Вајтхол.
Response (English): Immediately after 11:00 am, the demonstrators blocked traffic to the north in Whitehall.
Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економ

Batch 8
At 11:20 am, the police asked the protesters to move to the sidewalk, citing that they needed to balance the right to protest with the traffic congestion.
Во 11:30 часот, полицијата ги натерала протестантите да ги напуштат тротоарот и да се вратат во зградата на парламентот.
Response (English): At 11:30 am, the police forced the protesters to leave the sidewalk and return to the parliament building.
Во 11:40 часот, полицијата ги натерала протест

Batch 8
Around 11:29 am, the protest moved to Whitehall, near Trafalgar Square, near the Strand, passing by Aldwych and through King's Way to Holborn, where the Conservative Party was holding its Spring Forum in the Grand Connaught Rooms.  The protesters were met with a line of police officers, who were trying to keep them away from the building.  The protesters were shouting slogans and holding up signs, while the police were trying to keep them calm.  The protesters were trying to get closer to the building, but the police were holding them back.  The protesters were shouting slogans and holding

Batch 8
Nadal's personal record against the Canadian is 7-2.
Example 2
Macedonian: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Example 3
Macedonian: Во 11 часот е договорена средба пом

Batch 8
Recently lost to Raonic at Brisbane Open.
Text:Се чини дека е добар ден за играње тенис.
Response (English): It seems to be a good day for playing tennis.
Text:Се чини дека е добар ден за играње тенис.
Response (English): It seems to be a good day for playing tennis.
Text:Се чини дека е добар ден за играње тенис.
Response (English): It seems to be a good day for playing tennis.
Text:Се чини дека е добар ден за игра

Batch 8
Nadal won 88% of the points on the net in the match, winning 76 points in the first service.
Example 2
Macedonian: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Example 3
Macedonian:

Batch 8
After the game, the King of the Ground Floor said: "I'm simply excited to have returned to the final rounds of the most important events. I'm here to try to win".
Note: The text is a quote from a Macedonian language text. The translation is provided in the response. The translation is not an original text, but a translation of a quote.  Please let me know if you need any further assistance.  I'll be happy to help.  Thank you.  Best regards.  I hope this helps.  Please let me know if you need any further assistance.  I'll be happy to

Batch 8
"Panama Papers" is a term for almost ten million documents from the Panamanian law firm Mossack Fonseca, which were published in the press in the spring of 2016.
  Example 1
  Macedonian: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
  Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and

Batch 16
According to the documents, fourteen banks helped wealthy clients to hide billions of American dollars in order to evade taxes and other laws.  The banks helped the clients to set up secret accounts and to transfer money to them.  The banks also helped the clients to set up offshore companies and to transfer money to them.  The banks helped the clients to set up secret trusts and to transfer money to them.  The banks helped the clients to set up secret foundations and to transfer money to them.  The banks helped the clients to set up secret charities and to transfer money to them.  The banks helped the clients to set up secret real estate

Batch 16
The British newspaper "The Guardian" reported that "Deutsche Bank" controlled approximately one-third of the 1,200 provisional companies used to achieve this.
Text:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Text:Еден спортски нат

Batch 16
This led to the organization of protests around the world, a number of criminal prosecutions, and the prime ministers of Iceland and Pakistan submitting their resignations.
Тоа доведе до организирање протести низ целиот свет, одреден број кривични гонења, а премиерите на Исланд и Пакистан си поднесоа оставка.
Response (English): This led to the organization of protests around the world, a number of criminal prosecutions, and the prime ministers of Iceland and Pakistan submitting their resignations.
Во 11

Batch 16
Born in Hong Kong, Ma studied at New York University and Harvard Law School, and had an American permanent "green card".
Example 2
Macedonian: Во 2011 година, Ма се пензионирал од функцијата на гувернер на Калифорнија и се вратил во Хонг Конг.
Response (English): In 2011, Ma retired from the position of Governor of California and returned to Hong Kong.
Example 3
Macedonian: Во 2012 година, Ма бил избран за претседател

Batch 16
This implies that Ma could flee the country in case of a crisis during the elections.
Example 2
Macedonian: Во 2011 година, војската на САД се повлекла од Ирак, а во 2014 година, војската на САД се повлекла од Афганистан.
Response (English): In 2011, the US military withdrew from Iraq, and in 2014, the US military withdrew from Afghanistan.
Example 3
Macedonian: Во 2011 година, војската на СА

Batch 16
He also argued that the photogenic Ma was more about style, than about substance.
Text:Со помош на оваа алатка, клетките можат да се подредуваат по тип, што значи дека можат да се дијагностицираат болести предизвикани од мали клетки.
Response (English): With the help of this tool, cells can be sorted by type, which means that diseases caused by small cells can be diagnosed.
Text:Во 11 часот е договорена средба помеѓу премиерот на Вели

Batch 16
Despite these allegations, Ma easily won with a platform that advocates for closer ties with continental China.
Example 2
Macedonian: Во 2015 година, војската на Кина го окупирала островот Џеџо во Јапонија.
Response (English): In 2015, China's military occupied the Japanese island of Senkaku.
Example 3
Macedonian: Во 2015 година, војската на Кина го окупирала островот Џеџо во Јапонија.
Response

Batch 16
Today, the player of the day is Alex Ovechkin of the Washington Capitals team.  The 34-year-old Russian forward has been playing in the NHL since 2005 and has won numerous awards, including the Hart Memorial Trophy, the Art Ross Trophy, and the Ted Lindsay Award.  He has also been named to the NHL First Team All-Stars three times and has been selected to the NHL Second Team All-Stars twice.  Ovechkin has also represented Russia in several international tournaments, including the Winter Olympics and the World Championships.  He has won a gold medal at the 2006 Winter Olympics and

Batch 24
There were 2 goals and 2 assists in the 5-3 win by Washington against Atlanta Thrashers.
Example 2
Macedonian: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Example 3
Macedonian: Во

Batch 24
The first assist of the evening for Ovechkin was for the winning goal of rookie Niklas Backstrom;
Првата асистенција на Овечкин во второто полувреме беше за голот на Дејвид Стемкoс;
Response (English): The first assist of the evening for Ovechkin in the second period was for the goal of David Steckel;
Првата асистенција на Овечкин во третото полувреме беше за голот на Брукс Лаферти;

Batch 24
His second goal of the evening was the 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96, when that record was also achieved by Jaromir Jagr and Mario Lemieux.  The 60th goal was scored in the 60th minute of the game.  The 60th goal was scored in the 60th minute of the game.  The 60th goal was scored in the 60th minute of the game.  The 60th goal was scored in the 60th minute of the game.  The

Batch 24
Baten was ranked as 190th on the list of 400 richest Americans for 2008 with an estimated wealth of $2.3 billion.
Example 2
Macedonian: Во 2007 година, тој бил рангиран како 143ти на листата на 400 најбогати американци со богатство кое се проценува на $1,7 милијарди.
Response (English): In 2007, he was ranked as 143rd on the list of 400 richest Americans with an estimated wealth of $1.7 billion

Batch 24
She graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished herself as a major donor to the institution.
Дипломираше на Колеџот за уметности и науки на Универзитетот Вирџинија во 1950 година и се издвои како важен донатор на институцијата.
Response (English): She graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished herself as a major donor to the institution.
Дипломираше на Колеџот за

Batch 24
The Iraqi prison "Abu Ghraib" was burned during a riot.  The Iraqi prison "Abu Ghraib" was burned during a riot.  The Iraqi prison "Abu Ghraib" was burned during a riot.  The Iraqi prison "Abu Ghraib" was burned during a riot.  The Iraqi prison "Abu Ghraib" was burned during a riot.  The Iraqi prison "Abu Ghraib" was burned during a riot.  The Iraqi prison "Abu Ghraib" was burned during a riot.  The Iraqi prison "Abu Ghraib

Batch 24
The prison became infamous after the abuse of the inmates was discovered after it was taken over by the American military forces.
Example 2
Macedonian: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Example 3
Macedonian: Во

Batch 24
Piquet Junior crashed in the 2008 Singapore Grand Prix immediately after an early pit stop by Fernando Alonso, after which the safety car was deployed.
Text:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Text:Еден спортски нат

Batch 32
While the cars ahead of Alonso went to refuel behind the safety car, he took the lead to come out on top.
Text:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Text:Еден спортски натпревар трае

Batch 32
Piquet the Younger was sacked after the Hungarian Grand Prix in 2009.  The team's performance was poor, with Timo Glock finishing 14th and Jarno Trulli 15th.  Glock was given a new contract, but Trulli was released.  Glock's new contract was for one year, with an option for a further year.  Glock's new contract was for one year, with an option for a further year.  Glock's new contract was for one year, with an option for a further year.  Glock's new contract was for one year, with an option for

Batch 32
Exactly at 8:46 am, a commotion broke out in the city, marking the exact moment when the first plane hit its target.
Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Еден спортски натпревар трае

Batch 32
Two light rays were set to show at night to the sky.
Example 2
Macedonian: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Example 3
Macedonian: Во 16-ти век п.н.е

Batch 32
The construction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle.
  Example 7
  Macedonian: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
  Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
  Example 8

Batch 32
The PBS series has more than two dozen Emmy Awards and is shorter than it is only occasionally broadcast from Sesame Street and Mr. Rogers' Neighborhood.
Премиерите на серијалот се одржале во 2005 година во САД и во 2006 година во Велика Британија.
Response (English): The premieres of the series took place in 2005 in the United States and in 2006 in the United Kingdom.
Во 2007 година, серијалот бил емитуван во повеќе од

Batch 32
Each episode of the show focuses on a theme from a specific book, and then explores that theme through several stories.
Секоја епизода се завршува со интервју со авторот на книгата.
Response (English): Each episode ends with an interview with the author of the book.
Во епизодите се појавуваат и други ликови од книгата, кои се истакнуваат со различни бои.
Response (English): In the episodes, other characters from the book also appear, who are highlighted in different colors.

Batch 32
Also, each show will provide book recommendations that every child should ask for when they go to the library.
Исто така, секое шоу ќи обезбеди препораки за книги што секое дете би требало да ги побара кога оди во библиотека.
Response (English): Also, each show will provide book recommendations that every child should ask for when they go to the library.
Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германиј

Batch 40
John Grant, from WNED Buffalo ("Reading Rainbow's host station), said: "Reading Rainbow taught children why they should read... the love of reading — [the series] encouraged children to take a book and read".
Example 2
Macedonian: Во 2011 година, во САД, беше извршена истрага за наводите дека „Reading Rainbow“ го користеше фондот за образование за да ги финансира своите филмови.
Response (English): In 2011, in the United States, an investigation was conducted into

Batch 40
Some people, including John Grant, believe that the church financier and the change in philosophy for the educational content programs contributed to the break-up of the show.
Example 2
Macedonian: Во 2011 година, војската на САД се повлекла од Ирак, а во 2014 година, војската на САД се повлекла од Афганистан.

In [48]:
predictions = [elem.split("Example")[0] for elem in predictions_eng]
predictions

["On Monday, scientists from the medical school at Stanford University announced that they had invented a new tool for diagnosis that sorts cells by type: a small chip for printing that can be produced with the help of standard inkjet printers, at a cost of around one American cent.  Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.\nResponse (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of",
 'The leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with a low standard of living, where the survival rate from breast cancer, for example, can be twice as low as in wealthier countries. \n',
 "The JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights. \nText:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.\nResponse (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.",
 'It has been confirmed that the pilot was Dilokrit Patavi, the leader of the squadron. \n',
 "Local media report on an airport fire truck that overturned while firefighters inside it responded to a call. \nText:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.\nResponse (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.\nText:Еден спортски натпревар трае 90 минунти, од",
 'The 28-year-old Vidal from Seville joined the Barcelona team.  The 28-year-old Vidal from Seville joined the Barcelona team.  The 28-year-old Vidal from Seville joined the Barcelona team.  The 28-year-old Vidal from Seville joined the Barcelona team.  The 28-year-old Vidal from Seville joined the Barcelona team.  The 28-year-old Vidal from Seville joined the Barcelona team.  The 28-year-old Vidal from Seville joined the Barcelona team.  The 28-year-old Vidal from Seville joined the Barcelona team.',
 'After moving to the capital of Catalonia, Vidal played 49 games for the club. \n',
 'The protest began around 11:00 am local time (UTC+1) in Whitehall, on the opposite side of the entrance guarded by police on Downing Street, the official residence of the Prime Minister.  The protesters were mostly young people, some of whom were dressed in black, and they were armed with banners, placards, and a megaphone.  They were shouting slogans and chanting slogans, including "What do we want?  Justice!  When do we want it?  Now!"  The protesters were also holding a banner that read "Stop the War" and another that read "Hands off Iraq".',
 'Immediately after 11:00 am, the demonstrators blocked traffic to the north in Whitehall. \nВеднаш по 11:00 часот демонстрантите го блокираа сообраќајот кон север во Вајтхол. \nResponse (English): Immediately after 11:00 am, the demonstrators blocked traffic to the north in Whitehall. \nВо 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економ',
 'At 11:20 am, the police asked the protesters to move to the sidewalk, citing that they needed to balance the right to protest with the traffic congestion. \nВо 11:30 часот, полицијата ги натерала протестантите да ги напуштат тротоарот и да се вратат во зградата на парламентот.\nResponse (English): At 11:30 am, the police forced the protesters to leave the sidewalk and return to the parliament building.\nВо 11:40 часот, полицијата ги натерала протест',
 "Around 11:29 am, the protest moved to Whitehall, near Trafalgar Square, near the Strand, passing by Aldwych and through King's Way to Holborn, where the Conservative Party was holding its Spring Forum in the Grand Connaught Rooms.  The protesters were met with a line of police officers, who were trying to keep them away from the building.  The protesters were shouting slogans and holding up signs, while the police were trying to keep them calm.  The protesters were trying to get closer to the building, but the police were holding them back.  The protesters were shouting slogans and holding",
 "Nadal's personal record against the Canadian is 7-2. \n",
 'Recently lost to Raonic at Brisbane Open. \nText:Се чини дека е добар ден за играње тенис.\nResponse (English): It seems to be a good day for playing tennis.\nText:Се чини дека е добар ден за играње тенис.\nResponse (English): It seems to be a good day for playing tennis.\nText:Се чини дека е добар ден за играње тенис.\nResponse (English): It seems to be a good day for playing tennis.\nText:Се чини дека е добар ден за игра',
 'Nadal won 88% of the points on the net in the match, winning 76 points in the first service. \n',
 'After the game, the King of the Ground Floor said: "I\'m simply excited to have returned to the final rounds of the most important events. I\'m here to try to win". \nNote: The text is a quote from a Macedonian language text. The translation is provided in the response. The translation is not an original text, but a translation of a quote.  Please let me know if you need any further assistance.  I\'ll be happy to help.  Thank you.  Best regards.  I hope this helps.  Please let me know if you need any further assistance.  I\'ll be happy to',
 '"Panama Papers" is a term for almost ten million documents from the Panamanian law firm Mossack Fonseca, which were published in the press in the spring of 2016. \n  ',
 'According to the documents, fourteen banks helped wealthy clients to hide billions of American dollars in order to evade taxes and other laws.  The banks helped the clients to set up secret accounts and to transfer money to them.  The banks also helped the clients to set up offshore companies and to transfer money to them.  The banks helped the clients to set up secret trusts and to transfer money to them.  The banks helped the clients to set up secret foundations and to transfer money to them.  The banks helped the clients to set up secret charities and to transfer money to them.  The banks helped the clients to set up secret real estate',
 'The British newspaper "The Guardian" reported that "Deutsche Bank" controlled approximately one-third of the 1,200 provisional companies used to achieve this. \nText:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.\nResponse (English): At 11 o\'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.\nText:Еден спортски нат',
 'This led to the organization of protests around the world, a number of criminal prosecutions, and the prime ministers of Iceland and Pakistan submitting their resignations. \nТоа доведе до организирање протести низ целиот свет, одреден број кривични гонења, а премиерите на Исланд и Пакистан си поднесоа оставка.\nResponse (English): This led to the organization of protests around the world, a number of criminal prosecutions, and the prime ministers of Iceland and Pakistan submitting their resignations. \nВо 11',
 'Born in Hong Kong, Ma studied at New York University and Harvard Law School, and had an American permanent "green card". \n',
 'This implies that Ma could flee the country in case of a crisis during the elections. \n',
 'He also argued that the photogenic Ma was more about style, than about substance. \nText:Со помош на оваа алатка, клетките можат да се подредуваат по тип, што значи дека можат да се дијагностицираат болести предизвикани од мали клетки.\nResponse (English): With the help of this tool, cells can be sorted by type, which means that diseases caused by small cells can be diagnosed.\nText:Во 11 часот е договорена средба помеѓу премиерот на Вели',
 'Despite these allegations, Ma easily won with a platform that advocates for closer ties with continental China. \n',
 'Today, the player of the day is Alex Ovechkin of the Washington Capitals team.  The 34-year-old Russian forward has been playing in the NHL since 2005 and has won numerous awards, including the Hart Memorial Trophy, the Art Ross Trophy, and the Ted Lindsay Award.  He has also been named to the NHL First Team All-Stars three times and has been selected to the NHL Second Team All-Stars twice.  Ovechkin has also represented Russia in several international tournaments, including the Winter Olympics and the World Championships.  He has won a gold medal at the 2006 Winter Olympics and',
 'There were 2 goals and 2 assists in the 5-3 win by Washington against Atlanta Thrashers. \n',
 'The first assist of the evening for Ovechkin was for the winning goal of rookie Niklas Backstrom; \nПрвата асистенција на Овечкин во второто полувреме беше за голот на Дејвид Стемкoс;\nResponse (English): The first assist of the evening for Ovechkin in the second period was for the goal of David Steckel;\nПрвата асистенција на Овечкин во третото полувреме беше за голот на Брукс Лаферти;',
 'His second goal of the evening was the 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96, when that record was also achieved by Jaromir Jagr and Mario Lemieux.  The 60th goal was scored in the 60th minute of the game.  The 60th goal was scored in the 60th minute of the game.  The 60th goal was scored in the 60th minute of the game.  The 60th goal was scored in the 60th minute of the game.  The',
 'Baten was ranked as 190th on the list of 400 richest Americans for 2008 with an estimated wealth of $2.3 billion. \n',
 'She graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished herself as a major donor to the institution. \nДипломираше на Колеџот за уметности и науки на Универзитетот Вирџинија во 1950 година и се издвои како важен донатор на институцијата.\nResponse (English): She graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished herself as a major donor to the institution. \nДипломираше на Колеџот за',
 'The Iraqi prison "Abu Ghraib" was burned during a riot.  The Iraqi prison "Abu Ghraib" was burned during a riot.  The Iraqi prison "Abu Ghraib" was burned during a riot.  The Iraqi prison "Abu Ghraib" was burned during a riot.  The Iraqi prison "Abu Ghraib" was burned during a riot.  The Iraqi prison "Abu Ghraib" was burned during a riot.  The Iraqi prison "Abu Ghraib" was burned during a riot.  The Iraqi prison "Abu Ghraib',
 'The prison became infamous after the abuse of the inmates was discovered after it was taken over by the American military forces. \n',
 "Piquet Junior crashed in the 2008 Singapore Grand Prix immediately after an early pit stop by Fernando Alonso, after which the safety car was deployed. \nText:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.\nResponse (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.\nText:Еден спортски нат",
 "While the cars ahead of Alonso went to refuel behind the safety car, he took the lead to come out on top. \nText:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.\nResponse (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.\nText:Еден спортски натпревар трае",
 "Piquet the Younger was sacked after the Hungarian Grand Prix in 2009.  The team's performance was poor, with Timo Glock finishing 14th and Jarno Trulli 15th.  Glock was given a new contract, but Trulli was released.  Glock's new contract was for one year, with an option for a further year.  Glock's new contract was for one year, with an option for a further year.  Glock's new contract was for one year, with an option for a further year.  Glock's new contract was for one year, with an option for",
 "Exactly at 8:46 am, a commotion broke out in the city, marking the exact moment when the first plane hit its target. \nВо 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.\nResponse (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.\nЕден спортски натпревар трае",
 'Two light rays were set to show at night to the sky. \n',
 'The construction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle. \n  ',
 "The PBS series has more than two dozen Emmy Awards and is shorter than it is only occasionally broadcast from Sesame Street and Mr. Rogers' Neighborhood. \nПремиерите на серијалот се одржале во 2005 година во САД и во 2006 година во Велика Британија.\nResponse (English): The premieres of the series took place in 2005 in the United States and in 2006 in the United Kingdom.\nВо 2007 година, серијалот бил емитуван во повеќе од",
 'Each episode of the show focuses on a theme from a specific book, and then explores that theme through several stories. \nСекоја епизода се завршува со интервју со авторот на книгата.\nResponse (English): Each episode ends with an interview with the author of the book.\nВо епизодите се појавуваат и други ликови од книгата, кои се истакнуваат со различни бои.\nResponse (English): In the episodes, other characters from the book also appear, who are highlighted in different colors.',
 'Also, each show will provide book recommendations that every child should ask for when they go to the library. \nИсто така, секое шоу ќи обезбеди препораки за книги што секое дете би требало да ги побара кога оди во библиотека.\nResponse (English): Also, each show will provide book recommendations that every child should ask for when they go to the library. \nВо 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германиј',
 'John Grant, from WNED Buffalo ("Reading Rainbow\'s host station), said: "Reading Rainbow taught children why they should read... the love of reading — [the series] encouraged children to take a book and read". \n',
 'Some people, including John Grant, believe that the church financier and the change in philosophy for the educational content programs contributed to the break-up of the show. \n',
 'The storm, located 645 miles (1040 km) west of the islands of the Green Horn, will likely be scattered before it poses any threat to any land area, meteorologists say.  The storm is expected to bring heavy rain and strong winds to the islands, but it is not expected to make landfall.  The National Hurricane Center has issued a tropical storm watch for the islands, and residents are advised to take precautions.  The storm is expected to bring strong winds and heavy rain to the islands, but it is not expected to make landfall.  The National Hurricane Center has issued a tropical storm watch for the islands',
 'At the moment, Fred is experiencing winds blowing at a speed of 105 miles per hour (165 km/h) and is moving northwest.  The wind is blowing at a speed of 105 miles per hour (165 km/h) and is moving northwest.  The wind is blowing at a speed of 105 miles per hour (165 km/h) and is moving northwest.  The wind is blowing at a speed of 105 miles per hour (165 km/h) and is moving northwest.  The wind is blowing at a speed of 105 miles per hour (165 km/h) and is moving northwest.  The wind is',
 'Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic from satellite imagery, but it is only the third major hurricane recorded east of 35° W. \n',
 "On September 24, 1759, Arthur Guinness signed a 9,000-year lease for the St. James's Gate Brewery in Dublin, Ireland.  ",
 '250 years later, "Ginés" grew into a global business with an annual turnover of 10 billion euros (14.7 billion dollars). 250 years later, "Ginés" grew into a global business with an annual turnover of 10 billion euros (14.7 billion dollars). 250 years later, "Ginés" grew into a global business with an annual turnover of 10 billion euros (14.7 billion dollars). 250 years later, "Ginés" grew into a global business with an annual turnover of 10 billion euros (14.7 billion dollars). 250 years later',
 'Johnny Reid, a co-driver for the A1GP team from New Zealand, today created a historic event by legally crossing the 48-year-old Auckland Harbour Bridge in New Zealand in the shortest time. \n  ',
 "Mr. Reid managed to drive the New Zealand A1GP car, Black Swan at a speed of over 160 km/h seven times across the bridge. \nText:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.\nResponse (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.\nText:Еден спортски нат",
 'The New Zealand police are facing a problem in using the radar to determine the speed of Mr. Reid, due to the height of the Black Peak, and the only path when the police managed to catch Mr. Reid was when he slowed down to 160 km/h. \n',
 'In the last 3 months, over 80 detainees have been released from the detention center without being formally charged. \n',
 'In April this year, Judge Glyn issued an order to temporarily restrict the institution of those who are detained for more than 24 hours after being arrested, who have not been heard by a judicial commissioner.  1. Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања. 2. Еден спортски натпревар трае 90 минунти, односно две полувремињ',
 'The commissioner determines bail, if allowed, and formalizes the charges submitted by the officer who made the arrests. Then the charges are entered into the state computer system where the case is being followed. \n',
 'The date for the speedy trial of the accused will also be determined at this hearing. \n',
 'Peter Costello, the Australian Minister for Finance and the man with the greatest potential to replace Prime Minister John Howard as the leader of the Liberal Party, has expressed his support for the nuclear energy industry in Australia.  The Australian government has been considering the development of a nuclear industry in the country.  The government has been looking at the possibility of building a nuclear power plant in the state of South Australia.  The nuclear power plant would be used to generate electricity for the state.  The government has been considering the possibility of building a nuclear power plant in the state of South Australia.  The nuclear power plant would be used to generate electricity',
 "G. Costello said that when nuclear reactors will be economically viable, Australia will begin to use them. \nText:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.\nResponse (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.\nText:Еден спортски натпревар трае 90 минунти",

In [49]:
predictions_new = [first_sentence(text) for text in predictions]
predictions_new

['On Monday, scientists from the medical school at Stanford University announced that they had invented a new tool for diagnosis that sorts cells by type: a small chip for printing that can be produced with the help of standard inkjet printers, at a cost of around one American cent.',
 'The leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with a low standard of living, where the survival rate from breast cancer, for example, can be twice as low as in wealthier countries.',
 'The JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights.',
 'It has been confirmed that the pilot was Dilokrit Patavi, the leader of the squadron.',
 'Local media report on an airport fire truck that overturned while firefighters inside it responded to a call.',
 'The 28-year-old Vidal from Seville joined the Barcelona team.',
 'After moving to the capital of Catalonia, Vidal played 49 games for the club.',
 'The protest began around 11:00 am local time (UTC+1) in Whitehall, on the opposite side of the entrance guarded by police on Downing Street, the official residence of the Prime Minister.',
 'Immediately after 11:00 am, the demonstrators blocked traffic to the north in Whitehall.',
 'At 11:20 am, the police asked the protesters to move to the sidewalk, citing that they needed to balance the right to protest with the traffic congestion.',
 "Around 11:29 am, the protest moved to Whitehall, near Trafalgar Square, near the Strand, passing by Aldwych and through King's Way to Holborn, where the Conservative Party was holding its Spring Forum in the Grand Connaught Rooms.",
 "Nadal's personal record against the Canadian is 7-2.",
 'Recently lost to Raonic at Brisbane Open.',
 'Nadal won 88% of the points on the net in the match, winning 76 points in the first service.',
 'After the game, the King of the Ground Floor said: "I\'m simply excited to have returned to the final rounds of the most important events.',
 '"Panama Papers" is a term for almost ten million documents from the Panamanian law firm Mossack Fonseca, which were published in the press in the spring of 2016.',
 'According to the documents, fourteen banks helped wealthy clients to hide billions of American dollars in order to evade taxes and other laws.',
 'The British newspaper "The Guardian" reported that "Deutsche Bank" controlled approximately one-third of the 1,200 provisional companies used to achieve this.',
 'This led to the organization of protests around the world, a number of criminal prosecutions, and the prime ministers of Iceland and Pakistan submitting their resignations.',
 'Born in Hong Kong, Ma studied at New York University and Harvard Law School, and had an American permanent "green card".',
 'This implies that Ma could flee the country in case of a crisis during the elections.',
 'He also argued that the photogenic Ma was more about style, than about substance.',
 'Despite these allegations, Ma easily won with a platform that advocates for closer ties with continental China.',
 'Today, the player of the day is Alex Ovechkin of the Washington Capitals team.',
 'There were 2 goals and 2 assists in the 5-3 win by Washington against Atlanta Thrashers.',
 'The first assist of the evening for Ovechkin was for the winning goal of rookie Niklas Backstrom; \nПрвата асистенција на Овечкин во второто полувреме беше за голот на Дејвид Стемкoс;\nResponse (English): The first assist of the evening for Ovechkin in the second period was for the goal of David Steckel;\nПрвата асистенција на Овечкин во третото полувреме беше за голот на Брукс Лаферти;',
 'His second goal of the evening was the 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96, when that record was also achieved by Jaromir Jagr and Mario Lemieux.',
 'Baten was ranked as 190th on the list of 400 richest Americans for 2008 with an estimated wealth of $2.3 billion.',
 'She graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished herself as a major donor to the institution.',
 'The Iraqi prison "Abu Ghraib" was burned during a riot.',
 'The prison became infamous after the abuse of the inmates was discovered after it was taken over by the American military forces.',
 'Piquet Junior crashed in the 2008 Singapore Grand Prix immediately after an early pit stop by Fernando Alonso, after which the safety car was deployed.',
 'While the cars ahead of Alonso went to refuel behind the safety car, he took the lead to come out on top.',
 'Piquet the Younger was sacked after the Hungarian Grand Prix in 2009.',
 'Exactly at 8:46 am, a commotion broke out in the city, marking the exact moment when the first plane hit its target.',
 'Two light rays were set to show at night to the sky.',
 'The construction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle.',
 "The PBS series has more than two dozen Emmy Awards and is shorter than it is only occasionally broadcast from Sesame Street and Mr. Rogers' Neighborhood.",
 'Each episode of the show focuses on a theme from a specific book, and then explores that theme through several stories.',
 'Also, each show will provide book recommendations that every child should ask for when they go to the library.',
 'John Grant, from WNED Buffalo ("Reading Rainbow\'s host station), said: "Reading Rainbow taught children why they should read... the love of reading — [the series] encouraged children to take a book and read".',
 'Some people, including John Grant, believe that the church financier and the change in philosophy for the educational content programs contributed to the break-up of the show.',
 'The storm, located 645 miles (1040 km) west of the islands of the Green Horn, will likely be scattered before it poses any threat to any land area, meteorologists say.',
 'At the moment, Fred is experiencing winds blowing at a speed of 105 miles per hour (165 km/h) and is moving northwest.',
 'Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic from satellite imagery, but it is only the third major hurricane recorded east of 35° W.',
 "On September 24, 1759, Arthur Guinness signed a 9,000-year lease for the St. James's Gate Brewery in Dublin, Ireland.",
 '250 years later, "Ginés" grew into a global business with an annual turnover of 10 billion euros (14.7 billion dollars).',
 'Johnny Reid, a co-driver for the A1GP team from New Zealand, today created a historic event by legally crossing the 48-year-old Auckland Harbour Bridge in New Zealand in the shortest time.',
 'Mr. Reid managed to drive the New Zealand A1GP car, Black Swan at a speed of over 160 km/h seven times across the bridge.',
 'The New Zealand police are facing a problem in using the radar to determine the speed of Mr. Reid, due to the height of the Black Peak, and the only path when the police managed to catch Mr. Reid was when he slowed down to 160 km/h.',
 'In the last 3 months, over 80 detainees have been released from the detention center without being formally charged.',
 'In April this year, Judge Glyn issued an order to temporarily restrict the institution of those who are detained for more than 24 hours after being arrested, who have not been heard by a judicial commissioner.',
 'The commissioner determines bail, if allowed, and formalizes the charges submitted by the officer who made the arrests.',
 'The date for the speedy trial of the accused will also be determined at this hearing.',
 'Peter Costello, the Australian Minister for Finance and the man with the greatest potential to replace Prime Minister John Howard as the leader of the Liberal Party, has expressed his support for the nuclear energy industry in Australia.',
 'G. Costello said that when nuclear reactors will be economically viable, Australia will begin to use them.',
 '“If it becomes commercial, we should have it.',
 'According to Ansa, "the police were worried about several high-level attacks for which they feared they could trigger a war for the successor in full swing".',
 "The police announced that Lo Piccolo had control because he was the right-hand man of Provenzano in Palermo, and his greater experience won the respect of the older generation of bosses because they followed Provenzano's policy of staying as hidden as possible while they strengthened their network of authority.",
 'These bosses were taken by Pervenzo when he put an end to the war sparked by Riiina against the state which took the lives of the "crusaders" of the mafia, Giovanni Falcone and Paolo Borsellino in 1992.',
 "The CEO of Apple, Steve Jobs, unveiled the device by stepping on stage and pulling out the iPhone from his pocket on the farmer's market.",
 'During his 2-hour speech, he stated that „Apple will invent the telephone again, Today we will create history“.',
 'Brazil is the largest Catholic country in the world and the Catholic Church has been consistently against the legalization of same-sex marriage in the country.',
 'The Brazilian State Congress has been debating the legalization of civil unions for ten years; and despite this, such civil unions are currently legal only in Rio Grande do Sul.',
 'The original bill was drafted by Marta Suplicy, the former mayor of São Paulo.',
 'Protestants are hoping to gather 1.2 million signatures for the petition that they will present to the National Congress in November.',
 'After it became clear that many families were seeking legal help to deal with the evictions, a meeting was held on March 20 at the Community Legal Centre in East Bay for the victims of the housing scam.',
 'When the residents started sharing what happened to them, it became clear to most of the families involved that Carolin Wilson of OHA had stolen their security deposits and had fled the city.',
 'Residents in Lockwood Gardens believe there may be 40 families or more who are facing eviction, as they learned that the Oakland Housing Authority police are investigating and other rental properties in Oakland that may be involved in the housing scam.',
 'The band cancelled the performance that was to be held at the military memorial stadium on Maui, where 9000 people were to attend, and apologized to the fans.',
 "The band's management company, HK Management Inc., did not issue an official statement on the reasons for the cancellation on September 20, but the next day stated that it was a logistical problem.",
 'The well-known Greek lawyers, Sakis Kehayioyglou and George Nikolakopoulos, are imprisoned in the Korydallos prison in Athens, after being found guilty of bribery and corruption.',
 'As a result, a major scandal broke out in the Greek legal community with the revelation of the illegal activities that judges, lawyers, attorneys and legal guardians had been carrying out in the previous years.',
 'A few weeks ago, following the information published by journalist Makis Triantafyllopoulos in his popular TV show "Zooungra" on Alpha TV, MP and lawyer Petros Mantouvalos resigned because members of his cabinet were involved in bribery and corruption.',
 'In addition, the top judge Evangelos Kalos, is in custody for corruption and improper behavior.',
 'Roberts declined to comment on his belief about when life begins, which is an important issue given the ethics of abortion, saying it would be unethical to comment on the specific details of potential cases.',
 'However, he confirmed his previous statement that Ruo vs. Wei is the "main standard", emphasizing the importance of consistent decisions by the Supreme Court.',
 'He also confirmed that he believes in the inalienable right to privacy, on which the Row decision was based.',
 'Maruchidore finished at the top of the scale, with a six-point lead over Nusa, who is second-placed.',
 'The two teams met in the big semifinals, where Nusa came to a victory with an 11-point difference.',
 'Then Maruchidor defeated Kabultur in the preliminary final.',
 'Hesperonychus elizabethae is a species of the family Dromaeosauridae that is closely related to the velociraptor.',
 'It is believed that this warm-blooded bird of prey with feathers all over its body walked upright on two legs, with claws like those of the velociraptor.',
 'His second claw was larger, from which the name Hesperonihus was derived, meaning "western claw".',
 'The extreme weather conditions, including the ice that is breaking, are complicating the rescue efforts.',
 'Pitman notes that the conditions will not improve until next week.',
 'The quantity and thickness of the sea ice, according to Pitman, is the worst so far for seal hunters in the past 15 years.',
 'Today, in the Red Lake district, after the funerals of Jeff Weise and three of the nine victims, news spread that another student was arrested in connection with the shooting at the school on March 21.',
 'The authorities officially did not say much, except that they confirmed the current arrest.',
 'However, a source with knowledge of the investigation told the "Minneapolis Star-Tribune" that it was Louis Jourdren, the 16-year-old son of tribal chairman Floyd Jourdren.',
 'At the moment, it is not known what charges will be filed, nor what led the authorities to the boy, but the procedure against the minor has been started in a federal court.',
 'Also, Lodi says that the officials decided to cancel the second round of elections to save the Afghans from expenses and to avoid the security risk of another voting.',
 'Diplomats said they found enough ambiguities in the Afghan Constitution to determine that a second round of elections is unnecessary.',
 'This is contradictory to the previous statements, which said that the cancellation of the second round would be unconstitutional.',
 'The plane had been headed towards Irkutsk and was being operated by internal troops.',
 'An investigation has been launched to investigate.',
 'II-76 was the largest component of both the Russian and Soviet army since the 1970s, which last month suffered a serious disaster in Russia.',
 'On October 7, the engine separated during takeoff, without damage.',
 '800 miles of the Trans-Alaska pipeline were shut down after thousands of raw oil wells ran dry south of Fairbanks, Alaska.',
 'Following a routine test of the fire management system, a power outage occurred, causing the pressure vents to open and crude oil to spill near pump station 9 at Fort Greely.']

In [50]:
predictions_new = [text.split("\nПрвата")[0] for text in predictions_new]
predictions_new

['On Monday, scientists from the medical school at Stanford University announced that they had invented a new tool for diagnosis that sorts cells by type: a small chip for printing that can be produced with the help of standard inkjet printers, at a cost of around one American cent.',
 'The leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with a low standard of living, where the survival rate from breast cancer, for example, can be twice as low as in wealthier countries.',
 'The JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights.',
 'It has been confirmed that the pilot was Dilokrit Patavi, the leader of the squadron.',
 'Local media report on an airport fire truck that overturned while firefighters inside it responded to a call.',
 'The 28-year-old Vidal from Seville joined the Barcelona team.',
 'After moving to the capital of Catalonia, Vidal played 49 games for the club.',
 'The protest began around 11:00 am local time (UTC+1) in Whitehall, on the opposite side of the entrance guarded by police on Downing Street, the official residence of the Prime Minister.',
 'Immediately after 11:00 am, the demonstrators blocked traffic to the north in Whitehall.',
 'At 11:20 am, the police asked the protesters to move to the sidewalk, citing that they needed to balance the right to protest with the traffic congestion.',
 "Around 11:29 am, the protest moved to Whitehall, near Trafalgar Square, near the Strand, passing by Aldwych and through King's Way to Holborn, where the Conservative Party was holding its Spring Forum in the Grand Connaught Rooms.",
 "Nadal's personal record against the Canadian is 7-2.",
 'Recently lost to Raonic at Brisbane Open.',
 'Nadal won 88% of the points on the net in the match, winning 76 points in the first service.',
 'After the game, the King of the Ground Floor said: "I\'m simply excited to have returned to the final rounds of the most important events.',
 '"Panama Papers" is a term for almost ten million documents from the Panamanian law firm Mossack Fonseca, which were published in the press in the spring of 2016.',
 'According to the documents, fourteen banks helped wealthy clients to hide billions of American dollars in order to evade taxes and other laws.',
 'The British newspaper "The Guardian" reported that "Deutsche Bank" controlled approximately one-third of the 1,200 provisional companies used to achieve this.',
 'This led to the organization of protests around the world, a number of criminal prosecutions, and the prime ministers of Iceland and Pakistan submitting their resignations.',
 'Born in Hong Kong, Ma studied at New York University and Harvard Law School, and had an American permanent "green card".',
 'This implies that Ma could flee the country in case of a crisis during the elections.',
 'He also argued that the photogenic Ma was more about style, than about substance.',
 'Despite these allegations, Ma easily won with a platform that advocates for closer ties with continental China.',
 'Today, the player of the day is Alex Ovechkin of the Washington Capitals team.',
 'There were 2 goals and 2 assists in the 5-3 win by Washington against Atlanta Thrashers.',
 'The first assist of the evening for Ovechkin was for the winning goal of rookie Niklas Backstrom; ',
 'His second goal of the evening was the 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96, when that record was also achieved by Jaromir Jagr and Mario Lemieux.',
 'Baten was ranked as 190th on the list of 400 richest Americans for 2008 with an estimated wealth of $2.3 billion.',
 'She graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished herself as a major donor to the institution.',
 'The Iraqi prison "Abu Ghraib" was burned during a riot.',
 'The prison became infamous after the abuse of the inmates was discovered after it was taken over by the American military forces.',
 'Piquet Junior crashed in the 2008 Singapore Grand Prix immediately after an early pit stop by Fernando Alonso, after which the safety car was deployed.',
 'While the cars ahead of Alonso went to refuel behind the safety car, he took the lead to come out on top.',
 'Piquet the Younger was sacked after the Hungarian Grand Prix in 2009.',
 'Exactly at 8:46 am, a commotion broke out in the city, marking the exact moment when the first plane hit its target.',
 'Two light rays were set to show at night to the sky.',
 'The construction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle.',
 "The PBS series has more than two dozen Emmy Awards and is shorter than it is only occasionally broadcast from Sesame Street and Mr. Rogers' Neighborhood.",
 'Each episode of the show focuses on a theme from a specific book, and then explores that theme through several stories.',
 'Also, each show will provide book recommendations that every child should ask for when they go to the library.',
 'John Grant, from WNED Buffalo ("Reading Rainbow\'s host station), said: "Reading Rainbow taught children why they should read... the love of reading — [the series] encouraged children to take a book and read".',
 'Some people, including John Grant, believe that the church financier and the change in philosophy for the educational content programs contributed to the break-up of the show.',
 'The storm, located 645 miles (1040 km) west of the islands of the Green Horn, will likely be scattered before it poses any threat to any land area, meteorologists say.',
 'At the moment, Fred is experiencing winds blowing at a speed of 105 miles per hour (165 km/h) and is moving northwest.',
 'Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic from satellite imagery, but it is only the third major hurricane recorded east of 35° W.',
 "On September 24, 1759, Arthur Guinness signed a 9,000-year lease for the St. James's Gate Brewery in Dublin, Ireland.",
 '250 years later, "Ginés" grew into a global business with an annual turnover of 10 billion euros (14.7 billion dollars).',
 'Johnny Reid, a co-driver for the A1GP team from New Zealand, today created a historic event by legally crossing the 48-year-old Auckland Harbour Bridge in New Zealand in the shortest time.',
 'Mr. Reid managed to drive the New Zealand A1GP car, Black Swan at a speed of over 160 km/h seven times across the bridge.',
 'The New Zealand police are facing a problem in using the radar to determine the speed of Mr. Reid, due to the height of the Black Peak, and the only path when the police managed to catch Mr. Reid was when he slowed down to 160 km/h.',
 'In the last 3 months, over 80 detainees have been released from the detention center without being formally charged.',
 'In April this year, Judge Glyn issued an order to temporarily restrict the institution of those who are detained for more than 24 hours after being arrested, who have not been heard by a judicial commissioner.',
 'The commissioner determines bail, if allowed, and formalizes the charges submitted by the officer who made the arrests.',
 'The date for the speedy trial of the accused will also be determined at this hearing.',
 'Peter Costello, the Australian Minister for Finance and the man with the greatest potential to replace Prime Minister John Howard as the leader of the Liberal Party, has expressed his support for the nuclear energy industry in Australia.',
 'G. Costello said that when nuclear reactors will be economically viable, Australia will begin to use them.',
 '“If it becomes commercial, we should have it.',
 'According to Ansa, "the police were worried about several high-level attacks for which they feared they could trigger a war for the successor in full swing".',
 "The police announced that Lo Piccolo had control because he was the right-hand man of Provenzano in Palermo, and his greater experience won the respect of the older generation of bosses because they followed Provenzano's policy of staying as hidden as possible while they strengthened their network of authority.",
 'These bosses were taken by Pervenzo when he put an end to the war sparked by Riiina against the state which took the lives of the "crusaders" of the mafia, Giovanni Falcone and Paolo Borsellino in 1992.',
 "The CEO of Apple, Steve Jobs, unveiled the device by stepping on stage and pulling out the iPhone from his pocket on the farmer's market.",
 'During his 2-hour speech, he stated that „Apple will invent the telephone again, Today we will create history“.',
 'Brazil is the largest Catholic country in the world and the Catholic Church has been consistently against the legalization of same-sex marriage in the country.',
 'The Brazilian State Congress has been debating the legalization of civil unions for ten years; and despite this, such civil unions are currently legal only in Rio Grande do Sul.',
 'The original bill was drafted by Marta Suplicy, the former mayor of São Paulo.',
 'Protestants are hoping to gather 1.2 million signatures for the petition that they will present to the National Congress in November.',
 'After it became clear that many families were seeking legal help to deal with the evictions, a meeting was held on March 20 at the Community Legal Centre in East Bay for the victims of the housing scam.',
 'When the residents started sharing what happened to them, it became clear to most of the families involved that Carolin Wilson of OHA had stolen their security deposits and had fled the city.',
 'Residents in Lockwood Gardens believe there may be 40 families or more who are facing eviction, as they learned that the Oakland Housing Authority police are investigating and other rental properties in Oakland that may be involved in the housing scam.',
 'The band cancelled the performance that was to be held at the military memorial stadium on Maui, where 9000 people were to attend, and apologized to the fans.',
 "The band's management company, HK Management Inc., did not issue an official statement on the reasons for the cancellation on September 20, but the next day stated that it was a logistical problem.",
 'The well-known Greek lawyers, Sakis Kehayioyglou and George Nikolakopoulos, are imprisoned in the Korydallos prison in Athens, after being found guilty of bribery and corruption.',
 'As a result, a major scandal broke out in the Greek legal community with the revelation of the illegal activities that judges, lawyers, attorneys and legal guardians had been carrying out in the previous years.',
 'A few weeks ago, following the information published by journalist Makis Triantafyllopoulos in his popular TV show "Zooungra" on Alpha TV, MP and lawyer Petros Mantouvalos resigned because members of his cabinet were involved in bribery and corruption.',
 'In addition, the top judge Evangelos Kalos, is in custody for corruption and improper behavior.',
 'Roberts declined to comment on his belief about when life begins, which is an important issue given the ethics of abortion, saying it would be unethical to comment on the specific details of potential cases.',
 'However, he confirmed his previous statement that Ruo vs. Wei is the "main standard", emphasizing the importance of consistent decisions by the Supreme Court.',
 'He also confirmed that he believes in the inalienable right to privacy, on which the Row decision was based.',
 'Maruchidore finished at the top of the scale, with a six-point lead over Nusa, who is second-placed.',
 'The two teams met in the big semifinals, where Nusa came to a victory with an 11-point difference.',
 'Then Maruchidor defeated Kabultur in the preliminary final.',
 'Hesperonychus elizabethae is a species of the family Dromaeosauridae that is closely related to the velociraptor.',
 'It is believed that this warm-blooded bird of prey with feathers all over its body walked upright on two legs, with claws like those of the velociraptor.',
 'His second claw was larger, from which the name Hesperonihus was derived, meaning "western claw".',
 'The extreme weather conditions, including the ice that is breaking, are complicating the rescue efforts.',
 'Pitman notes that the conditions will not improve until next week.',
 'The quantity and thickness of the sea ice, according to Pitman, is the worst so far for seal hunters in the past 15 years.',
 'Today, in the Red Lake district, after the funerals of Jeff Weise and three of the nine victims, news spread that another student was arrested in connection with the shooting at the school on March 21.',
 'The authorities officially did not say much, except that they confirmed the current arrest.',
 'However, a source with knowledge of the investigation told the "Minneapolis Star-Tribune" that it was Louis Jourdren, the 16-year-old son of tribal chairman Floyd Jourdren.',
 'At the moment, it is not known what charges will be filed, nor what led the authorities to the boy, but the procedure against the minor has been started in a federal court.',
 'Also, Lodi says that the officials decided to cancel the second round of elections to save the Afghans from expenses and to avoid the security risk of another voting.',
 'Diplomats said they found enough ambiguities in the Afghan Constitution to determine that a second round of elections is unnecessary.',
 'This is contradictory to the previous statements, which said that the cancellation of the second round would be unconstitutional.',
 'The plane had been headed towards Irkutsk and was being operated by internal troops.',
 'An investigation has been launched to investigate.',
 'II-76 was the largest component of both the Russian and Soviet army since the 1970s, which last month suffered a serious disaster in Russia.',
 'On October 7, the engine separated during takeoff, without damage.',
 '800 miles of the Trans-Alaska pipeline were shut down after thousands of raw oil wells ran dry south of Fairbanks, Alaska.',
 'Following a routine test of the fire management system, a power outage occurred, causing the pressure vents to open and crude oil to spill near pump station 9 at Fort Greely.']

In [51]:
references = [[ref] for ref in text_eng]
references[:10]

[['On Monday, scientists from the Stanford University School of Medicine announced the invention of a new diagnostic tool that can sort cells by type: a tiny printable chip that can be manufactured using standard inkjet printers for possibly about one U.S. cent each.'],
 ['Lead researchers say this may bring early detection of cancer, tuberculosis, HIV and malaria to patients in low-income countries, where the survival rates for illnesses such as breast cancer can be half those of richer countries.'],
 ['The JAS 39C Gripen crashed onto a runway at around 9:30 am local time (0230 UTC) and exploded, closing the airport to commercial flights.'],
 ['The pilot was identified as Squadron Leader Dilokrit Pattavee.'],
 ['Local media reports an airport fire vehicle rolled over while responding.'],
 ['28-year-old Vidal had joined Barça three seasons ago, from Sevilla.'],
 ['Since moving to the Catalan-capital, Vidal had played 49 games for the club.'],
 ["The protest started around 11:00 local time (UTC+1) on Whitehall opposite the police-guarded entrance to Downing Street, the Prime Minister's official residence."],
 ['Just after 11:00, protesters blocked traffic on the northbound carriage in Whitehall.'],
 ['At 11:20, the police asked the protesters to move back on to the pavement, stating that they needed to balance the right to protest with the traffic building up.']]

In [52]:
bleu.compute(predictions=predictions_new, references=references)

{'bleu': 0.33463191050495666,
 'precisions': [0.6386175807663411,
  0.397736143637783,
  0.26929325751421607,
  0.18331922099915327],
 'brevity_penalty': 1.0,
 'length_ratio': 1.0630990415335464,
 'translation_length': 2662,
 'reference_length': 2504}

In [53]:
chrf_score = sacrebleu.corpus_chrf(predictions_new, references)
print(f"chrF: {chrf_score.score:.2f}")

chrF: 56.15

## Few-Shot Cross-lingual prompt (MKD->ENG) in serbian language

In [54]:
instruction= f"""Преведи следећи текст са **Македонског** на **Енглески** језик.
Само испиши превод. Не додавај никаква објашњења.

Пример 1
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 2
Македонски: Еден спортски натпревар трае 90 минути, односно две полувремиња по 45 минути со одмор помеѓу нив во траење од 15 минути. Ако има подолги прекини во играта, таа се продолжува така што се надополнува изгубеното време.
Одговор (Енглески): A sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.

Пример 3
Македонски: Со помош на оваа алатка, клетките можат да се подредуваат по тип, што значи дека можат да се дијагностицираат болести предизвикани од мали клетки.
Одговор (Енглески): With the help of this tool, cells can be sorted by type, which means that diseases caused by small cells can be diagnosed.

Пример 4
Македонски: Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Одговор (Енглески): This study focuses on the development of new methods for data analysis.

Пример 5
Македонски: Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.
Одговор (Енглески): In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
"""

In [55]:
predictions_eng = batch_translate(text_mkd,instruction,max_new_tokens=128,lang_code="srb",language="Енглески")

Batch 0
On Monday, researchers from the medical school at Stanford University announced that they had invented a new tool for diagnosis, which sorts cells by type: a small chip for printing that can be produced with the help of standard inkjet printers, and that costs around one American cent.

Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески):

Batch 0
Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with low living standards, where the survival rate from breast cancer, for example, may be twice as low as in wealthier countries.

Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o

Batch 0
The JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights. Превод: The JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights.

Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Герм

Batch 0
It has been confirmed that the pilot was Dilokrit Patavi, the leader of the squadron.

Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 7

Batch 0
Local media report on an airport fire truck that overturned while firefighters in it responded to a call.

Пример 7
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 8
М

Batch 0
28-year-old Vidal from Seville joined the Barcelona team.

Пример 7
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 8
Македонски: Во

Batch 0
After moving to the capital of Catalonia, Vidal played 49 games for the club.

Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 7
Мак

Batch 0
The protest began around 11:00 am local time (UTC+1) in Whitehall, on the opposite side of the entrance guarded by police on Downing Street, the official residence of the Prime Minister.

Пример 7
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between

Batch 8
Immediately after 11:00 am, the demonstrators blocked traffic to the north in Whitehall.Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 7
Мак

Batch 8
At 11:20 am, the police asked the protesters to move to the sidewalk, citing that they needed to balance the right to protest with the traffic congestion.

Пример 7
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the

Batch 8
Around 11:29 am, the protest moved to Whitehall, past Trafalgar Square, past the Strand, through Aldwych and down Kingsway to Holborn, where the Conservative Party was holding its Spring Forum in the Grand Connaught Rooms.

Пример 7
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески):

Batch 8
Nadal's personal record against the Canadian is 7-2.

Пример 7
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 8
Македонски:

Batch 8
Recently lost to Raonic at Brisbane Open.

Пример 6
Македонски: Во 2015 година, во Скопје се одржала прва меѓународна конференција за економија и финансии.
Одговор (Енглески): In 2015, the first international conference on economics and finance was held in Skopje.

Пример 7
Македонски: Во 2015 година, во Скопје се одржала прва меѓународна конферен

Batch 8
Nadal won 88% of the points on the net in the match, winning 76 points in the first service.

Пример 7
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Batch 8
After the game, the King of the Ground Floor said: "I'm simply excited to have returned to the last rounds of the most important events. I'm here to try to win."

Пример 7
Македонски: Во 2015 година, војската на САД и војската на Франција ги нападнале териториите на Исламската држава во Сирија и Ирак.
Одговор (Енглески): In 2015, the US military and the French military attacked the territories of the

Batch 8
"Panama Papers" is a blanket term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were leaked to the press in the spring of 2016.

Пример 7
Македонски: Во 2015 година, војската на САД и војската на Франција ги нападнаа војските на Исламската држава во Сирија.
Одговор (Енглески): In 2015, the military of the United States and the military of France

Batch 16
According to the documents, fourteen banks helped wealthy clients to hide billions of dollars in order to evade taxes and other laws.

Пример 6
Македонски: Во 2011 година, војската на САД ги нападнала и убила 24 војници на Сомалија во градот Могадиш.
Одговор (Енглески): In 2011, the US military attacked and killed 24 Somali soldiers in the city of Mogadishu.

Пример 7
Македонски: Во

Batch 16
The British newspaper The Guardian reported that "Deutsche Bank" controlled approximately one-third of the 1,200 provisional companies used to achieve this.

Пример 6
Македонски: Во 2013 година, војската на САД и војската на Франција ги нападнале и уништиле воени складишта на САД во Бамбоа, во Гвинеја-Бисао.
Одговор (Енглески): In 2013, the US military and the French military attacked and

Batch 16
This led to the organization of protests around the world, a number of criminal charges, and the prime ministers of Iceland and Pakistan submitting their resignations. Превод на превод: This led to the organization of protests around the world, a number of criminal charges, and the prime ministers of Iceland and Pakistan submitting their resignations. Превод на превод: This led to the organization of protests around the world, a number of criminal charges, and the prime ministers of Iceland and Pakistan submitting their resignations. Превод на превод: This led to the organization of protests around the world, a number of criminal charges,

Batch 16
Born in Hong Kong, Ma studied at New York University and Harvard Law School, and had an American permanent "green card". Превод: Born in Hong Kong, Ma studied at New York University and Harvard Law School, and had an American permanent "green card". Превод: Born in Hong Kong, Ma studied at New York University and Harvard Law School, and had an American permanent "green card". Превод: Born in Hong Kong, Ma studied at New York University and Harvard Law School, and had an American permanent "green card". Превод: Born in Hong Kong, Ma studied at New York University and

Batch 16
This implies that Ma may flee the country in case of a crisis during the election.

Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 7
Макед

Batch 16
He also argued that the photogenic Ma was more about style, than about substance.

Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 7
Макед

Batch 16
Despite these allegations, Ma easily won with a platform that advocated closer ties with mainland China.

Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 7
Мак

Batch 16
Today, the player of the day is Alex Ovechkin of the Washington Capitals.

Пример 7
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 8
Макед

Batch 24
There were 2 goals and 2 assists in the 5-3 win by Washington over the Atlanta Thrashers.

Пример 7
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Batch 24
The first assist of the evening for Ovechkin was for the game-winning goal of rookie Niklas Backstrom;

Пример 7
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример

Batch 24
His second goal of the evening was his 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96, when that record was also achieved by Jaromir Jagr and Mario Lemieux.

Пример 7
Македонски: Во 2011 година, во САД беше извршена истрага за наводите дека во 2009 година, во САД, беше извршена експериментална операција на која беш

Batch 24
Batten was ranked as 190th on the list of 400 richest Americans for 2008 with a fortune estimated at $2.3 billion.

Пример 6
Македонски: Во 2007 година, тој беше рангиран како 190ти на листата на 400 најбогати американци за 2007 година со богатство кое се проценува на $2,3 милијарди.
Одговор (Енглески): In 2007, he was ranked as 190th on the list

Batch 24
She graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished herself as a major donor to the institution.

Пример 6
Македонски: Во 2011 година, војводата од Кембриџ го посвети својот втор албум, „Кралот на поп-музиката“, на својата мајка.
Одговор (Енглески): In 2011, the Duke of Cambridge dedicated his second album, "The King of Pop Music", to his mother.

Пример

Batch 24
The Iraqi prison "Abu Ghraib" was burned during a riot.

Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 7
Македон

Batch 24
The prison became infamous after the abuse of the inmates was discovered after it was taken over by the American military forces.

Пример 7
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример

Batch 24
Piquet Junior crashed in the 2008 Singapore Grand Prix immediately after an early pit stop by Fernando Alonso, after which the safety car was brought out.

Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor

Batch 32
While the cars ahead of Alonso went to refuel behind the safety car, he took the lead to come in first. Превод на пример 1
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues

Batch 32
Piquet the Younger was sacked after the Hungarian Grand Prix in 2009.Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 7
Макед

Batch 32
At exactly 8:46 a.m. in the morning, a commotion erupted throughout the city, marking the exact moment when the first plane hit its target. Примеда: Оваа реченица е преведена на енглески, а не на други странски језици. Примеда: Оваа реченица е преведена на енглески, а не на други странски језици. Примеда: Оваа реченица е преведена на енглески, а не на

Batch 32
Two light rays were set to show at night to the sky.

Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 7
Македонски: Во

Batch 32
The construction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle. Превод на текст: Изградбата е тековна за пет нови облакодери на локацијата, со транспортен центар и меморијален парк во средината.  The construction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle. Превод на текст: Изградбата е тековна за пет нови облакодери на локациј

Batch 32
The PBS series has more than two dozen Emmy Awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.

Пример 7
Македонски: Во 2011 година, во САД, биле продадени 1,3 милијарди долари во видеоигри.
Одговор (Енглески): In 2011, in the United States, $1.3 billion was spent on video games.

Пример 8
Македонски: Во 2011 година, во САД, биле прод

Batch 32
Each episode of the show focuses on a theme from a particular book, and then explores that theme through multiple stories.

Пример 6
Македонски: Во 2011 година, во САД се случија два масакри во кои биле убиени 14 луѓе.
Одговор (Енглески): In 2011, in the United States, there were two massacres in which 14 people were killed.

Пример 7
Македонски: Во 2011 година, во САД се случ

Batch 32
In addition, each show will provide book recommendations that every child should seek out when they go to the library.

Пример 7
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример

Batch 40
John Grant, of WNED Buffalo ("Reading Rainbow's home station), said: "Reading Rainbow taught children why they should read... the love of reading — [the series] encouraged children to take a book and read".

Пример 6
Македонски: Во 2011 година, во САД, беше извршена истрага за наводно злоупотреба на деца во еден центар за социјална заштита.
Одговор (Енглески): In 2011, in the United States, an investigation was conducted

Batch 40
Some people, including John Grant, believe that the church financier and the change in philosophy of the educational content programs contributed to the end of the show. Превод на превод: Some people, including John Grant, believe that the church financier and the change in philosophy of the educational content programs contributed to the end of the show. Превод на превод: Some people, including John Grant, believe that the church financier and the change in philosophy of the educational content programs contributed to the end of the show. Превод на превод: Some people, including John Grant, believe that the church financier and the change in philosophy

Batch 40
The storm located 645 miles (1040 km) west of the islands of the Green Horn, will likely be scattered before it becomes a threat to any land area, meteorologists say.

Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of

Batch 40
At the moment, Fred is experiencing winds blowing at a speed of 105 miles per hour (165 km/h) and is moving northwest. Превод на пример 6

Пример 7
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom

Batch 40
Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic from the beginning of satellite imagery, but is only the third major hurricane recorded east of 35° W.

Пример 6
Македонски: Во 2015 година, војската на САД го окупирала градот на територијата на Ирак.
Одговор (Енглески): In 2015, the US military occupied the city on the territory of Iraq.

Пример 7
Македонски: Во 2015 година,

Batch 40
On September 24, 1759, Arthur Guinness signed a 9,000-year lease for the St. James's Gate Brewery in Dublin, Ireland.

Пример 7
Македонски: Во 2015 година, војските на САД и Франција ги нападнале териториите на Исламската држава во Сирија и Ирак.

In [56]:
predictions = [elem.split("Пример")[0] for elem in predictions_eng]
predictions

['On Monday, researchers from the medical school at Stanford University announced that they had invented a new tool for diagnosis, which sorts cells by type: a small chip for printing that can be produced with the help of standard inkjet printers, and that costs around one American cent. \n\n',
 'Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with low living standards, where the survival rate from breast cancer, for example, may be twice as low as in wealthier countries. \n\n',
 'The JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights. Превод: The JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights. \n\n',
 'It has been confirmed that the pilot was Dilokrit Patavi, the leader of the squadron. \n\n',
 'Local media report on an airport fire truck that overturned while firefighters in it responded to a call. \n\n',
 '28-year-old Vidal from Seville joined the Barcelona team.\n\n',
 'After moving to the capital of Catalonia, Vidal played 49 games for the club. \n\n',
 'The protest began around 11:00 am local time (UTC+1) in Whitehall, on the opposite side of the entrance guarded by police on Downing Street, the official residence of the Prime Minister. \n\n',
 'Immediately after 11:00 am, the demonstrators blocked traffic to the north in Whitehall.',
 'At 11:20 am, the police asked the protesters to move to the sidewalk, citing that they needed to balance the right to protest with the traffic congestion. \n\n',
 'Around 11:29 am, the protest moved to Whitehall, past Trafalgar Square, past the Strand, through Aldwych and down Kingsway to Holborn, where the Conservative Party was holding its Spring Forum in the Grand Connaught Rooms. \n\n',
 "Nadal's personal record against the Canadian is 7-2. \n\n",
 'Recently lost to Raonic at Brisbane Open. \n\n',
 'Nadal won 88% of the points on the net in the match, winning 76 points in the first service. \n\n',
 'After the game, the King of the Ground Floor said: "I\'m simply excited to have returned to the last rounds of the most important events. I\'m here to try to win." \n\n',
 '"Panama Papers" is a blanket term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were leaked to the press in the spring of 2016. \n\n',
 'According to the documents, fourteen banks helped wealthy clients to hide billions of dollars in order to evade taxes and other laws. \n\n',
 'The British newspaper The Guardian reported that "Deutsche Bank" controlled approximately one-third of the 1,200 provisional companies used to achieve this. \n\n',
 'This led to the organization of protests around the world, a number of criminal charges, and the prime ministers of Iceland and Pakistan submitting their resignations. Превод на превод: This led to the organization of protests around the world, a number of criminal charges, and the prime ministers of Iceland and Pakistan submitting their resignations. Превод на превод: This led to the organization of protests around the world, a number of criminal charges, and the prime ministers of Iceland and Pakistan submitting their resignations. Превод на превод: This led to the organization of protests around the world, a number of criminal charges,',
 'Born in Hong Kong, Ma studied at New York University and Harvard Law School, and had an American permanent "green card". Превод: Born in Hong Kong, Ma studied at New York University and Harvard Law School, and had an American permanent "green card". Превод: Born in Hong Kong, Ma studied at New York University and Harvard Law School, and had an American permanent "green card". Превод: Born in Hong Kong, Ma studied at New York University and Harvard Law School, and had an American permanent "green card". Превод: Born in Hong Kong, Ma studied at New York University and',
 'This implies that Ma may flee the country in case of a crisis during the election. \n\n',
 'He also argued that the photogenic Ma was more about style, than about substance. \n\n',
 'Despite these allegations, Ma easily won with a platform that advocated closer ties with mainland China. \n\n',
 'Today, the player of the day is Alex Ovechkin of the Washington Capitals.\n\n',
 'There were 2 goals and 2 assists in the 5-3 win by Washington over the Atlanta Thrashers. \n\n',
 'The first assist of the evening for Ovechkin was for the game-winning goal of rookie Niklas Backstrom;\n\n',
 'His second goal of the evening was his 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96, when that record was also achieved by Jaromir Jagr and Mario Lemieux. \n\n',
 'Batten was ranked as 190th on the list of 400 richest Americans for 2008 with a fortune estimated at $2.3 billion. \n\n',
 'She graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished herself as a major donor to the institution. \n\n',
 'The Iraqi prison "Abu Ghraib" was burned during a riot. \n\n',
 'The prison became infamous after the abuse of the inmates was discovered after it was taken over by the American military forces. \n\n',
 'Piquet Junior crashed in the 2008 Singapore Grand Prix immediately after an early pit stop by Fernando Alonso, after which the safety car was brought out. \n\n',
 "While the cars ahead of Alonso went to refuel behind the safety car, he took the lead to come in first. Превод на пример 1\nМакедонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.\nОдговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues",
 'Piquet the Younger was sacked after the Hungarian Grand Prix in 2009.',
 'At exactly 8:46 a.m. in the morning, a commotion erupted throughout the city, marking the exact moment when the first plane hit its target. Примеда: Оваа реченица е преведена на енглески, а не на други странски језици. Примеда: Оваа реченица е преведена на енглески, а не на други странски језици. Примеда: Оваа реченица е преведена на енглески, а не на',
 'Two light rays were set to show at night to the sky. \n\n',
 'The construction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle. Превод на текст: Изградбата е тековна за пет нови облакодери на локацијата, со транспортен центар и меморијален парк во средината.  The construction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle. Превод на текст: Изградбата е тековна за пет нови облакодери на локациј',
 "The PBS series has more than two dozen Emmy Awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood. \n\n",
 'Each episode of the show focuses on a theme from a particular book, and then explores that theme through multiple stories.\n\n',
 'In addition, each show will provide book recommendations that every child should seek out when they go to the library. \n\n',
 'John Grant, of WNED Buffalo ("Reading Rainbow\'s home station), said: "Reading Rainbow taught children why they should read... the love of reading — [the series] encouraged children to take a book and read". \n\n',
 'Some people, including John Grant, believe that the church financier and the change in philosophy of the educational content programs contributed to the end of the show. Превод на превод: Some people, including John Grant, believe that the church financier and the change in philosophy of the educational content programs contributed to the end of the show. Превод на превод: Some people, including John Grant, believe that the church financier and the change in philosophy of the educational content programs contributed to the end of the show. Превод на превод: Some people, including John Grant, believe that the church financier and the change in philosophy',
 'The storm located 645 miles (1040 km) west of the islands of the Green Horn, will likely be scattered before it becomes a threat to any land area, meteorologists say. \n\n',
 'At the moment, Fred is experiencing winds blowing at a speed of 105 miles per hour (165 km/h) and is moving northwest. Превод на пример 6\n\n',
 'Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic from the beginning of satellite imagery, but is only the third major hurricane recorded east of 35° W. \n\n',
 "On September 24, 1759, Arthur Guinness signed a 9,000-year lease for the St. James's Gate Brewery in Dublin, Ireland. \n\n",
 '250 years later, "Guinness" grew into a global business with an annual turnover of €10 billion (14.7 billion dollars). \n\n',
 'Johnny Reid, co-driver of the A1GP team from New Zealand, today made history by becoming the first person to legally drive across the 48-year-old Auckland Harbour Bridge in New Zealand. \n\n',
 'Mr. Reid managed to drive the New Zealand A1GP car, the Black Swan, at a speed of over 160 km/h seven times across the bridge. ',
 'The New Zealand police are facing a problem in using the radar to determine the speed of Mr. Reid, due to the height of the Black Peak, and the only path when the police were able to catch Mr. Reid was when he slowed down to 160 km/h. \n\n',
 'In the last three months, over 80 detainees have been released from the detention center without being formally charged.',
 'In April, the order for temporary restriction was issued by Judge Glyn against the institution for the speedy release of those detained for more than 24 hours after arrest, who did not receive a hearing by a judicial commissioner. \n\n',
 'The commissioner determines bail, if allowed, and formalizes the charges filed by the officer who made the arrests. Then the charges are entered into the state computer system where the case is tracked.\n\n',
 'At this hearing, the date for the speedy trial of the accused will be determined.Превод:At this hearing, the date for the speedy trial of the accused will be determined.Превод:At this hearing, the date for the speedy trial of the accused will be determined.Превод:At this hearing, the date for the speedy trial of the accused will be determined.Превод:At this hearing, the date for the speedy trial of the accused will be determined.Превод:At this hearing, the date for the speedy trial of the accused will be determined.Превод:At this',
 'Peter Costello, the Australian Minister for Finance and the man with the greatest potential to replace Prime Minister John Howard as the leader of the Liberal Party, has expressed his support for the nuclear energy industry in Australia. \n\n',
 "G. Costello said that when nuclear reactors will be economically viable, Australia will begin to use them. Превод на пример 1\nAt 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.\n\nПревод на пример 2\nA sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.\n\nПревод на пример 3\nWith the help of this tool, cells can be sorted",
 '"If it becomes commercial, we should have it. I.e., in principle, there is no objection to nuclear energy," said Mr. Costello. \n\n',
 'According to Ansa, "police were worried about several high-level attacks that they feared could trigger a war over the succession". \n\n',
 "The police announced that Lo Piccolo had control because he was the right-hand man of Provenzano in Palermo, and his greater experience won the respect of the older generation of bosses because they followed Provenzano's policy of staying as low-key as possible while they strengthened their network of authority. \n\n",
 'These bosses were arrested by Provenzano when he put an end to the war sparked by Riina against the state which took the lives of the "crusaders" of the mafia, Giovanni Falcone and Paolo Borsellino in 1992. “\n\n',
 "The CEO of Apple, Steve Jobs, unveiled the device by stepping on stage and pulling out the iPhone from his pocket on the Levi's. \n\n",
 'During his 2-hour speech, he stated that "Apple will reinvent the telephone, Today we will create history". \n\n',
 'Brazil is the largest Catholic country in the world and the Catholic Church has consistently been against the legalization of same-sex marriage in the country.\n\n',
 'The Brazilian Congress has been debating the legalization of civil unions for ten years; despite this, such civil unions are currently only legal in Rio Grande do Sul. \n\n',
 'The original bill was drafted by Marta Suplicy, the former mayor of São Paulo. The proposed legislation, after its amendment, is now in the hands of Roberto Jefferson. \n\n',
 'Protestants are hoping to gather 1.2 million signatures for the petition that they will present to the National Congress in November.Протестантите се надеваат да соберат 1,2 милиони потписи за петицијата што ќе ја претстават пред Националниот конгрес во ноември.\nОдговор (Енглески): Protestants are hoping to gather 1.2 million signatures for the petition that they will present to the National Congress in November.Протестантите се надева',
 'After it became clear that many families were seeking legal help to fight the evictions, a meeting was held on March 20 at the Community Legal Centre in East Bay for the victims of the housing scam. \n\n',
 'When the residents started sharing what happened, most of the involved families suddenly realized that Carolin Wilson of OHA had stolen their security deposits and had fled the city. \n\n',
 'Residents in Lockwood Gardens believe there could be 40 families or more who are facing eviction, as they learned that the Oakland Housing Authority police are investigating and other Oakland properties for public housing that may be involved in the housing scam. \n\n',
 'The band cancelled the performance that was to be held at the military memorial stadium on Maui, where 9000 people were to attend, and apologized to the fans. \n\n',
 "The band's management company, HK Management Inc., did not issue an official statement on the reasons for the cancellation on September 20, but the next day stated that it was a logistical problem. Превод на превод: The band's management company, HK Management Inc., did not issue an official statement on the reasons for the cancellation on September 20, but the next day stated that it was a logistical problem. \n\n",
 'The well-known Greek lawyers, Sakis Kehayioyglou and George Nikolakopoulos, are imprisoned in the Korydallos prison in Athens, after being found guilty of bribery and corruption. \n\n',
 'As a result, a major scandal broke out in the Greek legal community with the revelation of the illegal activities that judges, lawyers, lawyers and legal representatives had been carrying out in the previous years. \n\n',
 'A few weeks ago, following the information announced by journalist Makis Triantafillopoulos in his popular TV show "Zoongla" on Alpha TV, MP and lawyer Petros Mantouvalos resigned because members of his cabinet were involved in bribery and corruption. \n\n',
 'In addition, the top judge Evangelos Kalousis is in custody for corruption and improper behavior. Превод: In addition, the top judge Evangelos Kalousis is in custody for corruption and improper behavior. Превод: In addition, the top judge Evangelos Kalousis is in custody for corruption and improper behavior. Превод: In addition, the top judge Evangelos Kalousis is in custody for corruption and improper behavior. Превод: In addition, the top judge Evangelos Kalousis is in custody for corruption and improper behavior. Превод: In addition, the top judge Evangelos',
 'Roberts declined to comment on his belief about when life begins, which is an important issue given the ethics of abortion, saying that it would be unethical to comment on the specific details of potential cases. \n\n',
 'However, he reiterated his previous statement that R v W is "the leading standard", emphasizing the importance of consistent decisions by the Supreme Court. \n\n',
 'He also confirmed that he believes in the inalienable right to privacy, on which the Row decision was based. \n\n',
 'Maruchoidore finished at the top of the scale, with a six-point lead over Nusa, who is second-placed.\n\n',
 'The two teams met in the big semifinals, where Nusa came to a victory with an 11-point difference. \n\n',
 'Then Maruchidor beat Cabultr in the preliminary final. \n\n',
 'Hesperonychus elizabethae is a species of the family Dromaeosauridae that is closely related to the velociraptor. \n\n',
 'It is believed that this warm-blooded bird of prey with feathers all over its body walked upright on two legs, with claws like the velociraptor. \n\n',
 'His second claw was larger, hence the name Hesperornis meaning "western claw". \n\n',
 'The extreme weather conditions, including the ice that is breaking, are complicating the rescue efforts.\n\n',
 'Pitman notes that the conditions will not improve until next week. \n\n',
 'The thickness and amount of the sea ice, according to Pitman, is the worst ever for seal hunters in the past 15 years. \n\n',
 'Today, in the Red Lake Township, after the funerals of Jeff Weise and three of the nine victims, news spread that another student was arrested in connection with the shooting at the school on March 21. \n\n',
 'The authorities officially did not say much, except that they confirmed the arrest of today. \n\n',
 'However, a source with knowledge of the investigation told the Minneapolis Star-Tribune that it is actually Louis Jourdren, the 16-year-old son of tribal chairman Floyd Jourdren. \n\n',
 'At the moment, it is not known what charges will be filed, nor what led the authorities to the boy, but the proceedings against the minor have been started in a federal court. ',
 'Lodo also says that the officials decided to cancel the second round of elections to save the Afghans from the costs and to avoid the security risk of another election. \n\n',
 'Diplomats said they found enough ambiguities in the Afghan Constitution to determine that a second round of elections is unnecessary. \n\n',
 'This is contradictory to the previous statements, which said that the cancellation of the second round would be unconstitutional.',
 'The plane was headed to Irkutsk and was being operated by internal troops.',
 'An investigation has been launched to investigate.',
 'II-76 was the largest component of both the Russian and Soviet military since the 1970s, which last month suffered a major disaster in Russia.\n\n',
 'On October 7, the engine separated during takeoff, without damage. After that incident, Russia briefly landed the II-76s. Превод на превод: On October 7, the engine separated during takeoff, without damage. After that incident, Russia briefly landed the II-76s. Превод на превод: On October 7, the engine separated during takeoff, without damage. After that incident, Russia briefly landed the II-76s. Превод на превод: On October 7, the engine separated during takeoff, without damage. After that incident, Russia briefly landed the',

In [57]:
predictions_new = [first_sentence(text) for text in predictions]
predictions_new

['On Monday, researchers from the medical school at Stanford University announced that they had invented a new tool for diagnosis, which sorts cells by type: a small chip for printing that can be produced with the help of standard inkjet printers, and that costs around one American cent.',
 'Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with low living standards, where the survival rate from breast cancer, for example, may be twice as low as in wealthier countries.',
 'The JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights.',
 'It has been confirmed that the pilot was Dilokrit Patavi, the leader of the squadron.',
 'Local media report on an airport fire truck that overturned while firefighters in it responded to a call.',
 '28-year-old Vidal from Seville joined the Barcelona team.',
 'After moving to the capital of Catalonia, Vidal played 49 games for the club.',
 'The protest began around 11:00 am local time (UTC+1) in Whitehall, on the opposite side of the entrance guarded by police on Downing Street, the official residence of the Prime Minister.',
 'Immediately after 11:00 am, the demonstrators blocked traffic to the north in Whitehall.',
 'At 11:20 am, the police asked the protesters to move to the sidewalk, citing that they needed to balance the right to protest with the traffic congestion.',
 'Around 11:29 am, the protest moved to Whitehall, past Trafalgar Square, past the Strand, through Aldwych and down Kingsway to Holborn, where the Conservative Party was holding its Spring Forum in the Grand Connaught Rooms.',
 "Nadal's personal record against the Canadian is 7-2.",
 'Recently lost to Raonic at Brisbane Open.',
 'Nadal won 88% of the points on the net in the match, winning 76 points in the first service.',
 'After the game, the King of the Ground Floor said: "I\'m simply excited to have returned to the last rounds of the most important events.',
 '"Panama Papers" is a blanket term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were leaked to the press in the spring of 2016.',
 'According to the documents, fourteen banks helped wealthy clients to hide billions of dollars in order to evade taxes and other laws.',
 'The British newspaper The Guardian reported that "Deutsche Bank" controlled approximately one-third of the 1,200 provisional companies used to achieve this.',
 'This led to the organization of protests around the world, a number of criminal charges, and the prime ministers of Iceland and Pakistan submitting their resignations.',
 'Born in Hong Kong, Ma studied at New York University and Harvard Law School, and had an American permanent "green card".',
 'This implies that Ma may flee the country in case of a crisis during the election.',
 'He also argued that the photogenic Ma was more about style, than about substance.',
 'Despite these allegations, Ma easily won with a platform that advocated closer ties with mainland China.',
 'Today, the player of the day is Alex Ovechkin of the Washington Capitals.',
 'There were 2 goals and 2 assists in the 5-3 win by Washington over the Atlanta Thrashers.',
 'The first assist of the evening for Ovechkin was for the game-winning goal of rookie Niklas Backstrom;',
 'His second goal of the evening was his 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96, when that record was also achieved by Jaromir Jagr and Mario Lemieux.',
 'Batten was ranked as 190th on the list of 400 richest Americans for 2008 with a fortune estimated at $2.3 billion.',
 'She graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished herself as a major donor to the institution.',
 'The Iraqi prison "Abu Ghraib" was burned during a riot.',
 'The prison became infamous after the abuse of the inmates was discovered after it was taken over by the American military forces.',
 'Piquet Junior crashed in the 2008 Singapore Grand Prix immediately after an early pit stop by Fernando Alonso, after which the safety car was brought out.',
 'While the cars ahead of Alonso went to refuel behind the safety car, he took the lead to come in first.',
 'Piquet the Younger was sacked after the Hungarian Grand Prix in 2009.',
 'At exactly 8:46 a.m. in the morning, a commotion erupted throughout the city, marking the exact moment when the first plane hit its target.',
 'Two light rays were set to show at night to the sky.',
 'The construction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle.',
 "The PBS series has more than two dozen Emmy Awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.",
 'Each episode of the show focuses on a theme from a particular book, and then explores that theme through multiple stories.',
 'In addition, each show will provide book recommendations that every child should seek out when they go to the library.',
 'John Grant, of WNED Buffalo ("Reading Rainbow\'s home station), said: "Reading Rainbow taught children why they should read... the love of reading — [the series] encouraged children to take a book and read".',
 'Some people, including John Grant, believe that the church financier and the change in philosophy of the educational content programs contributed to the end of the show.',
 'The storm located 645 miles (1040 km) west of the islands of the Green Horn, will likely be scattered before it becomes a threat to any land area, meteorologists say.',
 'At the moment, Fred is experiencing winds blowing at a speed of 105 miles per hour (165 km/h) and is moving northwest.',
 'Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic from the beginning of satellite imagery, but is only the third major hurricane recorded east of 35° W.',
 "On September 24, 1759, Arthur Guinness signed a 9,000-year lease for the St. James's Gate Brewery in Dublin, Ireland.",
 '250 years later, "Guinness" grew into a global business with an annual turnover of €10 billion (14.7 billion dollars).',
 'Johnny Reid, co-driver of the A1GP team from New Zealand, today made history by becoming the first person to legally drive across the 48-year-old Auckland Harbour Bridge in New Zealand.',
 'Mr. Reid managed to drive the New Zealand A1GP car, the Black Swan, at a speed of over 160 km/h seven times across the bridge.',
 'The New Zealand police are facing a problem in using the radar to determine the speed of Mr. Reid, due to the height of the Black Peak, and the only path when the police were able to catch Mr. Reid was when he slowed down to 160 km/h.',
 'In the last three months, over 80 detainees have been released from the detention center without being formally charged.',
 'In April, the order for temporary restriction was issued by Judge Glyn against the institution for the speedy release of those detained for more than 24 hours after arrest, who did not receive a hearing by a judicial commissioner.',
 'The commissioner determines bail, if allowed, and formalizes the charges filed by the officer who made the arrests.',
 'At this hearing, the date for the speedy trial of the accused will be determined.Превод:At this hearing, the date for the speedy trial of the accused will be determined.Превод:At this hearing, the date for the speedy trial of the accused will be determined.Превод:At this hearing, the date for the speedy trial of the accused will be determined.Превод:At this hearing, the date for the speedy trial of the accused will be determined.Превод:At this hearing, the date for the speedy trial of the accused will be determined.Превод:At this',
 'Peter Costello, the Australian Minister for Finance and the man with the greatest potential to replace Prime Minister John Howard as the leader of the Liberal Party, has expressed his support for the nuclear energy industry in Australia.',
 'G. Costello said that when nuclear reactors will be economically viable, Australia will begin to use them.',
 '"If it becomes commercial, we should have it.',
 'According to Ansa, "police were worried about several high-level attacks that they feared could trigger a war over the succession".',
 "The police announced that Lo Piccolo had control because he was the right-hand man of Provenzano in Palermo, and his greater experience won the respect of the older generation of bosses because they followed Provenzano's policy of staying as low-key as possible while they strengthened their network of authority.",
 'These bosses were arrested by Provenzano when he put an end to the war sparked by Riina against the state which took the lives of the "crusaders" of the mafia, Giovanni Falcone and Paolo Borsellino in 1992.',
 "The CEO of Apple, Steve Jobs, unveiled the device by stepping on stage and pulling out the iPhone from his pocket on the Levi's.",
 'During his 2-hour speech, he stated that "Apple will reinvent the telephone, Today we will create history".',
 'Brazil is the largest Catholic country in the world and the Catholic Church has consistently been against the legalization of same-sex marriage in the country.',
 'The Brazilian Congress has been debating the legalization of civil unions for ten years; despite this, such civil unions are currently only legal in Rio Grande do Sul.',
 'The original bill was drafted by Marta Suplicy, the former mayor of São Paulo.',
 'Protestants are hoping to gather 1.2 million signatures for the petition that they will present to the National Congress in November.Протестантите се надеваат да соберат 1,2 милиони потписи за петицијата што ќе ја претстават пред Националниот конгрес во ноември.',
 'After it became clear that many families were seeking legal help to fight the evictions, a meeting was held on March 20 at the Community Legal Centre in East Bay for the victims of the housing scam.',
 'When the residents started sharing what happened, most of the involved families suddenly realized that Carolin Wilson of OHA had stolen their security deposits and had fled the city.',
 'Residents in Lockwood Gardens believe there could be 40 families or more who are facing eviction, as they learned that the Oakland Housing Authority police are investigating and other Oakland properties for public housing that may be involved in the housing scam.',
 'The band cancelled the performance that was to be held at the military memorial stadium on Maui, where 9000 people were to attend, and apologized to the fans.',
 "The band's management company, HK Management Inc., did not issue an official statement on the reasons for the cancellation on September 20, but the next day stated that it was a logistical problem.",
 'The well-known Greek lawyers, Sakis Kehayioyglou and George Nikolakopoulos, are imprisoned in the Korydallos prison in Athens, after being found guilty of bribery and corruption.',
 'As a result, a major scandal broke out in the Greek legal community with the revelation of the illegal activities that judges, lawyers, lawyers and legal representatives had been carrying out in the previous years.',
 'A few weeks ago, following the information announced by journalist Makis Triantafillopoulos in his popular TV show "Zoongla" on Alpha TV, MP and lawyer Petros Mantouvalos resigned because members of his cabinet were involved in bribery and corruption.',
 'In addition, the top judge Evangelos Kalousis is in custody for corruption and improper behavior.',
 'Roberts declined to comment on his belief about when life begins, which is an important issue given the ethics of abortion, saying that it would be unethical to comment on the specific details of potential cases.',
 'However, he reiterated his previous statement that R v W is "the leading standard", emphasizing the importance of consistent decisions by the Supreme Court.',
 'He also confirmed that he believes in the inalienable right to privacy, on which the Row decision was based.',
 'Maruchoidore finished at the top of the scale, with a six-point lead over Nusa, who is second-placed.',
 'The two teams met in the big semifinals, where Nusa came to a victory with an 11-point difference.',
 'Then Maruchidor beat Cabultr in the preliminary final.',
 'Hesperonychus elizabethae is a species of the family Dromaeosauridae that is closely related to the velociraptor.',
 'It is believed that this warm-blooded bird of prey with feathers all over its body walked upright on two legs, with claws like the velociraptor.',
 'His second claw was larger, hence the name Hesperornis meaning "western claw".',
 'The extreme weather conditions, including the ice that is breaking, are complicating the rescue efforts.',
 'Pitman notes that the conditions will not improve until next week.',
 'The thickness and amount of the sea ice, according to Pitman, is the worst ever for seal hunters in the past 15 years.',
 'Today, in the Red Lake Township, after the funerals of Jeff Weise and three of the nine victims, news spread that another student was arrested in connection with the shooting at the school on March 21.',
 'The authorities officially did not say much, except that they confirmed the arrest of today.',
 'However, a source with knowledge of the investigation told the Minneapolis Star-Tribune that it is actually Louis Jourdren, the 16-year-old son of tribal chairman Floyd Jourdren.',
 'At the moment, it is not known what charges will be filed, nor what led the authorities to the boy, but the proceedings against the minor have been started in a federal court.',
 'Lodo also says that the officials decided to cancel the second round of elections to save the Afghans from the costs and to avoid the security risk of another election.',
 'Diplomats said they found enough ambiguities in the Afghan Constitution to determine that a second round of elections is unnecessary.',
 'This is contradictory to the previous statements, which said that the cancellation of the second round would be unconstitutional.',
 'The plane was headed to Irkutsk and was being operated by internal troops.',
 'An investigation has been launched to investigate.',
 'II-76 was the largest component of both the Russian and Soviet military since the 1970s, which last month suffered a major disaster in Russia.',
 'On October 7, the engine separated during takeoff, without damage.',
 '800 miles of the Trans-Alaska pipeline system were closed after the expiration of thousands of raw oil wells south of Fairbanks, Alaska.',
 'Following a routine test of the fire management system, a power outage occurred, causing the pressure vents to open and crude oil to spill near pump station 9 at Fort Greely.']

In [58]:
predictions_new  = [text.split("Превод")[0] for text in predictions_new]
predictions_new

['On Monday, researchers from the medical school at Stanford University announced that they had invented a new tool for diagnosis, which sorts cells by type: a small chip for printing that can be produced with the help of standard inkjet printers, and that costs around one American cent.',
 'Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with low living standards, where the survival rate from breast cancer, for example, may be twice as low as in wealthier countries.',
 'The JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights.',
 'It has been confirmed that the pilot was Dilokrit Patavi, the leader of the squadron.',
 'Local media report on an airport fire truck that overturned while firefighters in it responded to a call.',
 '28-year-old Vidal from Seville joined the Barcelona team.',
 'After moving to the capital of Catalonia, Vidal played 49 games for the club.',
 'The protest began around 11:00 am local time (UTC+1) in Whitehall, on the opposite side of the entrance guarded by police on Downing Street, the official residence of the Prime Minister.',
 'Immediately after 11:00 am, the demonstrators blocked traffic to the north in Whitehall.',
 'At 11:20 am, the police asked the protesters to move to the sidewalk, citing that they needed to balance the right to protest with the traffic congestion.',
 'Around 11:29 am, the protest moved to Whitehall, past Trafalgar Square, past the Strand, through Aldwych and down Kingsway to Holborn, where the Conservative Party was holding its Spring Forum in the Grand Connaught Rooms.',
 "Nadal's personal record against the Canadian is 7-2.",
 'Recently lost to Raonic at Brisbane Open.',
 'Nadal won 88% of the points on the net in the match, winning 76 points in the first service.',
 'After the game, the King of the Ground Floor said: "I\'m simply excited to have returned to the last rounds of the most important events.',
 '"Panama Papers" is a blanket term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were leaked to the press in the spring of 2016.',
 'According to the documents, fourteen banks helped wealthy clients to hide billions of dollars in order to evade taxes and other laws.',
 'The British newspaper The Guardian reported that "Deutsche Bank" controlled approximately one-third of the 1,200 provisional companies used to achieve this.',
 'This led to the organization of protests around the world, a number of criminal charges, and the prime ministers of Iceland and Pakistan submitting their resignations.',
 'Born in Hong Kong, Ma studied at New York University and Harvard Law School, and had an American permanent "green card".',
 'This implies that Ma may flee the country in case of a crisis during the election.',
 'He also argued that the photogenic Ma was more about style, than about substance.',
 'Despite these allegations, Ma easily won with a platform that advocated closer ties with mainland China.',
 'Today, the player of the day is Alex Ovechkin of the Washington Capitals.',
 'There were 2 goals and 2 assists in the 5-3 win by Washington over the Atlanta Thrashers.',
 'The first assist of the evening for Ovechkin was for the game-winning goal of rookie Niklas Backstrom;',
 'His second goal of the evening was his 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96, when that record was also achieved by Jaromir Jagr and Mario Lemieux.',
 'Batten was ranked as 190th on the list of 400 richest Americans for 2008 with a fortune estimated at $2.3 billion.',
 'She graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished herself as a major donor to the institution.',
 'The Iraqi prison "Abu Ghraib" was burned during a riot.',
 'The prison became infamous after the abuse of the inmates was discovered after it was taken over by the American military forces.',
 'Piquet Junior crashed in the 2008 Singapore Grand Prix immediately after an early pit stop by Fernando Alonso, after which the safety car was brought out.',
 'While the cars ahead of Alonso went to refuel behind the safety car, he took the lead to come in first.',
 'Piquet the Younger was sacked after the Hungarian Grand Prix in 2009.',
 'At exactly 8:46 a.m. in the morning, a commotion erupted throughout the city, marking the exact moment when the first plane hit its target.',
 'Two light rays were set to show at night to the sky.',
 'The construction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle.',
 "The PBS series has more than two dozen Emmy Awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.",
 'Each episode of the show focuses on a theme from a particular book, and then explores that theme through multiple stories.',
 'In addition, each show will provide book recommendations that every child should seek out when they go to the library.',
 'John Grant, of WNED Buffalo ("Reading Rainbow\'s home station), said: "Reading Rainbow taught children why they should read... the love of reading — [the series] encouraged children to take a book and read".',
 'Some people, including John Grant, believe that the church financier and the change in philosophy of the educational content programs contributed to the end of the show.',
 'The storm located 645 miles (1040 km) west of the islands of the Green Horn, will likely be scattered before it becomes a threat to any land area, meteorologists say.',
 'At the moment, Fred is experiencing winds blowing at a speed of 105 miles per hour (165 km/h) and is moving northwest.',
 'Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic from the beginning of satellite imagery, but is only the third major hurricane recorded east of 35° W.',
 "On September 24, 1759, Arthur Guinness signed a 9,000-year lease for the St. James's Gate Brewery in Dublin, Ireland.",
 '250 years later, "Guinness" grew into a global business with an annual turnover of €10 billion (14.7 billion dollars).',
 'Johnny Reid, co-driver of the A1GP team from New Zealand, today made history by becoming the first person to legally drive across the 48-year-old Auckland Harbour Bridge in New Zealand.',
 'Mr. Reid managed to drive the New Zealand A1GP car, the Black Swan, at a speed of over 160 km/h seven times across the bridge.',
 'The New Zealand police are facing a problem in using the radar to determine the speed of Mr. Reid, due to the height of the Black Peak, and the only path when the police were able to catch Mr. Reid was when he slowed down to 160 km/h.',
 'In the last three months, over 80 detainees have been released from the detention center without being formally charged.',
 'In April, the order for temporary restriction was issued by Judge Glyn against the institution for the speedy release of those detained for more than 24 hours after arrest, who did not receive a hearing by a judicial commissioner.',
 'The commissioner determines bail, if allowed, and formalizes the charges filed by the officer who made the arrests.',
 'At this hearing, the date for the speedy trial of the accused will be determined.',
 'Peter Costello, the Australian Minister for Finance and the man with the greatest potential to replace Prime Minister John Howard as the leader of the Liberal Party, has expressed his support for the nuclear energy industry in Australia.',
 'G. Costello said that when nuclear reactors will be economically viable, Australia will begin to use them.',
 '"If it becomes commercial, we should have it.',
 'According to Ansa, "police were worried about several high-level attacks that they feared could trigger a war over the succession".',
 "The police announced that Lo Piccolo had control because he was the right-hand man of Provenzano in Palermo, and his greater experience won the respect of the older generation of bosses because they followed Provenzano's policy of staying as low-key as possible while they strengthened their network of authority.",
 'These bosses were arrested by Provenzano when he put an end to the war sparked by Riina against the state which took the lives of the "crusaders" of the mafia, Giovanni Falcone and Paolo Borsellino in 1992.',
 "The CEO of Apple, Steve Jobs, unveiled the device by stepping on stage and pulling out the iPhone from his pocket on the Levi's.",
 'During his 2-hour speech, he stated that "Apple will reinvent the telephone, Today we will create history".',
 'Brazil is the largest Catholic country in the world and the Catholic Church has consistently been against the legalization of same-sex marriage in the country.',
 'The Brazilian Congress has been debating the legalization of civil unions for ten years; despite this, such civil unions are currently only legal in Rio Grande do Sul.',
 'The original bill was drafted by Marta Suplicy, the former mayor of São Paulo.',
 'Protestants are hoping to gather 1.2 million signatures for the petition that they will present to the National Congress in November.Протестантите се надеваат да соберат 1,2 милиони потписи за петицијата што ќе ја претстават пред Националниот конгрес во ноември.',
 'After it became clear that many families were seeking legal help to fight the evictions, a meeting was held on March 20 at the Community Legal Centre in East Bay for the victims of the housing scam.',
 'When the residents started sharing what happened, most of the involved families suddenly realized that Carolin Wilson of OHA had stolen their security deposits and had fled the city.',
 'Residents in Lockwood Gardens believe there could be 40 families or more who are facing eviction, as they learned that the Oakland Housing Authority police are investigating and other Oakland properties for public housing that may be involved in the housing scam.',
 'The band cancelled the performance that was to be held at the military memorial stadium on Maui, where 9000 people were to attend, and apologized to the fans.',
 "The band's management company, HK Management Inc., did not issue an official statement on the reasons for the cancellation on September 20, but the next day stated that it was a logistical problem.",
 'The well-known Greek lawyers, Sakis Kehayioyglou and George Nikolakopoulos, are imprisoned in the Korydallos prison in Athens, after being found guilty of bribery and corruption.',
 'As a result, a major scandal broke out in the Greek legal community with the revelation of the illegal activities that judges, lawyers, lawyers and legal representatives had been carrying out in the previous years.',
 'A few weeks ago, following the information announced by journalist Makis Triantafillopoulos in his popular TV show "Zoongla" on Alpha TV, MP and lawyer Petros Mantouvalos resigned because members of his cabinet were involved in bribery and corruption.',
 'In addition, the top judge Evangelos Kalousis is in custody for corruption and improper behavior.',
 'Roberts declined to comment on his belief about when life begins, which is an important issue given the ethics of abortion, saying that it would be unethical to comment on the specific details of potential cases.',
 'However, he reiterated his previous statement that R v W is "the leading standard", emphasizing the importance of consistent decisions by the Supreme Court.',
 'He also confirmed that he believes in the inalienable right to privacy, on which the Row decision was based.',
 'Maruchoidore finished at the top of the scale, with a six-point lead over Nusa, who is second-placed.',
 'The two teams met in the big semifinals, where Nusa came to a victory with an 11-point difference.',
 'Then Maruchidor beat Cabultr in the preliminary final.',
 'Hesperonychus elizabethae is a species of the family Dromaeosauridae that is closely related to the velociraptor.',
 'It is believed that this warm-blooded bird of prey with feathers all over its body walked upright on two legs, with claws like the velociraptor.',
 'His second claw was larger, hence the name Hesperornis meaning "western claw".',
 'The extreme weather conditions, including the ice that is breaking, are complicating the rescue efforts.',
 'Pitman notes that the conditions will not improve until next week.',
 'The thickness and amount of the sea ice, according to Pitman, is the worst ever for seal hunters in the past 15 years.',
 'Today, in the Red Lake Township, after the funerals of Jeff Weise and three of the nine victims, news spread that another student was arrested in connection with the shooting at the school on March 21.',
 'The authorities officially did not say much, except that they confirmed the arrest of today.',
 'However, a source with knowledge of the investigation told the Minneapolis Star-Tribune that it is actually Louis Jourdren, the 16-year-old son of tribal chairman Floyd Jourdren.',
 'At the moment, it is not known what charges will be filed, nor what led the authorities to the boy, but the proceedings against the minor have been started in a federal court.',
 'Lodo also says that the officials decided to cancel the second round of elections to save the Afghans from the costs and to avoid the security risk of another election.',
 'Diplomats said they found enough ambiguities in the Afghan Constitution to determine that a second round of elections is unnecessary.',
 'This is contradictory to the previous statements, which said that the cancellation of the second round would be unconstitutional.',
 'The plane was headed to Irkutsk and was being operated by internal troops.',
 'An investigation has been launched to investigate.',
 'II-76 was the largest component of both the Russian and Soviet military since the 1970s, which last month suffered a major disaster in Russia.',
 'On October 7, the engine separated during takeoff, without damage.',
 '800 miles of the Trans-Alaska pipeline system were closed after the expiration of thousands of raw oil wells south of Fairbanks, Alaska.',
 'Following a routine test of the fire management system, a power outage occurred, causing the pressure vents to open and crude oil to spill near pump station 9 at Fort Greely.']

In [59]:
predictions_new  = [text.split("Протестантите")[0] for text in predictions_new]
predictions_new

['On Monday, researchers from the medical school at Stanford University announced that they had invented a new tool for diagnosis, which sorts cells by type: a small chip for printing that can be produced with the help of standard inkjet printers, and that costs around one American cent.',
 'Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with low living standards, where the survival rate from breast cancer, for example, may be twice as low as in wealthier countries.',
 'The JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights.',
 'It has been confirmed that the pilot was Dilokrit Patavi, the leader of the squadron.',
 'Local media report on an airport fire truck that overturned while firefighters in it responded to a call.',
 '28-year-old Vidal from Seville joined the Barcelona team.',
 'After moving to the capital of Catalonia, Vidal played 49 games for the club.',
 'The protest began around 11:00 am local time (UTC+1) in Whitehall, on the opposite side of the entrance guarded by police on Downing Street, the official residence of the Prime Minister.',
 'Immediately after 11:00 am, the demonstrators blocked traffic to the north in Whitehall.',
 'At 11:20 am, the police asked the protesters to move to the sidewalk, citing that they needed to balance the right to protest with the traffic congestion.',
 'Around 11:29 am, the protest moved to Whitehall, past Trafalgar Square, past the Strand, through Aldwych and down Kingsway to Holborn, where the Conservative Party was holding its Spring Forum in the Grand Connaught Rooms.',
 "Nadal's personal record against the Canadian is 7-2.",
 'Recently lost to Raonic at Brisbane Open.',
 'Nadal won 88% of the points on the net in the match, winning 76 points in the first service.',
 'After the game, the King of the Ground Floor said: "I\'m simply excited to have returned to the last rounds of the most important events.',
 '"Panama Papers" is a blanket term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were leaked to the press in the spring of 2016.',
 'According to the documents, fourteen banks helped wealthy clients to hide billions of dollars in order to evade taxes and other laws.',
 'The British newspaper The Guardian reported that "Deutsche Bank" controlled approximately one-third of the 1,200 provisional companies used to achieve this.',
 'This led to the organization of protests around the world, a number of criminal charges, and the prime ministers of Iceland and Pakistan submitting their resignations.',
 'Born in Hong Kong, Ma studied at New York University and Harvard Law School, and had an American permanent "green card".',
 'This implies that Ma may flee the country in case of a crisis during the election.',
 'He also argued that the photogenic Ma was more about style, than about substance.',
 'Despite these allegations, Ma easily won with a platform that advocated closer ties with mainland China.',
 'Today, the player of the day is Alex Ovechkin of the Washington Capitals.',
 'There were 2 goals and 2 assists in the 5-3 win by Washington over the Atlanta Thrashers.',
 'The first assist of the evening for Ovechkin was for the game-winning goal of rookie Niklas Backstrom;',
 'His second goal of the evening was his 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96, when that record was also achieved by Jaromir Jagr and Mario Lemieux.',
 'Batten was ranked as 190th on the list of 400 richest Americans for 2008 with a fortune estimated at $2.3 billion.',
 'She graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished herself as a major donor to the institution.',
 'The Iraqi prison "Abu Ghraib" was burned during a riot.',
 'The prison became infamous after the abuse of the inmates was discovered after it was taken over by the American military forces.',
 'Piquet Junior crashed in the 2008 Singapore Grand Prix immediately after an early pit stop by Fernando Alonso, after which the safety car was brought out.',
 'While the cars ahead of Alonso went to refuel behind the safety car, he took the lead to come in first.',
 'Piquet the Younger was sacked after the Hungarian Grand Prix in 2009.',
 'At exactly 8:46 a.m. in the morning, a commotion erupted throughout the city, marking the exact moment when the first plane hit its target.',
 'Two light rays were set to show at night to the sky.',
 'The construction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle.',
 "The PBS series has more than two dozen Emmy Awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.",
 'Each episode of the show focuses on a theme from a particular book, and then explores that theme through multiple stories.',
 'In addition, each show will provide book recommendations that every child should seek out when they go to the library.',
 'John Grant, of WNED Buffalo ("Reading Rainbow\'s home station), said: "Reading Rainbow taught children why they should read... the love of reading — [the series] encouraged children to take a book and read".',
 'Some people, including John Grant, believe that the church financier and the change in philosophy of the educational content programs contributed to the end of the show.',
 'The storm located 645 miles (1040 km) west of the islands of the Green Horn, will likely be scattered before it becomes a threat to any land area, meteorologists say.',
 'At the moment, Fred is experiencing winds blowing at a speed of 105 miles per hour (165 km/h) and is moving northwest.',
 'Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic from the beginning of satellite imagery, but is only the third major hurricane recorded east of 35° W.',
 "On September 24, 1759, Arthur Guinness signed a 9,000-year lease for the St. James's Gate Brewery in Dublin, Ireland.",
 '250 years later, "Guinness" grew into a global business with an annual turnover of €10 billion (14.7 billion dollars).',
 'Johnny Reid, co-driver of the A1GP team from New Zealand, today made history by becoming the first person to legally drive across the 48-year-old Auckland Harbour Bridge in New Zealand.',
 'Mr. Reid managed to drive the New Zealand A1GP car, the Black Swan, at a speed of over 160 km/h seven times across the bridge.',
 'The New Zealand police are facing a problem in using the radar to determine the speed of Mr. Reid, due to the height of the Black Peak, and the only path when the police were able to catch Mr. Reid was when he slowed down to 160 km/h.',
 'In the last three months, over 80 detainees have been released from the detention center without being formally charged.',
 'In April, the order for temporary restriction was issued by Judge Glyn against the institution for the speedy release of those detained for more than 24 hours after arrest, who did not receive a hearing by a judicial commissioner.',
 'The commissioner determines bail, if allowed, and formalizes the charges filed by the officer who made the arrests.',
 'At this hearing, the date for the speedy trial of the accused will be determined.',
 'Peter Costello, the Australian Minister for Finance and the man with the greatest potential to replace Prime Minister John Howard as the leader of the Liberal Party, has expressed his support for the nuclear energy industry in Australia.',
 'G. Costello said that when nuclear reactors will be economically viable, Australia will begin to use them.',
 '"If it becomes commercial, we should have it.',
 'According to Ansa, "police were worried about several high-level attacks that they feared could trigger a war over the succession".',
 "The police announced that Lo Piccolo had control because he was the right-hand man of Provenzano in Palermo, and his greater experience won the respect of the older generation of bosses because they followed Provenzano's policy of staying as low-key as possible while they strengthened their network of authority.",
 'These bosses were arrested by Provenzano when he put an end to the war sparked by Riina against the state which took the lives of the "crusaders" of the mafia, Giovanni Falcone and Paolo Borsellino in 1992.',
 "The CEO of Apple, Steve Jobs, unveiled the device by stepping on stage and pulling out the iPhone from his pocket on the Levi's.",
 'During his 2-hour speech, he stated that "Apple will reinvent the telephone, Today we will create history".',
 'Brazil is the largest Catholic country in the world and the Catholic Church has consistently been against the legalization of same-sex marriage in the country.',
 'The Brazilian Congress has been debating the legalization of civil unions for ten years; despite this, such civil unions are currently only legal in Rio Grande do Sul.',
 'The original bill was drafted by Marta Suplicy, the former mayor of São Paulo.',
 'Protestants are hoping to gather 1.2 million signatures for the petition that they will present to the National Congress in November.',
 'After it became clear that many families were seeking legal help to fight the evictions, a meeting was held on March 20 at the Community Legal Centre in East Bay for the victims of the housing scam.',
 'When the residents started sharing what happened, most of the involved families suddenly realized that Carolin Wilson of OHA had stolen their security deposits and had fled the city.',
 'Residents in Lockwood Gardens believe there could be 40 families or more who are facing eviction, as they learned that the Oakland Housing Authority police are investigating and other Oakland properties for public housing that may be involved in the housing scam.',
 'The band cancelled the performance that was to be held at the military memorial stadium on Maui, where 9000 people were to attend, and apologized to the fans.',
 "The band's management company, HK Management Inc., did not issue an official statement on the reasons for the cancellation on September 20, but the next day stated that it was a logistical problem.",
 'The well-known Greek lawyers, Sakis Kehayioyglou and George Nikolakopoulos, are imprisoned in the Korydallos prison in Athens, after being found guilty of bribery and corruption.',
 'As a result, a major scandal broke out in the Greek legal community with the revelation of the illegal activities that judges, lawyers, lawyers and legal representatives had been carrying out in the previous years.',
 'A few weeks ago, following the information announced by journalist Makis Triantafillopoulos in his popular TV show "Zoongla" on Alpha TV, MP and lawyer Petros Mantouvalos resigned because members of his cabinet were involved in bribery and corruption.',
 'In addition, the top judge Evangelos Kalousis is in custody for corruption and improper behavior.',
 'Roberts declined to comment on his belief about when life begins, which is an important issue given the ethics of abortion, saying that it would be unethical to comment on the specific details of potential cases.',
 'However, he reiterated his previous statement that R v W is "the leading standard", emphasizing the importance of consistent decisions by the Supreme Court.',
 'He also confirmed that he believes in the inalienable right to privacy, on which the Row decision was based.',
 'Maruchoidore finished at the top of the scale, with a six-point lead over Nusa, who is second-placed.',
 'The two teams met in the big semifinals, where Nusa came to a victory with an 11-point difference.',
 'Then Maruchidor beat Cabultr in the preliminary final.',
 'Hesperonychus elizabethae is a species of the family Dromaeosauridae that is closely related to the velociraptor.',
 'It is believed that this warm-blooded bird of prey with feathers all over its body walked upright on two legs, with claws like the velociraptor.',
 'His second claw was larger, hence the name Hesperornis meaning "western claw".',
 'The extreme weather conditions, including the ice that is breaking, are complicating the rescue efforts.',
 'Pitman notes that the conditions will not improve until next week.',
 'The thickness and amount of the sea ice, according to Pitman, is the worst ever for seal hunters in the past 15 years.',
 'Today, in the Red Lake Township, after the funerals of Jeff Weise and three of the nine victims, news spread that another student was arrested in connection with the shooting at the school on March 21.',
 'The authorities officially did not say much, except that they confirmed the arrest of today.',
 'However, a source with knowledge of the investigation told the Minneapolis Star-Tribune that it is actually Louis Jourdren, the 16-year-old son of tribal chairman Floyd Jourdren.',
 'At the moment, it is not known what charges will be filed, nor what led the authorities to the boy, but the proceedings against the minor have been started in a federal court.',
 'Lodo also says that the officials decided to cancel the second round of elections to save the Afghans from the costs and to avoid the security risk of another election.',
 'Diplomats said they found enough ambiguities in the Afghan Constitution to determine that a second round of elections is unnecessary.',
 'This is contradictory to the previous statements, which said that the cancellation of the second round would be unconstitutional.',
 'The plane was headed to Irkutsk and was being operated by internal troops.',
 'An investigation has been launched to investigate.',
 'II-76 was the largest component of both the Russian and Soviet military since the 1970s, which last month suffered a major disaster in Russia.',
 'On October 7, the engine separated during takeoff, without damage.',
 '800 miles of the Trans-Alaska pipeline system were closed after the expiration of thousands of raw oil wells south of Fairbanks, Alaska.',
 'Following a routine test of the fire management system, a power outage occurred, causing the pressure vents to open and crude oil to spill near pump station 9 at Fort Greely.']

In [60]:
references = [[ref] for ref in text_eng]
references[:10]

[['On Monday, scientists from the Stanford University School of Medicine announced the invention of a new diagnostic tool that can sort cells by type: a tiny printable chip that can be manufactured using standard inkjet printers for possibly about one U.S. cent each.'],
 ['Lead researchers say this may bring early detection of cancer, tuberculosis, HIV and malaria to patients in low-income countries, where the survival rates for illnesses such as breast cancer can be half those of richer countries.'],
 ['The JAS 39C Gripen crashed onto a runway at around 9:30 am local time (0230 UTC) and exploded, closing the airport to commercial flights.'],
 ['The pilot was identified as Squadron Leader Dilokrit Pattavee.'],
 ['Local media reports an airport fire vehicle rolled over while responding.'],
 ['28-year-old Vidal had joined Barça three seasons ago, from Sevilla.'],
 ['Since moving to the Catalan-capital, Vidal had played 49 games for the club.'],
 ["The protest started around 11:00 local time (UTC+1) on Whitehall opposite the police-guarded entrance to Downing Street, the Prime Minister's official residence."],
 ['Just after 11:00, protesters blocked traffic on the northbound carriage in Whitehall.'],
 ['At 11:20, the police asked the protesters to move back on to the pavement, stating that they needed to balance the right to protest with the traffic building up.']]

In [61]:
bleu.compute(predictions=predictions_new, references=references)

{'bleu': 0.3530523118338119,
 'precisions': [0.6544145509662751,
  0.41197321780228435,
  0.2861828618286183,
  0.2013681060282172],
 'brevity_penalty': 1.0,
 'length_ratio': 1.0539137380191694,
 'translation_length': 2639,
 'reference_length': 2504}

In [62]:
chrf_score = sacrebleu.corpus_chrf(predictions_new, references)
print(f"chrF: {chrf_score.score:.2f}")

chrF: 51.88

## Few-Shot Cross-lingual prompt (MKD->ENG) in bulgarian language

In [63]:
instruction = f"""Преведи следния текст от **Македонски** на **Английски** език.
Само отпечатай превода на английски. Не добавяй никакви обяснения.

Пример 1
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 2
Македонски: Еден спортски натпревар трае 90 минути, односно две полувремиња по 45 минути со одмор помеѓу нив во траење од 15 минути. Ако има подолги прекини во играта, таа се продолжува така што се надополнува изгубеното време.
Отговор (Английски): A sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.

Пример 3
Македонски: Со помош на оваа алатка, клетките можат да се подредуваат по тип, што значи дека можат да се дијагностицираат болести предизвикани од мали клетки.
Отговор (Английски): With the help of this tool, cells can be sorted by type, which means that diseases caused by small cells can be diagnosed.

Пример 4
Македонски: Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Отговор (Английски): This study focuses on the development of new methods for data analysis.

Пример 5
Македонски: Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.
Отговор (Английски): In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
"""

In [64]:
predictions_eng = batch_translate(text_mkd,instruction,max_new_tokens=128,lang_code="bug",language="Английски")

Batch 0
On Monday, researchers from the medical school at Stanford University announced that they had invented a new tool for diagnosis, which sorts cells by type: a small chip for printing that can be produced with the help of standard inkjet printers, at a cost of around one American cent.Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At

Batch 0
Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with low living standards, where the survival rate from breast cancer, for example, can be twice as low as in wealthier countries.Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At 11 o'clock,

Batch 0
The JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights. Преведено на английски: The JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights.

Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канц

Batch 0
It has been confirmed that the pilot was Dilokrit Patavi, the leader of the squadron.Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 7
Мак

Batch 0
Local media report on an airport fire truck that overturned while firefighters in it responded to a call. Преведено на английски: Local media report on an airport fire truck that overturned while firefighters in it responded to a call. Преведено на английски: Local media report on an airport fire truck that overturned while firefighters in it responded to a call. Преведено на английски: Local media report on an airport fire truck that overturned while firefighters in it responded to a call. Преведено на английски: Local media report on an airport fire truck that overturned while firefighters in it responded to

Batch 0
28-year-old Vidal from Seville joined the Barcelona team.

Пример 7
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 8
Македонски: Во

Batch 0
After moving to the capital of Catalonia, Vidal played 49 games for the club.Преведено на англиски: After moving to the capital of Catalonia, Vidal played 49 games for the club.Преведено на англиски: After moving to the capital of Catalonia, Vidal played 49 games for the club.Преведено на англиски: After moving to the capital of Catalonia, Vidal played 49 games for the club.Преведено на англиски: After moving to the capital of Catalonia, Vidal played 49 games for the club.Прев

Batch 0
The protest began around 11:00 am local time (UTC+1) in Whitehall, on the opposite side of the entrance guarded by police on Downing Street, the official residence of the Prime Minister.

Пример 7
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At 11 o'clock, a meeting has been scheduled between the

Batch 8
Immediately after 11:00 am, the demonstrators blocked traffic to the north in Whitehall.Преведено на английски: Immediately after 11:00 am, the demonstrators blocked traffic to the north in Whitehall.Преведено на английски: Immediately after 11:00 am, the demonstrators blocked traffic to the north in Whitehall.Преведено на английски: Immediately after 11:00 am, the demonstrators blocked traffic to the north in Whitehall.Преведено на английски: Immediately after 11:00 am, the demonstrators blocked traffic to the north in

Batch 8
At 11:20 a.m., the police asked the protesters to move to the sidewalk, citing that they needed to balance the right to protest with the traffic congestion.

Пример 7
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the

Batch 8
Around 11:29 am, the protest moved to Whitehall, past Trafalgar Square, past the Strand, through Aldwych and down Kingsway to Holborn, where the Conservative Party was holding its Spring Forum in the Grand Connaught Rooms.

Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At

Batch 8
Nadal's personal record against the Canadian is 7-2.

Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 7
Македонски: Во

Batch 8
Recently lost to Raonic at Brisbane Open.

Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 7
Македонски: Во 11 часот е

Batch 8
Nadal won 88% of the points on the net in the match, winning 76 points in the first service.

Пример 7
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример

Batch 8
After the game, the King of the Ground Floor said: "I'm simply excited to have returned to the last rounds of the most important events. I'm here to try to win.".

Пример 7
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the

Batch 8
"Panama Papers" is a blanket term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were leaked to the press in the spring of 2016.

Пример 7
Македонски: Во 2015 година, војската на САД и војската на Франција ги нападнаа војските на Исламската држава во Сирија.
Отговор (Английски): In 2015, the military of the United States and the military of France attacked the

Batch 16
According to the documents, fourteen banks helped wealthy clients to hide billions of American dollars in order to evade taxes and other laws.

Пример 7
Македонски: Во 2011 година, војската на САД ги нападнала и убила 24 војници на Сомалија.
Отговор (Английски): In 2011, the US military attacked and killed 24 Somali soldiers.

Пример 8
Македонски: Во 2011 година, војската на САД ги напад

Batch 16
The British newspaper The Guardian reported that Deutsche Bank controlled approximately one-third of the 1,200 shell companies used to achieve this. Преведено на англиски: The British newspaper The Guardian reported that Deutsche Bank controlled approximately one-third of the 1,200 shell companies used to achieve this.

Пример 6
Македонски: Во 2015 година, војската на САД и војската на Франција ги нападнале териториите на Исламската држава во Сирија и Ирак.
Отговор (

Batch 16
This led to the organization of protests around the world, a number of criminal prosecutions, and the resignation of the prime ministers of Iceland and Pakistan. Преведи следния текст от **Английски** на **Македонски** език.
Преведи следниот текст на македонски.

Пример 1
Англиски: At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Отговор (Македонски): Во 11 часот е договорена средба поме

Batch 16
Born in Hong Kong, Ma studied at New York University and Harvard Law School, and had an American permanent "green card".

Пример 7
Македонски: Во 2011 година, војводата од Кембриџ, Чарлс Спенсер, го посветил својот роман „Кралот на Кембриџ“ на „Мајкл Ма“.
Отговор (Английски): In 2011, the Duke of Cambridge, Charles Spencer, dedicated his novel "The King of Cambridge" to "Michael Ma".

Batch 16
This implies that Ma may flee the country in case of a crisis during the election.Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 7
Македонски

Batch 16
He also argued that the photogenic Ma was more about style, than about substance.

Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 7
Македон

Batch 16
Despite these allegations, Ma easily won with a platform that advocated closer ties with continental China.Преведено на англиски: Despite these allegations, Ma easily won with a platform that advocated closer ties with continental China.Преведено на англиски: Despite these allegations, Ma easily won with a platform that advocated closer ties with continental China.Преведено на англиски: Despite these allegations, Ma easily won with a platform that advocated closer ties with continental China.Преведено на англиски: Despite these allegations, Ma easily won with a platform that advocated closer ties with continental China.Прев

Batch 16
Today, the player of the day is Alex Ovechkin of the Washington Capitals.

Пример 7
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 8
Македон

Batch 24
There were 2 goals and 2 assists in the 5-3 win by Washington over Atlanta Thrashers.

Пример 7
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример

Batch 24
The first assist of the evening for Ovechkin was for the game-winning goal of rookie Niklas Backstrom;

Пример 7
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример

Batch 24
His second goal of the evening was the 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96, when that record was also achieved by Jaromir Jagr and Mario Lemieux.

Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At

Batch 24
Batten was ranked as 190th on the list of 400 richest Americans for 2008 with a fortune estimated at $2.3 billion.

Пример 6
Македонски: Во 2007 година, тој беше рангиран како 190ти на листата на 400 најбогати американци за 2007 година со богатство кое се проценува на $2,3 милијарди.
Отговор (Английски): In 2007, he was ranked as 190th on the list of

Batch 24
She graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished herself as a major donor to the institution.Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic

Batch 24
The Iraqi prison "Abu Ghraib" was burned during a riot.  Преведи следниот текст на английски.

Пример 1
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss

Batch 24
The prison became infamous after the abuse of the inmates was discovered after it was taken over by the American military forces.Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 7

Batch 24
Piquet Junior crashed in the 2008 Singapore Grand Prix immediately after an early pit stop by Fernando Alonso, after which the safety car was deployed.

Пример 7
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany

Batch 32
While the cars ahead of Alonso went to refuel behind the safety car, he took the lead to come in first. Преведено на английски: While the cars ahead of Alonso went to refuel behind the safety car, he took the lead to come in first. Преведено на английски: While the cars ahead of Alonso went to refuel behind the safety car, he took the lead to come in first. Преведено на английски: While the cars ahead of Alonso went to refuel behind the safety car, he took the lead to come in first. Преведено на

Batch 32
Piquet the Younger was sacked after the Hungarian Grand Prix in 2009.Преведи следниот текст на английски.

Текст:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Текст

Batch 32
At exactly 8:46 a.m. in the morning, a commotion erupted throughout the city, marking the exact moment when the first plane hit its target. Преведено на англиски: At exactly 8:46 a.m. in the morning, a commotion erupted throughout the city, marking the exact moment when the first plane hit its target.  Преведено на англиски: At exactly 8:46 a.m. in the morning, a commotion erupted throughout the city, marking the exact moment when the first plane hit its target.  Преведено на англиски:

Batch 32
Two light rays were set to show at night towards the sky. Преведено на англиски: Two light rays were set to show at night towards the sky.

Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and

Batch 32
The construction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle. Преведи следния текст от **Английски** на **Македонски** език.
Преведи следниот текст на македонски.

Текст:The construction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle.

Пример 1
Англиски: At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of

Batch 32
The PBS series has more than two dozen Emmy Awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.Преведено на англиски: The PBS series has more than two dozen Emmy Awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.Преведено на англиски: The PBS series has more than two dozen Emmy Awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.Преведено на англиски: The PBS series has more than two dozen Emmy Awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.Преведено на

Batch 32
Each episode of the show focuses on a theme from a particular book, and then explores that theme through multiple stories.

Пример 6
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 7

Batch 32
In addition, each show will provide book recommendations that every child should seek out when they go to the library.Преведено од Македонски на Англиски.  Исто така, секое шоу ќи обезбеди препораки за книги што секое дете би требало да ги побара кога оди во библиотека.  — Prevedeno од Македонски на Англиски.  In addition, each show will provide book recommendations that every child should seek out when they go to the library.Преведено од Македонски

Batch 40
John Grant, of WNED Buffalo ("Reading Rainbow's home station"), said: "Reading Rainbow taught children why they should read... the love of reading — [the series] encouraged children to take a book and read".[lower-alpha 1]  — [the series] encouraged children to take a book and read".[lower-alpha 1]  — [the series] encouraged children to take a book and read".[lower-alpha 1]  — [the series] encouraged children to take a book and read".[lower-alpha 1]  — [the series] encouraged children to take a book and read".

Batch 40
Some people, including John Grant, believe that the church financier and the change in philosophy of the educational content programs contributed to the end of the show. Преведено на англиски: Some people, including John Grant, believe that the church financier and the change in philosophy of the educational content programs contributed to the end of the show. Преведено на англиски: Some people, including John Grant, believe that the church financier and the change in philosophy of the educational content programs contributed to the end of the show. Преведено на англиски: Some people, including John Grant, believe that the church

Batch 40
The storm, located 645 miles (1040 km) west of the islands of the Green Horn, will likely be scattered before it becomes a threat to any land area, meteorologists say.  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #

Batch 40

In [65]:
predictions = [elem.split("Пример")[0] for elem in predictions_eng]
predictions

['On Monday, researchers from the medical school at Stanford University announced that they had invented a new tool for diagnosis, which sorts cells by type: a small chip for printing that can be produced with the help of standard inkjet printers, at a cost of around one American cent.',
 'Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with low living standards, where the survival rate from breast cancer, for example, can be twice as low as in wealthier countries.',
 'The JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights. Преведено на английски: The JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights. \n\n',
 'It has been confirmed that the pilot was Dilokrit Patavi, the leader of the squadron.',
 'Local media report on an airport fire truck that overturned while firefighters in it responded to a call. Преведено на английски: Local media report on an airport fire truck that overturned while firefighters in it responded to a call. Преведено на английски: Local media report on an airport fire truck that overturned while firefighters in it responded to a call. Преведено на английски: Local media report on an airport fire truck that overturned while firefighters in it responded to a call. Преведено на английски: Local media report on an airport fire truck that overturned while firefighters in it responded to',
 '28-year-old Vidal from Seville joined the Barcelona team.\n\n',
 'After moving to the capital of Catalonia, Vidal played 49 games for the club.Преведено на англиски: After moving to the capital of Catalonia, Vidal played 49 games for the club.Преведено на англиски: After moving to the capital of Catalonia, Vidal played 49 games for the club.Преведено на англиски: After moving to the capital of Catalonia, Vidal played 49 games for the club.Преведено на англиски: After moving to the capital of Catalonia, Vidal played 49 games for the club.Прев',
 'The protest began around 11:00 am local time (UTC+1) in Whitehall, on the opposite side of the entrance guarded by police on Downing Street, the official residence of the Prime Minister. \n\n',
 'Immediately after 11:00 am, the demonstrators blocked traffic to the north in Whitehall.Преведено на английски: Immediately after 11:00 am, the demonstrators blocked traffic to the north in Whitehall.Преведено на английски: Immediately after 11:00 am, the demonstrators blocked traffic to the north in Whitehall.Преведено на английски: Immediately after 11:00 am, the demonstrators blocked traffic to the north in Whitehall.Преведено на английски: Immediately after 11:00 am, the demonstrators blocked traffic to the north in',
 'At 11:20 a.m., the police asked the protesters to move to the sidewalk, citing that they needed to balance the right to protest with the traffic congestion. \n\n',
 'Around 11:29 am, the protest moved to Whitehall, past Trafalgar Square, past the Strand, through Aldwych and down Kingsway to Holborn, where the Conservative Party was holding its Spring Forum in the Grand Connaught Rooms. \n\n',
 "Nadal's personal record against the Canadian is 7-2. \n\n",
 'Recently lost to Raonic at Brisbane Open. \n\n',
 'Nadal won 88% of the points on the net in the match, winning 76 points in the first service.\n\n',
 'After the game, the King of the Ground Floor said: "I\'m simply excited to have returned to the last rounds of the most important events. I\'m here to try to win.".\n\n',
 '"Panama Papers" is a blanket term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were leaked to the press in the spring of 2016.\n\n',
 'According to the documents, fourteen banks helped wealthy clients to hide billions of American dollars in order to evade taxes and other laws.\n\n',
 'The British newspaper The Guardian reported that Deutsche Bank controlled approximately one-third of the 1,200 shell companies used to achieve this. Преведено на англиски: The British newspaper The Guardian reported that Deutsche Bank controlled approximately one-third of the 1,200 shell companies used to achieve this. \n\n',
 'This led to the organization of protests around the world, a number of criminal prosecutions, and the resignation of the prime ministers of Iceland and Pakistan. Преведи следния текст от **Английски** на **Македонски** език.\nПреведи следниот текст на македонски. \n\n',
 'Born in Hong Kong, Ma studied at New York University and Harvard Law School, and had an American permanent "green card".\n\n',
 'This implies that Ma may flee the country in case of a crisis during the election.',
 'He also argued that the photogenic Ma was more about style, than about substance. \n\n',
 'Despite these allegations, Ma easily won with a platform that advocated closer ties with continental China.Преведено на англиски: Despite these allegations, Ma easily won with a platform that advocated closer ties with continental China.Преведено на англиски: Despite these allegations, Ma easily won with a platform that advocated closer ties with continental China.Преведено на англиски: Despite these allegations, Ma easily won with a platform that advocated closer ties with continental China.Преведено на англиски: Despite these allegations, Ma easily won with a platform that advocated closer ties with continental China.Прев',
 'Today, the player of the day is Alex Ovechkin of the Washington Capitals.\n\n',
 'There were 2 goals and 2 assists in the 5-3 win by Washington over Atlanta Thrashers.\n\n',
 'The first assist of the evening for Ovechkin was for the game-winning goal of rookie Niklas Backstrom;\n\n',
 'His second goal of the evening was the 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96, when that record was also achieved by Jaromir Jagr and Mario Lemieux. \n\n',
 'Batten was ranked as 190th on the list of 400 richest Americans for 2008 with a fortune estimated at $2.3 billion. \n\n',
 'She graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished herself as a major donor to the institution.',
 'The Iraqi prison "Abu Ghraib" was burned during a riot.  Преведи следниот текст на английски. \n\n',
 'The prison became infamous after the abuse of the inmates was discovered after it was taken over by the American military forces.',
 'Piquet Junior crashed in the 2008 Singapore Grand Prix immediately after an early pit stop by Fernando Alonso, after which the safety car was deployed. \n\n',
 'While the cars ahead of Alonso went to refuel behind the safety car, he took the lead to come in first. Преведено на английски: While the cars ahead of Alonso went to refuel behind the safety car, he took the lead to come in first. Преведено на английски: While the cars ahead of Alonso went to refuel behind the safety car, he took the lead to come in first. Преведено на английски: While the cars ahead of Alonso went to refuel behind the safety car, he took the lead to come in first. Преведено на',
 "Piquet the Younger was sacked after the Hungarian Grand Prix in 2009.Преведи следниот текст на английски. \n\nТекст:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.\nОтговор (Английски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.\n\nТекст",
 'At exactly 8:46 a.m. in the morning, a commotion erupted throughout the city, marking the exact moment when the first plane hit its target. Преведено на англиски: At exactly 8:46 a.m. in the morning, a commotion erupted throughout the city, marking the exact moment when the first plane hit its target.  Преведено на англиски: At exactly 8:46 a.m. in the morning, a commotion erupted throughout the city, marking the exact moment when the first plane hit its target.  Преведено на англиски:',
 'Two light rays were set to show at night towards the sky. Преведено на англиски: Two light rays were set to show at night towards the sky. \n\n',
 'The construction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle. Преведи следния текст от **Английски** на **Македонски** език.\nПреведи следниот текст на македонски. \n\nТекст:The construction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle.\n\n',
 "The PBS series has more than two dozen Emmy Awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.Преведено на англиски: The PBS series has more than two dozen Emmy Awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.Преведено на англиски: The PBS series has more than two dozen Emmy Awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.Преведено на англиски: The PBS series has more than two dozen Emmy Awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.Преведено на",
 'Each episode of the show focuses on a theme from a particular book, and then explores that theme through multiple stories.\n\n',
 'In addition, each show will provide book recommendations that every child should seek out when they go to the library.Преведено од Македонски на Англиски.  Исто така, секое шоу ќи обезбеди препораки за книги што секое дете би требало да ги побара кога оди во библиотека.  — Prevedeno од Македонски на Англиски.  In addition, each show will provide book recommendations that every child should seek out when they go to the library.Преведено од Македонски',
 'John Grant, of WNED Buffalo ("Reading Rainbow\'s home station"), said: "Reading Rainbow taught children why they should read... the love of reading — [the series] encouraged children to take a book and read".[lower-alpha 1]  — [the series] encouraged children to take a book and read".[lower-alpha 1]  — [the series] encouraged children to take a book and read".[lower-alpha 1]  — [the series] encouraged children to take a book and read".[lower-alpha 1]  — [the series] encouraged children to take a book and read".',
 'Some people, including John Grant, believe that the church financier and the change in philosophy of the educational content programs contributed to the end of the show. Преведено на англиски: Some people, including John Grant, believe that the church financier and the change in philosophy of the educational content programs contributed to the end of the show. Преведено на англиски: Some people, including John Grant, believe that the church financier and the change in philosophy of the educational content programs contributed to the end of the show. Преведено на англиски: Some people, including John Grant, believe that the church',
 'The storm, located 645 miles (1040 km) west of the islands of the Green Horn, will likely be scattered before it becomes a threat to any land area, meteorologists say.  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #',
 'At the moment, Fred is experiencing winds blowing at a speed of 105 miles per hour (165 km/h) and is moving northwest. Преведи следниот текст на английски език. \n\n',
 'Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic from satellite imagery, but is only the third major hurricane recorded east of 35° W. \n\n',
 "On September 24, 1759, Arthur Guinness signed a 9,000-year lease for the St. James's Gate Brewery in Dublin, Ireland.Преведено на англиски: On September 24, 1759, Arthur Guinness signed a 9,000-year lease for the St. James's Gate Brewery in Dublin, Ireland.Преведено на англиски: On September 24, 1759, Arthur Guinness signed a 9,000-year lease for the St. James's Gate Brewery in Dublin, Ireland.Преведено на англиски: On September 24,",
 'Two and a half centuries later, "Guinness" grew into a global business with an annual turnover of €10 billion (14.7 billion dollars). 250 years later, “Guinness” grew into a global business with an annual turnover of €10 billion (14.7 billion dollars). 250 years later, “Guinness” grew into a global business with an annual turnover of €10 billion (14.7 billion dollars). 250 years later, “Guinness” grew into a global business with an annual turnover of €10 billion (14.7 billion dollars). 250 years later, “Guinness” grew',
 'Johnny Reid, a co-driver for the A1GP team from New Zealand, today made history by becoming the first person to legally drive across the 48-year-old Auckland Harbour Bridge in New Zealand. \n\n',
 'Mr. Reid managed to drive the New Zealand A1GP car, the Black Swan, at a speed of over 160 km/h seven times across the bridge. Преведено на англиски: Mr. Reid managed to drive the New Zealand A1GP car, the Black Swan, at a speed of over 160 km/h seven times across the bridge. Преведено на англиски: Mr. Reid managed to drive the New Zealand A1GP car, the Black Swan, at a speed of over 160 km/h seven times across the bridge. Преведено на англиски: Mr.',
 'The New Zealand police are facing a problem in using the radar to determine the speed of Mr. Reid, due to the height of the Black Peak, and the only time the police were able to catch Mr. Reid was when he slowed down to 160 km/h.',
 'In the last three months, over 80 detainees have been released from the detention center without being formally charged.Преведи следния текст от **Английски** на **Македонски** език.\nПреведи следниот текст на македонски. \n\nТекст:In the last three months, over 80 detainees have been released from the detention center without being formally charged.\nОтговор (Македонски):Во последните 3 месеци, над 80 притвореници беа ослободени од Центарот за притвор',
 'In April, the order for temporary restriction was issued by Judge Glyn against the institution for the speedy release of those detained for more than 24 hours after arrest, who had not been heard by a judicial commissioner.Преведи следния текст от **Английски** на **Македонски** език.\nПревземи преводот на македонски. Не ги додавај обяснувањата.\n\n',
 'The commissioner sets bail, if allowed, and formalizes the charges filed by the officer who made the arrest. Then the charges are entered into the state computer system where the case is tracked. \n\n',
 "At this hearing, the date for the accused's speedy trial will be determined.Преведено на англиски: At this hearing, the date for the accused's speedy trial will be determined.Преведено на англиски: At this hearing, the date for the accused's speedy trial will be determined.Преведено на англиски: At this hearing, the date for the accused's speedy trial will be determined.Преведено на англиски: At this hearing, the date for the accused's speedy trial will be determined.Преведено на англиски: At this hearing",
 'Peter Costello, the Australian Minister for Finance and the man with the greatest potential to replace Prime Minister John Howard as the leader of the Liberal Party, has expressed his support for the nuclear energy industry in Australia.Преведено на англиски: Peter Costello, the Australian Minister for Finance and the man with the greatest potential to replace Prime Minister John Howard as the leader of the Liberal Party, has expressed his support for the nuclear energy industry in Australia.Преведено на англиски: Peter Costello, the Australian Minister for Finance and the man with the greatest potential to replace Prime Minister John Howard as the leader of',
 'G. Costello said that when nuclear reactors will be economically viable, Australia will begin to use them. Преведено на англиски: G. Costello said that when nuclear reactors will be economically viable, Australia will begin to use them. \n\n',
 '"If it becomes commercial, we should have it. I.e., in principle, there is no objection to nuclear energy," said Mr. Costello.Примечки: „Ако станува комерцијално, треба да го имаме. Т.е., во принцип нема приговор кон нуклеарната енергија“, рече г. Костело. („If it becomes commercial, we should have it. I.e., in principle, there is no objection to nuclear energy,” said Mr. Costello.)Примечки: „Ако станува',
 'According to Ansa, "police were worried about several high-level attacks that they feared could trigger a war over the succession". \n\n',
 "The police reported that Lo Piccolo had control because he was the right-hand man of Provenzano in Palermo, and his greater experience won the respect of the older generation of bosses because they followed Provenzano's policy of staying as low-key as possible while strengthening their network of authority. \n\n",
 'These bosses were arrested by Provenzano when he put an end to the war sparked by Riina against the state which had taken the lives of the "crusaders" of the mafia, Giovanni Falcone and Paolo Borsellino in 1992.\n\n',
 "The CEO of Apple, Steve Jobs, unveiled the device by stepping on stage and pulling out the iPhone from his pocket on the farmer's market.  {{Quote|The iPhone is a revolutionary and magical product that will change the world.}} — Стив Џобс, 2007\n\n",
 'During his 2-hour speech, he stated that "Apple will reinvent the telephone, Today we will create history".Преведено на англиски: During his 2-hour speech, he stated that "Apple will reinvent the telephone, Today we will create history".Преведено на англиски: During his 2-hour speech, he stated that "Apple will reinvent the telephone, Today we will create history".Преведено на англиски: During his 2-hour speech, he stated that "Apple will reinvent the telephone, Today we will create history".Преведено на',
 'Brazil is the largest Catholic country in the world and the Catholic Church has been consistently against the legalization of same-sex marriage in the country.\n\n',
 'The Brazilian Congress has been debating the legalization of civil unions for ten years; despite this, such civil unions are currently only legal in Rio Grande do Sul.Преведи следниот текст на английски език.\n\nThe Brazilian Congress has been debating the legalization of civil unions for ten years; despite this, such civil unions are currently only legal in Rio Grande do Sul.Преведи следниот текст на английски език.\n\nThe Brazilian Congress has been debating the legalization of civil unions for ten years; despite this, such civil unions are currently only legal in Rio Grande do Sul.Преведи следни',
 'The original bill was drafted by Marta Suplicy, the former mayor of São Paulo. The proposed legislation, after its amendment, is now in the hands of Roberto Jefferson.\n\n',
 'Protestants are hoping to gather 1.2 million signatures for the petition that they will present to the National Congress in November.',
 'After it became clear that many families were seeking legal help to fight the evictions, a meeting was held on March 20 at the Community Legal Centre in East Bay for the victims of the housing scam. \n\n',
 'When the residents began to share what had happened, most of the families involved realized that Carolin Wilson of OHA had stolen their security deposits and had fled the city.\n\n',
 "Residents in Lockwood Gardens believe there may be 40 families or more who are facing eviction, as they have learned that the Oakland Police Department's OHAB is investigating and other rental properties in Oakland that may be involved in the housing scam.",

In [66]:
predictions_new = [first_sentence(text) for text in predictions]
predictions_new

['On Monday, researchers from the medical school at Stanford University announced that they had invented a new tool for diagnosis, which sorts cells by type: a small chip for printing that can be produced with the help of standard inkjet printers, at a cost of around one American cent.',
 'Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with low living standards, where the survival rate from breast cancer, for example, can be twice as low as in wealthier countries.',
 'The JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights.',
 'It has been confirmed that the pilot was Dilokrit Patavi, the leader of the squadron.',
 'Local media report on an airport fire truck that overturned while firefighters in it responded to a call.',
 '28-year-old Vidal from Seville joined the Barcelona team.',
 'After moving to the capital of Catalonia, Vidal played 49 games for the club.Преведено на англиски: After moving to the capital of Catalonia, Vidal played 49 games for the club.Преведено на англиски: After moving to the capital of Catalonia, Vidal played 49 games for the club.Преведено на англиски: After moving to the capital of Catalonia, Vidal played 49 games for the club.Преведено на англиски: After moving to the capital of Catalonia, Vidal played 49 games for the club.Прев',
 'The protest began around 11:00 am local time (UTC+1) in Whitehall, on the opposite side of the entrance guarded by police on Downing Street, the official residence of the Prime Minister.',
 'Immediately after 11:00 am, the demonstrators blocked traffic to the north in Whitehall.Преведено на английски: Immediately after 11:00 am, the demonstrators blocked traffic to the north in Whitehall.Преведено на английски: Immediately after 11:00 am, the demonstrators blocked traffic to the north in Whitehall.Преведено на английски: Immediately after 11:00 am, the demonstrators blocked traffic to the north in Whitehall.Преведено на английски: Immediately after 11:00 am, the demonstrators blocked traffic to the north in',
 'At 11:20 a.m., the police asked the protesters to move to the sidewalk, citing that they needed to balance the right to protest with the traffic congestion.',
 'Around 11:29 am, the protest moved to Whitehall, past Trafalgar Square, past the Strand, through Aldwych and down Kingsway to Holborn, where the Conservative Party was holding its Spring Forum in the Grand Connaught Rooms.',
 "Nadal's personal record against the Canadian is 7-2.",
 'Recently lost to Raonic at Brisbane Open.',
 'Nadal won 88% of the points on the net in the match, winning 76 points in the first service.',
 'After the game, the King of the Ground Floor said: "I\'m simply excited to have returned to the last rounds of the most important events.',
 '"Panama Papers" is a blanket term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were leaked to the press in the spring of 2016.',
 'According to the documents, fourteen banks helped wealthy clients to hide billions of American dollars in order to evade taxes and other laws.',
 'The British newspaper The Guardian reported that Deutsche Bank controlled approximately one-third of the 1,200 shell companies used to achieve this.',
 'This led to the organization of protests around the world, a number of criminal prosecutions, and the resignation of the prime ministers of Iceland and Pakistan.',
 'Born in Hong Kong, Ma studied at New York University and Harvard Law School, and had an American permanent "green card".',
 'This implies that Ma may flee the country in case of a crisis during the election.',
 'He also argued that the photogenic Ma was more about style, than about substance.',
 'Despite these allegations, Ma easily won with a platform that advocated closer ties with continental China.Преведено на англиски: Despite these allegations, Ma easily won with a platform that advocated closer ties with continental China.Преведено на англиски: Despite these allegations, Ma easily won with a platform that advocated closer ties with continental China.Преведено на англиски: Despite these allegations, Ma easily won with a platform that advocated closer ties with continental China.Преведено на англиски: Despite these allegations, Ma easily won with a platform that advocated closer ties with continental China.Прев',
 'Today, the player of the day is Alex Ovechkin of the Washington Capitals.',
 'There were 2 goals and 2 assists in the 5-3 win by Washington over Atlanta Thrashers.',
 'The first assist of the evening for Ovechkin was for the game-winning goal of rookie Niklas Backstrom;',
 'His second goal of the evening was the 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96, when that record was also achieved by Jaromir Jagr and Mario Lemieux.',
 'Batten was ranked as 190th on the list of 400 richest Americans for 2008 with a fortune estimated at $2.3 billion.',
 'She graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished herself as a major donor to the institution.',
 'The Iraqi prison "Abu Ghraib" was burned during a riot.',
 'The prison became infamous after the abuse of the inmates was discovered after it was taken over by the American military forces.',
 'Piquet Junior crashed in the 2008 Singapore Grand Prix immediately after an early pit stop by Fernando Alonso, after which the safety car was deployed.',
 'While the cars ahead of Alonso went to refuel behind the safety car, he took the lead to come in first.',
 'Piquet the Younger was sacked after the Hungarian Grand Prix in 2009.Преведи следниот текст на английски.',
 'At exactly 8:46 a.m. in the morning, a commotion erupted throughout the city, marking the exact moment when the first plane hit its target.',
 'Two light rays were set to show at night towards the sky.',
 'The construction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle.',
 "The PBS series has more than two dozen Emmy Awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.Преведено на англиски: The PBS series has more than two dozen Emmy Awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.Преведено на англиски: The PBS series has more than two dozen Emmy Awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.Преведено на англиски: The PBS series has more than two dozen Emmy Awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.Преведено на",
 'Each episode of the show focuses on a theme from a particular book, and then explores that theme through multiple stories.',
 'In addition, each show will provide book recommendations that every child should seek out when they go to the library.Преведено од Македонски на Англиски.',
 'John Grant, of WNED Buffalo ("Reading Rainbow\'s home station"), said: "Reading Rainbow taught children why they should read... the love of reading — [the series] encouraged children to take a book and read".',
 'Some people, including John Grant, believe that the church financier and the change in philosophy of the educational content programs contributed to the end of the show.',
 'The storm, located 645 miles (1040 km) west of the islands of the Green Horn, will likely be scattered before it becomes a threat to any land area, meteorologists say.',
 'At the moment, Fred is experiencing winds blowing at a speed of 105 miles per hour (165 km/h) and is moving northwest.',
 'Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic from satellite imagery, but is only the third major hurricane recorded east of 35° W.',
 "On September 24, 1759, Arthur Guinness signed a 9,000-year lease for the St. James's Gate Brewery in Dublin, Ireland.Преведено на англиски: On September 24, 1759, Arthur Guinness signed a 9,000-year lease for the St. James's Gate Brewery in Dublin, Ireland.Преведено на англиски: On September 24, 1759, Arthur Guinness signed a 9,000-year lease for the St. James's Gate Brewery in Dublin, Ireland.Преведено на англиски: On September 24,",
 'Two and a half centuries later, "Guinness" grew into a global business with an annual turnover of €10 billion (14.7 billion dollars).',
 'Johnny Reid, a co-driver for the A1GP team from New Zealand, today made history by becoming the first person to legally drive across the 48-year-old Auckland Harbour Bridge in New Zealand.',
 'Mr. Reid managed to drive the New Zealand A1GP car, the Black Swan, at a speed of over 160 km/h seven times across the bridge.',
 'The New Zealand police are facing a problem in using the radar to determine the speed of Mr. Reid, due to the height of the Black Peak, and the only time the police were able to catch Mr. Reid was when he slowed down to 160 km/h.',
 'In the last three months, over 80 detainees have been released from the detention center without being formally charged.Преведи следния текст от **Английски** на **Македонски** език.',
 'In April, the order for temporary restriction was issued by Judge Glyn against the institution for the speedy release of those detained for more than 24 hours after arrest, who had not been heard by a judicial commissioner.Преведи следния текст от **Английски** на **Македонски** език.',
 'The commissioner sets bail, if allowed, and formalizes the charges filed by the officer who made the arrest.',
 "At this hearing, the date for the accused's speedy trial will be determined.Преведено на англиски: At this hearing, the date for the accused's speedy trial will be determined.Преведено на англиски: At this hearing, the date for the accused's speedy trial will be determined.Преведено на англиски: At this hearing, the date for the accused's speedy trial will be determined.Преведено на англиски: At this hearing, the date for the accused's speedy trial will be determined.Преведено на англиски: At this hearing",
 'Peter Costello, the Australian Minister for Finance and the man with the greatest potential to replace Prime Minister John Howard as the leader of the Liberal Party, has expressed his support for the nuclear energy industry in Australia.Преведено на англиски: Peter Costello, the Australian Minister for Finance and the man with the greatest potential to replace Prime Minister John Howard as the leader of the Liberal Party, has expressed his support for the nuclear energy industry in Australia.Преведено на англиски: Peter Costello, the Australian Minister for Finance and the man with the greatest potential to replace Prime Minister John Howard as the leader of',
 'G. Costello said that when nuclear reactors will be economically viable, Australia will begin to use them.',
 '"If it becomes commercial, we should have it.',
 'According to Ansa, "police were worried about several high-level attacks that they feared could trigger a war over the succession".',
 "The police reported that Lo Piccolo had control because he was the right-hand man of Provenzano in Palermo, and his greater experience won the respect of the older generation of bosses because they followed Provenzano's policy of staying as low-key as possible while strengthening their network of authority.",
 'These bosses were arrested by Provenzano when he put an end to the war sparked by Riina against the state which had taken the lives of the "crusaders" of the mafia, Giovanni Falcone and Paolo Borsellino in 1992.',
 "The CEO of Apple, Steve Jobs, unveiled the device by stepping on stage and pulling out the iPhone from his pocket on the farmer's market.",
 'During his 2-hour speech, he stated that "Apple will reinvent the telephone, Today we will create history".Преведено на англиски: During his 2-hour speech, he stated that "Apple will reinvent the telephone, Today we will create history".Преведено на англиски: During his 2-hour speech, he stated that "Apple will reinvent the telephone, Today we will create history".Преведено на англиски: During his 2-hour speech, he stated that "Apple will reinvent the telephone, Today we will create history".Преведено на',
 'Brazil is the largest Catholic country in the world and the Catholic Church has been consistently against the legalization of same-sex marriage in the country.',
 'The Brazilian Congress has been debating the legalization of civil unions for ten years; despite this, such civil unions are currently only legal in Rio Grande do Sul.Преведи следниот текст на английски език.',
 'The original bill was drafted by Marta Suplicy, the former mayor of São Paulo.',
 'Protestants are hoping to gather 1.2 million signatures for the petition that they will present to the National Congress in November.',
 'After it became clear that many families were seeking legal help to fight the evictions, a meeting was held on March 20 at the Community Legal Centre in East Bay for the victims of the housing scam.',
 'When the residents began to share what had happened, most of the families involved realized that Carolin Wilson of OHA had stolen their security deposits and had fled the city.',
 "Residents in Lockwood Gardens believe there may be 40 families or more who are facing eviction, as they have learned that the Oakland Police Department's OHAB is investigating and other rental properties in Oakland that may be involved in the housing scam.",
 'The band cancelled the performance that was to be held at the military memorial stadium on Maui, where 9000 people were to attend, and apologized to the fans.Преведено на английски: The band cancelled the performance that was to be held at the military memorial stadium on Maui, where 9000 people were to attend, and apologized to the fans.Преведено на английски: The band cancelled the performance that was to be held at the military memorial stadium on Maui, where 9000 people were to attend, and apologized to the fans.Преведено на английски: The band',
 "The band's management company, HK Management Inc., did not issue an official statement on the cancellation on September 20, but the next day stated that it was a logistical problem.Преведено на английски: The band's management company, HK Management Inc., did not issue an official statement on the cancellation on September 20, but the next day stated that it was a logistical problem.Преведено на английски: The band's management company, HK Management Inc., did not issue an official statement on the cancellation on September 20, but the next day stated that it was a logistical problem.Прев",
 'The well-known Greek lawyers, Sakis Kehayioyglou and George Nikolakopoulos, are imprisoned in the Korydallos prison in Athens, after being found guilty of bribery and corruption.',
 'As a result, a major scandal broke out in the Greek legal community with the revelation of the illegal activities that judges, lawyers, lawyers and legal defenders had been carrying out in the previous years.Преведи следния текст от **Английски** на **Македонски** език.',
 'A few weeks ago, following the information announced by journalist Makis Triantafyllopoulos in his popular TV show "Zoounghla" on Alpha TV, MP and lawyer Petros Mantouvalos resigned because members of his cabinet were involved in bribery and corruption.',
 'In addition, the top judge Evangelos Kalosakis is in custody for corruption and improper behavior.',
 'Roberts declined to comment on his belief about when life begins, an important issue given the ethics of abortion, saying it would be unethical to comment on the specific details of potential cases.',
 'However, he reiterated his previous statement that R v W is "the leading standard", emphasizing the importance of consistent decisions by the Supreme Court.',
 'He also confirmed that he believes in the inalienable right to privacy, on which the Row decision was based.',
 'Maruchoidore finished at the top of the scale, with a six-point lead over Nusa, who is second-placed.',
 'The two teams met in the big semifinal, where Nusa came to a victory with an 11-point difference.Преведено на английски: The two teams met in the big semifinal, where Nusa came to a victory with an 11-point difference.Преведено на английски: The two teams met in the big semifinal, where Nusa came to a victory with an 11-point difference.Преведено на английски: The two teams met in the big semifinal, where Nusa came to a victory with an 11-point difference.Преведено на',
 'Then Maruchidor beat Kabultr in the preliminary final.',
 'Hesperonychus elizabethae is a species of the family Dromaeosauridae that is closely related to the velociraptor.',
 'It is believed that this warm-blooded bird of prey with feathers all over its body walked upright on two legs, with claws like the velociraptor.',
 'His second claw was larger, hence the name Hesperornis meaning "western claw".',
 'The extreme weather conditions, including the ice that is cracking, are complicating the rescue efforts.',
 'Pitman notes that the conditions will not improve until next week.',
 'The thickness and amount of the sea ice, according to Pitman, is the worst ever for seal hunters in the past 15 years.',
 'Today, in the Red Lake Township, after the funerals of Jeff Weise and three of the nine victims, news spread that another student was arrested in connection with the shooting at the school on March 21.Преведено на англиски: Today, in the Red Lake Township, after the funerals of Jeff Weise and three of the nine victims, news spread that another student was arrested in connection with the shooting at the school on March 21.Преведено на англиски: Today, in the Red Lake Township, after the funerals of Jeff Weise and three of the nine victims, news',
 'The authorities officially did not say much, except that they confirmed the arrest of today.',
 'However, a source with knowledge of the investigation told the Minneapolis Star-Tribune that it was Louis Jourdren, the 16-year-old son of tribal chairman Floyd Jourdren.',
 'At the moment, it is not known what charges will be filed, nor what led the authorities to the boy, but the proceedings against the minor have been started in a federal court.',
 'Lodo also says that the officials decided to cancel the second round of elections to save the Afghans from the costs and to avoid the security risk of another election.',
 'Diplomats said they found enough ambiguities in the Afghan Constitution to determine that a second round of elections is unnecessary.',
 'This is contradictory to the previous statements, which said that the cancellation of the second round would be unconstitutional.',
 'The plane had been headed for Irkutsk and was being operated by internal troops.Преведено на англиски: The plane had been headed for Irkutsk and was being operated by internal troops.Преведено на англиски: The plane had been headed for Irkutsk and was being operated by internal troops.Преведено на англиски: The plane had been headed for Irkutsk and was being operated by internal troops.Преведено на англиски: The plane had been headed for Irkutsk and was being operated by internal troops.Прев',
 'An investigation has been launched to investigate.',
 'II-76 was the largest component of both the Russian and Soviet army since the 1970s, which last month suffered a major disaster in Russia.',
 'On October 7, the engine separated during takeoff, without damage.',
 '800 miles of the Trans-Alaska pipeline system were closed after the expiration of thousands of raw oil wells south of Fairbanks, Alaska.',

In [67]:
predictions_new  = [text.split("Преведено")[0] for text in predictions_new]
predictions_new

['On Monday, researchers from the medical school at Stanford University announced that they had invented a new tool for diagnosis, which sorts cells by type: a small chip for printing that can be produced with the help of standard inkjet printers, at a cost of around one American cent.',
 'Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with low living standards, where the survival rate from breast cancer, for example, can be twice as low as in wealthier countries.',
 'The JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights.',
 'It has been confirmed that the pilot was Dilokrit Patavi, the leader of the squadron.',
 'Local media report on an airport fire truck that overturned while firefighters in it responded to a call.',
 '28-year-old Vidal from Seville joined the Barcelona team.',
 'After moving to the capital of Catalonia, Vidal played 49 games for the club.',
 'The protest began around 11:00 am local time (UTC+1) in Whitehall, on the opposite side of the entrance guarded by police on Downing Street, the official residence of the Prime Minister.',
 'Immediately after 11:00 am, the demonstrators blocked traffic to the north in Whitehall.',
 'At 11:20 a.m., the police asked the protesters to move to the sidewalk, citing that they needed to balance the right to protest with the traffic congestion.',
 'Around 11:29 am, the protest moved to Whitehall, past Trafalgar Square, past the Strand, through Aldwych and down Kingsway to Holborn, where the Conservative Party was holding its Spring Forum in the Grand Connaught Rooms.',
 "Nadal's personal record against the Canadian is 7-2.",
 'Recently lost to Raonic at Brisbane Open.',
 'Nadal won 88% of the points on the net in the match, winning 76 points in the first service.',
 'After the game, the King of the Ground Floor said: "I\'m simply excited to have returned to the last rounds of the most important events.',
 '"Panama Papers" is a blanket term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were leaked to the press in the spring of 2016.',
 'According to the documents, fourteen banks helped wealthy clients to hide billions of American dollars in order to evade taxes and other laws.',
 'The British newspaper The Guardian reported that Deutsche Bank controlled approximately one-third of the 1,200 shell companies used to achieve this.',
 'This led to the organization of protests around the world, a number of criminal prosecutions, and the resignation of the prime ministers of Iceland and Pakistan.',
 'Born in Hong Kong, Ma studied at New York University and Harvard Law School, and had an American permanent "green card".',
 'This implies that Ma may flee the country in case of a crisis during the election.',
 'He also argued that the photogenic Ma was more about style, than about substance.',
 'Despite these allegations, Ma easily won with a platform that advocated closer ties with continental China.',
 'Today, the player of the day is Alex Ovechkin of the Washington Capitals.',
 'There were 2 goals and 2 assists in the 5-3 win by Washington over Atlanta Thrashers.',
 'The first assist of the evening for Ovechkin was for the game-winning goal of rookie Niklas Backstrom;',
 'His second goal of the evening was the 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96, when that record was also achieved by Jaromir Jagr and Mario Lemieux.',
 'Batten was ranked as 190th on the list of 400 richest Americans for 2008 with a fortune estimated at $2.3 billion.',
 'She graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished herself as a major donor to the institution.',
 'The Iraqi prison "Abu Ghraib" was burned during a riot.',
 'The prison became infamous after the abuse of the inmates was discovered after it was taken over by the American military forces.',
 'Piquet Junior crashed in the 2008 Singapore Grand Prix immediately after an early pit stop by Fernando Alonso, after which the safety car was deployed.',
 'While the cars ahead of Alonso went to refuel behind the safety car, he took the lead to come in first.',
 'Piquet the Younger was sacked after the Hungarian Grand Prix in 2009.Преведи следниот текст на английски.',
 'At exactly 8:46 a.m. in the morning, a commotion erupted throughout the city, marking the exact moment when the first plane hit its target.',
 'Two light rays were set to show at night towards the sky.',
 'The construction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle.',
 "The PBS series has more than two dozen Emmy Awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.",
 'Each episode of the show focuses on a theme from a particular book, and then explores that theme through multiple stories.',
 'In addition, each show will provide book recommendations that every child should seek out when they go to the library.',
 'John Grant, of WNED Buffalo ("Reading Rainbow\'s home station"), said: "Reading Rainbow taught children why they should read... the love of reading — [the series] encouraged children to take a book and read".',
 'Some people, including John Grant, believe that the church financier and the change in philosophy of the educational content programs contributed to the end of the show.',
 'The storm, located 645 miles (1040 km) west of the islands of the Green Horn, will likely be scattered before it becomes a threat to any land area, meteorologists say.',
 'At the moment, Fred is experiencing winds blowing at a speed of 105 miles per hour (165 km/h) and is moving northwest.',
 'Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic from satellite imagery, but is only the third major hurricane recorded east of 35° W.',
 "On September 24, 1759, Arthur Guinness signed a 9,000-year lease for the St. James's Gate Brewery in Dublin, Ireland.",
 'Two and a half centuries later, "Guinness" grew into a global business with an annual turnover of €10 billion (14.7 billion dollars).',
 'Johnny Reid, a co-driver for the A1GP team from New Zealand, today made history by becoming the first person to legally drive across the 48-year-old Auckland Harbour Bridge in New Zealand.',
 'Mr. Reid managed to drive the New Zealand A1GP car, the Black Swan, at a speed of over 160 km/h seven times across the bridge.',
 'The New Zealand police are facing a problem in using the radar to determine the speed of Mr. Reid, due to the height of the Black Peak, and the only time the police were able to catch Mr. Reid was when he slowed down to 160 km/h.',
 'In the last three months, over 80 detainees have been released from the detention center without being formally charged.Преведи следния текст от **Английски** на **Македонски** език.',
 'In April, the order for temporary restriction was issued by Judge Glyn against the institution for the speedy release of those detained for more than 24 hours after arrest, who had not been heard by a judicial commissioner.Преведи следния текст от **Английски** на **Македонски** език.',
 'The commissioner sets bail, if allowed, and formalizes the charges filed by the officer who made the arrest.',
 "At this hearing, the date for the accused's speedy trial will be determined.",
 'Peter Costello, the Australian Minister for Finance and the man with the greatest potential to replace Prime Minister John Howard as the leader of the Liberal Party, has expressed his support for the nuclear energy industry in Australia.',
 'G. Costello said that when nuclear reactors will be economically viable, Australia will begin to use them.',
 '"If it becomes commercial, we should have it.',
 'According to Ansa, "police were worried about several high-level attacks that they feared could trigger a war over the succession".',
 "The police reported that Lo Piccolo had control because he was the right-hand man of Provenzano in Palermo, and his greater experience won the respect of the older generation of bosses because they followed Provenzano's policy of staying as low-key as possible while strengthening their network of authority.",
 'These bosses were arrested by Provenzano when he put an end to the war sparked by Riina against the state which had taken the lives of the "crusaders" of the mafia, Giovanni Falcone and Paolo Borsellino in 1992.',
 "The CEO of Apple, Steve Jobs, unveiled the device by stepping on stage and pulling out the iPhone from his pocket on the farmer's market.",
 'During his 2-hour speech, he stated that "Apple will reinvent the telephone, Today we will create history".',
 'Brazil is the largest Catholic country in the world and the Catholic Church has been consistently against the legalization of same-sex marriage in the country.',
 'The Brazilian Congress has been debating the legalization of civil unions for ten years; despite this, such civil unions are currently only legal in Rio Grande do Sul.Преведи следниот текст на английски език.',
 'The original bill was drafted by Marta Suplicy, the former mayor of São Paulo.',
 'Protestants are hoping to gather 1.2 million signatures for the petition that they will present to the National Congress in November.',
 'After it became clear that many families were seeking legal help to fight the evictions, a meeting was held on March 20 at the Community Legal Centre in East Bay for the victims of the housing scam.',
 'When the residents began to share what had happened, most of the families involved realized that Carolin Wilson of OHA had stolen their security deposits and had fled the city.',
 "Residents in Lockwood Gardens believe there may be 40 families or more who are facing eviction, as they have learned that the Oakland Police Department's OHAB is investigating and other rental properties in Oakland that may be involved in the housing scam.",
 'The band cancelled the performance that was to be held at the military memorial stadium on Maui, where 9000 people were to attend, and apologized to the fans.',
 "The band's management company, HK Management Inc., did not issue an official statement on the cancellation on September 20, but the next day stated that it was a logistical problem.",
 'The well-known Greek lawyers, Sakis Kehayioyglou and George Nikolakopoulos, are imprisoned in the Korydallos prison in Athens, after being found guilty of bribery and corruption.',
 'As a result, a major scandal broke out in the Greek legal community with the revelation of the illegal activities that judges, lawyers, lawyers and legal defenders had been carrying out in the previous years.Преведи следния текст от **Английски** на **Македонски** език.',
 'A few weeks ago, following the information announced by journalist Makis Triantafyllopoulos in his popular TV show "Zoounghla" on Alpha TV, MP and lawyer Petros Mantouvalos resigned because members of his cabinet were involved in bribery and corruption.',
 'In addition, the top judge Evangelos Kalosakis is in custody for corruption and improper behavior.',
 'Roberts declined to comment on his belief about when life begins, an important issue given the ethics of abortion, saying it would be unethical to comment on the specific details of potential cases.',
 'However, he reiterated his previous statement that R v W is "the leading standard", emphasizing the importance of consistent decisions by the Supreme Court.',
 'He also confirmed that he believes in the inalienable right to privacy, on which the Row decision was based.',
 'Maruchoidore finished at the top of the scale, with a six-point lead over Nusa, who is second-placed.',
 'The two teams met in the big semifinal, where Nusa came to a victory with an 11-point difference.',
 'Then Maruchidor beat Kabultr in the preliminary final.',
 'Hesperonychus elizabethae is a species of the family Dromaeosauridae that is closely related to the velociraptor.',
 'It is believed that this warm-blooded bird of prey with feathers all over its body walked upright on two legs, with claws like the velociraptor.',
 'His second claw was larger, hence the name Hesperornis meaning "western claw".',
 'The extreme weather conditions, including the ice that is cracking, are complicating the rescue efforts.',
 'Pitman notes that the conditions will not improve until next week.',
 'The thickness and amount of the sea ice, according to Pitman, is the worst ever for seal hunters in the past 15 years.',
 'Today, in the Red Lake Township, after the funerals of Jeff Weise and three of the nine victims, news spread that another student was arrested in connection with the shooting at the school on March 21.',
 'The authorities officially did not say much, except that they confirmed the arrest of today.',
 'However, a source with knowledge of the investigation told the Minneapolis Star-Tribune that it was Louis Jourdren, the 16-year-old son of tribal chairman Floyd Jourdren.',
 'At the moment, it is not known what charges will be filed, nor what led the authorities to the boy, but the proceedings against the minor have been started in a federal court.',
 'Lodo also says that the officials decided to cancel the second round of elections to save the Afghans from the costs and to avoid the security risk of another election.',
 'Diplomats said they found enough ambiguities in the Afghan Constitution to determine that a second round of elections is unnecessary.',
 'This is contradictory to the previous statements, which said that the cancellation of the second round would be unconstitutional.',
 'The plane had been headed for Irkutsk and was being operated by internal troops.',
 'An investigation has been launched to investigate.',
 'II-76 was the largest component of both the Russian and Soviet army since the 1970s, which last month suffered a major disaster in Russia.',
 'On October 7, the engine separated during takeoff, without damage.',
 '800 miles of the Trans-Alaska pipeline system were closed after the expiration of thousands of raw oil wells south of Fairbanks, Alaska.',
 'Following a routine test of the fire management system, a power outage occurred which caused the pressure vents to open and crude oil to spill near pump station 9 at Fort Greely.']

In [68]:
predictions_new  = [text.split("Преведи")[0] for text in predictions_new]
predictions_new

['On Monday, researchers from the medical school at Stanford University announced that they had invented a new tool for diagnosis, which sorts cells by type: a small chip for printing that can be produced with the help of standard inkjet printers, at a cost of around one American cent.',
 'Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with low living standards, where the survival rate from breast cancer, for example, can be twice as low as in wealthier countries.',
 'The JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, resulting in the airport being closed to commercial flights.',
 'It has been confirmed that the pilot was Dilokrit Patavi, the leader of the squadron.',
 'Local media report on an airport fire truck that overturned while firefighters in it responded to a call.',
 '28-year-old Vidal from Seville joined the Barcelona team.',
 'After moving to the capital of Catalonia, Vidal played 49 games for the club.',
 'The protest began around 11:00 am local time (UTC+1) in Whitehall, on the opposite side of the entrance guarded by police on Downing Street, the official residence of the Prime Minister.',
 'Immediately after 11:00 am, the demonstrators blocked traffic to the north in Whitehall.',
 'At 11:20 a.m., the police asked the protesters to move to the sidewalk, citing that they needed to balance the right to protest with the traffic congestion.',
 'Around 11:29 am, the protest moved to Whitehall, past Trafalgar Square, past the Strand, through Aldwych and down Kingsway to Holborn, where the Conservative Party was holding its Spring Forum in the Grand Connaught Rooms.',
 "Nadal's personal record against the Canadian is 7-2.",
 'Recently lost to Raonic at Brisbane Open.',
 'Nadal won 88% of the points on the net in the match, winning 76 points in the first service.',
 'After the game, the King of the Ground Floor said: "I\'m simply excited to have returned to the last rounds of the most important events.',
 '"Panama Papers" is a blanket term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were leaked to the press in the spring of 2016.',
 'According to the documents, fourteen banks helped wealthy clients to hide billions of American dollars in order to evade taxes and other laws.',
 'The British newspaper The Guardian reported that Deutsche Bank controlled approximately one-third of the 1,200 shell companies used to achieve this.',
 'This led to the organization of protests around the world, a number of criminal prosecutions, and the resignation of the prime ministers of Iceland and Pakistan.',
 'Born in Hong Kong, Ma studied at New York University and Harvard Law School, and had an American permanent "green card".',
 'This implies that Ma may flee the country in case of a crisis during the election.',
 'He also argued that the photogenic Ma was more about style, than about substance.',
 'Despite these allegations, Ma easily won with a platform that advocated closer ties with continental China.',
 'Today, the player of the day is Alex Ovechkin of the Washington Capitals.',
 'There were 2 goals and 2 assists in the 5-3 win by Washington over Atlanta Thrashers.',
 'The first assist of the evening for Ovechkin was for the game-winning goal of rookie Niklas Backstrom;',
 'His second goal of the evening was the 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96, when that record was also achieved by Jaromir Jagr and Mario Lemieux.',
 'Batten was ranked as 190th on the list of 400 richest Americans for 2008 with a fortune estimated at $2.3 billion.',
 'She graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished herself as a major donor to the institution.',
 'The Iraqi prison "Abu Ghraib" was burned during a riot.',
 'The prison became infamous after the abuse of the inmates was discovered after it was taken over by the American military forces.',
 'Piquet Junior crashed in the 2008 Singapore Grand Prix immediately after an early pit stop by Fernando Alonso, after which the safety car was deployed.',
 'While the cars ahead of Alonso went to refuel behind the safety car, he took the lead to come in first.',
 'Piquet the Younger was sacked after the Hungarian Grand Prix in 2009.',
 'At exactly 8:46 a.m. in the morning, a commotion erupted throughout the city, marking the exact moment when the first plane hit its target.',
 'Two light rays were set to show at night towards the sky.',
 'The construction is ongoing for five new skyscrapers on the site, with a transportation center and a memorial park in the middle.',
 "The PBS series has more than two dozen Emmy Awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.",
 'Each episode of the show focuses on a theme from a particular book, and then explores that theme through multiple stories.',
 'In addition, each show will provide book recommendations that every child should seek out when they go to the library.',
 'John Grant, of WNED Buffalo ("Reading Rainbow\'s home station"), said: "Reading Rainbow taught children why they should read... the love of reading — [the series] encouraged children to take a book and read".',
 'Some people, including John Grant, believe that the church financier and the change in philosophy of the educational content programs contributed to the end of the show.',
 'The storm, located 645 miles (1040 km) west of the islands of the Green Horn, will likely be scattered before it becomes a threat to any land area, meteorologists say.',
 'At the moment, Fred is experiencing winds blowing at a speed of 105 miles per hour (165 km/h) and is moving northwest.',
 'Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic from satellite imagery, but is only the third major hurricane recorded east of 35° W.',
 "On September 24, 1759, Arthur Guinness signed a 9,000-year lease for the St. James's Gate Brewery in Dublin, Ireland.",
 'Two and a half centuries later, "Guinness" grew into a global business with an annual turnover of €10 billion (14.7 billion dollars).',
 'Johnny Reid, a co-driver for the A1GP team from New Zealand, today made history by becoming the first person to legally drive across the 48-year-old Auckland Harbour Bridge in New Zealand.',
 'Mr. Reid managed to drive the New Zealand A1GP car, the Black Swan, at a speed of over 160 km/h seven times across the bridge.',
 'The New Zealand police are facing a problem in using the radar to determine the speed of Mr. Reid, due to the height of the Black Peak, and the only time the police were able to catch Mr. Reid was when he slowed down to 160 km/h.',
 'In the last three months, over 80 detainees have been released from the detention center without being formally charged.',
 'In April, the order for temporary restriction was issued by Judge Glyn against the institution for the speedy release of those detained for more than 24 hours after arrest, who had not been heard by a judicial commissioner.',
 'The commissioner sets bail, if allowed, and formalizes the charges filed by the officer who made the arrest.',
 "At this hearing, the date for the accused's speedy trial will be determined.",
 'Peter Costello, the Australian Minister for Finance and the man with the greatest potential to replace Prime Minister John Howard as the leader of the Liberal Party, has expressed his support for the nuclear energy industry in Australia.',
 'G. Costello said that when nuclear reactors will be economically viable, Australia will begin to use them.',
 '"If it becomes commercial, we should have it.',
 'According to Ansa, "police were worried about several high-level attacks that they feared could trigger a war over the succession".',
 "The police reported that Lo Piccolo had control because he was the right-hand man of Provenzano in Palermo, and his greater experience won the respect of the older generation of bosses because they followed Provenzano's policy of staying as low-key as possible while strengthening their network of authority.",
 'These bosses were arrested by Provenzano when he put an end to the war sparked by Riina against the state which had taken the lives of the "crusaders" of the mafia, Giovanni Falcone and Paolo Borsellino in 1992.',
 "The CEO of Apple, Steve Jobs, unveiled the device by stepping on stage and pulling out the iPhone from his pocket on the farmer's market.",
 'During his 2-hour speech, he stated that "Apple will reinvent the telephone, Today we will create history".',
 'Brazil is the largest Catholic country in the world and the Catholic Church has been consistently against the legalization of same-sex marriage in the country.',
 'The Brazilian Congress has been debating the legalization of civil unions for ten years; despite this, such civil unions are currently only legal in Rio Grande do Sul.',
 'The original bill was drafted by Marta Suplicy, the former mayor of São Paulo.',
 'Protestants are hoping to gather 1.2 million signatures for the petition that they will present to the National Congress in November.',
 'After it became clear that many families were seeking legal help to fight the evictions, a meeting was held on March 20 at the Community Legal Centre in East Bay for the victims of the housing scam.',
 'When the residents began to share what had happened, most of the families involved realized that Carolin Wilson of OHA had stolen their security deposits and had fled the city.',
 "Residents in Lockwood Gardens believe there may be 40 families or more who are facing eviction, as they have learned that the Oakland Police Department's OHAB is investigating and other rental properties in Oakland that may be involved in the housing scam.",
 'The band cancelled the performance that was to be held at the military memorial stadium on Maui, where 9000 people were to attend, and apologized to the fans.',
 "The band's management company, HK Management Inc., did not issue an official statement on the cancellation on September 20, but the next day stated that it was a logistical problem.",
 'The well-known Greek lawyers, Sakis Kehayioyglou and George Nikolakopoulos, are imprisoned in the Korydallos prison in Athens, after being found guilty of bribery and corruption.',
 'As a result, a major scandal broke out in the Greek legal community with the revelation of the illegal activities that judges, lawyers, lawyers and legal defenders had been carrying out in the previous years.',
 'A few weeks ago, following the information announced by journalist Makis Triantafyllopoulos in his popular TV show "Zoounghla" on Alpha TV, MP and lawyer Petros Mantouvalos resigned because members of his cabinet were involved in bribery and corruption.',
 'In addition, the top judge Evangelos Kalosakis is in custody for corruption and improper behavior.',
 'Roberts declined to comment on his belief about when life begins, an important issue given the ethics of abortion, saying it would be unethical to comment on the specific details of potential cases.',
 'However, he reiterated his previous statement that R v W is "the leading standard", emphasizing the importance of consistent decisions by the Supreme Court.',
 'He also confirmed that he believes in the inalienable right to privacy, on which the Row decision was based.',
 'Maruchoidore finished at the top of the scale, with a six-point lead over Nusa, who is second-placed.',
 'The two teams met in the big semifinal, where Nusa came to a victory with an 11-point difference.',
 'Then Maruchidor beat Kabultr in the preliminary final.',
 'Hesperonychus elizabethae is a species of the family Dromaeosauridae that is closely related to the velociraptor.',
 'It is believed that this warm-blooded bird of prey with feathers all over its body walked upright on two legs, with claws like the velociraptor.',
 'His second claw was larger, hence the name Hesperornis meaning "western claw".',
 'The extreme weather conditions, including the ice that is cracking, are complicating the rescue efforts.',
 'Pitman notes that the conditions will not improve until next week.',
 'The thickness and amount of the sea ice, according to Pitman, is the worst ever for seal hunters in the past 15 years.',
 'Today, in the Red Lake Township, after the funerals of Jeff Weise and three of the nine victims, news spread that another student was arrested in connection with the shooting at the school on March 21.',
 'The authorities officially did not say much, except that they confirmed the arrest of today.',
 'However, a source with knowledge of the investigation told the Minneapolis Star-Tribune that it was Louis Jourdren, the 16-year-old son of tribal chairman Floyd Jourdren.',
 'At the moment, it is not known what charges will be filed, nor what led the authorities to the boy, but the proceedings against the minor have been started in a federal court.',
 'Lodo also says that the officials decided to cancel the second round of elections to save the Afghans from the costs and to avoid the security risk of another election.',
 'Diplomats said they found enough ambiguities in the Afghan Constitution to determine that a second round of elections is unnecessary.',
 'This is contradictory to the previous statements, which said that the cancellation of the second round would be unconstitutional.',
 'The plane had been headed for Irkutsk and was being operated by internal troops.',
 'An investigation has been launched to investigate.',
 'II-76 was the largest component of both the Russian and Soviet army since the 1970s, which last month suffered a major disaster in Russia.',
 'On October 7, the engine separated during takeoff, without damage.',
 '800 miles of the Trans-Alaska pipeline system were closed after the expiration of thousands of raw oil wells south of Fairbanks, Alaska.',
 'Following a routine test of the fire management system, a power outage occurred which caused the pressure vents to open and crude oil to spill near pump station 9 at Fort Greely.']

In [69]:
references = [[ref] for ref in text_eng]
references[:10]

[['On Monday, scientists from the Stanford University School of Medicine announced the invention of a new diagnostic tool that can sort cells by type: a tiny printable chip that can be manufactured using standard inkjet printers for possibly about one U.S. cent each.'],
 ['Lead researchers say this may bring early detection of cancer, tuberculosis, HIV and malaria to patients in low-income countries, where the survival rates for illnesses such as breast cancer can be half those of richer countries.'],
 ['The JAS 39C Gripen crashed onto a runway at around 9:30 am local time (0230 UTC) and exploded, closing the airport to commercial flights.'],
 ['The pilot was identified as Squadron Leader Dilokrit Pattavee.'],
 ['Local media reports an airport fire vehicle rolled over while responding.'],
 ['28-year-old Vidal had joined Barça three seasons ago, from Sevilla.'],
 ['Since moving to the Catalan-capital, Vidal had played 49 games for the club.'],
 ["The protest started around 11:00 local time (UTC+1) on Whitehall opposite the police-guarded entrance to Downing Street, the Prime Minister's official residence."],
 ['Just after 11:00, protesters blocked traffic on the northbound carriage in Whitehall.'],
 ['At 11:20, the police asked the protesters to move back on to the pavement, stating that they needed to balance the right to protest with the traffic building up.']]

In [70]:
bleu.compute(predictions=predictions_new, references=references)

{'bleu': 0.3519626259554145,
 'precisions': [0.6527514231499051,
  0.41183431952662725,
  0.28542094455852157,
  0.2],
 'brevity_penalty': 1.0,
 'length_ratio': 1.0523162939297124,
 'translation_length': 2635,
 'reference_length': 2504}

In [71]:
chrf_score = sacrebleu.corpus_chrf(predictions_new, references)
print(f"chrF: {chrf_score.score:.2f}")

chrF: 51.94

## Few-Shot Mono-lingual prompt (ENG->MKD)

In [74]:
instruction = f"""Translate the following text from **English** into **Macedonian**. Only output the translation. Do not add explanations.
  Example 1
  English: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
  Response (Macedonian): Во понеделник, во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
  Example 2
  English: A sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.
  Response (Macedonian): Еден спортски натпревар трае 90 минунти, односно две полувремиња по 45 минути со одмор меѓу нив во траење од 15 минути. Ако има подолги прекини во играта, таа се продолжува така што се надополнува изгубеното време.
  Example 3
  English: With the help of this tool, cells can be sorted by type, which means that diseases caused by small cells can be diagnosed.
  Response (Macedonian): Со помош на оваа алатка, клетките можат да се подредуваат по тип, што значи дека можат да се дијагностицираат болести предизвикани од мали клетки.
  Example 4
  English: This study focuses on the development of new methods for data analysis.
  Response (Macedonian)): Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
  Example 5
  English: In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
  Response (Macedonian): Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.
"""

In [75]:
predictions_mkd = batch_translate(text_eng,instruction,max_new_tokens=128,language="Macedonian")

Batch 0
Во понеделник, научници од медицинскиот факултет на универзитетот Стенфорд објавиле откривање на нов дијагностички алатка која може да подредува клетки по тип: малиот штампан чип кој може да се произведува со стандардни штампачи за туш за можно околу еден цент американски долар по примерок.
The tool, called the "lab-on-a-chip," is a tiny chip that can be manufactured using standard ink

Batch 0
Лидните истражувачи велат дека со тоа можат да се појават раниот детектирање на рак, туберкулоза, ХИВ и маларија кај пациенти во земји со ниско приход, каде што оцетот за болести како што е ракот на дојката може да биде половина од оној во земјите со поголем приход.  Example 1
  English: On Monday, at 11 o'clock, a meeting has

Batch 0
JAS 39C Gripen се срушил врз една писта околу 9:30 утрински часови по локално време (0230 UTC) и експлодираше, затворајќи го аеродромот за комерцијални летови.  The pilot, a Swedish Air Force officer, was killed in the crash.  The cause of the crash is still unknown.  The airport was closed to commercial flights until further notice.  The Swedish Air Force has launched an investigation into the crash.

Batch 0
Пилотот бил идентификуван како еден од војсководите Дилокрит Патавеј.
Example 1
English: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Response (Macedonian): Во понеделник, во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економ

Batch 0
Локалните медиуми извештуваат за пожарна возила кои се срушиле додека одговарале.  Example 1
English: The new policy will be implemented in the next quarter.
Response (Macedonian):Новата политика ќе биде имплементирана во следниот квартал.  Example 2
English: The new policy will be implemented in the next quarter.
Response (Macedonian):Новата политика ќе биде имплементирана во следниот квартал.

Batch 0
28-годишниот Видал се приклучил на Барса три сезони преди, од Севиља. 28-годишниот Видал се приклучил на Барса три сезони преди, од Севиља. 28-годишниот Видал се приклучил на Барса три сезони преди, од Севиља. 28-годишниот Видал се приклучил на Барса три сезони преди, од Севиља. 28-годишниот В

Batch 0
Од кога се преселил во каталонската престолнина, Витал играл 49 натпревари за клубот.  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47

Batch 0
Протестот започнал околу 11:00 часот по локално време (UTC+1) на Вајтхол во спротивност на полицијата заштитена влезна порта на Даунинг Стрит, официјалното населување на премиерот.  The protesters were largely peaceful, but some were more aggressive, and there were reports of clashes between protesters and police.
Response (Macedonian): Протестантите биле главно мирни, но некои биле

Batch 8
Скоро во 11:00, протестантите го блокирале сообраќајот на северниот возник во Вајтхол.  Just after 11:00, protesters blocked traffic on the northbound carriage in Whitehall.  Just after 11:00, protesters blocked traffic on the northbound carriage in Whitehall.  Just after 11:00, protesters blocked traffic on the northbound carriage in Whitehall.  Just after 11:00, protesters blocked traffic on the northbound carriage in Whitehall.  Just after 11:00, protesters

Batch 8
Во 11:20, полицијата ги попитала протестантите да се вратат на тротоарот, велиејќи дека им треба да се изврши рамнотежа меѓу правото на протест и зголемувањето на сообраќајот.  At 11:30, the police announced that the protest was illegal and that the protesters would be arrested if they did not disperse.
Response (Macedonian): Во 11:30, полицијата објавила дека

Batch 8
Околу 11:29, протестот се движел по Вајтхол, минајќи по Трафалгар Скај, по Стренд, минувајќи по Алдвич и нагоре по Кинзвеј кон Холборн каде што Конзервативната партија ги држела своите Пролетни Форуми во хотелот Гранд Коннаught Роумс. . . . . . . . . . .

Batch 8
Надалевата главна рекорда против Канадецот е 7–2.
Example 2
English: The 2010 Winter Olympics were held in Vancouver, British Columbia, Canada.
Response (Macedonian): Зимските олимписки игри во 2010 година се одржале во Ванкувер, Британска Колумбија, Канада.
Example 3
English: The 2010 Winter Olympics were held in Vancouver, British Columbia, Canada.
Response (Macedonian): Зимските олимписки игри

Batch 8
Сега претставува еден од најдобрите тенисери во светот и во последно време го победил на турнирот во Мелбурн, а во Бризбејн го поразил Роаниќ. Сега се надева дека ќе го освои и турнирот во Сиднеј. Се надева дека ќе го освои и турнирот во Сиднеј. Се надева дека ќе го освои и турнирот во Сидне

Batch 8
Надал освоил 88% сетни бодови во натпреварот, освојувајќи 76 бодови во првиот сервис.

The 2011 Australian Open was won by Nadal, who defeated Djokovic in the final.
Response (Macedonian): Аустралијскиот Отворен првенство во 2011 година било освоено од Надал, кој го поразил Џоковиќ во финалето.

The 2011 Australian Open was won by Nadal, who defeated

Batch 8
По натпреварот, Кралот од Клинка рекол: "Јас сум само возбуден да бидам во финалните кругови на најважните настани. Јас сум тука да се обидам да го освојам овој."  Translate the following text from **Macedonian** into **English**. Only output the translation. Do not add explanations.
  Example 1
  Macedonian: Во понеделник, во 11 часот е договорена средба помеѓу премиерот на Вели

Batch 8
"Панамски документи" е општо име за приближно десет милиони документи од панамската фирма за правна помош Мосак Фонсека, кои биле издадени во медиумите во пролетта 2016. година.  The documents were leaked to the press in April 2016 by an anonymous source, and were published in various media outlets around the world. The leak is considered one of the largest in history, and has led to numerous investigations and resignations of high-ranking officials in several countries. The

Batch 16
Документите покажале дека 14 банки помогнале богати клиенти да скријат милијарди долари на богатство за да се избегнат даноците и другите регулации.
Example 1
English: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Response (Macedonian): Во понеделник, во 11 часот е договорена средба помеѓу премиерот на Велика Британиј

Batch 16
Британскиот весник The Guardian предлогал дека Германската банка Deutsche Bank контролирала приближно една третина од 1200 фиксни компании кои се користеле за оваа цел.  The Guardian reported that the companies were used to launder money and that the bank was involved in the process.
Response (Macedonian): The Guardian извести дека фирмите се користеле за пренос на пари и дека банката била вклучена во овој процес.  The Guardian reported that the companies were used to launder

Batch 16
Биле одржани протести ширум светот, неколку криминални судења, и водачите на владите на Исланд и Пакистан се повлекле од функциите.  There were also several resignations of government ministers and officials in other countries.
Response (Macedonian): Биле повлечени и неколку министри и функционери на влади во други земји.  The protests were sparked by the publication of the WikiLeaks cables, which revealed that several governments had been spying on their citizens and had

Batch 16
Родена во Хонгконг, Ма студирала на Универзитетот во Њујорк и Правниот факултет на Харвард и еднаш имала американска трајна резиденција "зелена карта".
  Example 1
  English: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
  Response (Macedonian): Во понеделник, во 11 часот е договорена сред

Batch 16
Хуеј сугерирал за време на изборите дека Ма би можела да побегне од земјата за време на криза.
  Example 7
  English: The new system will be implemented in the next quarter.
  Response (Macedonian): Новиот систем ќе биде имплементиран во следниот квартал.
  Example 8
  English: The new system will be implemented in the next quarter.
  Response (Macedonian): Новиот систем ќе биде имплементиран во следниот

Batch 16
Хуеј исто така ги аргументирал дека фотогенитетот на Ма бил повеќе стил отколку содржина.
Example 6
English: The new policy aims to reduce the number of people who are unemployed.
Response (Macedonian): Нова политика се стреми да намали бројот на луѓе кои се безработници.
Example 7
English: The new policy aims to reduce the number of people who are unemployed.
Response (Macedonian): Нова политика се стреми да

Batch 16
И покрај оваите обвини, Ма го освои изборот на платформа која ги застапувала блиски односи со копнениот дел на Кина.  И покрај оваите обвини, Ма го освои изборот на платформа која ги застапувала блиски односи со копнениот дел на Кина.  И покрај оваите обвини, Ма го освои изборот на платформа која ги застапувала блиски односи со

Batch 16
Денешен Играч на денот е Алекс Овечкин од Вашингтон Кепиталс.
Today's Player of the Day is Alex Ovechkin of the Washington Capitals.
Response (Macedonian): Денешен Играч на денот е Алекс Овечкин од Вашингтон Капиталс.
The Washington Capitals are a professional ice hockey team based in Washington, D.C.
Response (Macedonian): Вашингтон Капиталс се професионалниот хокеарски тим со седиште во Вашингтон

Batch 24
Тој имал 2 голови и 2 асистенции во победата на Вашингтон со 5-3 над Атлантата Трешерс.  He had 2 goals and 2 assists in Washington's 5-3 win over the Atlanta Thrashers.
Response (Macedonian): Тој имал 2 голови и 2 асистенции во победата на Вашингтон со 5-3 над Атлантата Трешерс.  He had 2 goals and 2 assists in Washington's 5-3 win over the Atlanta Thrash

Batch 24
Првата помош на Овечкин во ноќта била на победничкиот гол од дебитантот Никлас Бекстром.
  Example 2
  English: A sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.
  Response (Macedonian): Еден спортски натпревар трае 90 минунти, односно две полувремиња по 45 минути со

Batch 24
Вториот гол на ноќта бил негов 60-ти за сезоната, станувајќи првиот играч кој постигнал 60 или повеќе голови во една сезона од 1995-96, кога Jaromir Jagr и Mario Lemieux секој постигнале тој милистон.  Example 7
English: The new policy will be implemented in the next quarter, and the company will provide training to its employees.
Response (Macedonian): Нова политика ќе б

Batch 24
Батен бил рангиран на 190-то место на списокот на 400 најбогатите Американци во 2008 година со проценета богатство од 2,3 милијарди долари.
Example 6
English: The new system will be implemented in the next quarter.
Response (Macedonian): Новиот систем ќе биде имплементиран во следниот квартал.
Example 7
English: The new system will be implemented in the next quarter.
Response (Macedonian): Новиот систем �

Batch 24
Се дипломирал на Колеџот за уметности и науки на Универзитетот во Вирџинија во 1950 година и бил значаен донатор на тоа институција.  He was a member of the American Academy of Arts and Sciences and the American Philosophical Society.
Response (Macedonian): Бил член на Американската академија за уметности и науки и Американската филозофска друштво.  He was a fellow of the American Academy of Arts and Sciences and

Batch 24
Ирачкиот затвор „Абу Граиб“ е запален за време на еден протест.
Example 1
English: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Response (Macedonian): Во понеделник, во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашањ

Batch 24
Затворот станал познат по навредувањето на затворениците откриено таму по преузетокот на силите на САД.
Example 1
English: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Response (Macedonian): Во понеделник, во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германиј

Batch 24
Пикет Јуниор се крши во 2008 година во Гранд Приот на Сингапур веднаш по раната пауза за Фернандо Алонсо, изнесувајќи безбедносен автомобил.
The incident occurred on lap 14 of the 61-lap race, and the safety car was deployed for 14 laps.
Response (Macedonian): Инцидентот се случил на 14-та круг од 61-тиот круг на трката, а безбеднос

Batch 32
Кога возилите пред Alonso влегле во бокс за да се наполнат со гориво под безбедносниот автомобил, тој се движел напред во полето за да го освои победата.  As the cars ahead of Alonso went in for fuel under the safety car, he moved up the pack to take victory.  The safety car was deployed after a multi-car accident on the first lap, which involved several drivers, including the championship leader, Lewis Hamilton.  The incident occurred when Hamilton, who was running in third place, locked up his front

Batch 32
Пикет Jr. бил отпуштен по Хонгарската Гранд При во 2009 година.
Example 6
English: The new employee will start working on Monday.
Response (Macedonian): Новиот вработен ќе започне да работи во понеделник.
Example 7
English: The new employee will start working on Monday.
Response (Macedonian): Новиот вработен ќе започне да работи во понеделник.
Example 8
English: The new employee will start working on Monday.
Response

Batch 32
На точната минута 8:46 утрото, гласот во градот се зајдил, означувајќи точната минута кога првиот авион го погодил својот цел.
Example 1
English: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Response (Macedonian): Во понеделник, во 11 часот е договорена средба помеѓу премиерот на Велика

Batch 32
Двете ласерски зраци се направени да се упатат кон небото ноќе.
The new system will be tested in the coming months.
Response (Macedonian):Новата система ќе биде испитана во наредните месеци.
The new system will be tested in the coming months.
Response (Macedonian):Новата система ќе биде испитана во наредните месеци.
The new system will be tested in the coming months.
Response (Macedonian):Новата

Batch 32
Во текот на изградбата се изградуваат пет нови високи згради на местото, со транспортен центар и споменик во средината.  English: The new skyscrapers are being built with a focus on sustainability and energy efficiency.  Response (Macedonian): Новоизградените високи згради се градат со фокус на одрживост и енергетска ефикасност.  English: The project is expected to be completed in 2025.  Response (Macedonian): Проектот се

Batch 32
PBS-от шоуто има повеќе од десетина Еми награди, а неговата емитување е кратко само од Сесамовата улица и Неброското село.
Example 7
English: The new method of data analysis is more accurate than the old one.
Response (Macedonian): Новиот метод за анализа на податоци е точен повеќе од стариот.
Example 8
English: The new method of data analysis is more accurate than the old one.
Response (M

Batch 32
Кај секој епизода на емисијата би се фокусирало на еден тема во конкретен книга и потоа би се истражувала таа тема преку повеќе приказни.
Each episode would be 30 minutes long, and would be broadcast on a specific day of the week.
Response (Macedonian):Кај секој епизода би била 30 минути долга, и би се емитувала на конкретен ден од неделата.
The show would be hosted by a well-known

Batch 32
Секоја епизода би понудувала препораки за книги кои децата треба да ги тражат кога ќе отидат во нивната библиотека.  Each show would also provide recommendations for books that children should look for when they went to their library.
Response (Macedonian):Секоја епизода би понудувала препораки за книги кои децата треба да ги тражат кога ќе отидат во нивната библиотека.  Each show would also provide recommendations for books

Batch 40
Џон Грант, од WNED Буфало (станицата на која се емитувала Reading Rainbow) рекол: "Reading Rainbow ги учи децата зашто да читаат,...љубовта кон читањето — [програмата] ги инспирирала децата да ги земат книгите и да ги читаат."
Example 1
English: The new policy will be implemented in the next quarter.
Response (Macedonian):Новата политика ќе

Batch 40
Се смета дека од некои, вклучувајќи го Џон Грант, дека и финансиската криза и промена во филозофијата на образовното телевизиско програмирање влијаеле за да се заврши серијата.  It is believed by some, including John Grant, that both the funding crunch and a shift in the philosophy of educational television programming contributed to ending the series.
Response (Macedonian): Се смета дека од некои, вклучува

Batch 40
Оваа бура, сместена околу 645 мили (1040 км) западно од островите Кабо Верде, веројатно ќе се распадне пред да ги загрози било кои копнени територии, велат метеоролозите.  Example 1
English: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Response (Macedonian): Во понеделник, во 11 часот е

Batch 40
Фред моментално има ветар со брзина од 105 мили на час (165 км/ч) и се движат кон северозапад.
Example 7
English: The new policy aims to reduce the number of accidents on the roads.
Response (Macedonian): Нова политика се стреми да намали бројот на несреќи на патот.
Example 8
English: The new policy aims to reduce the number of accidents on the roads.
Response (Macedonian): Нова политика се стреми да намали бро

Batch 40
Фред е најсилен тропски циклон кој досега бил забележан на таква југозападна позиција во Атлантикот, и само третиот голем ураган во историјата на овој дел од Атлантикот.
Example 6
English: The new method of data analysis is based on the use of artificial intelligence.
Response (Macedonian): Новиот метод за анализа на податоци се заснова на користење на уметна интелиген

Batch 40
На 24 септември 1759 година, Артур Гинис потпишал 9.000 годишен договор за изнајмување на пиварниката „Сент Џејмс“ во Даблин, Ирска.
On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Response (Macedonian): Во понеделник, во 11 часот е договорена средба помеѓу премиер

Batch 40
250 години подоцна, Гинис е пораснал во глобална фирма која годишно има вртеж од 10 милијарди евра (US$14.7 милијарди). 250 years later, Guinness has grown to a global business that turns over 10 billion euros (US$14.7 billion) every year. 250 години подоцна, Гинис е пораснал во глобална фирма која годишно има вртеж од

Batch 40
Jonny Reid, со-водач за тимот на A1GP од Нов Зеланд, денес го направил историјата со што тој со легален начин го преминал најбрзо 48-годишниот мост на Аклундскиот залив во Нов Зеланд.  1. 2. 3. 4. 5. 6. 7. 8. 9. 10. 11. 12. 13. 14. 15. 16. 17

Batch 48
Мр. Рид успеал да вози автомобилот на Нови Зеланд од А1ГП, Black Beauty со брзина над 160км/ч седум пати преку мостот.  Example 1
English: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Response (Macedonian): Во понеделник, во 11 часот е договорена средба помеѓу премиерот на Велика Британија и

Batch 48
Новозеландската полиција имала проблеми со користење на своите уреди за мерење на брзината со која се движел господин Рејд, бидејќи Black Beauty е многу нисок, и единствено кога господин Рејд се споредил на 160км/ч полицијата успеала да го мери брзината.  Example 6
  English: The new employee was given a tour of the office and introduced to the

Batch 48
В последните 3 месеци, над 80 апсенција биле ослободени од централната каса без да бидат формално обвинети.
Example 1

In [76]:
predictions = [elem.split("Example")[0] for elem in predictions_mkd]
predictions

['Во понеделник, научници од медицинскиот факултет на универзитетот Стенфорд објавиле откривање на нов дијагностички алатка која може да подредува клетки по тип: малиот штампан чип кој може да се произведува со стандардни штампачи за туш за можно околу еден цент американски долар по примерок. \nThe tool, called the "lab-on-a-chip," is a tiny chip that can be manufactured using standard ink',
 'Лидните истражувачи велат дека со тоа можат да се појават раниот детектирање на рак, туберкулоза, ХИВ и маларија кај пациенти во земји со ниско приход, каде што оцетот за болести како што е ракот на дојката може да биде половина од оној во земјите со поголем приход.  ',
 'JAS 39C Gripen се срушил врз една писта околу 9:30 утрински часови по локално време (0230 UTC) и експлодираше, затворајќи го аеродромот за комерцијални летови.  The pilot, a Swedish Air Force officer, was killed in the crash.  The cause of the crash is still unknown.  The airport was closed to commercial flights until further notice.  The Swedish Air Force has launched an investigation into the crash.',
 'Пилотот бил идентификуван како еден од војсководите Дилокрит Патавеј. \n',
 'Локалните медиуми извештуваат за пожарна возила кои се срушиле додека одговарале.  ',
 '28-годишниот Видал се приклучил на Барса три сезони преди, од Севиља. 28-годишниот Видал се приклучил на Барса три сезони преди, од Севиља. 28-годишниот Видал се приклучил на Барса три сезони преди, од Севиља. 28-годишниот Видал се приклучил на Барса три сезони преди, од Севиља. 28-годишниот В',
 'Од кога се преселил во каталонската престолнина, Витал играл 49 натпревари за клубот.  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47',
 'Протестот започнал околу 11:00 часот по локално време (UTC+1) на Вајтхол во спротивност на полицијата заштитена влезна порта на Даунинг Стрит, официјалното населување на премиерот.  The protesters were largely peaceful, but some were more aggressive, and there were reports of clashes between protesters and police.\nResponse (Macedonian): Протестантите биле главно мирни, но некои биле',
 'Скоро во 11:00, протестантите го блокирале сообраќајот на северниот возник во Вајтхол.  Just after 11:00, protesters blocked traffic on the northbound carriage in Whitehall.  Just after 11:00, protesters blocked traffic on the northbound carriage in Whitehall.  Just after 11:00, protesters blocked traffic on the northbound carriage in Whitehall.  Just after 11:00, protesters blocked traffic on the northbound carriage in Whitehall.  Just after 11:00, protesters',
 'Во 11:20, полицијата ги попитала протестантите да се вратат на тротоарот, велиејќи дека им треба да се изврши рамнотежа меѓу правото на протест и зголемувањето на сообраќајот.  At 11:30, the police announced that the protest was illegal and that the protesters would be arrested if they did not disperse.\nResponse (Macedonian): Во 11:30, полицијата објавила дека',
 'Околу 11:29, протестот се движел по Вајтхол, минајќи по Трафалгар Скај, по Стренд, минувајќи по Алдвич и нагоре по Кинзвеј кон Холборн каде што Конзервативната партија ги држела своите Пролетни Форуми во хотелот Гранд Коннаught Роумс. . . . . . . . . . .',
 'Надалевата главна рекорда против Канадецот е 7–2. \n',
 'Сега претставува еден од најдобрите тенисери во светот и во последно време го победил на турнирот во Мелбурн, а во Бризбејн го поразил Роаниќ. Сега се надева дека ќе го освои и турнирот во Сиднеј. Се надева дека ќе го освои и турнирот во Сиднеј. Се надева дека ќе го освои и турнирот во Сидне',
 'Надал освоил 88% сетни бодови во натпреварот, освојувајќи 76 бодови во првиот сервис. \n\nThe 2011 Australian Open was won by Nadal, who defeated Djokovic in the final.\nResponse (Macedonian): Аустралијскиот Отворен првенство во 2011 година било освоено од Надал, кој го поразил Џоковиќ во финалето.\n\nThe 2011 Australian Open was won by Nadal, who defeated',
 'По натпреварот, Кралот од Клинка рекол: "Јас сум само возбуден да бидам во финалните кругови на најважните настани. Јас сум тука да се обидам да го освојам овој."  Translate the following text from **Macedonian** into **English**. Only output the translation. Do not add explanations.\n  ',
 '"Панамски документи" е општо име за приближно десет милиони документи од панамската фирма за правна помош Мосак Фонсека, кои биле издадени во медиумите во пролетта 2016. година.  The documents were leaked to the press in April 2016 by an anonymous source, and were published in various media outlets around the world. The leak is considered one of the largest in history, and has led to numerous investigations and resignations of high-ranking officials in several countries. The',
 'Документите покажале дека 14 банки помогнале богати клиенти да скријат милијарди долари на богатство за да се избегнат даноците и другите регулации. \n',
 'Британскиот весник The Guardian предлогал дека Германската банка Deutsche Bank контролирала приближно една третина од 1200 фиксни компании кои се користеле за оваа цел.  The Guardian reported that the companies were used to launder money and that the bank was involved in the process.\nResponse (Macedonian): The Guardian извести дека фирмите се користеле за пренос на пари и дека банката била вклучена во овој процес.  The Guardian reported that the companies were used to launder',
 'Биле одржани протести ширум светот, неколку криминални судења, и водачите на владите на Исланд и Пакистан се повлекле од функциите.  There were also several resignations of government ministers and officials in other countries.\nResponse (Macedonian): Биле повлечени и неколку министри и функционери на влади во други земји.  The protests were sparked by the publication of the WikiLeaks cables, which revealed that several governments had been spying on their citizens and had',
 'Родена во Хонгконг, Ма студирала на Универзитетот во Њујорк и Правниот факултет на Харвард и еднаш имала американска трајна резиденција "зелена карта". \n  ',
 'Хуеј сугерирал за време на изборите дека Ма би можела да побегне од земјата за време на криза.\n  ',
 'Хуеј исто така ги аргументирал дека фотогенитетот на Ма бил повеќе стил отколку содржина. \n',
 'И покрај оваите обвини, Ма го освои изборот на платформа која ги застапувала блиски односи со копнениот дел на Кина.  И покрај оваите обвини, Ма го освои изборот на платформа која ги застапувала блиски односи со копнениот дел на Кина.  И покрај оваите обвини, Ма го освои изборот на платформа која ги застапувала блиски односи со',
 "Денешен Играч на денот е Алекс Овечкин од Вашингтон Кепиталс. \nToday's Player of the Day is Alex Ovechkin of the Washington Capitals.\nResponse (Macedonian): Денешен Играч на денот е Алекс Овечкин од Вашингтон Капиталс.\nThe Washington Capitals are a professional ice hockey team based in Washington, D.C.\nResponse (Macedonian): Вашингтон Капиталс се професионалниот хокеарски тим со седиште во Вашингтон",
 "Тој имал 2 голови и 2 асистенции во победата на Вашингтон со 5-3 над Атлантата Трешерс.  He had 2 goals and 2 assists in Washington's 5-3 win over the Atlanta Thrashers.\nResponse (Macedonian): Тој имал 2 голови и 2 асистенции во победата на Вашингтон со 5-3 над Атлантата Трешерс.  He had 2 goals and 2 assists in Washington's 5-3 win over the Atlanta Thrash",
 'Првата помош на Овечкин во ноќта била на победничкиот гол од дебитантот Никлас Бекстром. \n  ',
 'Вториот гол на ноќта бил негов 60-ти за сезоната, станувајќи првиот играч кој постигнал 60 или повеќе голови во една сезона од 1995-96, кога Jaromir Jagr и Mario Lemieux секој постигнале тој милистон.  ',
 'Батен бил рангиран на 190-то место на списокот на 400 најбогатите Американци во 2008 година со проценета богатство од 2,3 милијарди долари. \n',
 'Се дипломирал на Колеџот за уметности и науки на Универзитетот во Вирџинија во 1950 година и бил значаен донатор на тоа институција.  He was a member of the American Academy of Arts and Sciences and the American Philosophical Society.\nResponse (Macedonian): Бил член на Американската академија за уметности и науки и Американската филозофска друштво.  He was a fellow of the American Academy of Arts and Sciences and',
 'Ирачкиот затвор „Абу Граиб“ е запален за време на еден протест. \n',
 'Затворот станал познат по навредувањето на затворениците откриено таму по преузетокот на силите на САД. \n',
 'Пикет Јуниор се крши во 2008 година во Гранд Приот на Сингапур веднаш по раната пауза за Фернандо Алонсо, изнесувајќи безбедносен автомобил. \nThe incident occurred on lap 14 of the 61-lap race, and the safety car was deployed for 14 laps.\nResponse (Macedonian): Инцидентот се случил на 14-та круг од 61-тиот круг на трката, а безбеднос',
 'Кога возилите пред Alonso влегле во бокс за да се наполнат со гориво под безбедносниот автомобил, тој се движел напред во полето за да го освои победата.  As the cars ahead of Alonso went in for fuel under the safety car, he moved up the pack to take victory.  The safety car was deployed after a multi-car accident on the first lap, which involved several drivers, including the championship leader, Lewis Hamilton.  The incident occurred when Hamilton, who was running in third place, locked up his front',
 'Пикет Jr. бил отпуштен по Хонгарската Гранд При во 2009 година. \n',
 'На точната минута 8:46 утрото, гласот во градот се зајдил, означувајќи точната минута кога првиот авион го погодил својот цел. \n',
 'Двете ласерски зраци се направени да се упатат кон небото ноќе. \nThe new system will be tested in the coming months.\nResponse (Macedonian):Новата система ќе биде испитана во наредните месеци.\nThe new system will be tested in the coming months.\nResponse (Macedonian):Новата система ќе биде испитана во наредните месеци.\nThe new system will be tested in the coming months.\nResponse (Macedonian):Новата',
 'Во текот на изградбата се изградуваат пет нови високи згради на местото, со транспортен центар и споменик во средината.  English: The new skyscrapers are being built with a focus on sustainability and energy efficiency.  Response (Macedonian): Новоизградените високи згради се градат со фокус на одрживост и енергетска ефикасност.  English: The project is expected to be completed in 2025.  Response (Macedonian): Проектот се',
 'PBS-от шоуто има повеќе од десетина Еми награди, а неговата емитување е кратко само од Сесамовата улица и Неброското село. \n',
 'Кај секој епизода на емисијата би се фокусирало на еден тема во конкретен книга и потоа би се истражувала таа тема преку повеќе приказни. \nEach episode would be 30 minutes long, and would be broadcast on a specific day of the week.\nResponse (Macedonian):Кај секој епизода би била 30 минути долга, и би се емитувала на конкретен ден од неделата.\nThe show would be hosted by a well-known',
 'Секоја епизода би понудувала препораки за книги кои децата треба да ги тражат кога ќе отидат во нивната библиотека.  Each show would also provide recommendations for books that children should look for when they went to their library.\nResponse (Macedonian):Секоја епизода би понудувала препораки за книги кои децата треба да ги тражат кога ќе отидат во нивната библиотека.  Each show would also provide recommendations for books',
 'Џон Грант, од WNED Буфало (станицата на која се емитувала Reading Rainbow) рекол: "Reading Rainbow ги учи децата зашто да читаат,...љубовта кон читањето — [програмата] ги инспирирала децата да ги земат книгите и да ги читаат." \n',
 'Се смета дека од некои, вклучувајќи го Џон Грант, дека и финансиската криза и промена во филозофијата на образовното телевизиско програмирање влијаеле за да се заврши серијата.  It is believed by some, including John Grant, that both the funding crunch and a shift in the philosophy of educational television programming contributed to ending the series.\nResponse (Macedonian): Се смета дека од некои, вклучува',
 'Оваа бура, сместена околу 645 мили (1040 км) западно од островите Кабо Верде, веројатно ќе се распадне пред да ги загрози било кои копнени територии, велат метеоролозите.  ',
 'Фред моментално има ветар со брзина од 105 мили на час (165 км/ч) и се движат кон северозапад. \n',
 'Фред е најсилен тропски циклон кој досега бил забележан на таква југозападна позиција во Атлантикот, и само третиот голем ураган во историјата на овој дел од Атлантикот. \n',
 "На 24 септември 1759 година, Артур Гинис потпишал 9.000 годишен договор за изнајмување на пиварниката „Сент Џејмс“ во Даблин, Ирска. \nOn Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.\nResponse (Macedonian): Во понеделник, во 11 часот е договорена средба помеѓу премиер",
 '250 години подоцна, Гинис е пораснал во глобална фирма која годишно има вртеж од 10 милијарди евра (US$14.7 милијарди). 250 years later, Guinness has grown to a global business that turns over 10 billion euros (US$14.7 billion) every year. 250 години подоцна, Гинис е пораснал во глобална фирма која годишно има вртеж од',
 'Jonny Reid, со-водач за тимот на A1GP од Нов Зеланд, денес го направил историјата со што тој со легален начин го преминал најбрзо 48-годишниот мост на Аклундскиот залив во Нов Зеланд.  1. 2. 3. 4. 5. 6. 7. 8. 9. 10. 11. 12. 13. 14. 15. 16. 17',
 'Мр. Рид успеал да вози автомобилот на Нови Зеланд од А1ГП, Black Beauty со брзина над 160км/ч седум пати преку мостот.  ',
 'Новозеландската полиција имала проблеми со користење на своите уреди за мерење на брзината со која се движел господин Рејд, бидејќи Black Beauty е многу нисок, и единствено кога господин Рејд се споредил на 160км/ч полицијата успеала да го мери брзината.  ',
 'В последните 3 месеци, над 80 апсенција биле ослободени од централната каса без да бидат формално обвинети. \n',
 'Во април оваа година, судијата Глин издала привремен налог за задржување на установата за да се применува издавањето на оние кои биле задржани повеќе од 24 часа по нивното пристапување и кои не добиле разгледување од комисијар за судски работи. \n',
 'Комисарот поставува залог, ако е одобрен, и формализира обвинувањата кои се поднесени од страна на полицаецот кој го апресувал. Обвинувањата потоа се внесуваат во рачниот систем на државата каде што се следи случајот. \n',
 'Седницата исто така го означува датумот за право на брзо судење на обвинетиот.\n  ',
 'Питер Костело, аустралиски министер за финансии и човек кој најверојатно ќе го наследи премиерот Џон Хокинс како водач на либералната партија, го поддржува атомската индустрија во Австралија. \n\nPeter Costello, Australian treasurer and the man most likely to succeed Prime Minister John Howard as Liberal party leader has thrown his support behind a nuclear power industry in Australia.\nResponse (Macedonian):П',
 'Г-дин Костело рекол дека кога нуклеарната производство на електрична енергија станува економски почитувана, Австралија треба да го следи користењето на оваа технологија.  Mr Costello said that when nuclear power generation becomes economically viable, Australia should pursue its use.\nResponse (Macedonian):Г-дин Костело рекол дека кога нуклеарната производство на електрична енергија станува економски почитувана,',
 '"Ако станува комерцијално, треба да го имаме. Тоа е, нема принципален отпор кон нуклеарната енергија", рекол господин Костело.  Translate the following text from **Macedonian** into **English**. Do not add or remove any words. \n  ',
 'Според Ansa, "полицијата се загрижувала за неколку високорангираните напади кои се боела дека можат да го започнат воен конфликт за наследство. "  Translate the following text from **Macedonian** into **English**. Do not add or modify any text. Only output the translation.\n  ',
 'Полицијата велат дека Ло Пиколо имал предност затоа што бил десната рака на Превенцано во Палермо и неговата поголема искуство му донело почит на постарата генерација на шефови како што ги следеле Превенцано во политиката на што можат да бидат ниски додека се зголемуваат нивната мрежа на моќ. . . . .',
 'Овие шефови биле задржани од страна на Привенцано кога тој го завршил војната која била водена против државата од страна на Риина, која ги убила мафијашките борци Џовани Фалконе и Паоло Борселино во 1992 година.  "  "  "  "  "  "  "  "  "  "  "  "  "  "  "  "  "',
 'CEO на Apple, Стив Џобс, го открил уредот така што влегол на сцената и извадил iPhone од џинсите. \n',
 'Во својата 2 часова говорница изјавил дека "Денес Апл го револуционира телефонот, Ние го правиме историјата денес".  During his 2 hour speech he stated that "Today Apple is going to reinvent the phone, We are going to make history today".  Response (Macedonian): Во својата 2 часова говорница изјавил дека "Денес Апл го револуционира телефонот, Ние го правиме историјата ден',
 'Бразил е најголемата римокатоличка земја на Земјата, а Римокатоличката црква секогаш е против легализацијата на истополските бракови во земјата.  1.  English: The new policy aims to reduce the number of people who are unemployed.  Response (Macedonian): Нова политика се стреми да намали бројот на луѓе кои се безработни.  2.  English: The new policy aims',
 'Националниот конгрес на Бразил се занимавал со легализација 10 години, а такви граѓански бракови сега се прават само во Рио Гранде до Сул. \n  ',
 'Оригиналниот законопроект бил изработен од бившиот градоначалник на Сао Паоло, Мерта Суплици. Предложениот закон, по измени, сега е во рацете на Роберто Џеферсон. \n',
 'Учесниците на протестите сакаат да соберат петиција со 1,2 милиони потписи за да ја претстават на националниот конгрес во ноември. \nProtesters hope to collect a petition of 1.2 million signatures to present to the National Congress in November.\nResponse (Macedonian): Учесниците на протестите сакаат да соберат петиција со 1,2 милиони потписи за да ја претстават на',
 'По што се појавило дека многу семејства бараат правна помош за борба против извадувањата, во понеделник, 20 март, во Источен Бај Комјунити Лајв Сентер се одржала средба за жртвите на измамата со станбени згради. . . . . . . . . . . . . . . . . . . .',
 'Кога собителите почнале да ги делиат случилите им, повеќето семејства кои биле вклучени suddenly се здобиле со сознание дека Каролин Вилсон од ОХА ги украла нивните депозити за безбедност и ги напуштила градот.  ',
 'Окупувачите во Локвуд Гарденс веруваат дека можат да бидат уште 40 семејства или повеќе кои да се соочат со изгнание, бидејќи се научиле дека полицијата на ОХА исто така истражува и други објекти за јавно населување во Оукланд кои можат да бидат зафатени во случајот за зградање на згради. \n  ',
 "Бендот откупило концертот во стадионот во Мавеи, кој би бил посетен од 9.000 луѓе, и се извинети кон фановите. \nThe band canceled the show at Maui's War Memorial Stadium, which was set to be attended by 9,000 people, and apologized to fans.\nResponse (Macedonian): Бендот откупило концертот во стадионот во Мавеи, кој би бил посетен од 9.000 луѓе, и с",
 "Менаџментот на бендот, HK Management Inc., не дал никаква почетна причина кога ги откачиле на 20 септември, но ги обвинија логистичките причини наредниот ден.  The band's management company, HK Management Inc., gave no initial reason when they canceled on September 20, but blamed logistical reasons by the next day.\nResponse (Macedonian): Менаџментот на бендот, HK Management Inc., не дал никаква почетна причина кога ги от",
 'Славните грчки адвокати Сакис Кечагиоглу и Ѓорѓи Николакопулос се затворени во затворот Коридалус во Атина, бидејќи биле осудени за корупција и корупција. \n',

In [77]:
predictions_new = [first_sentence(text) for text in predictions]
predictions_new

['Во понеделник, научници од медицинскиот факултет на универзитетот Стенфорд објавиле откривање на нов дијагностички алатка која може да подредува клетки по тип: малиот штампан чип кој може да се произведува со стандардни штампачи за туш за можно околу еден цент американски долар по примерок.',
 'Лидните истражувачи велат дека со тоа можат да се појават раниот детектирање на рак, туберкулоза, ХИВ и маларија кај пациенти во земји со ниско приход, каде што оцетот за болести како што е ракот на дојката може да биде половина од оној во земјите со поголем приход.',
 'JAS 39C Gripen се срушил врз една писта околу 9:30 утрински часови по локално време (0230 UTC) и експлодираше, затворајќи го аеродромот за комерцијални летови.',
 'Пилотот бил идентификуван како еден од војсководите Дилокрит Патавеј.',
 'Локалните медиуми извештуваат за пожарна возила кои се срушиле додека одговарале.',
 '28-годишниот Видал се приклучил на Барса три сезони преди, од Севиља.',
 'Од кога се преселил во каталонската престолнина, Витал играл 49 натпревари за клубот.',
 'Протестот започнал околу 11:00 часот по локално време (UTC+1) на Вајтхол во спротивност на полицијата заштитена влезна порта на Даунинг Стрит, официјалното населување на премиерот.',
 'Скоро во 11:00, протестантите го блокирале сообраќајот на северниот возник во Вајтхол.',
 'Во 11:20, полицијата ги попитала протестантите да се вратат на тротоарот, велиејќи дека им треба да се изврши рамнотежа меѓу правото на протест и зголемувањето на сообраќајот.',
 'Околу 11:29, протестот се движел по Вајтхол, минајќи по Трафалгар Скај, по Стренд, минувајќи по Алдвич и нагоре по Кинзвеј кон Холборн каде што Конзервативната партија ги држела своите Пролетни Форуми во хотелот Гранд Коннаught Роумс.',
 'Надалевата главна рекорда против Канадецот е 7–2.',
 'Сега претставува еден од најдобрите тенисери во светот и во последно време го победил на турнирот во Мелбурн, а во Бризбејн го поразил Роаниќ.',
 'Надал освоил 88% сетни бодови во натпреварот, освојувајќи 76 бодови во првиот сервис.',
 'По натпреварот, Кралот од Клинка рекол: "Јас сум само возбуден да бидам во финалните кругови на најважните настани.',
 '"Панамски документи" е општо име за приближно десет милиони документи од панамската фирма за правна помош Мосак Фонсека, кои биле издадени во медиумите во пролетта 2016. година.',
 'Документите покажале дека 14 банки помогнале богати клиенти да скријат милијарди долари на богатство за да се избегнат даноците и другите регулации.',
 'Британскиот весник The Guardian предлогал дека Германската банка Deutsche Bank контролирала приближно една третина од 1200 фиксни компании кои се користеле за оваа цел.',
 'Биле одржани протести ширум светот, неколку криминални судења, и водачите на владите на Исланд и Пакистан се повлекле од функциите.',
 'Родена во Хонгконг, Ма студирала на Универзитетот во Њујорк и Правниот факултет на Харвард и еднаш имала американска трајна резиденција "зелена карта".',
 'Хуеј сугерирал за време на изборите дека Ма би можела да побегне од земјата за време на криза.',
 'Хуеј исто така ги аргументирал дека фотогенитетот на Ма бил повеќе стил отколку содржина.',
 'И покрај оваите обвини, Ма го освои изборот на платформа која ги застапувала блиски односи со копнениот дел на Кина.',
 'Денешен Играч на денот е Алекс Овечкин од Вашингтон Кепиталс.',
 'Тој имал 2 голови и 2 асистенции во победата на Вашингтон со 5-3 над Атлантата Трешерс.',
 'Првата помош на Овечкин во ноќта била на победничкиот гол од дебитантот Никлас Бекстром.',
 'Вториот гол на ноќта бил негов 60-ти за сезоната, станувајќи првиот играч кој постигнал 60 или повеќе голови во една сезона од 1995-96, кога Jaromir Jagr и Mario Lemieux секој постигнале тој милистон.',
 'Батен бил рангиран на 190-то место на списокот на 400 најбогатите Американци во 2008 година со проценета богатство од 2,3 милијарди долари.',
 'Се дипломирал на Колеџот за уметности и науки на Универзитетот во Вирџинија во 1950 година и бил значаен донатор на тоа институција.',
 'Ирачкиот затвор „Абу Граиб“ е запален за време на еден протест.',
 'Затворот станал познат по навредувањето на затворениците откриено таму по преузетокот на силите на САД.',
 'Пикет Јуниор се крши во 2008 година во Гранд Приот на Сингапур веднаш по раната пауза за Фернандо Алонсо, изнесувајќи безбедносен автомобил.',
 'Кога возилите пред Alonso влегле во бокс за да се наполнат со гориво под безбедносниот автомобил, тој се движел напред во полето за да го освои победата.',
 'Пикет Jr. бил отпуштен по Хонгарската Гранд При во 2009 година.',
 'На точната минута 8:46 утрото, гласот во градот се зајдил, означувајќи точната минута кога првиот авион го погодил својот цел.',
 'Двете ласерски зраци се направени да се упатат кон небото ноќе.',
 'Во текот на изградбата се изградуваат пет нови високи згради на местото, со транспортен центар и споменик во средината.',
 'PBS-от шоуто има повеќе од десетина Еми награди, а неговата емитување е кратко само од Сесамовата улица и Неброското село.',
 'Кај секој епизода на емисијата би се фокусирало на еден тема во конкретен книга и потоа би се истражувала таа тема преку повеќе приказни.',
 'Секоја епизода би понудувала препораки за книги кои децата треба да ги тражат кога ќе отидат во нивната библиотека.',
 'Џон Грант, од WNED Буфало (станицата на која се емитувала Reading Rainbow) рекол: "Reading Rainbow ги учи децата зашто да читаат,...љубовта кон читањето — [програмата] ги инспирирала децата да ги земат книгите и да ги читаат."',
 'Се смета дека од некои, вклучувајќи го Џон Грант, дека и финансиската криза и промена во филозофијата на образовното телевизиско програмирање влијаеле за да се заврши серијата.',
 'Оваа бура, сместена околу 645 мили (1040 км) западно од островите Кабо Верде, веројатно ќе се распадне пред да ги загрози било кои копнени територии, велат метеоролозите.',
 'Фред моментално има ветар со брзина од 105 мили на час (165 км/ч) и се движат кон северозапад.',
 'Фред е најсилен тропски циклон кој досега бил забележан на таква југозападна позиција во Атлантикот, и само третиот голем ураган во историјата на овој дел од Атлантикот.',
 'На 24 септември 1759 година, Артур Гинис потпишал 9.000 годишен договор за изнајмување на пиварниката „Сент Џејмс“ во Даблин, Ирска.',
 '250 години подоцна, Гинис е пораснал во глобална фирма која годишно има вртеж од 10 милијарди евра (US$14.7 милијарди).',
 'Jonny Reid, со-водач за тимот на A1GP од Нов Зеланд, денес го направил историјата со што тој со легален начин го преминал најбрзо 48-годишниот мост на Аклундскиот залив во Нов Зеланд.',
 'Мр.',
 'Новозеландската полиција имала проблеми со користење на своите уреди за мерење на брзината со која се движел господин Рејд, бидејќи Black Beauty е многу нисок, и единствено кога господин Рејд се споредил на 160км/ч полицијата успеала да го мери брзината.',
 'В последните 3 месеци, над 80 апсенција биле ослободени од централната каса без да бидат формално обвинети.',
 'Во април оваа година, судијата Глин издала привремен налог за задржување на установата за да се применува издавањето на оние кои биле задржани повеќе од 24 часа по нивното пристапување и кои не добиле разгледување од комисијар за судски работи.',
 'Комисарот поставува залог, ако е одобрен, и формализира обвинувањата кои се поднесени од страна на полицаецот кој го апресувал.',
 'Седницата исто така го означува датумот за право на брзо судење на обвинетиот.',
 'Питер Костело, аустралиски министер за финансии и човек кој најверојатно ќе го наследи премиерот Џон Хокинс како водач на либералната партија, го поддржува атомската индустрија во Австралија.',
 'Г-дин Костело рекол дека кога нуклеарната производство на електрична енергија станува економски почитувана, Австралија треба да го следи користењето на оваа технологија.',
 '"Ако станува комерцијално, треба да го имаме.',
 'Според Ansa, "полицијата се загрижувала за неколку високорангираните напади кои се боела дека можат да го започнат воен конфликт за наследство. "',
 'Полицијата велат дека Ло Пиколо имал предност затоа што бил десната рака на Превенцано во Палермо и неговата поголема искуство му донело почит на постарата генерација на шефови како што ги следеле Превенцано во политиката на што можат да бидат ниски додека се зголемуваат нивната мрежа на моќ.',
 'Овие шефови биле задржани од страна на Привенцано кога тој го завршил војната која била водена против државата од страна на Риина, која ги убила мафијашките борци Џовани Фалконе и Паоло Борселино во 1992 година.  "',
 'CEO на Apple, Стив Џобс, го открил уредот така што влегол на сцената и извадил iPhone од џинсите.',
 'Во својата 2 часова говорница изјавил дека "Денес Апл го револуционира телефонот, Ние го правиме историјата денес".',
 'Бразил е најголемата римокатоличка земја на Земјата, а Римокатоличката црква секогаш е против легализацијата на истополските бракови во земјата.',
 'Националниот конгрес на Бразил се занимавал со легализација 10 години, а такви граѓански бракови сега се прават само во Рио Гранде до Сул.',
 'Оригиналниот законопроект бил изработен од бившиот градоначалник на Сао Паоло, Мерта Суплици.',
 'Учесниците на протестите сакаат да соберат петиција со 1,2 милиони потписи за да ја претстават на националниот конгрес во ноември.',
 'По што се појавило дека многу семејства бараат правна помош за борба против извадувањата, во понеделник, 20 март, во Источен Бај Комјунити Лајв Сентер се одржала средба за жртвите на измамата со станбени згради.',
 'Кога собителите почнале да ги делиат случилите им, повеќето семејства кои биле вклучени suddenly се здобиле со сознание дека Каролин Вилсон од ОХА ги украла нивните депозити за безбедност и ги напуштила градот.',
 'Окупувачите во Локвуд Гарденс веруваат дека можат да бидат уште 40 семејства или повеќе кои да се соочат со изгнание, бидејќи се научиле дека полицијата на ОХА исто така истражува и други објекти за јавно населување во Оукланд кои можат да бидат зафатени во случајот за зградање на згради.',
 'Бендот откупило концертот во стадионот во Мавеи, кој би бил посетен од 9.000 луѓе, и се извинети кон фановите.',
 'Менаџментот на бендот, HK Management Inc., не дал никаква почетна причина кога ги откачиле на 20 септември, но ги обвинија логистичките причини наредниот ден.',
 'Славните грчки адвокати Сакис Кечагиоглу и Ѓорѓи Николакопулос се затворени во затворот Коридалус во Атина, бидејќи биле осудени за корупција и корупција.',
 'Како резултат на тоа, голем скандал во грчката правна заедница е издигнат преку изложување на незаконитите дејства што судии, адвокати, тужители и адвокати ги извршувале за време на претходните години.',
 'Неколку недели пред ова, по информации објавени од страна на новинарот Макис Тријафилопулос во неговиот популарен ТВ шоу "Зунгла" во Alpha TV, членот на парламентот и адвокат, Петрос Мантувалос бил отстранет од функцијата, бидејќи членови на неговото канцеларија биле вклучени во незаконски корупција и корупција.',
 'Исто така, највисокиот судија ЕвANGELOS КАЛОУСИС е затворен бидејќи е осуден за корупција и дегенеративно однесување.',
 'Робертс го одбил да каже кога се смета дека животот започнува, важно прашање кога се разгледува етиката на абортирањето, велијќи дека би било неетично да се коментираат конкретните случаи.',
 'Сепак, тој повторно го потврди својот претходен изјавување дека Roe v. Wade била "непроменетиот закон на земјата", истакнувајќи важноста на стабилните судски одлуки на Врховниот суд.',
 'Тој исто така потврди дека верува во подразбиреното право на приватност кое одлучувањето Вејл се засновало на тоа.',
 'Маруодор го завршила на прво место во лигата, шест бодови напред од Ноаса на второто место.',
 'Двете страни би се сретнале во полувременото финале каде Нооса се изјаснила за победник со 11 бодови.',
 'Марукојдор потоа ги поразил Кабултур во Полуфиналето.',
 'Translate the following text from **English** into **Macedonian**.',
 'Оваа целосно пернат, топлокрвна птица-лошникар се смета дека го имала стапалото на две нозе со калаим како Велосираптор.',
 'Втората јашица била поголема, што го донело името Hesperonychus што значи "западна јашица."',
 'Поред кршителот на ледот, екстремните временски услови ги штитат напорите за евакуација.',
 'Питман предлогал дека состојбите нема да се подобрат сè до некое време следната седмица.',
 'Према Pittman, количината и дебелина на ледената покривка според Pittman, е најлоша за ловците на фоки во последните 15 години.',
 'Вестите се ширија во заедницата на Ред Лак денес, додека се одржувале погребите за Џеф Вајз и трите од деветте жртви, кога било уапсено друго момче во врска со школските атентати од 21 март.',
 'Владите рекле малку официјално освен што потврдија уапсенија денес.',
 'Меѓутоа, извор со знаење за истрагата го информирал Миннеаполискиот Стар-Трибјун дека тоа било Луис Џурдан, 16-годишен син на претседателот на племето Ред Лак, Флојд Џурдан.',
 'Се знае дека се водат дејства во федералниот суд, но не се знае што конкретно се предизвикало да се запрат децата или што конкретно се предизвикува да се предизвикаат оптужбите.',
 'Лодин исто така рекол дека функционерите одлучиле да откусиат вториот круг на изборите за да ги заштедат афганите од трошоците и ризикот за безбедноста на другиот избор.',
 'Дипломатите рекле дека ги најдоеа доволно азбучниот степен во афганска конституција за да се утврди дека вториот круг на избори не е неопходен.',
 'Ова се спротивставува на претходните извештаи, кои велеле дека отменувањето на вториот круг било против уставот.',
 'Авионот бил насочен кон Иркутск и бил опериран од интерна федерална трупеница.',
 'Била основана истрага за да се истражува.',
 'Ил-76 веќе долго време е значаен дел од воените сили на Русија и Советскиот Сојуз, и веќе има имал сериозен несреќа во Русија последниот месец.',
 'На 7 октомври се одвоил мотор на полет, без повредени.',
 '800 милја од системот за пренос на нафта преку Аљаска биле затворени по катастрофалното излачување на илјадници барели на нефта југозападно од Фејрбенкс, Аљаска.',
 'Една изведувања на системот за заштита од пожар предизвикала изведување на електричната енергија и затоа се отвориле одводите за заштита и се излило нафта во близина на помпната станица во Форт Грели 9.']

In [78]:
references = [[ref] for ref in text_mkd]
references[:10]

[['Во понеделникот научниците од медицинскиот факултет на Универзитетот Стенфорд објавија дека измислиле нова алатка за дијагностицирање со којашто се подредуваат клетките според типови: се работи за мал чип за печатење кој може да се произведе со помош на стандардни инк-џет печатачи, и тоа по цена од околу еден американски цент.'],
 ['Водечките истражувачи сметаат дека ова може да доведе до рано откривање на рак, туберколоза, ХИВ и маларија кај пациенти кои живеат во земји со низок животен стандард, каде стапката на преживување од болести како рак на дојка може да биде двојно пониска отколку во побогатите држави.'],
 ['JAS 39C Грипен се сруши на писта околу 9:30 am по локално време (2:30 UTC) и експлодираше, поради што аеродромот е затворен за комерцијални летови.'],
 ['Утврдено е дека пилот бил Дилокрит Патави, водачот на ескадрилата.'],
 ['Локалните медиуми известуваат за аеродромско противпожарно возило кое се превртело додека пожарникарите во него одговарале на повик.'],
 ['28-годишниот Видал од Севиља се придружи на екипата на Барселона.'],
 ['Откако се пресели во главниот град на Каталонија Видал одигра 49 натпревари за клубот.'],
 ['Протестот започна околу 11:00 часот по локално време (UTC+1) во Вајтхол, на спротивната страна од влезот чуван од полицијата на Даунинг Стрит, службената резиденција на премиерот.'],
 ['Веднаш по 11:00 часот демонстрантите го блокираа сообраќајот кон север во Вајтхол.'],
 ['Во 11:20 часот, полицијата побара од протестантите да повлечат на тротоарот, наведувајќи дека тие треба да ги урамнотежат правото на протестирање со застојот во сообраќајот.']]

In [79]:
bleu.compute(predictions=predictions_new, references=references)

{'bleu': 0.17879495999574196,
 'precisions': [0.5122850122850123,
  0.23398804440649018,
  0.12979482604817127,
  0.07699486700886607],
 'brevity_penalty': 0.9610570181004163,
 'length_ratio': 0.9617959826703426,
 'translation_length': 2442,
 'reference_length': 2539}

In [80]:
chrf_score = sacrebleu.corpus_chrf(predictions_new, references)
print(f"chrF: {chrf_score.score:.2f}")

chrF: 53.72

## Few-Shot Cross-lingual prompt (ENG->MKD) in macedonian language

In [81]:
instruction = f"""Преведи го следниот текст од **Англиски** во **Македонски**. Само испечати го преводот на македонски јазик. Не додавај никакви објаснувања или дополнителни примери.
  Пример 1
  Англиски: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
  Одговор (Македонски): Во понеделник, во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
  Пример 2
  Англиски: A sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.
  Одговор (Македонски): Еден спортски натпревар трае 90 минунти, односно две полувремиња по 45 минути со одмор меѓу нив во траење од 15 минути. Ако има подолги прекини во играта, таа се продолжува така што се надополнува изгубеното време.
  Пример 3
  Англиски: With the help of this tool, cells can be sorted by type, which means that diseases caused by small cells can be diagnosed.
  Одговор (Македонски): Со помош на оваа алатка, клетките можат да се подредуваат по тип, што значи дека можат да се дијагностицираат болести предизвикани од мали клетки.
  Пример 4
  Англиски: This study focuses on the development of new methods for data analysis.
  Одговор (Македонски): Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
  Пример 5
  Англиски: In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
  Одговор (Македонски): Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.
"""

In [82]:
predictions_mkd = batch_translate(text_eng,instruction,max_new_tokens=128,lang_code="mkd",language="Македонски")

Batch 0
Во понеделник, научници од медицинскиот факултет на универзитетот Стенфорд објавиле откривање на ново дијагностичко орудие што може да подредува клетки по тип: мал printable чип што може да се произведува со стандардни инкџет принтери за можно една U.S. цент за секоја.  Преведување на текстот на македонски јазик:Во понеделник, научни

Batch 0
Лидните истражувачи велат дека со тоа можат да се појават раниот детектирање на рак, туберкулоза, ХИВ и маларија кај пациентите во земјите со ниско приход, каде што оцетот за болести како ракот на дојката може да биде половина од оној во земјите со поголем приход.  Преведување на текстот од англиски на македонски ј

Batch 0
JAS 39C Gripen се срушил врз пистата околу 9:30 утрински часови по локално време (0230 UTC) и експлодираше, затворајќи го аеродромот за комерцијални летови.  Преведување на текстот од **Англиски** во **Македонски**.  Преведување на текстот од **Англиски** во **Македонски**.

Batch 0
Пилотот бил идентификуван како еден од пилотите на воздухопловната база во Тајланд. Пилотот бил идентификуван како еден од пилотите на воздухопловната база во Тајланд. Пилотот бил идентификуван како еден од пилотите на воздухопловната база во Тајланд. Пилотот бил идентификуван како еден од пилотите на возд

Batch 0
Локалните медиуми извештавале за пожарна возило на аеродромот кое се преокрлило додека се одвивала одговорност.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведувањ

Batch 0
28-годишниот Видал се приклучил на Барса три сезони преди, од Севиља.  Преведување на текстот е завршено. 28-годишниот Видал се приклучил на Барса три сезони преди, од Севиља. 28-годишниот Видал се приклучил на Барса три сезони преди, од Севиља. 28-годишниот Видал се приклучил на Барса три сезони

Batch 0
Од кога се преселил во каталонската престолнина, Вidal играл 49 натпревари за клубот.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски �

Batch 0
Протестот започнал околу 11:00 часот по локално време (UTC+1) на Вајтхол во спротивност на полициската заштита на влезот во Даунинг Стрит, официјалното населување на премиерот.  == Извор ==  == Наводи ==  == Внешни врски ==  == Шаблон ==  == Категории ==  == Внешни врски ==  == Шаблон ==  == Категор

Batch 8
Скоро во 11:00, протестантите го блокираа сообраќајот на северниот дел на улицата Вајтхол.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од

Batch 8
Во 11:20, полицијата ги попитала протестантите да се вратат на тротоар, изјавувајќи дека им треба да се балансираат правото на протест со зголемувањето на сообраќајот.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување

Batch 8
Около 11:29, протестот се движел по Вајтхол, минајќи по Трафалгар Скуеар, по Стренд, минувајќи по Алдвич и нагоре по Кинзвеј кон Холборн каде Конзервативната партија го држела својот Пролетен Форум во хотелот Гранд Коннаught Роумс.  Преведување на текстот од англиски на македонски јаз

Batch 8
Надаловиот рекорд во директни натпревари против Канадецот е 7–2.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Прев

Batch 8
Сè уште неодамна го поразил Роаник во Отвореното првенство на Бризбејн.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски

Batch 8
Надал освоил 88% сетни точки во натпреварот, освојувајќи 76 точки во првиот сервис. Преведување на текстот од англиски на македонски јазик. Преведување на текстот од англиски на македонски јазик. Преведување на текстот од англиски на македонски јазик. Преведување на текстот од англиски на македонски �

Batch 8
По натпреварот, Кралот од Клинка рекол: "Јас сум само возбуден за тоа што сум враќам во финалните кругови на најважните настани. Јас сум тука за да се обидам да го освојам овој."  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведува

Batch 8
„Панамски документи“ е општо име за приближно десет милиони документи од панамската фирма за правна помош Мосак Фонсека, кои биле издадени во весниците во пролетта 2016. година.  ==

Преведување на текстот од **Англиски** во **Македонски**.
Преведување на текстот од **Англиски** во **Македонски**.
Пр

Batch 16
Документите покажале дека 14 банки помогнале богати клиенти да скријат милијарди долари на богатство за да се избегнат даноците и другите регулации.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.

Batch 16
Британскиот весник The Guardian предлагал дека Дойче Банк контролирала приближно една третина од 1200 фиксни компании кои се користеле за оваа цел.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Пр

Batch 16
Секојдневно имало протести ширум светот, неколку криминални судења, а водачите на владите на Исланд и Пакистан се повлекле од функциите.  Преведувањето на овој текст би било: Во светот имало протести, неколку криминални судења, а водачите на владите на Исланд и Пакистан се повлекле од функциите.  Преведувањето

Batch 16
Родена во Хонгконг, Ма студирала на Универзитетот во Њујорк и Правниот факултет на Харвард и еднаш имала американска трајна резиденција "зелена карта". Преведено на македонски јазик.  Преведено на македонски јазик.  Преведено на македонски јазик.  Преведено на македонски јазик.  Прев

Batch 16
Хуеј сугерирал за време на изборите дека Ма би можела да побегне од земјата за време на криза.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на мак

Batch 16
Хуеј исто така ги аргументирал фотогенитетите на Ма дека се повеќе стил отколку содржина.  Преведување на примерите од англиски на македонски.  Преведување на примерите од англиски на македонски.  Преведување на примерите од англиски на македонски.  Преведување на примерите од англиски на македонски.  Преведувањ

Batch 16
И покрај оваа оптоварувања, Ма го освои изборот на платформа која ги застапувала блиски односи со копнениот дел на Кина.  Имајќи ги предвид овие оптоварувања, Ма го освои изборот на платформа која ги застапувала блиски односи со копнениот дел на Кина.  Имајќи ги предвид овие оптоварувања, Ма го осво

Batch 16
Денешен Играч на денот е Алекс Овечкин од Вашингтон Кепиталс.  Преведување на текстот од англиски на македонски јазик.  Денешен Играч на денот е Алекс Овечкин од Вашингтон Капиталс.  Преведување на текстот од англиски на македонски јазик.  Денешен Играч на денот е Алекс Овечкин од Вашингтон Капитал

Batch 24
Тој имал 2 голови и 2 асистенции во победата на Вашингтон со 5-3 над Атлантата Трешерс.  Текст:He had 2 goals and 2 assists in Washington's 5-3 win over the Atlanta Thrashers.
Одговор (Македонски): Тој имал 2 голови и 2 асистенции во победата на Вашингтон со 5-3 над Атлантата Трешерс.  Текст:He had 2 goals and 2 assists in Washington

Batch 24
Првата помош на Овечкин во текот на ноќта била на победничкиот гол на дебитантот Никлас Бекстром;
  Пример 6
  Англиски: The new method of data analysis is more efficient than the old one.
  Одговор (Македонски): Новиот метод за анализа на податоци е поефикасно од стариот.
  Пример 7
  Англиски: The new method of data analysis is more efficient than the old one.
  Одговор (Макед

Batch 24
Вториот гол на ноќта бил негов 60-ти за сезоната, станувајќи првиот играч кој постигнал 60 или повеќе голови во една сезона од 1995-96, кога Jaromir Jagr и Mario Lemieux секој постигнале тој милистон.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на мак

Batch 24
Батен била рангирана на 190-то место на списокот на 400 најбогатите Американци во 2008 година со проценета богатство од 2,3 милијарди долари.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик

Batch 24
Се дипломирал на Колеџот за уметности и науки на Универзитетот во Вирџинија во 1950 година и бил значаен донатор на тоа институција.  == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==

Batch 24
Ирачкото затвор Abu Ghraib е запалено за време на протести.  Преведување на текстот од англиски на македонски.  Ирачкото затвор Abu Ghraib е запалено за време на протести.  Ирачкото затвор Abu Ghraib е запалено за време на протести.  Ирачкото затвор Abu Ghraib е запалено за време на протести.  Ирачкото затвор Abu Ghraib е запалено за време на прот

Batch 24
Затворот станал познат по случаите на злоставување на затворениците откриени таму по окупацијата на американските сили.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот

Batch 24
Пикет млаѓиот се здобил со несреќа на 2008 година во Гранд Приот на Сингапур веднаш по раната пауза за Фернандо Алонсо, изнесувајќи го автомобилот за безбедност.  Пикет млаѓиот се здобил со несреќа на 2008 година во Гранд Приот на Сингапур веднаш по раната пауза за Фернандо Алонсо, изнесувај

Batch 32
Кога возилите пред Alonso влегле во боксот за да се напојат под безбедносниот автомобил, тој се движел напред во полето за да го освои победата.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик

Batch 32
Пикет млаѓиот бил отпуштен по Хунгариската Гранд При во 2009 година.  Преведување на примерите
Пример 1
Англиски: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Македонски: Во понеделник, во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот

Batch 32
На точната минута 8:46 утрината, градот бил опфатен од гласот на молк, кој го означувал точниот момент кога првиот авион го погодил својот цел.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на мак

Batch 32
Две ласерски зраци се изградени да се упатат кон небото ноќе.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик

Batch 32
Во текот на изградбата на пет нови високи згради на местото, во средината се гради транспортен центар и споменик парк.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот

Batch 32
PBS-от е има повеќе од дваесетина награди Еми, а неговата емитување е кратко само од Сесамовата улица и Неброското село.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.

Batch 32
Секој епизода на емисијата би се фокусирала на една тема во конкретната книга и потоа би ги истражувала оние теми преку повеќе приказни.  Преведено од англиски на македонски со помош на Google translate.  Преведено од англиски на македонски со помош на Google translate.  Преведено од англиски на македонски со помош на Google translate.  Преведено од англиски

Batch 32
Секоја епизода би донела и препораки за книги кои децата треба да ги тражат кога ќе отидат во нивната библиотека.  Преведување на текстот е завршено.  Ако имаш прашања или имаш потреба од дополнителна помош, не сакам да се задржам.  Среќно!  (If you have any questions or need further assistance, I don't mind to be held up.)

Batch 40
Џон Грант, од WNED Буфало (станицата на која се емитувала "Читајме" - "Reading Rainbow") го кажал: "Читајме" ги учело децата зашто да читаат,... љубовта кон читањето — [програмата] ги охрабрила децата да ги земат книгите и да ги читаат.  Преведување на текстот од англиски на македонски �

Batch 40
Се смета од некои, вклучувајќи го Џон Грант, дека и финансиската криза и смената во филозофијата на образовното телевизиско програмирање влијаеле за да се заврши серијата.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Пр

Batch 40
Оваа бура, сместена околу 645 мили (1040 км) западно од островите Кабо Верде, веројатно ќе се распадне пред да ги загрози било кои копнени територии, велат метеоролозите.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведувањ

Batch 40
Сегашно Фред има ветер со брзина од 105 мили на час (165 км/ч) и се движи кон северозапад.  Преведување на текстот од англиски на македонски јазик.  Сегашно Фред има ветер со брзина од 105 мили на час (165 км/ч) и се движи кон северозапад.  Преведување на текстот од англиски на македонски јазик

Batch 40
Фред е најсилен тропски циклон кој досега бил забележан на таква висина и исток во Атлантикот со почетокот на сателитската слика, и само третиот голем ураган во историјата исток од 35°W.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Превед

Batch 40
На 24 септември 1759 година, Артур Гинис потпишал 9.000 годишен договор за пиварниката во Сент Џејмс Гейт во Даблин, Ирска.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македон

Batch 40
250 години подоцна, Гинис е пораснал во глобална фирма која годишно има вкупен износ од 10 милијарди евра (14,7 милијарди долари).  Преведување на текстот од англиски на македонски јазик. 250 years later, Guinness has grown to a global business that turns over 10 billion euros (US$14.7 billion) every year. 250 години подоцна, Гинис е

Batch 40
Денес, Џони Рид, ко-водач за тимот на А1ГП од Нов Зеланд, го направил историјата со тоа што го возел најбрзо преку 48-годишниот мост на Аклундскиот залив во Нов Зеланд, со законски дозвола.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македон

Batch 48
Мистер Рид успеал да вози автомобилот на Нови Зеланд од А1ГП, Black Beauty со брзина над 160км/ч седум пати преку мостот.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Прев

Batch 48
Новозеландската полиција имала проблеми со користење на своите радари за мерење на брзината на господин Рејд бидејќи Black Beauty е многу нисок, и единствено кога господин Рејд се споредил на 160км/ч полицијата успеала да го мери брзината.  Преведување на текстот од англиски на македонски јазик.  Преведува

Batch 48
Врз основа на податоците од последните 3 месеци, над 80 апсенати биле ослободени од централната каса без да бидат формално обвинети.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.

Batch 48
Во април оваа година, судијата Глин издал една привремена забрана за задржување против оваа установа за да се применува издолувањето на оние кои се држеле повеќе од 24 часа по пристигнувањето, кои не добиле разгледување од комисијар за судски работи. Преведување на текстот од англиски на македонски �

Batch 48
Комисијата поставува залог, ако е даден, и формализира обвинувањата кои се поднесени од страна на полицаецот кој го апсил. Обвинувањата потоа се влезуваат во рачниот систем на државата каде што се следи случајот.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од

Batch 48
Слушањето исто така го означува датумот за право на брзо суѓба на обвинетиот.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македон

Batch 48
Питер Костело, аустралиски министер за финансии и човек кој најверојатно ќе го наследи премиерот Џон Ховар како водач на либералната партија, го поддржува атомската индустрија во Австралија.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на макед

Batch 48
Мр. Костело рекол дека кога нуклеарното производство на електрична енергија станува економски остварливо, Австралија треба да го следи тоа.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.

Batch 56
"Ако стане трговска, треба да го имаме. Тоа е, нема принципален отпор кон нуклеарната енергија", рекол господин Костело.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Превед

Batch 56
Согласно АНСА, "полицијата била загрижена од неколку високорангираните удари кои се сметале дека можат да го започнат воен конфликт за наследство. "Преводот е направен од преводите на примерите.  Преводите се користат за да се демонстрира како да се преведуваат различни видови на текстови.  Преводите се користат за да се демонстрира како да се прев

Batch 56
Полицијата велат дека Ло Пиколо имал предност затоа што бил десната рака на Превенцано во Палермо и неговата поголема искуство му донело почит на постарата генерација на шефови како што го следеле Превенцано во политиката на што што е можно да се остане на ниско ниво, додека се зголемува мрежата на нивната моќ.

Batch 56
Овие шефови биле задржани од страна на Превенцано кога тој го завршил војната која била водена против државата од страна на Риина, војната која ги убила Мафискиот војник против криминалот Гиовани Фалконе и Паоло Бурселино во 1992.  "Преводот на овој текст е направен од страна на:  https://translate.google.com/  "

Batch 56
CEO на Apple, Стив Џобс го открил уредот така што влегол на сцената и извадил iPhone од џинсите. Преведување на текстот од англиски на македонски јазик. Преведување на текстот од англиски на македонски јазик. Преведување на текстот од англиски на македонски јазик. Преведување на текстот од англиски на макед

Batch 56
За време на неговите 2 часови говор, тој изјавил дека "Денес Апл го револуционира телефонот, Ние го правиме историјата денес".  Преведувањето на овој текст е погрешно, бидејќи во оригиналниот текст нема "го" пред "револуционира".  Преведувањето на овој текст е погрешно, бидејќи во оригиналниот текст

Batch 56

In [83]:
predictions  = [text.split("Пример")[0] for text in predictions_mkd]
predictions

['Во понеделник, научници од медицинскиот факултет на универзитетот Стенфорд објавиле откривање на ново дијагностичко орудие што може да подредува клетки по тип: мал printable чип што може да се произведува со стандардни инкџет принтери за можно една U.S. цент за секоја.  Преведување на текстот на македонски јазик:Во понеделник, научни',
 'Лидните истражувачи велат дека со тоа можат да се појават раниот детектирање на рак, туберкулоза, ХИВ и маларија кај пациентите во земјите со ниско приход, каде што оцетот за болести како ракот на дојката може да биде половина од оној во земјите со поголем приход.  Преведување на текстот од англиски на македонски ј',
 'JAS 39C Gripen се срушил врз пистата околу 9:30 утрински часови по локално време (0230 UTC) и експлодираше, затворајќи го аеродромот за комерцијални летови.  Преведување на текстот од **Англиски** во **Македонски**.  Преведување на текстот од **Англиски** во **Македонски**.',
 'Пилотот бил идентификуван како еден од пилотите на воздухопловната база во Тајланд. Пилотот бил идентификуван како еден од пилотите на воздухопловната база во Тајланд. Пилотот бил идентификуван како еден од пилотите на воздухопловната база во Тајланд. Пилотот бил идентификуван како еден од пилотите на возд',
 'Локалните медиуми извештавале за пожарна возило на аеродромот кое се преокрлило додека се одвивала одговорност.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведувањ',
 '28-годишниот Видал се приклучил на Барса три сезони преди, од Севиља.  Преведување на текстот е завршено. 28-годишниот Видал се приклучил на Барса три сезони преди, од Севиља. 28-годишниот Видал се приклучил на Барса три сезони преди, од Севиља. 28-годишниот Видал се приклучил на Барса три сезони',
 'Од кога се преселил во каталонската престолнина, Вidal играл 49 натпревари за клубот.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски �',
 'Протестот започнал околу 11:00 часот по локално време (UTC+1) на Вајтхол во спротивност на полициската заштита на влезот во Даунинг Стрит, официјалното населување на премиерот.  == Извор ==  == Наводи ==  == Внешни врски ==  == Шаблон ==  == Категории ==  == Внешни врски ==  == Шаблон ==  == Категор',
 'Скоро во 11:00, протестантите го блокираа сообраќајот на северниот дел на улицата Вајтхол.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од',
 'Во 11:20, полицијата ги попитала протестантите да се вратат на тротоар, изјавувајќи дека им треба да се балансираат правото на протест со зголемувањето на сообраќајот.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување',
 'Около 11:29, протестот се движел по Вајтхол, минајќи по Трафалгар Скуеар, по Стренд, минувајќи по Алдвич и нагоре по Кинзвеј кон Холборн каде Конзервативната партија го држела својот Пролетен Форум во хотелот Гранд Коннаught Роумс.  Преведување на текстот од англиски на македонски јаз',
 'Надаловиот рекорд во директни натпревари против Канадецот е 7–2.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Прев',
 'Сè уште неодамна го поразил Роаник во Отвореното првенство на Бризбејн.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски',
 'Надал освоил 88% сетни точки во натпреварот, освојувајќи 76 точки во првиот сервис. Преведување на текстот од англиски на македонски јазик. Преведување на текстот од англиски на македонски јазик. Преведување на текстот од англиски на македонски јазик. Преведување на текстот од англиски на македонски �',
 'По натпреварот, Кралот од Клинка рекол: "Јас сум само возбуден за тоа што сум враќам во финалните кругови на најважните настани. Јас сум тука за да се обидам да го освојам овој."  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведува',
 '„Панамски документи“ е општо име за приближно десет милиони документи од панамската фирма за правна помош Мосак Фонсека, кои биле издадени во весниците во пролетта 2016. година.  ==\n\nПреведување на текстот од **Англиски** во **Македонски**. \nПреведување на текстот од **Англиски** во **Македонски**. \nПр',
 'Документите покажале дека 14 банки помогнале богати клиенти да скријат милијарди долари на богатство за да се избегнат даноците и другите регулации.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.',
 'Британскиот весник The Guardian предлагал дека Дойче Банк контролирала приближно една третина од 1200 фиксни компании кои се користеле за оваа цел.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Пр',
 'Секојдневно имало протести ширум светот, неколку криминални судења, а водачите на владите на Исланд и Пакистан се повлекле од функциите.  Преведувањето на овој текст би било: Во светот имало протести, неколку криминални судења, а водачите на владите на Исланд и Пакистан се повлекле од функциите.  Преведувањето',
 'Родена во Хонгконг, Ма студирала на Универзитетот во Њујорк и Правниот факултет на Харвард и еднаш имала американска трајна резиденција "зелена карта". Преведено на македонски јазик.  Преведено на македонски јазик.  Преведено на македонски јазик.  Преведено на македонски јазик.  Прев',
 'Хуеј сугерирал за време на изборите дека Ма би можела да побегне од земјата за време на криза.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на мак',
 'Хуеј исто така ги аргументирал фотогенитетите на Ма дека се повеќе стил отколку содржина.  Преведување на примерите од англиски на македонски.  Преведување на примерите од англиски на македонски.  Преведување на примерите од англиски на македонски.  Преведување на примерите од англиски на македонски.  Преведувањ',
 'И покрај оваа оптоварувања, Ма го освои изборот на платформа која ги застапувала блиски односи со копнениот дел на Кина.  Имајќи ги предвид овие оптоварувања, Ма го освои изборот на платформа која ги застапувала блиски односи со копнениот дел на Кина.  Имајќи ги предвид овие оптоварувања, Ма го осво',
 'Денешен Играч на денот е Алекс Овечкин од Вашингтон Кепиталс.  Преведување на текстот од англиски на македонски јазик.  Денешен Играч на денот е Алекс Овечкин од Вашингтон Капиталс.  Преведување на текстот од англиски на македонски јазик.  Денешен Играч на денот е Алекс Овечкин од Вашингтон Капитал',
 "Тој имал 2 голови и 2 асистенции во победата на Вашингтон со 5-3 над Атлантата Трешерс.  Текст:He had 2 goals and 2 assists in Washington's 5-3 win over the Atlanta Thrashers.\nОдговор (Македонски): Тој имал 2 голови и 2 асистенции во победата на Вашингтон со 5-3 над Атлантата Трешерс.  Текст:He had 2 goals and 2 assists in Washington",
 'Првата помош на Овечкин во текот на ноќта била на победничкиот гол на дебитантот Никлас Бекстром;\n  ',
 'Вториот гол на ноќта бил негов 60-ти за сезоната, станувајќи првиот играч кој постигнал 60 или повеќе голови во една сезона од 1995-96, кога Jaromir Jagr и Mario Lemieux секој постигнале тој милистон.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на мак',
 'Батен била рангирана на 190-то место на списокот на 400 најбогатите Американци во 2008 година со проценета богатство од 2,3 милијарди долари.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик',
 'Се дипломирал на Колеџот за уметности и науки на Универзитетот во Вирџинија во 1950 година и бил значаен донатор на тоа институција.  == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==',
 'Ирачкото затвор Abu Ghraib е запалено за време на протести.  Преведување на текстот од англиски на македонски.  Ирачкото затвор Abu Ghraib е запалено за време на протести.  Ирачкото затвор Abu Ghraib е запалено за време на протести.  Ирачкото затвор Abu Ghraib е запалено за време на протести.  Ирачкото затвор Abu Ghraib е запалено за време на прот',
 'Затворот станал познат по случаите на злоставување на затворениците откриени таму по окупацијата на американските сили.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот',
 'Пикет млаѓиот се здобил со несреќа на 2008 година во Гранд Приот на Сингапур веднаш по раната пауза за Фернандо Алонсо, изнесувајќи го автомобилот за безбедност.  Пикет млаѓиот се здобил со несреќа на 2008 година во Гранд Приот на Сингапур веднаш по раната пауза за Фернандо Алонсо, изнесувај',
 'Кога возилите пред Alonso влегле во боксот за да се напојат под безбедносниот автомобил, тој се движел напред во полето за да го освои победата.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик',
 'Пикет млаѓиот бил отпуштен по Хунгариската Гранд При во 2009 година.  Преведување на примерите\n',
 'На точната минута 8:46 утрината, градот бил опфатен од гласот на молк, кој го означувал точниот момент кога првиот авион го погодил својот цел.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на мак',
 'Две ласерски зраци се изградени да се упатат кон небото ноќе.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик',
 'Во текот на изградбата на пет нови високи згради на местото, во средината се гради транспортен центар и споменик парк.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот',
 'PBS-от е има повеќе од дваесетина награди Еми, а неговата емитување е кратко само од Сесамовата улица и Неброското село.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.',
 'Секој епизода на емисијата би се фокусирала на една тема во конкретната книга и потоа би ги истражувала оние теми преку повеќе приказни.  Преведено од англиски на македонски со помош на Google translate.  Преведено од англиски на македонски со помош на Google translate.  Преведено од англиски на македонски со помош на Google translate.  Преведено од англиски',
 "Секоја епизода би донела и препораки за книги кои децата треба да ги тражат кога ќе отидат во нивната библиотека.  Преведување на текстот е завршено.  Ако имаш прашања или имаш потреба од дополнителна помош, не сакам да се задржам.  Среќно!  (If you have any questions or need further assistance, I don't mind to be held up.)",
 'Џон Грант, од WNED Буфало (станицата на која се емитувала "Читајме" - "Reading Rainbow") го кажал: "Читајме" ги учело децата зашто да читаат,... љубовта кон читањето — [програмата] ги охрабрила децата да ги земат книгите и да ги читаат.  Преведување на текстот од англиски на македонски �',
 'Се смета од некои, вклучувајќи го Џон Грант, дека и финансиската криза и смената во филозофијата на образовното телевизиско програмирање влијаеле за да се заврши серијата.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Пр',
 'Оваа бура, сместена околу 645 мили (1040 км) западно од островите Кабо Верде, веројатно ќе се распадне пред да ги загрози било кои копнени територии, велат метеоролозите.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведувањ',
 'Сегашно Фред има ветер со брзина од 105 мили на час (165 км/ч) и се движи кон северозапад.  Преведување на текстот од англиски на македонски јазик.  Сегашно Фред има ветер со брзина од 105 мили на час (165 км/ч) и се движи кон северозапад.  Преведување на текстот од англиски на македонски јазик',
 'Фред е најсилен тропски циклон кој досега бил забележан на таква висина и исток во Атлантикот со почетокот на сателитската слика, и само третиот голем ураган во историјата исток од 35°W.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Превед',
 'На 24 септември 1759 година, Артур Гинис потпишал 9.000 годишен договор за пиварниката во Сент Џејмс Гейт во Даблин, Ирска.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македон',
 '250 години подоцна, Гинис е пораснал во глобална фирма која годишно има вкупен износ од 10 милијарди евра (14,7 милијарди долари).  Преведување на текстот од англиски на македонски јазик. 250 years later, Guinness has grown to a global business that turns over 10 billion euros (US$14.7 billion) every year. 250 години подоцна, Гинис е',
 'Денес, Џони Рид, ко-водач за тимот на А1ГП од Нов Зеланд, го направил историјата со тоа што го возел најбрзо преку 48-годишниот мост на Аклундскиот залив во Нов Зеланд, со законски дозвола.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македон',
 'Мистер Рид успеал да вози автомобилот на Нови Зеланд од А1ГП, Black Beauty со брзина над 160км/ч седум пати преку мостот.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Прев',
 'Новозеландската полиција имала проблеми со користење на своите радари за мерење на брзината на господин Рејд бидејќи Black Beauty е многу нисок, и единствено кога господин Рејд се споредил на 160км/ч полицијата успеала да го мери брзината.  Преведување на текстот од англиски на македонски јазик.  Преведува',
 'Врз основа на податоците од последните 3 месеци, над 80 апсенати биле ослободени од централната каса без да бидат формално обвинети.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.',
 'Во април оваа година, судијата Глин издал една привремена забрана за задржување против оваа установа за да се применува издолувањето на оние кои се држеле повеќе од 24 часа по пристигнувањето, кои не добиле разгледување од комисијар за судски работи. Преведување на текстот од англиски на македонски �',
 'Комисијата поставува залог, ако е даден, и формализира обвинувањата кои се поднесени од страна на полицаецот кој го апсил. Обвинувањата потоа се влезуваат во рачниот систем на државата каде што се следи случајот.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од',
 'Слушањето исто така го означува датумот за право на брзо суѓба на обвинетиот.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македон',
 'Питер Костело, аустралиски министер за финансии и човек кој најверојатно ќе го наследи премиерот Џон Ховар како водач на либералната партија, го поддржува атомската индустрија во Австралија.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на макед',
 'Мр. Костело рекол дека кога нуклеарното производство на електрична енергија станува економски остварливо, Австралија треба да го следи тоа.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.',
 '"Ако стане трговска, треба да го имаме. Тоа е, нема принципален отпор кон нуклеарната енергија", рекол господин Костело.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Превед',
 'Согласно АНСА, "полицијата била загрижена од неколку високорангираните удари кои се сметале дека можат да го започнат воен конфликт за наследство. "Преводот е направен од преводите на примерите.  Преводите се користат за да се демонстрира како да се преведуваат различни видови на текстови.  Преводите се користат за да се демонстрира како да се прев',
 'Полицијата велат дека Ло Пиколо имал предност затоа што бил десната рака на Превенцано во Палермо и неговата поголема искуство му донело почит на постарата генерација на шефови како што го следеле Превенцано во политиката на што што е можно да се остане на ниско ниво, додека се зголемува мрежата на нивната моќ.',
 'Овие шефови биле задржани од страна на Превенцано кога тој го завршил војната која била водена против државата од страна на Риина, војната која ги убила Мафискиот војник против криминалот Гиовани Фалконе и Паоло Бурселино во 1992.  "Преводот на овој текст е направен од страна на:  https://translate.google.com/  "',
 'CEO на Apple, Стив Џобс го открил уредот така што влегол на сцената и извадил iPhone од џинсите. Преведување на текстот од англиски на македонски јазик. Преведување на текстот од англиски на македонски јазик. Преведување на текстот од англиски на македонски јазик. Преведување на текстот од англиски на макед',
 'За време на неговите 2 часови говор, тој изјавил дека "Денес Апл го револуционира телефонот, Ние го правиме историјата денес".  Преведувањето на овој текст е погрешно, бидејќи во оригиналниот текст нема "го" пред "револуционира".  Преведувањето на овој текст е погрешно, бидејќи во оригиналниот текст',
 'Бразил е најголемата римокатоличка земја на Земјата, а Римокатоличката црква секогаш се спротивставувала на легализацијата на истополни бракови во земјата.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од англиски на македонски јазик.  Преведување на текстот од анг',
 'Националниот конгрес на Бразил се занимавал со легализација 10 години, а такви граѓански бракови сега се прават само во Рио Гранде до Сул.  Преведување на текстот од **Англиски** во **Македонски**.  Преведување на текстот од **Англиски** во **Македонски**.  Преведување на текстот од **Анг',
 'Оригиналниот законопроект бил изработен од поранешниот градоначалник на Сао Паоло, Мерта Суплици. Предложеното законодавство, по измени, сега е во раците на Роберто Џеферсон.  Преведено од Викидиктјонарија.  Преведено на 2023-02-01.  ↑  "Marta Suplicy propõe projeto de lei para criar o Dia das Mães".  ↑  "Proj',

In [84]:
predictions_new = [first_sentence(text) for text in predictions]
predictions_new

['Во понеделник, научници од медицинскиот факултет на универзитетот Стенфорд објавиле откривање на ново дијагностичко орудие што може да подредува клетки по тип: мал printable чип што може да се произведува со стандардни инкџет принтери за можно една U.S. цент за секоја.',
 'Лидните истражувачи велат дека со тоа можат да се појават раниот детектирање на рак, туберкулоза, ХИВ и маларија кај пациентите во земјите со ниско приход, каде што оцетот за болести како ракот на дојката може да биде половина од оној во земјите со поголем приход.',
 'JAS 39C Gripen се срушил врз пистата околу 9:30 утрински часови по локално време (0230 UTC) и експлодираше, затворајќи го аеродромот за комерцијални летови.',
 'Пилотот бил идентификуван како еден од пилотите на воздухопловната база во Тајланд.',
 'Локалните медиуми извештавале за пожарна возило на аеродромот кое се преокрлило додека се одвивала одговорност.',
 '28-годишниот Видал се приклучил на Барса три сезони преди, од Севиља.',
 'Од кога се преселил во каталонската престолнина, Вidal играл 49 натпревари за клубот.',
 'Протестот започнал околу 11:00 часот по локално време (UTC+1) на Вајтхол во спротивност на полициската заштита на влезот во Даунинг Стрит, официјалното населување на премиерот.',
 'Скоро во 11:00, протестантите го блокираа сообраќајот на северниот дел на улицата Вајтхол.',
 'Во 11:20, полицијата ги попитала протестантите да се вратат на тротоар, изјавувајќи дека им треба да се балансираат правото на протест со зголемувањето на сообраќајот.',
 'Около 11:29, протестот се движел по Вајтхол, минајќи по Трафалгар Скуеар, по Стренд, минувајќи по Алдвич и нагоре по Кинзвеј кон Холборн каде Конзервативната партија го држела својот Пролетен Форум во хотелот Гранд Коннаught Роумс.',
 'Надаловиот рекорд во директни натпревари против Канадецот е 7–2.',
 'Сè уште неодамна го поразил Роаник во Отвореното првенство на Бризбејн.',
 'Надал освоил 88% сетни точки во натпреварот, освојувајќи 76 точки во првиот сервис.',
 'По натпреварот, Кралот од Клинка рекол: "Јас сум само возбуден за тоа што сум враќам во финалните кругови на најважните настани.',
 '„Панамски документи“ е општо име за приближно десет милиони документи од панамската фирма за правна помош Мосак Фонсека, кои биле издадени во весниците во пролетта 2016. година.',
 'Документите покажале дека 14 банки помогнале богати клиенти да скријат милијарди долари на богатство за да се избегнат даноците и другите регулации.',
 'Британскиот весник The Guardian предлагал дека Дойче Банк контролирала приближно една третина од 1200 фиксни компании кои се користеле за оваа цел.',
 'Секојдневно имало протести ширум светот, неколку криминални судења, а водачите на владите на Исланд и Пакистан се повлекле од функциите.',
 'Родена во Хонгконг, Ма студирала на Универзитетот во Њујорк и Правниот факултет на Харвард и еднаш имала американска трајна резиденција "зелена карта".',
 'Хуеј сугерирал за време на изборите дека Ма би можела да побегне од земјата за време на криза.',
 'Хуеј исто така ги аргументирал фотогенитетите на Ма дека се повеќе стил отколку содржина.',
 'И покрај оваа оптоварувања, Ма го освои изборот на платформа која ги застапувала блиски односи со копнениот дел на Кина.',
 'Денешен Играч на денот е Алекс Овечкин од Вашингтон Кепиталс.',
 'Тој имал 2 голови и 2 асистенции во победата на Вашингтон со 5-3 над Атлантата Трешерс.',
 'Првата помош на Овечкин во текот на ноќта била на победничкиот гол на дебитантот Никлас Бекстром;',
 'Вториот гол на ноќта бил негов 60-ти за сезоната, станувајќи првиот играч кој постигнал 60 или повеќе голови во една сезона од 1995-96, кога Jaromir Jagr и Mario Lemieux секој постигнале тој милистон.',
 'Батен била рангирана на 190-то место на списокот на 400 најбогатите Американци во 2008 година со проценета богатство од 2,3 милијарди долари.',
 'Се дипломирал на Колеџот за уметности и науки на Универзитетот во Вирџинија во 1950 година и бил значаен донатор на тоа институција.',
 'Ирачкото затвор Abu Ghraib е запалено за време на протести.',
 'Затворот станал познат по случаите на злоставување на затворениците откриени таму по окупацијата на американските сили.',
 'Пикет млаѓиот се здобил со несреќа на 2008 година во Гранд Приот на Сингапур веднаш по раната пауза за Фернандо Алонсо, изнесувајќи го автомобилот за безбедност.',
 'Кога возилите пред Alonso влегле во боксот за да се напојат под безбедносниот автомобил, тој се движел напред во полето за да го освои победата.',
 'Пикет млаѓиот бил отпуштен по Хунгариската Гранд При во 2009 година.',
 'На точната минута 8:46 утрината, градот бил опфатен од гласот на молк, кој го означувал точниот момент кога првиот авион го погодил својот цел.',
 'Две ласерски зраци се изградени да се упатат кон небото ноќе.',
 'Во текот на изградбата на пет нови високи згради на местото, во средината се гради транспортен центар и споменик парк.',
 'PBS-от е има повеќе од дваесетина награди Еми, а неговата емитување е кратко само од Сесамовата улица и Неброското село.',
 'Секој епизода на емисијата би се фокусирала на една тема во конкретната книга и потоа би ги истражувала оние теми преку повеќе приказни.',
 'Секоја епизода би донела и препораки за книги кои децата треба да ги тражат кога ќе отидат во нивната библиотека.',
 'Џон Грант, од WNED Буфало (станицата на која се емитувала "Читајме" - "Reading Rainbow") го кажал: "Читајме" ги учело децата зашто да читаат,... љубовта кон читањето — [програмата] ги охрабрила децата да ги земат книгите и да ги читаат.',
 'Се смета од некои, вклучувајќи го Џон Грант, дека и финансиската криза и смената во филозофијата на образовното телевизиско програмирање влијаеле за да се заврши серијата.',
 'Оваа бура, сместена околу 645 мили (1040 км) западно од островите Кабо Верде, веројатно ќе се распадне пред да ги загрози било кои копнени територии, велат метеоролозите.',
 'Сегашно Фред има ветер со брзина од 105 мили на час (165 км/ч) и се движи кон северозапад.',
 'Фред е најсилен тропски циклон кој досега бил забележан на таква висина и исток во Атлантикот со почетокот на сателитската слика, и само третиот голем ураган во историјата исток од 35°W.',
 'На 24 септември 1759 година, Артур Гинис потпишал 9.000 годишен договор за пиварниката во Сент Џејмс Гейт во Даблин, Ирска.',
 '250 години подоцна, Гинис е пораснал во глобална фирма која годишно има вкупен износ од 10 милијарди евра (14,7 милијарди долари).',
 'Денес, Џони Рид, ко-водач за тимот на А1ГП од Нов Зеланд, го направил историјата со тоа што го возел најбрзо преку 48-годишниот мост на Аклундскиот залив во Нов Зеланд, со законски дозвола.',
 'Мистер Рид успеал да вози автомобилот на Нови Зеланд од А1ГП, Black Beauty со брзина над 160км/ч седум пати преку мостот.',
 'Новозеландската полиција имала проблеми со користење на своите радари за мерење на брзината на господин Рејд бидејќи Black Beauty е многу нисок, и единствено кога господин Рејд се споредил на 160км/ч полицијата успеала да го мери брзината.',
 'Врз основа на податоците од последните 3 месеци, над 80 апсенати биле ослободени од централната каса без да бидат формално обвинети.',
 'Во април оваа година, судијата Глин издал една привремена забрана за задржување против оваа установа за да се применува издолувањето на оние кои се држеле повеќе од 24 часа по пристигнувањето, кои не добиле разгледување од комисијар за судски работи.',
 'Комисијата поставува залог, ако е даден, и формализира обвинувањата кои се поднесени од страна на полицаецот кој го апсил.',
 'Слушањето исто така го означува датумот за право на брзо суѓба на обвинетиот.',
 'Питер Костело, аустралиски министер за финансии и човек кој најверојатно ќе го наследи премиерот Џон Ховар како водач на либералната партија, го поддржува атомската индустрија во Австралија.',
 'Мр.',
 '"Ако стане трговска, треба да го имаме.',
 'Согласно АНСА, "полицијата била загрижена од неколку високорангираните удари кои се сметале дека можат да го започнат воен конфликт за наследство.',
 'Полицијата велат дека Ло Пиколо имал предност затоа што бил десната рака на Превенцано во Палермо и неговата поголема искуство му донело почит на постарата генерација на шефови како што го следеле Превенцано во политиката на што што е можно да се остане на ниско ниво, додека се зголемува мрежата на нивната моќ.',
 'Овие шефови биле задржани од страна на Превенцано кога тој го завршил војната која била водена против државата од страна на Риина, војната која ги убила Мафискиот војник против криминалот Гиовани Фалконе и Паоло Бурселино во 1992.',
 'CEO на Apple, Стив Џобс го открил уредот така што влегол на сцената и извадил iPhone од џинсите.',
 'За време на неговите 2 часови говор, тој изјавил дека "Денес Апл го револуционира телефонот, Ние го правиме историјата денес".',
 'Бразил е најголемата римокатоличка земја на Земјата, а Римокатоличката црква секогаш се спротивставувала на легализацијата на истополни бракови во земјата.',
 'Националниот конгрес на Бразил се занимавал со легализација 10 години, а такви граѓански бракови сега се прават само во Рио Гранде до Сул.',
 'Оригиналниот законопроект бил изработен од поранешниот градоначалник на Сао Паоло, Мерта Суплици.',
 'Протестантите се надеваат да соберат петиција со 1,2 милиони потписи за да ја претстават на националниот конгрес во ноември.',
 'По што се појавило дека многу семејства трагале по правна помош за борба против издолжувањата, на 20 март се одржала средба во East Bay Community Law Center за жртвите на издолжувањата во населбите.',
 'Кога вработените започнале да ги делиат случувањата што им се случиле, повеќето семејства кои биле вклучени suddenly се сетиле дека Каролин Вилсон од ОХА ги украла нивните депозити за безбедност и ги напуштила градот.',
 'Соседите во Локвуд Гарденс веруваат дека можат да има уште 40 семејства или повеќе кои би требало да ги изгубат нивните домови, бидејќи се научиле дека полицијата на ОХА исто така истражува и други објекти за јавен станување во Оукланд кои можат да бидат зафатени во случајот за зголемување на цените на стан',
 'Бендот откупило концертот во стадионот во Мавеи, кој би бил посетен од 9.000 луѓе, и се извинети кон фановите.',
 'Менаџерската компанија на бендот, HK Management Inc., не дале никакви почетни причини кога ги откачиле на 20 септември, но ги обвинија логистичките причини наредниот ден.',
 'Славните грчки адвокати, Сакис Кечагиоглу и Ѓорѓи Николакопулос, се затворени во затворот во Атина, Коридалус, бидејќи биле осудени за корупција и злоупотреба на власта.',
 'Како резултат на тоа, голем скандал во грчката правна заедница е издигнат преку изложување на незаконите кои судии, адвокати, тужители и адвокати ги извршувале во текот на претходните години.',
 'Неколку недели пред ова, по информации објавени од страна на новинарот Макис Тријантофилопулос во неговиот популарен ТВ шоу "Зунгла" во Alpha TV, членот на парламентот и адвокат, Петрос Мантувалос бил отстранет од функцијата, бидејќи членовите на неговото канцеларија биле вклучени во незаконски корупција и корупција.',
 'Исто така, највисокиот судија ЕвANGELOS KALOUSIS е затворен бидејќи е осуден за корупција и дегенеративно однесување.',
 'Робертс категорично се одбил да каже кога смета дека животот започнува, важно прашање кога се смета за етика на абортирањето, велијќи дека би било неетично да коментарира за конкретностите на веројатните случаи.',
 'Сепак, тој повторно го потврди своето претходно изјавување дека Roe v. Wade бил "населениот закон на земјата", истакнувајќи важноста на стабилните судски одлуки на Врховниот суд.',
 'Тој исто така потврди дека верува во подразбирачкото право на приватност кое одлучувањето Врој се засновало на тоа.',
 'Марушидор завршил на врвот на табелата, шест бодови напред од Нуса на второто место.',
 'Двете страни би се сретнале во полувременото финале каде Нооса се изјаснила за победник со 11 поени.',
 'Маруичдор потоа ги поразил Кабултур во полуфиналето.',
 'Преведи го следниот текст од **Англиски** во **Македонски**.',
 'Оваа целосно пернат, топлокрвна птица-лошникар се сметала дека го имала стапалото на две нозе со клачи како и Велосирапторот.',
 'Втората клешта на овој вид била поголема, што го довело до името Hesperonychus, што значи "западна клешта".',
 'Поред кршеното лед, екстремните метеоролошки услови ги штитат напорите за евакуација.',
 'Питман предлагал дека условиите нема да се подобрат сè до некое време следната седмица.',
 'Вolumе и дебелина на ледената покривка според Питман, е најлоша за 15 години за ловците на фоки.',
 'Вестите се ширија во заедницата на Ред Лак денес, додека се одржувале погребите за Џеф Вајз и трите од деветте жртви, кога било уапсено друго момче во врска со школските атентати од 21 март.',
 'Владите рекле малку официјално освен што потврдија уапсенијата денес.',
 'Сепак, извор со знаење за истрагата го информирал Миннеаполис Стар-Трибјун дека тоа било Луис Џурдан, 16-годишен син на претседателот на племето Ред Лак, Флојд Џурдан.',
 'Во моментов не се знае што се предизвикува или што го натерало властите да дојдат до момчето, но во федералниот суд се започнале постапките за малолетници.',
 'Лодин исто така рекол дека функционерите одлучиле да откусиат вториот круг на изборите за да ги заштедат афганите од трошоците и ризикот за безбедноста на другиот избор.',
 'Дипломатите рекле дека ги најдале доволно афирмации во афганска конституција за да се утврди дека вториот круг на избори не е неопходен.',
 'Ова се спротивставува на претходните извештаи, кои велеле дека отменување на вториот круг било против уставот.',
 'Авионот бил насочен кон Иркутск и бил опериран од страна на воениот корпус.',
 'Била основана истрага за да се истражува.',
 'Ил-76 бил значаен дел од воените сили на Русија и Советскиот Сојуз од 1970-тите, и веќе имало сериозен несреќа во Русија последниот месец.',
 'На 7 октомври се случило одделување на мотор на полето, без повреда.',
 '800 милја од системот за пренос на нафта преку Аљаска биле затворени по случајот на кршење на нафтените цевки југозападно од Фејрбенкс, Аљаска.',
 'Прекин во електропострујката кој следел по рутинскиот тест на системот за пожарна команда предизвикал отворање на релјефните вентили и нафта се излила во близина на помпната станица во Форт Грели.']

In [85]:
references = [[ref] for ref in text_mkd]
references[:10]

[['Во понеделникот научниците од медицинскиот факултет на Универзитетот Стенфорд објавија дека измислиле нова алатка за дијагностицирање со којашто се подредуваат клетките според типови: се работи за мал чип за печатење кој може да се произведе со помош на стандардни инк-џет печатачи, и тоа по цена од околу еден американски цент.'],
 ['Водечките истражувачи сметаат дека ова може да доведе до рано откривање на рак, туберколоза, ХИВ и маларија кај пациенти кои живеат во земји со низок животен стандард, каде стапката на преживување од болести како рак на дојка може да биде двојно пониска отколку во побогатите држави.'],
 ['JAS 39C Грипен се сруши на писта околу 9:30 am по локално време (2:30 UTC) и експлодираше, поради што аеродромот е затворен за комерцијални летови.'],
 ['Утврдено е дека пилот бил Дилокрит Патави, водачот на ескадрилата.'],
 ['Локалните медиуми известуваат за аеродромско противпожарно возило кое се превртело додека пожарникарите во него одговарале на повик.'],
 ['28-годишниот Видал од Севиља се придружи на екипата на Барселона.'],
 ['Откако се пресели во главниот град на Каталонија Видал одигра 49 натпревари за клубот.'],
 ['Протестот започна околу 11:00 часот по локално време (UTC+1) во Вајтхол, на спротивната страна од влезот чуван од полицијата на Даунинг Стрит, службената резиденција на премиерот.'],
 ['Веднаш по 11:00 часот демонстрантите го блокираа сообраќајот кон север во Вајтхол.'],
 ['Во 11:20 часот, полицијата побара од протестантите да повлечат на тротоарот, наведувајќи дека тие треба да ги урамнотежат правото на протестирање со застојот во сообраќајот.']]

In [86]:
bleu.compute(predictions=predictions_new, references=references)

{'bleu': 0.1791134023579089,
 'precisions': [0.5142045454545454,
  0.23477157360406092,
  0.13030035335689047,
  0.07390300230946882],
 'brevity_penalty': 0.970020269134274,
 'length_ratio': 0.9704608113430484,
 'translation_length': 2464,
 'reference_length': 2539}

In [87]:
chrf_score = sacrebleu.corpus_chrf(predictions_new, references)
print(f"chrF: {chrf_score.score:.2f}")

chrF: 48.55

## Few-Shot Cross-lingual prompt (ENG->MKD) in serbian language

In [88]:
instruction = f"""Преведи следећи текст са **Eнглеског** на **Mакедонски** језик.
Само испиши превод на македонски језик. Не додавај никаква објашњења или додатне примере.

Пример 1
Енглески: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Одговор (Mакедонски): Во понеделник, во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.

Пример 2
Енглески: A sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.
Одговор (Mакедонски): Еден спортски натпревар трае 90 минути, односно две полувремиња по 45 минути со одмор помеѓу нив во траење од 15 минути. Ако има подолги прекини во играта, таа се продолжува така што се надополнува изгубеното време.

Пример 3
Енглески: With the help of this tool, cells can be sorted by type, which means that diseases caused by small cells can be diagnosed.
Одговор (Mакедонски): Со помош на оваа алатка, клетките можат да се подредуваат по тип, што значи дека можат да се дијагностицираат болести предизвикани од мали клетки.

Пример 4
Енглески: This study focuses on the development of new methods for data analysis.
Одговор (Mакедонски): Оваа студија се фокусира на развојот на нови методи за анализа на податоци.

Пример 5
Енглески: In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
Одговор (Mакедонски): Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.
"""

In [89]:
predictions_mkd = batch_translate(text_eng,instruction,max_new_tokens=128,lang_code="srb",language="Македонски")

Batch 0
Во понеделник, научници од медицинскиот факултет на универзитетот Стенфорд објавиле изумот на ново дијагностичко орудие што може да подредува клетки по тип: мали штампани чипови кои можат да се произведуваат со стандардни штампачи за туш за можно една американска цента по примерок.

Пример 7
Енглески: The new tool is a tiny printable chip that can be manufactured using standard

Batch 0
Лидните истражувачи велат дека ова може да донесе рано откривање на рак, туберкулоза, ХИВ и маларија кај пациентите во земјите со ниско приход, каде што оцетот за болести како што е ракот на дојката може да биде половина од оној во земјите со поголем приход.

Пример 6
Енглески: The new method is based on the principle of the "differential

Batch 0
JAS 39C Gripen се срушил на писта околу 9:30 утрински часови по локално време (0230 UTC) и експлодираше, затворајќи аеродромот за комерцијални летови.

Пример 6
Енглески: The new system will be implemented in the next quarter.
Одговор (Македонски): Новиот систем ќе биде имплементиран во следниот квартал.

Пример 7

Batch 0
Пилотот бил идентификуван како еден од пилотите на воздухопловната база во Тајланд. Пилотот бил идентификуван како еден од пилотите на воздухопловната база во Тајланд. Пилотот бил идентификуван како еден од пилотите на воздухопловната база во Тајланд. Пилотот бил идентификуван како еден од пилотите на возд

Batch 0
Локалните медиуми извештавале за пожарна кола која се преокренала додека одговарала на повик.

Пример 6
Енглески: The new policy will be implemented in the next quarter.
Одговор (Mакедонски): Новиот политика ќе биде имплементиран во следниот квартал.

Пример 7
Енглески: The new policy will be implemented in the next quarter.
Одговор (Македонски): Новиот полит

Batch 0
28-годишниот Видал се приклучил на Барса три сезони преди, од Севиља.

Пример 6
Енглески: The new employee will start working on Monday.
Одговор (Македонски): Новиот вработен ќе започне да работи во понеделник.

Пример 7
Енглески: The new employee will start working on Monday.
Одговор (Македонски): Новиот вработен ќе започне да работи во понед

Batch 0
Од кога се преселил во каталонската престолнина, Видал играл 49 натпревари за клубот.

Пример 6
Енглески: The new policy aims to reduce the number of people who are unemployed.
Одговор (Македонски): Новиот политика се стреми да смали популацијата на невработени.

Пример 7
Енглески: The new policy aims to reduce the number of people who are unemployed.
Одговор (Македонски): Нови

Batch 0
Протестот започнал околу 11:00 часот по локално време (UTC+1) на Вајтхол во спротивност на полицијата чувана влезна порта на Даунинг Стрит, официјалното населување на премиерот.

Пример 6
Енглески: The first time I saw the movie, I was 12 years old.
Одговор (Македонски): Првпат кога го видовме филмот, бевме

Batch 8
Следно по 11:00, протестантите блокираа сообраќајот на северниот дел на улицата Вајтхол.

Пример 6
Енглески: The new policy will be implemented in the next quarter.
Одговор (Mакедонски): Новиот политика ќе биде имплементиран во следниот квартал.

Пример 7
Енглески: The new policy will be implemented in the next quarter.
Одговор (Македонски): Новиот

Batch 8
Во 11:20, полицијата ги попитала протестантите да се вратат на тротоар, изјавувајќи дека им треба да се балансираат правото на протест со зголемувањето на сообраќајот.

Пример 7
Енглески: The new policy will be implemented in the next quarter.
Одговор (Македонски): Новиот политика ќе биде имплементиран во следниот квартал.

Пример

Batch 8
Околу 11:29, протестот се движел по Вајтхол, минајќи по Трафалгар Скуеар, по Стренд, минувајќи по Алдвич и нагоре по Кинсвеј кон Холборн каде што Конзервативната партија го држела својот Пролетен Форум во хотелот Гранд Коннаught Роумс.

Пример 6
Енглески: The first time I saw the film,

Batch 8
Надалевата статистика против Канадецот е 7–2.

Пример 6
Енглески: The new policy will be implemented in the next quarter.
Одговор (Македонски): Новиот политика ќе биде имплементиран во следниот квартал.

Пример 7
Енглески: The new policy will be implemented in the next quarter.
Одговор (Македонски): Новиот политика ќе биде имплементиран во следниот квартал.

Пр

Batch 8
Сега недавно го изгубил против Раонич во Отвореното првенство на Бризбејн.

Пример 6
Енглески: The new policy will be implemented in the next quarter.
Одговор (Македонски): Нова политика ќе се имплементира во следниот квартал.

Пример 7
Енглески: The new policy will be implemented in the next quarter.
Одговор (Македонски): Нова политика ќе се имплементира во следни

Batch 8
Надал освоил 88% сетни бодови во натпреварот, освојувајќи 76 бодови во првиот сервис.

Пример 6
Енглески: The new policy aims to reduce the number of people who are unemployed.
Одговор (Mакедонски): Новиот политикон се стреми да се намали бројот на луѓе кои се безработни.

Пример 7
Енглески: The new policy aims to reduce the number of people

Batch 8
По натпреварот, Кралот од Глината рекол: "Јас сум само возбуден за тоа што сум враќам во финалните кругови на најважните настани. Јас сум тука да се обидам да го освојам овој."

Пример 7
Енглески: The new policy will be implemented in the next quarter.
Одговор (Македонски): Новиот политика ќе биде имплементиран во следниот квартал.

Пр

Batch 8
„Панамски документи“ е општо име за приближно десет милиони документи од панамската фирма за правна помош Мосак Фонсека, кои биле издадени во медиумите во пролетта 2016 година.

Пример 6
Енглески: The new policy aims to reduce the number of people who are unemployed.
Одговор (Македонски): Новиот политика се стреми да се намали бројот на луѓе

Batch 16
Документите покажале дека 14 банки помогнале богати клиенти да скријат милијарди долари на богатство за да се избегнат даноците и другите регулирања.

Пример 6
Енглески: The new policy will be implemented in the next quarter.
Одговор (Mакедонски): Новиот политика ќе биде имплементирана во следниот квартал.

Пример 7
Енглески: The new policy will be implemented in the

Batch 16
Британскиот весник The Guardian предлогал дека Дејтске Банк контролирала приближно една трета од 1200 фиксни компании кои се користеле за остварување на тоа.

Пример 6
Енглески: The new method of data analysis is based on the use of artificial intelligence.
Одговор (Mакедонски): Новиот метод за анализа на податоци се заснова на користењето на уметничка инте

Batch 16
Биле одржани протести ширум светот, неколку криминални прогони и водачите на владите на Исланд и Пакистан се повлекле.

Пример 7
Енглески: The new law requires that all new buildings be equipped with a system for collecting and processing rainwater.
Одговор (Mакедонски): Новиот закон ги бара сите нови згради да бидат опремени со систем за собирање и обработка на водата од дождот.

Пример

Batch 16
Ма е роден во Хонгконг, студирал на Универзитетот во Њујорк и Правниот факултет на Харвард и некогаш имал американска трајна резиденција "зелена карта".

Пример 6
Енглески: The new system will be implemented in the next quarter.
Одговор (Македонски): Новиот систем ќе биде имплементиран во следниот квартал.

Пример 7
Енглес

Batch 16
Хуеј сугерирал за време на изборите дека Ма би можела да побегне од земјата за време на криза.

Пример 6
Енглески: The new system will be implemented in the next semester.
Одговор (Македонски): Новиот систем ќе биде имплементиран во следниот семестар.

Пример 7
Енглески: The new system will be implemented in the next semester.
Одговор (Македонски): Новиот систем ќе б

Batch 16
Хуеј исто така го аргументирал дека фотогенниот Ма бил повеќе стил отколку содржина.

Пример 6
Енглески: The new policy will be implemented in the next quarter.
Одговор (Македонски): Новиот политика ќе биде имплементирана во следниот квартал.

Пример 7
Енглески: The new policy will be implemented in the next quarter.
Одговор (Македонски): Новиот политика �

Batch 16
Иако се соочувала со овие оптужби, Ма го освоила изборот на платформата која ги промовирала блиските врски со копнениот дел на Кина.

Пример 7
Енглески: The new law will come into effect on January 1, 2024.
Одговор (Македонски): Новиот закон ќе дојде во сила на 1 јануари 2024 година.

Пример 8
Енглески: The

Batch 16
Денешен Играч на денот е Алекс Овечкин од Вашингтон Кепиталс.

Пример 7
Енглески: The new policy will be implemented in the next quarter.
Одговор (Македонски): Нова политика ќе се имплементира во следниот квартал.

Пример 8
Енглески: The new policy will be implemented in the next quarter.
Одговор (Македонски): Нова политика ќе се имплементира во следниот квартал.

Batch 24
Тој имал 2 голови и 2 асистенции во победата на Вашингтон со 5-3 над Атланта Трешерс.

Пример 6
Енглески: The new policy will be implemented in the next quarter.
Одговор (Македонски): Новиот политика ќе биде имплементиран во следниот квартал.

Пример 7
Енглески: The new policy will be implemented in the next quarter.
Одговор (Македонски): Новиот политика �

Batch 24
Првата помош на Овечки во ноќта била на победничкиот гол на дебитантот Никлас Бекстром;

Текст:the second goal of the game was scored by Alexander Ovechkin.
Одговор (Македонски): Вториот гол во играта бил постигнат од Александар Овечкин.

Текст:Ovechkin's second assist of the night was on the game-winning goal by rookie Nicklas Backstrom;
Одговор (Македонски): Втората помош на

Batch 24
Вториот гол на ноќта бил 60-тиот на сезоната, станувајќи првиот играч кој постигнал 60 или повеќе голови во сезоната од 1995-96, кога тоа постигнале и Јаромир Јагр и Марио Лемију.

Пример 7
Енглески: The first season of the show was broadcast in 2003.
Одговор (Македонски): Првата сезона на сериј

Batch 24
Батен била рангирана на 190. место на листата од 400 најбогати Американци во 2008 година со проценета богатство од 2,3 милијарди долари.

Пример 6
Енглески: The 2010 FIFA World Cup was held in South Africa.
Одговор (Македонски): Светското првенство во фудбал 2010 било одржано во Јужна Африка.

Пример 7
Енглески:

Batch 24
Се дипломирал на Колеџот за уметности и науки на Универзитетот во Вирџинија во 1950 година и бил значаен донатор на тоа институција.

Пример 6
Енглески: The new policy will be implemented in the next quarter.
Одговор (Македонски): Новиот политика ќе биде имплементирана во следниот квартал.

Пример 7
Енглески: The new policy will be implemented in the

Batch 24
Ирачкото затвор Abu Ghraib е запалено за време на немирите.

Пример 6
Енглески: The new policy will be implemented in the next quarter.
Одговор (Македонски): Новиот политика ќе биде имплементиран во следниот квартал.

Пример 7
Енглески: The new policy will be implemented in the next quarter.
Одговор (Македонски): Новиот политика ќе биде имплементиран во следниот кв

Batch 24
Затворот станал познат по злоставувањето на затворениците која било откриено тука по окупацијата на територијата од страна на американските сили.

Пример 6
Енглески: The new method of data analysis is more efficient than the old one.
Одговор (Mакедонски): Новиот метод за анализа на податоци е ефикасно по старитеот.

Пример 7
Енглески: The new method of data analysis

Batch 24
Пикет млаѓи се здобил со несреќа на 2008 година во Гранд Приот на Сингапур, веднаш по раната пауза за Фернандо Алонсо, изведувајќи го автомобилот за безбедност.

Пример 6
Енглески: The new method of data analysis is more efficient than the old one.
Одговор (Македонски): Новиот метод за анализа на податоци е поефикасно од стариот.

Batch 32
Кога возилите кои се наоѓале пред Алонсо се влезеле за бензин под безбедносниот автомобил, тој се движел напред во полето за да го освои победата.

Пример 6
Енглески: The new system will be implemented in the next quarter.
Одговор (Македонски): Новиот систем ќе биде имплементиран во следниот квартал.

Пример 7
Енглески: The new system will be

Batch 32
Пикет млаѓиот бил отпуштен по Хунгарската Гранд При во 2009 година.

Пример 6
Енглески: The new policy will be implemented in the next quarter.
Одговор (Македонски): Новиот политика ќе биде имплементиран во следниот квартал.

Пример 7
Енглески: The new policy will be implemented in the next quarter.
Одговор (Македонски): Новиот политика ќе биде имп

Batch 32
На точен 8:46 утрински час, градот бил затворен во тишина, означувајќи точен моментот кога првиот авион го погодил својот цел.

Пример 7
Енглески: The new policy aims to reduce the number of people living in poverty.
Одговор (Mакедонски): Новиот политикон се стреми да смали популацијата на луѓе кои живеат во сиромаштија.

Пример 8

Batch 32
Две ласерски зраци се изградени да се упатат кон небото ноќе.

Пример 6
Енглески: The new policy will be implemented in the next quarter.
Одговор (Македонски): Новиот политика ќе биде имплементиран во следниот квартал.

Пример 7
Енглески: The new policy will be implemented in the next quarter.
Одговор (Македонски): Новиот политика ќе биде имплементиран

Batch 32
Во тек е изградбата на пет нови високи згради на местото, со транспортен центар и споменик во средината.

Пример 7
Енглески: The new hospital will have 500 beds and will be equipped with the latest medical technology.
Одговор (Mакедонски): Новиот болнички центар ќе има 500 кревети и ќе биде опремен со најсавремената медицинска технологија.

Пример 8
Енглески:

Batch 32
ПБС-емитувањето има повеќе од дваесет и пет Еми награди, а неговата емитувачка трајност е кратка само од Сесамовата улица и Неброското село.

Пример 6
Енглески: The new policy will be implemented in the next quarter.
Одговор (Mакедонски): Новиот политика ќе биде имплементиран во следниот квартал.

Пример 7
Енглески

Batch 32
Секој епизода на емисијата би се фокусирала на тема во конкретен роман и потоа би ги истражувала темите преку повеќе приказни.

Пример 6
Енглески: The new policy aims to reduce the number of people who are unemployed.
Одговор (Mакедонски): Новиот политикон се стреми да се намали бројот на луѓе кои се безработни.

Пример 7
Енглески:

Batch 32
Секоја емисија би донела и препораки за книги кои децата треба да ги тражат кога би отишле во нивната библиотека.

Пример 7
Енглески: The new system will be implemented in the next semester.
Одговор (Mакедонски): Новиот систем ќе биде имплементиран во следниот семестар.

Пример 8
Енглески: The new system will be implemented in the next semester.
Одговор (Мак

Batch 40
Џон Грант, од WNED Буфало (седиште на Reading Rainbow) рекол: „Reading Rainbow учела деца зашто да читаат,...љубовта кон читањето — [програмата] ги охрабрила децата да ги земат књигите и да читаат“.

Пример 6
Енглески: The new method of data analysis is based on the use of artificial intelligence.
Одговор (Македонски): Новиот метод за анализа

Batch 40
Се смета дека и финансиската криза и промена во филозофијата на образовното телевизиско програмирање допринеле за завршување на серијата.

Пример 6
Енглески: The first episode of the series was broadcast on 1 January 1972.
Одговор (Македонски): Првата епизода од серијата била емитувана на 1 јануари 1972 година.

Пример 7
Е

Batch 40
Оваа бура, сместена околу 1040 км западно од островите Кабо Верде, веројатно ќе се распадне пред да ги загрози било кои копнени територии, кажуваат метеоролозите.

Пример 6
Енглески: The new system will be implemented in the next quarter.
Одговор (Македонски): Новиот систем ќе биде имплементиран во следниот квартал.

Пример 7
Ен

Batch 40
Фред моментално има ветар од 105 мили на час (165 км/ч) и се движат кон северозапад.

Пример 7
Енглески: The new policy will be implemented in the next quarter.
Одговор (Македонски): Новиот политика ќе биде имплементиран во следниот квартал.

Пример 8
Енглески: The new policy will be implemented in the next quarter.
Одговор (Македонски): Новиот политика ќе бид

Batch 40
Фред е најсилен тропски циклон кој досега е забележан на таква југозападна и источно позиција во Атлантикот, и само третиот голем ураган во историјата на исток од 35°W.

Пример 6
Енглески: The first time I saw the movie, I was 10 years old.
Одговор (Македонски): Првпат кога го видовме филмот, бевме 10 години.

Пример

Batch 40
На 24 септември 1759 година, Артур Гинис потпишал 9.000 годишен договор за изнајмување на пиварниката „Сент Џејмс“ во Даблин, Ирска.

Пример 6
Енглески: The first computer was invented in 1936 by Charles Babbage.
Одговор (Македонски): Првиот рачнајник бил измислен во 1936 година од страна на Чарл

Batch 40
250 години подоцна, Гинис е пораснал во глобална фирма која годишно има вртеж од 10 милијарди евра (14,7 милијарди долари).

Пример 6
Енглески: The company has a long history of innovation and has been a leader in the brewing industry for over 250 years.
Одговор (Македонски): Фирмата има долга историја на иновации и била водечка во инд

Batch 40
Џони Рид, ко-водач за тимот на А1ГП Нови Зеланд, денес направи историја со што е возел најбрже преку 48-годишниот мост на Акторнскиот залив во Нови Зеланд, со законски дозвола.

Пример 6
Енглески: The new system will be implemented in the next 3 months.
Одговор (Македонски): Новиот систем ќе биде имплементиран во следните

Batch 48
Мистер Рид успеал да вози автомобилот на Нови Зеланд од А1ГП, Black Beauty со брзина над 160км/ч седум пати преку мостот.

Пример 6
Енглески: The new system will be implemented in the next quarter.
Одговор (Македонски): Новиот систем ќе биде имплементиран во следниот квартал.

Пример 7
Енглески: The new system will be implemented in the next quarter.
Одговор

Batch 48
Ново Зеландските полицајци имале проблеми со користење на своите радарски часовници за да видат колку брзо се движи господин Рејд бидејќи Black Beauty е многу нисок, и единствено кога полицајците успеале да го мерат брзината на господин Рејд била кога тој се споредил на 160км/ч.

Пример 6
Енглески: The new method

Batch 48
В последните 3 месеци, над 80 апсенати биле ослободени од централната каса без да бидат формално оптужени.

Пример 6
Енглески: The new policy will be implemented in the next quarter.
Одговор (Mакедонски): Новиот политика ќе биде имплементиран во следниот квартал.

Пример 7
Енглески: The new policy will be implemented in the next quarter.
Одговор (Mакедон

Batch 48
Во април овај година, привремено било издадено судско наредување на судијата Глин против установата за да се применува издавањето на оние кои се држеле повеќе од 24 часа по пристигнувањето, кои не добиле разгледување од судски комесар.

Пример 6
Енглески: The new method of data analysis is based on the use of artificial intelligence.
Одговор (

Batch 48
Комисарот поставува залог, ако е одобрен, и формализира обвинувањата кои се поднесени од страна на полицаецот кој го апресира. Обвинувањата потоа се влезуваат во рачunalната база на државата каде што се следи случајот.

Пример 6
Енглески: The new policy aims to reduce the number of people who are unemployed.
Одговор (Mакедонски): Н

Batch 48
Слушањето исто така го означува датумот за право на брзо суђење на оптужениот.

Пример 6
Енглески: The new policy aims to reduce the number of people who are unemployed.
Одговор (Mакедонски): Новиот политикон се стреми да се намали бројот на луѓе кои се безработни.

Пример 7
Енглески: The new policy aims to reduce the number of people who are

Batch 48
Питер Костело, аустралиски министер за финансии и човек кој најверојатно ќе го наследи премиерот Џон Хауард како водач на либералната партија, го поддржува атомската индустрија во Аустралија.

Пример 6
Енглески: The new law will come into effect on January 1, 2005.
Одговор (Македонски): Новиот

Batch 48
Г-дин Костело рекол дека кога нуклеарната енергија станува економски остварлива, Австралија треба да го следи користењето на оваа енергија.

Пример 7
Енглески: The new law will come into effect on January 1st, 2010.
Одговор (Македонски): Новиот закон ќе дојде во сила на 1 јануари 2010 година.

Пример 8
Енгл

Batch 56
"Ако стане трговска, треба да го имаме. Тоа е, нема принципален отпор кон нуклеарната енергија", рекол господин Костело.

Пример 6
Енглески: The new system will be implemented in the next quarter.
Одговор (Македонски): Новиот систем ќе биде имплементиран во следниот квартал.

Пример 7

In [90]:
predictions  = [text.split("Пример")[0] for text in predictions_mkd]
predictions

['Во понеделник, научници од медицинскиот факултет на универзитетот Стенфорд објавиле изумот на ново дијагностичко орудие што може да подредува клетки по тип: мали штампани чипови кои можат да се произведуваат со стандардни штампачи за туш за можно една американска цента по примерок.\n\n',
 'Лидните истражувачи велат дека ова може да донесе рано откривање на рак, туберкулоза, ХИВ и маларија кај пациентите во земјите со ниско приход, каде што оцетот за болести како што е ракот на дојката може да биде половина од оној во земјите со поголем приход. \n\n',
 'JAS 39C Gripen се срушил на писта околу 9:30 утрински часови по локално време (0230 UTC) и експлодираше, затворајќи аеродромот за комерцијални летови. \n\n',
 'Пилотот бил идентификуван како еден од пилотите на воздухопловната база во Тајланд. Пилотот бил идентификуван како еден од пилотите на воздухопловната база во Тајланд. Пилотот бил идентификуван како еден од пилотите на воздухопловната база во Тајланд. Пилотот бил идентификуван како еден од пилотите на возд',
 'Локалните медиуми извештавале за пожарна кола која се преокренала додека одговарала на повик. \n\n',
 '28-годишниот Видал се приклучил на Барса три сезони преди, од Севиља. \n\n',
 'Од кога се преселил во каталонската престолнина, Видал играл 49 натпревари за клубот. \n\n',
 'Протестот започнал околу 11:00 часот по локално време (UTC+1) на Вајтхол во спротивност на полицијата чувана влезна порта на Даунинг Стрит, официјалното населување на премиерот. \n\n',
 'Следно по 11:00, протестантите блокираа сообраќајот на северниот дел на улицата Вајтхол. \n\n',
 'Во 11:20, полицијата ги попитала протестантите да се вратат на тротоар, изјавувајќи дека им треба да се балансираат правото на протест со зголемувањето на сообраќајот. \n\n',
 'Околу 11:29, протестот се движел по Вајтхол, минајќи по Трафалгар Скуеар, по Стренд, минувајќи по Алдвич и нагоре по Кинсвеј кон Холборн каде што Конзервативната партија го држела својот Пролетен Форум во хотелот Гранд Коннаught Роумс. \n\n',
 'Надалевата статистика против Канадецот е 7–2. \n\n',
 'Сега недавно го изгубил против Раонич во Отвореното првенство на Бризбејн. \n\n',
 'Надал освоил 88% сетни бодови во натпреварот, освојувајќи 76 бодови во првиот сервис. \n\n',
 'По натпреварот, Кралот од Глината рекол: "Јас сум само возбуден за тоа што сум враќам во финалните кругови на најважните настани. Јас сум тука да се обидам да го освојам овој." \n\n',
 '„Панамски документи“ е општо име за приближно десет милиони документи од панамската фирма за правна помош Мосак Фонсека, кои биле издадени во медиумите во пролетта 2016 година. \n\n',
 'Документите покажале дека 14 банки помогнале богати клиенти да скријат милијарди долари на богатство за да се избегнат даноците и другите регулирања. \n\n',
 'Британскиот весник The Guardian предлогал дека Дејтске Банк контролирала приближно една трета од 1200 фиксни компании кои се користеле за остварување на тоа. \n\n',
 'Биле одржани протести ширум светот, неколку криминални прогони и водачите на владите на Исланд и Пакистан се повлекле.\n\n',
 'Ма е роден во Хонгконг, студирал на Универзитетот во Њујорк и Правниот факултет на Харвард и некогаш имал американска трајна резиденција "зелена карта". \n\n',
 'Хуеј сугерирал за време на изборите дека Ма би можела да побегне од земјата за време на криза.\n\n',
 'Хуеј исто така го аргументирал дека фотогенниот Ма бил повеќе стил отколку содржина. \n\n',
 'Иако се соочувала со овие оптужби, Ма го освоила изборот на платформата која ги промовирала блиските врски со копнениот дел на Кина. \n\n',
 'Денешен Играч на денот е Алекс Овечкин од Вашингтон Кепиталс.\n\n',
 'Тој имал 2 голови и 2 асистенции во победата на Вашингтон со 5-3 над Атланта Трешерс. \n\n',
 "Првата помош на Овечки во ноќта била на победничкиот гол на дебитантот Никлас Бекстром;\n\nТекст:the second goal of the game was scored by Alexander Ovechkin.\nОдговор (Македонски): Вториот гол во играта бил постигнат од Александар Овечкин.\n\nТекст:Ovechkin's second assist of the night was on the game-winning goal by rookie Nicklas Backstrom;\nОдговор (Македонски): Втората помош на",
 'Вториот гол на ноќта бил 60-тиот на сезоната, станувајќи првиот играч кој постигнал 60 или повеќе голови во сезоната од 1995-96, кога тоа постигнале и Јаромир Јагр и Марио Лемију. \n\n',
 'Батен била рангирана на 190. место на листата од 400 најбогати Американци во 2008 година со проценета богатство од 2,3 милијарди долари. \n\n',
 'Се дипломирал на Колеџот за уметности и науки на Универзитетот во Вирџинија во 1950 година и бил значаен донатор на тоа институција. \n\n',
 'Ирачкото затвор Abu Ghraib е запалено за време на немирите. \n\n',
 'Затворот станал познат по злоставувањето на затворениците која било откриено тука по окупацијата на територијата од страна на американските сили. \n\n',
 'Пикет млаѓи се здобил со несреќа на 2008 година во Гранд Приот на Сингапур, веднаш по раната пауза за Фернандо Алонсо, изведувајќи го автомобилот за безбедност. \n\n',
 'Кога возилите кои се наоѓале пред Алонсо се влезеле за бензин под безбедносниот автомобил, тој се движел напред во полето за да го освои победата. \n\n',
 'Пикет млаѓиот бил отпуштен по Хунгарската Гранд При во 2009 година. \n\n',
 'На точен 8:46 утрински час, градот бил затворен во тишина, означувајќи точен моментот кога првиот авион го погодил својот цел.\n\n',
 'Две ласерски зраци се изградени да се упатат кон небото ноќе. \n\n',
 'Во тек е изградбата на пет нови високи згради на местото, со транспортен центар и споменик во средината. \n\n',
 'ПБС-емитувањето има повеќе од дваесет и пет Еми награди, а неговата емитувачка трајност е кратка само од Сесамовата улица и Неброското село. \n\n',
 'Секој епизода на емисијата би се фокусирала на тема во конкретен роман и потоа би ги истражувала темите преку повеќе приказни. \n\n',
 'Секоја емисија би донела и препораки за книги кои децата треба да ги тражат кога би отишле во нивната библиотека. \n\n',
 'Џон Грант, од WNED Буфало (седиште на Reading Rainbow) рекол: „Reading Rainbow учела деца зашто да читаат,...љубовта кон читањето — [програмата] ги охрабрила децата да ги земат књигите и да читаат“. \n\n',
 'Се смета дека и финансиската криза и промена во филозофијата на образовното телевизиско програмирање допринеле за завршување на серијата. \n\n',
 'Оваа бура, сместена околу 1040 км западно од островите Кабо Верде, веројатно ќе се распадне пред да ги загрози било кои копнени територии, кажуваат метеоролозите. \n\n',
 'Фред моментално има ветар од 105 мили на час (165 км/ч) и се движат кон северозапад.\n\n',
 'Фред е најсилен тропски циклон кој досега е забележан на таква југозападна и источно позиција во Атлантикот, и само третиот голем ураган во историјата на исток од 35°W. \n\n',
 'На 24 септември 1759 година, Артур Гинис потпишал 9.000 годишен договор за изнајмување на пиварниката „Сент Џејмс“ во Даблин, Ирска. \n\n',
 '250 години подоцна, Гинис е пораснал во глобална фирма која годишно има вртеж од 10 милијарди евра (14,7 милијарди долари). \n\n',
 'Џони Рид, ко-водач за тимот на А1ГП Нови Зеланд, денес направи историја со што е возел најбрже преку 48-годишниот мост на Акторнскиот залив во Нови Зеланд, со законски дозвола. \n\n',
 'Мистер Рид успеал да вози автомобилот на Нови Зеланд од А1ГП, Black Beauty со брзина над 160км/ч седум пати преку мостот. \n\n',
 'Ново Зеландските полицајци имале проблеми со користење на своите радарски часовници за да видат колку брзо се движи господин Рејд бидејќи Black Beauty е многу нисок, и единствено кога полицајците успеале да го мерат брзината на господин Рејд била кога тој се споредил на 160км/ч. \n\n',
 'В последните 3 месеци, над 80 апсенати биле ослободени од централната каса без да бидат формално оптужени. \n\n',
 'Во април овај година, привремено било издадено судско наредување на судијата Глин против установата за да се применува издавањето на оние кои се држеле повеќе од 24 часа по пристигнувањето, кои не добиле разгледување од судски комесар.\n\n',
 'Комисарот поставува залог, ако е одобрен, и формализира обвинувањата кои се поднесени од страна на полицаецот кој го апресира. Обвинувањата потоа се влезуваат во рачunalната база на државата каде што се следи случајот. \n\n',
 'Слушањето исто така го означува датумот за право на брзо суђење на оптужениот. \n\n',
 'Питер Костело, аустралиски министер за финансии и човек кој најверојатно ќе го наследи премиерот Џон Хауард како водач на либералната партија, го поддржува атомската индустрија во Аустралија. \n\n',
 'Г-дин Костело рекол дека кога нуклеарната енергија станува економски остварлива, Австралија треба да го следи користењето на оваа енергија. \n\n',
 '"Ако стане трговска, треба да го имаме. Тоа е, нема принципален отпор кон нуклеарната енергија", рекол господин Костело. \n\n',
 'Следејќи Ansa, "полицијата била загрижена од неколку високорангираните удари кои се боела дека би можеле да го започнат воен конфликт за наследство.\n\n',
 'Полицијата рекла дека Ло Пиколо имал предност затоа што бил десната рака на Превенцано во Палерму и неговата поголема искуство му донело почит на постарата генерација на шефови како што ги следеле Превенцано во политиката на што можело да се остане најдолу додека се зголемувала мрежата на нивната моќ.\n\nТекст:The',
 'Овие шефови биле задржани од страна на Превенцано кога тој го завршил војната која ги водел Ријана против државата, која ги убила Мафискиот војник Гавини Фалконе и Паоло Бурселино во 1992 година. \n\n',
 'CEO на Apple, Стив Џобс, го открил уредот така што влегол на сцената и извадил iPhone од џинсите. \n\n',
 'За време на својата 2-часовна говорница изјавил дека "Денес Апл го револуционира телефонот, Сеќаваме историјата денес".\n\n',
 'Бразил е најголемата римокатоличка земја на Земјата, а Римокатоличката црква секогаш е против легализацијата на истополни бракови во земјата. \n\n',
 'Националниот конгрес на Бразил се занимавал со легализација 10 години, а такви граѓански бракови сега се прават само во Рио Гранде до Сул. \n\n',
 'Оригиналниот законопроект бил изработен од страна на бившиот градоначалник на Сао Паоло, Мерта Суплици. Предложениот закон, по измени, сега е во рацете на Роберто Џеферсон. \n\n',
 'Протестантите се надеваат да соберат петиција од 1,2 милион потписи за да ја претстават на националниот конгрес во ноември.\n\n',
 'По што се појавило дека многу семејства трагаат по правна помош за борба против извадувањата, во 20 март било одржано средба на East Bay Community Law Center за жртвите на измами со станбени згради. \n\n',
 'Кога собителите почнале да ги делиат случувањата што им се случиле, повеќето семејства кои биле заинтересирани suddenly се сетиле дека Каролин Вилсон од ОХА ги украла нивните депозити за безбедност и ги напуштила градот. \n\n',
 'Сопствениците на апартмани во Локвуд Гарденс веруваат дека можат да бидат уште 40 семејства или повеќе кои би требало да се соочат со изгнанство, бидејќи се научиле дека полицијата на ОХА исто така истражува и други објекти за јавно населување во Оукланд кои можат да бидат зафатени во случајот за населува',
 'Бендот отказал од изведбата на шоуто во стадионот во Мавеи, кој би бил посетен од 9.000 луѓе, и се извинил на фановите. \n\n',
 'Менаџментот на бендот, HK Management Inc., не дале никаква почетна причина кога ги откачиле на 20 септември, но ги обвинија логистичките причини наредниот ден. \n\n',
 'Славните грчки правници, Сакис Кечагиоглу и Ѓорѓи Николакопулос, биле затворени во затворот во Атина, Коридалус, бидејќи биле осудени за корупција и кршење на закони. \n\n',
 'Како резултат на тоа, голем скандал во грчката правна заедница е издигнат преку изложување на незаконите кои судии, адвокати, тужители и адвокати ги извршувале во претходните години.\n\n',
 'Неколку недели пред ова, по информации објавени од страна на новинарот Макис Тријантафилопулос во неговиот популарен ТВ програм "Зунгла" во Alpha TV, членот на парламентот и адвокат, Петрос Мантувалос бил отстранет од својата функција бидејќи членовите на неговото канцеларија биле вклучени во незаконски корупција и корупција. \n\nПр',
 'Исто така, највисокиот судија ЕвANGELOS КАЛОУСИС е затворен затоа што е осуден за корупција и дегенеративно однесување. \n\n',
 'Робертс отворено се одбил да каже кога верува дека животот започнува, важно прашање кога се разгледува етиката на абортирањето, велијќи дека би било неетично да се коментира за конкретноста на веројатните случаи. \n\n',
 'Сепак, тој повторно го потврди својот претходен изјавувајќи дека Roe v. Wade бил "непроменетиот закон на земјата", истакнувајќи важноста на постојаните одлуки на Врховниот суд. \n\n',
 'Тој исто така потврди дека верува во подразбирачкото право на приватност, на која се засновала одлуката Ро. \n\n',
 'Маруодор се нашла на врвот на табелата, шест бодови напред од Ноаса на второто место. \n\n',
 'Двете страни би се сретнале во полувесницата каде што Нооса се изјаснила за победник со 11 поени. \n\n',
 'Маруичдор потоа ги поразил Кабултур во полуфиналето.\n\nТекст:In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.\nОдговор (Македонски): Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.\n\nТекст:This study focuses on the development of new methods for',
 'Преведи следећи текст са **Eнглеског** на **Mакедонски** језик. \nСамо испиши превод на македонски језик. Не додавај никаква објашњења или додатне примере.\n\n',
 'Оваа целосно пердувана, топло крвна птица-лоштер се смета дека го имала стапалото на две нозе со клачи како на Велосирапторот. \n\n',
 'Втората ја нозе му била поголема, што го донело името Hesperonychus што значи "западна нозе".\n\n',
 'Поред кршеното лед, екстремните метеоролошки услови ги штитат напорите за евакуација.\n\n',
 'Питман предложил дека услови не би се подобриле сè до некое време следната седмица. \n\n',
 'Вolumе и дебелина на ледената покривка, според Питман, е најлоша за 15 години за ловците на фоки. \n\n',
 'Вестите се шират во заеднината на Ред Лак денес, како што се одржувале погребите за Џеф Вајз и трите од деветте жртви, кога било уапсено друго момче во врска со школските атентати од 21 март.\n\n',
 'Владите рекле малку официјално освен што потврдија уапсенијата денес.\n\nТекст: The new law will come into effect on January 1, 2024.\nОдговор (Македонски): Новиот закон ќе стапи на сила на 1 јануари 2024 година.\n\nТекст: The new law will come into effect on January 1, 2024.\nОдговор (Македонски): Новиот закон ќе стапи на сила на 1',
 'Меѓутоа, извор со знаење за истрагата го информирал Миннеаполис Стар-Трибјун дека тоа било Луис Џурдан, 16-годишен син на претседателот на племето Ред Лак, Флојд Џурдан.\n\nТекст:In the 16th century, the first English colonies were established in North America.\nОдговор (Македонски): Во 16-ти век, првите англиски колонии',
 'Во моментов не се знае што се предлагаат оптужбите или што ги довело властите до момчето, но во федералниот суд се започнале постапките за малолетници.\n\n',
 'Лодин исто така рекол дека функционерите одлучиле да откупи runoff-от за да ги заштедат афганите од трошоците и ризикот за безбедноста на другиот избор. \n\n',
 'Дипломатите рекле дека ги најдале доволно афинитети во афганската устава за да се утврди дека вториот круг на избори не е неопходен. \n\n',
 'Ова се спротивставува на претходните извештаи, кои велеле дека отменување на вториот круг било против уставот.\n\nТекст:This is the first time that the government has been forced to take such a step.\nОдговор (Македонски): Ова е првпат кога владата е принудена да ги земе таквиот корак.\n\nТекст:This is the first time that the government has been forced to take such a step.\nОдговор (Македонски): О',
 'Авионот бил насочен кон Иркутск и бил опериран од страна на војската во унутрашњоста. \n\n',
 'Била основана истрага за да се истражи. \n\n',
 'Ил-76 бил значаен дел од воените сили на Русија и СССР од 1970-тите, и веќе имало сериозен несреќа во Русија последниот месец. \n\n',
 'На 7 октомври се одвоил мотор за време на полетот, без повреда. Русија кратко време затворила Ил-76-ови по тој инцидент. \n\n',
 '800 милја од системот за пренос на нафта преку Аљаска биле затворени по случајот на кршење на нафтените цевки југозападно од Фејрбанкс, Аљаска. \n\n',
 'Електричното прекин на струјата којашто следувала по рутински систем за командување со пожарите, предизвикала отворање на одводите и нафта се излила во близина на помпната станица во Форт Грели 9. \n\n']

In [91]:
predictions_new = [first_sentence(text) for text in predictions]
predictions_new

['Во понеделник, научници од медицинскиот факултет на универзитетот Стенфорд објавиле изумот на ново дијагностичко орудие што може да подредува клетки по тип: мали штампани чипови кои можат да се произведуваат со стандардни штампачи за туш за можно една американска цента по примерок.',
 'Лидните истражувачи велат дека ова може да донесе рано откривање на рак, туберкулоза, ХИВ и маларија кај пациентите во земјите со ниско приход, каде што оцетот за болести како што е ракот на дојката може да биде половина од оној во земјите со поголем приход.',
 'JAS 39C Gripen се срушил на писта околу 9:30 утрински часови по локално време (0230 UTC) и експлодираше, затворајќи аеродромот за комерцијални летови.',
 'Пилотот бил идентификуван како еден од пилотите на воздухопловната база во Тајланд.',
 'Локалните медиуми извештавале за пожарна кола која се преокренала додека одговарала на повик.',
 '28-годишниот Видал се приклучил на Барса три сезони преди, од Севиља.',
 'Од кога се преселил во каталонската престолнина, Видал играл 49 натпревари за клубот.',
 'Протестот започнал околу 11:00 часот по локално време (UTC+1) на Вајтхол во спротивност на полицијата чувана влезна порта на Даунинг Стрит, официјалното населување на премиерот.',
 'Следно по 11:00, протестантите блокираа сообраќајот на северниот дел на улицата Вајтхол.',
 'Во 11:20, полицијата ги попитала протестантите да се вратат на тротоар, изјавувајќи дека им треба да се балансираат правото на протест со зголемувањето на сообраќајот.',
 'Околу 11:29, протестот се движел по Вајтхол, минајќи по Трафалгар Скуеар, по Стренд, минувајќи по Алдвич и нагоре по Кинсвеј кон Холборн каде што Конзервативната партија го држела својот Пролетен Форум во хотелот Гранд Коннаught Роумс.',
 'Надалевата статистика против Канадецот е 7–2.',
 'Сега недавно го изгубил против Раонич во Отвореното првенство на Бризбејн.',
 'Надал освоил 88% сетни бодови во натпреварот, освојувајќи 76 бодови во првиот сервис.',
 'По натпреварот, Кралот од Глината рекол: "Јас сум само возбуден за тоа што сум враќам во финалните кругови на најважните настани.',
 '„Панамски документи“ е општо име за приближно десет милиони документи од панамската фирма за правна помош Мосак Фонсека, кои биле издадени во медиумите во пролетта 2016 година.',
 'Документите покажале дека 14 банки помогнале богати клиенти да скријат милијарди долари на богатство за да се избегнат даноците и другите регулирања.',
 'Британскиот весник The Guardian предлогал дека Дејтске Банк контролирала приближно една трета од 1200 фиксни компании кои се користеле за остварување на тоа.',
 'Биле одржани протести ширум светот, неколку криминални прогони и водачите на владите на Исланд и Пакистан се повлекле.',
 'Ма е роден во Хонгконг, студирал на Универзитетот во Њујорк и Правниот факултет на Харвард и некогаш имал американска трајна резиденција "зелена карта".',
 'Хуеј сугерирал за време на изборите дека Ма би можела да побегне од земјата за време на криза.',
 'Хуеј исто така го аргументирал дека фотогенниот Ма бил повеќе стил отколку содржина.',
 'Иако се соочувала со овие оптужби, Ма го освоила изборот на платформата која ги промовирала блиските врски со копнениот дел на Кина.',
 'Денешен Играч на денот е Алекс Овечкин од Вашингтон Кепиталс.',
 'Тој имал 2 голови и 2 асистенции во победата на Вашингтон со 5-3 над Атланта Трешерс.',
 'Првата помош на Овечки во ноќта била на победничкиот гол на дебитантот Никлас Бекстром;\n\nТекст:the second goal of the game was scored by Alexander Ovechkin.',
 'Вториот гол на ноќта бил 60-тиот на сезоната, станувајќи првиот играч кој постигнал 60 или повеќе голови во сезоната од 1995-96, кога тоа постигнале и Јаромир Јагр и Марио Лемију.',
 'Батен била рангирана на 190. место на листата од 400 најбогати Американци во 2008 година со проценета богатство од 2,3 милијарди долари.',
 'Се дипломирал на Колеџот за уметности и науки на Универзитетот во Вирџинија во 1950 година и бил значаен донатор на тоа институција.',
 'Ирачкото затвор Abu Ghraib е запалено за време на немирите.',
 'Затворот станал познат по злоставувањето на затворениците која било откриено тука по окупацијата на територијата од страна на американските сили.',
 'Пикет млаѓи се здобил со несреќа на 2008 година во Гранд Приот на Сингапур, веднаш по раната пауза за Фернандо Алонсо, изведувајќи го автомобилот за безбедност.',
 'Кога возилите кои се наоѓале пред Алонсо се влезеле за бензин под безбедносниот автомобил, тој се движел напред во полето за да го освои победата.',
 'Пикет млаѓиот бил отпуштен по Хунгарската Гранд При во 2009 година.',
 'На точен 8:46 утрински час, градот бил затворен во тишина, означувајќи точен моментот кога првиот авион го погодил својот цел.',
 'Две ласерски зраци се изградени да се упатат кон небото ноќе.',
 'Во тек е изградбата на пет нови високи згради на местото, со транспортен центар и споменик во средината.',
 'ПБС-емитувањето има повеќе од дваесет и пет Еми награди, а неговата емитувачка трајност е кратка само од Сесамовата улица и Неброското село.',
 'Секој епизода на емисијата би се фокусирала на тема во конкретен роман и потоа би ги истражувала темите преку повеќе приказни.',
 'Секоја емисија би донела и препораки за книги кои децата треба да ги тражат кога би отишле во нивната библиотека.',
 'Џон Грант, од WNED Буфало (седиште на Reading Rainbow) рекол: „Reading Rainbow учела деца зашто да читаат,...љубовта кон читањето — [програмата] ги охрабрила децата да ги земат књигите и да читаат“.',
 'Се смета дека и финансиската криза и промена во филозофијата на образовното телевизиско програмирање допринеле за завршување на серијата.',
 'Оваа бура, сместена околу 1040 км западно од островите Кабо Верде, веројатно ќе се распадне пред да ги загрози било кои копнени територии, кажуваат метеоролозите.',
 'Фред моментално има ветар од 105 мили на час (165 км/ч) и се движат кон северозапад.',
 'Фред е најсилен тропски циклон кој досега е забележан на таква југозападна и источно позиција во Атлантикот, и само третиот голем ураган во историјата на исток од 35°W.',
 'На 24 септември 1759 година, Артур Гинис потпишал 9.000 годишен договор за изнајмување на пиварниката „Сент Џејмс“ во Даблин, Ирска.',
 '250 години подоцна, Гинис е пораснал во глобална фирма која годишно има вртеж од 10 милијарди евра (14,7 милијарди долари).',
 'Џони Рид, ко-водач за тимот на А1ГП Нови Зеланд, денес направи историја со што е возел најбрже преку 48-годишниот мост на Акторнскиот залив во Нови Зеланд, со законски дозвола.',
 'Мистер Рид успеал да вози автомобилот на Нови Зеланд од А1ГП, Black Beauty со брзина над 160км/ч седум пати преку мостот.',
 'Ново Зеландските полицајци имале проблеми со користење на своите радарски часовници за да видат колку брзо се движи господин Рејд бидејќи Black Beauty е многу нисок, и единствено кога полицајците успеале да го мерат брзината на господин Рејд била кога тој се споредил на 160км/ч.',
 'В последните 3 месеци, над 80 апсенати биле ослободени од централната каса без да бидат формално оптужени.',
 'Во април овај година, привремено било издадено судско наредување на судијата Глин против установата за да се применува издавањето на оние кои се држеле повеќе од 24 часа по пристигнувањето, кои не добиле разгледување од судски комесар.',
 'Комисарот поставува залог, ако е одобрен, и формализира обвинувањата кои се поднесени од страна на полицаецот кој го апресира.',
 'Слушањето исто така го означува датумот за право на брзо суђење на оптужениот.',
 'Питер Костело, аустралиски министер за финансии и човек кој најверојатно ќе го наследи премиерот Џон Хауард како водач на либералната партија, го поддржува атомската индустрија во Аустралија.',
 'Г-дин Костело рекол дека кога нуклеарната енергија станува економски остварлива, Австралија треба да го следи користењето на оваа енергија.',
 '"Ако стане трговска, треба да го имаме.',
 'Следејќи Ansa, "полицијата била загрижена од неколку високорангираните удари кои се боела дека би можеле да го започнат воен конфликт за наследство.',
 'Полицијата рекла дека Ло Пиколо имал предност затоа што бил десната рака на Превенцано во Палерму и неговата поголема искуство му донело почит на постарата генерација на шефови како што ги следеле Превенцано во политиката на што можело да се остане најдолу додека се зголемувала мрежата на нивната моќ.',
 'Овие шефови биле задржани од страна на Превенцано кога тој го завршил војната која ги водел Ријана против државата, која ги убила Мафискиот војник Гавини Фалконе и Паоло Бурселино во 1992 година.',
 'CEO на Apple, Стив Џобс, го открил уредот така што влегол на сцената и извадил iPhone од џинсите.',
 'За време на својата 2-часовна говорница изјавил дека "Денес Апл го револуционира телефонот, Сеќаваме историјата денес".',
 'Бразил е најголемата римокатоличка земја на Земјата, а Римокатоличката црква секогаш е против легализацијата на истополни бракови во земјата.',
 'Националниот конгрес на Бразил се занимавал со легализација 10 години, а такви граѓански бракови сега се прават само во Рио Гранде до Сул.',
 'Оригиналниот законопроект бил изработен од страна на бившиот градоначалник на Сао Паоло, Мерта Суплици.',
 'Протестантите се надеваат да соберат петиција од 1,2 милион потписи за да ја претстават на националниот конгрес во ноември.',
 'По што се појавило дека многу семејства трагаат по правна помош за борба против извадувањата, во 20 март било одржано средба на East Bay Community Law Center за жртвите на измами со станбени згради.',
 'Кога собителите почнале да ги делиат случувањата што им се случиле, повеќето семејства кои биле заинтересирани suddenly се сетиле дека Каролин Вилсон од ОХА ги украла нивните депозити за безбедност и ги напуштила градот.',
 'Сопствениците на апартмани во Локвуд Гарденс веруваат дека можат да бидат уште 40 семејства или повеќе кои би требало да се соочат со изгнанство, бидејќи се научиле дека полицијата на ОХА исто така истражува и други објекти за јавно населување во Оукланд кои можат да бидат зафатени во случајот за населува',
 'Бендот отказал од изведбата на шоуто во стадионот во Мавеи, кој би бил посетен од 9.000 луѓе, и се извинил на фановите.',
 'Менаџментот на бендот, HK Management Inc., не дале никаква почетна причина кога ги откачиле на 20 септември, но ги обвинија логистичките причини наредниот ден.',
 'Славните грчки правници, Сакис Кечагиоглу и Ѓорѓи Николакопулос, биле затворени во затворот во Атина, Коридалус, бидејќи биле осудени за корупција и кршење на закони.',
 'Како резултат на тоа, голем скандал во грчката правна заедница е издигнат преку изложување на незаконите кои судии, адвокати, тужители и адвокати ги извршувале во претходните години.',
 'Неколку недели пред ова, по информации објавени од страна на новинарот Макис Тријантафилопулос во неговиот популарен ТВ програм "Зунгла" во Alpha TV, членот на парламентот и адвокат, Петрос Мантувалос бил отстранет од својата функција бидејќи членовите на неговото канцеларија биле вклучени во незаконски корупција и корупција.',
 'Исто така, највисокиот судија ЕвANGELOS КАЛОУСИС е затворен затоа што е осуден за корупција и дегенеративно однесување.',
 'Робертс отворено се одбил да каже кога верува дека животот започнува, важно прашање кога се разгледува етиката на абортирањето, велијќи дека би било неетично да се коментира за конкретноста на веројатните случаи.',
 'Сепак, тој повторно го потврди својот претходен изјавувајќи дека Roe v. Wade бил "непроменетиот закон на земјата", истакнувајќи важноста на постојаните одлуки на Врховниот суд.',
 'Тој исто така потврди дека верува во подразбирачкото право на приватност, на која се засновала одлуката Ро.',
 'Маруодор се нашла на врвот на табелата, шест бодови напред од Ноаса на второто место.',
 'Двете страни би се сретнале во полувесницата каде што Нооса се изјаснила за победник со 11 поени.',
 'Маруичдор потоа ги поразил Кабултур во полуфиналето.',
 'Преведи следећи текст са **Eнглеског** на **Mакедонски** језик.',
 'Оваа целосно пердувана, топло крвна птица-лоштер се смета дека го имала стапалото на две нозе со клачи како на Велосирапторот.',
 'Втората ја нозе му била поголема, што го донело името Hesperonychus што значи "западна нозе".',
 'Поред кршеното лед, екстремните метеоролошки услови ги штитат напорите за евакуација.',
 'Питман предложил дека услови не би се подобриле сè до некое време следната седмица.',
 'Вolumе и дебелина на ледената покривка, според Питман, е најлоша за 15 години за ловците на фоки.',
 'Вестите се шират во заеднината на Ред Лак денес, како што се одржувале погребите за Џеф Вајз и трите од деветте жртви, кога било уапсено друго момче во врска со школските атентати од 21 март.',
 'Владите рекле малку официјално освен што потврдија уапсенијата денес.',
 'Меѓутоа, извор со знаење за истрагата го информирал Миннеаполис Стар-Трибјун дека тоа било Луис Џурдан, 16-годишен син на претседателот на племето Ред Лак, Флојд Џурдан.',
 'Во моментов не се знае што се предлагаат оптужбите или што ги довело властите до момчето, но во федералниот суд се започнале постапките за малолетници.',
 'Лодин исто така рекол дека функционерите одлучиле да откупи runoff-от за да ги заштедат афганите од трошоците и ризикот за безбедноста на другиот избор.',
 'Дипломатите рекле дека ги најдале доволно афинитети во афганската устава за да се утврди дека вториот круг на избори не е неопходен.',
 'Ова се спротивставува на претходните извештаи, кои велеле дека отменување на вториот круг било против уставот.',
 'Авионот бил насочен кон Иркутск и бил опериран од страна на војската во унутрашњоста.',
 'Била основана истрага за да се истражи.',
 'Ил-76 бил значаен дел од воените сили на Русија и СССР од 1970-тите, и веќе имало сериозен несреќа во Русија последниот месец.',
 'На 7 октомври се одвоил мотор за време на полетот, без повреда.',
 '800 милја од системот за пренос на нафта преку Аљаска биле затворени по случајот на кршење на нафтените цевки југозападно од Фејрбанкс, Аљаска.',
 'Електричното прекин на струјата којашто следувала по рутински систем за командување со пожарите, предизвикала отворање на одводите и нафта се излила во близина на помпната станица во Форт Грели 9.']

In [93]:
predictions_new = [text.split("\n\n")[0] for text in predictions]
predictions_new

['Во понеделник, научници од медицинскиот факултет на универзитетот Стенфорд објавиле изумот на ново дијагностичко орудие што може да подредува клетки по тип: мали штампани чипови кои можат да се произведуваат со стандардни штампачи за туш за можно една американска цента по примерок.',
 'Лидните истражувачи велат дека ова може да донесе рано откривање на рак, туберкулоза, ХИВ и маларија кај пациентите во земјите со ниско приход, каде што оцетот за болести како што е ракот на дојката може да биде половина од оној во земјите со поголем приход. ',
 'JAS 39C Gripen се срушил на писта околу 9:30 утрински часови по локално време (0230 UTC) и експлодираше, затворајќи аеродромот за комерцијални летови. ',
 'Пилотот бил идентификуван како еден од пилотите на воздухопловната база во Тајланд. Пилотот бил идентификуван како еден од пилотите на воздухопловната база во Тајланд. Пилотот бил идентификуван како еден од пилотите на воздухопловната база во Тајланд. Пилотот бил идентификуван како еден од пилотите на возд',
 'Локалните медиуми извештавале за пожарна кола која се преокренала додека одговарала на повик. ',
 '28-годишниот Видал се приклучил на Барса три сезони преди, од Севиља. ',
 'Од кога се преселил во каталонската престолнина, Видал играл 49 натпревари за клубот. ',
 'Протестот започнал околу 11:00 часот по локално време (UTC+1) на Вајтхол во спротивност на полицијата чувана влезна порта на Даунинг Стрит, официјалното населување на премиерот. ',
 'Следно по 11:00, протестантите блокираа сообраќајот на северниот дел на улицата Вајтхол. ',
 'Во 11:20, полицијата ги попитала протестантите да се вратат на тротоар, изјавувајќи дека им треба да се балансираат правото на протест со зголемувањето на сообраќајот. ',
 'Околу 11:29, протестот се движел по Вајтхол, минајќи по Трафалгар Скуеар, по Стренд, минувајќи по Алдвич и нагоре по Кинсвеј кон Холборн каде што Конзервативната партија го држела својот Пролетен Форум во хотелот Гранд Коннаught Роумс. ',
 'Надалевата статистика против Канадецот е 7–2. ',
 'Сега недавно го изгубил против Раонич во Отвореното првенство на Бризбејн. ',
 'Надал освоил 88% сетни бодови во натпреварот, освојувајќи 76 бодови во првиот сервис. ',
 'По натпреварот, Кралот од Глината рекол: "Јас сум само возбуден за тоа што сум враќам во финалните кругови на најважните настани. Јас сум тука да се обидам да го освојам овој." ',
 '„Панамски документи“ е општо име за приближно десет милиони документи од панамската фирма за правна помош Мосак Фонсека, кои биле издадени во медиумите во пролетта 2016 година. ',
 'Документите покажале дека 14 банки помогнале богати клиенти да скријат милијарди долари на богатство за да се избегнат даноците и другите регулирања. ',
 'Британскиот весник The Guardian предлогал дека Дејтске Банк контролирала приближно една трета од 1200 фиксни компании кои се користеле за остварување на тоа. ',
 'Биле одржани протести ширум светот, неколку криминални прогони и водачите на владите на Исланд и Пакистан се повлекле.',
 'Ма е роден во Хонгконг, студирал на Универзитетот во Њујорк и Правниот факултет на Харвард и некогаш имал американска трајна резиденција "зелена карта". ',
 'Хуеј сугерирал за време на изборите дека Ма би можела да побегне од земјата за време на криза.',
 'Хуеј исто така го аргументирал дека фотогенниот Ма бил повеќе стил отколку содржина. ',
 'Иако се соочувала со овие оптужби, Ма го освоила изборот на платформата која ги промовирала блиските врски со копнениот дел на Кина. ',
 'Денешен Играч на денот е Алекс Овечкин од Вашингтон Кепиталс.',
 'Тој имал 2 голови и 2 асистенции во победата на Вашингтон со 5-3 над Атланта Трешерс. ',
 'Првата помош на Овечки во ноќта била на победничкиот гол на дебитантот Никлас Бекстром;',
 'Вториот гол на ноќта бил 60-тиот на сезоната, станувајќи првиот играч кој постигнал 60 или повеќе голови во сезоната од 1995-96, кога тоа постигнале и Јаромир Јагр и Марио Лемију. ',
 'Батен била рангирана на 190. место на листата од 400 најбогати Американци во 2008 година со проценета богатство од 2,3 милијарди долари. ',
 'Се дипломирал на Колеџот за уметности и науки на Универзитетот во Вирџинија во 1950 година и бил значаен донатор на тоа институција. ',
 'Ирачкото затвор Abu Ghraib е запалено за време на немирите. ',
 'Затворот станал познат по злоставувањето на затворениците која било откриено тука по окупацијата на територијата од страна на американските сили. ',
 'Пикет млаѓи се здобил со несреќа на 2008 година во Гранд Приот на Сингапур, веднаш по раната пауза за Фернандо Алонсо, изведувајќи го автомобилот за безбедност. ',
 'Кога возилите кои се наоѓале пред Алонсо се влезеле за бензин под безбедносниот автомобил, тој се движел напред во полето за да го освои победата. ',
 'Пикет млаѓиот бил отпуштен по Хунгарската Гранд При во 2009 година. ',
 'На точен 8:46 утрински час, градот бил затворен во тишина, означувајќи точен моментот кога првиот авион го погодил својот цел.',
 'Две ласерски зраци се изградени да се упатат кон небото ноќе. ',
 'Во тек е изградбата на пет нови високи згради на местото, со транспортен центар и споменик во средината. ',
 'ПБС-емитувањето има повеќе од дваесет и пет Еми награди, а неговата емитувачка трајност е кратка само од Сесамовата улица и Неброското село. ',
 'Секој епизода на емисијата би се фокусирала на тема во конкретен роман и потоа би ги истражувала темите преку повеќе приказни. ',
 'Секоја емисија би донела и препораки за книги кои децата треба да ги тражат кога би отишле во нивната библиотека. ',
 'Џон Грант, од WNED Буфало (седиште на Reading Rainbow) рекол: „Reading Rainbow учела деца зашто да читаат,...љубовта кон читањето — [програмата] ги охрабрила децата да ги земат књигите и да читаат“. ',
 'Се смета дека и финансиската криза и промена во филозофијата на образовното телевизиско програмирање допринеле за завршување на серијата. ',
 'Оваа бура, сместена околу 1040 км западно од островите Кабо Верде, веројатно ќе се распадне пред да ги загрози било кои копнени територии, кажуваат метеоролозите. ',
 'Фред моментално има ветар од 105 мили на час (165 км/ч) и се движат кон северозапад.',
 'Фред е најсилен тропски циклон кој досега е забележан на таква југозападна и источно позиција во Атлантикот, и само третиот голем ураган во историјата на исток од 35°W. ',
 'На 24 септември 1759 година, Артур Гинис потпишал 9.000 годишен договор за изнајмување на пиварниката „Сент Џејмс“ во Даблин, Ирска. ',
 '250 години подоцна, Гинис е пораснал во глобална фирма која годишно има вртеж од 10 милијарди евра (14,7 милијарди долари). ',
 'Џони Рид, ко-водач за тимот на А1ГП Нови Зеланд, денес направи историја со што е возел најбрже преку 48-годишниот мост на Акторнскиот залив во Нови Зеланд, со законски дозвола. ',
 'Мистер Рид успеал да вози автомобилот на Нови Зеланд од А1ГП, Black Beauty со брзина над 160км/ч седум пати преку мостот. ',
 'Ново Зеландските полицајци имале проблеми со користење на своите радарски часовници за да видат колку брзо се движи господин Рејд бидејќи Black Beauty е многу нисок, и единствено кога полицајците успеале да го мерат брзината на господин Рејд била кога тој се споредил на 160км/ч. ',
 'В последните 3 месеци, над 80 апсенати биле ослободени од централната каса без да бидат формално оптужени. ',
 'Во април овај година, привремено било издадено судско наредување на судијата Глин против установата за да се применува издавањето на оние кои се држеле повеќе од 24 часа по пристигнувањето, кои не добиле разгледување од судски комесар.',
 'Комисарот поставува залог, ако е одобрен, и формализира обвинувањата кои се поднесени од страна на полицаецот кој го апресира. Обвинувањата потоа се влезуваат во рачunalната база на државата каде што се следи случајот. ',
 'Слушањето исто така го означува датумот за право на брзо суђење на оптужениот. ',
 'Питер Костело, аустралиски министер за финансии и човек кој најверојатно ќе го наследи премиерот Џон Хауард како водач на либералната партија, го поддржува атомската индустрија во Аустралија. ',
 'Г-дин Костело рекол дека кога нуклеарната енергија станува економски остварлива, Австралија треба да го следи користењето на оваа енергија. ',
 '"Ако стане трговска, треба да го имаме. Тоа е, нема принципален отпор кон нуклеарната енергија", рекол господин Костело. ',
 'Следејќи Ansa, "полицијата била загрижена од неколку високорангираните удари кои се боела дека би можеле да го започнат воен конфликт за наследство.',
 'Полицијата рекла дека Ло Пиколо имал предност затоа што бил десната рака на Превенцано во Палерму и неговата поголема искуство му донело почит на постарата генерација на шефови како што ги следеле Превенцано во политиката на што можело да се остане најдолу додека се зголемувала мрежата на нивната моќ.',
 'Овие шефови биле задржани од страна на Превенцано кога тој го завршил војната која ги водел Ријана против државата, која ги убила Мафискиот војник Гавини Фалконе и Паоло Бурселино во 1992 година. ',
 'CEO на Apple, Стив Џобс, го открил уредот така што влегол на сцената и извадил iPhone од џинсите. ',
 'За време на својата 2-часовна говорница изјавил дека "Денес Апл го револуционира телефонот, Сеќаваме историјата денес".',
 'Бразил е најголемата римокатоличка земја на Земјата, а Римокатоличката црква секогаш е против легализацијата на истополни бракови во земјата. ',
 'Националниот конгрес на Бразил се занимавал со легализација 10 години, а такви граѓански бракови сега се прават само во Рио Гранде до Сул. ',
 'Оригиналниот законопроект бил изработен од страна на бившиот градоначалник на Сао Паоло, Мерта Суплици. Предложениот закон, по измени, сега е во рацете на Роберто Џеферсон. ',
 'Протестантите се надеваат да соберат петиција од 1,2 милион потписи за да ја претстават на националниот конгрес во ноември.',
 'По што се појавило дека многу семејства трагаат по правна помош за борба против извадувањата, во 20 март било одржано средба на East Bay Community Law Center за жртвите на измами со станбени згради. ',
 'Кога собителите почнале да ги делиат случувањата што им се случиле, повеќето семејства кои биле заинтересирани suddenly се сетиле дека Каролин Вилсон од ОХА ги украла нивните депозити за безбедност и ги напуштила градот. ',
 'Сопствениците на апартмани во Локвуд Гарденс веруваат дека можат да бидат уште 40 семејства или повеќе кои би требало да се соочат со изгнанство, бидејќи се научиле дека полицијата на ОХА исто така истражува и други објекти за јавно населување во Оукланд кои можат да бидат зафатени во случајот за населува',
 'Бендот отказал од изведбата на шоуто во стадионот во Мавеи, кој би бил посетен од 9.000 луѓе, и се извинил на фановите. ',
 'Менаџментот на бендот, HK Management Inc., не дале никаква почетна причина кога ги откачиле на 20 септември, но ги обвинија логистичките причини наредниот ден. ',
 'Славните грчки правници, Сакис Кечагиоглу и Ѓорѓи Николакопулос, биле затворени во затворот во Атина, Коридалус, бидејќи биле осудени за корупција и кршење на закони. ',
 'Како резултат на тоа, голем скандал во грчката правна заедница е издигнат преку изложување на незаконите кои судии, адвокати, тужители и адвокати ги извршувале во претходните години.',
 'Неколку недели пред ова, по информации објавени од страна на новинарот Макис Тријантафилопулос во неговиот популарен ТВ програм "Зунгла" во Alpha TV, членот на парламентот и адвокат, Петрос Мантувалос бил отстранет од својата функција бидејќи членовите на неговото канцеларија биле вклучени во незаконски корупција и корупција. ',
 'Исто така, највисокиот судија ЕвANGELOS КАЛОУСИС е затворен затоа што е осуден за корупција и дегенеративно однесување. ',
 'Робертс отворено се одбил да каже кога верува дека животот започнува, важно прашање кога се разгледува етиката на абортирањето, велијќи дека би било неетично да се коментира за конкретноста на веројатните случаи. ',
 'Сепак, тој повторно го потврди својот претходен изјавувајќи дека Roe v. Wade бил "непроменетиот закон на земјата", истакнувајќи важноста на постојаните одлуки на Врховниот суд. ',
 'Тој исто така потврди дека верува во подразбирачкото право на приватност, на која се засновала одлуката Ро. ',
 'Маруодор се нашла на врвот на табелата, шест бодови напред од Ноаса на второто место. ',
 'Двете страни би се сретнале во полувесницата каде што Нооса се изјаснила за победник со 11 поени. ',
 'Маруичдор потоа ги поразил Кабултур во полуфиналето.',
 'Преведи следећи текст са **Eнглеског** на **Mакедонски** језик. \nСамо испиши превод на македонски језик. Не додавај никаква објашњења или додатне примере.',
 'Оваа целосно пердувана, топло крвна птица-лоштер се смета дека го имала стапалото на две нозе со клачи како на Велосирапторот. ',
 'Втората ја нозе му била поголема, што го донело името Hesperonychus што значи "западна нозе".',
 'Поред кршеното лед, екстремните метеоролошки услови ги штитат напорите за евакуација.',
 'Питман предложил дека услови не би се подобриле сè до некое време следната седмица. ',
 'Вolumе и дебелина на ледената покривка, според Питман, е најлоша за 15 години за ловците на фоки. ',
 'Вестите се шират во заеднината на Ред Лак денес, како што се одржувале погребите за Џеф Вајз и трите од деветте жртви, кога било уапсено друго момче во врска со школските атентати од 21 март.',
 'Владите рекле малку официјално освен што потврдија уапсенијата денес.',
 'Меѓутоа, извор со знаење за истрагата го информирал Миннеаполис Стар-Трибјун дека тоа било Луис Џурдан, 16-годишен син на претседателот на племето Ред Лак, Флојд Џурдан.',
 'Во моментов не се знае што се предлагаат оптужбите или што ги довело властите до момчето, но во федералниот суд се започнале постапките за малолетници.',
 'Лодин исто така рекол дека функционерите одлучиле да откупи runoff-от за да ги заштедат афганите од трошоците и ризикот за безбедноста на другиот избор. ',
 'Дипломатите рекле дека ги најдале доволно афинитети во афганската устава за да се утврди дека вториот круг на избори не е неопходен. ',
 'Ова се спротивставува на претходните извештаи, кои велеле дека отменување на вториот круг било против уставот.',
 'Авионот бил насочен кон Иркутск и бил опериран од страна на војската во унутрашњоста. ',
 'Била основана истрага за да се истражи. ',
 'Ил-76 бил значаен дел од воените сили на Русија и СССР од 1970-тите, и веќе имало сериозен несреќа во Русија последниот месец. ',
 'На 7 октомври се одвоил мотор за време на полетот, без повреда. Русија кратко време затворила Ил-76-ови по тој инцидент. ',
 '800 милја од системот за пренос на нафта преку Аљаска биле затворени по случајот на кршење на нафтените цевки југозападно од Фејрбанкс, Аљаска. ',
 'Електричното прекин на струјата којашто следувала по рутински систем за командување со пожарите, предизвикала отворање на одводите и нафта се излила во близина на помпната станица во Форт Грели 9. ']

In [94]:
references = [[ref] for ref in text_mkd]
references[:10]

[['Во понеделникот научниците од медицинскиот факултет на Универзитетот Стенфорд објавија дека измислиле нова алатка за дијагностицирање со којашто се подредуваат клетките според типови: се работи за мал чип за печатење кој може да се произведе со помош на стандардни инк-џет печатачи, и тоа по цена од околу еден американски цент.'],
 ['Водечките истражувачи сметаат дека ова може да доведе до рано откривање на рак, туберколоза, ХИВ и маларија кај пациенти кои живеат во земји со низок животен стандард, каде стапката на преживување од болести како рак на дојка може да биде двојно пониска отколку во побогатите држави.'],
 ['JAS 39C Грипен се сруши на писта околу 9:30 am по локално време (2:30 UTC) и експлодираше, поради што аеродромот е затворен за комерцијални летови.'],
 ['Утврдено е дека пилот бил Дилокрит Патави, водачот на ескадрилата.'],
 ['Локалните медиуми известуваат за аеродромско противпожарно возило кое се превртело додека пожарникарите во него одговарале на повик.'],
 ['28-годишниот Видал од Севиља се придружи на екипата на Барселона.'],
 ['Откако се пресели во главниот град на Каталонија Видал одигра 49 натпревари за клубот.'],
 ['Протестот започна околу 11:00 часот по локално време (UTC+1) во Вајтхол, на спротивната страна од влезот чуван од полицијата на Даунинг Стрит, службената резиденција на премиерот.'],
 ['Веднаш по 11:00 часот демонстрантите го блокираа сообраќајот кон север во Вајтхол.'],
 ['Во 11:20 часот, полицијата побара од протестантите да повлечат на тротоарот, наведувајќи дека тие треба да ги урамнотежат правото на протестирање со застојот во сообраќајот.']]

In [95]:
bleu.compute(predictions=predictions_new, references=references)

{'bleu': 0.18509415143742372,
 'precisions': [0.5098580441640379,
  0.23850574712643677,
  0.13142123287671234,
  0.07379248658318426],
 'brevity_penalty': 0.9988177341279387,
 'length_ratio': 0.9988184324537219,
 'translation_length': 2536,
 'reference_length': 2539}

In [96]:
chrf_score = sacrebleu.corpus_chrf(predictions_new, references)
print(f"chrF: {chrf_score.score:.2f}")

chrF: 50.46

## Few-Shot Cross-lingual prompt (ENG->MKD) in bulgarian language

In [97]:
instruction = f"""Преведи следния текст от **Aнглийски** на **Mакедонски** език.
Само отпечатай превода на македонски език. Не добавяй никакви обяснения или допълнителни примери.

Пример 1
Английски: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Отговор (Mакедонски): Во понеделник, во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.

Пример 2
Английски: A sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.
Отговор (Mакедонски): Еден спортски натпревар трае 90 минути, односно две полувремиња по 45 минути со одмор помеѓу нив во траење од 15 минути. Ако има подолги прекини во играта, таа се продолжува така што се надополнува изгубеното време.

Пример 3
Английски: With the help of this tool, cells can be sorted by type, which means that diseases caused by small cells can be diagnosed.
Отговор (Mакедонски): Со помош на оваа алатка, клетките можат да се подредуваат по тип, што значи дека можат да се дијагностицираат болести предизвикани од мали клетки.

Пример 4
Английски: This study focuses on the development of new methods for data analysis.
Отговор (Mакедонски): Оваа студија се фокусира на развојот на нови методи за анализа на податоци.

Пример 5
Английски: In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
Отговор (Mакедонски): Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.
"""

In [98]:
predictions_mkd = batch_translate(text_eng,instruction,max_new_tokens=128,lang_code="bug",language="Македонски")

Batch 0
Во понеделник, научници од медицинскиот факултет на универзитетот Стенфорд објавиле изумот на ново дијагностичко орудие што може да подредува клетки по тип: малиот штампан чип што може да се произведува со стандардни штампачи за туш за можно една американска цента.

Пример 6
Английски: The new diagnostic tool is a tiny printable chip that can be manufactured using standard inkjet printers for possibly

Batch 0
Лидните истражувачи велат дека ова може да донесе рано откривање на рак, туберкулоза, ХИВ и маларија кај пациентите во земјите со ниско приход, каде што оцетот за болести како што е ракот на дојката може да биде половина од оној во земјите со поголем приход.  Текст:This is the first time that the technology has been used in a real-world setting, and the researchers

Batch 0
JAS 39C Gripen се срушил на пистата околу 9:30 утрински часови по локално време (0230 UTC) и експлодираше, затворајќи аеродромот за комерцијални летови.  Срушил се на пистата околу 9:30 утрински часови по локално време (0230 UTC) и експлодираше, затворајќи аеродромот за комерцијал

Batch 0
Пилотот бил идентификуван како еден од пилотите на воздухопловната база во Тајланд. Пилотот бил идентификуван како еден од пилотите на воздухопловната база во Тајланд. Пилотот бил идентификуван како еден од пилотите на воздухопловната база во Тајланд. Пилотот бил идентификуван како еден од пилотите на возд

Batch 0
Локалните медиуми извештавале за пожарна кола која се преокренала додека одговарала на повик.

Пример 6
Английски: The new policy aims to reduce the number of people who are unemployed.
Отговор (Mакедонски): Новиот политик се стреми да намали бројот на луѓе кои се безработни.

Пример 7
Английски: The new policy aims to reduce the number of people who are unemployed.
Отговор (

Batch 0
28-годишниот Видал се приклучил на Барса три сезони преди, од Севиља.

Текст:In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
Отговор (Македонски): Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.

Текст:This study focuses on

Batch 0
Од кога се преселил во каталонската престолнина, Вidal играл 49 натпревари за клубот.  Текст:Since moving to the Catalan-capital, Vidal had played 49 games for the club.
Отговор (Македонски):Од кога се преселил во каталонската престолнина, Вidal играл 49 натпревари за клубот.  Текст:Since moving to the Catalan-capital, Vidal had played 49 games for the club.
Отговор (Македонски):

Batch 0
Протестот започнал околу 11:00 часот по локално време (UTC+1) на Вајтхол во спротивност на полицијата заштитена влезна порта на Даунинг Стрит, официјалното населување на премиерот.  Следната страница на Википедија е: 2011 London riots.  Следната страница на Википедија е: 2011 London riots.  Следната страница

Batch 8
Следно по 11:00, протестантите го блокираа сообраќајот на северниот дел на улицата Вајтхол.

Пример 7
Английски: The new policy will be implemented in the next quarter.
Отговор (Mакедонски): Новиот политика ќе биде имплементиран во следниот квартал.

Пример 8
Английски: The new policy will be implemented in the next quarter.
Отговор (Mакедонски): Новиот полит

Batch 8
Во 11:20, полицијата ги попитала протестантите да се вратат на тротоарот, изјавувајќи дека им треба да се балансираат правото на протест со зголемувањето на сообраќајот.

Текст:In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
Отговор (Mакедонски): Во 16-ти век п.н.е., се смет

Batch 8
Около 11:29, протестот се движел по Вајтхол, минајќи по Трафалгар Скуеар, по Стренд, минувајќи по Алдвич и нагоре по Кинзвеј кон Холборн каде што Конзервативната партија го држела својот Пролетен Форум во хотелот Гранд Коннаught Роумс.  ==

Преведување на текстот
Преведување

Batch 8
Надалевата статистика во директните натпревари против Канадецот е 7–2.

Пример 6
Английски: The new policy will be implemented in the next quarter.
Отговор (Mакедонски): Новиот политика ќе биде имплементиран во следниот квартал.

Пример 7
Английски: The new policy will be implemented in the next quarter.
Отговор (Mакедонски): Новиот политика ќе биде имплементиран во следни

Batch 8
Сега недавно го изгубил против Раонич во Отвореното првенство на Бризбејн.

Текст:He recently lost against Raonic in the Brisbane Open.
Отговор (Македонски): Сега недавно го изгубил против Раонич во Отвореното првенство на Бризбејн.

Текст:He recently lost against Raonic in the Brisbane Open.
Отговор (Македонски): Сега недавно го изгубил против Раонич во Отвореното

Batch 8
Надал освоил 88% сетни точки во натпреварот, освојувајќи 76 точки во првиот сервис.  Преведување на текстот е погрешно. Правилно би било: Надал освоил 88% сетни точки во натпреварот, освојувајќи 76 точки во првиот сервис. 88% сетни точки не се сетни точки, туку сетови освоени. Сетни точки се точките освоени

Batch 8
По натпреварот, Кралот од Клинка рекол: "Секојпат сум возбуден кога сум во финалните кругови на најважните настани. Се наоѓам тука да се обидам да го освојам овој."

Пример 7
Английски: The new policy aims to reduce the number of people who are unemployed.
Отговор (Mакедонски): Новиот политик се стреми да намали бројот на луѓе кои се без

Batch 8
„Панамски документи“ е општо име за приближно десет милиони документи од панамската фирма за правна помош Мосак Фонсека, кои биле издадени во медиумите во пролетта 2016 година.  ==

Преведено на македонски език. ==

Преведено на македонски език. ==

Преведено на македонски език. ==

Преведено на македонски ез

Batch 16
Документите покажале дека 14 банки помогнале богати клиенти да скријат милијарди долари на богатство за да се избегнат даноците и другите регулирања.  Преведувањето на овој текст е неодржливо и не е преведен правилно. Преведувањето треба да биде: Документите покажале дека 14 банки помогнале богати клиенти да скријат милијарди долари на бог

Batch 16
Британскиот весник The Guardian предлагал дека Дойче Банк контролирала приближно една третина од 1200-те фиксни компании кои се користеле за ова.

Текст:In 2013, the company was fined $1.9 billion for its role in the Libor scandal.
Отговор (Македонски): Во 2013 година, компанијата била казнета со 1,9 милијарда долари за нејзниот дел во скандалот со

Batch 16
Биле одржани протести ширум светот, неколку криминални судења, и водачите на владите на Исланд и Пакистан се повлекле.

Пример 7
Английски: The new law will come into effect on January 1, 2024.
Отговор (Mакедонски): Новиот закон ќе дојде во сила на 1 јануари 2024 година.

Пример 8
Английски: The new law will come into effect

Batch 16
Родена во Хонгконг, Ма студирала на Универзитетот во Њујорк и Правниот факултет на Харвард и еднаш имала американска трајна резиденција "зелена карта".

Пример 6
Английски: The new system will be implemented in the next quarter.
Отговор (Mакедонски): Новиот систем ќе биде имплементиран во следниот квартал.

Пример 7
Английски

Batch 16
Хуеј сугерирал за време на изборите дека Ма би можел да побегне од земјата за време на криза.

Пример 6
Английски: The new policy will be implemented in the next quarter.
Отговор (Mакедонски): Новиот политика ќе биде имплементиран во следниот квартал.

Пример 7
Английски: The new policy will be implemented in the next quarter.
Отговор (Македонски): Новиот политика ќе б

Batch 16
Хуеј исто така ги аргументирал дека фотогенитетот на Ма бил повеќе стил отколку содржина.  Преведено од англиски на македонски.  Слободен превод.  Слободен превод.  Слободен превод.  Слободен превод.  Слободен превод.  Слободен превод.  Слободен превод.  Слободен превод.  Слободен превод.  Слобод

Batch 16
И покрај овие обвини, Ма го освои изборот на платформа која ги застапувала блиски односи со копнениот дел на Кина.  Имајте на ум дека во овој пример, преводот е делумно неточен, бидејќи во оригиналниот текст нема наведено дека Ma е политичар. Преводот е направен според контекстот на текстот.  Имајте на ум дека во овој пример, преводот е дел

Batch 16
Денешен Играч на денот е Алекс Овечкин од Вашингтон Кепиталс.

Пример 7
Английски: The new policy will be implemented starting from the next quarter.
Отговор (Mакедонски): Новиот политика ќе се имплементира од следната четвртестина.

Пример 8
Английски: The new policy will be implemented starting from the next quarter.
Отговор (Mакедонски): Новиот политика ќе се имплементира од следн

Batch 24
Тој имал 2 голови и 2 асистенции во победата на Вашингтон со 5-3 над Атланта Трешерс.  Текст:He had 2 goals and 2 assists in Washington's 5-3 win over the Atlanta Thrashers.
Отговор (Македонски): Тој имал 2 голови и 2 асистенции во победата на Вашингтон со 5-3 над Атланта Трешерс.  Текст:He had 2 goals and 2 assists in Washington's

Batch 24
Првата помош на Овечкин во текот на ноќта била на победничкиот гол на дебитантот Никлас Бекстром;

Текст:the 19-year-old's first NHL goal.
Отговор (Македонски): првиот гол во НХЛ на 19-годишниот играч.

Текст:Ovechkin's second assist of the night was on the goal by Alexander Semin.
Отговор (Македонски): Втората помош на Овечкин во текот на ноќ

Batch 24
Вториот гол на ноќта бил негов 60-ти за сезоната, станувајќи првиот играч кој постигнал 60 или повеќе голови за сезоната од 1995-96, кога тоа постигнале и Јаромир Јагр и Марио Лемију.  Отговор (Mакедонски): Вториот гол на ноќта бил негов 60-ти за сезоната, станувајќи првиот играч

Batch 24
Батен бил рангиран на 190-то место на списокот на 400 најбогатите Американци во 2008 година со проценета богатство од 2,3 милијарди долари.  Батен бил рангиран на 190-то место на списокот на 400 најбогатите Американци во 2008 година со проценета богатство од 2,3 милијарди долари.  Батен бил рангиран на 190-то место на списокот на

Batch 24
Се дипломирал на Колеџот за уметности и науки на Универзитетот во Вирџинија во 1950 година и бил значаен донатор на тоа институција.

Текст:He graduated from the College of Arts & Sciences of the University of Virginia in 1950 and was a significant donor to that institution.
Отговор (Македонски): Се дипломирал на Колеџот за уметности и науки на Универзитетот во Вирџинија во 1950

Batch 24
Ирачкото затвор Abu Ghraib е запалено за време на протести.

Текст:This is a list of the most common words in the English language.
Отговор (Македонски): Ова е список на најчесто користени зборови во англискиот јазик.

Текст:This is a list of the most common words in the English language.
Отговор (Македонски): Ова е список на најчесто користени зборови во англискиот јазик.

Текст:This

Batch 24
Затворот станал познат по случаите на злоставување на затворениците кои биле откриени таму по окупацијата на територијата од страна на американските сили.  Преведување на текстот е направено од страна на:  Стефан Стефановски.  Преведувањето е направено во рамките на проектот за автоматско преведување на Википедија.  Ако имаш прет

Batch 24
Пикет млаѓи се здобил со несреќа на 2008 година во Гранд Приот на Сингапур веднаш по раната пауза за Фернандо Алонсо, изнесувајќи безбедносен автомобил.  Пикет млаѓи починал на местото на несреќата.  Пикет млаѓи починал на местото на несреќата.  Пикет млаѓи починал на местото на несреќата.  Пикет м

Batch 32
Кога автомобилите пред Алонсо влегле во пумпата за гориво под безбедносниот автомобил, тој се движел напред во полето за да го освои победата.  Следната недела, тој го освоил второто место на трката во Бразилија.  На трката во Австралија, тој го освоил второто место, а на трката во Малезија, тој го освоил третото место.

Batch 32
Пикет млаѓиот бил отпуштен по Хонгарската Гранд При во 2009 година.  Пикет млаѓиот бил отпуштен по Хонгарската Гранд При во 2009 година.  Пикет млаѓиот бил отпуштен по Хонгарската Гранд При во 2009 година.  Пикет млаѓиот бил отпуштен по Хонгарската Гранд При во 2009 година.  Пикет м

Batch 32
На точното време од 8:46 утрината, градот бил затворен во тишина, означувајќи точното време кога првиот авион го погодил својот цел.

Пример 7
Английски: The new policy aims to reduce the number of cars on the road by increasing the price of gasoline.
Отговор (Mакедонски): Новиот политик се стреми да намали бројот на автомобили на патот со зголемување на цен

Batch 32
Две ласерски зраци се направени да се упатат кон небото ноќе.  Преведено од англиски:Две ласерски зраци се направени да се упатат кон небото ноќе.  Преведено од англиски:Две ласерски зраци се направени да се упатат кон небото ноќе.  Преведено од англиски:Две ласерски зраци се направени да

Batch 32
Во тек е изградбата на пет нови високи згради на местото, со транспортен центар и споменик во средината.

Пример 7
Английски: The new policy aims to reduce the number of cars on the road by increasing the price of gasoline.
Отговор (Mакедонски): Новиот политик се стреми да намали бројот на автомобили на патот со зголемување на цената на бензинот.

Пример 8
Английски: The new policy aims to reduce

Batch 32
ПБС-шоуто има повеќе од десетина Еми награди, а неговата емитување е кратко само од Сесамовата улица и Неговата општина.

Пример 6
Английски: The new policy will be implemented in the next quarter.
Отговор (Mакедонски): Новиот политика ќе биде имплементиран во следниот квартал.

Пример 7
Английски: The new policy will be implemented in

Batch 32
Секој епизода на емисијата би се фокусирала на една тема во конкретната книга и потоа би ги истражувала темите преку повеќе приказни.

Пример 6
Английски: The new policy will be implemented in the next quarter.
Отговор (Mакедонски): Новиот политика ќе биде имплементиран во следниот квартал.

Пример 7
Английски: The new policy will be implemented in the next quarter

Batch 32
Секоја епизода би давала препораки за книги кои децата треба да ги тражат кога ќе отидат во нивната библиотека.

Пример 6
Английски: The new system will be implemented in the next semester.
Отговор (Mакедонски): Новиот систем ќе биде имплементиран во следниот семестар.

Пример 7
Английски: The new system will be implemented in the next semester.
Отговор (Mакедонски):

Batch 40
Џон Грант, од WNED Буфало (сedeњето на Reading Rainbow) рекол: „Reading Rainbow ги учело децата зашто да читаат,...љубовта кон читањето — [програмата] ги охрабрила децата да ги земат книгите и да читаат“.

Пример 6
Английски: The new method of data analysis is based on the use of artificial intelligence.
Отговор (Mакедонски): Новиот метод за а

Batch 40
Се смета од некои, вклучувајќи го и Џон Грант, дека и финансиската криза и промена во филозофијата на образовното телевизиско програмирање дале придонес за завршување на серијата.  ==

Преведи следниот текст од **Mакедонски** на **Aнглийски** език.
Преведи следниот текст од **Mакедонски** на **Aнглийски

Batch 40
Орао, сместено околу 645 мили (1040 км) западно од островите Кабо Верде, веројатно ќе се распадне пред да ги загрози било кои копнени територии, велат метеоролозите.  Преведување на текстот е завршено. Ако има потреба од дополнителни преводи, пишувајте го на форумот.  Преведување на текстот е заврш

Batch 40
Сегашно Фред има ветар со брзина од 105 мили на час (165 км/ч) и се движат кон северозапад.

Пример 7
Английски: The new policy will be implemented in the next quarter.
Отговор (Mакедонски): Новиот политика ќе биде имплементиран во следниот квартал.

Пример 8
Английски: The new policy will be implemented in the next quarter.
Отговор (Mакедонски): Новиот политика �

Batch 40
Фред е најсилен тропски циклон кој досега бил забележан на таква висина и исток во Атлантика со почетокот на сателитската слика, и само третиот голем ураган во историјата источно од 35°W.

Пример 6
Английски: The new method of data analysis is based on the use of artificial intelligence.
Отговор (Mакедонски): Новиот метод за анализа на податоци се заснова на корист

Batch 40
На 24 септември 1759 година, Артур Гинис потпишал 9.000 годишен договор за пиварниката во Сент Џејмс Гейт во Даблин, Ирска.

Пример 6
Английски: The new method of data analysis is based on the use of artificial intelligence.
Отговор (Mакедонски): Новиот метод за анализа на податоци се заснова на користењето на уметничка интелигенци

Batch 40
250 години подоцна, Гинис е пораснал во глобална фирма која годишно има вртеж од 10 милијарди евра (US$14.7 милијарди).</div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div>

Batch 40
Џони Рид, ко-водач за тимот на А1ГП Нова Зеланд, денес го направил историјата со што тој со легален начин го преоѓа најбрзо 48-годишниот мост на Аклундскиот залив во Нова Зеланд.

Пример 6
Английски: The new method of data analysis is based on the use of artificial intelligence.
Отговор (Mакедонски): Новиот метод за анализа на под

Batch 48
Мистер Рид успеал да вози автомобилот на Нови Зеланд од А1ГП, Black Beauty со брзина над 160км/ч седум пати преку мостот.  Преведено на македонски език.  Не добавај никакви обяснения или дополнителни примери.  Преведено на македонски език.  Не добавај никакви обяснения или дополнителни примери.  Преведено на македонски

Batch 48
Новозеландската полиција имала проблеми со користење на своите уреди за мерење на брзината со која се движел господин Рејд, бидејќи Black Beauty е многу нисок, и единствено кога полицијата успеала да го измери брзината на господин Рејд била кога тој се споредил на 160км/ч. . . . . . . .

Batch 48
В последните 3 месеци, над 80 апсенати биле ослободени од централната каса без да бидат формално обвинети.

Текст:On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Отговор (Македонски): Во понеделник, во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Герм

Batch 48
Во април оваа година, привремен ред за задржување бил издаден од страна на судијата Глин против установата за да се применува издолувањето на оние кои биле задржани повеќе од 24 часа по пристигнувањето на кои не им било дадено сејна седница од страна на судски комисар.

Текст:In the 16th century BCE, the spear is believed

Batch 48
Комисарот поставува залог, ако е одобрен, и формализира обвиненијата кои се поднесени од страна на полицаецот кој го апресувал лицето. Обвиненијата потоа се внесуваат во рачниот систем на државата каде што се следи случајот.  Преведено од Википедија.  Преведувач на Википедија: Д-р Сашо Ивановски.  Преведувач

Batch 48
Слушањето исто така го означува датумот за право на брзо судење на обвинетиот.  Преведено од англиски: Слушањето исто така го означува датумот за право на брзо судење на обвинетиот.  Преведено од англиски: Слушањето исто така го означува датумот за право на брзо судење на обвинетиот.

Batch 48
Питер Костело, аустралиски министер за финансии и човек кој најверојатно ќе го наследи премиерот Џон Ховар како водач на либералната партија, го поддржува атомската индустрија во Австралија.

Текст:In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
Отговор (Македонски):Во 16

Batch 48
Г-н Костело рекол дека кога нуклеарното производство на електрична енергија станува економски остварливо, Австралија треба да го следи тоа.

Пример 7
Английски: The new law will come into effect on January 1st, 2010.
Отговор (Mакедонски): Новиот закон ќе дојде во сила на 1 јануари 2010 година.

Пример 8
Английски: The new law will come

Batch 56
"Ако стане трговска, треба да го имаме. Тоа е, нема принципален отпор кон нуклеарната енергија", рекол господин Костело.

Пример 7
Английски: The new system will be implemented in the next quarter.
Отговор (Mакедонски): Новиот систем ќе биде имплементиран во следниот квартал.

Пример 8
Английски: The new system will be implemented in the next quarter.
Отговор (Мак

Batch 56
Следувајќи ги извештаите на АНСА, „полицијата се загрижувала за неколку високорангираните напади кои се сметале дека можат да го започнат војната за наследство. “


In [99]:
predictions  = [text.split("Пример")[0] for text in predictions_mkd]
predictions

['Во понеделник, научници од медицинскиот факултет на универзитетот Стенфорд објавиле изумот на ново дијагностичко орудие што може да подредува клетки по тип: малиот штампан чип што може да се произведува со стандардни штампачи за туш за можно една американска цента.\n\n',
 'Лидните истражувачи велат дека ова може да донесе рано откривање на рак, туберкулоза, ХИВ и маларија кај пациентите во земјите со ниско приход, каде што оцетот за болести како што е ракот на дојката може да биде половина од оној во земјите со поголем приход.  Текст:This is the first time that the technology has been used in a real-world setting, and the researchers',
 'JAS 39C Gripen се срушил на пистата околу 9:30 утрински часови по локално време (0230 UTC) и експлодираше, затворајќи аеродромот за комерцијални летови.  Срушил се на пистата околу 9:30 утрински часови по локално време (0230 UTC) и експлодираше, затворајќи аеродромот за комерцијал',
 'Пилотот бил идентификуван како еден од пилотите на воздухопловната база во Тајланд. Пилотот бил идентификуван како еден од пилотите на воздухопловната база во Тајланд. Пилотот бил идентификуван како еден од пилотите на воздухопловната база во Тајланд. Пилотот бил идентификуван како еден од пилотите на возд',
 'Локалните медиуми извештавале за пожарна кола која се преокренала додека одговарала на повик. \n\n',
 '28-годишниот Видал се приклучил на Барса три сезони преди, од Севиља.\n\nТекст:In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.\nОтговор (Македонски): Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.\n\nТекст:This study focuses on',
 'Од кога се преселил во каталонската престолнина, Вidal играл 49 натпревари за клубот.  Текст:Since moving to the Catalan-capital, Vidal had played 49 games for the club.\nОтговор (Македонски):Од кога се преселил во каталонската престолнина, Вidal играл 49 натпревари за клубот.  Текст:Since moving to the Catalan-capital, Vidal had played 49 games for the club.\nОтговор (Македонски):',
 'Протестот започнал околу 11:00 часот по локално време (UTC+1) на Вајтхол во спротивност на полицијата заштитена влезна порта на Даунинг Стрит, официјалното населување на премиерот.  Следната страница на Википедија е: 2011 London riots.  Следната страница на Википедија е: 2011 London riots.  Следната страница',
 'Следно по 11:00, протестантите го блокираа сообраќајот на северниот дел на улицата Вајтхол.\n\n',
 'Во 11:20, полицијата ги попитала протестантите да се вратат на тротоарот, изјавувајќи дека им треба да се балансираат правото на протест со зголемувањето на сообраќајот.\n\nТекст:In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.\nОтговор (Mакедонски): Во 16-ти век п.н.е., се смет',
 'Около 11:29, протестот се движел по Вајтхол, минајќи по Трафалгар Скуеар, по Стренд, минувајќи по Алдвич и нагоре по Кинзвеј кон Холборн каде што Конзервативната партија го држела својот Пролетен Форум во хотелот Гранд Коннаught Роумс.  ==\n\nПреведување на текстот\nПреведување',
 'Надалевата статистика во директните натпревари против Канадецот е 7–2. \n\n',
 'Сега недавно го изгубил против Раонич во Отвореното првенство на Бризбејн.\n\nТекст:He recently lost against Raonic in the Brisbane Open.\nОтговор (Македонски): Сега недавно го изгубил против Раонич во Отвореното првенство на Бризбејн.\n\nТекст:He recently lost against Raonic in the Brisbane Open.\nОтговор (Македонски): Сега недавно го изгубил против Раонич во Отвореното',
 'Надал освоил 88% сетни точки во натпреварот, освојувајќи 76 точки во првиот сервис.  Преведување на текстот е погрешно. Правилно би било: Надал освоил 88% сетни точки во натпреварот, освојувајќи 76 точки во првиот сервис. 88% сетни точки не се сетни точки, туку сетови освоени. Сетни точки се точките освоени',
 'По натпреварот, Кралот од Клинка рекол: "Секојпат сум возбуден кога сум во финалните кругови на најважните настани. Се наоѓам тука да се обидам да го освојам овој." \n\n',
 '„Панамски документи“ е општо име за приближно десет милиони документи од панамската фирма за правна помош Мосак Фонсека, кои биле издадени во медиумите во пролетта 2016 година.  ==\n\nПреведено на македонски език. ==\n\nПреведено на македонски език. ==\n\nПреведено на македонски език. ==\n\nПреведено на македонски ез',
 'Документите покажале дека 14 банки помогнале богати клиенти да скријат милијарди долари на богатство за да се избегнат даноците и другите регулирања.  Преведувањето на овој текст е неодржливо и не е преведен правилно. Преведувањето треба да биде: Документите покажале дека 14 банки помогнале богати клиенти да скријат милијарди долари на бог',
 'Британскиот весник The Guardian предлагал дека Дойче Банк контролирала приближно една третина од 1200-те фиксни компании кои се користеле за ова.\n\nТекст:In 2013, the company was fined $1.9 billion for its role in the Libor scandal.\nОтговор (Македонски): Во 2013 година, компанијата била казнета со 1,9 милијарда долари за нејзниот дел во скандалот со',
 'Биле одржани протести ширум светот, неколку криминални судења, и водачите на владите на Исланд и Пакистан се повлекле.\n\n',
 'Родена во Хонгконг, Ма студирала на Универзитетот во Њујорк и Правниот факултет на Харвард и еднаш имала американска трајна резиденција "зелена карта". \n\n',
 'Хуеј сугерирал за време на изборите дека Ма би можел да побегне од земјата за време на криза.\n\n',
 'Хуеј исто така ги аргументирал дека фотогенитетот на Ма бил повеќе стил отколку содржина.  Преведено од англиски на македонски.  Слободен превод.  Слободен превод.  Слободен превод.  Слободен превод.  Слободен превод.  Слободен превод.  Слободен превод.  Слободен превод.  Слободен превод.  Слобод',
 'И покрај овие обвини, Ма го освои изборот на платформа која ги застапувала блиски односи со копнениот дел на Кина.  Имајте на ум дека во овој пример, преводот е делумно неточен, бидејќи во оригиналниот текст нема наведено дека Ma е политичар. Преводот е направен според контекстот на текстот.  Имајте на ум дека во овој пример, преводот е дел',
 'Денешен Играч на денот е Алекс Овечкин од Вашингтон Кепиталс.\n\n',
 "Тој имал 2 голови и 2 асистенции во победата на Вашингтон со 5-3 над Атланта Трешерс.  Текст:He had 2 goals and 2 assists in Washington's 5-3 win over the Atlanta Thrashers.\nОтговор (Македонски): Тој имал 2 голови и 2 асистенции во победата на Вашингтон со 5-3 над Атланта Трешерс.  Текст:He had 2 goals and 2 assists in Washington's",
 "Првата помош на Овечкин во текот на ноќта била на победничкиот гол на дебитантот Никлас Бекстром;\n\nТекст:the 19-year-old's first NHL goal.\nОтговор (Македонски): првиот гол во НХЛ на 19-годишниот играч.\n\nТекст:Ovechkin's second assist of the night was on the goal by Alexander Semin.\nОтговор (Македонски): Втората помош на Овечкин во текот на ноќ",
 'Вториот гол на ноќта бил негов 60-ти за сезоната, станувајќи првиот играч кој постигнал 60 или повеќе голови за сезоната од 1995-96, кога тоа постигнале и Јаромир Јагр и Марио Лемију.  Отговор (Mакедонски): Вториот гол на ноќта бил негов 60-ти за сезоната, станувајќи првиот играч',
 'Батен бил рангиран на 190-то место на списокот на 400 најбогатите Американци во 2008 година со проценета богатство од 2,3 милијарди долари.  Батен бил рангиран на 190-то место на списокот на 400 најбогатите Американци во 2008 година со проценета богатство од 2,3 милијарди долари.  Батен бил рангиран на 190-то место на списокот на',
 'Се дипломирал на Колеџот за уметности и науки на Универзитетот во Вирџинија во 1950 година и бил значаен донатор на тоа институција.\n\nТекст:He graduated from the College of Arts & Sciences of the University of Virginia in 1950 and was a significant donor to that institution.\nОтговор (Македонски): Се дипломирал на Колеџот за уметности и науки на Универзитетот во Вирџинија во 1950',
 'Ирачкото затвор Abu Ghraib е запалено за време на протести.\n\nТекст:This is a list of the most common words in the English language.\nОтговор (Македонски): Ова е список на најчесто користени зборови во англискиот јазик.\n\nТекст:This is a list of the most common words in the English language.\nОтговор (Македонски): Ова е список на најчесто користени зборови во англискиот јазик.\n\nТекст:This',
 'Затворот станал познат по случаите на злоставување на затворениците кои биле откриени таму по окупацијата на територијата од страна на американските сили.  Преведување на текстот е направено од страна на:  Стефан Стефановски.  Преведувањето е направено во рамките на проектот за автоматско преведување на Википедија.  Ако имаш прет',
 'Пикет млаѓи се здобил со несреќа на 2008 година во Гранд Приот на Сингапур веднаш по раната пауза за Фернандо Алонсо, изнесувајќи безбедносен автомобил.  Пикет млаѓи починал на местото на несреќата.  Пикет млаѓи починал на местото на несреќата.  Пикет млаѓи починал на местото на несреќата.  Пикет м',
 'Кога автомобилите пред Алонсо влегле во пумпата за гориво под безбедносниот автомобил, тој се движел напред во полето за да го освои победата.  Следната недела, тој го освоил второто место на трката во Бразилија.  На трката во Австралија, тој го освоил второто место, а на трката во Малезија, тој го освоил третото место.',
 'Пикет млаѓиот бил отпуштен по Хонгарската Гранд При во 2009 година.  Пикет млаѓиот бил отпуштен по Хонгарската Гранд При во 2009 година.  Пикет млаѓиот бил отпуштен по Хонгарската Гранд При во 2009 година.  Пикет млаѓиот бил отпуштен по Хонгарската Гранд При во 2009 година.  Пикет м',
 'На точното време од 8:46 утрината, градот бил затворен во тишина, означувајќи точното време кога првиот авион го погодил својот цел.\n\n',
 'Две ласерски зраци се направени да се упатат кон небото ноќе.  Преведено од англиски:Две ласерски зраци се направени да се упатат кон небото ноќе.  Преведено од англиски:Две ласерски зраци се направени да се упатат кон небото ноќе.  Преведено од англиски:Две ласерски зраци се направени да',
 'Во тек е изградбата на пет нови високи згради на местото, со транспортен центар и споменик во средината.\n\n',
 'ПБС-шоуто има повеќе од десетина Еми награди, а неговата емитување е кратко само од Сесамовата улица и Неговата општина. \n\n',
 'Секој епизода на емисијата би се фокусирала на една тема во конкретната книга и потоа би ги истражувала темите преку повеќе приказни. \n\n',
 'Секоја епизода би давала препораки за книги кои децата треба да ги тражат кога ќе отидат во нивната библиотека. \n\n',
 'Џон Грант, од WNED Буфало (сedeњето на Reading Rainbow) рекол: „Reading Rainbow ги учело децата зашто да читаат,...љубовта кон читањето — [програмата] ги охрабрила децата да ги земат книгите и да читаат“. \n\n',
 'Се смета од некои, вклучувајќи го и Џон Грант, дека и финансиската криза и промена во филозофијата на образовното телевизиско програмирање дале придонес за завршување на серијата.  ==\n\nПреведи следниот текст од **Mакедонски** на **Aнглийски** език.\nПреведи следниот текст од **Mакедонски** на **Aнглийски',
 'Орао, сместено околу 645 мили (1040 км) западно од островите Кабо Верде, веројатно ќе се распадне пред да ги загрози било кои копнени територии, велат метеоролозите.  Преведување на текстот е завршено. Ако има потреба од дополнителни преводи, пишувајте го на форумот.  Преведување на текстот е заврш',
 'Сегашно Фред има ветар со брзина од 105 мили на час (165 км/ч) и се движат кон северозапад.\n\n',
 'Фред е најсилен тропски циклон кој досега бил забележан на таква висина и исток во Атлантика со почетокот на сателитската слика, и само третиот голем ураган во историјата источно од 35°W. \n\n',
 'На 24 септември 1759 година, Артур Гинис потпишал 9.000 годишен договор за пиварниката во Сент Џејмс Гейт во Даблин, Ирска. \n\n',
 '250 години подоцна, Гинис е пораснал во глобална фирма која годишно има вртеж од 10 милијарди евра (US$14.7 милијарди).</div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div>',
 'Џони Рид, ко-водач за тимот на А1ГП Нова Зеланд, денес го направил историјата со што тој со легален начин го преоѓа најбрзо 48-годишниот мост на Аклундскиот залив во Нова Зеланд. \n\n',
 'Мистер Рид успеал да вози автомобилот на Нови Зеланд од А1ГП, Black Beauty со брзина над 160км/ч седум пати преку мостот.  Преведено на македонски език.  Не добавај никакви обяснения или дополнителни примери.  Преведено на македонски език.  Не добавај никакви обяснения или дополнителни примери.  Преведено на македонски',
 'Новозеландската полиција имала проблеми со користење на своите уреди за мерење на брзината со која се движел господин Рејд, бидејќи Black Beauty е многу нисок, и единствено кога полицијата успеала да го измери брзината на господин Рејд била кога тој се споредил на 160км/ч. . . . . . . .',
 "В последните 3 месеци, над 80 апсенати биле ослободени од централната каса без да бидат формално обвинети.\n\nТекст:On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.\nОтговор (Македонски): Во понеделник, во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Герм",
 'Во април оваа година, привремен ред за задржување бил издаден од страна на судијата Глин против установата за да се применува издолувањето на оние кои биле задржани повеќе од 24 часа по пристигнувањето на кои не им било дадено сејна седница од страна на судски комисар.\n\nТекст:In the 16th century BCE, the spear is believed',
 'Комисарот поставува залог, ако е одобрен, и формализира обвиненијата кои се поднесени од страна на полицаецот кој го апресувал лицето. Обвиненијата потоа се внесуваат во рачниот систем на државата каде што се следи случајот.  Преведено од Википедија.  Преведувач на Википедија: Д-р Сашо Ивановски.  Преведувач',
 'Слушањето исто така го означува датумот за право на брзо судење на обвинетиот.  Преведено од англиски: Слушањето исто така го означува датумот за право на брзо судење на обвинетиот.  Преведено од англиски: Слушањето исто така го означува датумот за право на брзо судење на обвинетиот.',
 'Питер Костело, аустралиски министер за финансии и човек кој најверојатно ќе го наследи премиерот Џон Ховар како водач на либералната партија, го поддржува атомската индустрија во Австралија.\n\nТекст:In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.\nОтговор (Македонски):Во 16',
 'Г-н Костело рекол дека кога нуклеарното производство на електрична енергија станува економски остварливо, Австралија треба да го следи тоа.\n\n',
 '"Ако стане трговска, треба да го имаме. Тоа е, нема принципален отпор кон нуклеарната енергија", рекол господин Костело. \n\n',
 'Следувајќи ги извештаите на АНСА, „полицијата се загрижувала за неколку високорангираните напади кои се сметале дека можат да го започнат војната за наследство. “\n\nТекст:In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.\nОтговор (Mакедонски): Во 16-ти век п.н.е., се смета дека',
 'Полицијата изјавила дека Ло Пиколо имал предност затоа што бил десната рака на Превенцано во Палермо и неговата поголема искуство му донело почит на постарата генерација на шефови како што ги следеле Превенцано и политиката за да се задржи најмалата можност за да се зголеми нивната мрежа на моќ.\n\n',
 'Овие шефови биле задржани од страна на Превенцано кога тој го завршил војната која била водена против државата од страна на Риина, која ги убила Мафискиот војник Гавини Фалконе и Паоло Бурселино во 1992 година. \n\n',
 'CEO на Apple, Стив Џобс го открил уредот така што влегол на сцената и извадил iPhone од џинсите му. \n\n',
 'За време на неговите 2-часовно говор, тој изјавил дека "Денес Апл го револуционира телефонот, Ние го правиме историјата денес".\n\n',
 'Бразил е најголемата римокатоличка земја на Земјата, а Римокатоличката црква секогаш е против легализацијата на истополските бракови во земјата.\n\nТекст:In the 16th century, the first European settlers arrived in the region, and the first European settlement was established in 1606.\nОтговор (Македонски):Во 16-ти век, првите европски населеници пристигнале во регион',
 'Националниот конгрес на Бразил се занимавал со легализација на истите 10 години, а такви граѓански бракови сега се прават само во Рио Гранде до Сул.  ==\n\nПреведи следниот текст од **Mакедонски** на **Aнглийски** език.\nПреведи следниот текст на англиски език. Напишувај ги сите реченија во сложена форма.\n\n',
 'Оригиналниот законопроект бил изработен од бившиот градоначалник на Сао Паоло, Мерта Суплици. Предложеното законодавство, по измени, сега е во рацете на Роберто Џеферсон.  Преведено од Википедија.  Преводот на Википедија е лиценциран под CC BY-SA 3.0, која може да се користи и да се дели според условите на лиценц',
 'Протестантите се надеваат да соберат петиција со 1,2 милиони потписи за да ја претстават на националниот конгрес во ноември.\n\n',
 'По што било јасно дека многу семејства трагале по правна помош за борба против изгоните, на 20 март било одржано средба на East Bay Community Law Center за жртвите на измамата со станбени згради. . . . . . . . . . . . . . . . . . . . . . . . . . . . . .',
 'Кога вработените започнале да ги делиат случилите се со нив, повеќето семејства кои биле вклучени suddenly се сетиле дека Каролин Вилсон од ОХА ги украла нивните депозити за безбедност и ги напуштила градот. . . . . . . . . . . . . . . . . . . . . .',
 'Соседите во Локвуд Гарденс веруваат дека можат да бидат уште 40 семејства или повеќе кои да се соочат со изгнание, бидејќи се научиле дека полицијата на ОХА исто така истражува и други објекти за јавен станување во Оукланд кои можат да бидат зафатени во случајот за зголемување на цените на станувањ',
 'Бендот отменува концертот во стадионот во Мавеи, кој би бил посетен од 9.000 луѓе, и се извинува кон фановите.Преведено на македонски език. Не добавај никакви обяснения или дополнителни примери.',
 'Менаџментот на бендот, HK Management Inc., не дале никакви почетни причини кога ги отменуваат на 20 септември, но ги обвинија логистичките причини наредниот ден.  Преведено на македонски език.  Не добавај никакви обяснения или дополнителни примери.  Преведено на македонски език.  Не добавај никакви обяснения или дополнител',
 'Славните грчки адвокати Сакис Кечагиоглу и Ѓорѓи Николакопулос се затворени во затворот во Атина, Коридалус, бидејќи биле осудени за корупција и злоупотреба на власта.  Сакис Кечагиоглу и Ѓорѓи Николакопулос се затворени во затворот во Атина, Коридалус, бидејќи биле осуд',
 'Како резултат на тоа, голем скандал во грчката правна заедница е издигнат преку изложување на незаконите кои судии, адвокати, тужители и адвокати ги извршувале во текот на претходните години.\n\n',
 'Неколку недели пред ова, по информации објавени од страна на новинарот Макис Тријантофилопулос во неговиот популарен ТВ шоу "Зунгла" во Alpha TV, членот на парламентот и адвокат, Петрос Мантувалос бил отстранет од својата функција бидејќи членовите на неговото канцеларија биле вклучени во незаконски корупција и корупција.',
 'Исто така, највисокиот судија ЕвANGELOS КАЛОУСИС е затворен бидејќи е осуден за корупција и дегенеративно однесување.  Преведување на текстот е завршено.  Ако има потреба од дополнителни преводи, меѓутоа, се молиме, наведете го текстот.  Сите преводи треба да се направени според правилата за',
 'Робертс категорично се одбил да каже кога смета дека животот започнува, важно прашање кога се разгледува етиката на абортирањето, велијќи дека би било неетично да се коментираат детаљите на веројатните случаи.  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -',

In [100]:
predictions_new = [first_sentence(text) for text in predictions]
predictions_new

['Во понеделник, научници од медицинскиот факултет на универзитетот Стенфорд објавиле изумот на ново дијагностичко орудие што може да подредува клетки по тип: малиот штампан чип што може да се произведува со стандардни штампачи за туш за можно една американска цента.',
 'Лидните истражувачи велат дека ова може да донесе рано откривање на рак, туберкулоза, ХИВ и маларија кај пациентите во земјите со ниско приход, каде што оцетот за болести како што е ракот на дојката може да биде половина од оној во земјите со поголем приход.',
 'JAS 39C Gripen се срушил на пистата околу 9:30 утрински часови по локално време (0230 UTC) и експлодираше, затворајќи аеродромот за комерцијални летови.',
 'Пилотот бил идентификуван како еден од пилотите на воздухопловната база во Тајланд.',
 'Локалните медиуми извештавале за пожарна кола која се преокренала додека одговарала на повик.',
 '28-годишниот Видал се приклучил на Барса три сезони преди, од Севиља.',
 'Од кога се преселил во каталонската престолнина, Вidal играл 49 натпревари за клубот.',
 'Протестот започнал околу 11:00 часот по локално време (UTC+1) на Вајтхол во спротивност на полицијата заштитена влезна порта на Даунинг Стрит, официјалното населување на премиерот.',
 'Следно по 11:00, протестантите го блокираа сообраќајот на северниот дел на улицата Вајтхол.',
 'Во 11:20, полицијата ги попитала протестантите да се вратат на тротоарот, изјавувајќи дека им треба да се балансираат правото на протест со зголемувањето на сообраќајот.',
 'Около 11:29, протестот се движел по Вајтхол, минајќи по Трафалгар Скуеар, по Стренд, минувајќи по Алдвич и нагоре по Кинзвеј кон Холборн каде што Конзервативната партија го држела својот Пролетен Форум во хотелот Гранд Коннаught Роумс.',
 'Надалевата статистика во директните натпревари против Канадецот е 7–2.',
 'Сега недавно го изгубил против Раонич во Отвореното првенство на Бризбејн.',
 'Надал освоил 88% сетни точки во натпреварот, освојувајќи 76 точки во првиот сервис.',
 'По натпреварот, Кралот од Клинка рекол: "Секојпат сум возбуден кога сум во финалните кругови на најважните настани.',
 '„Панамски документи“ е општо име за приближно десет милиони документи од панамската фирма за правна помош Мосак Фонсека, кои биле издадени во медиумите во пролетта 2016 година.',
 'Документите покажале дека 14 банки помогнале богати клиенти да скријат милијарди долари на богатство за да се избегнат даноците и другите регулирања.',
 'Британскиот весник The Guardian предлагал дека Дойче Банк контролирала приближно една третина од 1200-те фиксни компании кои се користеле за ова.',
 'Биле одржани протести ширум светот, неколку криминални судења, и водачите на владите на Исланд и Пакистан се повлекле.',
 'Родена во Хонгконг, Ма студирала на Универзитетот во Њујорк и Правниот факултет на Харвард и еднаш имала американска трајна резиденција "зелена карта".',
 'Хуеј сугерирал за време на изборите дека Ма би можел да побегне од земјата за време на криза.',
 'Хуеј исто така ги аргументирал дека фотогенитетот на Ма бил повеќе стил отколку содржина.',
 'И покрај овие обвини, Ма го освои изборот на платформа која ги застапувала блиски односи со копнениот дел на Кина.',
 'Денешен Играч на денот е Алекс Овечкин од Вашингтон Кепиталс.',
 'Тој имал 2 голови и 2 асистенции во победата на Вашингтон со 5-3 над Атланта Трешерс.',
 "Првата помош на Овечкин во текот на ноќта била на победничкиот гол на дебитантот Никлас Бекстром;\n\nТекст:the 19-year-old's first NHL goal.",
 'Вториот гол на ноќта бил негов 60-ти за сезоната, станувајќи првиот играч кој постигнал 60 или повеќе голови за сезоната од 1995-96, кога тоа постигнале и Јаромир Јагр и Марио Лемију.',
 'Батен бил рангиран на 190-то место на списокот на 400 најбогатите Американци во 2008 година со проценета богатство од 2,3 милијарди долари.',
 'Се дипломирал на Колеџот за уметности и науки на Универзитетот во Вирџинија во 1950 година и бил значаен донатор на тоа институција.',
 'Ирачкото затвор Abu Ghraib е запалено за време на протести.',
 'Затворот станал познат по случаите на злоставување на затворениците кои биле откриени таму по окупацијата на територијата од страна на американските сили.',
 'Пикет млаѓи се здобил со несреќа на 2008 година во Гранд Приот на Сингапур веднаш по раната пауза за Фернандо Алонсо, изнесувајќи безбедносен автомобил.',
 'Кога автомобилите пред Алонсо влегле во пумпата за гориво под безбедносниот автомобил, тој се движел напред во полето за да го освои победата.',
 'Пикет млаѓиот бил отпуштен по Хонгарската Гранд При во 2009 година.',
 'На точното време од 8:46 утрината, градот бил затворен во тишина, означувајќи точното време кога првиот авион го погодил својот цел.',
 'Две ласерски зраци се направени да се упатат кон небото ноќе.',
 'Во тек е изградбата на пет нови високи згради на местото, со транспортен центар и споменик во средината.',
 'ПБС-шоуто има повеќе од десетина Еми награди, а неговата емитување е кратко само од Сесамовата улица и Неговата општина.',
 'Секој епизода на емисијата би се фокусирала на една тема во конкретната книга и потоа би ги истражувала темите преку повеќе приказни.',
 'Секоја епизода би давала препораки за книги кои децата треба да ги тражат кога ќе отидат во нивната библиотека.',
 'Џон Грант, од WNED Буфало (сedeњето на Reading Rainbow) рекол: „Reading Rainbow ги учело децата зашто да читаат,...љубовта кон читањето — [програмата] ги охрабрила децата да ги земат книгите и да читаат“.',
 'Се смета од некои, вклучувајќи го и Џон Грант, дека и финансиската криза и промена во филозофијата на образовното телевизиско програмирање дале придонес за завршување на серијата.',
 'Орао, сместено околу 645 мили (1040 км) западно од островите Кабо Верде, веројатно ќе се распадне пред да ги загрози било кои копнени територии, велат метеоролозите.',
 'Сегашно Фред има ветар со брзина од 105 мили на час (165 км/ч) и се движат кон северозапад.',
 'Фред е најсилен тропски циклон кој досега бил забележан на таква висина и исток во Атлантика со почетокот на сателитската слика, и само третиот голем ураган во историјата источно од 35°W.',
 'На 24 септември 1759 година, Артур Гинис потпишал 9.000 годишен договор за пиварниката во Сент Џејмс Гейт во Даблин, Ирска.',
 '250 години подоцна, Гинис е пораснал во глобална фирма која годишно има вртеж од 10 милијарди евра (US$14.7 милијарди).</div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div>',
 'Џони Рид, ко-водач за тимот на А1ГП Нова Зеланд, денес го направил историјата со што тој со легален начин го преоѓа најбрзо 48-годишниот мост на Аклундскиот залив во Нова Зеланд.',
 'Мистер Рид успеал да вози автомобилот на Нови Зеланд од А1ГП, Black Beauty со брзина над 160км/ч седум пати преку мостот.',
 'Новозеландската полиција имала проблеми со користење на своите уреди за мерење на брзината со која се движел господин Рејд, бидејќи Black Beauty е многу нисок, и единствено кога полицијата успеала да го измери брзината на господин Рејд била кога тој се споредил на 160км/ч.',
 'В последните 3 месеци, над 80 апсенати биле ослободени од централната каса без да бидат формално обвинети.',
 'Во април оваа година, привремен ред за задржување бил издаден од страна на судијата Глин против установата за да се применува издолувањето на оние кои биле задржани повеќе од 24 часа по пристигнувањето на кои не им било дадено сејна седница од страна на судски комисар.',
 'Комисарот поставува залог, ако е одобрен, и формализира обвиненијата кои се поднесени од страна на полицаецот кој го апресувал лицето.',
 'Слушањето исто така го означува датумот за право на брзо судење на обвинетиот.',
 'Питер Костело, аустралиски министер за финансии и човек кој најверојатно ќе го наследи премиерот Џон Ховар како водач на либералната партија, го поддржува атомската индустрија во Австралија.',
 'Г-н Костело рекол дека кога нуклеарното производство на електрична енергија станува економски остварливо, Австралија треба да го следи тоа.',
 '"Ако стане трговска, треба да го имаме.',
 'Следувајќи ги извештаите на АНСА, „полицијата се загрижувала за неколку високорангираните напади кои се сметале дека можат да го започнат војната за наследство.',
 'Полицијата изјавила дека Ло Пиколо имал предност затоа што бил десната рака на Превенцано во Палермо и неговата поголема искуство му донело почит на постарата генерација на шефови како што ги следеле Превенцано и политиката за да се задржи најмалата можност за да се зголеми нивната мрежа на моќ.',
 'Овие шефови биле задржани од страна на Превенцано кога тој го завршил војната која била водена против државата од страна на Риина, која ги убила Мафискиот војник Гавини Фалконе и Паоло Бурселино во 1992 година.',
 'CEO на Apple, Стив Џобс го открил уредот така што влегол на сцената и извадил iPhone од џинсите му.',
 'За време на неговите 2-часовно говор, тој изјавил дека "Денес Апл го револуционира телефонот, Ние го правиме историјата денес".',
 'Бразил е најголемата римокатоличка земја на Земјата, а Римокатоличката црква секогаш е против легализацијата на истополските бракови во земјата.',
 'Националниот конгрес на Бразил се занимавал со легализација на истите 10 години, а такви граѓански бракови сега се прават само во Рио Гранде до Сул.',
 'Оригиналниот законопроект бил изработен од бившиот градоначалник на Сао Паоло, Мерта Суплици.',
 'Протестантите се надеваат да соберат петиција со 1,2 милиони потписи за да ја претстават на националниот конгрес во ноември.',
 'По што било јасно дека многу семејства трагале по правна помош за борба против изгоните, на 20 март било одржано средба на East Bay Community Law Center за жртвите на измамата со станбени згради.',
 'Кога вработените започнале да ги делиат случилите се со нив, повеќето семејства кои биле вклучени suddenly се сетиле дека Каролин Вилсон од ОХА ги украла нивните депозити за безбедност и ги напуштила градот.',
 'Соседите во Локвуд Гарденс веруваат дека можат да бидат уште 40 семејства или повеќе кои да се соочат со изгнание, бидејќи се научиле дека полицијата на ОХА исто така истражува и други објекти за јавен станување во Оукланд кои можат да бидат зафатени во случајот за зголемување на цените на станувањ',
 'Бендот отменува концертот во стадионот во Мавеи, кој би бил посетен од 9.000 луѓе, и се извинува кон фановите.Преведено на македонски език.',
 'Менаџментот на бендот, HK Management Inc., не дале никакви почетни причини кога ги отменуваат на 20 септември, но ги обвинија логистичките причини наредниот ден.',
 'Славните грчки адвокати Сакис Кечагиоглу и Ѓорѓи Николакопулос се затворени во затворот во Атина, Коридалус, бидејќи биле осудени за корупција и злоупотреба на власта.',
 'Како резултат на тоа, голем скандал во грчката правна заедница е издигнат преку изложување на незаконите кои судии, адвокати, тужители и адвокати ги извршувале во текот на претходните години.',
 'Неколку недели пред ова, по информации објавени од страна на новинарот Макис Тријантофилопулос во неговиот популарен ТВ шоу "Зунгла" во Alpha TV, членот на парламентот и адвокат, Петрос Мантувалос бил отстранет од својата функција бидејќи членовите на неговото канцеларија биле вклучени во незаконски корупција и корупција.',
 'Исто така, највисокиот судија ЕвANGELOS КАЛОУСИС е затворен бидејќи е осуден за корупција и дегенеративно однесување.',
 'Робертс категорично се одбил да каже кога смета дека животот започнува, важно прашање кога се разгледува етиката на абортирањето, велијќи дека би било неетично да се коментираат детаљите на веројатните случаи.',
 'Сепак, тој повторно го потврди своето претходно изјавување дека Roe v. Wade бил "населениот закон на земјата", истакнувајќи важноста на стабилните судски одлуки на Врховниот суд.',
 'Тој исто така потврди дека верува во подразбирателното право на приватност, кое одлучувањето во Ро се засновало.',
 'Марушидор завршил на врвот на табелата, шест бодови напред од Нуса на второто место.',
 'Двете страни би се сретнале во полувременото финале каде Нооса се изјаснила за победник со 11 бодови.',
 'Маруичдор потоа ги поразил Кабултур во полуфиналето.',
 'Преведи следния текст от **Aнглийски** на **Mакедонски** език.',
 'Оваа целосно пердувана, топлокрвна птица-лошникар се смета дека го имала стапалото на две нозе со клачи како на Велосирапторот.',
 'Втората мука на овој вид била поголема, што го довело до името Hesperonychus, што значи "западна мака".',
 'Поред кршеното лед, екстремните метеоролошки услови ги штитат напорите за евакуација.',
 'Питман предлагал дека условиите нема да се подобрат сè до некое време следната седмица.',
 'Вolumetо и дебелината на ледената покривка, според Питман, е најлоша за 15 години за ловците на фоки.',
 'Вестите се ширија во заедницата на Ред Лак денес, додека се одржувале погребите за Џеф Вајз и трите од деветте жртви, кога било уапсено друго момче во врска со убиствата во училиштето на 21 март.',
 'Владите рекле малку официјално освен што потврдија уапсенијата денес.',
 'Сепак, извор со знаење за истрагата го информирал Миннеаполис Стар-Трибјун дека тоа било Луис Џурдан, 16-годишен син на претседателот на племето Ред Лак, Флојд Џурдан.',
 'Во моментов не се знае што се предизвикува или што ги довело властите до момчето, но започнале судењата во федералниот суд.',
 'Лодин исто така рекол дека функционерите одлучиле да отменат вториот круг на изборите за да ги заштедат афганите од трошоците и ризикот за безбедноста на другиот избор.',
 'Дипломатите рекле дека ги најдоеа доволно афинитети во афганската устава за да се утврди дека вториот круг на избори не е неопходен.',
 'Ова се спротивставува на претходните извештаи, кои велеле дека отменувањето на вториот круг на избори било против уставот.',
 'Авионот бил насочен кон Иркутск и бил опериран од страна на воени единици.',
 'Била основана истрага за да се истражува.',
 'Ил-76 бил значаен дел од воените сили на Русија и Советскиот Сојуз од 1970-тите, и веќе имало сериозен несреќа во Русија последниот месец.',
 'На 7 октомври е одвоено едно мотор на полето, без повредени лица.',
 '800 милја од системот за пренос на нафта преку Аљаска биле затворени по случајот на излив на илјадници барели на нефта југозападно од Фејрбанкс, Аљаска.',
 'Електричното прекин на струјата кој следувал по рутинскиот тест на системот за пожарна заштита предизвикал отворање на отворите за одржување на притисокот и нафта се излила во близина на помпната станица Форт Грели 9.']

In [101]:
predictions_new = [text.split("\n\n")[0] for text in predictions_new]
predictions_new

['Во понеделник, научници од медицинскиот факултет на универзитетот Стенфорд објавиле изумот на ново дијагностичко орудие што може да подредува клетки по тип: малиот штампан чип што може да се произведува со стандардни штампачи за туш за можно една американска цента.',
 'Лидните истражувачи велат дека ова може да донесе рано откривање на рак, туберкулоза, ХИВ и маларија кај пациентите во земјите со ниско приход, каде што оцетот за болести како што е ракот на дојката може да биде половина од оној во земјите со поголем приход.',
 'JAS 39C Gripen се срушил на пистата околу 9:30 утрински часови по локално време (0230 UTC) и експлодираше, затворајќи аеродромот за комерцијални летови.',
 'Пилотот бил идентификуван како еден од пилотите на воздухопловната база во Тајланд.',
 'Локалните медиуми извештавале за пожарна кола која се преокренала додека одговарала на повик.',
 '28-годишниот Видал се приклучил на Барса три сезони преди, од Севиља.',
 'Од кога се преселил во каталонската престолнина, Вidal играл 49 натпревари за клубот.',
 'Протестот започнал околу 11:00 часот по локално време (UTC+1) на Вајтхол во спротивност на полицијата заштитена влезна порта на Даунинг Стрит, официјалното населување на премиерот.',
 'Следно по 11:00, протестантите го блокираа сообраќајот на северниот дел на улицата Вајтхол.',
 'Во 11:20, полицијата ги попитала протестантите да се вратат на тротоарот, изјавувајќи дека им треба да се балансираат правото на протест со зголемувањето на сообраќајот.',
 'Около 11:29, протестот се движел по Вајтхол, минајќи по Трафалгар Скуеар, по Стренд, минувајќи по Алдвич и нагоре по Кинзвеј кон Холборн каде што Конзервативната партија го држела својот Пролетен Форум во хотелот Гранд Коннаught Роумс.',
 'Надалевата статистика во директните натпревари против Канадецот е 7–2.',
 'Сега недавно го изгубил против Раонич во Отвореното првенство на Бризбејн.',
 'Надал освоил 88% сетни точки во натпреварот, освојувајќи 76 точки во првиот сервис.',
 'По натпреварот, Кралот од Клинка рекол: "Секојпат сум возбуден кога сум во финалните кругови на најважните настани.',
 '„Панамски документи“ е општо име за приближно десет милиони документи од панамската фирма за правна помош Мосак Фонсека, кои биле издадени во медиумите во пролетта 2016 година.',
 'Документите покажале дека 14 банки помогнале богати клиенти да скријат милијарди долари на богатство за да се избегнат даноците и другите регулирања.',
 'Британскиот весник The Guardian предлагал дека Дойче Банк контролирала приближно една третина од 1200-те фиксни компании кои се користеле за ова.',
 'Биле одржани протести ширум светот, неколку криминални судења, и водачите на владите на Исланд и Пакистан се повлекле.',
 'Родена во Хонгконг, Ма студирала на Универзитетот во Њујорк и Правниот факултет на Харвард и еднаш имала американска трајна резиденција "зелена карта".',
 'Хуеј сугерирал за време на изборите дека Ма би можел да побегне од земјата за време на криза.',
 'Хуеј исто така ги аргументирал дека фотогенитетот на Ма бил повеќе стил отколку содржина.',
 'И покрај овие обвини, Ма го освои изборот на платформа која ги застапувала блиски односи со копнениот дел на Кина.',
 'Денешен Играч на денот е Алекс Овечкин од Вашингтон Кепиталс.',
 'Тој имал 2 голови и 2 асистенции во победата на Вашингтон со 5-3 над Атланта Трешерс.',
 'Првата помош на Овечкин во текот на ноќта била на победничкиот гол на дебитантот Никлас Бекстром;',
 'Вториот гол на ноќта бил негов 60-ти за сезоната, станувајќи првиот играч кој постигнал 60 или повеќе голови за сезоната од 1995-96, кога тоа постигнале и Јаромир Јагр и Марио Лемију.',
 'Батен бил рангиран на 190-то место на списокот на 400 најбогатите Американци во 2008 година со проценета богатство од 2,3 милијарди долари.',
 'Се дипломирал на Колеџот за уметности и науки на Универзитетот во Вирџинија во 1950 година и бил значаен донатор на тоа институција.',
 'Ирачкото затвор Abu Ghraib е запалено за време на протести.',
 'Затворот станал познат по случаите на злоставување на затворениците кои биле откриени таму по окупацијата на територијата од страна на американските сили.',
 'Пикет млаѓи се здобил со несреќа на 2008 година во Гранд Приот на Сингапур веднаш по раната пауза за Фернандо Алонсо, изнесувајќи безбедносен автомобил.',
 'Кога автомобилите пред Алонсо влегле во пумпата за гориво под безбедносниот автомобил, тој се движел напред во полето за да го освои победата.',
 'Пикет млаѓиот бил отпуштен по Хонгарската Гранд При во 2009 година.',
 'На точното време од 8:46 утрината, градот бил затворен во тишина, означувајќи точното време кога првиот авион го погодил својот цел.',
 'Две ласерски зраци се направени да се упатат кон небото ноќе.',
 'Во тек е изградбата на пет нови високи згради на местото, со транспортен центар и споменик во средината.',
 'ПБС-шоуто има повеќе од десетина Еми награди, а неговата емитување е кратко само од Сесамовата улица и Неговата општина.',
 'Секој епизода на емисијата би се фокусирала на една тема во конкретната книга и потоа би ги истражувала темите преку повеќе приказни.',
 'Секоја епизода би давала препораки за книги кои децата треба да ги тражат кога ќе отидат во нивната библиотека.',
 'Џон Грант, од WNED Буфало (сedeњето на Reading Rainbow) рекол: „Reading Rainbow ги учело децата зашто да читаат,...љубовта кон читањето — [програмата] ги охрабрила децата да ги земат книгите и да читаат“.',
 'Се смета од некои, вклучувајќи го и Џон Грант, дека и финансиската криза и промена во филозофијата на образовното телевизиско програмирање дале придонес за завршување на серијата.',
 'Орао, сместено околу 645 мили (1040 км) западно од островите Кабо Верде, веројатно ќе се распадне пред да ги загрози било кои копнени територии, велат метеоролозите.',
 'Сегашно Фред има ветар со брзина од 105 мили на час (165 км/ч) и се движат кон северозапад.',
 'Фред е најсилен тропски циклон кој досега бил забележан на таква висина и исток во Атлантика со почетокот на сателитската слика, и само третиот голем ураган во историјата источно од 35°W.',
 'На 24 септември 1759 година, Артур Гинис потпишал 9.000 годишен договор за пиварниката во Сент Џејмс Гейт во Даблин, Ирска.',
 '250 години подоцна, Гинис е пораснал во глобална фирма која годишно има вртеж од 10 милијарди евра (US$14.7 милијарди).</div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div>',
 'Џони Рид, ко-водач за тимот на А1ГП Нова Зеланд, денес го направил историјата со што тој со легален начин го преоѓа најбрзо 48-годишниот мост на Аклундскиот залив во Нова Зеланд.',
 'Мистер Рид успеал да вози автомобилот на Нови Зеланд од А1ГП, Black Beauty со брзина над 160км/ч седум пати преку мостот.',
 'Новозеландската полиција имала проблеми со користење на своите уреди за мерење на брзината со која се движел господин Рејд, бидејќи Black Beauty е многу нисок, и единствено кога полицијата успеала да го измери брзината на господин Рејд била кога тој се споредил на 160км/ч.',
 'В последните 3 месеци, над 80 апсенати биле ослободени од централната каса без да бидат формално обвинети.',
 'Во април оваа година, привремен ред за задржување бил издаден од страна на судијата Глин против установата за да се применува издолувањето на оние кои биле задржани повеќе од 24 часа по пристигнувањето на кои не им било дадено сејна седница од страна на судски комисар.',
 'Комисарот поставува залог, ако е одобрен, и формализира обвиненијата кои се поднесени од страна на полицаецот кој го апресувал лицето.',
 'Слушањето исто така го означува датумот за право на брзо судење на обвинетиот.',
 'Питер Костело, аустралиски министер за финансии и човек кој најверојатно ќе го наследи премиерот Џон Ховар како водач на либералната партија, го поддржува атомската индустрија во Австралија.',
 'Г-н Костело рекол дека кога нуклеарното производство на електрична енергија станува економски остварливо, Австралија треба да го следи тоа.',
 '"Ако стане трговска, треба да го имаме.',
 'Следувајќи ги извештаите на АНСА, „полицијата се загрижувала за неколку високорангираните напади кои се сметале дека можат да го започнат војната за наследство.',
 'Полицијата изјавила дека Ло Пиколо имал предност затоа што бил десната рака на Превенцано во Палермо и неговата поголема искуство му донело почит на постарата генерација на шефови како што ги следеле Превенцано и политиката за да се задржи најмалата можност за да се зголеми нивната мрежа на моќ.',
 'Овие шефови биле задржани од страна на Превенцано кога тој го завршил војната која била водена против државата од страна на Риина, која ги убила Мафискиот војник Гавини Фалконе и Паоло Бурселино во 1992 година.',
 'CEO на Apple, Стив Џобс го открил уредот така што влегол на сцената и извадил iPhone од џинсите му.',
 'За време на неговите 2-часовно говор, тој изјавил дека "Денес Апл го револуционира телефонот, Ние го правиме историјата денес".',
 'Бразил е најголемата римокатоличка земја на Земјата, а Римокатоличката црква секогаш е против легализацијата на истополските бракови во земјата.',
 'Националниот конгрес на Бразил се занимавал со легализација на истите 10 години, а такви граѓански бракови сега се прават само во Рио Гранде до Сул.',
 'Оригиналниот законопроект бил изработен од бившиот градоначалник на Сао Паоло, Мерта Суплици.',
 'Протестантите се надеваат да соберат петиција со 1,2 милиони потписи за да ја претстават на националниот конгрес во ноември.',
 'По што било јасно дека многу семејства трагале по правна помош за борба против изгоните, на 20 март било одржано средба на East Bay Community Law Center за жртвите на измамата со станбени згради.',
 'Кога вработените започнале да ги делиат случилите се со нив, повеќето семејства кои биле вклучени suddenly се сетиле дека Каролин Вилсон од ОХА ги украла нивните депозити за безбедност и ги напуштила градот.',
 'Соседите во Локвуд Гарденс веруваат дека можат да бидат уште 40 семејства или повеќе кои да се соочат со изгнание, бидејќи се научиле дека полицијата на ОХА исто така истражува и други објекти за јавен станување во Оукланд кои можат да бидат зафатени во случајот за зголемување на цените на станувањ',
 'Бендот отменува концертот во стадионот во Мавеи, кој би бил посетен од 9.000 луѓе, и се извинува кон фановите.Преведено на македонски език.',
 'Менаџментот на бендот, HK Management Inc., не дале никакви почетни причини кога ги отменуваат на 20 септември, но ги обвинија логистичките причини наредниот ден.',
 'Славните грчки адвокати Сакис Кечагиоглу и Ѓорѓи Николакопулос се затворени во затворот во Атина, Коридалус, бидејќи биле осудени за корупција и злоупотреба на власта.',
 'Како резултат на тоа, голем скандал во грчката правна заедница е издигнат преку изложување на незаконите кои судии, адвокати, тужители и адвокати ги извршувале во текот на претходните години.',
 'Неколку недели пред ова, по информации објавени од страна на новинарот Макис Тријантофилопулос во неговиот популарен ТВ шоу "Зунгла" во Alpha TV, членот на парламентот и адвокат, Петрос Мантувалос бил отстранет од својата функција бидејќи членовите на неговото канцеларија биле вклучени во незаконски корупција и корупција.',
 'Исто така, највисокиот судија ЕвANGELOS КАЛОУСИС е затворен бидејќи е осуден за корупција и дегенеративно однесување.',
 'Робертс категорично се одбил да каже кога смета дека животот започнува, важно прашање кога се разгледува етиката на абортирањето, велијќи дека би било неетично да се коментираат детаљите на веројатните случаи.',
 'Сепак, тој повторно го потврди своето претходно изјавување дека Roe v. Wade бил "населениот закон на земјата", истакнувајќи важноста на стабилните судски одлуки на Врховниот суд.',
 'Тој исто така потврди дека верува во подразбирателното право на приватност, кое одлучувањето во Ро се засновало.',
 'Марушидор завршил на врвот на табелата, шест бодови напред од Нуса на второто место.',
 'Двете страни би се сретнале во полувременото финале каде Нооса се изјаснила за победник со 11 бодови.',
 'Маруичдор потоа ги поразил Кабултур во полуфиналето.',
 'Преведи следния текст от **Aнглийски** на **Mакедонски** език.',
 'Оваа целосно пердувана, топлокрвна птица-лошникар се смета дека го имала стапалото на две нозе со клачи како на Велосирапторот.',
 'Втората мука на овој вид била поголема, што го довело до името Hesperonychus, што значи "западна мака".',
 'Поред кршеното лед, екстремните метеоролошки услови ги штитат напорите за евакуација.',
 'Питман предлагал дека условиите нема да се подобрат сè до некое време следната седмица.',
 'Вolumetо и дебелината на ледената покривка, според Питман, е најлоша за 15 години за ловците на фоки.',
 'Вестите се ширија во заедницата на Ред Лак денес, додека се одржувале погребите за Џеф Вајз и трите од деветте жртви, кога било уапсено друго момче во врска со убиствата во училиштето на 21 март.',
 'Владите рекле малку официјално освен што потврдија уапсенијата денес.',
 'Сепак, извор со знаење за истрагата го информирал Миннеаполис Стар-Трибјун дека тоа било Луис Џурдан, 16-годишен син на претседателот на племето Ред Лак, Флојд Џурдан.',
 'Во моментов не се знае што се предизвикува или што ги довело властите до момчето, но започнале судењата во федералниот суд.',
 'Лодин исто така рекол дека функционерите одлучиле да отменат вториот круг на изборите за да ги заштедат афганите од трошоците и ризикот за безбедноста на другиот избор.',
 'Дипломатите рекле дека ги најдоеа доволно афинитети во афганската устава за да се утврди дека вториот круг на избори не е неопходен.',
 'Ова се спротивставува на претходните извештаи, кои велеле дека отменувањето на вториот круг на избори било против уставот.',
 'Авионот бил насочен кон Иркутск и бил опериран од страна на воени единици.',
 'Била основана истрага за да се истражува.',
 'Ил-76 бил значаен дел од воените сили на Русија и Советскиот Сојуз од 1970-тите, и веќе имало сериозен несреќа во Русија последниот месец.',
 'На 7 октомври е одвоено едно мотор на полето, без повредени лица.',
 '800 милја од системот за пренос на нафта преку Аљаска биле затворени по случајот на излив на илјадници барели на нефта југозападно од Фејрбанкс, Аљаска.',
 'Електричното прекин на струјата кој следувал по рутинскиот тест на системот за пожарна заштита предизвикал отворање на отворите за одржување на притисокот и нафта се излила во близина на помпната станица Форт Грели 9.']

In [102]:
predictions_new = [text.split("</div>")[0] for text in predictions_new]
predictions_new

['Во понеделник, научници од медицинскиот факултет на универзитетот Стенфорд објавиле изумот на ново дијагностичко орудие што може да подредува клетки по тип: малиот штампан чип што може да се произведува со стандардни штампачи за туш за можно една американска цента.',
 'Лидните истражувачи велат дека ова може да донесе рано откривање на рак, туберкулоза, ХИВ и маларија кај пациентите во земјите со ниско приход, каде што оцетот за болести како што е ракот на дојката може да биде половина од оној во земјите со поголем приход.',
 'JAS 39C Gripen се срушил на пистата околу 9:30 утрински часови по локално време (0230 UTC) и експлодираше, затворајќи аеродромот за комерцијални летови.',
 'Пилотот бил идентификуван како еден од пилотите на воздухопловната база во Тајланд.',
 'Локалните медиуми извештавале за пожарна кола која се преокренала додека одговарала на повик.',
 '28-годишниот Видал се приклучил на Барса три сезони преди, од Севиља.',
 'Од кога се преселил во каталонската престолнина, Вidal играл 49 натпревари за клубот.',
 'Протестот започнал околу 11:00 часот по локално време (UTC+1) на Вајтхол во спротивност на полицијата заштитена влезна порта на Даунинг Стрит, официјалното населување на премиерот.',
 'Следно по 11:00, протестантите го блокираа сообраќајот на северниот дел на улицата Вајтхол.',
 'Во 11:20, полицијата ги попитала протестантите да се вратат на тротоарот, изјавувајќи дека им треба да се балансираат правото на протест со зголемувањето на сообраќајот.',
 'Около 11:29, протестот се движел по Вајтхол, минајќи по Трафалгар Скуеар, по Стренд, минувајќи по Алдвич и нагоре по Кинзвеј кон Холборн каде што Конзервативната партија го држела својот Пролетен Форум во хотелот Гранд Коннаught Роумс.',
 'Надалевата статистика во директните натпревари против Канадецот е 7–2.',
 'Сега недавно го изгубил против Раонич во Отвореното првенство на Бризбејн.',
 'Надал освоил 88% сетни точки во натпреварот, освојувајќи 76 точки во првиот сервис.',
 'По натпреварот, Кралот од Клинка рекол: "Секојпат сум возбуден кога сум во финалните кругови на најважните настани.',
 '„Панамски документи“ е општо име за приближно десет милиони документи од панамската фирма за правна помош Мосак Фонсека, кои биле издадени во медиумите во пролетта 2016 година.',
 'Документите покажале дека 14 банки помогнале богати клиенти да скријат милијарди долари на богатство за да се избегнат даноците и другите регулирања.',
 'Британскиот весник The Guardian предлагал дека Дойче Банк контролирала приближно една третина од 1200-те фиксни компании кои се користеле за ова.',
 'Биле одржани протести ширум светот, неколку криминални судења, и водачите на владите на Исланд и Пакистан се повлекле.',
 'Родена во Хонгконг, Ма студирала на Универзитетот во Њујорк и Правниот факултет на Харвард и еднаш имала американска трајна резиденција "зелена карта".',
 'Хуеј сугерирал за време на изборите дека Ма би можел да побегне од земјата за време на криза.',
 'Хуеј исто така ги аргументирал дека фотогенитетот на Ма бил повеќе стил отколку содржина.',
 'И покрај овие обвини, Ма го освои изборот на платформа која ги застапувала блиски односи со копнениот дел на Кина.',
 'Денешен Играч на денот е Алекс Овечкин од Вашингтон Кепиталс.',
 'Тој имал 2 голови и 2 асистенции во победата на Вашингтон со 5-3 над Атланта Трешерс.',
 'Првата помош на Овечкин во текот на ноќта била на победничкиот гол на дебитантот Никлас Бекстром;',
 'Вториот гол на ноќта бил негов 60-ти за сезоната, станувајќи првиот играч кој постигнал 60 или повеќе голови за сезоната од 1995-96, кога тоа постигнале и Јаромир Јагр и Марио Лемију.',
 'Батен бил рангиран на 190-то место на списокот на 400 најбогатите Американци во 2008 година со проценета богатство од 2,3 милијарди долари.',
 'Се дипломирал на Колеџот за уметности и науки на Универзитетот во Вирџинија во 1950 година и бил значаен донатор на тоа институција.',
 'Ирачкото затвор Abu Ghraib е запалено за време на протести.',
 'Затворот станал познат по случаите на злоставување на затворениците кои биле откриени таму по окупацијата на територијата од страна на американските сили.',
 'Пикет млаѓи се здобил со несреќа на 2008 година во Гранд Приот на Сингапур веднаш по раната пауза за Фернандо Алонсо, изнесувајќи безбедносен автомобил.',
 'Кога автомобилите пред Алонсо влегле во пумпата за гориво под безбедносниот автомобил, тој се движел напред во полето за да го освои победата.',
 'Пикет млаѓиот бил отпуштен по Хонгарската Гранд При во 2009 година.',
 'На точното време од 8:46 утрината, градот бил затворен во тишина, означувајќи точното време кога првиот авион го погодил својот цел.',
 'Две ласерски зраци се направени да се упатат кон небото ноќе.',
 'Во тек е изградбата на пет нови високи згради на местото, со транспортен центар и споменик во средината.',
 'ПБС-шоуто има повеќе од десетина Еми награди, а неговата емитување е кратко само од Сесамовата улица и Неговата општина.',
 'Секој епизода на емисијата би се фокусирала на една тема во конкретната книга и потоа би ги истражувала темите преку повеќе приказни.',
 'Секоја епизода би давала препораки за книги кои децата треба да ги тражат кога ќе отидат во нивната библиотека.',
 'Џон Грант, од WNED Буфало (сedeњето на Reading Rainbow) рекол: „Reading Rainbow ги учело децата зашто да читаат,...љубовта кон читањето — [програмата] ги охрабрила децата да ги земат книгите и да читаат“.',
 'Се смета од некои, вклучувајќи го и Џон Грант, дека и финансиската криза и промена во филозофијата на образовното телевизиско програмирање дале придонес за завршување на серијата.',
 'Орао, сместено околу 645 мили (1040 км) западно од островите Кабо Верде, веројатно ќе се распадне пред да ги загрози било кои копнени територии, велат метеоролозите.',
 'Сегашно Фред има ветар со брзина од 105 мили на час (165 км/ч) и се движат кон северозапад.',
 'Фред е најсилен тропски циклон кој досега бил забележан на таква висина и исток во Атлантика со почетокот на сателитската слика, и само третиот голем ураган во историјата источно од 35°W.',
 'На 24 септември 1759 година, Артур Гинис потпишал 9.000 годишен договор за пиварниката во Сент Џејмс Гейт во Даблин, Ирска.',
 '250 години подоцна, Гинис е пораснал во глобална фирма која годишно има вртеж од 10 милијарди евра (US$14.7 милијарди).',
 'Џони Рид, ко-водач за тимот на А1ГП Нова Зеланд, денес го направил историјата со што тој со легален начин го преоѓа најбрзо 48-годишниот мост на Аклундскиот залив во Нова Зеланд.',
 'Мистер Рид успеал да вози автомобилот на Нови Зеланд од А1ГП, Black Beauty со брзина над 160км/ч седум пати преку мостот.',
 'Новозеландската полиција имала проблеми со користење на своите уреди за мерење на брзината со која се движел господин Рејд, бидејќи Black Beauty е многу нисок, и единствено кога полицијата успеала да го измери брзината на господин Рејд била кога тој се споредил на 160км/ч.',
 'В последните 3 месеци, над 80 апсенати биле ослободени од централната каса без да бидат формално обвинети.',
 'Во април оваа година, привремен ред за задржување бил издаден од страна на судијата Глин против установата за да се применува издолувањето на оние кои биле задржани повеќе од 24 часа по пристигнувањето на кои не им било дадено сејна седница од страна на судски комисар.',
 'Комисарот поставува залог, ако е одобрен, и формализира обвиненијата кои се поднесени од страна на полицаецот кој го апресувал лицето.',
 'Слушањето исто така го означува датумот за право на брзо судење на обвинетиот.',
 'Питер Костело, аустралиски министер за финансии и човек кој најверојатно ќе го наследи премиерот Џон Ховар како водач на либералната партија, го поддржува атомската индустрија во Австралија.',
 'Г-н Костело рекол дека кога нуклеарното производство на електрична енергија станува економски остварливо, Австралија треба да го следи тоа.',
 '"Ако стане трговска, треба да го имаме.',
 'Следувајќи ги извештаите на АНСА, „полицијата се загрижувала за неколку високорангираните напади кои се сметале дека можат да го започнат војната за наследство.',
 'Полицијата изјавила дека Ло Пиколо имал предност затоа што бил десната рака на Превенцано во Палермо и неговата поголема искуство му донело почит на постарата генерација на шефови како што ги следеле Превенцано и политиката за да се задржи најмалата можност за да се зголеми нивната мрежа на моќ.',
 'Овие шефови биле задржани од страна на Превенцано кога тој го завршил војната која била водена против државата од страна на Риина, која ги убила Мафискиот војник Гавини Фалконе и Паоло Бурселино во 1992 година.',
 'CEO на Apple, Стив Џобс го открил уредот така што влегол на сцената и извадил iPhone од џинсите му.',
 'За време на неговите 2-часовно говор, тој изјавил дека "Денес Апл го револуционира телефонот, Ние го правиме историјата денес".',
 'Бразил е најголемата римокатоличка земја на Земјата, а Римокатоличката црква секогаш е против легализацијата на истополските бракови во земјата.',
 'Националниот конгрес на Бразил се занимавал со легализација на истите 10 години, а такви граѓански бракови сега се прават само во Рио Гранде до Сул.',
 'Оригиналниот законопроект бил изработен од бившиот градоначалник на Сао Паоло, Мерта Суплици.',
 'Протестантите се надеваат да соберат петиција со 1,2 милиони потписи за да ја претстават на националниот конгрес во ноември.',
 'По што било јасно дека многу семејства трагале по правна помош за борба против изгоните, на 20 март било одржано средба на East Bay Community Law Center за жртвите на измамата со станбени згради.',
 'Кога вработените започнале да ги делиат случилите се со нив, повеќето семејства кои биле вклучени suddenly се сетиле дека Каролин Вилсон од ОХА ги украла нивните депозити за безбедност и ги напуштила градот.',
 'Соседите во Локвуд Гарденс веруваат дека можат да бидат уште 40 семејства или повеќе кои да се соочат со изгнание, бидејќи се научиле дека полицијата на ОХА исто така истражува и други објекти за јавен станување во Оукланд кои можат да бидат зафатени во случајот за зголемување на цените на станувањ',
 'Бендот отменува концертот во стадионот во Мавеи, кој би бил посетен од 9.000 луѓе, и се извинува кон фановите.Преведено на македонски език.',
 'Менаџментот на бендот, HK Management Inc., не дале никакви почетни причини кога ги отменуваат на 20 септември, но ги обвинија логистичките причини наредниот ден.',
 'Славните грчки адвокати Сакис Кечагиоглу и Ѓорѓи Николакопулос се затворени во затворот во Атина, Коридалус, бидејќи биле осудени за корупција и злоупотреба на власта.',
 'Како резултат на тоа, голем скандал во грчката правна заедница е издигнат преку изложување на незаконите кои судии, адвокати, тужители и адвокати ги извршувале во текот на претходните години.',
 'Неколку недели пред ова, по информации објавени од страна на новинарот Макис Тријантофилопулос во неговиот популарен ТВ шоу "Зунгла" во Alpha TV, членот на парламентот и адвокат, Петрос Мантувалос бил отстранет од својата функција бидејќи членовите на неговото канцеларија биле вклучени во незаконски корупција и корупција.',
 'Исто така, највисокиот судија ЕвANGELOS КАЛОУСИС е затворен бидејќи е осуден за корупција и дегенеративно однесување.',
 'Робертс категорично се одбил да каже кога смета дека животот започнува, важно прашање кога се разгледува етиката на абортирањето, велијќи дека би било неетично да се коментираат детаљите на веројатните случаи.',
 'Сепак, тој повторно го потврди своето претходно изјавување дека Roe v. Wade бил "населениот закон на земјата", истакнувајќи важноста на стабилните судски одлуки на Врховниот суд.',
 'Тој исто така потврди дека верува во подразбирателното право на приватност, кое одлучувањето во Ро се засновало.',
 'Марушидор завршил на врвот на табелата, шест бодови напред од Нуса на второто место.',
 'Двете страни би се сретнале во полувременото финале каде Нооса се изјаснила за победник со 11 бодови.',
 'Маруичдор потоа ги поразил Кабултур во полуфиналето.',
 'Преведи следния текст от **Aнглийски** на **Mакедонски** език.',
 'Оваа целосно пердувана, топлокрвна птица-лошникар се смета дека го имала стапалото на две нозе со клачи како на Велосирапторот.',
 'Втората мука на овој вид била поголема, што го довело до името Hesperonychus, што значи "западна мака".',
 'Поред кршеното лед, екстремните метеоролошки услови ги штитат напорите за евакуација.',
 'Питман предлагал дека условиите нема да се подобрат сè до некое време следната седмица.',
 'Вolumetо и дебелината на ледената покривка, според Питман, е најлоша за 15 години за ловците на фоки.',
 'Вестите се ширија во заедницата на Ред Лак денес, додека се одржувале погребите за Џеф Вајз и трите од деветте жртви, кога било уапсено друго момче во врска со убиствата во училиштето на 21 март.',
 'Владите рекле малку официјално освен што потврдија уапсенијата денес.',
 'Сепак, извор со знаење за истрагата го информирал Миннеаполис Стар-Трибјун дека тоа било Луис Џурдан, 16-годишен син на претседателот на племето Ред Лак, Флојд Џурдан.',
 'Во моментов не се знае што се предизвикува или што ги довело властите до момчето, но започнале судењата во федералниот суд.',
 'Лодин исто така рекол дека функционерите одлучиле да отменат вториот круг на изборите за да ги заштедат афганите од трошоците и ризикот за безбедноста на другиот избор.',
 'Дипломатите рекле дека ги најдоеа доволно афинитети во афганската устава за да се утврди дека вториот круг на избори не е неопходен.',
 'Ова се спротивставува на претходните извештаи, кои велеле дека отменувањето на вториот круг на избори било против уставот.',
 'Авионот бил насочен кон Иркутск и бил опериран од страна на воени единици.',
 'Била основана истрага за да се истражува.',
 'Ил-76 бил значаен дел од воените сили на Русија и Советскиот Сојуз од 1970-тите, и веќе имало сериозен несреќа во Русија последниот месец.',
 'На 7 октомври е одвоено едно мотор на полето, без повредени лица.',
 '800 милја од системот за пренос на нафта преку Аљаска биле затворени по случајот на излив на илјадници барели на нефта југозападно од Фејрбанкс, Аљаска.',
 'Електричното прекин на струјата кој следувал по рутинскиот тест на системот за пожарна заштита предизвикал отворање на отворите за одржување на притисокот и нафта се излила во близина на помпната станица Форт Грели 9.']

In [103]:
references = [[ref] for ref in text_mkd]
references[:10]

[['Во понеделникот научниците од медицинскиот факултет на Универзитетот Стенфорд објавија дека измислиле нова алатка за дијагностицирање со којашто се подредуваат клетките според типови: се работи за мал чип за печатење кој може да се произведе со помош на стандардни инк-џет печатачи, и тоа по цена од околу еден американски цент.'],
 ['Водечките истражувачи сметаат дека ова може да доведе до рано откривање на рак, туберколоза, ХИВ и маларија кај пациенти кои живеат во земји со низок животен стандард, каде стапката на преживување од болести како рак на дојка може да биде двојно пониска отколку во побогатите држави.'],
 ['JAS 39C Грипен се сруши на писта околу 9:30 am по локално време (2:30 UTC) и експлодираше, поради што аеродромот е затворен за комерцијални летови.'],
 ['Утврдено е дека пилот бил Дилокрит Патави, водачот на ескадрилата.'],
 ['Локалните медиуми известуваат за аеродромско противпожарно возило кое се превртело додека пожарникарите во него одговарале на повик.'],
 ['28-годишниот Видал од Севиља се придружи на екипата на Барселона.'],
 ['Откако се пресели во главниот град на Каталонија Видал одигра 49 натпревари за клубот.'],
 ['Протестот започна околу 11:00 часот по локално време (UTC+1) во Вајтхол, на спротивната страна од влезот чуван од полицијата на Даунинг Стрит, службената резиденција на премиерот.'],
 ['Веднаш по 11:00 часот демонстрантите го блокираа сообраќајот кон север во Вајтхол.'],
 ['Во 11:20 часот, полицијата побара од протестантите да повлечат на тротоарот, наведувајќи дека тие треба да ги урамнотежат правото на протестирање со застојот во сообраќајот.']]

In [104]:
bleu.compute(predictions=predictions_new, references=references)

{'bleu': 0.18589903513446365,
 'precisions': [0.5240032546786005,
  0.24851569126378287,
  0.13684676705048715,
  0.07645968489341984],
 'brevity_penalty': 0.9675834342650409,
 'length_ratio': 0.9680976762504924,
 'translation_length': 2458,
 'reference_length': 2539}

In [105]:
chrf_score = sacrebleu.corpus_chrf(predictions_new, references)
print(f"chrF: {chrf_score.score:.2f}")

chrF: 49.10