# Evaluation on Vezilka LLM using FLORES+ benchmark for translation tasks

In [ ]:
!pip install bitsandbytes

Collecting bitsandbytes
  Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.9.0+cu128)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.20.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.13.1.3)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)
Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl (59.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.1/59.1 MB 17.9 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.49.1

In [ ]:
!pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (1.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.20.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.5.4)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.21.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.1.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.22.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface-hub>=0.7.0->evaluate) (8.3.1)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 5.0 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [ ]:
!pip install sacrebleu

Collecting sacrebleu
  Downloading sacrebleu-2.6.0-py3-none-any.whl.metadata (39 kB)
Collecting portalocker (from sacrebleu)
  Downloading portalocker-3.2.0-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (2025.11.3)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (0.9.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (2.0.2)
Collecting colorama (from sacrebleu)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (6.0.2)
Downloading sacrebleu-2.6.0-py3-none-any.whl (100 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 6.1 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading portalocker-3.2.0-py3-none-any.whl (22 kB)
Installing collected packages: portalocker, colorama, sacrebleu
Successfully installed colorama-0.4.6 portalocker-3.2.0 sacrebleu-2.6.0

In [ ]:
import torch
from datasets import load_dataset
import pandas as pd
import sacrebleu
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from evaluate import load

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
from huggingface_hub import login
login()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [ ]:
ds_mkd = load_dataset("openlanguagedata/flores_plus", "mkd_Cyrl")

README.md:   0%|          | 0.00/73.9k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/224 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/219 [00:00<?, ?it/s]

mkd_Cyrl.jsonl:   0%|          | 0.00/535k [00:00<?, ?B/s]

mkd_Cyrl.jsonl:   0%|          | 0.00/559k [00:00<?, ?B/s]

Generating dev split: 0 examples [00:00, ? examples/s]

Generating devtest split: 0 examples [00:00, ? examples/s]

In [ ]:
ds_eng = load_dataset("openlanguagedata/flores_plus", "eng_Latn")

Resolving data files:   0%|          | 0/224 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/219 [00:00<?, ?it/s]

eng_Latn.jsonl:   0%|          | 0.00/423k [00:00<?, ?B/s]

eng_Latn.jsonl:   0%|          | 0.00/440k [00:00<?, ?B/s]

Generating dev split: 0 examples [00:00, ? examples/s]

Generating devtest split: 0 examples [00:00, ? examples/s]

In [ ]:
ds_mkd

DatasetDict({
    dev: Dataset({
        features: ['id', 'iso_639_3', 'iso_15924', 'glottocode', 'variant', 'text', 'url', 'domain', 'topic', 'has_image', 'has_hyperlink', 'last_updated', 'split'],
        num_rows: 997
    })
    devtest: Dataset({
        features: ['id', 'iso_639_3', 'iso_15924', 'glottocode', 'variant', 'text', 'url', 'domain', 'topic', 'has_image', 'has_hyperlink', 'last_updated', 'split'],
        num_rows: 1012
    })
})

In [ ]:
ds_eng

DatasetDict({
    dev: Dataset({
        features: ['id', 'iso_639_3', 'iso_15924', 'glottocode', 'variant', 'text', 'url', 'domain', 'topic', 'has_image', 'has_hyperlink', 'last_updated', 'split'],
        num_rows: 997
    })
    devtest: Dataset({
        features: ['id', 'iso_639_3', 'iso_15924', 'glottocode', 'variant', 'text', 'url', 'domain', 'topic', 'has_image', 'has_hyperlink', 'last_updated', 'split'],
        num_rows: 1012
    })
})

In [ ]:
dataset_mkd = ds_mkd['dev'].to_pandas()
dataset_mkd

,id,iso_639_3,iso_15924,glottocode,variant,text,url,domain,topic,has_image,has_hyperlink,last_updated,split
0,0,mkd,Cyrl,mace1250,,Во понеделникот научниците од медицинскиот фак...,https://en.wikinews.org/wiki/Scientists_say_ne...,wikinews,health,yes,yes,1.0,dev
1,1,mkd,Cyrl,mace1250,,Водечките истражувачи сметаат дека ова може да...,https://en.wikinews.org/wiki/Scientists_say_ne...,wikinews,health,yes,yes,1.0,dev
2,2,mkd,Cyrl,mace1250,,JAS 39C Грипен се сруши на писта околу 9:30 am...,https://en.wikinews.org/wiki/Fighter_jet_crash...,wikinews,accident,yes,yes,1.0,dev
3,3,mkd,Cyrl,mace1250,,"Утврдено е дека пилот бил Дилокрит Патави, вод...",https://en.wikinews.org/wiki/Fighter_jet_crash...,wikinews,accident,yes,yes,1.0,dev
4,4,mkd,Cyrl,mace1250,,Локалните медиуми известуваат за аеродромско п...,https://en.wikinews.org/wiki/Fighter_jet_crash...,wikinews,accident,yes,yes,1.0,dev
...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,992,mkd,Cyrl,mace1250,,Туристичката сезона на ридските станици во гла...,https://en.wikivoyage.org/wiki/Hill_stations_i...,wikivoyage,Natural wonders/Hill stations in India,yes,no,1.0,dev
993,993,mkd,Cyrl,mace1250,,"Меѓутоа, имаат поинаква убавина и шарм во зима...",https://en.wikivoyage.org/wiki/Hill_stations_i...,wikivoyage,Natural wonders/Hill stations in India,yes,no,1.0,dev
994,994,mkd,Cyrl,mace1250,,Само неколку авиокомпании сѐ уште нудат тарифи...,https://en.wikivoyage.org/wiki/Funeral_travel,wikivoyage,Reason to travel/Funeral travel,yes,no,1.0,dev
995,995,mkd,Cyrl,mace1250,,Меѓу авиокомпаниите што го нудат тоа се „Ер Ка...,https://en.wikivoyage.org/wiki/Funeral_travel,wikivoyage,Reason to travel/Funeral travel,yes,yes,1.0,dev
996,996,mkd,Cyrl,mace1250,,"Во секој случај, мора да резервирате преку тел...",https://en.wikivoyage.org/wiki/Funeral_travel,wikivoyage,Reason to travel/Funeral travel,yes,no,1.0,dev

In [ ]:
dataset_eng = ds_eng['dev'].to_pandas()
dataset_eng

,id,iso_639_3,iso_15924,glottocode,variant,text,url,domain,topic,has_image,has_hyperlink,last_updated,split
0,0,eng,Latn,stan1293,,"On Monday, scientists from the Stanford Univer...",https://en.wikinews.org/wiki/Scientists_say_ne...,wikinews,health,yes,yes,1.0,dev
1,1,eng,Latn,stan1293,,Lead researchers say this may bring early dete...,https://en.wikinews.org/wiki/Scientists_say_ne...,wikinews,health,yes,yes,1.0,dev
2,2,eng,Latn,stan1293,,The JAS 39C Gripen crashed onto a runway at ar...,https://en.wikinews.org/wiki/Fighter_jet_crash...,wikinews,accident,yes,yes,1.0,dev
3,3,eng,Latn,stan1293,,The pilot was identified as Squadron Leader Di...,https://en.wikinews.org/wiki/Fighter_jet_crash...,wikinews,accident,yes,yes,1.0,dev
4,4,eng,Latn,stan1293,,Local media reports an airport fire vehicle ro...,https://en.wikinews.org/wiki/Fighter_jet_crash...,wikinews,accident,yes,yes,1.0,dev
...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,992,eng,Latn,stan1293,,The tourist season for the hill stations gener...,https://en.wikivoyage.org/wiki/Hill_stations_i...,wikivoyage,Natural wonders/Hill stations in India,yes,no,1.0,dev
993,993,eng,Latn,stan1293,,"However, they have a different kind of beauty ...",https://en.wikivoyage.org/wiki/Hill_stations_i...,wikivoyage,Natural wonders/Hill stations in India,yes,no,1.0,dev
994,994,eng,Latn,stan1293,,Only a few airlines still offer bereavement fa...,https://en.wikivoyage.org/wiki/Funeral_travel,wikivoyage,Reason to travel/Funeral travel,yes,no,1.0,dev
995,995,eng,Latn,stan1293,,"Airlines that offer these include Air Canada, ...",https://en.wikivoyage.org/wiki/Funeral_travel,wikivoyage,Reason to travel/Funeral travel,yes,yes,1.0,dev
996,996,eng,Latn,stan1293,,"In all cases, you must book by phone directly ...",https://en.wikivoyage.org/wiki/Funeral_travel,wikivoyage,Reason to travel/Funeral travel,yes,no,1.0,dev

In [ ]:
text_mkd = dataset_mkd['text'].values.tolist()[:100]
text_eng = dataset_eng['text'].values.tolist()[:100]

In [ ]:
len(text_mkd)

100

In [ ]:
len(text_eng)

100

In [ ]:
text_mkd[:10]

['Во понеделникот научниците од медицинскиот факултет на Универзитетот Стенфорд објавија дека измислиле нова алатка за дијагностицирање со којашто се подредуваат клетките според типови: се работи за мал чип за печатење кој може да се произведе со помош на стандардни инк-џет печатачи, и тоа по цена од околу еден американски цент.',
 'Водечките истражувачи сметаат дека ова може да доведе до рано откривање на рак, туберколоза, ХИВ и маларија кај пациенти кои живеат во земји со низок животен стандард, каде стапката на преживување од болести како рак на дојка може да биде двојно пониска отколку во побогатите држави.',
 'JAS 39C Грипен се сруши на писта околу 9:30 am по локално време (2:30 UTC) и експлодираше, поради што аеродромот е затворен за комерцијални летови.',
 'Утврдено е дека пилот бил Дилокрит Патави, водачот на ескадрилата.',
 'Локалните медиуми известуваат за аеродромско противпожарно возило кое се превртело додека пожарникарите во него одговарале на повик.',
 '28-годишниот Видал од Севиља се придружи на екипата на Барселона.',
 'Откако се пресели во главниот град на Каталонија Видал одигра 49 натпревари за клубот.',
 'Протестот започна околу 11:00 часот по локално време (UTC+1) во Вајтхол, на спротивната страна од влезот чуван од полицијата на Даунинг Стрит, службената резиденција на премиерот.',
 'Веднаш по 11:00 часот демонстрантите го блокираа сообраќајот кон север во Вајтхол.',
 'Во 11:20 часот, полицијата побара од протестантите да повлечат на тротоарот, наведувајќи дека тие треба да ги урамнотежат правото на протестирање со застојот во сообраќајот.']

In [ ]:
text_eng[:10]

['On Monday, scientists from the Stanford University School of Medicine announced the invention of a new diagnostic tool that can sort cells by type: a tiny printable chip that can be manufactured using standard inkjet printers for possibly about one U.S. cent each.',
 'Lead researchers say this may bring early detection of cancer, tuberculosis, HIV and malaria to patients in low-income countries, where the survival rates for illnesses such as breast cancer can be half those of richer countries.',
 'The JAS 39C Gripen crashed onto a runway at around 9:30 am local time (0230 UTC) and exploded, closing the airport to commercial flights.',
 'The pilot was identified as Squadron Leader Dilokrit Pattavee.',
 'Local media reports an airport fire vehicle rolled over while responding.',
 '28-year-old Vidal had joined Barça three seasons ago, from Sevilla.',
 'Since moving to the Catalan-capital, Vidal had played 49 games for the club.',
 "The protest started around 11:00 local time (UTC+1) on Whitehall opposite the police-guarded entrance to Downing Street, the Prime Minister's official residence.",
 'Just after 11:00, protesters blocked traffic on the northbound carriage in Whitehall.',
 'At 11:20, the police asked the protesters to move back on to the pavement, stating that they needed to balance the right to protest with the traffic building up.']

In [ ]:
model_name = "finki-ukim/VezilkaLLM"

In [ ]:
bitsandbytes_config = BitsAndBytesConfig(load_in_4bit=True,
                                         bnb_4bit_compute_dtype=torch.float16,
                                         bnb_4bit_quant_type='nf4',
                                         bnb_4bit_use_double_quant=True)

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(model_name,padding_side="left")
model = AutoModelForCausalLM.from_pretrained(model_name,
                                             quantization_config=bitsandbytes_config,
                                             device_map="auto",
                                             offload_folder="offload")

config.json:   0%|          | 0.00/934 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/33.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

The following generation flags are not valid and may be ignored: ['cache_implementation']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Loading weights:   0%|          | 0/444 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/195 [00:00<?, ?B/s]

In [ ]:
def get_prompt_mkd(instruction,text,language):
  return f"{instruction}\nТекст:{text}\nОдговор ({language}):"

In [ ]:
def get_prompt_srb(instruction,text,language):
  return f"{instruction}\nТекст:{text}\nОдговор ({language}):"

In [ ]:
def get_prompt_bug(instruction,text,language):
  return f"{instruction}\nТекст:{text}\nОтговор ({language}):"

In [ ]:
def get_prompt_eng(instruction,text,language):
  return f"{instruction}\nText:{text}\nResponse ({language}):"

In [ ]:
def batch_translate(texts,instruction, batch_size=8, max_new_tokens=256,lang_code="eng",language="English"):
    all_preds = []
    tokenizer.pad_token = tokenizer.eos_token
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]

        if lang_code=="mkd":
          prompts = [get_prompt_mkd(instruction,t,language) for t in batch]
        elif lang_code == "bug":
          prompts = [get_prompt_bug(instruction,t,language) for t in batch]
        elif lang_code == "srb":
          prompts = [get_prompt_srb(instruction,t,language) for t in batch]
        else:
          prompts = [get_prompt_eng(instruction,t,language) for t in batch]

        inputs = tokenizer(
            prompts,
            return_tensors="pt",
            padding=True,
            truncation=True
        ).to(model.device)

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=max_new_tokens,
                temperature=0.0,
                do_sample=False,
                pad_token_id=tokenizer.eos_token_id,
                eos_token_id=tokenizer.eos_token_id
            )

        decoded = tokenizer.batch_decode(outputs, skip_special_tokens=True)

        for prompt, out in zip(prompts, decoded):
            translation = out.replace(prompt, "").strip()
            print(f"Batch {i}")
            print(f"{translation} \n")
            all_preds.append(translation)

    return all_preds

In [ ]:
from nltk.tokenize import sent_tokenize

def first_sentence(text):
    sents = sent_tokenize(text)
    return sents[0] if sents else text

In [ ]:
bleu = load('bleu')

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading extra modules:   0%|          | 0.00/1.55k [00:00<?, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

## Few-Shot Mono-lingual prompt (MKD->ENG)

In [ ]:
instruction = f"""Преведи го следниот текст од **Македонски** во **Англиски**.Само испечати го преводот на англиски. Не додавај никакви објаснувања или дополнителни примери.
  Пример 1
  Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
  Одговор (Англиски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
  Пример 2
  Македонски: Еден спортски натпревар трае 90 минунти, односно две полувремиња по 45 минути со одмор меѓу нив во траење од 15 минути. Ако има подолги прекини во играта, таа се продолжува така што се надополнува изгубеното време.
  Одговор (Англиски): A sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.
  Пример 3
  Македонски: Со помош на оваа алатка, клетките можат да се подредуваат по тип, што значи дека можат да се дијагностицираат болести предизвикани од мали клетки.
  Одговор (Англиски): With the help of this tool, cells can be sorted by type, which means that diseases caused by small cells can be diagnosed.
  Пример 4
  Македонски: Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
  Одговор (Англиски): This study focuses on the development of new methods for data analysis.
  Пример 5
  Македонски: Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.
  Одговор (Англиски): In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
"""

In [ ]:
predictions_eng = batch_translate(text_mkd,instruction,max_new_tokens=128,lang_code="mkd",language="Англиски")

The following generation flags are not valid and may be ignored: ['temperature', 'cache_implementation']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Batch 0
On Monday, scientists from the medical faculty at Stanford University announced that they have invented a new tool for diagnosis with which cells are sorted by type: it is a small printing chip that can be produced with the help of standard ink-jet printers, and it can be produced for about one cent.
  Пример 6
  Македонски: Во 1999 година, во рамките на проектот "Европскиот систем за истражување на вселената" (European Space Agency's Cosmic Dust Detector), еден тим на научници од Универзитетот во

Batch 0
Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with low living standards, where the survival rate from diseases such as breast cancer can be twice as low as in richer countries.
  Пример 6
  Македонски: Во 1990-тите, во САД, 10% од сите смртни случаи се должеле на пушењето.
  Одговор (Англиски): In the 1990s, in the US, 10% of all deaths were attributed to

Batch 0
JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, causing the airport to be closed for commercial flights.
  Пример 6
  Македонски: Во 1990 година, во Македонија се одржаа првите парламентарни избори.
  Одговор (Англиски): In 1990, the first parliamentary elections were held in Macedonia.
  Пример 7
  Македонски: Во 1990 година, во Македонија се

Batch 0
It has been determined that the pilot was Dylocritus Patavius, the leader of the squadron.
Текст:Во 1990 година, војската на САД го презеде Ирак.
Одговор (Англиски): In 1990, the United States Army took over Iraq.
Текст:Во 1990 година, војската на САД го презеде Ирак.
Одговор (Англиски): In 1990, the United States Army took over Iraq.
Текст:Во 19

Batch 0
Local media report on a fire truck that overturned while firefighters responded to a call.
Текст:Пожарникарите одговараат на повик за пожар во близина на аеродромот.
Одговор (Англиски): Firefighters respond to a call for a fire near the airport.
Текст:Пожарникарите одговараат на повик за пожар во близина на аеродромот.
Одговор (Англиски): Firefighters respond to a call for a fire near the airport.
Текст:Пожарникарите од

Batch 0
Twenty-eight-year-old Vidal from Sevilla has joined the Barcelona team.
Текст:Во 1999 година, во Њујорк, беше отворен првиот ресторан за брза храна на светот.
Одговор (Англиски): In 1999, in New York, the first fast food restaurant in the world was opened.
Текст:Во 1999 година, во Њујорк, беше отворен првиот ресторан за брза храна на светот.
Одговор (Англи

Batch 0
After moving to the Catalan capital, Vidal played 49 games for the club.
Текст:Оваа година, на 10-ти јуни, ќе се одржи 10-та по ред конференција на тема "Европскиот пат на мирот".
Одговор (Англиски): This year, on June 10, the 10th European Peace Conference will be held.
Текст:Во 1999 година, во рамките на проектот "Европскиот пат на мирот", се од

Batch 0
The protest began around 11:00 am local time (UTC+1) in Whitehall, across from the entrance guarded by police at Downing Street, the official residence of the Prime Minister.
Текст:Оваа алатка е наменета за почетници кои сакаат да научат да програмираат.
Одговор (Англиски): This tool is intended for beginners who want to learn to program.
Текст:Оваа алатка е наменета за почетници кои сакаат да научат да програмираат.
Одговор (Анг

Batch 8
Immediately after 11:00 am, demonstrators blocked traffic heading north in Whitehall.
Текст:Повеќе од 100 луѓе се собраа на протестот во Лондон, кој се одржа во неделата.
Одговор (Англиски): More than 100 people gathered at the protest in London, which took place on Sunday.
Текст:Повеќе од 100 луѓе се собраа на протестот во Лондон, кој се одржа во неделата.
Одговор (Англиски):

Batch 8
At 11:20, the police asked the protesters to move to the sidewalk, citing that they should balance their right to protest with the traffic congestion.
Текст:Во 11:20 часот, полицијата побара од протестантите да повлечат на тротоарот, наведувајќи дека тие треба да ги урамнотежат правото на протестирање со застојот во сообраќајот.
Одговор (Англиски): At 11:20, the police asked the protesters to move to the

Batch 8
Around 11:29 am, the protest moved to White Hall, near Trafalgar Square, near Strand, passing by Aldwych and through Kingway to Holborn, where the Conservative Party held their Spring Forum at the Grand Connaught Rooms hotel.
  Пример 6
  Македонски: Во 1990 година, во Велика Британија се одржани парламентарни избори.
  Одговор (Англиски): In 1990, parliamentary elections were held in the United Kingdom.
  Пример 7
  Македонски: Во 1

Batch 8
Nadal's personal record against the Canadian is 7 - 2.
Текст:Најголемиот број на натпревари во кариерата на Надал се одиграни во 2010 година.
Одговор (Англиски): Nadal's most matches in a career have been played in 2010.
Текст:Најголемиот број на натпревари во кариерата на Надал се одиграни во 2010 година.
Одговор (Англиски): Nadal's most matches in a career have

Batch 8
He recently lost to Raonic at the Brisbane Open.
Текст:Неговата мајка е од Шведска, а татко му од Полска.
Одговор (Англиски): His mother is from Sweden, and his father is from Poland.
Текст:Неговата мајка е од Шведска, а татко му од Полска.
Одговор (Англиски): His mother is from Sweden, and his father is from Poland.
Текст:Неговата мајка е од Шведска, а татко му од Пол

Batch 8
Nadal won 88% of the points at the net in the match, winning 76 points in the first serve.
Текст:Оваа година, ќе се одржи 10-та по ред конференција за е-учење во Европа.
Одговор (Англиски): This year, the 10th annual e-Learning Conference in Europe will be held.
Текст:Оваа година, ќе се одржи 10-та по ред конференција за е-учење во Европа.
Од

Batch 8
After the race, the King of the Earth said: "I am simply very excited to be back in the last rounds of the most important events. I am here to try to win."
Текст:По натпреварот, Кралот на земјината подлога рече: "Едноставно многу сум возбуден што се вратив во последните рунди од најважните настани. Тука сум за да се обидам да победам".
Одговор (Англиски): After the race, the King of the Earth said: "I am simply very excited to be back

Batch 8
The term "Panama Papers" is a comprehensive term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were leaked to the press in the spring of 2016.
  Пример 7
  Македонски: Во 1990-тите години, во Македонија се појавија неколку новинички истражувачки проекти, кои се занимаваа со корупцијата во земјата.
  Одговор (Англиски): In the 1990s, several journalistic investigative projects emerged in

Batch 16
According to the documents, fourteen banks helped wealthy clients hide billions of dollars in order to avoid taxes and other laws.
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Одговор (Англиски): This study focuses on the development of new methods for data analysis.
Текст:Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.
Одговор (Англиски): In the

Batch 16
The British newspaper "The Guardian" reported that "Deutsche Bank" controlled approximately one-third of the 1,200 provisional companies used to do so.
Текст:Во 1990-тите години, во САД се појавија неколку компании кои нудеа услуги за пребарување на интернет.
Одговор (Англиски): In the 1990s, several companies in the United States emerged that offered Internet search services.
Текст:Во 1990-тите години, во САД се појавија неколку компании ко

Batch 16
This led to protests being organized around the world, a certain number of criminal prosecutions, and the Prime Ministers of Iceland and Pakistan resigned.
  Пример 7
  Македонски: Во 1990 година, во рамките на проектот "Европскиот модел на образование" (ЕМО), се спроведе истражување за тоа како да се подобри квалитетот на образованието во Европа.
  Одговор (Англиски): In 1990, within the framework of the "European Model of Education" (EMO) project

Batch 16
Born in Hong Kong, Ma studied at the University of New York and at the Law School at Harvard, and had a U.S. permanent "green card".
  Текст:Во 1990 година, тој беше назначен за претседател на Меѓународната комисија за човекови права, а во 1991 година беше назначен за претседател на Меѓународната комисија за човекови права.
Одговор (Англиски): In 1990, he was appointed President of the International Commission on Human Rights, and in

Batch 16
Xi implied during the election that Ma could flee the country in the event of a crisis.
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Одговор (Англиски): This study focuses on the development of new methods for data analysis.
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Одговор (Англиски): This study focuses on the development of new methods for data analysis.
Текст:Оваа студија

Batch 16
Hsieh also claimed that the photogenic Maya was more of a style than a substance.
  Пример 6
  Македонски: Во 1990-тите, во САД се појавија неколку нови филмови кои се занимаваа со темата на сексуалната ориентација.
  Одговор (Англиски): In the 1990s, several new films appeared in the United States that dealt with the subject of sexual orientation.
  Пример 7
  Македонски: Во 1990-

Batch 16
Despite these accusations, Ma easily won with a platform that advocates closer ties with continental China.
  Пример 6
  Македонски: Во 1990 година, во Македонија се одржаа првите парламентарни избори.
  Одговор (Англиски): In 1990, the first parliamentary elections were held in Macedonia.
  Пример 7
  Македонски: Во 1990 година, во Македонија се одржаа првите парламентарни избори.
  Одговор (Англиски): In

Batch 16
Today's player of the day is Alex Ovechkin of the Washington Capitals.
  Пример 6
  Македонски: Во 1990 година, во САД се појавија првите мобилни телефони.
  Одговор (Англиски): In 1990, the first mobile phones appeared in the United States.
  Пример 7
  Македонски: Во 1990 година, во САД се појавија првите мобилни телефони.
  Одговор (Англиски): In

Batch 24
There were 2 goals and 2 assists in the 5-3 win of Washington over Atlanta Thrashers.
Текст:Повеќе од 1000 луѓе се собраа на протестот против полициската бруталност во Њујорк.
Одговор (Англиски): More than 1000 people gathered at the protest against police brutality in New York.
Текст:Повеќе од 1000 луѓе се собраа на протестот против полициската бруталност во Њуј

Batch 24
The first assist of Ovechkin tonight was for the game-winning goal of the starter Nicklas Backstrom.
Текст:Поразот на "црвените ѓаволи" од 2:0 во првиот натпревар од четвртфиналето на НХЛ-лигата против "Канадиенс" во Торонто, беше првиот пораз на "Јангстарс" во последните 11 натпревари.
Одговор (Англиски): The loss of 2-0 in the first game

Batch 24
His second goal that evening was his 60th of the season, making him the first player to have scored 60 or more goals in a season since 1995-96, when that record was set by Jaromir Jagr and Mario Lemieux.
  Пример 6
  Македонски: Во 1990-тите години, во Македонија се појавија неколку нови партии, кои се обидоа да го променат политичкиот систем.
  Одговор (Англиски): In the 1990s

Batch 24
Batten was ranked 190th on the 2008 list of the 400 richest Americans with a fortune estimated at $2.3 billion.
Текст:Во 1999 година, Џејмс Батен беше избран за претседател на компанијата "Бенк оф Америка".
Одговор (Англиски): In 1999, James Batten was elected President of Bank of America.
Текст:Во 1999 година, Џејмс Батен беше избран за претседател на компа

Batch 24
He graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished himself as an important donor to the institution.
Текст:Постојат многу начини да се заштити приватноста на корисниците на интернет.
Одговор (Англиски): There are many ways to protect the privacy of internet users.
Текст:Постојат многу начини да се заштити приватноста на корисниците на интернет.
Одговор (Англиски): There are many ways to protect the privacy of internet users

Batch 24
The Iraqi prison "Abu Ghraib" was set on fire during a riot.
Текст:Во 1990 година, војската на САД го окупираше Кувајт.
Одговор (Англиски): In 1990, the United States Army occupied Kuwait.
Текст:Во 1990 година, војската на САД го окупираше Кувајт.
Одговор (Англиски): In 1990, the United States Army occupied Kuwait.
Текст:Во 199

Batch 24
The prison became infamous after allegations of abuse of prisoners were discovered after it was taken over by the U.S. military.
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Одговор (Англиски): This study focuses on the development of new methods for data analysis.
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Одговор (Англиски): This study focuses on the development of new methods for data analysis.
Текст

Batch 24
Текст:Пике Јуниор се судри во Сингапурскиот Гранд При 2008 веднаш по предвремен питстоп на Фернандо Алонсо, по што беше изнесено безбедносното возило.
Одговор (Англиски):
Текст:Пике Јуниор се судри во Сингапурскиот Гранд При 2008 веднаш по предвремен питстоп на Фернандо Алонсо, по што беше изнесено безбедносното во

Batch 32
While the cars in front of Alonso went to fill up at the pit stop, he took the lead to come in for the win.
  Пример 7
  Македонски: Во 1999 година, во Њујорк, беше отворен првиот ресторан за брза храна на светот.
  Одговор (Англиски): In 1999, in New York, the first fast food restaurant in the world was opened.
  Пример 8
  Македонски: Во 1999 година, во

Batch 32
Пике Помладиот беше отпуштен по унгарското Гран При во 2009 година.
  Пример 2
  Македонски: Во 1999 година, војската на САД го бомбардираше Косово.
  Одговор (Англиски): In 1999, the United States military bombed Kosovo.
  Пример 3
  Македонски: Во 1999 година, војската на САД го бомбардираше Косово.
  Одговор (

Batch 32
At exactly 8:46 am, there was a traffic jam throughout the city, which marked the exact moment when the first plane hit its target.
  Пример 6
  Македонски: Во 1990 година, во Македонија се одржаа првите парламентарни избори.
  Одговор (Англиски): In 1990, the first parliamentary elections were held in Macedonia.
  Пример 7
  Македонски: Во 1990 година, во Македонија се одржаа првите парламентарни избори

Batch 32
Two beams of light were set up to show at night towards the sky.
  Пример 7
  Македонски: Во 1990 година, во Македонија се одржаа првите парламентарни избори.
  Одговор (Англиски): In 1990, the first parliamentary elections were held in Macedonia.
  Пример 8
  Македонски: Во 1990 година, во Македонија се одржаа првите парламентарни избори.
  Одговор (Англиски): In 199

Batch 32
Construction is underway for five new skyscrapers on the site, with a transportation center and memorial park in the middle.
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Одговор (Англиски): This study focuses on the development of new methods for data analysis.
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Одговор (Англиски): This study focuses on the development of new methods for data analysis.
Текст:Ова

Batch 32
PBS series has more than two dozen Emmy awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.
Текст:Оваа книга е напишана од страна на еден од најпознатите писатели на сите времиња.
Одговор (Англиски): This book was written by one of the most famous writers of all time.
Текст:Оваа книга е напишана од страна на еден од најпознатите писатели на сите времиња.
Одговор (Англиски): This book was written by one of the most famous writers

Batch 32
Each episode of the show focused on a topic from a certain book, and then that topic was researched through multiple stories.
Текст:Оваа книга е напишана од страна на еден од најпознатите писатели на сите времиња.
Одговор (Англиски): This book was written by one of the most famous writers of all time.
Текст:Оваа книга е напишана од страна на еден од најпознатите писатели на сите времиња.
Одговор (Англиски): This book was written by one of the most

Batch 32
In addition, each show will provide recommendations for books that every child should look for when they go to the library.
  Пример 7
  Македонски: Во 1990 година, во Македонија е основана Агенција за млади и спорт.
  Одговор (Англиски): In 1990, the Agency for Youth and Sports was established in Macedonia.
  Пример 8
  Македонски: Во 1990 година, во Македонија е основана Агенција за млади и спорт.
  Од

Batch 40
John Grant, from WNED Buffalo ("Reading Rainbow's station home"), said: "Reading Rainbow's taught children why they should read... a love of reading  —  [the series] encouraged children to pick up a book and read."
  Пример 6
  Македонски: Во 1990-тите години, во САД, се појавија многу нови технологии, вклучувајќи ги и компјутерите, мобилните телефони и интернет.
  Одговор (Англиски): In the 1990s,

Batch 40
Some people, including John Grant, believe that the church-financier and the change in the philosophy of educational programming contributed to the cancellation of the show.
  Пример 6
  Македонски: Во 1990 година, во рамките на проектот "Европскиот модел на образование" се појавија неколку нови идеи за образованието.
  Одговор (Англиски): In 1990, within the "European Model of Education" project, several new ideas for education emerged.
  Пример 7
  Македон

Batch 40
The hurricane located 645 miles (1040 km) west of the Green Reef Islands, is likely to dissipate before posing a threat to any land area, say meteorologists.
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Одговор (Англиски): This study focuses on the development of new methods for data analysis.
Текст:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу е

Batch 40
At the moment, Fred is covering winds of 105 mph (165 km/h) and is moving north-northwest.
Текст:Оваа алатка е наменета за да им помогне на корисниците да ги подобрат своите вештини за пишување.
Одговор (Англиски): This tool is intended to help users improve their writing skills.
Текст:Оваа алатка е наменета за да им помогне на корисниците да ги подобрат своите вештини за пишување.
Одговор (А

Batch 40
Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic from the invention of satellite recordings, but it is only the third major hurricane recorded east of 35° W.
  Пример 6
  Македонски: Во 1990 година, во Македонија се одржаа првите парламентарни избори.
  Одговор (Англиски): In 1990, the first parliamentary elections were held in Macedonia.
  Пример 7
  Македонски: Во 1990 година, во Македонија се

Batch 40
On September 24, 1759, Arthur Guinness signed a 9,000-year lease for the St. James Gate Brewery in Dublin, Ireland.
  Пример 7
  Македонски: Во 1990-тите години, во САД се појавија неколку нови видови на рак, вклучувајќи го и ракот на дојка.
  Одговор (Англиски): In the 1990s, several new types of cancer appeared in the United States, including breast cancer.

Batch 40
250 years later, Guinness has grown into a global business with an annual turnover of 10 billion euros (14.7 billion dollars).
  Пример 6
  Македонски: Во 1990 година, во Њујорк, беше отворен првиот ресторан за брза храна "Мекдоналдс".
  Одговор (Англиски): In 1990, in New York, the first McDonald's fast food restaurant was opened.
  Пример 7
  Македонски: Во

Batch 40
Text: Jonny Reid, co-driver of the A1GP team from New Zealand, today created a historical event by passing through the 48-year-old Auckland Harbour Bridge in New Zealand and that too legally.
  Пример 6
  Македонски: Во 1990 година, во Њујорк, беше отворен првиот ресторан за брза храна на светот.
  Одговор (Англиски): In 1990, in New York, the first fast food restaurant in the world was opened.
  Пример

Batch 48

In [ ]:
predictions_new = [first_sentence(text) for text in predictions_eng]
predictions_new

['On Monday, scientists from the medical faculty at Stanford University announced that they have invented a new tool for diagnosis with which cells are sorted by type: it is a small printing chip that can be produced with the help of standard ink-jet printers, and it can be produced for about one cent.',
 'Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with low living standards, where the survival rate from diseases such as breast cancer can be twice as low as in richer countries.',
 'JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, causing the airport to be closed for commercial flights.',
 'It has been determined that the pilot was Dylocritus Patavius, the leader of the squadron.',
 'Local media report on a fire truck that overturned while firefighters responded to a call.',
 'Twenty-eight-year-old Vidal from Sevilla has joined the Barcelona team.',
 'After moving to the Catalan capital, Vidal played 49 games for the club.',
 'The protest began around 11:00 am local time (UTC+1) in Whitehall, across from the entrance guarded by police at Downing Street, the official residence of the Prime Minister.',
 'Immediately after 11:00 am, demonstrators blocked traffic heading north in Whitehall.',
 'At 11:20, the police asked the protesters to move to the sidewalk, citing that they should balance their right to protest with the traffic congestion.',
 'Around 11:29 am, the protest moved to White Hall, near Trafalgar Square, near Strand, passing by Aldwych and through Kingway to Holborn, where the Conservative Party held their Spring Forum at the Grand Connaught Rooms hotel.',
 "Nadal's personal record against the Canadian is 7 - 2.",
 'He recently lost to Raonic at the Brisbane Open.',
 'Nadal won 88% of the points at the net in the match, winning 76 points in the first serve.',
 'After the race, the King of the Earth said: "I am simply very excited to be back in the last rounds of the most important events.',
 'The term "Panama Papers" is a comprehensive term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were leaked to the press in the spring of 2016.',
 'According to the documents, fourteen banks helped wealthy clients hide billions of dollars in order to avoid taxes and other laws.',
 'The British newspaper "The Guardian" reported that "Deutsche Bank" controlled approximately one-third of the 1,200 provisional companies used to do so.',
 'This led to protests being organized around the world, a certain number of criminal prosecutions, and the Prime Ministers of Iceland and Pakistan resigned.',
 'Born in Hong Kong, Ma studied at the University of New York and at the Law School at Harvard, and had a U.S. permanent "green card".',
 'Xi implied during the election that Ma could flee the country in the event of a crisis.',
 'Hsieh also claimed that the photogenic Maya was more of a style than a substance.',
 'Despite these accusations, Ma easily won with a platform that advocates closer ties with continental China.',
 "Today's player of the day is Alex Ovechkin of the Washington Capitals.",
 'There were 2 goals and 2 assists in the 5-3 win of Washington over Atlanta Thrashers.',
 'The first assist of Ovechkin tonight was for the game-winning goal of the starter Nicklas Backstrom.',
 'His second goal that evening was his 60th of the season, making him the first player to have scored 60 or more goals in a season since 1995-96, when that record was set by Jaromir Jagr and Mario Lemieux.',
 'Batten was ranked 190th on the 2008 list of the 400 richest Americans with a fortune estimated at $2.3 billion.',
 'He graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished himself as an important donor to the institution.',
 'The Iraqi prison "Abu Ghraib" was set on fire during a riot.',
 'The prison became infamous after allegations of abuse of prisoners were discovered after it was taken over by the U.S. military.',
 'Текст:Пике Јуниор се судри во Сингапурскиот Гранд При 2008 веднаш по предвремен питстоп на Фернандо Алонсо, по што беше изнесено безбедносното возило.',
 'While the cars in front of Alonso went to fill up at the pit stop, he took the lead to come in for the win.',
 'Пике Помладиот беше отпуштен по унгарското Гран При во 2009 година.',
 'At exactly 8:46 am, there was a traffic jam throughout the city, which marked the exact moment when the first plane hit its target.',
 'Two beams of light were set up to show at night towards the sky.',
 'Construction is underway for five new skyscrapers on the site, with a transportation center and memorial park in the middle.',
 "PBS series has more than two dozen Emmy awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.",
 'Each episode of the show focused on a topic from a certain book, and then that topic was researched through multiple stories.',
 'In addition, each show will provide recommendations for books that every child should look for when they go to the library.',
 'John Grant, from WNED Buffalo ("Reading Rainbow\'s station home"), said: "Reading Rainbow\'s taught children why they should read... a love of reading  —  [the series] encouraged children to pick up a book and read."',
 'Some people, including John Grant, believe that the church-financier and the change in the philosophy of educational programming contributed to the cancellation of the show.',
 'The hurricane located 645 miles (1040 km) west of the Green Reef Islands, is likely to dissipate before posing a threat to any land area, say meteorologists.',
 'At the moment, Fred is covering winds of 105 mph (165 km/h) and is moving north-northwest.',
 'Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic from the invention of satellite recordings, but it is only the third major hurricane recorded east of 35° W.\n  Пример 6\n  Македонски: Во 1990 година, во Македонија се одржаа првите парламентарни избори.',
 'On September 24, 1759, Arthur Guinness signed a 9,000-year lease for the St. James Gate Brewery in Dublin, Ireland.',
 '250 years later, Guinness has grown into a global business with an annual turnover of 10 billion euros (14.7 billion dollars).',
 'Text: Jonny Reid, co-driver of the A1GP team from New Zealand, today created a historical event by passing through the 48-year-old Auckland Harbour Bridge in New Zealand and that too legally.',
 'Mr. Reid managed to drive the New Zealand A1GP car, the Black Beauty, at speeds over 160 km/h across the bridge seven times.',
 'New Zealand police faced a problem when using radar to determine speeds because of the height of the Black Beauty, and the only time the police caught Mr. Reed was when he slowed down to 160 km/h.',
 'In the last 3 months, over 80 prisoners were released from the detention center without being formally charged.',
 'In April this year, the order for a temporary restriction was issued by Judge Glenn against the institution for the accelerated release of those detained for more than 24 hours after arrest, who have not received a hearing by a court commissioner.',
 'The Commissioner determines bail, if allowed, and formalizes the charges filed by the officer who made the arrests.',
 'At this hearing, the date for the right of the defendant to a speedy trial will be determined.',
 'Peter Costello, the Australian Minister for Finance and the man with the greatest potential to replace John Howard as leader of the Liberal Party, has expressed his support for a nuclear energy industry in Australia.',
 'G. Costello said that when nuclear reactors become economically viable, Australia will begin to use them.',
 '"If it becomes commercially viable, we should have it.',
 'According to ANSA, "the police were concerned about several high-profile assassinations for which they feared could spark a war for succession in full swing."',
 "The police announced that Lo Piccolo had control because he was Provenzano's right-hand man in Palermo, and his greater experience had won him respect from the older generation of bosses because they followed Provenzano's policy of staying as hidden as possible while they strengthened their network of authority.",
 'These bosses were subdued by Provenzano when he put an end to the war sparked by Rina against the state that took the lives of the "Crusaders of the Mafia," Giovanni Falcone and Paolo Borsellino in 1992.',
 'The Executive Director of Apple, Steve Jobs, unveiled the device by standing on stage and pulling the iPhone out of his jeans pocket.',
 'During his two-hour speech, he said, "Apple will re-invent the phone.',
 'Brazil is the largest Roman Catholic country on Earth and the Roman Catholic Church is constantly opposed to the legalization of same-sex marriage in the country.',
 'The Brazilian State Congress has been debating the legalization of same-sex marriage for ten years now; and despite that, such civil marriages are currently only legal in Rio Grande do Sul.',
 'The original proposal was drafted by Marta Suplicy, the former mayor of Sao Paulo.',
 'The Protestants hope to collect 1.2 million signatures on the petition that they will present to the National Congress in November.',
 'After it became clear that many families were seeking legal help to fight evictions, a meeting was held on March 20th at the Community Law Center in East Bay for victims of housing fraud.',
 'When the tenants started to share what had happened to them, the majority of the involved families suddenly realized that Caroline Wilson from OHA had stolen their security deposits and had fled the town.',
 'Residents of Lockwood Gardens believe that there may be 40 families or more facing eviction, because they have learned that the OHA is investigating other public housing properties in Oakland that may be involved in the housing scam.',
 'The band has canceled the performance that was scheduled to take place at the Maui Military Memorial Stadium, where 9,000 people were expected to attend, and apologized to the fans.',
 "The band's management company, HK Management Inc., did not give an official statement on the reasons for the cancellation on September 20th, but the next day they stated that it was a logistical problem.",
 'The famous Greek lawyers, Sakkis Kehayioglu and George Nikolaopoulos, have been sentenced to prison in the Koridallos prison in Athens, after being found guilty of bribery and corruption.',
 'As a result, a great scandal erupted in the Greek legal community with the revelation of illegal acts committed by judges, lawyers, attorneys, and prosecutors in the past years.',
 'A few weeks ago, after the news was published by journalist Makis Triantafilopoulos in his popular television show "Zoungla" on Alpha TV, the MP and lawyer Petros Mantouvalos resigned because members of his cabinet were involved in bribery and corruption.',
 'In addition, the top judge Evangelos Kaltsis is in prison for corruption and improper behavior.',
 'Roberts was vehemently opposed to discussing his belief about when life begins, which is an important question when considering the ethics of abortion, saying that it would be unethical to comment on the specific details of potential cases.',
 'However, he confirmed his previous statement that Roe v. Wade is "the standard," emphasizing the importance of consistent Supreme Court decisions.',
 "He also confirmed that he believes in the non-negotiable right to privacy, which was the basis of Roe's decision.",
 'Text: Maruchidore finished at the top of the scale, with six points ahead of Nussa, who is second.',
 'The two teams met in the big semi-final, where Nussa came to victory with 11 points difference.',
 'Then Maruchidor defeated Kabultur in the preliminary final.',
 'Hesperonychus elizabethae is a species of the Dromaeosauridae family that is closely related to the velociraptor.',
 'It is believed that this warm-blooded bird-of-prey with feathers all over its body walked upright on two legs, with talons like those of a velociraptor.',
 'His second claw was larger, which gave him the name Hesperonichus, meaning "western claw".',
 'Extreme weather conditions, including ice that breaks, make rescue efforts difficult.',
 'Pittman hinted that conditions would not improve until next week.',
 'The amount and thickness of the ice, according to Pitman, is the worst it has been in the past 15 years for seal hunters.',
 'Today, in the town of Red Lake, after the funerals of Jeff Weise and three of the nine victims, news spread that another student was arrested in connection with the shooting at the school on March 21.',
 'The authorities have not officially stated much, except that they confirmed the arrest today.',
 'Still, an insider with knowledge of the investigation for the "Minneapolis Star-Tribune" said it was Louis Jourden, the 16-year-old son of the tribal president of Red Lake, Floyd Jourden.',
 'At this time, it is not known which charges will be filed, nor what led authorities to the boy, but the case against the minor has been filed in a federal court.',
 'Also, Lodin said that officials decided to cancel the second round of elections to spare the Afghans from expenses and to avoid a security risk from another vote.',
 'Diplomats said they found enough ambiguities in the Afghan Constitution to determine that a second round of elections was unnecessary.',
 'This is contradictory to previous statements, which said that the cancellation of the second round would be unconstitutional.',
 'The plane was heading to Irkutsk and was being flown by internal troops.',
 'An investigation was initiated to determine.',
 'II-76 was the largest component of the Russian and Soviet army since the 1970s, which last month experienced a serious accident in Russia.',
 'On October 7, the engine separated during takeoff, without injuries.',
 '800 miles of the Trans-Alaska pipeline were closed after thousands of barrels of crude oil flowed south of Fairbanks, Alaska.',
 'After a routine test of the fire management system, a power outage occurred that caused the pressure valves to open and crude oil to spill near Pump Station 9 at Fort Grilly.']

In [ ]:
predictions_new  = [text.split("\n")[0] for text in predictions_new]
predictions_new

['On Monday, scientists from the medical faculty at Stanford University announced that they have invented a new tool for diagnosis with which cells are sorted by type: it is a small printing chip that can be produced with the help of standard ink-jet printers, and it can be produced for about one cent.',
 'Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with low living standards, where the survival rate from diseases such as breast cancer can be twice as low as in richer countries.',
 'JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, causing the airport to be closed for commercial flights.',
 'It has been determined that the pilot was Dylocritus Patavius, the leader of the squadron.',
 'Local media report on a fire truck that overturned while firefighters responded to a call.',
 'Twenty-eight-year-old Vidal from Sevilla has joined the Barcelona team.',
 'After moving to the Catalan capital, Vidal played 49 games for the club.',
 'The protest began around 11:00 am local time (UTC+1) in Whitehall, across from the entrance guarded by police at Downing Street, the official residence of the Prime Minister.',
 'Immediately after 11:00 am, demonstrators blocked traffic heading north in Whitehall.',
 'At 11:20, the police asked the protesters to move to the sidewalk, citing that they should balance their right to protest with the traffic congestion.',
 'Around 11:29 am, the protest moved to White Hall, near Trafalgar Square, near Strand, passing by Aldwych and through Kingway to Holborn, where the Conservative Party held their Spring Forum at the Grand Connaught Rooms hotel.',
 "Nadal's personal record against the Canadian is 7 - 2.",
 'He recently lost to Raonic at the Brisbane Open.',
 'Nadal won 88% of the points at the net in the match, winning 76 points in the first serve.',
 'After the race, the King of the Earth said: "I am simply very excited to be back in the last rounds of the most important events.',
 'The term "Panama Papers" is a comprehensive term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were leaked to the press in the spring of 2016.',
 'According to the documents, fourteen banks helped wealthy clients hide billions of dollars in order to avoid taxes and other laws.',
 'The British newspaper "The Guardian" reported that "Deutsche Bank" controlled approximately one-third of the 1,200 provisional companies used to do so.',
 'This led to protests being organized around the world, a certain number of criminal prosecutions, and the Prime Ministers of Iceland and Pakistan resigned.',
 'Born in Hong Kong, Ma studied at the University of New York and at the Law School at Harvard, and had a U.S. permanent "green card".',
 'Xi implied during the election that Ma could flee the country in the event of a crisis.',
 'Hsieh also claimed that the photogenic Maya was more of a style than a substance.',
 'Despite these accusations, Ma easily won with a platform that advocates closer ties with continental China.',
 "Today's player of the day is Alex Ovechkin of the Washington Capitals.",
 'There were 2 goals and 2 assists in the 5-3 win of Washington over Atlanta Thrashers.',
 'The first assist of Ovechkin tonight was for the game-winning goal of the starter Nicklas Backstrom.',
 'His second goal that evening was his 60th of the season, making him the first player to have scored 60 or more goals in a season since 1995-96, when that record was set by Jaromir Jagr and Mario Lemieux.',
 'Batten was ranked 190th on the 2008 list of the 400 richest Americans with a fortune estimated at $2.3 billion.',
 'He graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished himself as an important donor to the institution.',
 'The Iraqi prison "Abu Ghraib" was set on fire during a riot.',
 'The prison became infamous after allegations of abuse of prisoners were discovered after it was taken over by the U.S. military.',
 'Текст:Пике Јуниор се судри во Сингапурскиот Гранд При 2008 веднаш по предвремен питстоп на Фернандо Алонсо, по што беше изнесено безбедносното возило.',
 'While the cars in front of Alonso went to fill up at the pit stop, he took the lead to come in for the win.',
 'Пике Помладиот беше отпуштен по унгарското Гран При во 2009 година.',
 'At exactly 8:46 am, there was a traffic jam throughout the city, which marked the exact moment when the first plane hit its target.',
 'Two beams of light were set up to show at night towards the sky.',
 'Construction is underway for five new skyscrapers on the site, with a transportation center and memorial park in the middle.',
 "PBS series has more than two dozen Emmy awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.",
 'Each episode of the show focused on a topic from a certain book, and then that topic was researched through multiple stories.',
 'In addition, each show will provide recommendations for books that every child should look for when they go to the library.',
 'John Grant, from WNED Buffalo ("Reading Rainbow\'s station home"), said: "Reading Rainbow\'s taught children why they should read... a love of reading  —  [the series] encouraged children to pick up a book and read."',
 'Some people, including John Grant, believe that the church-financier and the change in the philosophy of educational programming contributed to the cancellation of the show.',
 'The hurricane located 645 miles (1040 km) west of the Green Reef Islands, is likely to dissipate before posing a threat to any land area, say meteorologists.',
 'At the moment, Fred is covering winds of 105 mph (165 km/h) and is moving north-northwest.',
 'Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic from the invention of satellite recordings, but it is only the third major hurricane recorded east of 35° W.',
 'On September 24, 1759, Arthur Guinness signed a 9,000-year lease for the St. James Gate Brewery in Dublin, Ireland.',
 '250 years later, Guinness has grown into a global business with an annual turnover of 10 billion euros (14.7 billion dollars).',
 'Text: Jonny Reid, co-driver of the A1GP team from New Zealand, today created a historical event by passing through the 48-year-old Auckland Harbour Bridge in New Zealand and that too legally.',
 'Mr. Reid managed to drive the New Zealand A1GP car, the Black Beauty, at speeds over 160 km/h across the bridge seven times.',
 'New Zealand police faced a problem when using radar to determine speeds because of the height of the Black Beauty, and the only time the police caught Mr. Reed was when he slowed down to 160 km/h.',
 'In the last 3 months, over 80 prisoners were released from the detention center without being formally charged.',
 'In April this year, the order for a temporary restriction was issued by Judge Glenn against the institution for the accelerated release of those detained for more than 24 hours after arrest, who have not received a hearing by a court commissioner.',
 'The Commissioner determines bail, if allowed, and formalizes the charges filed by the officer who made the arrests.',
 'At this hearing, the date for the right of the defendant to a speedy trial will be determined.',
 'Peter Costello, the Australian Minister for Finance and the man with the greatest potential to replace John Howard as leader of the Liberal Party, has expressed his support for a nuclear energy industry in Australia.',
 'G. Costello said that when nuclear reactors become economically viable, Australia will begin to use them.',
 '"If it becomes commercially viable, we should have it.',
 'According to ANSA, "the police were concerned about several high-profile assassinations for which they feared could spark a war for succession in full swing."',
 "The police announced that Lo Piccolo had control because he was Provenzano's right-hand man in Palermo, and his greater experience had won him respect from the older generation of bosses because they followed Provenzano's policy of staying as hidden as possible while they strengthened their network of authority.",
 'These bosses were subdued by Provenzano when he put an end to the war sparked by Rina against the state that took the lives of the "Crusaders of the Mafia," Giovanni Falcone and Paolo Borsellino in 1992.',
 'The Executive Director of Apple, Steve Jobs, unveiled the device by standing on stage and pulling the iPhone out of his jeans pocket.',
 'During his two-hour speech, he said, "Apple will re-invent the phone.',
 'Brazil is the largest Roman Catholic country on Earth and the Roman Catholic Church is constantly opposed to the legalization of same-sex marriage in the country.',
 'The Brazilian State Congress has been debating the legalization of same-sex marriage for ten years now; and despite that, such civil marriages are currently only legal in Rio Grande do Sul.',
 'The original proposal was drafted by Marta Suplicy, the former mayor of Sao Paulo.',
 'The Protestants hope to collect 1.2 million signatures on the petition that they will present to the National Congress in November.',
 'After it became clear that many families were seeking legal help to fight evictions, a meeting was held on March 20th at the Community Law Center in East Bay for victims of housing fraud.',
 'When the tenants started to share what had happened to them, the majority of the involved families suddenly realized that Caroline Wilson from OHA had stolen their security deposits and had fled the town.',
 'Residents of Lockwood Gardens believe that there may be 40 families or more facing eviction, because they have learned that the OHA is investigating other public housing properties in Oakland that may be involved in the housing scam.',
 'The band has canceled the performance that was scheduled to take place at the Maui Military Memorial Stadium, where 9,000 people were expected to attend, and apologized to the fans.',
 "The band's management company, HK Management Inc., did not give an official statement on the reasons for the cancellation on September 20th, but the next day they stated that it was a logistical problem.",
 'The famous Greek lawyers, Sakkis Kehayioglu and George Nikolaopoulos, have been sentenced to prison in the Koridallos prison in Athens, after being found guilty of bribery and corruption.',
 'As a result, a great scandal erupted in the Greek legal community with the revelation of illegal acts committed by judges, lawyers, attorneys, and prosecutors in the past years.',
 'A few weeks ago, after the news was published by journalist Makis Triantafilopoulos in his popular television show "Zoungla" on Alpha TV, the MP and lawyer Petros Mantouvalos resigned because members of his cabinet were involved in bribery and corruption.',
 'In addition, the top judge Evangelos Kaltsis is in prison for corruption and improper behavior.',
 'Roberts was vehemently opposed to discussing his belief about when life begins, which is an important question when considering the ethics of abortion, saying that it would be unethical to comment on the specific details of potential cases.',
 'However, he confirmed his previous statement that Roe v. Wade is "the standard," emphasizing the importance of consistent Supreme Court decisions.',
 "He also confirmed that he believes in the non-negotiable right to privacy, which was the basis of Roe's decision.",
 'Text: Maruchidore finished at the top of the scale, with six points ahead of Nussa, who is second.',
 'The two teams met in the big semi-final, where Nussa came to victory with 11 points difference.',
 'Then Maruchidor defeated Kabultur in the preliminary final.',
 'Hesperonychus elizabethae is a species of the Dromaeosauridae family that is closely related to the velociraptor.',
 'It is believed that this warm-blooded bird-of-prey with feathers all over its body walked upright on two legs, with talons like those of a velociraptor.',
 'His second claw was larger, which gave him the name Hesperonichus, meaning "western claw".',
 'Extreme weather conditions, including ice that breaks, make rescue efforts difficult.',
 'Pittman hinted that conditions would not improve until next week.',
 'The amount and thickness of the ice, according to Pitman, is the worst it has been in the past 15 years for seal hunters.',
 'Today, in the town of Red Lake, after the funerals of Jeff Weise and three of the nine victims, news spread that another student was arrested in connection with the shooting at the school on March 21.',
 'The authorities have not officially stated much, except that they confirmed the arrest today.',
 'Still, an insider with knowledge of the investigation for the "Minneapolis Star-Tribune" said it was Louis Jourden, the 16-year-old son of the tribal president of Red Lake, Floyd Jourden.',
 'At this time, it is not known which charges will be filed, nor what led authorities to the boy, but the case against the minor has been filed in a federal court.',
 'Also, Lodin said that officials decided to cancel the second round of elections to spare the Afghans from expenses and to avoid a security risk from another vote.',
 'Diplomats said they found enough ambiguities in the Afghan Constitution to determine that a second round of elections was unnecessary.',
 'This is contradictory to previous statements, which said that the cancellation of the second round would be unconstitutional.',
 'The plane was heading to Irkutsk and was being flown by internal troops.',
 'An investigation was initiated to determine.',
 'II-76 was the largest component of the Russian and Soviet army since the 1970s, which last month experienced a serious accident in Russia.',
 'On October 7, the engine separated during takeoff, without injuries.',
 '800 miles of the Trans-Alaska pipeline were closed after thousands of barrels of crude oil flowed south of Fairbanks, Alaska.',
 'After a routine test of the fire management system, a power outage occurred that caused the pressure valves to open and crude oil to spill near Pump Station 9 at Fort Grilly.']

In [ ]:
references = [[ref] for ref in text_eng]
references[:10]

[['On Monday, scientists from the Stanford University School of Medicine announced the invention of a new diagnostic tool that can sort cells by type: a tiny printable chip that can be manufactured using standard inkjet printers for possibly about one U.S. cent each.'],
 ['Lead researchers say this may bring early detection of cancer, tuberculosis, HIV and malaria to patients in low-income countries, where the survival rates for illnesses such as breast cancer can be half those of richer countries.'],
 ['The JAS 39C Gripen crashed onto a runway at around 9:30 am local time (0230 UTC) and exploded, closing the airport to commercial flights.'],
 ['The pilot was identified as Squadron Leader Dilokrit Pattavee.'],
 ['Local media reports an airport fire vehicle rolled over while responding.'],
 ['28-year-old Vidal had joined Barça three seasons ago, from Sevilla.'],
 ['Since moving to the Catalan-capital, Vidal had played 49 games for the club.'],
 ["The protest started around 11:00 local time (UTC+1) on Whitehall opposite the police-guarded entrance to Downing Street, the Prime Minister's official residence."],
 ['Just after 11:00, protesters blocked traffic on the northbound carriage in Whitehall.'],
 ['At 11:20, the police asked the protesters to move back on to the pavement, stating that they needed to balance the right to protest with the traffic building up.']]

In [ ]:
bleu.compute(predictions=predictions_new, references=references)

{'bleu': 0.347303590070769,
 'precisions': [0.6513761467889908,
  0.4117647058823529,
  0.27855960264900664,
  0.19473229706390327],
 'brevity_penalty': 1.0,
 'length_ratio': 1.0447284345047922,
 'translation_length': 2616,
 'reference_length': 2504}

In [ ]:
chrf_score = sacrebleu.corpus_chrf(predictions_new, references)
print(f"chrF: {chrf_score.score:.2f}")

chrF: 55.42

## Few-Shot Cross-lingual prompt (MKD->ENG) in english language

In [ ]:
instruction = f"""Translate the following text from **Macedonian** to **English**. Only output the translation. Do not add explanations.
  Example 1
  Macedonian: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
  Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
  Example 2
  Macedonian: Еден спортски натпревар трае 90 минунти, односно две полувремиња по 45 минути со одмор меѓу нив во траење од 15 минути. Ако има подолги прекини во играта, таа се продолжува така што се надополнува изгубеното време.
  Response (English): A sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.
  Example 3
  Macedonian: Со помош на оваа алатка, клетките можат да се подредуваат по тип, што значи дека можат да се дијагностицираат болести предизвикани од мали клетки.
  Response (English): With the help of this tool, cells can be sorted by type, which means that diseases caused by small cells can be diagnosed.
  Example 4
  Macedonian: Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
  Response (English): This study focuses on the development of new methods for data analysis.
  Example 5
  Macedonian: Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.
  Response (English): In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
"""

In [ ]:
predictions_eng = batch_translate(text_mkd,instruction,max_new_tokens=128)

Batch 0
In the Monday, scientists from the medical faculty at Stanford University announced that they have invented a new tool for diagnosis with which cells are sorted by type: it is a small printing chip that can be produced with the help of standard ink-jet printers, and that can be produced for about one US cent.
Translate the following text from **Macedonian** to **English**. Only output the translation. Do not add explanations.
  Example 1
  Macedonian: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за

Batch 0
Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with low living standards, where the survival rate from diseases such as breast cancer can be twice as low as in richer countries.
Translate the following text from **Macedonian** to **English**. Only output the translation. Do not add explanations.
  Example 1
  Macedonian: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
  Response

Batch 0
JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, due to which the airport is closed for commercial flights.
Text:The 2019–2020 coronavirus pandemic in the United States is the ongoing health effects of the COVID-19 pandemic in the United States.
Response (English): The 2019–2020 coronavirus pandemic in the United States is the ongoing health effects of the COVID-19 pandemic in the United States.
Text:The 2019–2

Batch 0
It has been determined that the pilot was Dilokrit Patavi, the leader of the squadron.
Text:Во 1990 година, војската на САД го презеде командниот центар на НАТО во Германија.
Response (English): In 1990, the United States Army took over the NATO command center in Germany.
Text:Во 1990 година, војската на САД го презеде командниот центар на НАТО во Германија.
Response (English): In 1990, the United States Army took

Batch 0
Local media report on an airport fire truck that overturned while firefighters responded to a call.
Text:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Text:Еден спортски натпревар трае 90 минунти, односно две полувремиња по 45 мину

Batch 0
28-year-old Vidal from Sevilla joined the Barcelona team.
Text:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Text:Еден спортски натпревар трае 90 минунти, односно две полувремиња по 45 минути со

Batch 0
After moving to the Catalan capital, Vidal played 49 games for the club.
Text:Во 1999 година, тој беше избран за најдобар млад играч во Премиер лигата.
Response (English): In 1999, he was voted the best young player in the Premier League.
Text:Во 2000 година, тој беше избран за најдобар млад играч во Премиер лигата.
Response (English): In 2000, he was voted the best young player in the Premier League.
Text:Во

Batch 0
The protest began around 11:00 am local time (UTC+1) in Whitehall, across from the entrance guarded by Downing Street police, the official residence of the Prime Minister.
Text:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Text:Еден спортски нат

Batch 8
Immediately after 11:00 am, demonstrators blocked traffic towards the north in Whitehall.
Text:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Text:Еден спортски натпревар трае 90 минунти, односно две полувремиња по 4

Batch 8
At 11:20, the police asked the protesters to move to the sidewalk, citing that they should balance their right to protest with the traffic congestion.
Text:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Text:Еден спортски натпревар трае 9

Batch 8
Around 11:29 p.m., the protest moved to White Hall, near Trafalgar Square, near Strand, passing by Aldwych and through Kingway to Holborn, where the Conservative Party held their Spring Forum at the Grand Connaught Rooms hotel.
Translate the following text from **Macedonian** to **English**. Only output the translation. Do not add explanations.
  Example 1
  Macedonian: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските праша

Batch 8
Nadal's personal record against the Canadian is 7 - 2.
Text:Во 1999 година, на 10-годишна возраст, тој го освои првиот турнир во својата кариера.
Response (English): In 1999, at the age of 10, he won his first tournament in his career.
Text:Во 1999 година, на 10-годишна возраст, тој го освои првиот турнир во својата кариера.
Response (English): In

Batch 8
He recently lost to Raonic at the Brisbane Open.
Text:Неодамна изгуби од Раониќ на Бризбејн Опен.
Response (English): He recently lost to Raonic at the Brisbane Open.
Text:Неодамна изгуби од Раониќ на Бризбејн Опен.
Response (English): He recently lost to Raonic at the Brisbane Open.
Text:Неодамна изгуби од Раониќ на Бризбејн Опен.
Response (English): He recently lost to Raonic at the Brisbane Open.
Text:

Batch 8
Nadal won 88% of the points at the net in the match, winning 76 points in the first service.
Text:Надал освои 88 % од поените на мрежа во мечот, освојувајќи 76 поени во првиот сервис.
Response (English): Nadal won 88% of the points at the net in the match, winning 76 points in the first service.
Text:Надал освои 88 % од поените на мрежа во мечот, освојувајќи

Batch 8
After the race, the King of the Earth said: "I am simply very excited to be back in the last rounds of the most important events. I am here to try to win."
Text:Во 1990 година, во 1990 година, во 1990 година, во 1990 година, во 1990 година, во 1990 година, во 1990 година, во 1990 година, во 1990 година, во 1990 година, во 1990 година

Batch 8
"The Panama Papers" is a comprehensive term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were leaked to the press in the spring of 2016.
Text:Во 1990 година, во Њујорк, беше отворен првиот ресторан за брза храна "Мекдоналдс".
Response (English): In 1990, in New York, the first McDonald's fast food restaurant was opened.
Text:Во 1990 година, во Њујорк, беше от

Batch 16
According to the documents, fourteen banks helped wealthy clients hide billions of dollars in order to avoid paying taxes and other laws.
Text:Во 1990 година, во САД, 100.000 луѓе биле вработени во индустријата за производство на оружје.
Response (English): In 1990, in the United States, 100,000 people were employed in the weapons manufacturing industry.
Text:Во 1990 година, во САД, 100.000 луѓе би

Batch 16
The British newspaper "The Guardian" reported that "Deutsche Bank" controlled about a third of the 1,200 provisional companies used to achieve that.
Text:Во 1990 година, во САД, 100.000 луѓе биле вработени во индустријата за производство на автомобили.
Response (English): In 1990, in the United States, 100,000 people were employed in the automobile manufacturing industry.
Text:Во 1990 година, во САД, 100.

Batch 16
This led to protests being organized around the world, a certain number of criminal prosecutions, and the Prime Ministers of Iceland and Pakistan resigned.
Text:Во 1990 година, тој беше избран за претседател на Република Македонија.
Response (English): In 1990, he was elected President of the Republic of Macedonia.
Text:Во 1990 година, тој беше избран за претседател на Република Македонија.
Response (English): In 1990, he was elected President of the Republic of Macedonia.
Text:

Batch 16
Born in Hong Kong, Ma studied at the University of New York and at the Law School at Harvard, and had a permanent American "green card".
Text:Во 1999 година, тој беше назначен за главен извршен директор на компанијата "Алибаба", која е една од најголемите е-трговски компании во светот.
Response (English): In 1999, he was appointed CEO of the company "Alibaba", which is one of the largest e-commerce companies in the world.
Text:Во 2000 година,

Batch 16
Hsieh implied during the elections that Ma could flee the country in the event of a crisis.
Text:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Text:Еден спортски натпревар трае 90 минунти, односно две полувремиња по 4

Batch 16
Text:Во 1990 година, во Њујорк, беше отворен првиот ресторан за брза храна во светот.
Response (English):
Text:Во 1990 година, во Њујорк, беше отворен првиот ресторан за брза храна во светот.
Response (English):
Text:Во 1990 година, во Њујорк, беше отворен првиот ресторан за брза храна во светот.
Response (English):
Text:Во

Batch 16
Despite these accusations, Ma easily won with a platform that advocates closer ties with continental China.
Text:Во 1990 година, војската на САД го презеде командното раководство над сите американски сили во Европа.
Response (English): In 1990, the U.S. Army assumed command of all U.S. forces in Europe.
Text:Во 1990 година, војската на САД го презеде командното раководство над сите американски сили во Европа.
Response (English): In 199

Batch 16
Today, player of the day is Alex Ovechkin of the Washington Capitals.
Text:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Text:Еден спортски натпревар трае 90 минунти, односно две полувремиња по 45 минути

Batch 24
There were 2 goals and 2 assists in the 5-3 win of Washington against Atlanta Thrashers.
Text:Имаше 2 гола и 2 асистенции во победата од 5-3 на Вашингтон против Атланта Трешерс.
Response (English): There were 2 goals and 2 assists in the 5-3 win of Washington against Atlanta Thrashers.
Text:Имаше 2 гола и 2 асистенции во победата од 5-3 на Вашингтон против Атланта Трешерс.
Response (

Batch 24
Ovechkin's first assist of the night was for the game-winning goal by the starter Nicklas Backstrom.
Text:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Text:Еден спортски натпревар трае 90 минунти, односно две полу

Batch 24
His second goal that night was the 60th of the season, making him the first player to have scored 60 or more goals in a season since 1995-96, when that record was set by Jaromir Jagr and Mario Lemieux.
Text:Во 1999 година, тој беше избран за најдобар млад играч во НХЛ.
Response (English): In 1999, he was named the NHL's best rookie.
Text:Во 2000 година, тој беше избран за најдобар млад играч

Batch 24
Batten was ranked 190th on the list of 400 richest Americans in 2008 with a fortune estimated at $2.3 billion.
Text:Во 1999 година, тој беше избран за член на Американската академија на науките и уметностите.
Response (English): In 1999, he was elected a member of the American Academy of Arts and Sciences.
Text:Во 2000 година, тој беше избран за член на Американската академија на уметностите и науките.
Response

Batch 24
He graduated from the College of Arts and Sciences at the University of Virginia in 1950 and was distinguished as an important donor to the institution.
Text:Во 1990 година, тој беше назначен за претседател на Одборот на директори на компанијата.
Response (English): In 1990, he was appointed President of the Board of Directors of the Company.
Text:Во 1991 година, тој беше назначен за претседател на Одборот на директори на компанијата.
Response (English): In

Batch 24
The Iraqi prison "Abu Ghraib" was set on fire during a riot.
Text:Во 1990 година, војската на САД го окупираше Кувајт.
Response (English): In 1990, the United States Army occupied Kuwait.
Text:Во 1990 година, војската на САД го окупираше Кувајт.
Response (English): In 1990, the United States Army occupied Kuwait.
Text:Во 1990 година, војската на САД го оку

Batch 24
The prison became infamously known after the abuse of prisoners was discovered after it was taken over by the American military.
Text:Во 1990 година, војската на САД го презеде Багдад, а во 1991 година, Ирак беше подложен на инвазија од страна на коалицијата предводена од САД.
Response (English): In 1990, the United States military took over Baghdad, and in 1991, Iraq was subjected to an invasion led by the United States-led coalition.
Text

Batch 24
Text:Пике Јуниор се судри во Сингапурскиот Гранд При 2008 веднаш по предвремен питстоп на Фернандо Алонсо, по што беше изнесено безбедносното возило.
Response (English):
Text:Пике Јуниор се судри во Сингапурскиот Гранд При 2008 веднаш по предвремен питстоп на Фернандо Алонсо, по што беше изнесено безбедносното возило.
Response (

Batch 32
While the cars in front of Alonso went to fill up their fuel after the safety car, he took the lead to come to victory.
Text:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Text:Еден спортски натпревар трае 90 минунти, односно

Batch 32
Pike Younger was fired after the Hungarian Grand Prix in 2009.
Text:Во 1999 година, тој беше избран за најдобар млад фудбалер во Европа.
Response (English): In 1999, he was voted the best young footballer in Europe.
Text:Во 2000 година, тој беше избран за најдобар млад фудбалер во Европа.
Response (English): In 2000, he was voted the best young footballer in Europe.
Text:Во 2001 година, тој беше

Batch 32
At exactly 8:46 am, there was a traffic jam throughout the city, which marked the exact moment when the first plane hit its target.
Text:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Text:Еден спортски натпревар трае 90 мину

Batch 32
Two beams of light were set to show night towards the sky.
Text:Во 1990 година, во Њујорк, беше отворен првиот ресторан за брза храна во светот.
Response (English): In 1990, in New York, the first fast food restaurant in the world was opened.
Text:Во 1990 година, во Њујорк, беше отворен првиот ресторан за брза храна во светот.
Response (English): In 1990, in New York,

Batch 32
Construction is underway for five new skyscrapers on the site, with a transportation center and memorial park in the middle.
Text:Во 1990 година, војската на САД го презеде управувањето со истражувачкиот центар за вселенски летови.
Response (English): In 1990, the United States Army took over management of the Space Flight Research Center.
Text:Во 1990 година, војската на САД го презеде управувањето со истражувачкиот центар за вселенски лето

Batch 32
PBS series has more than two dozen Emmy awards and is shorter to air than Sesame Street and Mr. Rogers' Neighborhood.
Text:Во 1990 година, Џејмс Камерон ја режираше филмската адаптација на романот на Стивен Кинг, "Твин Пикс".
Response (English): In 1990, James Cameron directed the film adaptation of Stephen King's novel, "Twin Peaks".
Text:Во 1990 година, Џејмс Камерон ја режираше филмската адаптација

Batch 32
Each episode of the show focused on a topic from a certain book, and then that topic was researched through multiple stories.
Text:Во 1990 година, во Њујорк, беше отворен првиот ресторан за брза храна во светот.
Response (English): In 1990, in New York, the first fast food restaurant in the world was opened.
Text:Во 1990 година, во Њујорк, беше отворен првиот ресторан за брза храна во светот.
Response (English):

Batch 32
In addition, each show will provide recommendations for books that every child should look for when they go to the library.
Text:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Response (English): This study focuses on the development of new methods for data analysis.
Text:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Response (English): This study focuses on the development of new methods for data analysis.
Text:Оваа студија се фокусира на разво

Batch 40
John Grant, from WNED Buffalo ("Reading Rainbow's station home"), said: "Reading Rainbow's taught children why they should read... the love of reading  —  [the series] encouraged children to take a book and read."
Text:Во 1990 година, Џон Грант, од WNED Buffalo ("Reading Rainbow's станицата домаќин), рече: "Reading Rainbow's ги научи децата зошто треба да читаат... љубовта кон читањето  —  [серијата] ги охрабри децата да земат книга

Batch 40
Some people, including John Grant, believe that the church-financier and the change in the philosophy of educational content programs contributed to the cancellation of the show.
Text:Во 1999 година, Џон Грант ја напушти емисијата и се пресели во Њујорк, каде што продолжи да работи како писател и продуцент.
Response (English): In 1999, John Grant left the show and moved to New York, where he continued to work as a writer and producer.
Text:Во 2000 година

Batch 40
The hurricane located 645 miles (1040 km) west of the Green Bay Islands, is likely to dissipate before posing any threat to any land area, say meteorologists.
Text:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Text:Еден спортски нат

Batch 40
At the moment, Fred covers winds blowing at 105 mph (165 km/h) and moving towards the northwest.
Text:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Response (English): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Text:Еден спортски натпревар трае 90 минунти, одно

Batch 40
Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic since the advent of satellite recordings, but it is only the third major hurricane recorded east of 35° W.

In [ ]:
predictions_new = [first_sentence(text) for text in predictions_eng]
predictions_new

['In the Monday, scientists from the medical faculty at Stanford University announced that they have invented a new tool for diagnosis with which cells are sorted by type: it is a small printing chip that can be produced with the help of standard ink-jet printers, and that can be produced for about one US cent.',
 'Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with low living standards, where the survival rate from diseases such as breast cancer can be twice as low as in richer countries.',
 'JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, due to which the airport is closed for commercial flights.',
 'It has been determined that the pilot was Dilokrit Patavi, the leader of the squadron.',
 'Local media report on an airport fire truck that overturned while firefighters responded to a call.',
 '28-year-old Vidal from Sevilla joined the Barcelona team.',
 'After moving to the Catalan capital, Vidal played 49 games for the club.',
 'The protest began around 11:00 am local time (UTC+1) in Whitehall, across from the entrance guarded by Downing Street police, the official residence of the Prime Minister.',
 'Immediately after 11:00 am, demonstrators blocked traffic towards the north in Whitehall.',
 'At 11:20, the police asked the protesters to move to the sidewalk, citing that they should balance their right to protest with the traffic congestion.',
 'Around 11:29 p.m., the protest moved to White Hall, near Trafalgar Square, near Strand, passing by Aldwych and through Kingway to Holborn, where the Conservative Party held their Spring Forum at the Grand Connaught Rooms hotel.',
 "Nadal's personal record against the Canadian is 7 - 2.",
 'He recently lost to Raonic at the Brisbane Open.',
 'Nadal won 88% of the points at the net in the match, winning 76 points in the first service.',
 'After the race, the King of the Earth said: "I am simply very excited to be back in the last rounds of the most important events.',
 '"The Panama Papers" is a comprehensive term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were leaked to the press in the spring of 2016.',
 'According to the documents, fourteen banks helped wealthy clients hide billions of dollars in order to avoid paying taxes and other laws.',
 'The British newspaper "The Guardian" reported that "Deutsche Bank" controlled about a third of the 1,200 provisional companies used to achieve that.',
 'This led to protests being organized around the world, a certain number of criminal prosecutions, and the Prime Ministers of Iceland and Pakistan resigned.',
 'Born in Hong Kong, Ma studied at the University of New York and at the Law School at Harvard, and had a permanent American "green card".',
 'Hsieh implied during the elections that Ma could flee the country in the event of a crisis.',
 'Text:Во 1990 година, во Њујорк, беше отворен првиот ресторан за брза храна во светот.',
 'Despite these accusations, Ma easily won with a platform that advocates closer ties with continental China.',
 'Today, player of the day is Alex Ovechkin of the Washington Capitals.',
 'There were 2 goals and 2 assists in the 5-3 win of Washington against Atlanta Thrashers.',
 "Ovechkin's first assist of the night was for the game-winning goal by the starter Nicklas Backstrom.",
 'His second goal that night was the 60th of the season, making him the first player to have scored 60 or more goals in a season since 1995-96, when that record was set by Jaromir Jagr and Mario Lemieux.',
 'Batten was ranked 190th on the list of 400 richest Americans in 2008 with a fortune estimated at $2.3 billion.',
 'He graduated from the College of Arts and Sciences at the University of Virginia in 1950 and was distinguished as an important donor to the institution.',
 'The Iraqi prison "Abu Ghraib" was set on fire during a riot.',
 'The prison became infamously known after the abuse of prisoners was discovered after it was taken over by the American military.',
 'Text:Пике Јуниор се судри во Сингапурскиот Гранд При 2008 веднаш по предвремен питстоп на Фернандо Алонсо, по што беше изнесено безбедносното возило.',
 'While the cars in front of Alonso went to fill up their fuel after the safety car, he took the lead to come to victory.',
 'Pike Younger was fired after the Hungarian Grand Prix in 2009.',
 'At exactly 8:46 am, there was a traffic jam throughout the city, which marked the exact moment when the first plane hit its target.',
 'Two beams of light were set to show night towards the sky.',
 'Construction is underway for five new skyscrapers on the site, with a transportation center and memorial park in the middle.',
 "PBS series has more than two dozen Emmy awards and is shorter to air than Sesame Street and Mr. Rogers' Neighborhood.",
 'Each episode of the show focused on a topic from a certain book, and then that topic was researched through multiple stories.',
 'In addition, each show will provide recommendations for books that every child should look for when they go to the library.',
 'John Grant, from WNED Buffalo ("Reading Rainbow\'s station home"), said: "Reading Rainbow\'s taught children why they should read... the love of reading  —  [the series] encouraged children to take a book and read."',
 'Some people, including John Grant, believe that the church-financier and the change in the philosophy of educational content programs contributed to the cancellation of the show.',
 'The hurricane located 645 miles (1040 km) west of the Green Bay Islands, is likely to dissipate before posing any threat to any land area, say meteorologists.',
 'At the moment, Fred covers winds blowing at 105 mph (165 km/h) and moving towards the northwest.',
 'Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic since the advent of satellite recordings, but it is only the third major hurricane recorded east of 35° W.\nText:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.',
 'On September 24, 1759, Arthur Guinness  signed a 9,000-year lease for the St. James Gate Brewery in Dublin, Ireland.',
 '250 years later, "Guinness" has grown into a global business with an annual turnover of 10 billion euros (14.7 billion dollars).',
 'Text:Џони Рид, совозач на тимот на А1ГП од Нов Зеланд, денес создаде историски настан најбрзо поминувајќи преку 48-годишниот Оклендски пристанишен мост во Нов Зеланд и тоа легално.',
 'Mr. Reid managed to drive the New Zealand A1GP car, the Black Beauty, at speeds over 160 km/h across the bridge seven times.',
 'New Zealand police faced a problem when using the radar to determine the speed of Mr. Reed, due to the height of the Black Beauty, and the only time the police managed to catch Mr. Reed was when he slowed down to 160 km/h.',
 'In the last 3 months, over 80 detainees were released from the detention center without being formally charged.',
 'In April this year, the order for a temporary restriction was issued by Judge Glin against the institution for the accelerated release of those detained for more than 24 hours after arrest, who have not received a hearing by a court commissioner.',
 'The Commissioner determines bail, if allowed, and formalizes the charges filed by the officer who made the arrests.',
 'Text:На ова сослушување ќе се одреди и датумот за правото на осомничениот за брзо донесување пресуда.',
 "Peter Costello, Australia's Minister for Finance and the man with the greatest potential to replace Prime Minister John Howard as leader of the Liberal Party, expressed his support for a nuclear energy industry in Australia.",
 'G. Costello said that when nuclear reactors become economically viable, Australia will start using them.',
 '"If it becomes commercially viable, we should have it.',
 'According to ANSA, "the police were concerned about several high-profile assassinations for which they feared could spark a war for succession in full swing."',
 "The police announced that Lo Piccolo had control because he was the right hand of Provencano in Palermo, and his greater experience had won the respect of the older generation of bosses because they followed Provencano's policy of staying as hidden as possible while they strengthened their network of authority.",
 'These bosses were subdued by Provenzano when he put an end to the war sparked by Rina against the state that took the lives of the "Mafia Crusaders", Giovanni Falcone and Paolo Borsellino in 1992.',
 'The CEO of Apple, Steve Jobs, unveiled the device by standing on stage and pulling the iPhone out of his jeans pocket.',
 'During his two-hour speech, he stated that "Apple will once again reinvent the phone.',
 'Brazil is the largest Roman Catholic country on Earth and the Roman Catholic Church is constantly against the legalization of same-sex marriage in the country.',
 'The Brazilian State Congress has been debating the legalization of same-sex marriages for ten years now; and despite that, such civil marriages are currently only legally recognized in Rio Grande do Sul.',
 'The original draft law was drafted by Marta Suplicy, the former mayor of Sao Paulo.',
 'The Protestants hope to collect 1.2 million signatures for the petition that will be presented before the National Congress in November.',
 'After it became clear that many families were seeking legal assistance to fight evictions, a meeting was held at the Community Law Center in East Bay on March 20th, for victims of housing fraud.',
 'When the residents started sharing what had happened to them, a larger part of the involved families suddenly realized that Caroline Wilson from OHCA had stolen their security deposits and had fled the city.',
 'Residents of Lockwood Gardens believe that there may be 40 families or more facing eviction, because they have learned that the OHA is investigating other public housing properties in Oakland that may be involved in the housing scam.',
 'The band has canceled the performance that was scheduled to take place at the Maui Military Memorial Stadium, where 9,000 people were supposed to attend, and apologized to the fans.',
 "The band's management company, HK Management Inc., did not give an official statement on the reasons for the cancellation on September 20th, but the next day they stated that it was a logistical problem.",
 'The famous Greek lawyers, Sakkis Kehayioglu and George Nikolaopoulos, are imprisoned in the Koridallos prison in Athens, after being found guilty of bribery and corruption.',
 'As a result, a great scandal erupted in the Greek legal community with the revelation of illegal acts committed by judges, lawyers, attorneys and prosecutors in the past years.',
 'A few weeks ago, after the news was published by journalist Makis Triantafilopoulos in his popular television show "Zoungla" on Alpha TV, the MP and lawyer Petros Mantouvalos resigned because members of his cabinet were involved in bribery and corruption.',
 'In addition, the top judge Evangelos Kalusis is in custody for corruption and improper behavior.',
 'Roberts indifferently refused to discuss his belief about when life begins, which is an important question considering the ethics of abortion, saying that it would be unethical to comment on the specific details of potential cases.',
 'However, he confirmed his previous statement that Roe v. Wade is "the standard," emphasizing the importance of consistent Supreme Court decisions.',
 "It also confirmed that he believed in the non-negotiable right to privacy, which was the basis of Roe's decision.",
 'Maruchidore finished at the top of the scale, with six points ahead of Nussa, who is second.',
 'The two teams met in the big semi-final, where Nussa came to victory with 11 points difference.',
 'Then Maruchidor defeated Kabultur in the preliminary final.',
 'Hesperonychus elizabethae is a species of the Dromaeosauridae family that is closely related to the velociraptor.',
 'It is believed that this feathered, warm-blooded bird-of-prey with feathers all over its body walked upright on two legs, with talons like those of a velociraptor.',
 'His second claw was larger, after which the name Hesperonichus was derived, which means "western claw".',
 'Extreme weather conditions, including the ice that breaks, make the rescue efforts difficult.',
 'Pittman hinted that the conditions would not improve until next week.',
 'The quantity and thickness of the ice, according to Pittman, is the worst in the past 15 years for seal hunters.',
 'Today, in the town of Red Lake, after the funerals of Jeff Weise and three of the nine victims, news spread that another student was arrested in connection with the shooting at the school on March 21.',
 'The authorities have not officially stated much, except that they confirmed the arrest today.',
 'Text:Сепак, извор со познавања од истрагата за "Минеаполис Стар-Трибјун" изјави дека се работи за Луис Журден, 16-годишниот син на племенскиот претседател на Ред Лејк, Флојд Журден.',
 'At this time, it is not known which charges will be filed, nor what led the authorities to the boy, but the case against the minor has been filed in a federal court.',
 'It was also said by Lodin that the officials decided to cancel the second round of elections in order to spare the Afghans from expenses and to avoid a security risk from another vote.',
 'Diplomats said they found enough ambiguities in the Afghan Constitution to determine that a second round of elections was unnecessary.',
 'This is contradictory to previous statements, which said that the cancellation of the second round would be unconstitutional.',
 'The plane was heading to Irkutsk and was being operated by internal troops.',
 'An investigation was initiated to examine.',
 'II-76 was the largest component of the Russian and Soviet army since the 1970s, which last month experienced a serious accident in Russia.',
 'On October 7, the engine separated during takeoff, without injuries.',
 '800 miles of the Trans-Alaska oil pipeline were closed after thousands of barrels of crude oil leaked south of Fairbanks, Alaska.',
 'After a routine test of the fire management system, a power outage occurred that caused the pressure valves to open and crude oil to spill near the pump station 9 at Fort Grilly.']

In [ ]:
references = [[ref] for ref in text_eng]
references[:10]

[['On Monday, scientists from the Stanford University School of Medicine announced the invention of a new diagnostic tool that can sort cells by type: a tiny printable chip that can be manufactured using standard inkjet printers for possibly about one U.S. cent each.'],
 ['Lead researchers say this may bring early detection of cancer, tuberculosis, HIV and malaria to patients in low-income countries, where the survival rates for illnesses such as breast cancer can be half those of richer countries.'],
 ['The JAS 39C Gripen crashed onto a runway at around 9:30 am local time (0230 UTC) and exploded, closing the airport to commercial flights.'],
 ['The pilot was identified as Squadron Leader Dilokrit Pattavee.'],
 ['Local media reports an airport fire vehicle rolled over while responding.'],
 ['28-year-old Vidal had joined Barça three seasons ago, from Sevilla.'],
 ['Since moving to the Catalan-capital, Vidal had played 49 games for the club.'],
 ["The protest started around 11:00 local time (UTC+1) on Whitehall opposite the police-guarded entrance to Downing Street, the Prime Minister's official residence."],
 ['Just after 11:00, protesters blocked traffic on the northbound carriage in Whitehall.'],
 ['At 11:20, the police asked the protesters to move back on to the pavement, stating that they needed to balance the right to protest with the traffic building up.']]

In [ ]:
bleu.compute(predictions=predictions_new, references=references)

{'bleu': 0.33253504408485496,
 'precisions': [0.6280556600225649,
  0.39546697928878466,
  0.26636844245628305,
  0.18482407799915218],
 'brevity_penalty': 1.0,
 'length_ratio': 1.0619009584664536,
 'translation_length': 2659,
 'reference_length': 2504}

In [ ]:
chrf_score = sacrebleu.corpus_chrf(predictions_new, references)
print(f"chrF: {chrf_score.score:.2f}")

chrF: 55.38

## Few-Shot Cross-lingual prompt (MKD->ENG) in serbian language

In [ ]:
instruction= f"""Преведи следећи текст са **Македонског** на **Енглески** језик.
Само испиши превод. Не додавај никаква објашњења.

Пример 1
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 2
Македонски: Еден спортски натпревар трае 90 минути, односно две полувремиња по 45 минути со одмор помеѓу нив во траење од 15 минути. Ако има подолги прекини во играта, таа се продолжува така што се надополнува изгубеното време.
Одговор (Енглески): A sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.

Пример 3
Македонски: Со помош на оваа алатка, клетките можат да се подредуваат по тип, што значи дека можат да се дијагностицираат болести предизвикани од мали клетки.
Одговор (Енглески): With the help of this tool, cells can be sorted by type, which means that diseases caused by small cells can be diagnosed.

Пример 4
Македонски: Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Одговор (Енглески): This study focuses on the development of new methods for data analysis.

Пример 5
Македонски: Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.
Одговор (Енглески): In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
"""

In [ ]:
predictions_eng = batch_translate(text_mkd,instruction,max_new_tokens=128,lang_code="srb",language="Енглески")

Batch 0
On Monday, scientists from the medical faculty at Stanford University announced that they have invented a new tool for diagnosis that sorts cells by type: it's a small printing chip that can be produced with standard ink-jet printers, for a price of about one U.S. cent.
Пример 1
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting

Batch 0
Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with low living standards, where the survival rate from diseases such as breast cancer can be twice as low as in richer countries.
Пример 1
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the

Batch 0
JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, causing the airport to be closed for commercial flights.
Текст:Оваа статија е за еден од најпознатите и најпознатите ликови во историјата на филмот.
Одговор (Енглески): This article is about one of the most famous and most famous characters in the history of cinema.
Текст:Оваа статија е за еден од најпознатите и најпознатите ликови во

Batch 0
It has been determined that the pilot was Dylokrit Patavi, the leader of the squadron.
Пример 6
Македонски: Во 1990 година, војската на САД го презеде командното раководство над силите на НАТО во Европа.
Одговор (Енглески): In 1990, the United States Army assumed command of NATO forces in Europe.
Пример 7
Македонски: Во 1990 година, војската на САД го презеде командното раководство над си

Batch 0
Local media report on a fire truck that overturned while firefighters responded to a call.
Текст:Полицијата во Њујорк ги предупреди граѓаните да не се движат по улиците во близина на полициските станици.
Одговор (Енглески): The police in New York have warned citizens not to move around the streets near police stations.
Текст:Полицијата во Њујорк ги предупреди граѓаните да не се движат по улиците во близина на полициските станици.
Одговор (Енгле

Batch 0
28-year-old Vidal from Sevilla has joined the Barcelona team.
Текст:Повеќе од 100.000 луѓе се собраа на улиците на Лондон за да го прослават крајот на Втората светска војна.
Одговор (Енглески): More than 100,000 people gathered on the streets of London to celebrate the end of World War II.
Текст:Повеќе од 100.000 луѓе се собраа на улиците на Лондон за да

Batch 0
After moving to the Catalan capital, Vidal played 49 games for the club.
Текст:Постојат многу теории за потеклото на името на овој град.
Одговор (Енглески): There are many theories about the origin of the name of this city.
Текст:Постојат многу теории за потеклото на името на овој град.
Одговор (Енглески): There are many theories about the origin of the name of this city.
Текст:Постојат многу теории за потеклото на

Batch 0
The protest began around 11:00 am local time (UTC+1) in Whitehall, across from the entrance guarded by police at Downing Street, the official residence of the Prime Minister.
Пример 1
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to

Batch 8
Immediately after 11:00 am, demonstrators blocked traffic heading north in Whitehall.
Текст:Повеќе од 100 луѓе се собраа на протестот во Лондон, кој се одржа во неделата, за да го искажат своето незадоволство од одлуката на британската влада да го намали буџетот за образование.
Одговор (Енглески): More than 100 people gathered at the protest in London, which took place on Sunday, to express their dissatisfaction with the British government's decision to cut the

Batch 8
At 11:20, the police asked the protesters to move to the sidewalk, citing that they should balance the right to protest with the traffic congestion.
Пример 1
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Пример

Batch 8
Around 11:29 am, the protest moved to White Hall, near Trafalgar Square, near Strand, passing by Aldwych and through Kingway to Holborn, where the Conservative Party held their Spring Forum at the Grand Connaught Rooms hotel.
Пример 6
Македонски: Во 1990 година, во Велика Британија се одржани парламентарни избори.
Одговор (Енглески): In 1990, parliamentary elections were held in the United Kingdom.
Пример 7
Македонски: Во 1990 година,

Batch 8
Nadal's personal record against the Canadian is 7 - 2.
Текст:Оваа година, ќе се одржат 100-тиот и 101-от роденден на Мајкл Џордан.
Одговор (Енглески): This year, Michael Jordan will celebrate his 100th and 101st birthday.
Текст:Оваа година, ќе се одржат 100-тиот и 101-от роденден на Мајкл Џордан

Batch 8
He recently lost to Raonic at the Brisbane Open.
Текст:Неговата мајка е од Шкотска, а татко му од Ирска.
Одговор (Енглески): His mother is from Scotland and his father is from Ireland.
Текст:Неговата мајка е од Шкотска, а татко му од Ирска.
Одговор (Енглески): His mother is from Scotland and his father is from Ireland.
Текст:Неговата мајка е од Шкотска, а татко му од И

Batch 8
Nadal won 88% of the points at the net in the match, winning 76 points in the first serve.
Текст:Оваа алатка е наменета за сите корисници кои сакаат да ги подобрат своите вештини во пишувањето.
Одговор (Енглески): This tool is intended for all users who want to improve their writing skills.
Текст:Оваа алатка е наменета за сите корисници кои сакаат да ги подобрат своите вештини во пишувањето.

Batch 8
After the race, the King of the Earth said: "I am simply very excited to be back in the last rounds of the most important events. I am here to try to win."
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Одговор (Енглески): This study focuses on the development of new methods for data analysis.
Текст:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економ

Batch 8
"The Panama Papers" is a comprehensive term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were leaked to the press in the spring of 2016.
Текст:Во 2014 година, во рамките на проектот "Европски истражувачки центар за истражувачко новинарство" (European Journalism Centre) беше објавен повик за пријавување на новинари од целиот свет кои би сакале да учествуваат на обука за истражувачко новинар

Batch 16
According to the documents, fourteen banks helped wealthy clients hide billions of dollars in order to avoid taxes and other laws.
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Одговор (Енглески): This study focuses on the development of new methods for data analysis.
Текст:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At

Batch 16
The British newspaper "The Guardian" reported that "Deutsche Bank" controlled approximately one-third of the 1,200 provisional companies used to achieve that.
Текст:Повеќе од 100.000 луѓе се пријавија за вакцинација против коронавирусот во Велика Британија, откако владата објави дека ќе започне со вакцинација на 8 јануари.
Одговор (Енглески): More than 100,000 people have signed up to receive the coronavirus vaccine in the United Kingdom

Batch 16
This led to protests being organized around the world, a certain number of criminal prosecutions, and the Prime Ministers of Iceland and Pakistan resigned.
Пример 1
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Пример 2
Македон

Batch 16
Born in Hong Kong, Ma studied at the University of New York and at the Law School at Harvard, and had a U.S. permanent "green card".
Текст:Во 1999 година, тој беше назначен за заменик-генерален секретар на Обединетите нации, а во 2001 година беше назначен за генерален секретар на Обединетите нации.
Одговор (Енглески): In 1999, he was appointed as the United Nations' Deputy Secretary-General, and in 2001, he was

Batch 16
Xi implied during the election that Ma could flee the country in the event of a crisis.
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Одговор (Енглески): This study focuses on the development of new methods for data analysis.
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Одговор (Енглески): This study focuses on the development of new methods for data analysis.
Текст:Оваа студија

Batch 16
Hsieh also claimed that the photogenic Maya was more of a style than a substance.
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Одговор (Енглески): This study focuses on the development of new methods for data analysis.
Текст:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'

Batch 16
Despite these accusations, Ma easily won with a platform that advocates closer ties with continental China.
Текст:Оваа алатка е наменета за сите кои сакаат да научат да свират на пијано.
Одговор (Енглески): This tool is intended for anyone who wants to learn to play the piano.
Текст:Оваа алатка е наменета за сите кои сакаат да научат да свират на пијано.
Одговор (Енглески): This tool is intended for anyone who wants to learn to play the

Batch 16
Today's player of the day is Alex Ovechkin of the Washington Capitals.
Текст:Денес, играч на денот е Алекс Овечкин од тимот на Вашингтон Капиталс.
Одговор (Енглески): Today's player of the day is Alex Ovechkin of the Washington Capitals.
Текст:Денес, играч на денот е Алекс Овечкин од тимот на Вашингтон Капиталс.
Одговор (Енглески): Today's player of the day is Alex Ovechkin

Batch 24
There were 2 goals and 2 assists in the 5-3 win of Washington over Atlanta Thrashers.
Текст:Оваа година, ќе се одржи 10-та по ред конференција за економија и бизнис во Скопје.
Одговор (Енглески): This year, the 10th annual conference on economics and business will be held in Skopje.
Текст:Оваа година, ќе се одржи 10-та по ред конференција за економија и бизнис во

Batch 24
Ovechkin's first assist of the night was for the game-winning goal by starter Nicklas Backstrom.
Текст:Оваа година, 100.000 луѓе се пријавија за да учествуваат на овој настан.
Одговор (Енглески): This year, 100,000 people have signed up to participate in this event.
Текст:Оваа година, 100.000 луѓе се пријавија за да учествуваат на овој настан.

Batch 24
His second goal that night was his 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96, when that record was set by Jaromir Jagr and Mario Lemieux.
Пример 6
Македонски: Во 1990-тите години, во некои земји, како што е Јапонија, се појавија нови видови на автомобили, кои се движат на електрична енергија.
Одговор (Енглески): In the 1

Batch 24
Batten was ranked 190th on the 2008 list of the 400 richest Americans with a fortune estimated at $2.3 billion.
Текст:Во 1999 година, Џејмс Камерон го сними филмот "Аватар" кој беше еден од најскапите филмови на сите времиња.
Одговор (Енглески): In 1999, James Cameron directed the film Avatar, which was one of the most expensive films of all time.
Текст:Во

Batch 24
He graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished himself as an important donor to the institution.
Текст:Постојат многу начини да се изгради мост помеѓу двете страни на реката.
Одговор (Енглески): There are many ways to build a bridge between the two sides of the river.
Текст:Постојат многу начини да се изгради мост помеѓу двете страни на реката.
Одговор (Енглески): There are many ways to

Batch 24
The Iraqi prison "Abu Ghraib" was set on fire during a riot.
Пример 1
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Пример 2
Македонски: Еден спортски натпревар

Batch 24
The prison became infamous after allegations of abuse of prisoners were discovered after it was taken over by the U.S. military.
Текст:Оваа алатка е наменета за да им помогне на корисниците да ги подобрат своите вештини за пишување.
Одговор (Енглески): This tool is intended to help users improve their writing skills.
Текст:Оваа алатка е наменета за да им помогне на корисниците да ги подобрат своите вештини за пишување.
Одговор (Енглески): This

Batch 24
The race was red-flagged after a collision between the Williams of Mark Webber and the McLaren of Lewis Hamilton, which occurred after a pit stop for Fernando Alonso's McLaren.
Текст:Постојат многу теории за потеклото на името на оваа птица.
Одговор (Енглески): There are many theories about the origin of the name of this bird.
Текст:Оваа птица е позната по тоа што е многу нежна и нежна кон своите јајца.
Одговор (Енглески): This bird is known

Batch 32
While the cars in front of Alonso went to fill up at the pit stop, he took the lead to come in for the win.
Пример 1
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Пример 2
Македон

Batch 32
Pike Younger was released after the Hungarian Grand Prix in 2009.
Текст:Повеќе од 100.000 луѓе се собраа на улиците на Лондон за да го прослават крајот на Втората светска војна.
Одговор (Енглески): More than 100,000 people gathered on the streets of London to celebrate the end of World War II.
Текст:Повеќе од 100.000 луѓе се собраа на улиците на Лондон за да

Batch 32
At exactly 8:46 am, there was a traffic jam throughout the city, which marked the exact moment when the first plane hit its target.
Пример 1
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Пример 2

Batch 32
Two beams of light were set to show night towards the sky.
Текст:Оваа алатка е наменета за да им помогне на луѓето да ги подобрат своите вештини за пишување.
Одговор (Енглески): This tool is intended to help people improve their writing skills.
Текст:Оваа алатка е наменета за да им помогне на луѓето да ги подобрат своите вештини за пишување.
Одговор (Енглески): This tool is intended to help people improve their writing skills.

Batch 32
Construction is underway for five new skyscrapers on the site, with a transportation center and memorial park in the middle.
Пример 1
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Пример 2
Македонски: Еден спорт

Batch 32
PBS series has more than two dozen Emmy awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.
Текст:Оваа книга е напишана од страна на еден од најпознатите писатели на сите времиња, Шекспир.
Одговор (Енглески): This book was written by one of the most famous writers of all time, Shakespeare.
Текст:Оваа книга е напишана од страна на еден од најпознатите писатели на сите времиња, Шекспир.
Одговор (Енглески

Batch 32
Each episode of the show focused on a topic from a certain book, and then that topic was researched through multiple stories.
Пример 1
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Пример 2
Македонски: Е

Batch 32
Also, each show will provide recommendations for books that every child should look for when they go to the library.
Пример 1
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Одговор (Енглески): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Пример 2
Македонски: Еден спорт

Batch 40
John Grant, from WNED Buffalo ("Reading Rainbow's Home Station"), said: "Reading Rainbow's taught children why they should read... a love of reading  —  [the series] encouraged children to pick up a book and read."
Пример 6
Македонски: Во 1990-тите, многу луѓе се преселија од руралните области во градовите.
Одговор (Енглески): In the 1990s, many people moved from rural areas to cities.
Пример 7
Македонски:

Batch 40
Some people, including John Grant, believe that the church-financier and the change in the philosophy of educational programming contributed to the cancellation of the show.
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Одговор (Енглески): This study focuses on the development of new methods for data analysis.
Текст:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Од

Batch 40
The storm, located 645 miles (1040 km) west of the Green Reef Islands, is likely to dissipate before posing a threat to any land area, according to meteorologists.
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Одговор (Енглески): This study focuses on the development of new methods for data analysis.
Текст:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори око

Batch 40
At the moment, Fred is covering winds of 105 mph (165 km/h) and moving north-northwest.
Текст:Оваа алатка е наменета за да им помогне на корисниците да ги подобрат своите вештини за пишување.
Одговор (Енглески): This tool is intended to help users improve their writing skills.
Текст:Оваа алатка е наменета за да им помогне на корисниците да ги подобрат своите вештини за пишување.
Одговор (Енг

Batch 40
Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic from the invention of satellite recordings, but it is only the third major hurricane recorded east of 35° W.
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Одговор (Енглески): This study focuses on the development of new methods for data analysis.
Текст:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу

Batch 40
On September 24, 1759, Arthur Guinness signed a 9,000-year lease for the St. James Gate Brewery in Dublin, Ireland.

In [ ]:
predictions_new = [first_sentence(text) for text in predictions_eng]
predictions_new

["On Monday, scientists from the medical faculty at Stanford University announced that they have invented a new tool for diagnosis that sorts cells by type: it's a small printing chip that can be produced with standard ink-jet printers, for a price of about one U.S. cent.",
 'Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with low living standards, where the survival rate from diseases such as breast cancer can be twice as low as in richer countries.',
 'JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, causing the airport to be closed for commercial flights.',
 'It has been determined that the pilot was Dylokrit Patavi, the leader of the squadron.',
 'Local media report on a fire truck that overturned while firefighters responded to a call.',
 '28-year-old Vidal from Sevilla has joined the Barcelona team.',
 'After moving to the Catalan capital, Vidal played 49 games for the club.',
 'The protest began around 11:00 am local time (UTC+1) in Whitehall, across from the entrance guarded by police at Downing Street, the official residence of the Prime Minister.',
 'Immediately after 11:00 am, demonstrators blocked traffic heading north in Whitehall.',
 'At 11:20, the police asked the protesters to move to the sidewalk, citing that they should balance the right to protest with the traffic congestion.',
 'Around 11:29 am, the protest moved to White Hall, near Trafalgar Square, near Strand, passing by Aldwych and through Kingway to Holborn, where the Conservative Party held their Spring Forum at the Grand Connaught Rooms hotel.',
 "Nadal's personal record against the Canadian is 7 - 2.",
 'He recently lost to Raonic at the Brisbane Open.',
 'Nadal won 88% of the points at the net in the match, winning 76 points in the first serve.',
 'After the race, the King of the Earth said: "I am simply very excited to be back in the last rounds of the most important events.',
 '"The Panama Papers" is a comprehensive term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were leaked to the press in the spring of 2016.',
 'According to the documents, fourteen banks helped wealthy clients hide billions of dollars in order to avoid taxes and other laws.',
 'The British newspaper "The Guardian" reported that "Deutsche Bank" controlled approximately one-third of the 1,200 provisional companies used to achieve that.',
 'This led to protests being organized around the world, a certain number of criminal prosecutions, and the Prime Ministers of Iceland and Pakistan resigned.',
 'Born in Hong Kong, Ma studied at the University of New York and at the Law School at Harvard, and had a U.S. permanent "green card".',
 'Xi implied during the election that Ma could flee the country in the event of a crisis.',
 'Hsieh also claimed that the photogenic Maya was more of a style than a substance.',
 'Despite these accusations, Ma easily won with a platform that advocates closer ties with continental China.',
 "Today's player of the day is Alex Ovechkin of the Washington Capitals.",
 'There were 2 goals and 2 assists in the 5-3 win of Washington over Atlanta Thrashers.',
 "Ovechkin's first assist of the night was for the game-winning goal by starter Nicklas Backstrom.",
 'His second goal that night was his 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96, when that record was set by Jaromir Jagr and Mario Lemieux.',
 'Batten was ranked 190th on the 2008 list of the 400 richest Americans with a fortune estimated at $2.3 billion.',
 'He graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished himself as an important donor to the institution.',
 'The Iraqi prison "Abu Ghraib" was set on fire during a riot.',
 'The prison became infamous after allegations of abuse of prisoners were discovered after it was taken over by the U.S. military.',
 "The race was red-flagged after a collision between the Williams of Mark Webber and the McLaren of Lewis Hamilton, which occurred after a pit stop for Fernando Alonso's McLaren.",
 'While the cars in front of Alonso went to fill up at the pit stop, he took the lead to come in for the win.',
 'Pike Younger was released after the Hungarian Grand Prix in 2009.',
 'At exactly 8:46 am, there was a traffic jam throughout the city, which marked the exact moment when the first plane hit its target.',
 'Two beams of light were set to show night towards the sky.',
 'Construction is underway for five new skyscrapers on the site, with a transportation center and memorial park in the middle.',
 "PBS series has more than two dozen Emmy awards and is shorter than Sesame Street and Mr. Rogers' Neighborhood.",
 'Each episode of the show focused on a topic from a certain book, and then that topic was researched through multiple stories.',
 'Also, each show will provide recommendations for books that every child should look for when they go to the library.',
 'John Grant, from WNED Buffalo ("Reading Rainbow\'s Home Station"), said: "Reading Rainbow\'s taught children why they should read... a love of reading  —  [the series] encouraged children to pick up a book and read."',
 'Some people, including John Grant, believe that the church-financier and the change in the philosophy of educational programming contributed to the cancellation of the show.',
 'The storm, located 645 miles (1040 km) west of the Green Reef Islands, is likely to dissipate before posing a threat to any land area, according to meteorologists.',
 'At the moment, Fred is covering winds of 105 mph (165 km/h) and moving north-northwest.',
 'Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic from the invention of satellite recordings, but it is only the third major hurricane recorded east of 35° W.\nТекст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.',
 'On September 24, 1759, Arthur Guinness signed a 9,000-year lease for the St. James Gate Brewery in Dublin, Ireland.',
 '250 years later, Guinness grew into a global business with an annual turnover of 10 billion euros (14.7 billion dollars).',
 'Jonny Reid, a co-driver from the A1GP team from New Zealand, today created a historical event by passing through the 48-year-old Auckland Harbour Bridge in New Zealand, legally.',
 'Mr. Reid managed to drive the New Zealand A1GP car, the Black Beauty, at speeds over 160 km/h across the bridge seven times.',
 'New Zealand police faced a problem when using radar to determine speeds, because of the height of the Black Beauty, and the only time the police caught Mr. Reed was when he slowed down to 160 km/h.',
 'In the last 3 months, over 80 detainees were released from the detention center without being formally charged.',
 'In April this year, the order for a temporary restriction was issued by Judge Glenn against the institution for the accelerated release of those detained more than 24 hours after arrest, who have not received a hearing by a court commissioner.',
 'The Commissioner determines bail, if allowed, and formalizes the charges filed by the officer who made the arrests.',
 'At this hearing, the date for the right of the defendant to a speedy trial will be determined.',
 "Peter Costello, Australia's Minister for Finance and the man with the greatest potential to replace John Howard as leader of the Liberal Party, has expressed his support for a nuclear energy industry in Australia.",
 'G. Costello said that when nuclear reactors become economically viable, Australia will begin to use them.',
 '"If it\'s commercially viable, we should have it.',
 'According to ANSA, "the police were concerned about several high-profile assassinations that they feared could spark a war for succession in full swing."',
 "The police announced that Lo Piccolo had control because he was Provenzano's right-hand man in Palermo, and his greater experience had won him respect from the older generation of bosses because they followed Provenzano's policy of staying as hidden as possible while they strengthened their network of authority.",
 'These bosses were subdued by Provenzano when he put an end to the war sparked by Rina against the state that took the lives of the "Mafia Crusaders," Giovanni Falcone and Paolo Borsellino in 1992.',
 "Apple's CEO, Steve Jobs, unveiled the device by standing on stage and pulling the iPhone out of his jeans pocket.",
 'During his two-hour speech, he stated that "Apple will re-invent the phone, Today we will create history."',
 'Brazil is the largest Roman Catholic country on Earth and the Roman Catholic Church is constantly opposed to the legalization of same-sex marriage in the country.',
 'The Brazilian State Congress has been debating the legalization of civil unions for ten years now; and despite this, such civil marriages are currently only legal in Rio Grande do Sul.',
 'The original bill was drafted by Marta Suplicy, the former mayor of Sao Paulo.',
 'Protestants hope to collect 1.2 million signatures for the petition that will be presented to the National Congress in November.',
 'After it became clear that many families were seeking legal assistance to fight evictions, a meeting was held at the Community Law Center in East Bay on March 20th, for victims of housing fraud.',
 'When the residents started to share what had happened to them, the majority of the families involved suddenly realized that Caroline Wilson from OHA had stolen their security deposits and had fled the city.',
 'Residents of Lockwood Gardens believe that there may be 40 families or more facing eviction, because they have learned that the OHA is investigating other public housing properties in Oakland that may be involved in the housing scam.',
 'The band has cancelled the performance that was scheduled to take place at the Maui Military Memorial Stadium, where 9,000 people were expected to attend, and apologized to the fans.',
 "The band's management company, HK Management Inc., did not give an official statement on the reasons for the cancellation on September 20th, but the next day they stated that it was a logistical problem.",
 'The famous Greek lawyers, Sakkis Kehayioglu and George Nikolaopoulos, have been sentenced to prison in the Koridallos prison in Athens, after being found guilty of bribery and corruption.',
 'As a result, a great scandal erupted in the Greek legal community with the revelation of illegal acts committed by judges, lawyers, attorneys, and prosecutors in the past years.',
 'A few weeks ago, after the news was published by journalist Makis Triantafilopoulos in his popular television show "Zoungla" on Alpha TV, the MP and lawyer Petros Mantouvalos resigned because members of his cabinet were involved in bribery and corruption.',
 'In addition, the top judge Evangelos Kalousis is in custody for corruption and improper behavior.',
 'Roberts unhesitatingly refused to discuss his belief about when life begins, which is an important question when considering the ethics of abortion, saying that it would be unethical to comment on the specific details of potential cases.',
 'However, he confirmed his previous statement that Roe v. Wade is "the standard," emphasizing the importance of consistent Supreme Court decisions.',
 "He also confirmed that he believes in the non-negotiable right to privacy, which was the basis of Roe's decision.",
 'Maruchidore finished at the top of the scale, with six points ahead of Nussa, who is second.',
 'The two teams met in the big semi-final, where Nussa came to victory with 11 points difference.',
 'Then Maruchidor defeated Kabultur in the preliminary final.',
 'Hesperonychus elizabethae is a species of the Dromaeosauridae family that is closely related to the velociraptor.',
 'It is believed that this warm-blooded bird-of-prey with feathers all over its body walked upright on two legs, with claws like those of a velociraptor.',
 'His second claw was larger, which gave it the name Hesperonichus, meaning "western claw".',
 'Extreme weather conditions, including ice that breaks, make rescue efforts difficult.',
 'Pittman hinted that conditions would not improve until next week.',
 'The amount and thickness of the ice, according to Pittman, is the worst in the past 15 years for seal hunters.',
 'Today, in the town of Red Lake, after the funerals of Jeff Weise and three of the nine victims, news spread that another student was arrested in connection with the shooting at the school on March 21.',
 'The authorities have not officially stated much, except that they confirmed the arrest today.',
 'Still, an insider with knowledge of the investigation for "Minneapolis Star-Tribune" said it was Louis Jourden, the 16-year-old son of the tribal president of Red Lake, Floyd Jourden.',
 'At this time, it is not known which charges will be brought against the minor, nor what led the authorities to the minor, but the case against the minor has been brought before a federal court.',
 'Also, Lodin said that officials decided to cancel the second round of elections to spare the Afghans from expenses and to avoid a security risk from another vote.',
 'Diplomats said they found enough ambiguities in the Afghan Constitution to determine that a second round of elections was unnecessary.',
 'This is contradictory to previous statements, which said that the cancellation of the second round would be unconstitutional.',
 'The plane was heading for Irkutsk and was being flown by internal troops.',
 'An investigation was initiated to determine.',
 'II-76 was the largest component of the Russian and Soviet army since the 1970s, which last month experienced a serious accident in Russia.',
 'On October 7, the engine separated during takeoff, without injuries.',
 '800 miles of the Trans-Alaska Pipeline system were closed after thousands of barrels of crude oil flowed south of Fairbanks, Alaska.',
 'After a routine test of the fire management system, a power outage occurred that caused the pressure valves to open and crude oil to spill near pump station 9 at Fort Grilly.']

In [ ]:
references = [[ref] for ref in text_eng]
references[:10]

[['On Monday, scientists from the Stanford University School of Medicine announced the invention of a new diagnostic tool that can sort cells by type: a tiny printable chip that can be manufactured using standard inkjet printers for possibly about one U.S. cent each.'],
 ['Lead researchers say this may bring early detection of cancer, tuberculosis, HIV and malaria to patients in low-income countries, where the survival rates for illnesses such as breast cancer can be half those of richer countries.'],
 ['The JAS 39C Gripen crashed onto a runway at around 9:30 am local time (0230 UTC) and exploded, closing the airport to commercial flights.'],
 ['The pilot was identified as Squadron Leader Dilokrit Pattavee.'],
 ['Local media reports an airport fire vehicle rolled over while responding.'],
 ['28-year-old Vidal had joined Barça three seasons ago, from Sevilla.'],
 ['Since moving to the Catalan-capital, Vidal had played 49 games for the club.'],
 ["The protest started around 11:00 local time (UTC+1) on Whitehall opposite the police-guarded entrance to Downing Street, the Prime Minister's official residence."],
 ['Just after 11:00, protesters blocked traffic on the northbound carriage in Whitehall.'],
 ['At 11:20, the police asked the protesters to move back on to the pavement, stating that they needed to balance the right to protest with the traffic building up.']]

In [ ]:
bleu.compute(predictions=predictions_new, references=references)

{'bleu': 0.3546464002042834,
 'precisions': [0.6568814334731223,
  0.41973840665873957,
  0.28600907965332234,
  0.20060266896254844],
 'brevity_penalty': 1.0,
 'length_ratio': 1.0475239616613419,
 'translation_length': 2623,
 'reference_length': 2504}

In [ ]:
chrf_score = sacrebleu.corpus_chrf(predictions_new, references)
print(f"chrF: {chrf_score.score:.2f}")

chrF: 59.45

## Few-Shot Cross-lingual prompt (MKD->ENG) in bulgarian language

In [ ]:
instruction = f"""Преведи следния текст от **Македонски** на **Английски** език.
Само отпечатай превода на английски. Не добавяй никакви обяснения.

Пример 1
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Пример 2
Македонски: Еден спортски натпревар трае 90 минути, односно две полувремиња по 45 минути со одмор помеѓу нив во траење од 15 минути. Ако има подолги прекини во играта, таа се продолжува така што се надополнува изгубеното време.
Отговор (Английски): A sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.

Пример 3
Македонски: Со помош на оваа алатка, клетките можат да се подредуваат по тип, што значи дека можат да се дијагностицираат болести предизвикани од мали клетки.
Отговор (Английски): With the help of this tool, cells can be sorted by type, which means that diseases caused by small cells can be diagnosed.

Пример 4
Македонски: Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Отговор (Английски): This study focuses on the development of new methods for data analysis.

Пример 5
Македонски: Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.
Отговор (Английски): In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
"""

In [ ]:
predictions_eng = batch_translate(text_mkd,instruction,max_new_tokens=128,lang_code="bug",language="Английски")

Batch 0
On Monday, scientists from the medical faculty at Stanford University announced that they have invented a new tool for diagnosis that sorts cells by type: it's a small printing chip that can be produced with standard ink-jet printers, for a price of about one US cent.
Пример 6
Македонски: Во 1999 година, во рамките на проектот "Европа 2000", беше објавен извештај за состојбата на човековите права во Македонија.
Отговор (Английски): In 1999,

Batch 0
Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with low living standards, where the survival rate from diseases such as breast cancer can be twice as low as in richer countries.
Пример 6
Македонски: Во 1990 година, во Македонија е донесен Закон за заштита на природата.
Отговор (Английски): In 1990, a law for the protection of nature was adopted in Macedonia.
Пример 7
Македонски: Во 199

Batch 0
JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, causing the airport to be closed for commercial flights.
Пример 6
Македонски: Во 1990 година, војската на САД го презеде командното раководство над силите на НАТО во Европа.
Отговор (Английски): In 1990, the United States Army took command of NATO forces in Europe.
Пример 7
Македонски: Во 1990

Batch 0
It has been determined that the pilot was Dylocritus Patavius, the leader of the squadron.
Текст:Во 1990 година, војската на САД го презеде Ирак.
Отговор (Английски): In 1990, the United States Army took over Iraq.
Текст:Во 1990 година, војската на САД го презеде Ирак.
Отговор (Английски): In 1990, the United States Army took over Iraq.
Текст:Во 19

Batch 0
Local media report on a fire truck that overturned while firefighters responded to a call.
Текст:Пожарникарите одговараат на повик за пожар во близина на аеродромот.
Отговор (Английски): Firefighters respond to a call for a fire near the airport.
Текст:Пожарникарите одговараат на повик за пожар во близина на аеродромот.
Отговор (Английски): Firefighters respond to a call for a fire near the airport.
Текст:Пожарникарите од

Batch 0
28-year-old Vidal from Sevilla has joined the Barcelona team.
Текст:Во 1999 година, во Њујорк, беше отворен првиот ресторан за брза храна на светот.
Отговор (Английски): In 1999, in New York, the world's first fast food restaurant was opened.
Текст:Во 1999 година, во Њујорк, беше отворен првиот ресторан за брза храна на светот.
Отговор (Англий

Batch 0
After moving to the Catalan capital, Vidal played 49 games for the club.
Текст:Во 1999 година, тој беше избран за најдобар млад фудбалер во Шпанија.
Отговор (Английски): In 1999, he was voted the best young player in Spain.
Текст:Во 2000 година, тој беше избран за најдобар млад фудбалер во Шпанија.
Отговор (Английски): In 2000, he was voted the best young player in Spain

Batch 0
The protest began around 11:00 am local time (UTC+1) in Whitehall, across from the entrance guarded by police at Downing Street, the official residence of the Prime Minister.
Пример 1
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to

Batch 8
Immediately after 11:00 am, demonstrators blocked traffic heading north in Whitehall.
Текст:Во 1990 година, војската на САД го изврши првиот напад со хемиско оружје во историјата на човештвото.
Отговор (Английски): In 1990, the United States military conducted the first chemical attack in history.
Текст:Во 1990 година, војската на САД го изврши првиот напад со хемиско оружје во историјата

Batch 8
At 11:20, the police asked the protesters to move to the sidewalk, citing that they should balance the right to protest with the traffic congestion.
Пример 1
Македонски: Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Отговор (Английски): At 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Пример

Batch 8
Around 11:29 am, the protest moved to White Hall, near Trafalgar Square, near Strand, passing by Aldwych and through Kingway to Holborn, where the Conservative Party held their Spring Forum at the Grand Connaught Rooms hotel.
Пример 6
Македонски: Во 1990 година, во рамките на проектот "Европскиот модел на образованието", се одржал семинар во Скопје, Македонија.
Отговор (Английски): In 1990, within the framework of the "European Model

Batch 8
Nadal's personal record against the Canadian is 7 - 2.
Пример 6
Македонски: Во 1990 година, во Њујорк, беше отворен првиот ресторан за брза храна "Мекдоналдс".
Отговор (Английски): In 1990, in New York, the first McDonald's fast food restaurant was opened.
Пример 7
Македонски: Во 1990 година, во Њујорк, беше отворен првиот ресторан

Batch 8
He recently lost to Raonic at the Brisbane Open.
Текст:Неговата мајка е од Шведска, а татко му од Полска.
Отговор (Английски): His mother is from Sweden, and his father is from Poland.
Текст:Неговата мајка е од Шведска, а татко му од Полска.
Отговор (Английски): His mother is from Sweden, and his father is from Poland.
Текст:Неговата мајка е од Шведска, а татко му од Пол

Batch 8
Nadal won 88% of the points at the net in the match, winning 76 points in the first serve.
Текст:Оваа алатка е наменета за да им помогне на корисниците да ги подобрат своите вештини за пишување.
Отговор (Английски): This tool is intended to help users improve their writing skills.
Текст:Оваа алатка е наменета за да им помогне на корисниците да ги подобрат своите вештини за пишување.
Отговор (Английски):

Batch 8
After the race, the King of the Earth said: "I am simply very excited to be back in the last rounds of the most important events. I am here to try to win."
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Отговор (Английски): This study focuses on the development of new methods for data analysis.
Текст:Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на

Batch 8
"The Panama Papers" is a comprehensive term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were leaked to the press in the spring of 2016.
Текст:Во 2015 година, 100.000 луѓе во светот починаа од ебола.
Отговор (Английски): In 2015, 100,000 people in the world died of Ebola.
Текст:Во 2015 година, 100.000 луѓ

Batch 16
According to the documents, fourteen banks helped wealthy clients hide billions of dollars in order to avoid taxes and other laws.
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Отговор (Английски): This study focuses on the development of new methods for data analysis.
Текст:Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.
Отговор (Английски): In the

Batch 16
The British newspaper "The Guardian" reported that "Deutsche Bank" controlled approximately one-third of the 1,200 provisional companies used to achieve that.
Текст:Во 1990 година, во САД се појавија првите случаи на ХИВ инфекција.
Отговор (Английски): In 1990, the first cases of HIV infection were reported in the United States.
Текст:Во 1990 година, во САД се појавија првите случаи на ХИВ инфекција.
Отговор (Анг

Batch 16
This led to protests being organized around the world, a certain number of criminal prosecutions, and the Prime Ministers of Iceland and Pakistan resigned.
Пример 6
Македонски: Во 1990 година, во рамките на проектот "Европа 2000", беше формирана Европската комисија за образование, култура и млади.
Отговор (Английски): In 1990, within the framework of the "Europe 2000" project, the European Commission for Education, Culture and Youth was formed.
Пример

Batch 16
Born in Hong Kong, Ma studied at the University of New York and at the Law School at Harvard, and had a U.S. permanent "green card".
Текст:Оваа книга е напишана од страна на еден од најпознатите светски научници, кој е познат по своите истражувања во областа на економијата.
Отговор (Английски): This book is written by one of the world's most famous scientists, who is known for his research in the field of economics.
Текст:Оваа книга е

Batch 16
Xi implied during the elections that Ma could flee the country in the event of a crisis.
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Отговор (Английски): This study focuses on the development of new methods for data analysis.
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Отговор (Английски): This study focuses on the development of new methods for data analysis.
Текст:Оваа студија

Batch 16
Hsieh also claimed that the photogenic Maya was more of a style than a substance.
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Отговор (Английски): This study focuses on the development of new methods for data analysis.
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Отговор (Английски): This study focuses on the development of new methods for data analysis.
Текст:Оваа студија

Batch 16
Despite these accusations, Ma easily won with a platform that advocates closer ties with continental China.
Пример 6
Македонски: Во 1990 година, во САД се појавија првите случаи на ХИВ инфекција.
Отговор (Английски): In 1990, the first cases of HIV infection appeared in the United States.
Пример 7
Македонски: Во 1990 година, во САД се појавија првите случаи на ХИВ инфекција.
Отговор (Английски

Batch 16
Today's player of the day is Alex Ovechkin of the Washington Capitals.
Текст:Денес, играч на денот е Алекс Овечкин од тимот на Вашингтон Капиталс.
Отговор (Английски): Today's player of the day is Alex Ovechkin of the Washington Capitals.
Текст:Денес, играч на денот е Алекс Овечкин од тимот на Вашингтон Капиталс.
Отговор (Английски): Today's player of the day is Alex Ovechkin

Batch 24
There were 2 goals and 2 assists in the 5-3 win of Washington against Atlanta Thrashers.
Текст:Оваа година, ќе се одржи 10-та по ред конференција за економија и бизнис во Скопје.
Отговор (Английски): This year, the 10th annual conference on economics and business will be held in Skopje.
Текст:Оваа година, ќе се одржи 10-та по ред конференција за економија и бизнис во

Batch 24
Ovechkin's first assist of the night was for the game-winning goal by starter Nicklas Backstrom.
Текст:Оваа година, 1000-та година од раѓањето на Исус Христос, беше прогласена за година на Исус Христос.
Отговор (Английски): In this year, the 1000th anniversary of the birth of Jesus Christ, was declared the Year of Jesus Christ.
Текст:Оваа година, 1000-та година од раѓањето на Исус Христос,

Batch 24
His second goal that night was his 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96, when that record was set by Jaromir Jagr and Mario Lemieux.
Текст:Оваа година, ние ќе ги објавиме нашите резултати од истражувањето на пазарот за 2010 година.
Отговор (Английски): This year, we will release our 2010 market research results.
Текст:Ова

Batch 24
Batten was ranked 190th on the 2008 list of the 400 richest Americans with a fortune estimated at $2.3 billion.
Текст:Во 1999 година, Џејмс Батен беше избран за претседател на компанијата "Спејс Икс" (SpaceX).
Отговор (Английски): In 1999, James Batten was elected President of the company SpaceX.
Текст:Во 2008 година, Батен беше рангиран како 190

Batch 24
He graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished himself as an important donor to the institution.
Текст:Постојат многу начини да се изгради мост помеѓу двете страни на реката.
Отговор (Английски): There are many ways to build a bridge between the two sides of the river.
Текст:Постојат многу начини да се изгради мост помеѓу двете страни на реката.
Отговор (Английски): There are many ways to

Batch 24
The Iraqi prison "Abu Ghraib" was set on fire during a riot.
Пример 7
Македонски: Во 1990 година, во САД се појавија првите случаи на ХИВ инфекција.
Отговор (Английски): In 1990, the first cases of HIV infection were reported in the United States.
Пример 8
Македонски: Во 1990 година, во САД се појавија првите случаи на ХИВ инфекција.
Отговор (Английски

Batch 24
The prison became infamous after allegations of abuse of prisoners were discovered after it was taken over by the U.S. military.
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Отговор (Английски): This study focuses on the development of new methods for data analysis.
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Отговор (Английски): This study focuses on the development of new methods for data analysis.
Текст

Batch 24
The text is about the 2008 Singapore Grand Prix, where the Red Bull Racing car of Mark Webber collided with the Williams-Toyota car of Mark Webber, which was driven by Mark Webber, after the car of Fernando Alonso was pulled into the pit lane for a safety car.
Текст:На 20-ти јуни 2008, во 11:00 часот, во Лондон, Велика Британија, беше одржана прес-конференција за да се промовира новата верзија на Windows.
Отговор (Английски):

Batch 32
While the cars in front of Alonso went to fill up their fuel tanks after the safety car, he took the lead to come to victory.
Пример 6
Македонски: Во 1990 година, војската на САД го изврши првиот напад со хеликоптери на воените позиции на Ирак.
Отговор (Английски): In 1990, the United States military conducted the first helicopter attack on Iraqi military positions.
Пример 7
Македонски: Во 1990 година, вој

Batch 32
Pike Younger was fired after the Hungarian Grand Prix in 2009.
Текст:Повеќе од 1000 луѓе се собраа на протестот против полициската бруталност во Лондон.
Отговор (Английски): More than 1000 people gathered at the protest against police brutality in London.
Текст:Повеќе од 1000 луѓе се собраа на протестот против полициската бруталност во Лондон.
Отговор (Английски): More than 100

Batch 32
At exactly 8:46 am, there was a traffic jam throughout the city, which marked the exact moment when the first plane hit its target.
Пример 6
Македонски: Во 1990 година, во Македонија се одржаа првите парламентарни избори.
Отговор (Английски): In 1990, the first parliamentary elections were held in Macedonia.
Пример 7
Македонски: Во 1990 година, во Македонија се одржаа првите парламентарни избори.
Отговор (

Batch 32
Two beams of light were set to show night towards the sky.
Текст:Оваа книга е напишана од страна на еден од најпознатите писатели на сите времиња.
Отговор (Английски): This book was written by one of the most famous writers of all time.
Текст:Оваа книга е напишана од страна на еден од најпознатите писатели на сите времиња.
Отговор (Английски): This book was written by one of the most famous writers of all time.
Текст:О

Batch 32
Construction is underway for five new skyscrapers on the site, with a transportation center and memorial park in the middle.
Пример 7
Македонски: Во 1990 година, војската на САД го презеде командното раководство над силите на НАТО во Европа.
Отговор (Английски): In 1990, the United States Army took command of NATO forces in Europe.
Пример 8
Македонски: Во 1990 година, војската на САД го презеде командното раководство над

Batch 32
PBS series has more than two dozen Emmy awards and is shorter to air than Sesame Street and Mr. Rogers' Neighborhood.
Пример 6
Македонски: Оваа книга е напишана од страна на еден од најпознатите писатели на сите времиња.
Отговор (Английски): This book is written by one of the most famous writers of all time.
Пример 7
Македонски: Оваа книга е напишана од страна на еден од најпознатите писатели на сите времиња.
Отговор (

Batch 32
Each episode of the show focused on a topic from a certain book, and then that topic was researched through multiple stories.
Пример 6
Македонски: Во 1990 година, во САД се појавија првите компјутери со графички процесор.
Отговор (Английски): In 1990, the first computers with a graphics processor appeared in the United States.
Пример 7
Македонски: Во 1990 година, во САД се појавија првите компјутери со графички процесор

Batch 32
In addition, each show will provide recommendations for books that every child should look for when they go to the library.
Пример 6
Македонски: Во 1990 година, во САД се појавија првите компјутери со графички процесор.
Отговор (Английски): In 1990, the first computers with a graphics processor appeared in the United States.
Пример 7
Македонски: Во 1990 година, во САД се појавија првите компјутери со графички процесор.

Batch 40
John Grant, from WNED Buffalo ("Reading Rainbow's Home Station"), said: "Reading Rainbow's taught children why they should read... a love of reading  —  [the series] encouraged children to pick up a book and read."
Пример 6
Македонски: Во 1990 година, во САД, 10% од населението имаше пристап до интернет.
Отговор (Английски): In 1990, in the United States, 10% of the population had access to the internet.
Пример 7
Ма

Batch 40
Some people, including John Grant, believe that the church-financier and the change in the philosophy of educational programs contributed to the cancellation of the show.
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Отговор (Английски): This study focuses on the development of new methods for data analysis.
Текст:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
От

Batch 40
The hurricane located 645 miles (1040 km) west of the Green Reef Islands, is likely to dissipate before posing a threat to any land area, say meteorologists.
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Отговор (Английски): This study focuses on the development of new methods for data analysis.
Текст:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу е

Batch 40
At the moment, Fred is covering winds of 105 mph (165 km/h) and moving north-northwest.
Текст:Оваа алатка е наменета за да им помогне на корисниците да ги подобрат своите вештини за пишување.
Отговор (Английски): This tool is intended to help users improve their writing skills.
Текст:Оваа алатка е наменета за да им помогне на корисниците да ги подобрат своите вештини за пишување.
Отговор (Анг

Batch 40
Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic from the invention of satellite recordings, but it is only the third major hurricane recorded east of 35° W.
Текст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
Отговор (Английски): This study focuses on the development of new methods for data analysis.
Текст:Во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу

Batch 40
On September 24, 1759, Arthur Guinness signed a 9,000-year lease for the St. James Gate Brewery in Dublin, Ireland.
Текст:Во 1990-тите, во САД, се појавија многу нови технологии за да се намали потрошувачката на енергија.
Отговор (Английски): In the 1990s, many new technologies emerged in the United States to reduce energy consumption.
Текст:Во 1990-тите, во САД, се

Batch 40
250 years later, Guinness grew into a global business with an annual turnover of 10 billion euros (14.7 billion dollars).
Текст:
Во 1990 година, "Гинис" беше купен од "Ворнер Брос" за 100 милиони долари.
Отговор (Английски): In 1990, Guinness was bought by Warner Bros for $100 million.
Текст:
Во 1995 година, "Гинис" беше купен од "Ворнер Брос" за

Batch 40

In [ ]:
predictions_new = [first_sentence(text) for text in predictions_eng]
predictions_new

["On Monday, scientists from the medical faculty at Stanford University announced that they have invented a new tool for diagnosis that sorts cells by type: it's a small printing chip that can be produced with standard ink-jet printers, for a price of about one US cent.",
 'Leading researchers believe that this could lead to early detection of cancer, tuberculosis, HIV and malaria in patients living in countries with low living standards, where the survival rate from diseases such as breast cancer can be twice as low as in richer countries.',
 'JAS 39C Gripen crashed on the runway around 9:30 am local time (2:30 UTC) and exploded, causing the airport to be closed for commercial flights.',
 'It has been determined that the pilot was Dylocritus Patavius, the leader of the squadron.',
 'Local media report on a fire truck that overturned while firefighters responded to a call.',
 '28-year-old Vidal from Sevilla has joined the Barcelona team.',
 'After moving to the Catalan capital, Vidal played 49 games for the club.',
 'The protest began around 11:00 am local time (UTC+1) in Whitehall, across from the entrance guarded by police at Downing Street, the official residence of the Prime Minister.',
 'Immediately after 11:00 am, demonstrators blocked traffic heading north in Whitehall.',
 'At 11:20, the police asked the protesters to move to the sidewalk, citing that they should balance the right to protest with the traffic congestion.',
 'Around 11:29 am, the protest moved to White Hall, near Trafalgar Square, near Strand, passing by Aldwych and through Kingway to Holborn, where the Conservative Party held their Spring Forum at the Grand Connaught Rooms hotel.',
 "Nadal's personal record against the Canadian is 7 - 2.",
 'He recently lost to Raonic at the Brisbane Open.',
 'Nadal won 88% of the points at the net in the match, winning 76 points in the first serve.',
 'After the race, the King of the Earth said: "I am simply very excited to be back in the last rounds of the most important events.',
 '"The Panama Papers" is a comprehensive term for nearly ten million documents from the Panamanian law firm Mossack Fonseca, which were leaked to the press in the spring of 2016.',
 'According to the documents, fourteen banks helped wealthy clients hide billions of dollars in order to avoid taxes and other laws.',
 'The British newspaper "The Guardian" reported that "Deutsche Bank" controlled approximately one-third of the 1,200 provisional companies used to achieve that.',
 'This led to protests being organized around the world, a certain number of criminal prosecutions, and the Prime Ministers of Iceland and Pakistan resigned.',
 'Born in Hong Kong, Ma studied at the University of New York and at the Law School at Harvard, and had a U.S. permanent "green card".',
 'Xi implied during the elections that Ma could flee the country in the event of a crisis.',
 'Hsieh also claimed that the photogenic Maya was more of a style than a substance.',
 'Despite these accusations, Ma easily won with a platform that advocates closer ties with continental China.',
 "Today's player of the day is Alex Ovechkin of the Washington Capitals.",
 'There were 2 goals and 2 assists in the 5-3 win of Washington against Atlanta Thrashers.',
 "Ovechkin's first assist of the night was for the game-winning goal by starter Nicklas Backstrom.",
 'His second goal that night was his 60th of the season, making him the first player to score 60 or more goals in a season since 1995-96, when that record was set by Jaromir Jagr and Mario Lemieux.',
 'Batten was ranked 190th on the 2008 list of the 400 richest Americans with a fortune estimated at $2.3 billion.',
 'He graduated from the College of Arts and Sciences at the University of Virginia in 1950 and distinguished himself as an important donor to the institution.',
 'The Iraqi prison "Abu Ghraib" was set on fire during a riot.',
 'The prison became infamous after allegations of abuse of prisoners were discovered after it was taken over by the U.S. military.',
 'The text is about the 2008 Singapore Grand Prix, where the Red Bull Racing car of Mark Webber collided with the Williams-Toyota car of Mark Webber, which was driven by Mark Webber, after the car of Fernando Alonso was pulled into the pit lane for a safety car.',
 'While the cars in front of Alonso went to fill up their fuel tanks after the safety car, he took the lead to come to victory.',
 'Pike Younger was fired after the Hungarian Grand Prix in 2009.',
 'At exactly 8:46 am, there was a traffic jam throughout the city, which marked the exact moment when the first plane hit its target.',
 'Two beams of light were set to show night towards the sky.',
 'Construction is underway for five new skyscrapers on the site, with a transportation center and memorial park in the middle.',
 "PBS series has more than two dozen Emmy awards and is shorter to air than Sesame Street and Mr. Rogers' Neighborhood.",
 'Each episode of the show focused on a topic from a certain book, and then that topic was researched through multiple stories.',
 'In addition, each show will provide recommendations for books that every child should look for when they go to the library.',
 'John Grant, from WNED Buffalo ("Reading Rainbow\'s Home Station"), said: "Reading Rainbow\'s taught children why they should read... a love of reading  —  [the series] encouraged children to pick up a book and read."',
 'Some people, including John Grant, believe that the church-financier and the change in the philosophy of educational programs contributed to the cancellation of the show.',
 'The hurricane located 645 miles (1040 km) west of the Green Reef Islands, is likely to dissipate before posing a threat to any land area, say meteorologists.',
 'At the moment, Fred is covering winds of 105 mph (165 km/h) and moving north-northwest.',
 'Fred is the strongest tropical cyclone ever recorded so far south and east in the Atlantic from the invention of satellite recordings, but it is only the third major hurricane recorded east of 35° W.\nТекст:Оваа студија се фокусира на развојот на нови методи за анализа на податоци.',
 'On September 24, 1759, Arthur Guinness signed a 9,000-year lease for the St. James Gate Brewery in Dublin, Ireland.',
 '250 years later, Guinness grew into a global business with an annual turnover of 10 billion euros (14.7 billion dollars).',
 'Jonny Reid, co-driver of the A1GP team from New Zealand, today created a historical event by legally passing through the 48-year-old Auckland Harbour Bridge in New Zealand, the fastest time ever.',
 'Mr. Reid managed to drive the New Zealand A1GP car, Black Beauty, at speeds over 160 km/h across the bridge seven times.',
 'New Zealand police faced a problem when using radar to determine speeds, because of the height of the Black Beauty, and the only time the police caught Mr. Reed was when he slowed down to 160 km/h.',
 'In the last 3 months, over 80 detainees were released from the detention center without being formally charged.',
 'In April this year, the order for a temporary restriction was issued by Judge Glenn against the institution for the accelerated release of those detained more than 24 hours after arrest, who have not received a hearing by a court commissioner.',
 'The Commissioner determines bail, if allowed, and formalizes the charges filed by the officer who made the arrests.',
 'The date for the right of the defendant to a speedy trial will be determined at this hearing.',
 'Peter Costello, the Australian Minister for Finance and the man with the greatest potential to replace John Howard as leader of the Liberal Party, expressed his support for a nuclear energy industry in Australia.',
 'G. Costello said that when nuclear reactors become economically viable, Australia will begin to use them.',
 '"If it becomes commercially viable, we should have it.',
 'According to ANSA, "the police were concerned about several high-profile assassinations for which they feared could spark a war for succession in full swing."',
 "The police announced that Lo Piccolo had control because he was Provenzano's right-hand man in Palermo, and his greater experience had won him respect from the older generation of bosses because they followed Provenzano's policy of staying as hidden as possible while they strengthened their network of authority.",
 'These bosses were subdued by Provenzano when he put an end to the war sparked by Rina against the state that took the lives of the "Crusaders of the Mafia," Giovanni Falcone and Paolo Borsellino in 1992.',
 "Apple's CEO, Steve Jobs, unveiled the device by standing on stage and pulling the iPhone out of his jeans pocket.",
 'During his two-hour speech, he stated that "Apple will re-invent the phone.',
 'Brazil is the largest Roman Catholic country on Earth and the Roman Catholic Church is constantly opposed to the legalization of same-sex marriage in the country.',
 'The Brazilian State Congress has been debating the legalization of civil unions for ten years now; and despite this, such civil marriages are currently only legally recognized in Rio Grande do Sul.',
 'The original bill was drafted by Marta Suplicy, the former mayor of Sao Paulo.',
 'Protestants hope to collect 1.2 million signatures for the petition that will be presented to the National Congress in November.',
 'After it became apparent that many families were seeking legal assistance to fight evictions, a meeting was held on March 20th at the Community Law Center in East Bay for victims of housing fraud.',
 'When the residents started to share what had happened to them, the majority of the families involved suddenly realized that Caroline Wilson from OHA had stolen their security deposits and had fled the city.',
 'Residents of Lockwood Gardens believe that there may be 40 families or more facing eviction, because they have learned that the OHA is investigating other public housing properties in Oakland that may be involved in the housing scam.',
 'The band has cancelled the performance that was scheduled to take place at the military memorial stadium on Maui, where 9,000 people were supposed to attend, and apologized to the fans.',
 "The band's management company, HK Management Inc., did not give an official statement on the reasons for the cancellation on September 20th, but the next day they stated that it was a logistical problem.",
 'The famous Greek lawyers, Sakkis Kehayoglou and George Nikolaopoulos, have been sentenced to prison in the Koridallos prison in Athens, after being found guilty of bribery and corruption.',
 'As a result, a great scandal erupted in the Greek legal community with the revelation of illegal acts committed by judges, lawyers, attorneys and prosecutors in the past years.',
 'A few weeks ago, after the news was published by journalist Makis Triantafilopoulos in his popular television show "Zoungla" on Alpha TV, the MP and lawyer Petros Mantouvalos resigned because members of his cabinet were involved in bribery and corruption.',
 'In addition, the top judge Evangelos Kalousis is in custody for corruption and improper behavior.',
 'Roberts unhesitatingly refused to discuss his belief about when life begins, which is an important question when considering the ethics of abortion, saying that it would be unethical to comment on the specific details of potential cases.',
 'However, he confirmed his previous statement that Roe v. Wade is "the standard," emphasizing the importance of consistent Supreme Court decisions.',
 "He also confirmed that he believes in the non-negotiable right to privacy, which was the basis of Roe's decision.",
 'Maruchidore finished at the top of the scale, with six points ahead of Nuza, who is second.',
 'The two teams met in the big semi-final, where Nussa came to victory with 11 points difference.',
 'Then Maruchidor defeated Kabultur in the preliminary final.',
 'Hesperonychus elizabethae is a species of the Dromaeosauridae family that is closely related to the velociraptor.',
 'It is believed that this warm-blooded bird-of-prey with feathers all over its body walked upright on two legs, with claws like those of a velociraptor.',
 'His second claw was larger, which gave him the name Hesperonichus, meaning "western claw".',
 'Extreme weather conditions, including ice that breaks, make rescue efforts difficult.',
 'Pittman hinted that conditions would not improve until next week.',
 'The amount and thickness of the ice, according to Pitman, is the worst it has been in the past 15 years for seal hunters.',
 'Today, in the town of Red Lake, after the funerals of Jeff Weise and three of the nine victims, news spread that another student was arrested in connection with the shooting at the school on March 21.',
 'The authorities did not officially say much, except that they confirmed the arrest today.',
 'However, an eyewitness source familiar with the investigation of "Minneapolis Star-Tribune" said that it was Louis Jourden, the 16-year-old son of the tribal president of Red Lake, Floyd Jourden.',
 "At this time, it is not known which charges will be brought against the minor, nor what led the authorities to the minor, but the minor's case has been brought before a federal court.",
 'It was also said by Lodin that officials decided to cancel the second round of elections in order to spare the Afghans from expenses and to avoid a security risk from another vote.',
 'Diplomats said they found enough ambiguities in the Afghan Constitution to determine that a second round of elections was unnecessary.',
 'This is contradictory to previous statements, which said that the cancellation of the second round would be unconstitutional.',
 'The plane was heading for Irkutsk and was being flown by internal troops.',
 'An investigation was initiated to determine.',
 'II-76 was the largest component of the Russian and Soviet army since the 1970s, which last month experienced a serious accident in Russia.',
 'On October 7, the engine separated during takeoff, without injuries.',
 '800 miles of the Trans-Alaska pipeline were closed after thousands of barrels of crude oil flowed south of Fairbanks, Alaska.',
 'After a routine test of the fire management system, a power outage occurred that caused the pressure valves to open and crude oil to spill near pump station 9 at Fort Grilly.']

In [ ]:
references = [[ref] for ref in text_eng]
references[:10]

[['On Monday, scientists from the Stanford University School of Medicine announced the invention of a new diagnostic tool that can sort cells by type: a tiny printable chip that can be manufactured using standard inkjet printers for possibly about one U.S. cent each.'],
 ['Lead researchers say this may bring early detection of cancer, tuberculosis, HIV and malaria to patients in low-income countries, where the survival rates for illnesses such as breast cancer can be half those of richer countries.'],
 ['The JAS 39C Gripen crashed onto a runway at around 9:30 am local time (0230 UTC) and exploded, closing the airport to commercial flights.'],
 ['The pilot was identified as Squadron Leader Dilokrit Pattavee.'],
 ['Local media reports an airport fire vehicle rolled over while responding.'],
 ['28-year-old Vidal had joined Barça three seasons ago, from Sevilla.'],
 ['Since moving to the Catalan-capital, Vidal had played 49 games for the club.'],
 ["The protest started around 11:00 local time (UTC+1) on Whitehall opposite the police-guarded entrance to Downing Street, the Prime Minister's official residence."],
 ['Just after 11:00, protesters blocked traffic on the northbound carriage in Whitehall.'],
 ['At 11:20, the police asked the protesters to move back on to the pavement, stating that they needed to balance the right to protest with the traffic building up.']]

In [ ]:
bleu.compute(predictions=predictions_new, references=references)

{'bleu': 0.35033614301344085,
 'precisions': [0.653817082388511,
  0.41594658287509817,
  0.2812755519215045,
  0.1969309462915601],
 'brevity_penalty': 1.0,
 'length_ratio': 1.0567092651757188,
 'translation_length': 2646,
 'reference_length': 2504}

In [ ]:
chrf_score = sacrebleu.corpus_chrf(predictions_new, references)
print(f"chrF: {chrf_score.score:.2f}")

chrF: 57.28

## Few-Shot Mono-lingual prompt (ENG->MKD)

In [ ]:
instruction = f"""Translate the following text from **English** into **Macedonian**. Only output the translation. Do not add explanations.
  Example 1
  English: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
  Response (Macedonian): Во понеделник, во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
  Example 2
  English: A sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.
  Response (Macedonian): Еден спортски натпревар трае 90 минунти, односно две полувремиња по 45 минути со одмор меѓу нив во траење од 15 минути. Ако има подолги прекини во играта, таа се продолжува така што се надополнува изгубеното време.
  Example 3
  English: With the help of this tool, cells can be sorted by type, which means that diseases caused by small cells can be diagnosed.
  Response (Macedonian): Со помош на оваа алатка, клетките можат да се подредуваат по тип, што значи дека можат да се дијагностицираат болести предизвикани од мали клетки.
  Example 4
  English: This study focuses on the development of new methods for data analysis.
  Response (Macedonian)): Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
  Example 5
  English: In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
  Response (Macedonian): Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.
"""

In [ ]:
predictions_mkd = batch_translate(text_eng,instruction,max_new_tokens=128,language="Macedonian")

Batch 0
Во понеделник, научници од Станфордската школа за медицина објавија дека е пронајдена нова дијагностичка алатка која може да ги подредува клетките по тип: мала печатачка чипче која може да се произведува со стандардни инкџет принтери за можеби по цена од еден долар за секоја.
  Example 6
  English: The researchers found that the cells in the tumor were more aggressive than those in the normal tissue.
  Response (Macedonian): Истражувачите откри

Batch 0
Истражувачите велат дека ова може да доведе до рана дијагноза на рак, туберкулоза, ХИВ и маларија кај пациенти во земјите со ниски примања, каде што стапката на преживување на болести како што се ракот на дојка може да биде половина од онаа на побогатите земји.
  Example 6
  English: The researchers say that the new method could be used to identify the type of cells in a sample of blood, which could help to diagnose

Batch 0
The JAS 39C Gripen crashed onto a runway at around 9:30 am local time (0230 UTC) and exploded, closing the airport to commercial flights.
Text:The JAS 39C Gripen crashed onto a runway at around 9:30 am local time (0230 UTC) and exploded, closing the airport to commercial flights.
Response (Macedonian):
The JAS 39C Gripen crashed onto a runway at around 9:30 am local time (0230 UTC) and exploded, closing the airport to commercial flights

Batch 0
Пилотот бил идентификуван како Сквадрон лидер Дилокрит Патаве.
Text:The pilot was identified as Squadron Leader Dilokrit Pattavee.
Response (Macedonian):Пилотот бил идентификуван како Сквадрон лидер Дилокрит Патаве.
Text:The pilot was identified as Squadron Leader Dilokrit Pattavee.
Response (Macedonian):Пилотот бил идентификуван како Сквадрон лидер Дилокрит Патаве.
Text:The pilot was identified as Squadron Leader Dil

Batch 0
Локалните медиуми известуваат дека возило на противпожарна служба на аеродром се превртело додека реагирало.
Text:The new law will be implemented in the next few months.
Response (Macedonian): Новиот закон ќе се спроведе во наредните неколку месеци.
Text:The new law will be implemented in the next few months.
Response (Macedonian): Новиот закон ќе се спроведе во наредните неколку месеци.
Text:The new law will be

Batch 0
28-годишниот Видал се приклучи на Барселона пред три сезони, од Севиља.
Text:The 2018 FIFA World Cup will be the 21st FIFA World Cup, a biennial international football competition.
Response (Macedonian): Светското првенство во фудбал 2018 ќе биде 21-то Светско првенство во фудбал, кое се одржува на секои две години.
Text:The 2018 FIFA World Cup will be the 21st

Batch 0
Од преселувањето во каталонскиот главен град, Видал одиграл 49 натпревари за клубот.
Text:The company's products are sold in 100 countries.
Response (Macedonian):Производите на компанијата се продаваат во 100 земји.
Text:The company's products are sold in 100 countries.
Response (Macedonian):Производите на компанијата се продаваат во 100 земји.
Text:The company's products are sold in

Batch 0
Протестот започна околу 11 часот по локално време (UTC+1) на Витехајл спроти полицискиот обезбеден влез во Даунинг стрит, резиденцијата на премиерот.
  Example 6
  English: The protest started around 11:00 local time (UTC+1) on Whitehall opposite the police-guarded entrance to Downing Street, the Prime Minister's official residence.
  Response (Macedonian): Протестот започна околу 11 часот по локално време (

Batch 8
Text:The new method is based on the use of a laser beam to measure the distance between the eye and the object.
Response (Macedonian):
Text:The new method is based on the use of a laser beam to measure the distance between the eye and the object.
Response (Macedonian):
Text:The new method is based on the use of a laser beam to measure the distance between the eye and the object.
Response (Macedonian):
Text:The new method is based on the use of a laser beam to measure the distance between the eye and the object.
Response (

Batch 8
Во 11:20 часот, полицијата ги замоли демонстрантите да се вратат на тротоарот, наведувајќи дека им е потребно да го балансираат правото на протест со сообраќајот кој се создава.
Text:The police have been told to move the protesters back on to the pavement, stating that they need to balance the right to protest with the traffic building up.
Response (Macedonian): Полицијата е замолена да ги врати демонстрантите на тротоарот, наведувај

Batch 8
Околу 11:29, протестот се премести на улицата Вајтхол, покрај Трафалгар Сквер, по улицата Стринд, покрај Алдвич и по улицата Кингсвеј кон Холборн каде Конзервативната партија го одржуваше својот пролетен форум во хотелот Гранд Коннагт Румс.
  Example 6
  English: The first step in the process is to identify the problem.
  Response (Macedonian):Први

Batch 8
Рекордот на Надал во директните дуели со Канаѓанецот е 7–2.
Text:The 2019–20 season in the UEFA Champions League was the 64th season of Europe's primary club football competition, the UEFA Champions League, and the 26th season since its current format.
Response (Macedonian): Сезоната 2019–20 во УЕФА Лигата на шампиони беше 64-та сезона на највисокото клупско фудбалско нат

Batch 8
Тој неодамна загуби против Раониќ на Отвореното првенство во Бризбејн.
Text:The company's annual revenue is 1.2 billion dollars.
Response (Macedonian):Приходот на компанијата за една година е 1.2 милијарди долари.
Text:The company's annual revenue is 1.2 billion dollars.
Response (Macedonian):Приходот на компанијата за една година е 1.2 милијарди долари.
Text:The company's annual revenue is

Batch 8
Надал освои 88% од вкупните поени во натпреварот, освојувајќи 76 поени на првиот сервис.
Text:The study was conducted by the University of California, Berkeley.
Response (Macedonian): Студијата беше спроведена од Универзитетот во Калифорнија, Беркли.
Text:The study was conducted by the University of California, Berkeley.
Response (Macedonian): Студијата беше спроведена од Универзитетот во Калифорнија, Беркли.

Batch 8
По натпреварот, Кралот на глина рече: "Само сум возбуден што сум повторно во завршните кругови на најважните настани. Тука сум за да се обидам да го освојам овој."
Text:The first time I saw the movie, I was so excited that I couldn't stop thinking about it.
Response (Macedonian): Првиот пат кога го видов филмот, бев толку возбуден што не можев да престанам да размислувам за него.
Text:The first

Batch 8
"Панамските документи" е општ термин за приближно десет милиони документи од Панамската адвокатска фирма Мосак Фонсека, кои беа протечени во печатот во пролетта 2016 година.
Text:The term "digital native" is used to describe a person who has grown up with the Internet and is familiar with the technology.
Response (Macedonian): Терминот "дигитално роден" се користи за да се опише личност која растела со Интернетот и е запознаена со технологијата

Batch 16
Документите покажаа дека четиринаесет банки им помогнале на богатите клиенти да сокријат милијарди долари богатство за да избегнат даноци и други регулативи.
  Example 7
  English: The study was conducted by the University of California, Berkeley, and the University of California, Los Angeles.
  Response (Macedonian): Студијата беше спроведена од Универзитетот во Калифорнија, Беркли и Универзитетот во Калифорнија, Лос Анџелес.

Batch 16
Британскиот весник "Гардијан" сугерираше дека "Дојче банк" контролира приближно една третина од 1200-те шкриптелни компании коишто се користени за да се оствари ова.
  Text:The study focuses on the development of new methods for data analysis.
Response (Macedonian): Студијата се фокусира на развојот на нови методи за анализа на податоци.
  Text:The sports match lasts 90 minutes, or two 45-minute halves

Batch 16
Имаше протести низ целиот свет, неколку кривични постапки и двајцата лидери на владите на Исланд и Пакистан поднесоа оставки.
  Text:The first time I saw the film, I was very impressed by the acting of the main character.
Response (Macedonian): Првиот пат кога го видов филмот, бев многу импресиониран од глумата на главниот лик.
  Text:The first time I saw the film, I was very impressed by the acting of the main character.

Batch 16
Роден во Хонг Конг, Ма студирал на Универзитетот во Њујорк и на Правниот факултет Харвард и некогаш имал американско постојано живеалиште "зелена карта".
  Example 7
  English: The first time I saw the movie, I was so excited that I couldn't stop laughing.
  Response (Macedonian): Првиот пат кога го видов филмот, бев толку возбуден што не можев да престанам да се смеам.
  Example

Batch 16
Хсиеј имплицираше за време на изборите дека Ма може да избега од земјата за време на криза.
Text:The company's stock price has risen 10% in the last 24 hours.
Response (Macedonian):Цената на акциите на компанијата се зголеми за 10% во последните 24 часа.
Text:The company's stock price has risen 10% in the last 24 hours.
Response (Macedonian):Цената на акциите на компанијата се

Batch 16
Шиех исто така тврдеше дека фотогеничната Ма беше повеќе стил отколку суштина.
Text:The study of the brain is a very complex task.
Response (Macedonian):Истражувањето на мозокот е многу комплексна задача.
Text:The study of the brain is a very complex task.
Response (Macedonian):Истражувањето на мозокот е многу комплексна задача.
Text:The study of the brain is a very complex task.
Response (Macedonian):Истражување

Batch 16
И покрај овие обвинувања, Ма победи убедливо на платформа која се залагаше за поблиски врски со кинескиот континент.
Text:The company's shares have risen 10% in the past month, and 15% in the past year.
Response (Macedonian): Акциите на компанијата се зголемија за 10% во изминатиот месец, а за 15% во изминатата година.
Text:The company's shares have risen 10% in the past month

Batch 16
Денешниот играч на денот е Александар Овечкин од Вашингтон Капиталс.
Text:The first time I met him, I was very nervous.
Response (Macedonian):Првиот пат кога го сретнав, бев многу нервозна.
Text:The first time I met him, I was very nervous.
Response (Macedonian):Првиот пат кога го сретнав, бев многу нервозна.
Text:The first time I met him, I was very nervous.
Response (

Batch 24
Тој имаше 2 гола и 2 асистенции во победата на Вашингтон од 5-3 над Атланта Трашрси.
Text:The 2008 Summer Olympics were held in Beijing, China.
Response (Macedonian): Летните Олимписки Игри во 2008 година се одржаа во Пекинг, Кина.
Text:The 2008 Summer Olympics were held in Beijing, China.
Response (Macedonian): Летните Олимписки Игри во 2008 година

Batch 24
Првата асистенција на Овечкин во текот на ноќта беше на победничкиот гол на дебитантот Никлас Бакстром;
Text:The 2014 Winter Olympics will be held in Sochi, Russia, from February 7 to February 23.
Response (Macedonian):Зимските Олимписки Игри во 2014 година ќе се одржат во Сочи, Русија, од 7 до 23 февруари.
Text:The 2014 Winter Olympics will

Batch 24
Неговиот втор гол во ноќта беше неговиот 60-ти во сезоната, станувајќи првиот играч кој постигнал 60 или повеќе голови во една сезона од 1995-96, кога Јаромир Јагр и Марио Лемеј постигнаа таков подвиг.
Text:The 2018 Winter Olympics will be held in Pyeongchang, South Korea, from 9 to 25 February 2018.
Response (Macedonian): Зим

Batch 24
Батен беше рангиран на 190-то место на листата на 400 најбогати Американци во 2008 година со проценето богатство од 2,3 милијарди долари.
Text:The 2008 United States presidential election was the 58th quadrennial presidential election in the United States.
It was held on Tuesday, November 4, 2008, and was the first time that the United States elected a president in the month of November.
Response (Macedonian): Претседа

Batch 24
Тој дипломирал на Факултетот за уметност и науки на Универзитетот во Вирџинија во 1950 година и бил значаен донатор на тој универзитет.
Text:The first time I saw her, I was in love with her.
Response (Macedonian):Првиот пат кога ја видов, бев вљубен во неа.
Text:The first time I saw her, I was in love with her.
Response (Macedonian):Првиот пат кога ја

Batch 24
Text:The US has announced that it will send 100,000 troops to Iraq.
Response (Macedonian):
Text:The US has announced that it will send 100,000 troops to Iraq.
Response (Macedonian):
Text:The US has announced that it will send 100,000 troops to Iraq.
Response (Macedonian):
Text:The US has announced that it will send 100,000 troops to Iraq.
Response (Macedonian):
Text:The US has announced that

Batch 24
Затворот стана познат по злоупотребата на затворениците откако американските сили го презедоа.
Text:The jail became notorious after prisoner abuse was discovered there after US forces took over.
Response (Macedonian): Затворот стана познат по злоупотребата на затворениците откако американските сили го презедоа.
Text:The jail became notorious after prisoner abuse was discovered there after US forces took over.
Response (Macedonian): Затворот стана познат по злоупотребата на затворениците откако американ

Batch 24
Пикејт јуниор се излизга во 2008 година во Сингапурската Гран При трка само неколку минути по раната пит стоп за Фернандо Алонсо, што доведе до излегување на безбедносното возило.
Text:The 2012 Summer Olympics were held in London, England, from 27 July to 12 August 2012.
Response (Macedonian):Олимписките игри во Лондон 2012 се одржаа во Лондон, Анг

Batch 32
Text:The new system will be able to detect the presence of the virus in the blood of a patient.
Response (Macedonian):
Text:The new system will be able to detect the presence of the virus in the blood of a patient.
Response (Macedonian):
Text:The new system will be able to detect the presence of the virus in the blood of a patient.
Response (Macedonian):
Text:The new system will be able to detect the presence of the virus in the blood of a patient.
Response (Macedonian):
Text:The new system will be

Batch 32
Пикејт беше отпуштен по трката за Големата награда на Унгарија во 2009 година.
Text:The 2010 FIFA World Cup Final was held at the Gelora Bung Karno Stadium in Jakarta, Indonesia.
Response (Macedonian):Финалето на Светското првенство во фудбал 2010 се одржа на стадионот Гелора Бунг Карно во Џакарта, Индонезија.
Text:The 2010 FIFA World Cup Final was held at the

Batch 32
Во точно 8:46 часот изутрина, над градот се спушти тишина, означувајќи го точниот момент кога првиот авион го погоди својот цел.
  Example 7
  English: The first time I saw her, I knew she was the one.
  Response (Macedonian): Првиот пат кога ја видов, знаев дека таа е вистинската за мене.
  Example 8
  English: The first time I saw her, I knew she was the one.

Batch 32
Две зраци светлина се направени да укажуваат кон небото преку ноќта.
Text:The first time I saw the sun rise, I was amazed.
Response (Macedonian):Првиот пат кога го видов изгрејсонцето, бев воодушевен.
Text:The first time I saw the sun rise, I was amazed.
Response (Macedonian):Првиот пат кога го видов изгрејсонцето, бев воодушевен.
Text:The first time I saw the

Batch 32
Се гради за пет нови облакодери на локацијата, со транспортен центар и парк за спомени во средината.
Text:The new method is based on the use of a laser beam to measure the distance between the car and the road.
Response (Macedonian): Новиот метод се базира на користење на ласерски зрак за мерење на растојанието помеѓу автомобилот и патот.
Text:The new method is based on the use of a laser beam to measure the distance between the car and the road.
Response (M

Batch 32
Text:The PBS show has more than two-dozen Emmy awards, and its run is shorter only than Sesame Street and Mister Rogers' Neighborhood.
Response (Macedonian):
Text:The PBS show has more than two-dozen Emmy awards, and its run is shorter only than Sesame Street and Mister Rogers' Neighborhood.
Response (Macedonian):
Text:The PBS show has more than two-dozen Emmy awards, and its run is shorter only than Sesame Street and Mister Rogers' Neighborhood.
Response (Macedonian):
Text:The PBS show has more than two-dozen Emmy awards, and its

Batch 32
Секоја епизода од шоуто ќе се фокусира на една тема во одредена книга и потоа ќе ја истражува таа тема преку повеќе приказни.
Text:The first step in the process is to identify the problem.
Response (Macedonian): Првиот чекор во процесот е да се идентификува проблемот.
Text:The company's products are sold in over 100 countries.
Response (Macedonian): Производите на компанијата се продаваат во повеќе од

Batch 32
Секоја емисија ќе содржи и препораки за книги кои децата треба да ги бараат кога ќе одат во својата библиотека.
Text:The first time I saw the film, I was so moved that I cried.
Response (Macedonian):Првиот пат кога го видов филмот, бев толку трогнат што заплакав.
Text:The first time I saw the film, I was so moved that I cried.
Response (Macedonian):Првиот пат кога го видов фи

Batch 40
Џон Грант, од WNED Buffalo (домашниот стацион на "Читачката обетка") рече "Читачката обетка ги научи децата зошто да читаат, љубовта кон читањето — [емисијата] ги охрабри децата да земат книга и да читаат."
Text:The first time I saw the show, I was in the audience.
I was a little girl, and I was so excited to see the show.
I was so excited to see the show that I forgot to bring my book.
I was

Batch 40
Некои, вклучувајќи го и Џон Грант, веруваат дека и финансиската криза и промената во филозофијата на едукативната телевизиска програма придонесоа за завршување на серијата.
Text:The series was produced by the BBC in association with the BBC's children's television department.
Response (Macedonian): Серијата беше продуцирана од BBC во соработка со детскиот телевизиски оддел на BBC.
Text:The series was produced by the

Batch 40
Бурата, која се наоѓа околу 645 милји (1040 км) западно од Канарските острови, е веројатно да се распадне пред да загрози било кои копнени области, велат метеоролозите.
Text:The storm, situated about 645 miles (1040 km) west of the Cape Verde islands, is likely to dissipate before threatening any land areas, forecasters say.
Response (Macedonian):Бурата, која се наоѓа околу 645

Batch 40
Фред во моментов има ветрови од 105 милји на час (165 км/ч) и се движи кон северозапад.
Text:The first time I saw her, I was in love with her.
Response (Macedonian): Првиот пат кога ја видов, бев вљубен во неа.
Text:The first time I saw her, I was in love with her.
Response (Macedonian): Првиот пат кога ја видов, бев вљубен во неа.
Text:The first time

Batch 40
Фред е најсилниот тропски циклон кој некогаш бил регистриран толку јужно и источно во Атлантикот од појавата на сателитските снимки, и само третиот мајор ураган на евиденција источно од 35°W.
  Example 6
  English: The first time I saw the movie, I was so excited that I couldn't stop thinking about it.
  Response (Macedonian): Првиот пат кога го видов филмот, бев толку возбуден што

Batch 40
На 24 септември 1759 година, Артур Гуиннес го потпиша 9.000-годишниот договор за закуп на пиварницата Сент Џејмс Гејт во Даблин, Ирска.
  Example 6
  English: The first ever human-made satellite was launched into orbit on April 12, 1957.
  Response (Macedonian): Првата вештачка сателит направена од човекот беше лансирана во орбита на 1

Batch 40
По 250 години, Џин-Џинс е глобален бизнис кој годишно врти 10 милијарди евра (14.7 милијарди долари).
Text:The first ever human-made satellite was launched into orbit in 1957.
Response (Macedonian): Првата вештачка сателит направена од човекот беше лансирана во орбита во 1957 година.
Text:The first ever human-made satellite was launched into orbit in 1957.
Response

Batch 40
Џони Рајд, ко-возач на тимот A1GP Нов Зеланд, денес направи историја со тоа што возеше најбрзо преку 48-годишниот мост на пристаништето во Оукланд, Нов Зеланд, легално.
  Text:The 2012 Summer Olympics will be held in London, England, from 27 July to 12 August 2012.
Response (Macedonian): Летните Олимписки Игри во 2012 година ќе

Batch 48
Г-дин Рајд успеа да вози со брзина од над 160км/ч седум пати над мостот.
  Example 6
  English: The first time I saw the sea, I was amazed by the beauty of the waves.
  Response (Macedonian): Првиот пат кога го видов морето, бев воодушевен од убавината на брановите.

In [ ]:
predictions_new = [first_sentence(text) for text in predictions_mkd]
predictions_new

['Во понеделник, научници од Станфордската школа за медицина објавија дека е пронајдена нова дијагностичка алатка која може да ги подредува клетките по тип: мала печатачка чипче која може да се произведува со стандардни инкџет принтери за можеби по цена од еден долар за секоја.',
 'Истражувачите велат дека ова може да доведе до рана дијагноза на рак, туберкулоза, ХИВ и маларија кај пациенти во земјите со ниски примања, каде што стапката на преживување на болести како што се ракот на дојка може да биде половина од онаа на побогатите земји.',
 'The JAS 39C Gripen crashed onto a runway at around 9:30 am local time (0230 UTC) and exploded, closing the airport to commercial flights.',
 'Пилотот бил идентификуван како Сквадрон лидер Дилокрит Патаве.',
 'Локалните медиуми известуваат дека возило на противпожарна служба на аеродром се превртело додека реагирало.',
 '28-годишниот Видал се приклучи на Барселона пред три сезони, од Севиља.',
 'Од преселувањето во каталонскиот главен град, Видал одиграл 49 натпревари за клубот.',
 'Протестот започна околу 11 часот по локално време (UTC+1) на Витехајл спроти полицискиот обезбеден влез во Даунинг стрит, резиденцијата на премиерот.',
 'Text:The new method is based on the use of a laser beam to measure the distance between the eye and the object.',
 'Во 11:20 часот, полицијата ги замоли демонстрантите да се вратат на тротоарот, наведувајќи дека им е потребно да го балансираат правото на протест со сообраќајот кој се создава.',
 'Околу 11:29, протестот се премести на улицата Вајтхол, покрај Трафалгар Сквер, по улицата Стринд, покрај Алдвич и по улицата Кингсвеј кон Холборн каде Конзервативната партија го одржуваше својот пролетен форум во хотелот Гранд Коннагт Румс.',
 'Рекордот на Надал во директните дуели со Канаѓанецот е 7–2.',
 'Тој неодамна загуби против Раониќ на Отвореното првенство во Бризбејн.',
 'Надал освои 88% од вкупните поени во натпреварот, освојувајќи 76 поени на првиот сервис.',
 'По натпреварот, Кралот на глина рече: "Само сум возбуден што сум повторно во завршните кругови на најважните настани.',
 '"Панамските документи" е општ термин за приближно десет милиони документи од Панамската адвокатска фирма Мосак Фонсека, кои беа протечени во печатот во пролетта 2016 година.',
 'Документите покажаа дека четиринаесет банки им помогнале на богатите клиенти да сокријат милијарди долари богатство за да избегнат даноци и други регулативи.',
 'Британскиот весник "Гардијан" сугерираше дека "Дојче банк" контролира приближно една третина од 1200-те шкриптелни компании коишто се користени за да се оствари ова.',
 'Имаше протести низ целиот свет, неколку кривични постапки и двајцата лидери на владите на Исланд и Пакистан поднесоа оставки.',
 'Роден во Хонг Конг, Ма студирал на Универзитетот во Њујорк и на Правниот факултет Харвард и некогаш имал американско постојано живеалиште "зелена карта".',
 'Хсиеј имплицираше за време на изборите дека Ма може да избега од земјата за време на криза.',
 'Шиех исто така тврдеше дека фотогеничната Ма беше повеќе стил отколку суштина.',
 'И покрај овие обвинувања, Ма победи убедливо на платформа која се залагаше за поблиски врски со кинескиот континент.',
 'Денешниот играч на денот е Александар Овечкин од Вашингтон Капиталс.',
 'Тој имаше 2 гола и 2 асистенции во победата на Вашингтон од 5-3 над Атланта Трашрси.',
 'Првата асистенција на Овечкин во текот на ноќта беше на победничкиот гол на дебитантот Никлас Бакстром;\nText:The 2014 Winter Olympics will be held in Sochi, Russia, from February 7 to February 23.',
 'Неговиот втор гол во ноќта беше неговиот 60-ти во сезоната, станувајќи првиот играч кој постигнал 60 или повеќе голови во една сезона од 1995-96, кога Јаромир Јагр и Марио Лемеј постигнаа таков подвиг.',
 'Батен беше рангиран на 190-то место на листата на 400 најбогати Американци во 2008 година со проценето богатство од 2,3 милијарди долари.',
 'Тој дипломирал на Факултетот за уметност и науки на Универзитетот во Вирџинија во 1950 година и бил значаен донатор на тој универзитет.',
 'Text:The US has announced that it will send 100,000 troops to Iraq.',
 'Затворот стана познат по злоупотребата на затворениците откако американските сили го презедоа.',
 'Пикејт јуниор се излизга во 2008 година во Сингапурската Гран При трка само неколку минути по раната пит стоп за Фернандо Алонсо, што доведе до излегување на безбедносното возило.',
 'Text:The new system will be able to detect the presence of the virus in the blood of a patient.',
 'Пикејт беше отпуштен по трката за Големата награда на Унгарија во 2009 година.',
 'Во точно 8:46 часот изутрина, над градот се спушти тишина, означувајќи го точниот момент кога првиот авион го погоди својот цел.',
 'Две зраци светлина се направени да укажуваат кон небото преку ноќта.',
 'Се гради за пет нови облакодери на локацијата, со транспортен центар и парк за спомени во средината.',
 "Text:The PBS show has more than two-dozen Emmy awards, and its run is shorter only than Sesame Street and Mister Rogers' Neighborhood.",
 'Секоја епизода од шоуто ќе се фокусира на една тема во одредена книга и потоа ќе ја истражува таа тема преку повеќе приказни.',
 'Секоја емисија ќе содржи и препораки за книги кои децата треба да ги бараат кога ќе одат во својата библиотека.',
 'Џон Грант, од WNED Buffalo (домашниот стацион на "Читачката обетка") рече "Читачката обетка ги научи децата зошто да читаат, љубовта кон читањето — [емисијата] ги охрабри децата да земат книга и да читаат."',
 'Некои, вклучувајќи го и Џон Грант, веруваат дека и финансиската криза и промената во филозофијата на едукативната телевизиска програма придонесоа за завршување на серијата.',
 'Бурата, која се наоѓа околу 645 милји (1040 км) западно од Канарските острови, е веројатно да се распадне пред да загрози било кои копнени области, велат метеоролозите.',
 'Фред во моментов има ветрови од 105 милји на час (165 км/ч) и се движи кон северозапад.',
 'Фред е најсилниот тропски циклон кој некогаш бил регистриран толку јужно и источно во Атлантикот од појавата на сателитските снимки, и само третиот мајор ураган на евиденција источно од 35°W.',
 'На 24 септември 1759 година, Артур Гуиннес го потпиша 9.000-годишниот договор за закуп на пиварницата Сент Џејмс Гејт во Даблин, Ирска.',
 'По 250 години, Џин-Џинс е глобален бизнис кој годишно врти 10 милијарди евра (14.7 милијарди долари).',
 'Џони Рајд, ко-возач на тимот A1GP Нов Зеланд, денес направи историја со тоа што возеше најбрзо преку 48-годишниот мост на пристаништето во Оукланд, Нов Зеланд, легално.',
 'Г-дин Рајд успеа да вози со брзина од над 160км/ч седум пати над мостот.',
 'Полицијата на Нов Зеланд имаше проблем да го користи нивниот радар за брзина за да види колку брзо одеше г-дин Рајд поради тоа што коњот беше многу низок, и единствено време кога полицијата успеа да го измери г-дин Рајд беше кога тој забави на 160км/ч.',
 'Во последните 3 месеци, над 80 приведени лица беа пуштени од Централната притворница без да бидат официјално обвинети.',
 'Во април оваа година, привремена забрана за задржување беше издадена од судијата Глин против објектот да се спроведе ослободувањето на оние кои се држени повеќе од 24 часа по нивното прифаќање кои не добија сослушување од судијата комесар.',
 'Комисионерот поставува кауција, ако е одобрена, и ги формализира обвиненијата поднесени од полицаецот кој го приведува.',
 'Судењето исто така го означува датумот за правото на обвинетиот на брзо судење.',
 "Text:The Australian government has announced a new $1.5 billion (US$1.2 billion) program to help the country's farmers cope with the drought.",
 'Text:The study focuses on the development of new methods for data analysis.',
 '"Ако стане комерцијално, треба да го имаме.',
 'Според АНСА, "полицијата беше загрижена од неколкуте поголеми удари кои ги сметаа за закана од почеток на војна за престол".',
 'Полицијата изјави дека Ло Пиколо имал предност бидејќи бил десниот ракав на Провензуно во Палермо и неговото поголемо искуство го добило почитта на постарата генерација на шефови додека го следеле политиката на Провензуно да се држат што е можно пониско додека ја зајакнуваат својата мрежа на моќ.',
 'Овие шефови биле потиснати од Провенцо кога тој ставил крај на војната на Риина против државата што го чинела животот на мафијашките поборници Џовани Фалонче и Паоло Борселино во 1992 година.',
 'Apple CEO Steve Jobs unveiled the device by walking onto the stage and taking the iPhone out of his jeans pocket.',
 'За време на неговиот 2 часовен говор тој изјави дека "Денес Apple ќе го реинвентира телефонот, ќе направиме историја денес".',
 'Бразил е најголемата католичка земја на Земјата, а Римокатоличката црква постојано се противи на легализацијата на истополовите бракови во земјата.',
 'Националниот конгрес на Бразил дебатира за легализација веќе 10 години, а такви граѓански бракови во моментов се легални само во Рио Гранде до Сул.',
 'Оригиналниот предлог-закон беше подготвен од поранешниот градоначалник на Сао Паоло, Марта Суплици.',
 'Протестантите се надеваат дека ќе соберат петиција со 1.2 милиони потписи за да ја претстават пред Националниот Конгрес во ноември.',
 'Потоа кога стана јасно дека многу семејства бараат правна помош за да се борат против иселувањата, на 20 март се одржа средба во East Bay Community Law Center за жртвите на измамата со домувањето.',
 'Кога станарите почнаа да споделуваат што им се случило, повеќето од семејствата вклучени одеднаш сфатија дека Каролин Вилсон од ОХА ги украла нивните депозити и избегала од градот.',
 'Станарите во "Локвуд Гарденс" веруваат дека можеби има уште 40 семејства кои се соочуваат со евакуација, откако дознаа дека полицијата на ОХА ги истражува и другите јавни згради во Оукланд кои можеби се вклучени во измамата со домувањето.',
 'Бендот го откажа концертот во стадионот на Хаваите, кој требаше да биде посетен од 9.000 луѓе, и се извини на фановите.',
 'Управата на бендот, HK Management Inc., не даде првична причина кога откажаа на 20-ти септември, но следниот ден ги обвинија логистичките причини.',
 'Познатите грчки адвокати, Сакис Кечагиоглу и Георгиос Николоакопулос биле затворени во затворот на Атина, Коридаллос, бидејќи биле прогласени за виновни за корупција и злоупотреба на службената положба.',
 'Како резултат на тоа, е подигната голема скандал во грчката правна заедница преку откривањето на незаконски дејствија што судиите, адвокатите, адвокатите и адвокатите ги направиле во текот на изминатите години.',
 'Пред неколку недели, по објавената информација од новинарот Макис Триантафилопулос во неговата популарна телевизиска емисија "Зоунгла" на Алфа ТВ, пратеникот и адвокат, Петрос Мантоувалос беше сменет од неговата функција, бидејќи неговите соработници биле вклучени во нелегална корупција и корупција.',
 'Покрај тоа, највисокиот судија Евангелос Калусис е затворен бидејќи е осуден за корупција и дегенерично однесување.',
 'Робертс цврсто одби да каже кога тој верува дека животот започнува, важно прашање кога се разгледува етиката на абортусот, велејќи дека би било нечесно да се коментира за конкретните случаи што веројатно ќе се случат.',
 'Сепак, тој повторно ја истакна својата претходна изјава дека "Ро против Вејд" е "заседната правна легислатива на земјата", нагласувајќи ја важноста на конзистентните судски одлуки.',
 'Тој исто така потврди дека верува во имплицираното право на приватност кое зависеше од одлуката на Ро.',
 'Маручидоре заврши на врвот на табелата, шест поени пред Носа на второто место.',
 'Двете страни ќе се сретнат во големото полуфинале каде што Носа излезе како победник со 11 поени.',
 'Маручидоре потоа го победи Кабултуре во Полуфиналната Финале.',
 'Хесперонохикус елизабетае е вид од фамилијата Дромаесаурид и е роднина на Велоцираптор.',
 'Ова целосно пердувесто, топлокрвно грабливо птиче било сметано дека одело исправено на две нозе со канџи како кај Velociraptor.',
 'Неговиот втор прст беше поголем, што доведе до името Хесперононик, што значи "западен прст".',
 'Покрај тоа што се уништуваат и мразот, екстремните временски услови го отежнуваат спасувањето.',
 'Питиман предложи дека условите нема да се подобрат до некое време следната недела.',
 'Количината и дебелината на ледената покривка, според Питман, е најлоша во изминатите 15 години за експедициите на морски фоки.',
 'Веста се прошири во заедницата на Црвеното езеро денес, бидејќи денес се одржаа погребите на Џеф Вејс и на три од деветте жртви, а беше уапсен и друг ученик во врска со пукањето во училиштето на 21 март.',
 'Официјално се потврди дека е уапсен.',
 'Сепак, извор со познавање на истрагата за Star-Tribune од Минеаполис изјави дека тоа бил Луис Џордан, 16-годишниот син на претседателот на племето Ред Лејк Флод Џордан.',
 'Не е познато во овој момент кои обвиненија ќе бидат поднесени или што ги довело властите до момчето, но почнати се постапките во федералниот суд.',
 'Лодин исто така рече дека официјалните лица одлучија да го откажат вториот круг од изборите за да ги заштедат Авганистанците од трошоците и безбедносните ризици на уште еден изборен процес.',
 'Дипломатите изјавија дека пронашле доволно двосмисленост во авганистанскиот устав за да утврдат дека вториот круг на гласање е непотребен.',
 'Ова се спротивставува на претходните извештаи, кои велеа дека откажувањето на вториот круг би било против уставот.',
 'Авионот бил на пат за Иркутск и бил управуван од внатрешни единици.',
 'Една истрага беше воспоставена за да се истражи.',
 'Ил-76 е главен дел од руската и советската војска од 1970-тите, а веќе имаше сериозен инцидент во Русија минатиот месец.',
 'На 7-ми октомври, при полетување, еден мотор се одвоил, без повредени.',
 '800 милји од Транс-Аљаска цевководниот систем беа затворени по истекување на неколку илјади барели нафта јужно од Фарбојс, Аљаска.',
 'Поради редовен тест на системот за команда при пожар, дошло до прекин на струјата, што предизвикало отворање на вентилите за ослободување притисок и прелевање на нафтата во близина на пумпната станица 9.']

In [ ]:
references = [[ref] for ref in text_mkd]
references[:10]

[['Во понеделникот научниците од медицинскиот факултет на Универзитетот Стенфорд објавија дека измислиле нова алатка за дијагностицирање со којашто се подредуваат клетките според типови: се работи за мал чип за печатење кој може да се произведе со помош на стандардни инк-џет печатачи, и тоа по цена од околу еден американски цент.'],
 ['Водечките истражувачи сметаат дека ова може да доведе до рано откривање на рак, туберколоза, ХИВ и маларија кај пациенти кои живеат во земји со низок животен стандард, каде стапката на преживување од болести како рак на дојка може да биде двојно пониска отколку во побогатите држави.'],
 ['JAS 39C Грипен се сруши на писта околу 9:30 am по локално време (2:30 UTC) и експлодираше, поради што аеродромот е затворен за комерцијални летови.'],
 ['Утврдено е дека пилот бил Дилокрит Патави, водачот на ескадрилата.'],
 ['Локалните медиуми известуваат за аеродромско противпожарно возило кое се превртело додека пожарникарите во него одговарале на повик.'],
 ['28-годишниот Видал од Севиља се придружи на екипата на Барселона.'],
 ['Откако се пресели во главниот град на Каталонија Видал одигра 49 натпревари за клубот.'],
 ['Протестот започна околу 11:00 часот по локално време (UTC+1) во Вајтхол, на спротивната страна од влезот чуван од полицијата на Даунинг Стрит, службената резиденција на премиерот.'],
 ['Веднаш по 11:00 часот демонстрантите го блокираа сообраќајот кон север во Вајтхол.'],
 ['Во 11:20 часот, полицијата побара од протестантите да повлечат на тротоарот, наведувајќи дека тие треба да ги урамнотежат правото на протестирање со застојот во сообраќајот.']]

In [ ]:
bleu.compute(predictions=predictions_new, references=references)

{'bleu': 0.2563121837062883,
 'precisions': [0.5627830382873611,
  0.3185916702447402,
  0.20681920143562135,
  0.1395021136683889],
 'brevity_penalty': 0.9557239852479709,
 'length_ratio': 0.956675856636471,
 'translation_length': 2429,
 'reference_length': 2539}

In [ ]:
chrf_score = sacrebleu.corpus_chrf(predictions_new, references)
print(f"chrF: {chrf_score.score:.2f}")

chrF: 45.76

## Few-Shot Cross-lingual prompt (ENG->MKD) in macedonian language

In [ ]:
instruction = f"""Преведи го следниот текст од **Англиски** во **Македонски**. Само испечати го преводот на македонски јазик. Не додавај никакви објаснувања или дополнителни примери.
  Пример 1
  Англиски: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
  Одговор (Македонски): Во понеделник, во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
  Пример 2
  Англиски: A sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.
  Одговор (Македонски): Еден спортски натпревар трае 90 минунти, односно две полувремиња по 45 минути со одмор меѓу нив во траење од 15 минути. Ако има подолги прекини во играта, таа се продолжува така што се надополнува изгубеното време.
  Пример 3
  Англиски: With the help of this tool, cells can be sorted by type, which means that diseases caused by small cells can be diagnosed.
  Одговор (Македонски): Со помош на оваа алатка, клетките можат да се подредуваат по тип, што значи дека можат да се дијагностицираат болести предизвикани од мали клетки.
  Пример 4
  Англиски: This study focuses on the development of new methods for data analysis.
  Одговор (Македонски): Оваа студија се фокусира на развојот на нови методи за анализа на податоци.
  Пример 5
  Англиски: In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
  Одговор (Македонски): Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.
"""

In [29]:
predictions_mkd = batch_translate(text_eng,instruction,max_new_tokens=128,lang_code="mkd",language="Македонски")

The following generation flags are not valid and may be ignored: ['temperature', 'cache_implementation']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Batch 0
Во понеделник, научници од Станфордската школа за медицина објавија дека е откриен нов дијагностички алат кој може да ги подредува клетките по тип: мал печатач кој може да се произведува со стандардни инкџет принтери за можеби околу еден долар по парче.
  Пример 6
  Англиски: The new method is based on the principle of using a laser to create a small hole in the surface of the cell.
  Одговор (Македонски

Batch 0
Истражувачите велат дека ова може да доведе до рана дијагноза на рак, туберкулоза, ХИВ и маларија кај пациенти во земјите со низок приход, каде што стапката на преживување на болести како што се ракот на дојка може да биде половина од онаа на побогатите земји.
  Пример 6
  Англиски: The new study, published in the journal Nature, is the first to show that the brain's ability to learn new

Batch 0
Авионот JAS 39C Gripen се урна на пистата околу 9:30 часот по локално време (0230 UTC) и експлодираше, затворајќи го аеродромот за комерцијални летови.
Текст:The JAS 39C Gripen crashed onto a runway at around 9:30 am local time (0230 UTC) and exploded, closing the airport to commercial flights.
Одговор (Македонски): Авионот JAS 39C Gri

Batch 0
Пилотот бил идентификуван како Сквадрон лидер Дилокрит Патаве.
Текст:The pilot was identified as Squadron Leader Dilokrit Pattavee.
Одговор (Македонски): Пилотот бил идентификуван како Сквадрон лидер Дилокрит Патаве.
Текст:The pilot was identified as Squadron Leader Dilokrit Pattavee.
Одговор (Македонски): Пилотот бил идентификуван како Сквадрон лидер Дилокрит Патаве.
Текст:The

Batch 0
Локалните медиуми известуваат дека возило за гаснење пожар во аеродром се превртело додека реагирало.
Текст:The company's annual revenue is estimated to be $100 million.
Одговор (Македонски): Проценетата годишна заработка на компанијата е 100 милиони долари.
Текст:The company's annual revenue is estimated to be $100 million.
Одговор (Македонски): Проценетата годишна заработка на компанијата

Batch 0
28-годишниот Видал се приклучи на Барселона пред три сезони, од Севиља.
  Пример 7
  Англиски: The company's annual report is a document that contains the company's financial statements and other information.
  Одговор (Македонски): Годишниот извештај на компанијата е документ кој содржи финансиски извештаи и други информации.
  Пример 8
  Англиски: The company's annual report is a document that contains the company's

Batch 0
Од појавувањето во каталонскиот главен град, Видал одиграл 49 натпревари за клубот.
  Пример 7
  Англиски: The company's products are sold in 100 countries around the world.
  Одговор (Македонски): Производите на компанијата се продаваат во 100 земји низ целиот свет.
  Пример 8
  Англиски: The company's products are sold in 100 countries around the world.
  Одговор

Batch 0
Протестот започна околу 11 часот по локално време (UTC+1) на Витезхајл спроти полицискиот обезбеден влез во Даунинг стрит, официјалната резиденција на премиерот.
  Пример 6
  Англиски: The first step in the process is to identify the problem.
  Одговор (Македонски): Првиот чекор во процесот е да се идентификува проблемот.
  Пример 7
  Англиски: The first step

Batch 8
Веднаш по 11 часот, демонстрантите го блокираа сообраќајот на северната линија во Вејтхол.
  Пример 2
  Англиски: The first time I saw her, I was so excited that I could hardly breathe.
  Одговор (Македонски): Првиот пат кога ја видов, бев толку возбуден што не можев да дишам.
  Пример 3
  Англиски: The first time I saw her, I was so excited that I could hardly breathe

Batch 8
Во 11:20 часот, полицијата ги замоли демонстрантите да се вратат на тротоарот, наведувајќи дека треба да се балансира правото на протест со сообраќајот кој се создава.
Текст:The police have been criticised for their use of force against the protesters.
Одговор (Македонски): Полицијата е критикувана за употребата на сила против демонстрантите.
Текст:The police have been criticised for their use of force against the protesters.
Одговор (Маке

Batch 8
Околу 11:29 часот, протестот се премести на улицата Вајтхол, покрај Трафалгар Сквер, по улицата Стринд, покрај Алдвич и по улицата Кингсвеј кон Холборн каде Конзервативната партија го одржуваше својот пролетен форум во хотелот Гранд Коннагт Румс.
  Пример 6
  Англиски: The first time I saw the film, I was very impressed by the special effects.

Batch 8
Рекордот на Надал во директните дуели со Канаѓанецот е 7–2.
Текст:The 2012 Summer Olympics were held in London, England.
Одговор (Македонски): Летните олимписки игри во 2012 година се одржаа во Лондон, Англија.
Текст:The 2012 Summer Olympics were held in London, England.
Одговор (Македонски): Летните олимписки игри во 2012 година се одржаа во

Batch 8
Тој неодамна загуби од Раониќ на Отвореното првенство во Бризбејн.
Текст:The company's products are sold in 100 countries.
Одговор (Македонски): Производите на компанијата се продаваат во 100 земји.
Текст:The company's products are sold in 100 countries.
Одговор (Македонски): Производите на компанијата се продаваат во 100 земји.
Текст:The company's products are sold in

Batch 8
Надал освои 88% од вкупните поени во натпреварот, освојувајќи 76 поени на првиот сервис.
  Пример 7
  Англиски: The company's annual report is a document that contains the company's financial statements and other information.
  Одговор (Македонски): Годишниот извештај на компанијата е документ кој содржи финансиски извештаи и други информации.
  Пример 8
  Англиски: The company

Batch 8
По натпреварот, Кралот на Каменот рече: "Само што сум возбуден што сум повторно во завршните кругови на најважните настани. Јас сум тука за да се обидам да го освојам овој турнир."
Текст:The first time I saw the movie, I was so excited that I couldn't stop thinking about it.
Одговор (Македонски): Првиот пат кога го видов филмот, бев толку возбуден што не можев да престанам да размислу

Batch 8
"Панама документи" е општ термин за приближно десет милиони документи од Панамската адвокатска фирма Мосак Фонсека, кои беа протечени во медиумите во пролетта 2016 година.
  Пример 7
  Англиски: The company's products are sold in over 100 countries.
  Одговор (Македонски): Производите на компанијата се продаваат во повеќе од 100 земји.
  Пример 8
  Англиски

Batch 16
Документите покажаа дека четиринаесет банки им помогнале на богатите клиенти да сокријат милијарди долари богатство за да избегнат плаќање даноци и други регулативи.
  Пример 7
  Англиски: The company's products are sold in over 100 countries.
  Одговор (Македонски): Производите на компанијата се продаваат во повеќе од 100 земји.
  Пример 8
  Англиски:

Batch 16
Британскиот весник "Гардијан" сугерираше дека "Дојче банк" контролира приближно една третина од 1200-те шпекулативни компании коишто беа користени за да се оствари ова.
  Пример 7
  Англиски: The company's products are sold in 100 countries and are used by 100 million people.
  Одговор (Македонски): Производите на компанијата се продаваат во 100 земји и

Batch 16
Имаше протести низ целиот свет, неколку кривични постапки и лидерите на владите на Исланд и Пакистан поднесоа оставки.
  Пример 7
  Англиски: The first time I saw the movie, I was very impressed by the acting of the main character.
  Одговор (Македонски): Првиот пат кога го видов филмот, бев многу импресиониран од глумата на главниот лик.
  Пример 8
  Англиски: The company

Batch 16
Роден во Хонг Конг, Ма студирал на Универзитетот во Њујорк и на Правниот факултет Харвард и некогаш поседувал американско постојано живеалиште "зелена карта".
  Пример 6
  Англиски: The company's products are sold in 100 countries and territories around the world.
  Одговор (Македонски): Производите на компанијата се продаваат во 100 земји и територии низ целиот свет.
  При

Batch 16
Хсиеј имплицираше за време на изборите дека Ма би можел да избега од земјата за време на криза.
Текст:The company's products are sold in 100 countries.
Одговор (Македонски): Производите на компанијата се продаваат во 100 земји.
Текст:The company's products are sold in 100 countries.
Одговор (Македонски): Производите на компанијата се продаваат во 100 земји.
Текст

Batch 16
Шиех исто така тврдеше дека фотогеничната Ма беше повеќе стил отколку суштина.
Текст:The first time I saw her, I was in love.
Одговор (Македонски):Првиот пат кога ја видов, бев вљубен.
Текст:The first time I saw her, I was in love.
Одговор (Македонски):Првиот пат кога ја видов, бев вљубен.
Текст:The first time I saw her, I was in love.

Batch 16
И покрај овие обвинувања, Ма победи убедливо на платформа која се залагаше за поблиски врски со кинескиот континент.
  Пример 7
  Англиски: The company's products are sold in 100 countries and territories around the world.
  Одговор (Македонски): Производите на компанијата се продаваат во 100 земји и територии низ целиот свет.
  Пример 8
  Англиски: The company's products are sold in 10

Batch 16
Денешниот играч на денот е Александар Овечкин од Вашингтон Капиталс.
  Пример 7
  Англиски: The first time I saw the movie, I was very impressed by the acting of the main character.
  Одговор (Македонски): Првиот пат кога го видов филмот, бев многу импресиониран од глумата на главниот лик.
  Пример 8
  Англиски: The main character in the movie is a young man who is a very

Batch 24
Тој имаше 2 гола и 2 асистенции во победата на Вашингтон од 5-3 над Атланта Трашрс.
Текст:The 2008 Summer Olympics were held in Beijing, China.
Одговор (Македонски): Летните олимписки игри во 2008 година се одржаа во Пекинг, Кина.
Текст:The 2008 Summer Olympics were held in Beijing, China.
Одговор (Македонски): Летните олимписки игри во

Batch 24
Првата асистенција на Овечкин во текот на ноќта беше на голот на дебитантот Никлас Бакстром кој го постигна победничкиот гол.
Текст:The first time I saw the movie, I was so excited that I couldn't stop laughing.
Одговор (Македонски): Првиот пат кога го видов филмот, бев толку возбуден што не можев да престанам да се смеам.
Текст:The first time I saw the movie, I was so excited

Batch 24
Неговиот втор гол во ноќта беше неговиот 60-ти гол во сезоната, станувајќи првиот играч кој постигнал 60 или повеќе голови во една сезона од 1995-96, кога Џаромир Јагр и Марио Лемеј постигнале по еден гол.
  Пример 6
  Англиски: The company's products are sold in over 100 countries.
  Одговор (Македонски): Производите

Batch 24
Батен бил рангиран на 190-то место на листата на 400 најбогати Американци во 2008 година со проценето богатство од 2,3 милијарди долари.
Текст:The 2008 United States presidential election was the 56th quadrennial presidential election in the United States.
Одговор (Македонски): Претседателските избори во САД во 2008 година беа 56-тите претседателски избори во САД.

Batch 24
Тој дипломирал на Факултетот за уметност и науки на Универзитетот во Вирџинија во 1950 година и бил значаен донатор на тој универзитет.
Текст:The first time I saw her, I was in love with her.
Одговор (Македонски): Првиот пат кога ја видов, бев вљубен во неа.
Текст:The first time I saw her, I was in love with her.
Одговор (Македонски): Пр

Batch 24
Пример 1
  Англиски: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
  Одговор (Македонски): Во понеделник, во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
  Пример 2
  Англиски: A sports match lasts 90 minutes, or two 4

Batch 24
Затворот стана познат по злоупотребата на затворениците откако американските сили го презедоа.
Текст:The jail became notorious after prisoner abuse was discovered there after US forces took over.
Одговор (Македонски): Затворот стана познат по злоупотребата на затворениците откако американските сили го презедоа.
Текст:The jail became notorious after prisoner abuse was discovered there after US forces took over.
Одговор (Македонски): Затворот стана познат по злоупотребата на

Batch 24
Пикетот се излизга во 2008 година во трката за Големата награда на Сингапур, само неколку минути по раната замена на болидот на Фернандо Алонсо, што предизвика излегување на безбедносното возило.
  Пример 6
  Англиски: The first time I saw the movie, I was very impressed by the acting of the main character.
  Одговор (Македонски): Првиот пат кога го видов филмот, бе

Batch 32
Додека возилата пред Алонсо влегуваа во боксот за гориво под безбедносното возило, тој се искачи напред во колоната за да го освои првото место.
Текст:The company's new product is a small, lightweight, and easy-to-use device that can be used to measure the speed of a car.
Одговор (Македонски):Новиот производ на компанијата е мал, лесен и лесен за употреба уред кој може да се користи за мерење на

Batch 32
Пикејт беше отпуштен по трката во Унгарија во 2009 година.
Текст:The 2010 FIFA World Cup Final was held at the Soccer City Stadium in Johannesburg, South Africa on 11 July 2010.
Одговор (Македонски): Финалниот натпревар на Светското првенство во фудбал 2010 година се одржа на стадионот Soccer City во Јоханесбург, Јужна Африка на 11 јули 2010

Batch 32
Во точно 8:46 часот, во градот настана тишина, означувајќи го точниот момент кога првиот авион ја погоди својата цел.
  Пример 7
  Англиски: The first time I saw her, I was in love with her.
  Одговор (Македонски): Првиот пат кога ја видов, бев вљубен во неа.
  Пример 8
  Англиски: The first time I saw her, I was in love with

Batch 32
Две зраци светлина се закачени да укажуваат кон небото преку ноќта.
Текст:The new study has been published in the journal "Nature".
Одговор (Македонски):Новата студија е објавена во списанието "Природа".
Текст:The new study has been published in the journal "Nature".
Одговор (Македонски):Новата студија е објавена во списанието "Природа".
Текст:The new study has been published in the journal "Nature".
Одговор (

Batch 32
Се гради за пет нови облакодери на локацијата, со транспортен центар и парк за спомени во средината.
  Пример 7
  Англиски: The new law will be enforced in the next few months.
  Одговор (Македонски): Новиот закон ќе стапи на сила во наредните неколку месеци.
  Пример 8
  Англиски: The new law will be enforced in the next few months.
  Одговор (Македонски): Новиот закон ќе ста

Batch 32
Еми наградите на оваа емисија се повеќе од дваесет и неколку, а нејзината емисија е покуса само од онаа на Сезам улицата и на Мистер Роџерс.
  Пример 2
  Англиски: The show has been nominated for 11 Emmy awards, and has won 10 of them.
  Одговор (Македонски): Еми наградите на оваа емисија се повеќе од дваесет и неколку, а нејзината емиси

Batch 32
Секоја епизода од серијата ќе се фокусира на една тема во одреден роман и потоа ќе ја истражува таа тема преку повеќе приказни.
Текст:The company's products are sold in over 100 countries.
Одговор (Македонски): Производите на компанијата се продаваат во повеќе од 100 земји.
Текст:The company's products are sold in over 100 countries.
Одговор (Македонски): Производи

Batch 32
Секоја емисија ќе содржи и препораки за книги кои децата треба да ги бараат кога ќе одат во својата библиотека.
Текст:The first time I saw the sea, I was in a boat.
Одговор (Македонски): Првиот пат кога го видов морето, бев во брод.
Текст:The first time I saw the sea, I was in a boat.
Одговор (Македонски): Првиот пат кога го видов морето, бев во

Batch 40
Џон Грант, од WNED Buffalo (домашниот станица на "Читањето Радува"), рече "Читањето Радува ги научи децата зошто да читаат, љубовта кон читањето — [емисијата] ги охрабри децата да земат книга и да читаат."
  Пример 6
  Англиски: The first time I saw a snake, I was scared.
  Одговор (Македонски): Првиот пат кога видов змија, бев исплашена

Batch 40
Некои, вклучувајќи го и Џон Грант, веруваат дека и финансиската криза и промената во филозофијата на едукативната телевизиска програма придонесоа за завршувањето на серијата.
  Пример 7
  Англиски: The first time I saw the movie, I was very impressed by the acting of the main character.
  Одговор (Македонски): Првиот пат кога го видов филмот, бев многу импре

Batch 40
Бурата, која се наоѓа околу 645 милји (1040 км) западно од Канарските острови, е веројатно дека ќе се распадне пред да загрози било кои копнени области, велат метеоролозите.
  Пример 1
  Англиски: The storm, situated about 645 miles (1040 km) west of the Cape Verde islands, is likely to dissipate before threatening any land areas, forecasters say.
  Одговор (Македонски

Batch 40
Фред во моментов има ветрови со брзина од 105 милји на час (165 км/ч) и се движи кон северозапад.
Текст:The new law will be enforced in the next few months.
Одговор (Македонски): Новиот закон ќе биде спроведен во наредните неколку месеци.
Текст:The new law will be enforced in the next few months.
Одговор (Македонски): Новиот закон ќе биде спроведен во наредните неколку месе

Batch 40
Фред е најсилниот тропски циклон кој некогаш бил регистриран толку јужно и источно во Атлантикот од појавата на сателитските снимки, и само третиот мајор ураган на евиденција источно од 35°W.
  Пример 6
  Англиски: The first time I saw a snake, I was scared.
  Одговор (Македонски): Првиот пат кога видов змија, бев исплашена.
  Пример 7

Batch 40
На 24 септември 1759 година, Артур Гиннес потпиша 9.000 годишен закуп за пиварницата Сент Џејмс Гејт во Даблин, Ирска.
  Пример 7
  Англиски: The first ever computer was invented in 1946 by the British computer scientist Alan Turing.
  Одговор (Македонски): Првиот компјутер воопшто бил измислен во 1946 година од британскиот компјутер

Batch 40
По 250 години, Џин-Џин еволуираше во глобална компанија која годишно остварува приход од 10 милијарди евра (14.7 милијарди долари).
  Пример 7
  Англиски: The company's products are sold in over 180 countries.
  Одговор (Македонски): Производите на компанијата се продаваат во повеќе од 180 земји.
  Пример 8
  Англиски

Batch 40
Џони Рајд, ко-возач на тимот за А1ГП Нов Зеланд, денес направи историја со тоа што возеше најбрзо преку 48-годишниот мост на пристаништето во Оукланд, Нов Зеланд, легално.
  Пример 7
  Англиски: The new system will be able to detect and identify the type of the disease.
  Одговор (Македонски): Новиот систем ќе биде во состојба да открие и идентифику

Batch 48
Г-дин Рајд успеа да вози со брзина од 160км/ч седум пати над мостот.
  Пример 6
  Англиски: The first time I went to the cinema, I was so excited that I forgot to take my seat.
  Одговор (Македонски): Првиот пат кога отидов во кино, бев толку возбуден што заборавав да земам седиште.
  Пример 7
  Англиски: The first time I went to the cinema

Batch 48
Полицијата на Нов Зеланд имаше проблем да го користи радарот за брзина за да види колку брзо се движел г-дин Рајд поради тоа што коњот е многу низок, и единствено време кога полицијата успеа да го измери брзината на г-дин Рајд беше кога тој забави на 160 км/ч.
  Пример 6
  Англиски: The police have been able to use the speed radar guns to see how fast Mr Reid was going because

Batch 48
Во последните 3 месеци, над 80 приведени беа пуштени од Централната канцеларија за притвор без да бидат официјално обвинети.
Текст:The new law will be implemented in the next 3 months.
Одговор (Македонски): Новиот закон ќе биде имплементиран во наредните 3 месеци.
Текст:The new law will be implemented in the next 3 months.
Одговор (Македонски): Новиот закон ќе биде имплементиран во

Batch 48
Во април оваа година, привремена забрана за задржување беше издадена од судијата Глин против објектот да се спроведе ослободувањето на оние кои се држени повеќе од 24 часа по нивното примање кои не добиле сослушување од судијата комесар.
Текст:The new system will be able to identify and track the movement of the animals, and will be able to detect any suspicious activity.
Одговор (Македонски): Новиот систем

Batch 48
Комисионерот поставува кауција, ако е одобрена, и ги формализира обвиненијата поднесени од страна на полицаецот кој го приведува.
Обвиненијата потоа се внесуваат во компјутерскиот систем на државата каде што случајот се следи.

In [30]:
predictions_new = [first_sentence(text) for text in predictions_mkd]
predictions_new

['Во понеделник, научници од Станфордската школа за медицина објавија дека е откриен нов дијагностички алат кој може да ги подредува клетките по тип: мал печатач кој може да се произведува со стандардни инкџет принтери за можеби околу еден долар по парче.',
 'Истражувачите велат дека ова може да доведе до рана дијагноза на рак, туберкулоза, ХИВ и маларија кај пациенти во земјите со низок приход, каде што стапката на преживување на болести како што се ракот на дојка може да биде половина од онаа на побогатите земји.',
 'Авионот JAS 39C Gripen се урна на пистата околу 9:30 часот по локално време (0230 UTC) и експлодираше, затворајќи го аеродромот за комерцијални летови.',
 'Пилотот бил идентификуван како Сквадрон лидер Дилокрит Патаве.',
 'Локалните медиуми известуваат дека возило за гаснење пожар во аеродром се превртело додека реагирало.',
 '28-годишниот Видал се приклучи на Барселона пред три сезони, од Севиља.',
 'Од појавувањето во каталонскиот главен град, Видал одиграл 49 натпревари за клубот.',
 'Протестот започна околу 11 часот по локално време (UTC+1) на Витезхајл спроти полицискиот обезбеден влез во Даунинг стрит, официјалната резиденција на премиерот.',
 'Веднаш по 11 часот, демонстрантите го блокираа сообраќајот на северната линија во Вејтхол.',
 'Во 11:20 часот, полицијата ги замоли демонстрантите да се вратат на тротоарот, наведувајќи дека треба да се балансира правото на протест со сообраќајот кој се создава.',
 'Околу 11:29 часот, протестот се премести на улицата Вајтхол, покрај Трафалгар Сквер, по улицата Стринд, покрај Алдвич и по улицата Кингсвеј кон Холборн каде Конзервативната партија го одржуваше својот пролетен форум во хотелот Гранд Коннагт Румс.',
 'Рекордот на Надал во директните дуели со Канаѓанецот е 7–2.',
 'Тој неодамна загуби од Раониќ на Отвореното првенство во Бризбејн.',
 'Надал освои 88% од вкупните поени во натпреварот, освојувајќи 76 поени на првиот сервис.',
 'По натпреварот, Кралот на Каменот рече: "Само што сум возбуден што сум повторно во завршните кругови на најважните настани.',
 '"Панама документи" е општ термин за приближно десет милиони документи од Панамската адвокатска фирма Мосак Фонсека, кои беа протечени во медиумите во пролетта 2016 година.',
 'Документите покажаа дека четиринаесет банки им помогнале на богатите клиенти да сокријат милијарди долари богатство за да избегнат плаќање даноци и други регулативи.',
 'Британскиот весник "Гардијан" сугерираше дека "Дојче банк" контролира приближно една третина од 1200-те шпекулативни компании коишто беа користени за да се оствари ова.',
 'Имаше протести низ целиот свет, неколку кривични постапки и лидерите на владите на Исланд и Пакистан поднесоа оставки.',
 'Роден во Хонг Конг, Ма студирал на Универзитетот во Њујорк и на Правниот факултет Харвард и некогаш поседувал американско постојано живеалиште "зелена карта".',
 'Хсиеј имплицираше за време на изборите дека Ма би можел да избега од земјата за време на криза.',
 'Шиех исто така тврдеше дека фотогеничната Ма беше повеќе стил отколку суштина.',
 'И покрај овие обвинувања, Ма победи убедливо на платформа која се залагаше за поблиски врски со кинескиот континент.',
 'Денешниот играч на денот е Александар Овечкин од Вашингтон Капиталс.',
 'Тој имаше 2 гола и 2 асистенции во победата на Вашингтон од 5-3 над Атланта Трашрс.',
 'Првата асистенција на Овечкин во текот на ноќта беше на голот на дебитантот Никлас Бакстром кој го постигна победничкиот гол.',
 'Неговиот втор гол во ноќта беше неговиот 60-ти гол во сезоната, станувајќи првиот играч кој постигнал 60 или повеќе голови во една сезона од 1995-96, кога Џаромир Јагр и Марио Лемеј постигнале по еден гол.',
 'Батен бил рангиран на 190-то место на листата на 400 најбогати Американци во 2008 година со проценето богатство од 2,3 милијарди долари.',
 'Тој дипломирал на Факултетот за уметност и науки на Универзитетот во Вирџинија во 1950 година и бил значаен донатор на тој универзитет.',
 "Пример 1\n  Англиски: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.",
 'Затворот стана познат по злоупотребата на затворениците откако американските сили го презедоа.',
 'Пикетот се излизга во 2008 година во трката за Големата награда на Сингапур, само неколку минути по раната замена на болидот на Фернандо Алонсо, што предизвика излегување на безбедносното возило.',
 'Додека возилата пред Алонсо влегуваа во боксот за гориво под безбедносното возило, тој се искачи напред во колоната за да го освои првото место.',
 'Пикејт беше отпуштен по трката во Унгарија во 2009 година.',
 'Во точно 8:46 часот, во градот настана тишина, означувајќи го точниот момент кога првиот авион ја погоди својата цел.',
 'Две зраци светлина се закачени да укажуваат кон небото преку ноќта.',
 'Се гради за пет нови облакодери на локацијата, со транспортен центар и парк за спомени во средината.',
 'Еми наградите на оваа емисија се повеќе од дваесет и неколку, а нејзината емисија е покуса само од онаа на Сезам улицата и на Мистер Роџерс.',
 'Секоја епизода од серијата ќе се фокусира на една тема во одреден роман и потоа ќе ја истражува таа тема преку повеќе приказни.',
 'Секоја емисија ќе содржи и препораки за книги кои децата треба да ги бараат кога ќе одат во својата библиотека.',
 'Џон Грант, од WNED Buffalo (домашниот станица на "Читањето Радува"), рече "Читањето Радува ги научи децата зошто да читаат, љубовта кон читањето — [емисијата] ги охрабри децата да земат книга и да читаат."',
 'Некои, вклучувајќи го и Џон Грант, веруваат дека и финансиската криза и промената во филозофијата на едукативната телевизиска програма придонесоа за завршувањето на серијата.',
 'Бурата, која се наоѓа околу 645 милји (1040 км) западно од Канарските острови, е веројатно дека ќе се распадне пред да загрози било кои копнени области, велат метеоролозите.',
 'Фред во моментов има ветрови со брзина од 105 милји на час (165 км/ч) и се движи кон северозапад.',
 'Фред е најсилниот тропски циклон кој некогаш бил регистриран толку јужно и источно во Атлантикот од појавата на сателитските снимки, и само третиот мајор ураган на евиденција источно од 35°W.',
 'На 24 септември 1759 година, Артур Гиннес потпиша 9.000 годишен закуп за пиварницата Сент Џејмс Гејт во Даблин, Ирска.',
 'По 250 години, Џин-Џин еволуираше во глобална компанија која годишно остварува приход од 10 милијарди евра (14.7 милијарди долари).',
 'Џони Рајд, ко-возач на тимот за А1ГП Нов Зеланд, денес направи историја со тоа што возеше најбрзо преку 48-годишниот мост на пристаништето во Оукланд, Нов Зеланд, легално.',
 'Г-дин Рајд успеа да вози со брзина од 160км/ч седум пати над мостот.',
 'Полицијата на Нов Зеланд имаше проблем да го користи радарот за брзина за да види колку брзо се движел г-дин Рајд поради тоа што коњот е многу низок, и единствено време кога полицијата успеа да го измери брзината на г-дин Рајд беше кога тој забави на 160 км/ч.',
 'Во последните 3 месеци, над 80 приведени беа пуштени од Централната канцеларија за притвор без да бидат официјално обвинети.',
 'Во април оваа година, привремена забрана за задржување беше издадена од судијата Глин против објектот да се спроведе ослободувањето на оние кои се држени повеќе од 24 часа по нивното примање кои не добиле сослушување од судијата комесар.',
 'Комисионерот поставува кауција, ако е одобрена, и ги формализира обвиненијата поднесени од страна на полицаецот кој го приведува.',
 'Судењето исто така го означува датумот за правото на обвинетиот на брзо судење.',
 'Петеро Костело, австралискиот министер за финансии и човекот кој најверојатно ќе го наследи премиерот Џон Ховард како лидер на Либералната партија, ја поддржува индустријата за нуклеарна енергија во Австралија.',
 'Г-дин Костело изјави дека кога нуклеарната енергија ќе стане економски исплатлива, Австралија треба да ја истражи нејзината употреба.',
 '"Ако стане комерцијално, треба да го имаме.',
 'Според АНСА, "полицијата беше загрижена од неколкуте напади на врвот кои ги сметаа за закана од почеток на војна за наследување."',
 'Полицијата изјави дека Ло Пиколо имал предност бидејќи бил десна рака на Провензуро во Палермо и неговото поголемо искуство го добило почитта на постарите шефови додека го следеле Провензуровиот план да останат што е можно пониски додека ја зајакнуваат својата мрежа на моќ.',
 'Овие шефови биле потиснати од Провенцо кога тој го заврши војната против државата што ја водеше Риина, која траеше од 1992 година и чии жртви беа мафијашките поборници Џовани Фалонче и Паоло Борселино.',
 'Apple CEO Steve Jobs unveiled the device by walking onto the stage and taking the iPhone out of his jeans pocket.',
 'За време на неговиот 2 часовен говор тој изјави дека "Денес Apple ќе го реинвентира телефонот, ќе направиме историја денес".',
 'Бразил е најголемата католичка земја на Земјата, а Римокатоличката црква постојано се противи на легализацијата на истополовите бракови во земјата.',
 'Националниот Конгрес на Бразил дебатира за легализација на истополовите бракови веќе 10 години, а такви цивилни бракови во моментов се легални само во Рио Гранде до Сул.',
 'Оригиналниот предлог-закон бил изработен од поранешниот градоначалник на Сао Паоло, Марта Суплици.',
 'Протестантите се надеваат дека ќе соберат петиција со 1.2 милиони потписи за да ја достават до Националниот Конгрес во ноември.',
 'Потоа кога стана јасно дека многу семејства бараат правна помош за да се борат против евакуациите, на 20-ти март се одржа средба во East Bay Community Law Center за жртвите на измамата со домувањето.',
 'Кога станарите почнаа да споделуваат што им се случило, повеќето од семејствата вклучени одеднаш сфатија дека Каролин Вилсон од ОХА ги украла нивните депозити и избегала од градот.',
 'Станарите на Локвуд Гарденс веруваат дека можеби има уште 40 семејства или повеќе кои ќе се соочат со протерување, откако дознаа дека полицијата на ОХА ги истражува и другите јавни згради за домување во Оукланд кои можеби се вклучени во измамата со домувањето.',
 'Бендот го откажа концертот во стадионот на Мауи, кој требаше да биде посетен од 9.000 луѓе, и се извини на фановите.',
 'Управувачката компанија на бендот, HK Management Inc., не даде првична причина кога го откажаа на 20-ти септември, но следниот ден ги обвинија логистичките причини.',
 'Познатите грчки адвокати, Сакис Кечагиоглу и Џорџ Николоакопулос, биле затворени во затворот во Атина, Коридаллос, бидејќи биле прогласени за виновни за корупција и корупција.',
 'Како резултат на тоа, е подигната голема скандал во грчката правна заедница преку откривањето на незаконски дејствија што судиите, адвокатите, адвокатите и адвокатите ги направиле во текот на претходните години.',
 'Пред неколку недели, по објавената информација од новинарот Макис Триантафилопулос во неговата популарна телевизиска емисија "Зоунгла" на Алфа ТВ, пратеникот и адвокат, Петрос Мантоувалос беше сменет од функцијата, бидејќи неговите соработници биле вклучени во нелегална корупција и корупција.',
 'Покрај тоа, највисокиот судија Евангелос Калусис е затворен бидејќи е осуден за корупција и девијантно однесување.',
 'Робертс цврсто одби да каже кога тој верува дека животот започнува, важно прашање кога се разгледуваат етичките прашања поврзани со абортусот, велејќи дека би било нечесно да се коментира за конкретните случаи кои би можеле да се случат.',
 'Сепак, тој повторно ја истакна својата претходна изјава дека Ро против Вејд е "законот што е воспоставен во земјата", нагласувајќи ја важноста на конзистентните одлуки на Врховниот суд.',
 'Тој исто така потврди дека верува во имплицираното право на приватност кое зависеше од одлуката на Ро.',
 'Марјучидор имаше завршено на врвот на табелата, шест поени пред Носа на второто место.',
 'Двете страни ќе се сретнат во големото полуфинале каде што Носа излезе како победник со 11 поени.',
 'Марјучидорден потоа го победи Кабултуре во Полуфиналната завршница.',
 'Хесперонохикус елизабета е вид од фамилијата Дромаесаурид и е роднина на Велоцираптор.',
 'Ова целосно пердувести, топлокрвни предатори кои летаат беа верувани дека одеа исправено на две нозе со канџи како кај Velociraptor.',
 'Неговиот втор прст беше поголем, што доведе до името Хесперонохикус, што значи "западен прст".',
 'Покрај топењето на мразот, екстремните временски услови го отежнуваат спасувањето.',
 'Питиман предложи дека условите нема да се подобрат до некое време следната недела.',
 'Според Питман, количината и дебелината на мразниот пакет, според Питман, е најлоша во изминатите 15 години за селерите.',
 'Веста се прошири во заедницата на Црвеното езеро денес, бидејќи се одржаа погреби за Џеф Вејс и тројца од деветте жртви, додека друг ученик беше уапсен во врска со пукањето во училиштето на 21 март.',
 'Официјално, властите потврдија дека денес е уапсен.',
 'Сепак, извор кој е запознаен со истрагата, за Minneapolis Star-Tribune изјави дека тоа бил Луис Џордан, 16-годишниот син на претседателот на племето Ред Лејк Флод Џордан.',
 'Не е познато во овој момент кои обвиненија ќе бидат поднесени или што ги довело властите до момчето, но почнати се постапките во федералниот суд.',
 'Исто така, официјалните лица одлучија да го откажат вториот круг од изборите за да ги заштедат Авганистанците од трошоците и безбедносните ризици на уште еден изборен процес.',
 'Дипломатите изјавија дека пронашле доволно двосмисленост во авганистанскиот устав за да го утврдат вториот круг како непотребен.',
 'Ова се спротивставува на претходните извештаи, кои велеа дека откажувањето на вториот круг би било против уставот.',
 'Авионот бил на пат за Иркутск и бил управуван од внатрешни единици.',
 'Се формираше истражна комисија за да истражи.',
 'Ил-76 е главен дел од руската и советската војска од 1970-тите, а веќе имаше сериозна несреќа во Русија минатиот месец.',
 'На 7-ми октомври, при полетување, еден мотор се одвоил без да има повредени.',
 '800 милји од Транс-Аљаска Пипелината беа затворени по истекување на неколку илјади барели нафта јужно од Фарбој, Аљаска.',
 'Поради редовен тест на системот за команда при пожар, дошло до прекин на струјата, што предизвикало отворање на вентилите за ослободување притисок и нафтата се излеала во близина на пумпната станица 9.']

In [31]:
references = [[ref] for ref in text_mkd]
references[:10]

[['Во понеделникот научниците од медицинскиот факултет на Универзитетот Стенфорд објавија дека измислиле нова алатка за дијагностицирање со којашто се подредуваат клетките според типови: се работи за мал чип за печатење кој може да се произведе со помош на стандардни инк-џет печатачи, и тоа по цена од околу еден американски цент.'],
 ['Водечките истражувачи сметаат дека ова може да доведе до рано откривање на рак, туберколоза, ХИВ и маларија кај пациенти кои живеат во земји со низок животен стандард, каде стапката на преживување од болести како рак на дојка може да биде двојно пониска отколку во побогатите држави.'],
 ['JAS 39C Грипен се сруши на писта околу 9:30 am по локално време (2:30 UTC) и експлодираше, поради што аеродромот е затворен за комерцијални летови.'],
 ['Утврдено е дека пилот бил Дилокрит Патави, водачот на ескадрилата.'],
 ['Локалните медиуми известуваат за аеродромско противпожарно возило кое се превртело додека пожарникарите во него одговарале на повик.'],
 ['28-годишниот Видал од Севиља се придружи на екипата на Барселона.'],
 ['Откако се пресели во главниот град на Каталонија Видал одигра 49 натпревари за клубот.'],
 ['Протестот започна околу 11:00 часот по локално време (UTC+1) во Вајтхол, на спротивната страна од влезот чуван од полицијата на Даунинг Стрит, службената резиденција на премиерот.'],
 ['Веднаш по 11:00 часот демонстрантите го блокираа сообраќајот кон север во Вајтхол.'],
 ['Во 11:20 часот, полицијата побара од протестантите да повлечат на тротоарот, наведувајќи дека тие треба да ги урамнотежат правото на протестирање со застојот во сообраќајот.']]

In [32]:
bleu.compute(predictions=predictions_new, references=references)

{'bleu': 0.2671029808616829,
 'precisions': [0.5847977114834492,
  0.3302087771623349,
  0.21495327102803738,
  0.1425244527247322],
 'brevity_penalty': 0.9631009368981077,
 'length_ratio': 0.9637652619141395,
 'translation_length': 2447,
 'reference_length': 2539}

In [33]:
chrf_score = sacrebleu.corpus_chrf(predictions_new, references)
print(f"chrF: {chrf_score.score:.2f}")

chrF: 44.38

## Few-Shot Cross-lingual prompt (ENG->MKD) in serbian language

In [36]:
instruction = f"""Преведи следећи текст са **Eнглеског** на **Mакедонски** језик.
Само испиши превод на македонски језик. Не додавај никаква објашњења или додатне примере.

Пример 1
Енглески: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Одговор (Mакедонски): Во понеделник, во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.

Пример 2
Енглески: A sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.
Одговор (Mакедонски): Еден спортски натпревар трае 90 минути, односно две полувремиња по 45 минути со одмор помеѓу нив во траење од 15 минути. Ако има подолги прекини во играта, таа се продолжува така што се надополнува изгубеното време.

Пример 3
Енглески: With the help of this tool, cells can be sorted by type, which means that diseases caused by small cells can be diagnosed.
Одговор (Mакедонски): Со помош на оваа алатка, клетките можат да се подредуваат по тип, што значи дека можат да се дијагностицираат болести предизвикани од мали клетки.

Пример 4
Енглески: This study focuses on the development of new methods for data analysis.
Одговор (Mакедонски): Оваа студија се фокусира на развојот на нови методи за анализа на податоци.

Пример 5
Енглески: In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
Одговор (Mакедонски): Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.
"""

In [38]:
predictions_mkd = batch_translate(text_eng,instruction,max_new_tokens=128,lang_code="srb",language="Македонски")

Batch 0
Во понеделник, научници од Станфордската школа за медицина објавија дека е измислена нова дијагностичка алатка која ги подредува клетките по тип: мала печатена чипче која може да се произведува со стандардни инкџет принтери за можни околу еден долар по парче.
Пример 1
Енглески: The new device is a small, portable, and easy-to-use device that can be used to measure the speed of a car.
Одговор (Mакедон

Batch 0
Истражувачите велат дека ова може да доведе до рана дијагноза на рак, туберкулоза, ХИВ и маларија кај пациенти во земјите со низок приход, каде што стапката на преживување на болести како што се ракот на дојка може да биде половина од онаа на побогатите земји.
Текст:The researchers say that the new method could be used to identify the most effective treatments for diseases such as cancer, tuberculosis, HIV and malaria.
Одговор (Ма

Batch 0
ЈАС 39Ц Грипен се урна на писта во 9:30 часот по локално време (02:30 UTC) и експлодираше, затворајќи го аеродромот за комерцијални летови.
Текст:The JAS 39C Gripen crashed onto a runway at around 9:30 am local time (0230 UTC) and exploded, closing the airport to commercial flights.
Одговор (Македонски): ЈАС 39Ц Грипен се урна на писта во 9

Batch 0
Пилотот бил идентитефикуван како Сквадрон лидер Дилокрит Патаве.
Текст:The pilot was identified as Squadron Leader Dilokrit Pattavee.
Одговор (Македонски): Пилотот бил идентитефикуван како Сквадрон лидер Дилокрит Патаве.
Текст:The pilot was identified as Squadron Leader Dilokrit Pattavee.
Одговор (Македонски): Пилотот бил идентитефикуван како Сквадрон лидер Дилокрит Патаве.
Текст:The

Batch 0
Локалните медиуми известуваат дека возило за гаснење пожар на аеродром се превртело додека реагирало.
Текст:The company's annual revenue is estimated at $100 million.
Одговор (Македонски): Проценетата годишна заработка на компанијата е 100 милиони долари.
Текст:The company's annual revenue is estimated at $100 million.
Одговор (Македонски): Проценетата годишна заработка на компанијата е

Batch 0
28-годишниот Видал се приклучи на Барселона пред три сезони, од Севиља.
Текст:The new technology is expected to be available in the market in 2019.
Одговор (Mакедонски): Новата технологија се очекува да биде достапна на пазарот во 2019 година.
Текст:The new technology is expected to be available in the market in 2019.
Одговор (Mакедонски): Новата технологија се очекува да биде

Batch 0
Од преселувањето во каталонскиот главен град, Видал одиграл 49 натпревари за клубот.
Текст:The company's products are sold in 100 countries.
Одговор (Македонски): Производите на компанијата се продаваат во 100 земји.
Текст:The company's products are sold in 100 countries.
Одговор (Македонски): Производите на компанијата се продаваат во 100 земји.
Текст:The

Batch 0
Протестот започна околу 11 часот по локално време (UTC+1) на Витезхајл спроти полицискиот обезбеден влез во Даунинг стрит, официјалната резиденција на премиерот.
Текст:The first step in the process of making a new drug is to identify a target molecule.
Одговор (Македонски): Првиот чекор во процесот на правење на нов лек е да се идентификува молекула на цел.
Текст:The new method is based

Batch 8
Веднаш по 11 часот, демонстрантите го блокираа сообраќајот на северната линија во Вејтхол.
Текст:The new law will be enforced by the police, who will be able to fine people who do not wear a mask.
Одговор (Mакедонски): Новиот закон ќе го спроведува полицијата, која ќе може да ги казнува луѓето кои не носат маска.
Текст:The new law will be enforced by the police, who will be able to fine people

Batch 8
Во 11:20 часот, полицијата ги замоли демонстрантите да се вратат на тротоарот, наведувајќи дека им е потребно да го балансираат правото на протест со сообраќајот кој се насобрал.
Текст:The first time I saw her, I was in love with her.
Одговор (Македонски): Првиот пат кога ја видов, бев вљубен во неа.
Текст:The first time I saw her, I was in love with her

Batch 8
Околу 11:29 часот, протестот се премести на улицата Вајтхол, покрај Трафалгар Сквер, по улицата Стринд, покрај Алдвич и по улицата Кингсвеј кон Холборн каде Конзервативната партија го одржуваше својот пролетен форум во хотелот Гранд Коннагт Румс.
Пример 1
Енглески: The first time I saw her, I was in love with her.
Одговор (M

Batch 8
Рекордот на Надал во директните дуели со Канаѓанецот е 7–2.
Текст:The 2012 Summer Olympics were held in London, England.
Одговор (Македонски): Летните олимписки игри во 2012 година се одржаа во Лондон, Англија.
Текст:The 2012 Summer Olympics were held in London, England.
Одговор (Македонски): Летните олимписки игри во 2012 година се одржаа во

Batch 8
Тој неодамна загуби од Раониќ на Отвореното првенство во Бризбејн.
Текст:The company's products are sold in 100 countries.
Одговор (Македонски): Производите на компанијата се продаваат во 100 земји.
Текст:The company's products are sold in 100 countries.
Одговор (Македонски): Производите на компанијата се продаваат во 100 земји.
Текст:The company's products are sold in

Batch 8
Надал освои 88% од вкупните поени во натпреварот, освојувајќи 76 поени на првиот сервис.
Текст:The new technology is expected to be available in the market in 2020.
Одговор (Македонски): Новата технологија се очекува да биде достапна на пазарот во 2020 година.
Текст:The new technology is expected to be available in the market in 2020.
Одговор (Македонски):

Batch 8
По натпреварот, Кралот на глина рече: "Само сум возбуден што сум повторно во завршните кругови на најважните настани. Тука сум за да се обидам да го освојам овој турнир."
Текст:The first time I saw her, I was in love with her.
Одговор (Македонски): Првиот пат кога ја видов, бев вљубен во неа.
Текст:The first time I saw her, I was in love with her.
Одговор (Маке

Batch 8
"Панама документи" е општ термин за приближно десет милиони документи од Панамската адвокатска фирма Мосак Фонсека, кои беа протечени во медиумите во пролетта 2016 година.
Пример 1
Енглески: The company's products are sold in over 100 countries.
Одговор (Mакедонски): Производите на компанијата се продаваат во повеќе од 100 земји.
Пример 2
Енглески: The company'

Batch 16
Документите покажаа дека четиринаесет банки им помогнале на богатите клиенти да сокријат милијарди долари богатство за да избегнат данок и други регулативи.
Текст:The new technology is expected to be available in the market in 2020.
Одговор (Mакедонски): Новата технологија се очекува да биде достапна на пазарот во 2020 година.
Текст:The new technology is expected to be available in the market in 2020

Batch 16
Британскиот весник "Гардијан" сугерираше дека "Дојче банк" контролира приближно една третина од 1200-те шпекулативни компании коишто се користени за да се оствари ова.
Текст:The company's shares are traded on the Frankfurt Stock Exchange.
Одговор (Македонски): Акциите на компанијата се тргуваат на берзата во Франкфурт.
Текст:The company's shares are traded on the Frankfurt Stock Exchange.

Batch 16
Имаше протести низ целиот свет, неколку кривични постапки и лидерите на владите на Исланд и Пакистан поднесоа оставки.
Текст:The first time I saw the movie, I was so excited that I couldn't stop thinking about it.
Одговор (Македонски): Првиот пат кога го видов филмот, бев толку возбуден што не можев да престанам да размислувам за него.
Текст:The first time I saw the movie, I was so excited that I couldn'

Batch 16
Роден во Хонг Конг, Ма студирал на Универзитетот во Њујорк и на Правниот факултет Харвард и некогаш поседувал американско постојано живеалиште "зелена карта".
Текст:The first time I saw the film, I was so moved that I cried.
Одговор (Македонски): Првиот пат кога го видов филмот, бев толку трогнат што заплакав.
Текст:The first time I saw the film, I was so moved that

Batch 16
Хсиеј имплицираше за време на изборите дека Ма би можел да избега од земјата за време на криза.
Текст:The company's products are sold in 100 countries and territories around the world.
Одговор (Македонски): Производите на компанијата се продаваат во 100 земји и територии низ целиот свет.
Текст:The company's products are sold in 100 countries and territories around the world.
Одговор (Македонски): Производите на компа

Batch 16
Хсиех исто така тврдеше дека фотогеничната Ма беше повеќе стил отколку суштина.
Текст:The first step in the process is to create a mold of the object.
Одговор (Македонски): Првиот чекор во процесот е да се создаде калап на објектот.
Текст:The first step in the process is to create a mold of the object.
Одговор (Македонски): Првиот чекор во процесот е да се создаде калап на об

Batch 16
И покрај овие обвинувања, Ма победи убедливо на платформа која се залагаше за поблиски врски со кинескиот континент.
Текст:The company's products are sold in 100 countries and territories around the world.
Одговор (Македонски): Производите на компанијата се продаваат во 100 земји и територии ширум светот.
Текст:The company's products are sold in 100 countries and territories around the world.
Одговор (Македонски): Произ

Batch 16
Денешниот играч на денот е Алекс Овечкин од Вашингтон Капиталс.
Текст:The first time I met him, he was very shy and reserved.
Одговор (Mакедонски): Првиот пат кога го сретнав, тој беше многу срамежлив и резервиран.
Текст:The first time I met him, he was very shy and reserved.
Одговор (Mакедонски): Првиот пат кога го сретнав, тој беше многу срамежлив

Batch 24
Тој имаше 2 гола и 2 асистенции во победата на Вашингтон од 5-3 над Атланта Трашрс.
Текст:The 2008 Summer Olympics were held in Beijing, China.
Одговор (Македонски): Летните олимписки игри во 2008 година се одржаа во Пекинг, Кина.
Текст:The 2008 Summer Olympics were held in Beijing, China.
Одговор (Македонски): Летните олимписки игри во

Batch 24
Првата асистенција на Овечкин во текот на ноќта беше на победничкиот гол на дебитантот Никлас Бакстром;
Текст:The first time I saw him, I was in love with him.
Одговор (Македонски): Првиот пат кога го видов, бев вљубена во него.
Текст:The first time I saw him, I was in love with him.
Одговор (Македонски): Првиот пат кога го видов, бев вљубе

Batch 24
Неговиот втор гол на вечерта беше неговиот 60-ти гол во сезоната, станувајќи првиот играч кој постигнал 60 или повеќе голови во една сезона од 1995-96, кога Џаромир Јагр и Марио Лемеј постигнаа таков подвиг.
Текст:The new system is designed to help the government to identify and track down the people who are responsible for the illegal activities.
Одговор (Македонски): Новиот систем е диза

Batch 24
Батен беше рангиран на 190-то место на листата на 400 најбогати Американци во 2008 година со проценето богатство од 2,3 милијарди долари.
Текст:The 2008 United States presidential election was the 56th quadrennial presidential election in the United States.
Одговор (Македонски): Претседателските избори во САД во 2008 година беа 56-ти избори за претседател на САД во

Batch 24
Тој дипломирал на Факултетот за уметности и науки на Универзитетот во Вирџинија во 1950 година и бил значаен донатор на тој универзитет.
Текст:The first time I saw her, I knew she was the one.
Одговор (Македонски): Првиот пат кога ја видов, знаев дека таа е вистинската.
Текст:The first time I saw her, I knew she was the one.
Одговор (Македонски): П

Batch 24
Пример 1
Енглески: The Prime Minister of the United Kingdom and the Chancellor of Germany have scheduled a meeting for Monday at 11 o'clock to discuss economic issues.
Одговор (Mакедонски):
Пример 2
Енглески: A sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.
Одговор (Mакедонски):
Пример 3
Енг

Batch 24
Затворот стана познат по злоупотребата на затворениците откако американските сили го презедоа.
Текст:The first time I saw her, I was in love with her.
Одговор (Македонски): Првиот пат кога ја видов, бев вљубен во неа.
Текст:The first time I saw her, I was in love with her.
Одговор (Македонски): Првиот пат кога ја видов, бев вљубен во неа.
Текст:The first time I

Batch 24
Пикетот на Џр.
излета во 2008 година на Гран при во Сингапур, само неколку минути по раната пит-стоп за Фернандо Алонсо, што предизвика излегување на безбедносните возила.
Текст:The 2010 FIFA World Cup Final was held at the Soccer City Stadium in Johannesburg, South Africa on 11 July 2010.
Одговор (Македонски): Финалниот натпревар на Светското првенство

Batch 32
Кога возачите пред Алонсо влегоа во боксот за промена на гуми, тој се искачи на првото место и победи.
Текст:The company's new product is a small, lightweight, and easy-to-use device that can be used to measure the speed of a car.
Одговор (Македонски): Новиот производ на компанијата е мал, лесен и лесен за употреба уред кој може да се користи за мерење на брзината на автомобилот.
Текст:The company's

Batch 32
Пикејт беше отпуштен по трката во Унгарија во 2009 година.
Текст:The 2010 FIFA World Cup Final was held at the Soccer City Stadium in Johannesburg, South Africa.
Одговор (Македонски): Финалниот натпревар на Светското првенство во фудбал во 2010 година се одржа на стадионот Soccer City во Јоханесбург, Јужна Африка.
Текст:The 2010 FIFA World Cup Final was held at the Soccer

Batch 32
Во точно 8:46 часот, во градот настана тишина, означувајќи го точниот момент кога првиот авион го погоди својот цел.
Пример 1
Енглески: The first jet struck its target at exactly 8:46 a.m.
Одговор (Mакедонски): Првиот авион го погоди својот цел во точно 8:46 часот.
Пример 2
Енглески: The first jet struck its target at

Batch 32
Две зраци светлина се закачени да укажуваат кон небото преку ноќта.
Текст:The new study has been published in the journal "Nature".
Одговор (Македонски): Новата студија е објавена во списанието "Природа".
Текст:The new study has been published in the journal "Nature".
Одговор (Македонски): Новата студија е објавена во списанието "Природа".
Текст:The new study has been published in the journal "Nature".
Одговор (

Batch 32
Се гради за пет нови облакодери на локацијата, со транспортен центар и парк за сеќавање во средината.
Текст:The company's products are sold in over 100 countries around the world.
Одговор (Mакедонски): Производите на компанијата се продаваат во повеќе од 100 земји низ целиот свет.
Текст:The company's products are sold in over 100 countries around the world.
Одговор (Mакедонски): Производите на компа

Batch 32
Еми наградите на оваа емисија се повеќе од дваесет и неколку, а нејзината емисија е покуса само од онаа на Сезам улицата и на Мистер Роџерс.
Текст:The first time I saw the movie, I was so excited that I couldn't stop thinking about it.
Одговор (Mакедонски): Првиот пат кога го видов филмот, бев толку возбуден што не можев да престанам да мислам на него.
Текст:The

Batch 32
Секоја епизода од серијата ќе се фокусира на една тема во одредена книга и потоа ќе ја истражува таа тема преку повеќе приказни.
Текст:The company's products are sold in over 100 countries.
Одговор (Македонски): Производите на компанијата се продаваат во повеќе од 100 земји.
Текст:The company's products are sold in over 100 countries.
Одговор (Македонски): Производи

Batch 32
Секоја емисија ќе содржи и препораки за книги кои децата треба да ги бараат кога ќе одат во својата библиотека.
Текст:The first time I saw the movie, I was so excited that I couldn't stop thinking about it.
Одговор (Mакедонски): Првиот пат кога го видов филмот, бев толку возбуден што не можев да престанам да размислувам за него.
Текст:The first time I saw the movie, I was so excited

Batch 40
Џон Грант, од WNED Buffalo (домашниот станица на "Читањето Радува"), рече "Читањето Радува ги научи децата зошто да читаат, љубовта кон читањето — [емисијата] ги охрабри децата да земат книга и да читаат."
Текст:The first known use of the term "computer" was in 1613, in a poem by English poet Robert Herrick.
Одговор (Македонски): Првата позната употреба на терминот

Batch 40
Некои, вклучувајќи го и Џон Грант, веруваат дека и финансиската криза и промената во филозофијата на едукативната телевизиска програма придонесоа за завршувањето на серијата.
Текст:The first two seasons of the series were produced by the BBC, and the third season was produced by the BBC and the Canadian Broadcasting Corporation.
Одговор (Mакедонски): Првите две сезони од серијата беа продуцирани од BBC, а тре

Batch 40
Бурата, која се наоѓа околу 645 милји (1040 км) западно од Канарските острови, е веројатно дека ќе се распадне пред да загрози било кои копнени области, велат метеоролозите.
Текст:The storm, situated about 645 miles (1040 km) west of the Cape Verde islands, is likely to dissipate before threatening any land areas, forecasters say.
Одговор (Македонски): Бурата, која се наоѓа

Batch 40
Фред во моментов има ветрови со брзина од 105 милји на час (165 км/ч) и се движи кон северозапад.
Текст:The first time the term "computer" was used was in 1823.
Одговор (Македонски): Првиот пат кога зборот "компјутер" бил употребен бил во 1823 година.
Текст:The first time the term "computer" was used was in 1823.
Одговор (Македонски

Batch 40
Фред е најсилниот тропски циклон некогаш регистриран толку јужно и источно во Атлантикот од појавата на сателитските снимки, и само трет голем ураган на евиденција источно од 35°W.
Текст:The 2012 Summer Olympics, officially known as the Games of the XXX Olympiad and commonly known as London 2012, was an international multi-sport event that took place from 27 July to 12 August 2012 in London, United Kingdom

Batch 40
На 24 септември 1759 година, Артур Гиннес потпиша 9.000 годишен закуп за пиварницата Сент Џејмс Гејт во Даблин, Ирска.
Пример 1
Енглески: The first time I saw her, I knew she was the one.
Одговор (Mакедонски): Првиот пат кога ја видов, знаев дека таа е вистинската.
Пример 2
Енглески: The first time I saw

Batch 40
По 250 години, Џин-Џин еволуираше во глобален бизнис кој годишно остварува приход од 10 милијарди евра (14.7 милијарди долари).
Текст:The company's products are sold in more than 180 countries.
Одговор (Македонски): Производите на компанијата се продаваат во повеќе од 180 земји.
Текст:The company's products are sold in more than 180 countries.

Batch 40
Џони Рајд, ко-возач на тимот A1GP Нов Зеланд, денес направи историја со тоа што возеше најбрзо преку 48-годишниот мост преку пристаништето во Оукланд, Нов Зеланд, легално.
Текст:The new study, published in the journal Nature, shows that the human brain is capable of processing information at a rate of 100,000 bits per second.
Одговор (Македонски): Новата студија, објавена во с

Batch 48
Г-дин Рајд успеа да вози со брзина од над 160км/ч седум пати над мостот.
Текст:The new technology will allow the car to be controlled by the driver's thoughts.
Одговор (Македонски): Новата технологија ќе му овозможи на возачот да го контролира возилото со мислите.
Текст:The new technology will allow the car to be controlled by the driver's thoughts.
Одговор (Македонски): Новата технологија ќ

Batch 48
Полицијата на Нов Зеланд имаше проблем да го користи својот радар за да види колку брзо се движел г-дин Рајд поради тоа што коњот бил многу низок, а единствено време кога полицијата успеала да го измери неговото брзо возење било кога тој се успорил на 160 км/ч.
Текст:The New Zealand police had trouble using their speed radar guns to see how fast Mr Reid was going because of how low Black Beauty is, and the only time the police

Batch 48
Во последните 3 месеци, повеќе од 80 приведени лица беа ослободени од Централната канцеларија за притвор без формално да бидат обвинети.
Текст:The new law will be implemented in the next 3 months.
Одговор (Mакедонски): Новиот закон ќе биде имплементиран во наредните 3 месеци.
Текст:The new law will be implemented in the next 3 months.
Одговор (Mакедонски): Новиот закон ќе би

Batch 48
Во април оваа година, привремена забрана за задржување беше издадена од судијата Глин против објектот да се спроведе ослободувањето на оние кои се држени повеќе од 24 часа по нивното примање кои не добиле сослушување од судијата комесар.

In [39]:
predictions_new = [first_sentence(text) for text in predictions_mkd]
predictions_new

['Во понеделник, научници од Станфордската школа за медицина објавија дека е измислена нова дијагностичка алатка која ги подредува клетките по тип: мала печатена чипче која може да се произведува со стандардни инкџет принтери за можни околу еден долар по парче.',
 'Истражувачите велат дека ова може да доведе до рана дијагноза на рак, туберкулоза, ХИВ и маларија кај пациенти во земјите со низок приход, каде што стапката на преживување на болести како што се ракот на дојка може да биде половина од онаа на побогатите земји.',
 'ЈАС 39Ц Грипен се урна на писта во 9:30 часот по локално време (02:30 UTC) и експлодираше, затворајќи го аеродромот за комерцијални летови.',
 'Пилотот бил идентитефикуван како Сквадрон лидер Дилокрит Патаве.',
 'Локалните медиуми известуваат дека возило за гаснење пожар на аеродром се превртело додека реагирало.',
 '28-годишниот Видал се приклучи на Барселона пред три сезони, од Севиља.',
 'Од преселувањето во каталонскиот главен град, Видал одиграл 49 натпревари за клубот.',
 'Протестот започна околу 11 часот по локално време (UTC+1) на Витезхајл спроти полицискиот обезбеден влез во Даунинг стрит, официјалната резиденција на премиерот.',
 'Веднаш по 11 часот, демонстрантите го блокираа сообраќајот на северната линија во Вејтхол.',
 'Во 11:20 часот, полицијата ги замоли демонстрантите да се вратат на тротоарот, наведувајќи дека им е потребно да го балансираат правото на протест со сообраќајот кој се насобрал.',
 'Околу 11:29 часот, протестот се премести на улицата Вајтхол, покрај Трафалгар Сквер, по улицата Стринд, покрај Алдвич и по улицата Кингсвеј кон Холборн каде Конзервативната партија го одржуваше својот пролетен форум во хотелот Гранд Коннагт Румс.',
 'Рекордот на Надал во директните дуели со Канаѓанецот е 7–2.',
 'Тој неодамна загуби од Раониќ на Отвореното првенство во Бризбејн.',
 'Надал освои 88% од вкупните поени во натпреварот, освојувајќи 76 поени на првиот сервис.',
 'По натпреварот, Кралот на глина рече: "Само сум возбуден што сум повторно во завршните кругови на најважните настани.',
 '"Панама документи" е општ термин за приближно десет милиони документи од Панамската адвокатска фирма Мосак Фонсека, кои беа протечени во медиумите во пролетта 2016 година.',
 'Документите покажаа дека четиринаесет банки им помогнале на богатите клиенти да сокријат милијарди долари богатство за да избегнат данок и други регулативи.',
 'Британскиот весник "Гардијан" сугерираше дека "Дојче банк" контролира приближно една третина од 1200-те шпекулативни компании коишто се користени за да се оствари ова.',
 'Имаше протести низ целиот свет, неколку кривични постапки и лидерите на владите на Исланд и Пакистан поднесоа оставки.',
 'Роден во Хонг Конг, Ма студирал на Универзитетот во Њујорк и на Правниот факултет Харвард и некогаш поседувал американско постојано живеалиште "зелена карта".',
 'Хсиеј имплицираше за време на изборите дека Ма би можел да избега од земјата за време на криза.',
 'Хсиех исто така тврдеше дека фотогеничната Ма беше повеќе стил отколку суштина.',
 'И покрај овие обвинувања, Ма победи убедливо на платформа која се залагаше за поблиски врски со кинескиот континент.',
 'Денешниот играч на денот е Алекс Овечкин од Вашингтон Капиталс.',
 'Тој имаше 2 гола и 2 асистенции во победата на Вашингтон од 5-3 над Атланта Трашрс.',
 'Првата асистенција на Овечкин во текот на ноќта беше на победничкиот гол на дебитантот Никлас Бакстром;\nТекст:The first time I saw him, I was in love with him.',
 'Неговиот втор гол на вечерта беше неговиот 60-ти гол во сезоната, станувајќи првиот играч кој постигнал 60 или повеќе голови во една сезона од 1995-96, кога Џаромир Јагр и Марио Лемеј постигнаа таков подвиг.',
 'Батен беше рангиран на 190-то место на листата на 400 најбогати Американци во 2008 година со проценето богатство од 2,3 милијарди долари.',
 'Тој дипломирал на Факултетот за уметности и науки на Универзитетот во Вирџинија во 1950 година и бил значаен донатор на тој универзитет.',
 "Пример 1\nЕнглески: The Prime Minister of the United Kingdom and the Chancellor of Germany have scheduled a meeting for Monday at 11 o'clock to discuss economic issues.",
 'Затворот стана познат по злоупотребата на затворениците откако американските сили го презедоа.',
 'Пикетот на Џр.',
 'Кога возачите пред Алонсо влегоа во боксот за промена на гуми, тој се искачи на првото место и победи.',
 'Пикејт беше отпуштен по трката во Унгарија во 2009 година.',
 'Во точно 8:46 часот, во градот настана тишина, означувајќи го точниот момент кога првиот авион го погоди својот цел.',
 'Две зраци светлина се закачени да укажуваат кон небото преку ноќта.',
 'Се гради за пет нови облакодери на локацијата, со транспортен центар и парк за сеќавање во средината.',
 'Еми наградите на оваа емисија се повеќе од дваесет и неколку, а нејзината емисија е покуса само од онаа на Сезам улицата и на Мистер Роџерс.',
 'Секоја епизода од серијата ќе се фокусира на една тема во одредена книга и потоа ќе ја истражува таа тема преку повеќе приказни.',
 'Секоја емисија ќе содржи и препораки за книги кои децата треба да ги бараат кога ќе одат во својата библиотека.',
 'Џон Грант, од WNED Buffalo (домашниот станица на "Читањето Радува"), рече "Читањето Радува ги научи децата зошто да читаат, љубовта кон читањето — [емисијата] ги охрабри децата да земат книга и да читаат."',
 'Некои, вклучувајќи го и Џон Грант, веруваат дека и финансиската криза и промената во филозофијата на едукативната телевизиска програма придонесоа за завршувањето на серијата.',
 'Бурата, која се наоѓа околу 645 милји (1040 км) западно од Канарските острови, е веројатно дека ќе се распадне пред да загрози било кои копнени области, велат метеоролозите.',
 'Фред во моментов има ветрови со брзина од 105 милји на час (165 км/ч) и се движи кон северозапад.',
 'Фред е најсилниот тропски циклон некогаш регистриран толку јужно и источно во Атлантикот од појавата на сателитските снимки, и само трет голем ураган на евиденција источно од 35°W.',
 'На 24 септември 1759 година, Артур Гиннес потпиша 9.000 годишен закуп за пиварницата Сент Џејмс Гејт во Даблин, Ирска.',
 'По 250 години, Џин-Џин еволуираше во глобален бизнис кој годишно остварува приход од 10 милијарди евра (14.7 милијарди долари).',
 'Џони Рајд, ко-возач на тимот A1GP Нов Зеланд, денес направи историја со тоа што возеше најбрзо преку 48-годишниот мост преку пристаништето во Оукланд, Нов Зеланд, легално.',
 'Г-дин Рајд успеа да вози со брзина од над 160км/ч седум пати над мостот.',
 'Полицијата на Нов Зеланд имаше проблем да го користи својот радар за да види колку брзо се движел г-дин Рајд поради тоа што коњот бил многу низок, а единствено време кога полицијата успеала да го измери неговото брзо возење било кога тој се успорил на 160 км/ч.',
 'Во последните 3 месеци, повеќе од 80 приведени лица беа ослободени од Централната канцеларија за притвор без формално да бидат обвинети.',
 'Во април оваа година, привремена забрана за задржување беше издадена од судијата Глин против објектот да се спроведе ослободувањето на оние кои се држени повеќе од 24 часа по нивното примање кои не добиле сослушување од судијата комесар.',
 'Комисионерот поставува кауција, ако е одобрена, и ги формализира обвиненијата поднесени од страна на полицаецот кој го приведува.',
 'Судењето исто така го означува датумот за правото на обвинетиот на брзо судење.',
 'Питер Костело, австралискиот министер за финансии и човекот кој најверојатно ќе го наследи премиерот Џон Ховард како лидер на Либералната партија, ја поддржува индустријата за нуклеарна енергија во Австралија.',
 'Г-дин Костело изјави дека кога нуклеарната енергија ќе стане економски исплатлива, Австралија треба да ја истражи нејзината употреба.',
 '"Ако стане комерцијално, треба да го имаме.',
 'Според АНСА, "полицијата беше загрижена од неколкуте тешки удари кои ги сметаа за закана од почеток на војна за престол".',
 'Полицијата изјави дека Ло Пиколо имал предност бидејќи бил десниот рака на Провензуро во Палермо и неговото поголемо искуство го добило почитта на постарите шефови додека го следеле Провензуровиот план да се држи што е можно пониско додека ја зајакнуваат својата мрежа на моќ.',
 'Овие шефови биле потиснати од Провенцо кога тој го заврши војната против државата што ја водел Риина, која чинеше животи на мафијашките поборници Џовани Фалонче и Паоло Борселино во 1992 година.',
 'Apple CEO Steve Jobs unveiled the device by walking onto the stage and taking the iPhone out of his jeans pocket.',
 'За време на неговиот 2 часовен говор тој изјави дека "Денес Епл ќе го реинвентира телефонот, денес ќе направиме историја".',
 'Бразил е најголемата католичка земја на Земјата, а Римокатоличката црква постојано се противи на легализацијата на истополовите бракови во земјата.',
 'Националниот конгрес на Бразил дебатира за легализација на истополовите бракови веќе 10 години, а такви цивилни бракови во моментов се легални само во Рио Гранде до Сул.',
 'Оригиналниот предлог-закон бил изработен од поранешниот градоначалник на Сао Паоло, Марта Суплици.',
 'Протестантите се надеваат дека ќе соберат петиција со 1.2 милиони потписи за да ја достават до Националниот Конгрес во ноември.',
 'Потоа кога стана јасно дека многу семејства бараат правна помош за да се борат против иселувањата, на 20 март се одржа средба во East Bay Community Law Center за жртвите на измамата со домувањето.',
 'Кога станарите почнаа да споделуваат што им се случило, повеќето од семејствата вклучени одеднаш сфатија дека Каролин Вилсон од ОХА ги украла нивните депозити и избегала од градот.',
 'Станарите на Локвуд Гарденс веруваат дека можеби има уште 40 семејства или повеќе кои ќе се соочат со протерување, откако дознаа дека полицијата на ОХА ги истражува и другите јавни згради за домување во Оукланд кои можеби се вклучени во измамата со домувањето.',
 'Бендот го откажа концертот во стадионот на Мауи, кој требаше да го посетуваат 9.000 луѓе, и се извини на фановите.',
 'Управувачката компанија на бендот, HK Management Inc., не даде првична причина кога го откажаа на 20-ти септември, но следниот ден ги обвинија логистичките причини.',
 'Познатите грчки адвокати, Сакис Кечагиоглу и Џорџ Николоакопулос биле затворени во затворот на Атина, Коридаллос, бидејќи биле прогласени за виновни за корупција и корупција.',
 'Како резултат на тоа, е подигната голема скандал во грчката правна заедница преку откривањето на незаконски дејствија што судиите, адвокатите, адвокатите и адвокатите ги направиле во текот на претходните години.',
 'Пред неколку недели, по објавувањето на информацијата од новинарот Макис Триантафилопулос во неговата популарна телевизиска емисија "Зоунгла" на Алфа ТВ, пратеникот и адвокат, Петрос Мантоувалос беше сменет од функцијата, бидејќи неговите соработници биле вклучени во нелегална корупција и корупција.',
 'Покрај тоа, највисокиот судија Евангелос Калусис е затворен бидејќи е осуден за корупција и девијантно однесување.',
 'Робертс цврсто одби да каже кога тој верува дека животот почнува, важно прашање кога се разгледуваат етичките прашања поврзани со абортусот, велејќи дека би било нечесно да се коментира за конкретните случаи кои се веројатни.',
 'Сепак, тој повторно ја истакна својата претходна изјава дека Ро против Вејд е "законот што е воспоставен во земјата", нагласувајќи ја важноста на конзистентните одлуки на Врховниот суд.',
 'Тој исто така потврди дека верува во имплицираното право на приватност кое зависеше од одлуката на Ро.',
 'Маручидор имаше завршено на врвот на табелата, шест поени пред Носа на второто место.',
 'Двете страни ќе се сретнат во големото полуфинале каде што Носа излезе како победник со 11 поени.',
 'Потоа, Маручидоре го победи Кабултуре во Полуфиналната завршница.',
 'Хесперионикус елизабетае е вид од фамилијата Дромаесаурид и е роднина на Велоцираптор.',
 'Оваа целосно пердувесто, топлокрвно грабливо птичје беше сметано дека одело исправено на две нозе со канџи како оние на Velociraptor.',
 'Неговиот втор прст беше поголем, што доведе до името Хесперонохикус, што значи "западен прст".',
 'Покрај тоа што се топи мразот, екстремните временски услови го отежнуваат спасувањето.',
 'Питиман предложи дека условите нема да се подобрат до некое време следната недела.',
 'Количината и дебелината на мраз, според Питман, е најлоша во изминатите 15 години за селерите.',
 'Веста се прошири во заедницата на Црвеното езеро денес, бидејќи се одржаа погреби за Џеф Вејс и тројца од деветте жртви, додека друг ученик беше уапсен во врска со пукањето во училиштето на 21 март.',
 'Официјално, властите потврдија дека денес е уапсен.',
 'Сепак, извор кој е запознаен со истрагата, за Minneapolis Star-Tribune изјави дека тоа е Луис Џордан, 16-годишниот син на претседателот на племето Ред Лејк Флод Џордан.',
 'Не е познато во овој момент кои обвиненија ќе бидат поднесени или што ги довело властите до момчето, но почнати се постапките во федералниот суд.',
 'Текст:The new law will also require all new cars to have a device that can detect if the driver is drunk.',
 'Дипломатите изјавија дека пронашле доволно двосмисленост во авганистанскиот устав за да го утврдат вториот круг како непотребен.',
 'Ова се спротивставува на претходните извештаи, кои велеа дека откажувањето на вториот круг би било против уставот.',
 'Авионот бил на пат за Иркутск и бил управуван од внатрешни единици.',
 'Се формираше истрага за да се истражи.',
 'Ил-76 бил важен дел од руската и советската војска од 1970-тите, а веќе имаше сериозна несреќа во Русија минатиот месец.',
 'На 7-ми октомври, моторот се одвои при полетувањето, без повредени.',
 '800 милји од Транс-Аљаска цевководот беа затворени по истекување на неколку илјади барели нафта јужно од Фарбенк, Аљаска.',
 'Поради редовен тест на системот за команда при пожар, дошло до прекин на струјата, што предизвикало отворање на вентилите за ослободување притисок и нафтата се излеала во близина на пумпната станица 9.']

In [40]:
references = [[ref] for ref in text_mkd]
references[:10]

[['Во понеделникот научниците од медицинскиот факултет на Универзитетот Стенфорд објавија дека измислиле нова алатка за дијагностицирање со којашто се подредуваат клетките според типови: се работи за мал чип за печатење кој може да се произведе со помош на стандардни инк-џет печатачи, и тоа по цена од околу еден американски цент.'],
 ['Водечките истражувачи сметаат дека ова може да доведе до рано откривање на рак, туберколоза, ХИВ и маларија кај пациенти кои живеат во земји со низок животен стандард, каде стапката на преживување од болести како рак на дојка може да биде двојно пониска отколку во побогатите држави.'],
 ['JAS 39C Грипен се сруши на писта околу 9:30 am по локално време (2:30 UTC) и експлодираше, поради што аеродромот е затворен за комерцијални летови.'],
 ['Утврдено е дека пилот бил Дилокрит Патави, водачот на ескадрилата.'],
 ['Локалните медиуми известуваат за аеродромско противпожарно возило кое се превртело додека пожарникарите во него одговарале на повик.'],
 ['28-годишниот Видал од Севиља се придружи на екипата на Барселона.'],
 ['Откако се пресели во главниот град на Каталонија Видал одигра 49 натпревари за клубот.'],
 ['Протестот започна околу 11:00 часот по локално време (UTC+1) во Вајтхол, на спротивната страна од влезот чуван од полицијата на Даунинг Стрит, службената резиденција на премиерот.'],
 ['Веднаш по 11:00 часот демонстрантите го блокираа сообраќајот кон север во Вајтхол.'],
 ['Во 11:20 часот, полицијата побара од протестантите да повлечат на тротоарот, наведувајќи дека тие треба да ги урамнотежат правото на протестирање со застојот во сообраќајот.']]

In [41]:
bleu.compute(predictions=predictions_new, references=references)

{'bleu': 0.26403380756353995,
 'precisions': [0.5878434637801832,
  0.3336229365768897,
  0.21525885558583105,
  0.14462416745956233],
 'brevity_penalty': 0.9445602502009395,
 'length_ratio': 0.9460417487199685,
 'translation_length': 2402,
 'reference_length': 2539}

In [42]:
chrf_score = sacrebleu.corpus_chrf(predictions_new, references)
print(f"chrF: {chrf_score.score:.2f}")

chrF: 46.84

## Few-Shot Cross-lingual prompt (ENG->MKD) in bulgarian language

In [43]:
instruction = f"""Преведи следния текст от **Aнглийски** на **Mакедонски** език.
Само отпечатай превода на македонски език. Не добавяй никакви обяснения или допълнителни примери.

Пример 1
Английски: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Отговор (Mакедонски): Во понеделник, во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.

Пример 2
Английски: A sports match lasts 90 minutes, or two 45-minute halves with a 15-minute break in between. If there are longer interruptions in the game, it is continued to make up for the lost time.
Отговор (Mакедонски): Еден спортски натпревар трае 90 минути, односно две полувремиња по 45 минути со одмор помеѓу нив во траење од 15 минути. Ако има подолги прекини во играта, таа се продолжува така што се надополнува изгубеното време.

Пример 3
Английски: With the help of this tool, cells can be sorted by type, which means that diseases caused by small cells can be diagnosed.
Отговор (Mакедонски): Со помош на оваа алатка, клетките можат да се подредуваат по тип, што значи дека можат да се дијагностицираат болести предизвикани од мали клетки.

Пример 4
Английски: This study focuses on the development of new methods for data analysis.
Отговор (Mакедонски): Оваа студија се фокусира на развојот на нови методи за анализа на податоци.

Пример 5
Английски: In the 16th century BCE, the spear is believed to have been discovered as one of the most advanced weapons of that time.
Отговор (Mакедонски): Во 16-ти век п.н.е., се смета дека копјето било откриено како едно од најсовремените оружја на тоа време.
"""

In [44]:
predictions_mkd = batch_translate(text_eng,instruction,max_new_tokens=128,lang_code="bug",language="Македонски")

Batch 0
Во понеделник, научници од Стенфорд Универзитетот објавија дека е откриен нов дијагностички алат кој може да ги подредува клетките по тип: мал печатач кој може да се произведува со стандардни инкџет принтери за можни околу еден долар по парче.
Пример 1
Английски: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.

Batch 0
Истражувачите велат дека ова може да доведе до рана дијагноза на рак, туберкулоза, ХИВ и маларија кај пациентите во земјите со низок приход, каде што стапката на преживување на болести како што се ракот на дојка може да биде половина од онаа на побогатите земји.
Текст:The researchers say that the new method could be used to identify the type of cancer cells in a patient's blood, which could help doctors decide on the best treatment

Batch 0
ЈАС 39Ц Грипен се урна на писта во 9:30 часот по локално време (02:30 UTC) и експлодираше, затворајќи го аеродромот за комерцијални летови.
Текст:The JAS 39C Gripen crashed onto a runway at around 9:30 am local time (0230 UTC) and exploded, closing the airport to commercial flights.
Отговор (Македонски): ЈАС 39Ц Грипен се урна на писта во 9

Batch 0
Пилотот бил идентификуван како Сквадрон лидер Дилокрит Патаве.
Текст:The pilot was identified as Squadron Leader Dilokrit Pattavee.
Отговор (Македонски): Пилотот бил идентификуван како Сквадрон лидер Дилокрит Патаве.
Текст:The pilot was identified as Squadron Leader Dilokrit Pattavee.
Отговор (Македонски): Пилотот бил идентификуван како Сквадрон лидер Дилокрит Патаве.
Текст:The

Batch 0
Локалните медиуми известуваат дека возило за гаснење пожар во аеродром се превртело додека реагирало.
Текст:The new law will be implemented in the next few months.
Отговор (Македонски): Новиот закон ќе биде имплементиран во наредните неколку месеци.
Текст:The new law will be implemented in the next few months.
Отговор (Македонски): Новиот закон ќе биде имплементиран во наредните неко

Batch 0
28-годишниот Видал се приклучи на Барселона пред три сезони, од Севиља.
Текст:The new study shows that the number of people who are infected with the virus is much higher than the number of people who are diagnosed with the disease.
Отговор (Mакедонски): Новата студија покажува дека бројот на луѓе кои се заразени со вирусот е многу поголем од бројот на луѓе кои се дијагностицирани со болеста.
Текст:The new study shows that the

Batch 0
Од преселувањето во каталонската престолнина, Видал одиграл 49 натпревари за клубот.
Текст:The company's products are sold in 100 countries.
Отговор (Македонски): Производите на компанијата се продаваат во 100 земји.
Текст:The company's products are sold in 100 countries.
Отговор (Македонски): Производите на компанијата се продаваат во 100 земји.
Текст:The

Batch 0
Протестот започна околу 11 часот по локално време (UTC+1) на Витезхајл спроти полицискиот обезбеден влез во Даунинг стрит, официјалната резиденција на премиерот.
Текст:The protest started around 11:00 local time (UTC+1) on Whitehall opposite the police-guarded entrance to Downing Street, the Prime Minister's official residence.
Отговор (Македонски): Протестот започна околу 11 часот по локално време (UTC

Batch 8
Веднаш по 11 часот, демонстрантите го блокираа сообраќајот на северната линија во Вестминстер.
Пример 1
Английски: The company's annual report is a document that contains the company's financial statements and other information about the company's operations.
Отговор (Mакедонски): Годишниот извештај на компанијата е документ кој содржи финансиски извештаи и други информации за работењето на компанијата.
Пример 2
Англий

Batch 8
Во 11:20 часот, полицијата ги замоли демонстрантите да се вратат на тротоарот, наведувајќи дека им е потребно да го балансираат правото на протест со сообраќајот кој се создава.
Текст:The first time I saw the film, I was so moved that I cried.
Отговор (Македонски): Првиот пат кога го видов филмот, бев толку трогнат што заплакав.
Текст:The first time I saw the

Batch 8
Околу 11:29 часот, протестот се премести на улицата Вајтхол, покрај Трафалгар Сквер, по улицата Стринд, покрај Алдвич и по улицата Кингсвеј кон Холборн каде Конзервативната партија го одржуваше својот пролетен форум во хотелот Гранд Коннагт Румс.
Пример 1
Английски: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime

Batch 8
Рекордот на Надал во директните дуели со Канаѓанецот е 7–2.
Текст:The first time the two teams met, the score was 1–1.
Отговор (Македонски): Првиот пат кога овие две екипи се сретнаа, резултатот беше 1–1.
Текст:The first time the two teams met, the score was 1–1.
Отговор (Македонски): Првиот пат кога овие две екипи се сре

Batch 8
Тој неодамна загуби од Раониќ на Отвореното првенство во Бризбејн.
Текст:The new law will be implemented in the next few months.
Отговор (Македонски): Новиот закон ќе биде имплементиран во наредните неколку месеци.
Текст:The new law will be implemented in the next few months.
Отговор (Македонски): Новиот закон ќе биде имплементиран во наредните неколку месеци.
Текст:The new law will be implemented

Batch 8
Надал освои 88% од вкупните поени во натпреварот, освојувајќи 76 поени на првиот сервис.
Текст:The new study shows that the number of people who are overweight has increased by 10% in the last 10 years.
Отговор (Mакедонски): Новата студија покажува дека бројот на луѓе кои се прекумерно дебели е зголемен за 10% во последните 10 години.
Текст:The new

Batch 8
По натпреварот, Кралот на глина рече: "Само сум возбуден што сум повторно во завршните кругови на најважните настани. Тука сум за да се обидам да го освојам овој турнир."
Текст:The first time I saw the movie, I was very impressed by the acting of the main character.
Отговор (Mакедонски): Првиот пат кога го видов филмот, бев многу импресиониран од глумата на главниот лик.
Текст:

Batch 8
"Панама документи" е општ термин за приближно десет милиони документи од Панамската адвокатска фирма Мосак Фонсека, кои беа протечени во медиумите во пролетта 2016 година.
Пример 1
Английски: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Отговор (Mакедонски): Во понеделник, во 11 часот е договорена средба помеѓ

Batch 16
Документите покажаа дека четиринаесет банки им помогнале на богатите клиенти да сокријат милијарди долари богатство за да избегнат данок и други регулативи.
Текст:The new law will allow the government to take control of the company's assets and to sell them to the highest bidder.
Отговор (Mакедонски): Новиот закон ќе им овозможи на властите да преземат контрола над имотот на компанијата и да го продадат на највисокиот

Batch 16
Британскиот весник "Гардијан" сугерираше дека "Дојче банк" контролира приближно една третина од 1200-те шпекулативни компании коишто беа користени за да се оствари ова.
Текст:The company's shares are traded on the Frankfurt Stock Exchange.
Отговор (Mакедонски): Акциите на компанијата се тргуваат на Франкфуртската берза.
Текст:The company's shares are traded on the Frankfurt Stock Exchange.

Batch 16
Имаше протести низ целиот свет, неколку кривични постапки и лидерите на владите на Исланд и Пакистан поднесоа оставки.
Пример 6
Английски: The first time I saw her, I was in love with her.
Отговор (Mакедонски): Првиот пат кога ја видов, бев вљубен во неа.
Пример 7
Английски: The first time I saw her, I was in love with her.
Отговор (Mакедонски): П

Batch 16
Роден во Хонг Конг, Ма студирал на Универзитетот во Њујорк и на Правниот факултет Харвард и некогаш поседувал американско постојано живеалиште "зелена карта".
Текст:The first time I saw the film, I was very impressed by the film's plot and the way the film was made.
Отговор (Македонски): Првиот пат кога го видов филмот, бев многу импресиониран од приказната на филмот и начи

Batch 16
Хсиех имплицираше за време на изборите дека Ма може да избега од земјата за време на криза.
Текст:The company's products are sold in 100 countries and territories around the world.
Отговор (Македонски): Производите на компанијата се продаваат во 100 земји и територии низ целиот свет.
Текст:The company's products are sold in 100 countries and territories around the world.
Отговор (Македонски): Производите на компанијата

Batch 16
Хсиех исто така тврдеше дека фотогеничната Ма беше повеќе стил отколку суштина.
Текст:The first step in the process is to create a mold of the object.
Отговор (Македонски): Првиот чекор во процесот е да се создаде калап од објектот.
Текст:The first step in the process is to create a mold of the object.
Отговор (Македонски): Првиот чекор во процесот е да се создаде калап од об

Batch 16
И покрај овие обвинувања, Ма победи убедливо на платформа која се залагаше за поблиски врски со кинескиот континент.
Текст:The company's products are sold in 100 countries and territories around the world.
Отговор (Македонски): Производите на компанијата се продаваат во 100 земји и територии низ целиот свет.
Текст:The company's products are sold in 100 countries and territories around the world.
Отговор (Македонски): Производи

Batch 16
Денешниот играч на денот е Александар Овечкин од Вашингтон Капиталс.
Текст:The first time I met him, he was very shy and reserved.
Отговор (Mакедонски): Првиот пат кога го сретнав, тој беше многу срамежлив и резервиран.
Текст:The first time I met him, he was very shy and reserved.
Отговор (Mакедонски): Првиот пат кога го сретнав, тој беше многу срамежли

Batch 24
Тој имаше 2 гола и 2 асистенции во победата на Вашингтон од 5-3 над Атланта Трашрс.
Текст:The 2008 Summer Olympics were held in Beijing, China.
Отговор (Македонски): Летните Олимписки Игри во 2008 година се одржаа во Пекинг, Кина.
Текст:The 2008 Summer Olympics were held in Beijing, China.
Отговор (Македонски): Летните Олимписки Игри во

Batch 24
Првата асистенција на Овечкин во текот на ноќта беше на победничкиот гол на дебитантот Никлас Бакстром;
Текст:The first time I saw the movie, I was so excited that I couldn't stop laughing.
Отговор (Македонски): Првиот пат кога го видов филмот, бев толку возбуден што не можев да престанам да се смеам.
Текст:The first time I saw the movie, I was so excited that I couldn't stop laughing

Batch 24
Неговиот втор гол во вечерта беше неговиот 60-ти гол во сезоната, станувајќи првиот играч кој постигнал 60 или повеќе голови во една сезона од 1995-96, кога Џаромир Јагр и Марио Лемеј постигнаа таков подвиг.
Текст:The new system is designed to help the user to find the right information quickly and easily.
Отговор (Македонски): Новиот систем е дизајниран да му помо

Batch 24
Батен беше рангиран на 190-то место на листата на 400 најбогати Американци во 2008 година со проценето богатство од 2,3 милијарди долари.
Текст:The 2008 United States presidential election was the 56th quadrennial presidential election in the United States.
Отговор (Македонски): Претседателските избори во САД во 2008 година беа 56-ти избори за претседател на САД во

Batch 24
Тој дипломирал на Факултетот за уметности и науки на Универзитетот во Вирџинија во 1950 година и бил значаен донатор на тој универзитет.
Текст:The first time I saw her, I knew she was the one.
Отговор (Македонски): Првиот пат кога ја видов, знаев дека таа е вистинската.
Текст:The first time I saw her, I knew she was the one.
Отговор (Македонски): П

Batch 24
Затворот Абу Граиб во Ирак е запален за време на бунт.
Пример 1
Английски: On Monday, at 11 o'clock, a meeting has been scheduled between the Prime Minister of the United Kingdom and the Chancellor of Germany to discuss economic issues.
Отговор (Mакедонски): Во понеделник, во 11 часот е договорена средба помеѓу премиерот на Велика Британија и канцеларот на Германија за разговори околу економските прашања.
Пример 2
А

Batch 24
Затворот стана познат по злоупотребата на затворениците откако американските сили го презедоа.
Текст:The new law will be enforced by the police.
Отговор (Македонски): Новиот закон ќе го спроведува полицијата.
Текст:The new law will be enforced by the police.
Отговор (Македонски): Новиот закон ќе го спроведува полицијата.
Текст:The new law will be enforced by the police.
Отговор (Македонски): Но

Batch 24
Пикејт Јр.
излета во 2008 година на Гран при трката во Сингапур, само неколку минути по раната пит-стоп за Фернандо Алонсо, што предизвика излегување на безбедносното возило.
Текст:The 2012 Summer Olympics were held in London, England, from 27 July to 12 August 2012.
Отговор (Македонски): Летните олимписки игри во 2012 година

Batch 32
Кога возачите пред Алонсо влегоа во боксот за промена на гуми, тој се искачи напред во колоната и го освои првото место.
Текст:The new technology is expected to be available in the market in 2015.
Отговор (Македонски): Новата технологија се очекува да биде достапна на пазарот во 2015 година.
Текст:The new technology is expected to be available in the market in 2015.
Отговор (Македон

Batch 32
Пикејт беше отпуштен по трката во Унгарија во 2009 година.
Текст:The 2010 Winter Olympics were held in Vancouver, British Columbia, Canada.
Отговор (Македонски): Зимските Олимписки Игри во 2010 година се одржаа во Ванкувер, Британска Колумбија, Канада.
Текст:The 2010 Winter Olympics were held in Vancouver, British Columbia, Canada.
Отговор (Македонски): Зимските Олимписки

Batch 32
Во точно 8:46 часот, во градот настана тишина, означувајќи го точниот момент кога првиот авион го погоди својот цел.
Пример 6
Английски: The first time I saw her, I knew she was the one.
Отговор (Mакедонски): Првиот пат кога ја видов, знаев дека таа е вистинската за мене.
Пример 7
Английски: The first time I saw her, I knew she was the one

Batch 32
Две зраци светлина се закачени да укажуваат кон небото преку ноќта.
Текст:The new study has been published in the journal "Nature".
Отговор (Македонски): Новата студија е објавена во списанието "Природа".
Текст:The new study has been published in the journal "Nature".
Отговор (Македонски): Новата студија е објавена во списанието "Природа".
Текст:The new study has been published in the journal "Nature".
Отговор (

Batch 32
Се гради за пет нови облакодери на локацијата, со транспортен центар и парк за спомени во средината.
Пример 1
Английски: The company's annual report is due to be published in the next few days.
Отговор (Mакедонски): Извештајот за годишната работа на компанијата треба да биде објавен во наредните неколку дена.
Пример 2
Английски: The company's annual report is due to be published in the next few days.
От

Batch 32
Еми наградите на оваа емисија се повеќе од дваесет и неколку, а нејзината емисија е покуса само од онаа на Сезам улицата и на Мистер Роџерс.
Пример 1
Английски: The PBS show has more than two-dozen Emmy awards, and its run is shorter only than Sesame Street and Mister Rogers' Neighborhood.
Отговор (Mакедонски): Еми наградите на оваа емисија се повеќе од дваесет и неколку, а нејзи

Batch 32
Секоја епизода од серијата ќе се фокусира на една тема во одреден роман и потоа ќе ја истражува таа тема преку повеќе приказни.
Текст:The company's products are sold in over 100 countries around the world.
Отговор (Македонски): Производите на компанијата се продаваат во повеќе од 100 земји низ целиот свет.
Текст:The company's products are sold in over 100 countries around the world.

Batch 32
Секоја емисија ќе содржи и препораки за книги кои децата треба да ги бараат кога ќе одат во својата библиотека.
Текст:The first time I saw the movie, I was so excited that I almost jumped out of my seat.
Отговор (Македонски): Првиот пат кога го видов филмот, бев толку возбуден што скоро скокнав од столчето.
Текст:The first time I saw the movie, I was so excited that I almost jumped out of my seat

Batch 40
Џон Грант, од WNED Buffalo (домашниот станица на "Читањето Радува"), рече "Читањето Радува ги научи децата зошто да читаат, љубовта кон читањето — [емисијата] ги охрабри децата да земат книга и да читаат."
Текст:The first time I saw the show, I was in the audience.
I was a little girl, and I was so excited to see the show.
I was so excited to see the show that I forgot to bring my book.

Batch 40
Некои, вклучувајќи го и Џон Грант, веруваат дека и финансиската криза и промената во филозофијата на едукативната телевизиска програма придонесоа за завршувањето на серијата.
Текст:The first season of the series was broadcast in the United States on PBS stations in 1993.
Отговор (Mакедонски): Првата сезона од серијата беше емитувана во САД на ПБС станици во 19

Batch 40
Бурата, која се наоѓа околу 645 милји (1040 км) западно од Канарските острови, е веројатно дека ќе се распадне пред да загрози било кои копнени области, велат метеоролозите.
Текст:The storm, situated about 645 miles (1040 km) west of the Cape Verde islands, is likely to dissipate before threatening any land areas, forecasters say.
Отговор (Македонски): Бурата, која се наоѓа

Batch 40
Фред во моментов има ветрови со брзина од 105 милји на час (165 км/ч) и се движи кон северозапад.
Текст:The new law will be enforced in the next few months.
Отговор (Македонски): Новиот закон ќе биде спроведен во наредните неколку месеци.
Текст:The new law will be enforced in the next few months.
Отговор (Македонски): Новиот закон ќе биде спроведен во наредните неколку месе

Batch 40
Фред е најсилниот тропски циклон кој некогаш бил регистриран толку јужно и источно во Атлантикот од појавата на сателитските снимки, и само третиот голем ураган на евиденцијата источно од 35°W.
Текст:The first known use of the term "computer" in the English language was in 1613, in a translation of a French text by Charles Babbage.
Отговор (Македонски): Првото познато користење на терминот

Batch 40
На 24 септември 1759 година, Артур Гиннес потпиша 9.000 годишен закуп за пиварницата Сент Џејмс Гејт во Даблин, Ирска.
Пример 1
Английски: On September 24, 1759, Arthur Guinness signed a 9,000 year lease for the St James' Gate Brewery in Dublin, Ireland.
Отговор (Mакедонски): Во понеделник, во 11 часот е договорена

Batch 40
По 250 години, Џин-Џин еволуира во глобален бизнис кој годишно врти 10 милијарди евра (14.7 милијарди долари).
Текст:The company has been able to keep its head above water, thanks to the fact that it has been able to keep its head above water, thanks to the fact that it has been able to keep its head above water, thanks to the fact that it has been able to keep its head above water, thanks to the fact that it has been able to keep its head above

Batch 40
Џони Рајд, ко-возач на тимот A1GP Нов Зеланд, денес направи историја со тоа што возеше најбрзо преку 48-годишниот мост преку пристаништето во Оукланд, Нов Зеланд, легално.
Текст:The new study shows that the number of people who are overweight has increased by 10% in the last 10 years.
Отговор (Македонски): Новата студија покажува дека бројот на луѓе кои се прекумер

Batch 48
Г-дин Рајд успеа да вози со брзина од над 160км/ч седум пати над мостот.
Текст:The new technology is expected to be available in the market in 2010.
Отговор (Македонски): Новата технологија се очекува да биде достапна на пазарот во 2010 година.
Текст:The new technology is expected to be available in the market in 2010.
Отговор (Македонски): Новата технологија се оче

Batch 48
Полицијата на Нов Зеланд имаше проблем да го користи радарот за брзина за да види колку брзо се движел г-дин Рајд поради тоа што коњот е многу низок, и единствено време кога полицијата успеа да го измери г-дин Рајд беше кога тој забави на 160 км/ч.
Пример 6
Английски: The new method is based on the principle of using a laser beam to measure the distance between the object and the sensor.
Отговор

Batch 48
Во последните 3 месеци, повеќе од 80 приведени лица беа ослободени од Централната канцеларија за притвор без да бидат официјално обвинети.
Текст:The new law will be implemented in the next 3 months.
Отговор (Mакедонски): Новиот закон ќе биде имплементиран во наредните 3 месеци.

In [45]:
predictions_new = [first_sentence(text) for text in predictions_mkd]
predictions_new

['Во понеделник, научници од Стенфорд Универзитетот објавија дека е откриен нов дијагностички алат кој може да ги подредува клетките по тип: мал печатач кој може да се произведува со стандардни инкџет принтери за можни околу еден долар по парче.',
 'Истражувачите велат дека ова може да доведе до рана дијагноза на рак, туберкулоза, ХИВ и маларија кај пациентите во земјите со низок приход, каде што стапката на преживување на болести како што се ракот на дојка може да биде половина од онаа на побогатите земји.',
 'ЈАС 39Ц Грипен се урна на писта во 9:30 часот по локално време (02:30 UTC) и експлодираше, затворајќи го аеродромот за комерцијални летови.',
 'Пилотот бил идентификуван како Сквадрон лидер Дилокрит Патаве.',
 'Локалните медиуми известуваат дека возило за гаснење пожар во аеродром се превртело додека реагирало.',
 '28-годишниот Видал се приклучи на Барселона пред три сезони, од Севиља.',
 'Од преселувањето во каталонската престолнина, Видал одиграл 49 натпревари за клубот.',
 'Протестот започна околу 11 часот по локално време (UTC+1) на Витезхајл спроти полицискиот обезбеден влез во Даунинг стрит, официјалната резиденција на премиерот.',
 'Веднаш по 11 часот, демонстрантите го блокираа сообраќајот на северната линија во Вестминстер.',
 'Во 11:20 часот, полицијата ги замоли демонстрантите да се вратат на тротоарот, наведувајќи дека им е потребно да го балансираат правото на протест со сообраќајот кој се создава.',
 'Околу 11:29 часот, протестот се премести на улицата Вајтхол, покрај Трафалгар Сквер, по улицата Стринд, покрај Алдвич и по улицата Кингсвеј кон Холборн каде Конзервативната партија го одржуваше својот пролетен форум во хотелот Гранд Коннагт Румс.',
 'Рекордот на Надал во директните дуели со Канаѓанецот е 7–2.',
 'Тој неодамна загуби од Раониќ на Отвореното првенство во Бризбејн.',
 'Надал освои 88% од вкупните поени во натпреварот, освојувајќи 76 поени на првиот сервис.',
 'По натпреварот, Кралот на глина рече: "Само сум возбуден што сум повторно во завршните кругови на најважните настани.',
 '"Панама документи" е општ термин за приближно десет милиони документи од Панамската адвокатска фирма Мосак Фонсека, кои беа протечени во медиумите во пролетта 2016 година.',
 'Документите покажаа дека четиринаесет банки им помогнале на богатите клиенти да сокријат милијарди долари богатство за да избегнат данок и други регулативи.',
 'Британскиот весник "Гардијан" сугерираше дека "Дојче банк" контролира приближно една третина од 1200-те шпекулативни компании коишто беа користени за да се оствари ова.',
 'Имаше протести низ целиот свет, неколку кривични постапки и лидерите на владите на Исланд и Пакистан поднесоа оставки.',
 'Роден во Хонг Конг, Ма студирал на Универзитетот во Њујорк и на Правниот факултет Харвард и некогаш поседувал американско постојано живеалиште "зелена карта".',
 'Хсиех имплицираше за време на изборите дека Ма може да избега од земјата за време на криза.',
 'Хсиех исто така тврдеше дека фотогеничната Ма беше повеќе стил отколку суштина.',
 'И покрај овие обвинувања, Ма победи убедливо на платформа која се залагаше за поблиски врски со кинескиот континент.',
 'Денешниот играч на денот е Александар Овечкин од Вашингтон Капиталс.',
 'Тој имаше 2 гола и 2 асистенции во победата на Вашингтон од 5-3 над Атланта Трашрс.',
 "Првата асистенција на Овечкин во текот на ноќта беше на победничкиот гол на дебитантот Никлас Бакстром;\nТекст:The first time I saw the movie, I was so excited that I couldn't stop laughing.",
 'Неговиот втор гол во вечерта беше неговиот 60-ти гол во сезоната, станувајќи првиот играч кој постигнал 60 или повеќе голови во една сезона од 1995-96, кога Џаромир Јагр и Марио Лемеј постигнаа таков подвиг.',
 'Батен беше рангиран на 190-то место на листата на 400 најбогати Американци во 2008 година со проценето богатство од 2,3 милијарди долари.',
 'Тој дипломирал на Факултетот за уметности и науки на Универзитетот во Вирџинија во 1950 година и бил значаен донатор на тој универзитет.',
 'Затворот Абу Граиб во Ирак е запален за време на бунт.',
 'Затворот стана познат по злоупотребата на затворениците откако американските сили го презедоа.',
 'Пикејт Јр.',
 'Кога возачите пред Алонсо влегоа во боксот за промена на гуми, тој се искачи напред во колоната и го освои првото место.',
 'Пикејт беше отпуштен по трката во Унгарија во 2009 година.',
 'Во точно 8:46 часот, во градот настана тишина, означувајќи го точниот момент кога првиот авион го погоди својот цел.',
 'Две зраци светлина се закачени да укажуваат кон небото преку ноќта.',
 'Се гради за пет нови облакодери на локацијата, со транспортен центар и парк за спомени во средината.',
 'Еми наградите на оваа емисија се повеќе од дваесет и неколку, а нејзината емисија е покуса само од онаа на Сезам улицата и на Мистер Роџерс.',
 'Секоја епизода од серијата ќе се фокусира на една тема во одреден роман и потоа ќе ја истражува таа тема преку повеќе приказни.',
 'Секоја емисија ќе содржи и препораки за книги кои децата треба да ги бараат кога ќе одат во својата библиотека.',
 'Џон Грант, од WNED Buffalo (домашниот станица на "Читањето Радува"), рече "Читањето Радува ги научи децата зошто да читаат, љубовта кон читањето — [емисијата] ги охрабри децата да земат книга и да читаат."',
 'Некои, вклучувајќи го и Џон Грант, веруваат дека и финансиската криза и промената во филозофијата на едукативната телевизиска програма придонесоа за завршувањето на серијата.',
 'Бурата, која се наоѓа околу 645 милји (1040 км) западно од Канарските острови, е веројатно дека ќе се распадне пред да загрози било кои копнени области, велат метеоролозите.',
 'Фред во моментов има ветрови со брзина од 105 милји на час (165 км/ч) и се движи кон северозапад.',
 'Фред е најсилниот тропски циклон кој некогаш бил регистриран толку јужно и источно во Атлантикот од појавата на сателитските снимки, и само третиот голем ураган на евиденцијата источно од 35°W.',
 'На 24 септември 1759 година, Артур Гиннес потпиша 9.000 годишен закуп за пиварницата Сент Џејмс Гејт во Даблин, Ирска.',
 'По 250 години, Џин-Џин еволуира во глобален бизнис кој годишно врти 10 милијарди евра (14.7 милијарди долари).',
 'Џони Рајд, ко-возач на тимот A1GP Нов Зеланд, денес направи историја со тоа што возеше најбрзо преку 48-годишниот мост преку пристаништето во Оукланд, Нов Зеланд, легално.',
 'Г-дин Рајд успеа да вози со брзина од над 160км/ч седум пати над мостот.',
 'Полицијата на Нов Зеланд имаше проблем да го користи радарот за брзина за да види колку брзо се движел г-дин Рајд поради тоа што коњот е многу низок, и единствено време кога полицијата успеа да го измери г-дин Рајд беше кога тој забави на 160 км/ч.',
 'Во последните 3 месеци, повеќе од 80 приведени лица беа ослободени од Централната канцеларија за притвор без да бидат официјално обвинети.',
 'Во април оваа година, привремена забрана за задржување беше издадена од судијата Глин против објектот да се спроведе ослободувањето на оние кои се држени повеќе од 24 часа по нивното примање кои не добиле сослушување од судијата комесар.',
 'Комисионерот поставува кауција, ако е одобрена, и ги формализира обвиненијата поднесени од страна на полицаецот кој го приведува.',
 'Судењето исто така го означува датумот за правото на обвинетиот на брзо судење.',
 'Питер Костело, австралискиот министер за финансии и човекот кој најверојатно ќе го наследи премиерот Џон Ховард како лидер на Либералната партија, ја поддржува индустријата за нуклеарна енергија во Австралија.',
 'Г-дин Костело изјави дека кога нуклеарната енергија ќе стане економски исплатлива, Австралија треба да ја истражи нејзината употреба.',
 '"Ако стане комерцијално, треба да го имаме.',
 'Според АНСА, "полицијата беше загрижена од неколкуте тешки удари кои ги сметаа за закана од почеток на војна за престол".',
 'Полицијата изјави дека Ло Пиколо имал предност бидејќи бил десна рака на Провензуро во Палермо и неговото поголемо искуство го добило почитта на постарите шефови додека го следеле политиката на Провензуро да бидат што е можно пониски додека ја зајакнуваат својата мрежа на моќ.',
 'Овие шефови биле потиснати од Провенцо кога тој го заврши војната против државата што ја водел Риина, која чинеше животи на мафијашките поборници Џовани Фалонче и Паоло Борселино во 1992 година.',
 'Извршниот директор на Apple, Стив Џобс, го претстави уредот со тоа што се појави на сцената и го извади iPhone-от од џебот.',
 'За време на неговиот 2 часовен говор тој изјави дека "Денес Apple ќе го реинвентира телефонот, ќе направиме историја денес".',
 'Бразил е најголемата католичка земја на Земјата, а Римокатоличката црква постојано се противи на легализацијата на истополовите бракови во земјата.',
 'Националниот конгрес на Бразил дебатира за легализација на истополовите бракови веќе 10 години, а такви цивилни бракови во моментов се легални само во Рио Гранде до Сул.',
 'Оригиналниот предлог-закон бил подготвен од поранешниот градоначалник на Сао Паоло, Марта Суплици.',
 'Протестантите се надеваат дека ќе соберат петиција со 1.2 милиони потписи за да ја достават до Националниот Конгрес во ноември.',
 'Потоа кога стана јасно дека многу семејства бараат правна помош за да се борат против иселувањата, на 20 март се одржа средба во East Bay Community Law Center за жртвите на измамата со домувањето.',
 'Кога станарите почнаа да споделуваат што им се случило, повеќето од семејствата вклучени одеднаш сфатија дека Каролин Вилсон од ОХА ги украла нивните депозити за безбедност и избегала од градот.',
 'Станарите на Локвуд Гарденс веруваат дека можеби има уште 40 семејства или повеќе кои ќе се соочат со протерување, откако дознаа дека полицијата на ОХА ги истражува и другите јавни згради за домување во Оукланд кои можеби се вклучени во измамата со домувањето.',
 'Бендот го откажа концертот во стадионот на Мауи, кој требаше да биде посетен од 9.000 луѓе, и се извини на фановите.',
 'Управувачката компанија на бендот, HK Management Inc., не даде првична причина кога го откажаа на 20-ти септември, но следниот ден ги обвинија логистичките причини.',
 'Познатите грчки адвокати, Сакис Кечагиоглу и Ѓорѓе Николоакопулос, биле затворени во затворот на Атина, Коридаллос, бидејќи биле прогласени за виновни за корупција и корупција.',
 'Како резултат на тоа, е подигната голема скандал во грчката правна заедница преку откривањето на незаконски постапки што ги направиле судиите, адвокатите, нотарите и адвокатите во текот на претходните години.',
 'Пред неколку недели, по објавувањето на информацијата од новинарот Макис Триантафилопулос во неговата популарна телевизиска емисија "Зоунгла" на Алфа ТВ, пратеникот и адвокат, Петрос Мантоувалос беше сменет од функцијата, бидејќи неговите соработници биле вклучени во нелегална корупција и корупција.',
 'Покрај тоа, највисокиот судија Евангелос Калусис е затворен бидејќи е осуден за корупција и девијантно однесување.',
 'Робертс категорично одби да каже кога тој верува дека животот започнува, важно прашање кога се разгледуваат етичките прашања поврзани со абортусот, велејќи дека би било нечесно да се коментира за конкретните случаи кои би можеле да се случат.',
 'Сепак, тој повторно ја истакна својата претходна изјава дека Roe v. Wade е "законот што е воспоставен во земјата", нагласувајќи ја важноста на конзистентните одлуки на Врховниот суд.',
 'Тој исто така потврди дека верува во имплицираното право на приватност кое зависеше од одлуката на Ро.',
 'Маручидор бил на врвот на табелата, шест поени пред Носа на второто место.',
 'Двете страни ќе се сретнат во големото полуфинале каде што Носа излезе како победник со 11 поени.',
 'Марјуридорден потоа го победи Кабултуре во Полуфиналната завршница.',
 'Хесперонохикус елизабетае е вид од фамилијата Дромаесаурид и е роднина на Велоцираптор.',
 'Ова целосно пердувести, топлокрвни предатори кои летаат беа верувани дека одеа исправено на две нозе со канџи како оние на Velociraptor.',
 'Неговиот втор прст беше поголем, што доведе до името Хесперонохикус, што значи "западен прст".',
 'Покрај топењето на мразот, екстремните временски услови го отежнуваат спасувањето.',
 'Питиман предложи дека условите нема да се подобрат до некое време следната недела.',
 'Количината и дебелината на ледената покривка, според Питман, е најлоша во изминатите 15 години за експедициите на морскиот леден покрив.',
 'Денес во заедницата на Црвеното езеро се шири веста за погребите на Џеф Вејс и тројца од деветте жртви, додека друг ученик беше уапсен во врска со пукањето во училиштето на 21 март.',
 'Официјално, властите потврдија дека денес е уапсен.',
 'Сепак, извор кој е запознаен со истрагата, за Minneapolis Star-Tribune изјави дека тоа бил Луис Џордан, 16-годишниот син на претседателот на племето Ред Лејк Флод Џордан.',
 'Не е познато во овој момент кои обвиненија ќе бидат поднесени или што ги довело властите до момчето, но почнати се постапките во федералниот суд.',
 'Лодин исто така рече дека официјалните лица одлучија да го откажат вториот круг од изборите за да ги заштедат Авганистанците од трошоците и безбедносните ризици на уште еден изборен процес.',
 'Дипломатите изјавија дека пронашле доволно двосмисленост во авганистанскиот устав за да го утврдат вториот круг како непотребен.',
 'Ова се спротивставува на претходните извештаи, кои велеа дека откажувањето на вториот круг би било против уставот.',
 'Авионот бил на пат за Иркутск и бил управуван од внатрешни единици.',
 'Еден истражен комитет беше формиран за да истражи.',
 'Ил-76 бил и останува важен дел од руската и советската војска од 1970-тите, а веќе имало сериозен инцидент во Русија минатиот месец.',
 'На 7-ми октомври, при полетување, еден мотор се одвоил без да има повредени.',
 '800 милји од Транс-Аљаска Пипелината беа затворени по истекување на неколку илјади барели нафта јужно од Фарбој, Аљаска.',
 'Поради редовен тест на системот за команда при пожар, дојде до прекин на струјата, што предизвика отворање на вентилите за ослободување притисок и нафтата се излеа во близина на пумпната станица 9.']

In [46]:
references = [[ref] for ref in text_mkd]
references[:10]

[['Во понеделникот научниците од медицинскиот факултет на Универзитетот Стенфорд објавија дека измислиле нова алатка за дијагностицирање со којашто се подредуваат клетките според типови: се работи за мал чип за печатење кој може да се произведе со помош на стандардни инк-џет печатачи, и тоа по цена од околу еден американски цент.'],
 ['Водечките истражувачи сметаат дека ова може да доведе до рано откривање на рак, туберколоза, ХИВ и маларија кај пациенти кои живеат во земји со низок животен стандард, каде стапката на преживување од болести како рак на дојка може да биде двојно пониска отколку во побогатите држави.'],
 ['JAS 39C Грипен се сруши на писта околу 9:30 am по локално време (2:30 UTC) и експлодираше, поради што аеродромот е затворен за комерцијални летови.'],
 ['Утврдено е дека пилот бил Дилокрит Патави, водачот на ескадрилата.'],
 ['Локалните медиуми известуваат за аеродромско противпожарно возило кое се превртело додека пожарникарите во него одговарале на повик.'],
 ['28-годишниот Видал од Севиља се придружи на екипата на Барселона.'],
 ['Откако се пресели во главниот град на Каталонија Видал одигра 49 натпревари за клубот.'],
 ['Протестот започна околу 11:00 часот по локално време (UTC+1) во Вајтхол, на спротивната страна од влезот чуван од полицијата на Даунинг Стрит, службената резиденција на премиерот.'],
 ['Веднаш по 11:00 часот демонстрантите го блокираа сообраќајот кон север во Вајтхол.'],
 ['Во 11:20 часот, полицијата побара од протестантите да повлечат на тротоарот, наведувајќи дека тие треба да ги урамнотежат правото на протестирање со застојот во сообраќајот.']]

In [47]:
bleu.compute(predictions=predictions_new, references=references)

{'bleu': 0.2722413045344638,
 'precisions': [0.5960979659609796,
  0.3412732784755305,
  0.22363060208239022,
  0.14983404457088667],
 'brevity_penalty': 0.9474659299204605,
 'length_ratio': 0.9487987396612839,
 'translation_length': 2409,
 'reference_length': 2539}

In [48]:
chrf_score = sacrebleu.corpus_chrf(predictions_new, references)
print(f"chrF: {chrf_score.score:.2f}")

chrF: 46.13